### ISSUE TITLE
Missing digits on scoresheets

### ISSUE THREAD

**Issue by Ilkyoo** [thewca/wca-regulations#101]
What do we do when some digits are missing (or illegible) on the scoresheet?

Give them a DNF? or assume the worst possible time?

Possible addition to the regulations or guidelines. 

The following is a suggestion by Stefan Pochmann:
A7c2) If a result is illegible or incomplete, it will be interpreted the worst possible way (e.g. "1:05" will be considered 1:05.99, and 1A.65 will be considered 19.65).

I have no preference on what happens, but I want to see something done so that it is clear which action to take by the delegate.

**Comment by lgarron** [comment]
What happens if someone writes 1:5.678 because some Stackmats are silly and
don't display the tens digit if it's 0?

(This could happen before, but an explicit specification about dealing with errors might make people think twice.)

**Comment by Ilkyoo** [comment]
According to the above, we will give them 1:59.67.
In most cases I imagine that the competitor will complain, and then we will find the judge and ask if he remembers.
This should both show the competitor and the judge to make sure that the missing 0 is written.

**Comment by lgarron** [comment]
Why should they complain? The judge writes _exactly what the timer says_, which is commonly what we tell them to do.
I would personally suggest to them to start putting a `0`, but it's not "wrong".

**Comment by Ilkyoo** [comment]
Sure.
But then shouldn't we change the phrasing of A7b1?

**Comment by lgarron** [comment]
Possibly. `1:5.678` is unambiguous if we assume there are no writing errors.

**Comment by Ilkyoo** [comment]
Isn't 1:5.678 ambiguous? It could be 1:50.678 or 1:05.678.

**Comment by lgarron** [comment]
Well, no. A Stackmat will display those as `1:50.678` and `1:5.678`, respectively.

**Comment by lgarron** [comment]
I also note that this has become more confusing since the new timers, Previously, `1:5.67` on a Gen 2 was sort of clear.
However, I would instinctively read a time like `1:5.678` as `1:56.78` for a while, because I was used to splitting the four digits after the colon in half..

**Comment by Ilkyoo** [comment]
I see, so there is no ambiguity with 1:5.678.
Also I agree that 1:5.678 vs 1:56.78 can be confusing, but there is nothing we can do in terms of regulations except to say be extra careful..

**Comment by lgarron** [comment]
I think the following approach is the most realistic:
- If a written result is unclear, the score taker should find the judge of the attempt to clarify it.
- If this is impractical, the score taker must interpret is as the worst possible valid result that can result from correcting or adding digits.

Concerns:
- I expect that we can't stop judges from writing 1:5.678 for some Stackmats (we could tell them, but "write down what it says on the timer" is all that some inexperienced judges will be able to retain). We need to make it clear what the score taker should do with that.
- How much effort should the score taker put in to find the judge? I want something that implies "best-effort" and "as soon as possible", but also allows them to make reasonable decisions on their own. (In particular, it's probably fine to interpret `1.3[A-ish]` as `1.38`, while `1[1 or 7].02` can benefit a lot more from asking the judge.)

**Comment by SAuroux** [comment]
A proposal being more clear to my mind as Stefan's one:

A7c2) Before signing, a competitor is supposed to check the recorded result for correct formatting, completeness and readability. If a result as signed by a competitor is found to be incomplete or unreadable, it will be interpreted the worst reasonable way (e.g. "1:05" will be considered 1:05.99, "1#.65" will be considered 17.65 if # is certainly either a 1 or a 7).

**Comment by pochmann** [comment]
The ", etc." and the "e.g." serve the same purpose, one of them can be
removed.

**Comment by SAuroux** [comment]
Indeed, fixed.

https://github.com/cubing/wca-documents/compare/missing-digits

**Comment by lgarron** [comment]
Rephrased in 5628fa5447587d876cf3d43e607ca69ecec6d148.
