### ISSUE TITLE
Preparing for Skewb as an official event for 2014

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#102]
I'm currently writing the proposal. It'll be completed by tomorrow.

**Comment by lgarron** [comment]
Relevant TODOs/links:
- [ ] [Skewb branch](https://github.com/cubing/wca-documents/compare/skewb)
- [ ] [TNoodle support](cubing/tnoodle#122)

**Comment by sarahstrong314** [comment]
Is there anything else that should be added to the skewb branch? I don't have anything more in particular to add to it.

**Comment by lgarron** [comment]
Hmm, the original Skewb proposal never made it here. For the record:

> Dear WCA Board, 
> 
> The WRC would like your approval for adding skewb as an official WCA event starting on January 1, 2014.
> 
> Here are the main reasons why we believe should be added:
> - There has been a high demand for adding skewb over the last few years, and there’s even more support for adding it now than there was before. A large portion of the speedcubing community has shown support toward adding it as an official event, and there have been many competitions since 2008 that have held skewb unofficially. Here are two threads in particular showing support from the speedsolving.com community:
>   - http://www.speedsolving.com/forum/showthread.php?28979-New-Event-ideas-(Poll)
>   - http://www.speedsolving.com/forum/showthread.php?43207-Skewb-will-be-an-Official-WCA-event?
> - Skewb stands out more than any other candidate that would add something new to the WCA (it is a deep-cut twisty puzzle). Other possible events that would being something new, such as Team BLD or helicube, either have logistical issues or lack support from the community.
> - It’s easy to learn and not too difficult to become fast at, so it should continue to grow in popularity.
> - It would cause no logistical problems at competitions, since scrambling is easy and it’s easy to determine misalignment penalties. Since it doesn't take much time to solve compared to most other puzzles, it would be a small burden on competition organizers, even for large competitions that hold every official event.
> - Singles will be fairly meaningless, but that should not prevent it from becoming an official event since lucky singles are inevitable with every fast puzzle, including many of our current events. Additionally, we can get TNoodle to filter scrambles with short solutions.
> 
> We have a draft of the Regulations to include skewb ready: https://github.com/cubing/wca-documents/compare/skewb
>
> I’ve shared it with several fast skewb solvers, including Brandon Harnish, Kris De Asis, and Christopher Wall, and they all agree that it should cover everything.
> 
> The other main thing that needs to be completed is integrating a random-state skewb scrambler with TNoodle. Chen Shuang has completed writing his scrambler, and is either finished or is currently working on displaying the images. You can view the progress here: https://github.com/cubing/wca-documents/compare/skewb#diff-0229c7701831da5cc3daf25b0120df24R325
> 
> We’d appreciate all members of the Board to express their opinions on adding Skewb as an official WCA event for 2014. If all members of the Board are on board, we’d like to publicly announce this to the cubing community as soon as possible since it’s already December.

(Sent by Sarah to the Board, 2013-12-04.)
