### ISSUE TITLE
Add definitions of attempt/solve from style guide

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#104]
https://github.com/cubing/wca-documents-extra/blob/master/style-guide.md#definitions

I would say to put this in the Guidelines, but I think it should be prominent enough in the Regulations.

**Comment by cubizh** [comment]
Please erase on the "Attempt:" definition line, the extra "to".

**Comment by lgarron** [comment]
Sure. I went ahead and fixed it: https://github.com/cubing/wca-documents-extra/commit/f1a2ea94fb610c6c9bb22296729c0ef313c23ce0

In the future, feel free to submit a pull request. They're pretty simple. ;-)
