### ISSUE TITLE
Remove reference to Competition Safety Policy

### ISSUE THREAD

**Issue by kr-matthews** [thewca/wca-regulations#1040]
The second sentence of regulation [Y2](https://www.worldcubeassociation.org/regulations/#Y1) makes reference to and provides a link to the Competition Safety Policy, which no longer exists.

**Comment by lgarron** [comment]
> The second sentence of regulation [Y2](https://www.worldcubeassociation.org/regulations/#Y1) makes reference to and provides a link to the Competition Safety Policy, which no longer exists.

Well, I don't love that https://www.worldcubeassociation.org/documents/policies/external/Competition%20Safety.pdf is a broken link. It'll still be referenced in old Regulations.
I don't know if removing the reference could warrant a mid-year Regulations update, but I'd be happy to review a PR.
