### ISSUE TITLE
No "Best of 3" for "Mean of 3" events

### ISSUE THREAD

**Issue by SAuroux** [thewca/wca-regulations#109]
# Proposal

**No "Best of 3" for "Mean of 3" events**
https://github.com/cubing/wca-documents/compare/no-best-of-3-for-mean-of-3
# Pro
- It doesn't seem to be desirable that an event from 9b2 is held with 3 attempts and rated with "Best of 3", when "Mean of 3" is possible and the preferred format.
# Cons

none.

**Comment by lgarron** [comment]
Arguably, the option could be useful. Could you get data on how often events have been held in each format in the last few years?

If few competitions have used "Best of 3" for a "Mean of 3" event, I think this change should be pretty uncontroversial.

**Comment by SAuroux** [comment]
As long as we clearly state "Mean of 3" as preferred format for these events, it is kind of contradictory that we allow "Best of 3" to be used.

There have never been such occurences for 6x6x6 or 7x7x7 so far. These are all occurences:

year    eventId COUNT(distinct Results.competitionId)
2005    333ft   1
2006    333ft   2
2007    333ft   1
2008    333ft   2
2010    333ft   2
2012    333ft   4
2013    333ft   3

SELECT Competitions.year, Results.eventId, COUNT(distinct Results.competitionId)
FROM Results INNER JOIN Competitions ON Results.competitionId=Competitions.id
WHERE (eventId="666" OR eventId="777" OR eventId="333ft") AND formatId="3"
GROUP BY Competitions.year, eventId

As a note, one should remember that "Best of 3" has been the preferred format for 3x3x3 with feet until 2013.

**Comment by lgarron** [comment]
```
SELECT Competitions.year, Results.eventId, COUNT(distinct Results.competitionId)
FROM Results INNER JOIN Competitions ON Results.competitionId=Competitions.id
WHERE (eventId="666" OR eventId="777" OR eventId="333ft") AND (formatId="m" OR formatId="3")
GROUP BY Competitions.year, eventId, formatId;
```

> ```
> +------+---------+---------------------------------------+
> | year | eventId | COUNT(distinct Results.competitionId) |
> +------+---------+---------------------------------------+
> | ...  | ...     |                                   ... |
> | 2012 | 333ft   |                                     4 |
> | 2012 | 333ft   |                                    80 |
> | 2012 | 666     |                                   114 |
> | 2012 | 777     |                                    99 |
> | 2013 | 333ft   |                                     3 |
> | 2013 | 333ft   |                                   103 |
> | 2013 | 666     |                                   134 |
> | 2013 | 777     |                                   139 |
> +------+---------+---------------------------------------+
> ```

That's only 3 out of 106 competitions: [CastellonOpen2013](https://www.worldcubeassociation.org/results/c.php?i=CastellonOpen2013&allResults=1#333ft) (3 feet competitors), [ColombiaTercer2013](https://www.worldcubeassociation.org/results/c.php?i=ColombiaTercer2013&allResults=1#333ft) (5 feet competitors), and [RybnikOpen2013](https://www.worldcubeassociation.org/results/c.php?i=RybnikOpen2013&allResults=1#333ft) (5 feet competitors).

I think this counts as uncontroversial.
