### ISSUE TITLE
Rule 9f1 implies truncation is similar to rounding

### ISSUE THREAD

**Issue by MFGookey** [thewca/wca-regulations#1106]
**Describe the typo**
The current text of the rule reads:
> 9f1) All timed results under 10 minutes, except for 3x3x3 Multi-Blind, are measured and truncated to the **nearest** hundredth of a second. All timed averages and means under 10 minutes are measured and rounded to the nearest hundredth of a second.

(Emphasis mine)
Truncation is closer to chopping off the least significant digits than adjusting a measurement to the nearest hundredth of a second.
Results of both `1.230` and `1.239` would be recorded as `1.23` when truncating, even though the nearest hundredth of a second to `1.239` is clearly `1.24`

**Possible solution**
Strike the word "nearest" from the text of the rule.  I have a branch with this change ready to go.

**Comment by MFGookey** [comment]
This is resolved by #1107

**Comment by lgarron** [comment]
I'd say the current wording is sufficiently accurate. If the time is 1.239, then truncating to the **nearest hundredth** is 1.23, as opposed to a different truncation like the **nearest tenth** (1.2 = 1.200) or **nearest second** (1 = 1.000). I'm not a huge fan of this wording, but my understanding is that it's pretty common.
That said, I agree that we could make this even more clear without too much trouble. I'll comment in the PR.
