### ISSUE TITLE
Mean of 3 for BLD *on the WCA website only*

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#111]
Proposal by Noah Arthurs, October 9:

> WCA Board,
> 
> I would like to propose that you add a world record and official rankings for 3x3 blindfolded averages. This is an issue that I am very passionate about as someone who takes blindfolded solving very seriously, and I hope that you will give serious consideration to my proposal. 
> 
> I am not asking that competitions be determined any differently (they would still be determined by single), but only that there be official rankings for 3x3 blindfolded averages, just as there are rankings for singles in other events where averages determine who wins a competition.
> 
> I made a thread about this topic on the speedsolving.com forum a little under a year ago: http://www.speedsolving.com/forum/showthread.php?39272-Should-official-3BLD-mo3s-be-ranked
> 
> Here I will give an expanded version of the arguments I made in the first post of that thread, with some additional points:
> 1. The world record single is at the point where even one of the fastest solvers would need a fairly lucky scramble in order to beat it. I know that this is true of many events (pyraminx, 2x2, 3x3 etc.), but in those events the WR average is generally considered to be more important. 3x3 Blindfolded does not have an average to fall back on, so the only record/ranking is quite based on luck.
> 2. Because of the luck element described above, competing in 3x3 blindfolded is often extremely frustrating for serious competitors. I go into every competition knowing that my ability to set a personal record has a lot to do with how easy the scrambles are for the event. Adding rankings for means would allow blindfolded solvers to have something to hope for other than a lucky scramble.
> 3. A mean of 3 is a better reflection of how fast a solver is than a good single. Although most of the 3x3 blindfolded single rankings are well deserved, there are plenty of examples of slower people overtaking faster people due to a lucky scramble. Again, this is not a problem in events that also have ranked averages, and would not be as much of a problem if 3x3 blindfolded averages were ranked.
> 4. It would add strategy and excitement to the 3x3 blindfolded event without removing any that is already there. Solvers would still be encouraged to go for fast times in order to win competitions, but they would also be encouraged get successes on scrambles that they can't get their best time on. I have had plenty of times where I have given up on a scramble or gone way faster than I should have because I knew that it didn't matter unless I beat the time that preceded it. For someone who has a PB single that they can't possibly beat due to a lucky scramble, ranked means would give them something new to go for.
> 5. In the thread on speedsolving.com, a few people argued that a reason for not ranking means is because not enough people have completed one successfully. I think most people can agree that this is not a valid argument to begin with, but I bring it up in order to point out one thing: one reason why not many people have gotten means is because of the lack of ranking for means. The current system encourages people to go for fast singles rather than averages, and so often times even fast people do not complete all three solves.
> 
> Honestly I cannot think of any reason why not to rank 3BLD means, and although it would be the only "best of" event to have ranked means, I don't think it would fundamentally change anything about competitions or the WCA. I find the luck-based elements of 3x3 blindfolded extremely frustrating, and I know that I am not the only blindsolver to feel this. I think that making this decision would make many people very happy, and would not have a negative effect on anyone.
> 
> Even if you do not accept my proposal, it will make me happy to know that you have considered it at the very least.

**Comment by sarahstrong314** [comment]
I'm in favour of this. It'd be more controversial if he were asking Mean of 3 to be the default format, but since all he's asking is for rankings to be shown for Mean of 3, I don't see any major issues.

**Comment by lgarron** [comment]
Support on speedsolving.com is looking strong: http://www.speedsolving.com/forum/showthread.php?39272-Should-official-3BLD-mo3s-be-ranked-(Read-the-first-post):
- 50 "yes" (or stronger)
- 18 "sure"
- 8 "no"

Would someone else on the WRC be willing to work with Noah to make an exact proposal and having the Board vote to approve it? I would strongly prefer this to be encoded in the Regulations, because it's still the only document for recording such conventions.

**Comment by lgarron** [comment]
# Proposal (December 26, 2013)

**For 3x3x3 BLD, recognize "Mean of 3" results from "Best of 3" rounds (on the WCA website only).**
https://github.com/cubing/wca-documents/compare/mean-bld-rank

## Pros and Cons
- See email by Noah Arthurs.
- In particular, this does not change the legal competition formats, so this gives us an interesting benefit without compromising the status quo.

## Community

From [the poll at the speedsolving.com thread](http://www.speedsolving.com/forum/showthread.php?39272-Should-official-3BLD-mo3s-be-ranked-(Read-the-first-post):
- Yes, I support this. 72 (57.60%)
- I think this is reasonable. 25 (20.00%)
- No. 12 (9.60%)
- Yes, and I _also_ think competitions should be able to rank BLD using mean of 3. 16 (12.80%)

Even though the poll was biased towards supportive choices (by trying to discern exactly what kind of support), there is clearly strong support for this. Although the proposal is new, there is evident community interest in this since years.
