### ISSUE TITLE
Examples in A7b1 use results recorded to 2 decimal digits instead of 3

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#1122]
**Describe the typo**
All legal timers mentioned in [7f1a](https://www.worldcubeassociation.org/regulations/#7f1a) display three decimal digits, so the examples should be written using three decimal digits.

> [A7b1](https://www.worldcubeassociation.org/regulations/#A7b1)) If penalties are assigned, the judge records the original recorded time displayed on the timer, along with any penalties. The format should be "X + T + Y = F", where X represents the sum of time penalties before/starting the solve, T represents the time displayed on the timer (the "original recorded time"), Y represents a sum of time penalties during/after the solve, and F represents the final result (e.g. 2 + 17.65 + 2 = 21.65). If X and/or Y is 0, the 0 terms are omitted (e.g. 17.65 + 2 = 19.65).

**Possible solution**
Change `2 + 17.65 + 2 = 21.65` to `2 + 17.650 + 2 = 21.650`, and change `17.65 + 2 = 19.65` to `17.650 + 2 = 19.650`.

**Comment by Nevseros** [comment]
[9f1](https://www.worldcubeassociation.org/regulations/#9f1) states that "all timed results... are **measured** and truncated to the nearest hundredth of a second", so I don't think we should change A7b1.

**Comment by sarahstrong314** [comment]
My understanding is that "measured" is referring to how the results are displayed as they are entered into live results and the results database. A7b1 uses the term "recording" instead of "measuring", which I believe is specifically refers to how the result is handwritten on the scorecard. The [Competitor Tutorial](https://www.worldcubeassociation.org/edudoc/competitor-tutorial/tutorial.pdf) also says that the judge should "[c]opy the time exactly as it is in on the timer", which would include the third decimal digit on all competition-legal timers.

**Comment by ohexter** [comment]
The WRC reviewed extensive Staff and Community feedback when selecting which topics to amend for the January 2025 WCA Regulations and Guidelines and chose not to make changes addressing this item. Previously raised items will not automatically be taken forward for consideration in future cycles so this issue has been closed. You are welcome to raise this topic again in a future cycle if desired.
