### ISSUE TITLE
Loophole in 9u phrasing

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#1123]
**Describe the typo**

It doesn't specify that 9u1 needs to be met before 9u2, meaning that if the Delegate announces that the competition is over before all the scheduled rounds are over, the competition would end exactly when the last attempt of the last round is completed. Based on 9u2a and 9u2b, I think it's clear that the intention is that 9u2 is meant to happen after 9u1.

> [9u](https://www.worldcubeassociation.org/regulations/#9u)) A competition is considered to have ended if all the following requirements are met:
> [9u1](https://www.worldcubeassociation.org/regulations/#9u1)) All the scheduled rounds in the WCA website are completed.
> [9u2](https://www.worldcubeassociation.org/regulations/#9u2)) The WCA Delegate announces the end of the competition. If the WCA Delegate does not announce the end of the competition, at least one of the following conditions are required:
> [9u2a](https://www.worldcubeassociation.org/regulations/#9u2a)) All the listed WCA Delegates permanently leave the venue.
> [9u2b](https://www.worldcubeassociation.org/regulations/#9u2b)) The end of the last calendar date of the competition is reached.

**Possible solution**
Reword 9u to make it clear that 9u1 needs to be met before 9u2.
> [9u](https://www.worldcubeassociation.org/regulations/#9u)) A competition is considered to have ended if all the following requirements are met **in the following order**:

**Comment by CarterKoala** [comment]
Is there an issue with this? I don't see a problem with the competition ending immediately once the last attempt is completed.

**Comment by sarahstrong314** [comment]
Since extra attempts cannot be given and missing signatures cannot be rectified once the competition is over, it doesn't seem desirable to end the competition exactly when the last attempt is done. There would be little or no time for competitors in the last group to raise an issue that could resolve in an extra or provisional extra, and score takers wouldn't have time to catch missing signatures for scorecards that haven't been delivered yet.

**Comment by CarterKoala** [comment]
If an extra attempt needs to be given, then the round isn’t over :p 

As for checking for missing signatures, this will be an issue if you announce the competition is over before all data is entered regardless of whether or not that is announced before the round finishes or not.

If we really wanted to fix the signing scorecard thing, then we could maybe add another requirement that all data is entered, but I think that is pretty unnecessary. If you want to avoid that as a delegate and give competitors more time, then IMO just don’t announce the comp is over until you give competitors the time you want to give them.

**Comment by sarahstrong314** [comment]
I agree that Delegates should announce that the competition is over at a reasonable time, however I find it bizarre that if a Delegate accidentally announces the competition is over before the final round is over there isn't a safeguard to negate the domino effects of the announcement. Suppose for example that a Delegate says "the competition is over" out of habit at the end of the first day of a multi-day competition. I believe it's fairly reasonable to want to prevent this from triggering 9u2 and the fix is as simple as adding a few words to 9u.

**Comment by Nanush7** [comment]
What do you think about the proposed change @sarahstrong314 ?
