### ISSUE TITLE
Review A6b threshold of 0.06

### ISSUE THREAD

**Issue by JonEsparaz** [thewca/wca-regulations#1124]
As far as I can tell, the 0.06 threshold in A6b was introduced more than 10 years ago (when Gen 2 timers were mainly used). I am curious if we have data or evidence that supports a time strictly below 0.06 being indicative of a malfunction on Gen 3, 4, and 5 timers.

I would push for removing A6b1 (automatic extra if the timer "malfunctions" to a time strictly below 0.06). I've seen other types of timer malfunctions that are reproducible (these should of course warrant extra attempts), but never a timer that consistently malfunctions to a time strictly below 0.06 seconds. My theory is that times below 0.06 are due to an extremely nervous competitor's hands shaking as they start the timer, which causes them to accidentally stop the timer.

**Comment by xsrvmy** [comment]
There was a very weird malfunction with a Gen 4 (IIRC) at one of our Ontario comps once where the timer was stopping without the competitor making full contact with the timer. IIRC that incident actually resulted in two DNFs over .06 which lead to E2 being given.

**Comment by Nevseros** [comment]
To add, I've seen quite a lot of malfunctions on Gen 4, when the timer stopped itself at 0.1*, but I rarely saw malfunctions with the time below 0.06 too.

**Comment by ohexter** [comment]
The WRC reviewed extensive Staff and Community feedback when selecting which topics to amend for the January 2025 WCA Regulations and Guidelines and chose not to make changes addressing this item. Previously raised items will not automatically be taken forward for consideration in future cycles so this issue has been closed. You are welcome to raise this topic again in a future cycle if desired.
