### ISSUE TITLE
Guideline 9q+

### ISSUE THREAD

**Issue by asto1001** [thewca/wca-regulations#1128]
**Describe the typo**
Guideline 9q+ exists but does not correspond to a regulation 9q.

**Possible solution**
Integrate Guideline 9q+ into another relevant article 9 Regulation such as 9p.

**Comment by Nanush7** [comment]
In the past, this guideline was Regulation 9q. https://www.worldcubeassociation.org/regulations/history/files/regulations2010.html#events

Having guidelines for removed regulations is not an issue (except for additions). However, I agree that this particular guideline is not very useful, so I think we should remove it. @thewca/wrc-team

**Comment by Nevseros** [comment]
I don't agree, I think we should keep it.

**Comment by ohexter** [comment]
The WRC reviewed extensive Staff and Community feedback when selecting which topics to amend for the January 2025 WCA Regulations and Guidelines and chose not to make changes addressing this item. Previously raised items will not automatically be taken forward for consideration in future cycles so this issue has been closed. You are welcome to raise this topic again in a future cycle if desired.
