### ISSUE TITLE
2i+ leniency 

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#1130]
> [2i+ 1](https://wcaregs.netlify.app/#2i+) Although the competitor may pick up a stopwatch to view the current time (when they are not blindfolded), they must not start, stop, pause, or otherwise interact with the timekeeping of the stopwatch.

At my most recent competition, we had 2 competitors during 4bld that ended their attempts and didn’t see any judge to their side to stop the timer. Panicking, both competitors ended up stopping their own stopwatches to avoid having extra time added to their results. Unfortunately, this resulted in a DNF penalty for both attempts (even though the puzzles were solved) even though there was no doubt that the results achieved were legitimate. I think that it would be beneficial to adjust this regulation to allow for greater leniency (such as allowing the penalty to be at the discretion of the WCA Delegate if the result is suspected to be accurate).

In one of these instances, a judge was walking towards the competitor in order to stop the stopwatch, but the competitor stopped it themselves before the judge made it to them. I think a specific guideline giving an example of a judge/delegate watching the competitor stop the stopwatch could be a good addition as well.

**Comment by Samuel-Baird** [comment]
Update, the WRC ruled that the attempts I mentioned, which received a DNF penalty, should have no penalty applied. This regulation will be updated in a future regulations cycle to reflect that ruling

**Comment by ohexter** [comment]
Addressed [here](https://github.com/thewca/wca-regulations/pull/1244/files), will be deployed January 1st, 2025.
