### ISSUE TITLE
Expand the scope of 1c 

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#1131]
> 1c The WCA Delegate is responsible for ensuring that the competition adheres to the WCA Regulations and any applicable WCA policies or requirements. The WCA Delegate may appoint other members of the **organization team** to carry out specific responsibilities on their behalf, but is ultimately accountable for how these responsibilities are carried out.

I think that 1c can be super helpful but currently has an overly narrow scope for how it can be applied. I think it would be great to modify the wording to include more people than just members of the organization team. 

In my local region we are now running 2-3 stages per competition and often use Delegates, organizers, and other experienced competitors to act as “stage leads” who oversee their stages and make sure that everything keeps running smoothly. Some of these stage leads frequently organize competitions and are experienced competitors, but we cannot allow them to handle basic incidents that require “Delegate calls” because they are not listed organizers.

In some instances, it may not be possible to have a Delegate oversee a room/the competition itself. For example, if a delegate acted as the sole organizer of a PBQ and was competing in 5bld, then it causes a problem if anyone needs an extra. A Delegate could appoint a trusted competitor to “act as a Delegate” while the delegate is competing.

**Comment by Nevseros** [comment]
Organization team != listed organizers. See [1a](https://www.worldcubeassociation.org/regulations/#1a).

Closing as irrelevant.
