### ISSUE TITLE
Change 9f2 from rounding to truncation

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#1132]
> 9f2 All timed results, averages, and means over 10 minutes, as well as all times for 3x3x3 Multi-Blind results, are measured and rounded to the nearest second (e.g. x.49 becomes x, x.50 becomes x+1).

Most stopwatches that I have seen used in competitions do not track centiseconds after 10 minutes but rather only track hours, minutes, and seconds. I think it could be argued that these stopwatches are illegal and shouldn’t be used but I believe changing this regulation to use truncation of centiseconds rather than rounding would be a reasonable enough change. The current rounding system already doesn’t fully value the accuracy of times (a .01 difference in times can be treated the same as a .99 difference in times) so I believe that this system wouldn’t affect too much in terms of accuracy. Having a result ~1 second faster than it actually took (ex. 11:00.99 vs 11:00.00) is fairly insignificant in the 10-minute to 1-hour range.

**Comment by ohexter** [comment]
Agree. This change would make the regulations simpler and more consistent. I have also seen 9f2 misapplied in practice on multiple occasions and suspect this is widespread.

**Comment by ohexter** [comment]
Addressed [here](https://github.com/thewca/wca-regulations/pull/1259), this will be deployed January 1st, 2025.
