### ISSUE TITLE
Rename the event “3x3x3 Multi-Blind”

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#1133]
Discussed in [this WCA forum post](https://forum.worldcubeassociation.org/t/rename-the-event-3x3x3-multi-blind/5050)

As pointed out by @Pedro_Santos_Guimara, “3x3x3 Multi-Blind” perhaps not might be the best name for the event.

Usually, in the Regulations, we use “blind” in the context of “blind competitors” (3d1a) or “color blind competitors” (3d1b). When talking about events where a competitor has to wear a blindfold, we use the them “blindfolded” (e.g. 3x3x3 Blindfolded, 4x4x4 Blindfolded, 5x5x5 Blindfolded).

From what I could tell, the event got this version of its name after this 5 commit on the Regulations GitHub that came in the wave of removing the mention of “Rubik’s Cube” of WCA Documents in general. It was changed from “Rubik’s Cube: Multiple Blindfolded” to "3x3x3 Multi-Blind.

Possibly it would be in the best interest of the consistency of the Regulations and for the professional tone it should convey to change the name of the event “3x3x3 Multi-Blind”.

A good proposal is to change it to “3x3x3 Multi-Blindfolded”, making it consistent with the rest of the Regulations.

How does the WCA Community and Staff feel about this change?

**Comment by mintydev789** [comment]
I personally feel like Multi-Blind works well. The dash makes it clear that it's a special name and has no connection to blindness, imo. I think we should keep it as is. I also always write team blindfolded as "3x3x3 Team-Blind", using the same idea as Multi-Blind, and I think it works well.

**Comment by mintydev789** [comment]
Also 3x3x3 Speed-Blind can use the same naming convention. So yeah, I'd definitely leave it unchanged.

**Comment by Samuel-Baird** [comment]
@dmint789 I think all the blind events end up getting shortened to blind/bld in casual conversation (ex. 3 blind, 4bld 5) in the same way that I’ve heard square-1 shortened to sq-1/sqone, big cubes referred to as 5, 6, and 7, 3x3 one-handed referred to as OH, 3x3 fewest moves referred to as FMC, and pyraminx referred to as py/pyra. As a result, it’s not a surprise that team blindfolded and speed blindfolded would both have their names abbreviated to blind as well. But ultimately, we probably shouldn’t be naming official events based off of unofficial events. 

If you look at most records for blindfolded events on YouTube the names are all “Rubik’s cube blindfolded” as it’s clearer to a non-cubing audience that they are solving 3x3’s blindfolded. In the case of multiblind, if I told a non-cuber that I was going to compete in Rubik’s cube multi-blind vs Rubik’s cube multiple blindfolded then I believe the latter would be much clearer. 

Since 3x3 multiple blindfolded is a lot clearer as to what the event actually is, has a history of being used in the WCA, and follows a more consistent naming scheme with other events I would personally be more in favor of it.

**Comment by mintydev789** [comment]
I don't think what we use to communicate the events to non-cubers is a particularly strong argument. By that same logic the 3x3x3 Cube event should be renamed to Rubik's Cube (which is a bad idea).

I think Multi-Blind works well as a name, and even if we rename it to Multiple Blindfolded, that would still require explanation almost every time. As for Team-Blind, I've personally never heard it referred to as Team Blindfolded (or very rarely at best), but I _will_ concede that it's not a good argument to go off of unofficial event names.

**Comment by Samuel-Baird** [comment]
> I don't think what we use to communicate the events to non-cubers is a particularly strong argument. By that same logic the 3x3x3 Cube event should be renamed to Rubik's Cube (which is a bad idea).

We used to call it Rubik's Cube but moved away for a few reasons which wouldn't apply here

> As for Team-Blind, I've personally never heard it referred to as Team Blindfolded (or very rarely at best), but I will concede that it's not a good argument to go off of unofficial event names.

I have heard both team blind and team blindfolded used, although team blind is definitely more common. CubingUSA reffered to it as team blindfolded at [USA nationals](https://www.cubingusa.org/nationals/2023/unofficial), as did [Calix Tang and Tommy Cherry's video](https://www.youtube.com/watch?v=tlgl8GMtsvg&pp=ygUWdGVhbSBibGluZCBydWJpa3MgY3ViZQ%3D%3D) from nationals.

**Comment by ohexter** [comment]
The WRC reviewed extensive Staff and Community feedback when selecting which topics to amend for the January 2025 WCA Regulations and Guidelines and chose not to make changes addressing this item. Previously raised items will not automatically be taken forward for consideration in future cycles so this issue has been closed. You are welcome to raise this topic again in a future cycle if desired.
