### ISSUE TITLE
Change in wording of 2j

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#1134]
> 2j The WCA Delegate may disqualify a competitor from specific attempts and/or events.

2k already covers this, a minor wording change could be helpful for 2j to make sense (since the sub-regulations for 2j should definitely be kept, it shouldn't be removed)

"If a competitor is disqualified from an event, the following regulations apply:"

**Comment by CarterKoala** [comment]
We talked through this, and determined it was not really necessary as there isn't any issue with how it is currently worded, since 2j and 2k talk about different things
