### ISSUE TITLE
Allowing non-similar pieces for clock

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#1135]
Currently, the regulations do not allow clocks to have non-matching edges, corners, and center pieces on the same face as per 3j and 3j2+ which includes color.

I would like to see this relaxed to allow non-similar pieces on the clock; including allowing checkerboard 10 puzzles and ignoring differing colors, patterns, and images on pieces.

While this may be advantageous in making it easier for orientation-neutral solvers to find their orientation, the legalization of customizable inserts 3 already allows this.

As long as it is clear where the dials are pointing and the 12 o’clock markings are clear then there should be no problems with allowing such a puzzle to be permitted.

**Comment by Nevseros** [comment]
You are using older version of the Regulations and Guidelines, this has been fixed in 2023-02-01 Regulations and Guidelines version (see [3h4b](https://www.worldcubeassociation.org/regulations/#3h4b), for example).
