### ISSUE TITLE
A6b+ should be A6b1+

### ISSUE THREAD

**Issue by OJCubing** [thewca/wca-regulations#1142]
[A6b](https://wcaregs.netlify.app/#A6b)) The competitor is responsible for stopping the Stackmat timer correctly.
[A6b1](https://wcaregs.netlify.app/#A6b1)) If the timer stops before the competitor has solved the puzzle and the timer shows a time strictly below 0.06 seconds, then the attempt is replaced by an extra attempt. A competitor forfeits the right to the additional attempt if the WCA Delegate determines that the timer was stopped deliberately.

[A6b+](https://wcaregs.netlify.app/#A6b+)) EXPLANATION The arbitrary value of 0.06 seconds was chosen to accommodate concerns about Stackmat timer malfunctions.

This guideline pertains to A6b1, not to A6b. Arguably it also pertains to [A6b2](https://wcaregs.netlify.app/#A6b2) as well, but only as a direct result of A6b1, which is much more applicable.

**Comment by ohexter** [comment]
Addressed [here](https://github.com/thewca/wca-regulations/pull/1232), this will be deployed January 1st, 2025.
