### ISSUE TITLE
Regulations about rounds being cancelled or additional rounds being added while the competition is in progress

### ISSUE THREAD

**Issue by benwh1** [thewca/wca-regulations#1143]
While looking through the recent changes, I noticed a potential issue in 9u):

```
- 9u) A competition is considered to have ended if all the following requirements are met simultaneously:
    - 9u1) All the scheduled rounds in the WCA website are completed.
    - 9u2) The WCA Delegate announces the end of the competition. If the WCA Delegate does not announce the end of the competition, at least one of the following conditions are required:
        - 9u2a) All the listed WCA Delegates permanently leave the venue.
        - 9u2b) The end of the last calendar date of the competition is reached. 
```

Making the assumption that a round can not be "completed" if it never starts, 9u1) implies that if a round is cancelled during the competition (e.g. due to falling behind schedule) and the schedule on the WCA website is not edited to reflect the cancellation, then the competition never ends.

Based on this, I think it would be a good idea to add some regulations about cancelling rounds or adding new rounds (e.g. due to being ahead of schedule) while a competition is in progress, as there is currently no information about these situations.

**Comment by Nanush7** [comment]
If a round is dropped during the competition, the WCA Delegate must change the schedule and events information in the WCA website before submitting the results to the WRT.
