### ISSUE TITLE
Change "Rubik's Cube" to "3x3x3 Cube"?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#115]
Does Seventowns care either way?

It would make the Regulations more consistent. However, it takes away from portraying us as the official organization for the _Rubik's Cube_ and similar puzzles.

(To keep in mind: The results pages say "Rubik's Cube".)

**Comment by SAuroux** [comment]
While indeed reasonable, this is definitely "controversial" and more than a simple change. 

If you care enough about this, you should mail the Board for discussion asap.

**Comment by lgarron** [comment]
This is definitely "if it ain't broke, don't fix it".

I don't think there's a place where it causes particularly much trouble, but it came to mind when I was trying to fix [E3b](https://github.com/cubing/wca-documents/commit/ea61e56c0be61b075c3d1d87fddad0b961e2f33d). Pedro [suggested "3x3x3 cubes"](https://github.com/cubing/wca-documents/issues/77), but that would have been inconsistent with the rest of the Regs. I opted to include a tentative E3b+ just to make sure that competitors won't try to bring a 4x4x4 into FMC and argue that it counts as a "Rubik's Cube".

**Comment by Laura-O** [comment]
This was discussed again when we changed the order of the events last year. The suggestion using "Rubik's Cube" won, so I think it's reasonable to use this term in regulations as well.
