### ISSUE TITLE
Change instances of “Citizenship” and “Country” to “Representing” and “Region” (2e)

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#1150]
In order to have the regulations reflect the recent changes made to how Hong Kong, Macau, and Taiwan are recognized, [2e](https://www.worldcubeassociation.org/regulations/#2e) needs some updated wording.

> [2e](https://www.worldcubeassociation.org/regulations/#2e)) Competitors must represent a country of which they hold citizenship. The WCA Delegate should verify citizenship by means of documents (e.g. a passport) at their first competition. If a competitor is found ineligible to represent the country under which they have registered, the competitor may be disqualified retroactively and/or suspended, at the discretion of the WCA Board.

Instances of “citizenship” and “country” will need to be replaced by words such as “representing” and “region”. This follows some [recent updates to the website](https://github.com/thewca/worldcubeassociation.org/pull/8166).

**Comment by Nanush7** [comment]
I think just "representing" is broader than a citizenship. Someone with a legal residence would be allowed to represent a region? Also, which is the legal citizenship of the competitors in such regions? Do they hold a Chinese citizenship?

I agree it would make sense to change "country" to "region", though.

**Comment by Samuel-Baird** [comment]
> I think just "representing" is broader than a citizenship. Someone with a legal residence would be allowed to represent a region? Also, which is the legal citizenship of the competitors in such regions? Do they hold a Chinese citizenship?
> 
> I agree it would make sense to change "country" to "region", though.

That definitely is difficult, the introduction of regions into the WCA definitely makes things harder to define…
