### ISSUE TITLE
Adding a Guideline for time schedules

### ISSUE THREAD

**Issue by SAuroux** [thewca/wca-regulations#116]
https://github.com/cubing/wca-documents/compare/time-schedules

It is important to have the need for time schedules mentioned at least somehwere in our documents.

**Comment by lgarron** [comment]
So we don't want to consider this as part of the competition announcement, right?

**Comment by SAuroux** [comment]
Exactly. We don't use to do this, as it is not reasonable to expect a very
detailed schedule when the competition is anounced in general.

For individual cases, the Board still has the power to require things like
that if needed.

2013/12/11 Lucas Garron notifications@github.com

**Comment by operge** [comment]
I think 2 weeks should also work. For someone planning to attend an official competition abroad, for logistics reasons, 2 weeks should be at least. Also, for the same reason, a requirement for english version wouldn't be a bad idea.
