### ISSUE TITLE
Guideline 5c+ does not belong to a regulation

### ISSUE THREAD

**Issue by coder13** [thewca/wca-regulations#1178]
![image](https://github.com/thewca/wca-regulations/assets/881394/9b9067bb-b9d5-4fdb-87b5-be5b53228ba9)

![image](https://github.com/thewca/wca-regulations/assets/881394/1aecb0a9-3c2b-4c87-809a-a83e9286bfdd)

**Comment by lgarron** [comment]
As mentioned in https://github.com/thewca/wca-regulations/issues/1179#issuecomment-1793991107 , this is not an issue in itself. There is no need for a Guideline number to match up to a Reg. In this case, the Guideline used to be Regulation 5c) and has been moved to 5c++).

I think it would be less disruptive to keep it as-is, although there isn't anything stopping us from renumbering it (e.g. to 5b++) either.

**Comment by ohexter** [comment]
The WRC reviewed extensive Staff and Community feedback when selecting which topics to amend for the January 2025 WCA Regulations and Guidelines and chose not to make changes addressing this item. Previously raised items will not automatically be taken forward for consideration in future cycles so this issue has been closed. You are welcome to raise this topic again in a future cycle if desired.
