### ISSUE TITLE
Guideline 9q+ does not belong to a regulation

### ISSUE THREAD

**Issue by coder13** [thewca/wca-regulations#1179]
![image](https://github.com/thewca/wca-regulations/assets/881394/1440681f-b50d-4b08-8320-c08320860688)

![image](https://github.com/thewca/wca-regulations/assets/881394/22801f5d-d91f-422f-8f3f-af72fefbdba3)

**Comment by Nanush7** [comment]
Thank you for the report! :)

Sometimes we keep guidelines for regulations that have been removed (when such guidelines do not fit in another regulation). Anyway, I think 9q+ is not really necessary anymore. @thewca/wrc-team

**Comment by hanwu85** [comment]
I agree, we should delete this one.  
The related regulations were moved to WCRP and it is a contradiction.

**Comment by Nevseros** [comment]
Why should it refer to anything? I think this is a good guideline to remind people that competition is not a competition if nobody **competes**.

**Comment by Nanush7** [comment]
It is about events and rounds. There isn't really a difference between 1 and 2 competitors for a specific event (i.e 5BLD, which is unpopular in some regions). The guideline is kind of hidden and I do not think it changes anything or adds valuable information.

**Comment by ohexter** [comment]
The WRC reviewed extensive Staff and Community feedback when selecting which topics to amend for the January 2025 WCA Regulations and Guidelines and chose not to make changes addressing this item. Previously raised items will not automatically be taken forward for consideration in future cycles so this issue has been closed. You are welcome to raise this topic again in a future cycle if desired.
