### ISSUE TITLE
FMC ranking system

### ISSUE THREAD

**Issue by bcube2** [thewca/wca-regulations#1192]
Maybe this is a better place to ask: https://www.speedsolving.com/threads/fmc-ranking-system.91848/#post-1582250

**Comment by bcube2** [comment]
By "this" I meant github. So, anyone?

**Comment by OtaMota** [comment]
I think https://forum.worldcubeassociation.org/ Would be a better place to discuss it, as more discussion happens there, and more common folks can access it.

**Comment by Nevseros** [comment]
If anyone wants to start the discussion on this, please do it using the WCA Forum, not GitHub. Thank you!
