### ISSUE TITLE
[Suggestion] Improve E2c1 and guidelines

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#1195]
After a recent incident on this topic (FM solution sheet missing competitor's name), some fellow delegates and I have been reflecting about it and believe the current regulations and corresponding guidelines could be improved.

## Current situation
Currently it says: (highlights by me)
>[E2c](https://www.worldcubeassociation.org/regulations#E2c)) At 60 minutes, each competitor must submit to the judge a single piece of paper with a written solution and **information to identify the attempt**.
[E2c1](https://www.worldcubeassociation.org/regulations#E2c1)) Information to identify the attempt is: **the competitor's name, WCA ID, or competition registrant ID (at least one, optionally multiple)**, and optionally the competition name, round, or attempt number. **Penalty for a submitted solution without name**, WCA ID, or competition registrant ID: **disqualification of the attempt (DNF)**.

>[E2c1++](https://www.worldcubeassociation.org/regulations/guidelines.html#E2c1++)) [ADDITION](https://www.worldcubeassociation.org/regulations/#E2c1) If the **competitor forgot to write information to identify** the attempt on their intended solution paper, they are **permitted to add it in front of a judge after the time limit**. In this case, the **_competitor must ask the judge while submitting their solution_** and then immediately write information to identify the attempt (without making other changes) under direct supervision of the judge. Once a **competitor has finished submitting their solution** (e.g. placing it in the judge's hands and allowing the judge to move on to the next competitor, placing it on the judge's table and walking away), they are **not permitted to add any information**. If the competitor writes anything after the time limit but before asking the judge, the attempt remains disqualified (DNF).
[E2c1+++](https://www.worldcubeassociation.org/regulations/guidelines.html#E2c1+++)) [EXPLANATION](https://www.worldcubeassociation.org/regulations/#E2c1) The competitor is not required to write the competition name, round, and/or attempt number on their submitted paper, but may wish to do so in order to help the organization team keep track of submitted solutions.
[E2c1++++](https://www.worldcubeassociation.org/regulations/guidelines.html#E2c1++++)) [ADDITION](https://www.worldcubeassociation.org/regulations/#E2c1) If a **judge finds a submitted solution without information to identify** the attempt (e.g. while grading the attempt), they **should find out the competitor who wrote the solution in order to assign them a DNF** (rather than DNS). Note that the **competitor must not be allowed to write information to identify the attempt at this point, so they must receive a DNF result**.

## Issue description and thoughts
Maybe the idea behind E2c1++ was to help the competitors by giving them a chance to write their name in case they have forgotten it, but as it is worded now, it doesn't help much (or at all). If the competitor forgot to identify their solution, it's very unlikely that they will remember about it **while delivering** the paper.
It would make more sense that the judge should check right away if the submitted solution is identified and give the competitor a chance to write their name in case it's missing.

While this may seem like a minor issue (and I believe it doesn't happen very often), it can have a big impact on competitors and their perception of a fun and fair environment. I'm not sure how it works in other places, but here if a school test is missing a name, the student won't get a zero grade for it.

Some may argue that this would not be practical for large competitions, but that doesn't seem to be the case. Even if there are many competitors, it's not expected that a big number of sheets will be missing a name. It's not hard to track down the person and fix it. We even have E2c1++++ (which I must confess I wasn't familiar with) that says the judge should find the competitor - only to give them a DNF. Eventhough it's a should, it would make more sense - at least in my view - to find the person and verify that the sheet is theirs, allowing them to have their result counted.
This would be similar to A7c5, which allows missing signatures on a score sheet to be added later, at the discretion of the Delegate.

Also, large competitions with FM will (or should) have more people judging/supervising the event, so it wouldn't be a burden to quickly check for missing names upon solutions' submissions.

I have compiled some data on FM competitions (see at the end), and found that out of the 2.842 competitions with the event, 2.361 (83,08%) had 25 competitors or less. Another 10% had between 26 and 35. Only 86 competitions (3%) had more than 50 people, and that includes 19 multi-location competitions, which usually don't have many competitors at the same place.

## Proposal
So the proposal would be to update E2c1++ and E2c1++++ to the following (added parts are in bold):

>E2c) At 60 minutes, each competitor must submit to the judge a single piece of paper with a written solution and information to identify the attempt.
E2c1) Information to identify the attempt is: the competitor's name, WCA ID, or competition registrant ID (at least one, optionally multiple), and optionally the competition name, round, or attempt number. Penalty for a submitted solution without name, WCA ID, or competition registrant ID: disqualification of the attempt (DNF).

>E2c1++) ADDITION **The judge should check the submitted solution paper for missing identification.** If the competitor forgot to write information to identify the attempt on their intended solution paper, they are permitted to add it in front of a judge after the time limit. In this case, the competitor must ask the judge ~while submitting their solution~ and then immediately write information to identify the attempt (without making other changes) under direct supervision of the judge. ~Once a competitor has finished submitting their solution (e.g. placing it in the judge's hands and allowing the judge to move on to the next competitor, placing it on the judge's table and walking away), they are not permitted to add any information.~ If the competitor writes anything after the time limit ~but before asking~ **without permission from** the judge, the attempt remains disqualified (DNF).
...
E2c1++++) ADDITION If a judge finds a submitted solution without information to identify the attempt (e.g. while grading the attempt), they ~should~ **may** find out the competitor who wrote the solution **and identify it, at the discretion of the WCA Delegate.** ~in order to assign them a DNF (rather than DNS). Note that the competitor must not be allowed to write information to identify the attempt at this point, so they must receive a DNF result~.

Differences: https://www.diffchecker.com/cyYPv4BP/

## Appendix
Data on FM competitions:
![image](https://github.com/thewca/wca-regulations/assets/1881933/8ce7dc20-f519-4cc5-810b-ea03ae89d49c)

SQL script:
```
select competitionId, Competitions.countryId, count(distinct personId) competitors, delegates
from Results 
join Competitions on Competitions.id = Results.competitionId
join (select competition_id, count(delegate_id) delegates
from competition_delegates
group by competition_id
order by delegates desc) delegados on delegados.competition_id = Competitions.id
where eventId = '333fm'
group by competitionId, countryId
order by competitors desc
```

**Comment by ohexter** [comment]
Addressed [here](https://github.com/thewca/wca-regulations/pull/1264/files), will be deployed January 1st, 2025.
