### ISSUE TITLE
[Proposal] Modify A7c4 to add leniency for first-time competitors

### ISSUE THREAD

**Issue by khkellis** [thewca/wca-regulations#1196]
proposal sent directly to WRC via Google Form; also posting here for visibility.

**What are your proposals for new regulations?**

Allow for retroactive scorecard signing for new competitors with video evidence.

**What changes do you want to see implemented to existing regulations?**

Similar to A7g for incidents found at the competition, modify A7c4 to allow first-time competitors to retroactively sign a scorecard if found to be unsigned after a competition, provided they have credible video evidence at delegate discretion.

As I discuss in the "NxNaperville 2022" thread, some of the considerations that should be outlined in the Guidelines:

"When it comes to how "reasonable and fair" is defined, I think we should refer to the delegate at the competition to gauge the situation, while offering some factors for that delegate to consider, such as:

1. Competition experience. This was <competitor's> first competition, and presumably is less familiar with competition rules than seasoned competitors.
2. Age. <Competitor> is 8 years old, and presumably younger children may forget administrative processes such as scorecard signing.
3. Evidence. <Competitor's> parent is able to produce evidence presumably (i) with the judge that signed the scorecard (ii) at the competition venue (iii) using the exact scramble, (iv) whilst other solves are also going on.
4. Timeframe of evidence proposal. Presumably, <competitor's> parent submitted evidence within a reasonable window after being asked about the result."

**Why do you want these changes to be implemented? Have you noticed any drawback to your proposals?**

See the discussion on the "NxNaperville 2022" thread. There is video evidence that an 8-year-old first-time competitor achieved a time of 12.13 on his final solve of his average, but he forgot to sign. The competitor's parents brought up video footage, with the intention of verifying the time on the scorecard, but was denied due to the strict wording of A7c4. Therefore, the solve is marked as a DNF in the database when the average delegate would be 100% confident that the time the competitor got on the scramble was in fact 12.13.

To me, it is against the spirit of "more fun" in the WCA Mission Statement to provide such a strict environment for first-time competitors.

My proposal is a narrow change aimed at providing leniency for newcomers without opening a can of worms regarding doctored video evidence for record-breaking solves (given the extremely low likelihood of something occurring by a first-time competitor).

**Comment by ohexter** [comment]
Addressed [here](https://github.com/thewca/wca-regulations/pull/1261/files), will be deployed January 1st, 2025.
