### ISSUE TITLE
Remove "Score Taker"?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#120]
Brought up in issue #66.

The score taker is mentioned very few times, and the responsibility is underspecified (in particular, the score taker is in charge of managing who advances each round, but this is not mentioned). In favor of making the Regulations simpler, I agree that this would be better to remove.

1g2 can be moved to A7c as A7c2.

**Comment by iVinshe** [comment]
Agreed.

**Comment by lgarron** [comment]
Unfortunately, I think removing mention of he score taker isn't a great idea.
Apart from the Delegate, judges, and scramblers, score takers are the only staff that are actually needed at every competition.

Two Guidelines are more straightforward with mentions of the score taker, and I think including the score taker helps people who are trying to get a sense of how competitions are run by reading the Regulations.

I also can't think of a great alternative name for "score taker" ("results person"?), so I think this is not critical to fix for now.
