### ISSUE TITLE
[Proposal] Separate 11e into components

### ISSUE THREAD

**Issue by khkellis** [thewca/wca-regulations#1202]
### What changes do you want to see implemented to existing regulations?
My proposal separates 11e into multiple components:
* 11e: The WCA Delegate may grant a competitor an extra attempt to replace an attempt affected by an incident.
  * (new) 11e1: If an incident occurs, the WCA Delegate must consider competitor preferences for an extra attempt when deciding whether to grant an extra attempt.
  * (new) Guideline 11e+: The competitor should appeal verbally or in writing to the judge and WCA Delegate at the time of the incident, before finishing the original attempt, to be eligible for an extra attempt. An appeal does not guarantee the competitor an extra attempt.

### Why do you want these changes to be implemented? Have you noticed any drawback to your proposals?
**Why**:
There was a recent instance where I personally witnessed an incident occur that resulted in a DNF for a competitor. The competitor, frustrated with their poor average up to that point, did not appeal for an extra attempt. However, when offered an extra attempt, the competitor accepted. 

Despite this, the current interpretation of the regulations directly tie the extra attempt to a competitor’s appeal. Without additional discussion, the default in this situation is to retain the competitor’s initial DNF instead of the extra attempt, which I think is problematic both from a fairness perspective (which contradicts the WCA Mission Statement) and from a logistical perspective. Appealing cases such as this take precious volunteer time from the WRC and WCA Board to focus on hyperlocal issues that are better handled by Delegates on the ground.

Consider a few other (some admittedly extreme) scenarios in favor of this Regulation change. 
  * If the lights are turned off at a competition, 11e’s current wording states that each individual competitor should submit an appeal to their judge and/or Delegate, which is almost never done. Instead, the already Delegate exercises the first part of 11e without considering the second part about appeals.
  * A competitor is drenched in ice water as a prank, taking their breath away. Notwithstanding the fact that this is not humorous, the competitor is physically unable to appeal for an extra attempt. 
  * Similarly, a competitor has a medical emergency (e.g. asthma attack) that prevents them from appealing the incident for an extra attempt.
  * A Delegate witnesses an incident involving a new competitor unaware of the appeal system that did not arise from inexperience (and hence is not covered by A7g). 

I also acknowledge the fact that the second half of 11e contains a “should” instead of a “must”, so all of these examples could be resolved by ignoring the “should” clause of the Regulation. The main problem is that the interpretation of whether a competitor “should” appeal, or whether an extra attempt is warranted without a competitor appeal, is arbitrary. Changing the Regulation to only describe a Delegate’s right to offer an extra attempt gives the Delegate more flexibility to exercise their judgment without needing input from the WRC about whether the “should” clause is appropriate for the exact setting.

**Why not**:

As brought up in an internal discussion, a competitor may not want an extra attempt despite an incident occurring.

**Example**: The venue lights are turned off during execution of a personal record BLD solve, where lights are not relevant to a competitor's execution.

Separating a Delegate’s right to grant extra attempts from competitor appeals allow a Delegate to override competitor’s preferences in these situations, which is also undesirable from a “more fun” perspective, going against the WCA Mission Statement.

**I believe the “Why” overrides the “Why not."** The proposal includes language requiring Delegates to account for competitor preferences (although, I acknowledge, it does not require a Delegate to follow them), the main “Why not” concern I am aware of.
However, I believe that Delegates do take competitor preferences into account when making decisions, and the screening process for recruiting and maintaining Delegates will safeguard against malicious Delegates.

**Comment by ohexter** [comment]
The WRC reviewed extensive Staff and Community feedback when selecting which topics to amend for the January 2025 WCA Regulations and Guidelines and chose not to make changes addressing this item. Previously raised items will not automatically be taken forward for consideration in future cycles so this issue has been closed. You are welcome to raise this topic again in a future cycle if desired.

**Comment by ohexter** [comment]
update status to 'closed as not planned'
