### ISSUE TITLE
[Proposal] Add regulation requiring "clear solving station"

### ISSUE THREAD

**Issue by khkellis** [thewca/wca-regulations#1203]
### What are your proposals for new regulations?

Create a new regulation along the following lines:

- "The judge is responsible for keeping objects clear of the solving station during the attempt, except objects placed by the competitor.”
- “The judge is responsible for keeping objects approximately 10cm clear of the timer during the attempt, except objects placed by the competitor."

### Why do you want these changes to be implemented? Have you noticed any drawback to your proposals?

I recently observed the following incident at a competition. During 3x3: One-handed, an inexperienced judge had placed the pen on the left-hand side of the mat, close to the timer. The competitor solved left-handed, and primarily placed the cube on the table (known colloquially as “table abuse”). During the solve, the competitor’s arm slipped on the pen, which caused them to miss a turn.

I deemed this an incident, since commonsense dictates that the pen’s placement is the judge’s responsibility. Despite this, there is no explicit mention of a clear solving station in the Regulations. Instead, I ruled that “not clearing the solving station of objects such as pens is against fair sportsmanship (Regulation 11d) and it is the judge’s responsibility, not the competitor’s, to maintain a clear solving station (Regulation 1e1)."

I believe there should be such a regulation enforcing clear solving stations, which is desirable from a “more fair” perspective and is directly in line with the WCA Mission Statement.

However, I am not certain about the exact language, and thus have two tentative proposals for the language of the regulation. Consider the following examples.
* The table, upon which the solving station is placed, is small, and the mat covers the entire table.
   * In this scenario, the first proposal (all objects clear of solving station) is not possible unless the judge holds the stopwatch, pen, scorecard, and cube cover. This seems like an unreasonable ask for a judge from a logistical perspective.
* A competition uses two separate types of mats: one large, and one small. 
   * In this scenario, the first proposal imposes more stringent requirements for judges at the solving stations with large mats.

One solution is to provide a distance requirement, such as the second proposal of 10cm // ~4in, but I do not know:

- what the appropriate distance should be
  - whether the required distance encounters the same problems as the first example above
- whether the distance should be enforced strictly, or whether softer language such as “approximately” should be used
  - strict enforcement seems cumbersome, and could be used to “farm” extra attempts by malicious competitors.

Overall, the primary objective of this regulation proposal is to create more uniformity across solving stations and to allow a Delegate to grant an extra attempt if the solving station is problematic. Unfortunately, I think there is work to do about the exact wording to prevent unreasonable and/or cumbersome scenarios for judges and Delegates.

**Comment by ohexter** [comment]
The WRC reviewed extensive Staff and Community feedback when selecting which topics to amend for the January 2025 WCA Regulations and Guidelines and chose not to make changes addressing this item. Previously raised items will not automatically be taken forward for consideration in future cycles so this issue has been closed. You are welcome to raise this topic again in a future cycle if desired.

**Comment by ohexter** [comment]
update status to 'closed as not planned'
