### ISSUE TITLE
What if the judge/scrambler makes a mistake?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#121]
Created based on #66.

This comes up sometimes. The usual convention is not to punish the competitor, and award an extra attempt if reasonable. This isn't codified anywhere.

**Comment by lgarron** [comment]
Someone on Delegate list mentioned lazy judge signing: https://groups.google.com/d/msg/wca-delegates/wqzQFBQiBHk/y2FCkCU_vDMJ
:-(

**Comment by lgarron** [comment]
I sent this idea the Delegate list 2 days ago (slightly reformatted for GitHub):

> - 1) Require the use of an experienced person as a dedicated scramble checker for each scramble (somebody who sits next to scramblers, does _not_ scramble at all, and only checks scrambles).
> 
> ---
> - 2) Require that people do not judge or scramble their close acquaintances, unless the person judging/scrambling is:
>   - a) on the organization team, or
>   - b) explicitly permitted by the Delegate.
> 
> This could reduce the risk/temptation of collusion; it also encourages mingling (more people! more fun!), and prevents systematic judging errors from isolated groups of competitors.
> 
> ---
> - 3) Require that all scrambles must be correct (apart from exceptions in 4g1), but craft a general policy that allows a result with an incident to stand as long as:
>   - a) it was scrambled correctly,
>   - b) the competitor did not directly cause the incident (or intentionally allow/influence it to happen), and
>   - c) the competitor did not receive a significant advantage.
> 
> However, make it clear that any such leniency is at the Delegate's discretion.
> 
> ---
> - 4) Establish the policy that the Delegate should give a provisional re-solve for the competitor any time there is an unclear incident that _could_ result in a re-solve. Replace the original result with the re-solve result if and only if the Board finds that a re-solve was the proper course of action.
> 
> ---
> 
> I would also be fine with relaxing 1. and 2. during non-final rounds (but recommended during all rounds).
> 
> There are some details to figure out (provisionally letting competitors advance, depending on a Board ruling?), but I would like to see if we could form this into a policy that handles all the major cases from 2014.

This isn't an actual proposal (yet), but it could be a start.

**Comment by lgarron** [comment]
[Asian Championship 2014](https://groups.google.com/forum/#!msg/wca-delegates/Yb98yq3kE80/s3m0ndADEjoJ)

> In the final round of 3x3 blindfolded, the judge was not putting a piece of
> cardboard between the competitor and the cube during his third attempt.
> He succeeded in this attempt, and if this attempt had been approved, his average would have been a new world record. However, Ron Van Bruchem, WCA Board Member, pointed out the judge’s mistake. After the discussion between Ron, Ilkyoo Choi, and Japanese Delegates, we decided to ask the
> competitor whether he would do an extra attempt, or choose DNF.
> We explained the detail to him; that this attempt would not be approved
> because of the judge’s not putting a piece of cardboard while his attempt, and that we would award him an extra attempt, for this was not his fault.
> After all, the competitor chose to do an extra attempt and he did. The extra attempt, however, did not set a new world record. (This average is a NR in India.) This incident was caused by a judge’s mistake. We thought, however, we could not prove at all he was not cheating. That is why we awarded him an extra
> attempt.
> In the following competitions, we will take some action against this case,
> explaining their duties to judges and telling them to be more careful.

Kit, later in the same thread:

> I presume that the 3bld incident is already being looked into further, but it seems strange to be that Angel Lim had a similar incident happen to him at BASC 4 and no action was taken there.  There's also a precedent to allow solves where the judge made a procedural error that potentially gave the competitor an advantage (Chris Olson inspection in 1.71 average).

**Comment by lgarron** [comment]
[Santa Claus Cube Race 2014](https://groups.google.com/forum/#!msg/wca-delegates/iU9ULwDfADg/oOybL3bMrGgJ)

> - there was few judge mistakes reported by competitors:
>   - timer wasn't reset before start,
>   - judge hung up staring at the wall (or whatever) and forgot to tell 8/12 during preinspection,

**Comment by lgarron** [comment]
[Cape Town 2014](https://groups.google.com/forum/#!msg/wca-delegates/xjzvzf3efFM/J4UkSB_FaHoJ):

One competitor with a friend judging got fake times (which were nevertheless suspicious enough to be caught), and both of them goofed off while judging.

Also, from Donovan:

> I also had to eventually put a ban on Judges solving their own puzzles while they are supposed to be overseeing the solves.

**Comment by lgarron** [comment]
[Austin Cubing Limits 2015](https://groups.google.com/forum/#!msg/wca-delegates/wKtxa9b0W1o/8dtRON64HpUJ)

> During pyraminx, Charlie Jordan finished his inspection and tried to start the solve, but the timer had not been turned on. He was given a DNF. I know A3c3 states that the judge is supposed to prepare the timer, but the accompanying clarification says "the competitor may reset [the timer] before/during the inspection phase if the judge accidentally neglected to do so." I interpreted this to mean that there is no reason why Charlie could not have turned on and reset the timer himself, and that he should have done so. Please let me know if I am interpreting this incorrectly or if you think I should have made a different call -- his family seemed very upset about this decision.

My response:

> Your interpretation is definitely incorrect. Unless you think the competitor intentionally took advantage of it (which is probably not the case), this should have been a resolve.

We should think about rephrasing A3c3+ to be crystal-clear that the competitor is _not_ responsible if the judge forgets to reset the timer. They're just permitted to reset the timer themselves because it can prevent annoying resolves, and doesn't affect the integrity of the result.
(While we're at it, we might also want to make clear that turning on the timer is fine, too, if it happened to be off.)

**Comment by lgarron** [comment]
> 2) Require that people do not judge or scramble their close acquaintances, unless the person judging/scrambling is:

See the [German Open 2015 report](https://groups.google.com/forum/#!msg/wca-delegates/M8LdKsJMujc/mH5wqsKJtGQJ) for an incident (incident #3).

**Comment by dancing-jules** [comment]
About possibly cheating judge/competitor pairs: I think it is a good idea to discourage two people judging each other for a whole average. 

That is of course easier to track in comps that don't have runners (someone at the scrambling station making sure nobody stands around waiting for a specific cube to be scrambled).

At comps with runners there can be an exception made for finals with assigned seating where you'd go with the "no close acquaintances" rule instead. 

And 3x3 finals are usually judged by delegates and/or main organizer anyway.
