### ISSUE TITLE
Should 3h1) exception be removed? (Pillowed 7x7x7)

### ISSUE THREAD

**Issue by cubizh** [thewca/wca-regulations#124]
Should the pillowed 7x7 exception be cleared from the regulations?

A 7x7 cubic version have been mass produced for over a year and this year another (smaller) version has been also released, and is used by most (if not all) top 7x7 competitors to smash regional records and improve this event's times.
What seemed to be an exception that could potentially be an advantage is now considered by the top cubers as a handicap and is being slowly abandoned to the newer cubic version.
According to Ron this issue could be fixed when a cubic version of 7x7 is generally available and widely used. (Source: https://www.worldcubeassociation.org/forum/viewtopic.php?p=5255#p5255)
Are we there yet?
A delegate's perspective on what people currently use in competition in this event should be helpful to see if it's time already or not, but it's worth discussing.

**Comment by lgarron** [comment]
There was a discussion on the Delegate list recently. Delegate consensus is that pillowed 7x7x7s should be allowed in 2014.

**Comment by AlbertoPdRF** [comment]
This issue is no longer needed (#504)
