### ISSUE TITLE
Publishing FMC Solutions

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#125]
Competition organizers usually don't look at FMC solutions too much because it takes a lot of time -- they're just glad to have scored them once.

I still have physical FMC solutions from past US Nationals that I intended to type up and publish -- but I've been partly concerned that some competitors have an expectation of privacy in their solution. Considering that cubing is traditionally an open sport (e.g. the community is very collaborative, and filming official solves of fast cubers to learn from/reconstruct is popular), I think it would be awesome if FMC results were public data, possibly even _part of the result_ (i.e. available on the results site). However, for now it would help to make explicit that the organizer has the _right_ to publish an FMC solution.

(Do we have a precedent where a competition organizer published a solution after a record was set, instead of the competitor reporting it? After SF09, I put up results [here](http://ca.cubingusa.com/sanfrancisco2009/files/fmc_results.htm) but I don't know how many people have seen that.)

If we had a good mechanism, digital scoring might actually be faster than turning physical cubes (and give us data as a byproduct). The current FMC sheets came out of my attempts to make this happen, going back to 2009:
- FMCTyper: http://www.speedsolving.com/forum/showthread.php?8090-FCF-and-FMCTyper
- FMC Scramble Sheets: http://www.speedsolving.com/forum/showthread.php?37704-FMC-Scramble-Sheets

I still think digital FMC scoring is worth pursuing, but I've had other things to worry about.

**Comment by iVinshe** [comment]
Easier to err on the side of privacy. Would it be simple to add a simple
opt-in check box for this?

**Comment by lgarron** [comment]
You mean, on the FMC sheet? I think case-by-case is rather messy; one simple rule would be preferable. (Like the clear choices of "gender public" and "age private".)

I don't think anyone _should_ have an expectation of privacy for an FMC solution, I was mainly concerned that some _might_ have.

**Comment by lgarron** [comment]
From #660 

> I'd like to support better FMC grading software, including software that allows uploading solutions for computer grading or assistance from people who are not the competition (thus freeing competition staff). This allows for easier competition logistics, provides a better record for accountability, and supports the open, constructive nature of the cubing community. (If I understand correctly, practically all top competitors freely share their official solutions and approaches.)
>
> To this end, I'd like us to clarify that FMC solutions are not secret.

**Comment by Berkmann18** [comment]
It's definitely a good idea whether the workings behind a solution or not are published alongside said solution.
I doubt anyone wouldn't want their final solution to go public when (I'm sure) a fair amount of FMCers would learn from it, or simply want to see what a person did on a certain scramble.

**Comment by ColorfulPockets** [comment]
I 100% support that the solutions should be public. Competitors are already required to explain a solution if asked, right? So if they were private, the only people who could learn their secret techniques would be people like delegates. 

Obviously that’s a ridiculous thing to actually happen, but in principle I think they need to be public

**Comment by lgarron** [comment]
I would like to consider this change for 2020.

1. The cubing community has so far been fairly open about our techniques. I'd like to encourage that by allowing everyone to learn from official solutions.
2. It allows better accountability. If someone cheating, the public information may help detect a pattern.
3. I'm interested in resuming a project to make it easy to grade FMC by taking pictures and transcribing them on a computer. This could be faster and more reliable than normal solution checking. Making solutions public allows volunteers from around the world help grade solutions at a given competition, potentially freeing up the organizer's resources. (Note: this still requires great care to protect the scramble *before* the attempt is finished.)
  - If someone receives a DNF they did not expect, a picture and transcription gives them a paper trail for what happened.

**Comment by ColorfulPockets** [comment]
A project to make it easy to transcribe? How does that work?

**Comment by maconard** [comment]
Vision recognition and potentially AI, I would assume. I've made an AI project that could read human handwriting and transcribe it (just for Arabic numerals), but regardless of how well done it is it will never be quite perfect.

If the idea is to take 3 seconds to snap a picture and have most if not all of the solution transcribed with parts marked that it couldn't figure out (such as where the competitor scratched out a move slot and skipped it or the handwriting was drastically different from standard) and need human review, I would think that's fairly do-able. It could even check the result if it's given the scramble before a grading session. 

However if the tool isn't done really well or has lots of errors, I could see it slowing down or making little to no improvement on the grading process time commitment.

**Comment by lgarron** [comment]
> A project to make it easy to transcribe? How does that work?
> Vision recognition and potentially AI, I would assume.

No AI!

I originally designed the FMC sheet make it easy to isolate letters for human transcription.
See https://www.speedsolving.com/threads/fcf-and-fmctyper.8090/#post-113677 for a program I wrote in 2008(!) to do this. I've learned a lot over the last 11 years, and I want to find a way to wrap up the project.

**Comment by Ivan-Brigidano** [comment]
I think this will be perfectly doable if the future [WCA Live](https://github.com/thewca/wca-live) includes the software needed for checking and saving the solutions

**Comment by ClemAntarctica** [comment]
What about a Bluetooth cube? You can scramble the cube and perform the solution and you didn't have to type it yourself, just check that the solution actually works.
