### ISSUE TITLE
Remove [r], [u], [f], [b], [l], [d] for rotations (use only x, y, z)

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#126]
## Proposal

Remove [r], [u], [f], [b], [l], [d] as rotations, leaving only x, y, z.
Exact changes: https://github.com/cubing/wca-documents/compare/rotations
## Pros
- Simplifies the Regulations (x/y/z already exist, so they're redundant).
- FMC sheets are now standard, and include a clear reminder about which of x, y, and z is which.
- They're non-standard. I've never seen anyone use them outside of occasional FMC solutions.
- They're the only use of lower-case u/f/r/b/l/d in notation, look confusing when compared to commutator/conjugate notations (common in the community), and suggest that multiple moves in brackets are multiple rotations (a convention which does not exist).
## Cons
- It was easy to tell which direction is which when using these rotations.
- Some FMC competitors may be used to them (but we've removed notation like slice moves in the past...).

**Comment by lgarron** [comment]
@ChenShuang Do you know if [r], [u], [f] notation is often used in China? I'm trying to find out where it's used.

**Comment by cs0x7f** [comment]
Never heard of the using of {[u] [r] [f] [d] [l] [b]} yet...

**Comment by lgarron** [comment]
Alright, thanks.

**Comment by Laura-O** [comment]
I checked FMC sheets at Hungarian Open 2015 and the  [r], [u], [f], [b], [l], [d] notation was used by probably more than 90% of the competitors using cube rotations in their solutions (which were quite many). New competitors in Germany are using this a lot as well.

I suggest to close this issue and keep the current notation.

**Comment by lgarron** [comment]
Yeah, I'm fine with giving up on this.
I never got proper international feedback, but there are always rumors floating around about people using it.
