### ISSUE TITLE
What defines a visual disability?

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#127]
This thought arose from Matthew Dickman's (2013DICK01) pyraminx solves: https://www.youtube.com/watch?v=VFNQENxMpWw

I was curious as to why he had a stickerless face.  From a discussion I had on facebook, he was apparently given the approval to use a stickerless side due to colorblindness.  (If this was not the case, I would be interested to hear what the situation was.)  But assuming that this is the case, my questions are:
1. Should this puzzle have been allowed?  The exception in 3d1 only allows for a puzzle with "different textures on different faces," and the three stickered sides had the same texture.
2. Does this regulation intend to make exceptions for those who are colorblind?  I would think that someone who is colorblind should instead find shades that are less similar to that particular competitor.  Someone with glasses could technically qualify as someone "with a medically documented visual disability," but I don't think anyone would ever allow such a competitor to use a textured cube.

**Comment by SAuroux** [comment]
That's definitely a bad decision in my opinion. I have a friend in Germany
who is colourblind as well. He simply uses black stickers instead of red on
all his puzzles. Same outcome, but no violation of any regulation.

2013/12/28 KitClement notifications@github.com

**Comment by KitClement** [comment]
Then the question is, how do we reword "medically documented visual disability" to make this more clear?  I would like to make it clear that this is intended for blind competitors, but being "visually blind" can range from the legal definition of 20/200 vision (which glasses can correct) to total blindness.

**Comment by Laura-O** [comment]
This was fixed in https://github.com/cubing/wca-regulations/commit/a9693fb7b10ffc1fc3838d0bec99172d10db5c20.
