### ISSUE TITLE
4f+ and 4f++ should be removed in official-2025-01-01(4f555e9)

### ISSUE THREAD

**Issue by oyyq99999** [thewca/wca-regulations#1271]
Those are duplicates of 4b+ and 4b++
https://github.com/thewca/wca-regulations/blob/4f555e9b83f6c3ba396eaa823fafd77441d9a3f2/wca-guidelines.md?plain=1#L95-L104

**Comment by ohexter** [comment]
Resolved [here ](https://github.com/thewca/wca-regulations/pull/1272)- will be deployed January 1st, 2025.
