### ISSUE TITLE
Square-1 Filtering

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#129]
Need to document.

This depends on TNoodle's support.

**Comment by jfly** [comment]
This depends on https://github.com/cubing/tnoodle/issues/151. If Chen Shuang can't fix this in the next couple of days, we'll stick with 11.

**Comment by lgarron** [comment]
I'm setting the value at 11. Unless this changes _very_ soon, it will not be possible to change without a Regulations change. However, in the interest of time, I have to gloss over the metric.

(And yes, I will continue to insist on documenting filtering limits in the Regulations for now.)

**Comment by jfly** [comment]
Gloss over the what?

**Comment by lgarron** [comment]
Metric. (Changed comment.)
