### ISSUE TITLE
Square One +2 second penalty

### ISSUE THREAD

**Issue by jfly** [thewca/wca-regulations#130]
Take a solved sq1. Apply the move (6, 6) to it. This puzzle is exactly 1 move away from solved, as per https://www.worldcubeassociation.org/regulations/2014-draft/#12c. By https://www.worldcubeassociation.org/regulations/2014-draft/#10e3, that means that this puzzle is solved with a 2 second penalty.

I asked Lucas about this, and he confirmed that this is a correct interpretation of the regs, but not intended, as it is inconsistent with other puzzles (a 3x3x3 with a U2 D2 applied to it is a DNF). I don't have a suggestion for how to fix this.

**Comment by SAuroux** [comment]
I don't think that the Regulations do clearly say that (6,6) is one move,
but yes, this should definitely be clarified.

Proposal:

12c2+) When counting the moves in case of a misalignment at the end of a
solve, x and y have to be considered seperately. Example: (5,2) is
considered one move, (5,5) i´s considered two moves.

2013/12/28 Jeremy Fleischman notifications@github.com

**Comment by jfly** [comment]
Your proposal sounds pretty good to me.  Do you think it should also
explicitly mention that this metric is used for considering alignment
penalties, but not for scramble filtering?

I'm going to look into changing tnoodle's turn metric to count (2, 1) as 2
turns. Would the WRC be ok with changing their sq1 move metric to that?

**Comment by Claster** [comment]
> (5,2) is considered one move

Why (5,2) is 1 move?

**Comment by SAuroux** [comment]
you are right, I suck. should be (5,1).

2013/12/29 Oleg Gritsenko notifications@github.com

**Comment by lgarron** [comment]
I have the silly worry worry here is that we might set a definition of "move" that defines a Markov model whose steady-state distribution is _not_ the one we use for selecting a random position.

Silly, but I worry about these things if I want to formalize them later. :-P
