### ISSUE TITLE
Clock scramble scrambling orientation (Vs. TNoodle)

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#132]
I was scrambling starting with the darker insert in front today, and I think the colors were the wrong way around int he images. Either the Regs or TNoodle should be fixed if this is wrong. If someone has time right now, could you check?

Tagging @Sa967St , @jfly.

**Comment by lgarron** [comment]
Yeah, they mismatch. Since we already use "dark color in front" in a bunch of places, I'd prefer to keep this the same. Will make a TNoodle issue.

**Comment by jfly** [comment]
Just want to make sure, isn't there a "turn the puzzle upside down" move in
the clock scrambles? Perhaps that's the confusion?

**Comment by lgarron** [comment]
You mean ["Turn around the puzzle so that twelve is still on top"](https://www.worldcubeassociation.org/regulations/#12g4)?

**Comment by jfly** [comment]
I believe so?
