### ISSUE TITLE
Make historical version and changes available

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#134]
Every new version should be linked from https://www.worldcubeassociation.org/regulations/history/

Also see #56.

**Comment by lgarron** [comment]
See https://github.com/cubing/wca-documents-extra/commit/2f88b57d6b91124e9a81a2d2d181b5d07afa2d2c

Still needs summarized changes to link to.

**Comment by Laura-O** [comment]
There are summarized changes for all summarized changes since 2014-01-01 and I recently updated the links (https://github.com/cubing/worldcubeassociation.org/commit/ac5819492fa4b9b4305a328ff83ccb49a98e610a), so I think we can close this.
