### ISSUE TITLE
Consistent place for repair restrictions

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#136]
Comment by Ron:

> ```
> 5b4) During a blindfolded phase (see Regulation B4), all repairs must be performed blindfolded. Penalty: disqualification of the attempt (DNF).
> ```
> 
> The location of this regulation is not inline with one-handed C1b2 and C1b3.
> Either blindfolded and one-handed should be handled in article 5 or both in B and C.

This has been the case since [2010 or earlier](https://www.worldcubeassociation.org/regulations/history/files/regulations2010.html), but the Regulations are definitely still suffering from inconsistent article structuring like this.

**Comment by Samuel-Baird** [comment]
it would make the most sense to move C1b2 to article 5 in my opinion
