### ISSUE TITLE
Registration fees

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#137]
Pointed out by Ron: 2k currently doesn't include paying the registration fee.

**Comment by SAuroux** [comment]
2k doesn't need to do so, as 2a does:

2a https://www.worldcubeassociation.org/regulations/#2a) Any person may
compete in a WCA competition if he:

....
- 2a2 https://www.worldcubeassociation.org/regulations/#2a2) Meets the
  competition requirements, which must be clearly announced before the
  competition.

2014/1/1 Lucas Garron notifications@github.com

**Comment by lgarron** [comment]
This is one of those "loopholes" that never causes confusion in practice. Closing.
