### ISSUE TITLE
"puzzle" instead of "cube"

### ISSUE THREAD

**Issue by pochmann** [thewca/wca-regulations#138]
3h2 should say "inside the puzzle", not "inside the cube".

I also don't quite understand what 10h means with "applying the relevant regulations for the Rubik's Cube".

All other occurences of "cube" in the regulations are correct.

**Comment by pochmann** [comment]
Apparently it's already fixed at
https://github.com/cubing/wca-documents/blob/official/wca-regulations.md
and only the diff-link at
http://www.speedsolving.com/forum/showthread.php?45688-Did-your-puzzle-get-banned&p=938247&viewfull=1#post938247
is bad.

**Comment by lgarron** [comment]
3h was fixed in https://github.com/cubing/wca-documents/commit/a4eab465605ab024b381bcc80fc64b3822c62fd6 .

10h has been around for a while; I haven't thought of a good replacement. 2015 will probably ned to fix all the odd things like that.

Also see #123 and #89.

**Comment by lgarron** [comment]
Reopening for 10h.
