### ISSUE TITLE
"Stickerless" regulation is confusing

### ISSUE THREAD

**Issue by pochmann** [thewca/wca-regulations#139]
Currently it says:

3h2) "Stickerless" puzzles, and other puzzles whose face colours are visible inside the puzzle, are not permitted.

Too often I've seen people claim that this says that stickerless puzzles are forbidden. Apparently they don't notice the quotes and the word "other". I suggest to rephrase like this:

3h2) Puzzles whose face colours are visible inside the puzzle are not permitted (for example some "stickerless" puzzles).

**Comment by lgarron** [comment]
It does forbid stickerless puzzles. Your rephrasing sounds fine, except it should use "e.g." for "for example".

**Comment by pochmann** [comment]
Hmm, now I'm not sure we're on the same page. When you say it "does forbid stickerless puzzles", do you mean in the sense that "there are stickerless puzzles it does forbid" or in the sense that it forbids _all_ stickerless puzzles? I believe that's what the people I mentioned usually mean when they say that, and that's most certainly how people reading/hearing that understand it.

**Comment by lgarron** [comment]
Are you saying people were using it to argue that tiled or painted puzzles are illegal? The "stickerless" part is clearly in quotes.

It is meant to disallow all puzzles that people usually refer to as "stickerless".

**Comment by pochmann** [comment]
I don't know what they think. It's unclear what they think. That's my point.

But yes, they might think this outlaws tiled or painted puzzles. Or at least their readers/listeners might think that if they only see/hear "stickerless puzzles are forbidden" without the context/explanation that 3h2 provides. You say "usually refer to", but what is that? The word "usually" already shows that "stickerless" is ambiguous and shouldn't be the the focus of the regulation. The quotes adding more uncertainty don't exactly help, either. Better focus on what you're actually after (colors inside the cube), and then mention "stickerless" cubes only as an illustrating example. 

It used to be clearer what "stickerless" meant when the stickerless GuHong (?) was the only one available. The lines are getting blurrier. I'd for example call the tiled cube4you cube "stickerless", and that one (with non-texture tiles) seems like a perfectly legitimate cube.

**Comment by pochmann** [comment]
To clarify: What I'm talking about is when people just write/say something like "Stickerless puzzles are forbidden.", omitting both the inside-color qualification as well as the quotes around "stickerless".

**Comment by lgarron** [comment]
Yeah, I don't disagree, just haven't gotten around to putting this on a branch with fixes. (Feel free to send a pull request).»Lucas Garron
