### ISSUE TITLE
Phrases to Fix

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#140]
- [x] 10h) "applying the relevant regulations for the Rubik's Cube" (#138)
- [x] 3h2) "Stickerless" ... (#139)
- [x] 3l) A puzzle may have a logo on a sticker/tile, but it must have at most one sticker/tile with a logo.

**Comment by sarahstrong314** [comment]
3l) A puzzle may have a logo on a sticker/tile, but it must have at most one sticker/tile with a logo.

I suggest changing "at most one" to something like "exactly zero or one". "At most one" is apparently confusing to many people.

**Comment by lgarron** [comment]
I don't dispute that it could be confusing, but I've never seen anyone say they found this unclear. Do you have particular cases in mind?

**Comment by sarahstrong314** [comment]
;)
http://www.speedsolving.com/forum/showthread.php?44849-Exceptions-with-logos-on-certain-puzzles&p=923925&viewfull=1#post923925

**Comment by lgarron** [comment]
Oh, duh, I haven't seen anyone say that because it was changed this year. :-P

"Exactly zero or one" sounds funky to me. I'd prefer to do something like add "if it has a logo" somewhere.

**Comment by sarahstrong314** [comment]
How about:

3l) A puzzle is not required to have a logo, but if it does, it must have only one logo, which must be located on one sticker/tile.

**Comment by sarahstrong314** [comment]
3l1b) For Square-1, the logo must be on a piece in the middle slice.

"Middle" isn't clear, and might actually make it more confusing. 
FYI: for Square-1, a  "slice" usually refers to the 90 degrees slice move "/".

Suggestion:
3l1b) For Square-1, the logo must be on a piece in the **equatorial** slice.

**Comment by sarahstrong314** [comment]
Also regarding Square-1,
12c1) Moves are applied with the smallest slice of the middle layer on left side of front face.

Are the two instances of the article "the" left out intentionally?

Suggestion:
12c1) Moves are applied with **one of the two smallest caps of the equatorial slice** on **the** left side of **the** front face.

**Comment by lgarron** [comment]
Square-1s don't all have caps under the smallest equatorial sticker, so I used "surface" for now. I'm open to other suggestion, but I'm closing the issue for now.
