### ISSUE TITLE
Proper community feedback mechanism

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#144]
This has come up a few times, but there isn't an issue for it.

Currently, speedsolving.com is the best we have to gauge "international" community views, but discussions can be derailed easily, and polls can be biased/stuffed.
The Delegate list can help get some international feedback, but I don't often see valuable feedback about some part of the world that does things differently. (Example: There was lots of discussion about [[r], [u], [f]](https://github.com/cubing/wca-documents/issues/126) based on opinions, but it took a lot of prodding to hear about any parts of the world other than Japan that would be significantly affected by removing those.)

Ideally, we'd have some sort of "suggestion" mechanism similar to a feature request site where many competitors (ideally with accounts associated with WCA ID, if they have one) vote and discuss on topics. Even better would be if this worked together with issues on GitHub. Also, if it gracefully handled the fact that a lot of competitors are young, and, uh... haven't had as much experience in productive discussions?

However, we don't have user accounts on the WCA site yet, and I'm strongly against adding "yet another" mechanism in the hopes of fixing things.

Also see #106.

**Comment by timhabermaas** [comment]
Having a more accessible system than Github would be awesome. But I fear we would need to create our own (I'm not aware of anything close to what we need).

There's also another issue which is that there's no apparent connection between the changes made on Github and the discussion going on (this is especially bad if the discussion happened mainly on the delegates list). I'd like to have these in one place (without people requiring to sign-up for Github, though), but I don't know how.

**Comment by iVinshe** [comment]
We "have our own"; it's just that nobody uses it (the WCA forum). If we
suddenly posted all community feedback there, would we have enough clout to
be able to draw over the "serious" members? I'm not sure that WCA Forum
accounts have to be linked to WCA IDs, but that would give more data as
well.

**Comment by lgarron** [comment]
Yes, we "have our own". After the last few years, I've temporarily given up
on making it work.
(Also, it would still suffer from some of the problems
speedsolving.comhas. And a forum always feels bulky for me compared to
email/GitHub
comments)

I wouldn't mind if someone wants to put in an effort to revive it, but it
needs to be a serious effort rather than "let's try using it again".

»Lucas Garron

**Comment by timhabermaas** [comment]
I have to agree with @lgarron. I don't think a forum is the right place for this. You might be able to make it work by some serious moderation and strict posting guidelines, but you'll never have the nice connection between the regulations and the discussion a Github/git workflow would provide. Unfortunately Github is neither easy to understand nor easy to access (to be fair: the WCA forum isn't particular good at these two features either).

BTW. There is a service which lets users create Github issues anonymously without requiring accounts, but I can't find it right now and I believe it required you to give this service full access to the repository (thanks to Github's limited access rights).

**Comment by lgarron** [comment]
Just a note on _anonymity_:

(I know your point wasn't about anonymity, but I thought I'd mention this,
since it may be relevant to other potential mechanisms.)

Cubing discussions have worked fine with public identities (or
well-identified pseudonyms, in many cases). Since cubing is based so much
on people meeting each other physically in person, I believe this is
important to the feel of the community.
I also check the "view what everyone voted for" option for all the
speedsolving.com polls about WRC stuff, so that we can ask people to
clarify their opinions. It also helps us tell who has more
experience/interest in the topic; raw numbers don't give the whole story.
(Also, sock puppetry/ballot stuffing.)

We might be able to gain some things by providing anonymity ("Give a man a
mask..."), but I would prefer the current situation unless someone has good
evidence that an alternate approach would lead to much better decisions. Or
that it would solve some of our problems, like broad international
participation.

As for the GitHub thing, I'd much prefer that everyone's comments are
attached to accounts. This 1) allows us to draw people into contributing
more (e.g. we're starting to see more code-inclined people help out with
the documents now), and 2) it enforces a minimum level of
seriousness/interest for everyone who is here. We don't get as much done on
GitHub, but at least it's productive.
If such an approach is unreasonable (e.g. people are too reluctant to make
a GitHub account, and _not_ just because it looks too confusing), then I'd
prefer that we have a clear place for certain parts of the discussion and a
few people in charge of cross-linking everything so that the discussion for
each topic is easy to track down.

»Lucas Garron

**Comment by timhabermaas** [comment]
I fully agree. When there's an actual discussion the contents should be tied to at least pseudonyms. This _anonymously submit issues_ thing would only be useful for proposing changes or pointing out some inconsistencies.

**Comment by lgarron** [comment]
Proposing a significant change should be attached to a person, I think.

The people who are on GitHub can always use it.
For everything else, there's MasterCa^H^H^H^H^H^H^H^Hthe WRC email list.

»Lucas Garron

**Comment by Nanush7** [comment]
Closing as we now have the official WCA Forum to get feedback.
