### ISSUE TITLE
Remove +2 for misalignment?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#145]
We'll probably need to have that discussion again this year.

**Comment by iVinshe** [comment]
My position will not change. Unfortunately, it seems like my vote doesn't count.

**Comment by timhabermaas** [comment]
@iVinshe What's your position?

**Comment by iVinshe** [comment]
I don't think we should have misalignment penalties that affect the
recorded time of any solve.

**Comment by lgarron** [comment]
For the record, this is the only controversial change I feel is worth implementing despite community concerns.
Without going too far into the (many, many) details:

This is one of those vestigial allowances that would not make sense if we were writing the Regulations from scratch. The change is reasonable, and (after years of lengthy discussion) I believe that the transition will not be bad -- in fact, in hindsight it will make just as much sense as removing pops.

That said, I respected that the Board did not judge the community to be ready in 2013, and that we should continue considering it in 2014.

(For comparison: I believe that having inspection also doesn't really make sense. However, in contrast with this issue, removing inspection is a breaking change that is _not_ practical at the current time, and I am not in favor of doing so.
As another comparison, puzzles/logos are something where community popularity is valuable for a few reasons. The reason for overriding the community there is not that we don't want to listen to them because we think we know better -- it's that we have to balance it with consistency.)

**Comment by lgarron** [comment]
An old unpublished list of proposal reasons:

> - It is more natural. The competitor must return the puzzle to the solved state; if (s)he leaves it in any other state, is unsolved and they did not finish.
> - It is simpler to explain to competitors, judges, and spectators/non-cubers.
>   - This makes it easier to be fair and consistent across the world.
> - Unlike other controversial changes, it is fair for all competitors with reasonable solving styles.
>   - In fact, it is method-neutral: it places methods that are more likely to end with slice turns (e.g. Roux) on the same footing as Fridrich.
>   - It is consistent for all puzzles.
> - In practice, misalignments are usually the result of dropping the puzzle carelessly, rather than "bad luck".
>   - It does not take much time to place the puzzle on the mat carefully.
>   - The current limits in Regulation 10f are lenient if the puzzle is not perfectly aligned.
>   - It is the competitor's prerogative to select a puzzle they can control. There are now many puzzles on the market that are fast and reliable.
> - As of 2013, most events use an average of 5 format. The top solve is discarded to remove unrepresentative results, and this should be enough to cover an occasional instance of "bad luck".
> - Competitors will get used to the change, just like other major changes (e.g. removing extra attempts for POPs).

(This is just for the record right now. I do not mean to get discussion started on this again right now..)

**Comment by lgarron** [comment]
I would like us to reconsider this for 2020, in order to simplify the complexity of making a decision about what counts as solved.

**Comment by Epride** [comment]
@lgarron I wonder how this will make it easier to determine between solved and not? There will still be the "close calls" if the +2 penalty exists or doesn't so not sure how that solves the problem.

**Comment by maconard** [comment]
I agree with @Epride. Whether the penalty is a +2 or a DNF it will still be hard for new competitors (etc) to judge when it's near 45 degrees. This would just make it unnecessarily more punishing. I believe if a puzzle is 1 move from completion, that the competitor clearly demonstrated their ability to solve the puzzle. +2 is way longer than it would actually take to fix the misalignment (< 0.3 for typical TPS, still <1 if you have to quickly pick the cube up again to fix it), so it's already quite punishing as it is.

**Comment by xsrvmy** [comment]
I believe this is extremely unfair (in terms of beating old times) for smaller events where the risk of a +2 is larger (one look and physical +2s). Competitors will have to be slightly safer, and even 0.1 second is enough to be unfair.
Even worse if a competitor DNFs the first solve, he has to be extra safe and stop timer slowly on the rest or risk a DNF average. This is pushes the mindset for all events in the direction of clock.

**Comment by xsrvmy** [comment]
Another issue is the +2s for touching the puzzle during/after timer stop. Will they become DNFs if this +2 is removed? That is extremely harsh.
The only events that I think this discussion should take place for are BLD and feet. For feet doing a double move is slower than 2 seconds for most people. For BLD being able to leave the last move off can give the event a bad reputation, and also if you are unsure of the last move you can just not do it and get a +2 instead of risking a DNF.
One problem with BLD is that MBLD does have a higher risk of physical +2s from puzzles hitting each other. IIRC the 41/41 former WR had a +2 like this. One option is to allow the competitor to put finished puzzles in a "solved" box if he/she believes it is solved, so that the judge can remove it from the attempt to avoid accidental moves (however this is a potentially big change, and I would only consider it if +2 becomes DNF).

**Comment by xsrvmy** [comment]
Actually is it possible to do some experimentation, either at unofficial comps, or simply using results from Chinese comps (cuz the reason for +2s are recorded), to see how often this change would result in a DNF average, both for top competitors and for everyone?

**Comment by Jambrose777** [comment]
@xsrvmy, competitors will have a drastically different mind set with solves without +2 penalties than they would now. As well after receiving 1 DNF they will likely be safer for the remaining solves.

**Comment by xsrvmy** [comment]
@Jambrose777 I am suggesting this to see how much safer competitors will have to be. At the current speeds even requiring competitor to be 0.1 slower on 2x2 will make records significantly harder to beat.
Also that's why I suggested unofficial comps.

**Comment by dancing-jules** [comment]
@xsrvmy - but a +2 in 2x2 for a good competitor is practically identical to a DNF anyway.

While I personally do not like the idea of removing mis-alignment-+2 (I don't think we are talking about any other +2-regs in this thread), _this would be one solution to the whole square-1-metric-issue (#699) because it would remove the need for a misalignment-metric altogether._ 

Edit: Nevermind

**Comment by Jambrose777** [comment]
I don’t understand how it removes the need for a misalignment metric? You still need to determine whether a puzzle is solved or DNF, which requires that metric

**Comment by dancing-jules** [comment]
@Jambrose777 you're right. My brain short-circuited there somewhere.

**Comment by lgarron** [comment]
For the record, here's an example of how this simplifies how to judge. It would allow us to remove 2 out of 5 of the images in the WCA Competition Tutorial without losing clarity:

<img width="712" alt="Screen Shot 2019-09-18 at 21 26 05" src="https://user-images.githubusercontent.com/248078/65213421-f131df00-da5a-11e9-945e-ddfb36d7db4a.png">

**Comment by xsrvmy** [comment]
> It does not take much time to place the puzzle on the mat carefully.

I don't think this is a valid reason. Even a 0.0x change in time can be significant these days.

> Unlike other controversial changes, it is fair for all competitors with reasonable solving styles.

Removing +2s forces the competitor to use a more controllable puzzle.

I have heard the argument "a +2 in 2x2 is basically a DNF". I don't think this stands as a valid argument except in final rounds.
Currently, a fast competitor can risk getting +2s in all non-final rounds if he can make finals anyways. This allows going for a record even with a +2 already in the average. With +2 changed to DNF, a single DNF basically ends the record attempt since now the competitor must be safer.

**Comment by TheMagicCuber** [comment]
I still think that having +2’s benefits cubing as a whole. It allows a mistake to not completely ruin an average or solve. Also, we still have +2’s for other things like touching after timerstop, or for going over inspection, etc. The +2 still is a benefit despite being a penalty. A DNF is a very harsh penalty, and to assign that onto almost every mistake or misturn by a competitor would severely overturn how Cubing is looked at and affect many future results to the point of people turning way to carefully and not performing as well as they would normally without the stress of DNF’ing.

**Comment by AlexKatyukov** [comment]
Clock already have no +2's. Pyraminx have a lot of +2 by corner misalignments. We will have a lot DNF averages in pyraminx if we will change it to DNF. Don't think that plenty of young first-timers will be happy to have a DNF in their profiles.

**Comment by Samuel-Baird** [comment]
I'm in favor of removing the +2 misalignment penalty. It would make instructing competitors and judges far easier and helps simplify the regs with minimal negative effects.

**Comment by xsrvmy** [comment]
How can the effect be minimal when the mindset for 2x2 and pyra (and in some ways 6 and 7) need to be changed which slows down times?

**Comment by Samuel-Baird** [comment]
> How can the effect be minimal when the mindset for 2x2 and pyra (and in some ways 6 and 7) need to be changed which slows down times?

+2s would already mess you up to some degree for shorter events so changing it to a DNF would only make it slightly harsher for those events. For longer events (big cubes and mega mostly) taking the extra quarter of a second to make sure you have your puzzle completely aligned is pretty negligible.

**Comment by xsrvmy** [comment]
But two +2s do not prevent you from advancing whereas two DNFs do.

**Comment by Ivan-Brigidano** [comment]
The WRC voted about this proposal for 2020 Regulations. We decided to not remove the +2 for misalignment
