### ISSUE TITLE
Simplify Handling of Borderline-Legal Puzzles

### ISSUE THREAD

**Issue by jbmertens** [thewca/wca-regulations#146]
In the delegates list and elsewhere, many discussions have happened regarding the many cases where a puzzle is neither clearly legal or illegal.  Personally, I don't keep track of most of these, and am not willing to.  The discussions I have looked at often don't even come to a conclusion.  As a result, I have seen puzzle regulations either not strongly enforced, or enforced extremely strictly, depending on a delegates philosophy.

There are a number of possible solutions to this problem:
1. Status quo: just allow inconsistent delegate rulings about puzzle legality
2. Maintain an explicit list of (un)acceptable puzzles
3. Maintain an explicit list of (un)acceptable puzzle features
4. Maintain a list of only 'major' rulings on (un)acceptable puzzles
5. Relax the regulations to try and reduce the number of borderline cases
6. A mix of the above, maybe something else.

Personally: I least like the first option, as I feel bad for competitors who are on the strict side of this.  And although possible, I don't care too much for the second and third options, since I feel bad telling competitors they can't use puzzles for arbitrary/nuanced reasons, and don't want to have to inspect cubes to maintain fairness.  The 4th option could possibly reduce the problem, but may still have the problems of points 2-3, and won't solve it completely.  So I somewhat prefer the 5th option, specifically a change that would effectively allow 'see-through' cubes, which (as far as I care to think about right now) would legalize most border cases except for BLD.  But in any case, I really would just prefer not 1-4.

This is sort of a meta-issue including things like #13, #59, #50, #33 (point 5 above also makes debate about logos sort of irrelevant), etc.

**Comment by lgarron** [comment]
That's a good summary of the options presented so far.

2014 was conservative by removing outdated things and taking the
intersection of Delegate consensus.

I don't really care what rules we end up with, as long as:
1) We have something consistent that competitors can apply to get answers
without asking the Delegate.
2) The rules are fair, and don't result in an arms race of modifications.
(Today's form factor of cubes should remain a competitive choice.)

The unfortunate thing for BLD is that feeling an embossed center at the
bottom of the cube is easy, and can provide a significant advantage over
keeping track in your head (less thinking/error recovery). So, I think we
would need to stay pretty strict for BLD.

»Lucas Garron

**Comment by Laura-O** [comment]
I think we have reached a state with very consistent decisions about (il)legal puzzles and the major cube manufacturers (at least try to) care about our regulations, so I see no need for action here.
