### ISSUE TITLE
Add step-by-step instructions for how to contribute

### ISSUE THREAD

**Issue by timhabermaas** [thewca/wca-regulations#147]
There should be documentation for how to properly propose regulation changes using Github in the README. I've already outlined the basics in this post: http://www.speedsolving.com/forum/showthread.php?45314-WCA-Regulations-2014-Logos-and-Stickers&p=940015&viewfull=1#post940015

**Comment by lgarron** [comment]
Should also include a clear alternative for those who don't want to deal with GitHub. I usually tell them to download the source (https://github.com/cubing/wca-documents/archive/official.zip), make changes in a text editor, and send it to the WRC.

Alternatively, a clear description of what Regulation to replace with another is sufficient, but more likely to end up with errors.

**Comment by lgarron** [comment]
Something to figure out: the internal development model. For 2014 I used:
- `official`
- `2014-fixes` for uncontroversial changes
- `2014-changes` for merging in controversial changes. (I've got a new `fixes` branch going for rolling into the next release)
- `2014-draft` once changes and fixes wee merged, and approaching release.

`official` is always pointing to some tag of an official release. It's the default branch on the root repo, and proposals should be a diff on top of it unless there's a good reason to base it on something else. (This has a few benefits, like the default diff on GitHub showing the right changes, and the full text of the proposal not including not-yet-official changes in case someone peruses the whole thing.) I have yet to run into an unreasonable merge conflict.

**Comment by timhabermaas** [comment]
I would use a different model as you currently use. I'll try to illustrate it using a simple scenario:

## Fix "The organisation team team require"
1. Create an issue named something like "Remove 'team team' typo". This issue will get the number 23.
2. Create a local branch called `23-team-typo`*
3. Remove the superfluous "team" from `wca-regulations.md`; commit
4. Push `23-team-typo`
5. Use `hub` to convert issue `23` to a pull request with `official` as the base branch and `23-team-typo` as the _compare_ branch.
6. Add a comment "@lgarron Please review & merge"
7. @lgarron reviews, merges and deletes the branch.

For changes which require the approval of the board (tagged with `needs-board-approval` or something similar) we'd replace step _6_ by writing an email including a link to that PR to the board and ask them for its approval. In this case the PR serves as a proposal. Once we have the approval of the board**, any of the WRC members is free to merge the changes into `official`.

A couple of important things to note about that workflow:
- There's no commit done to `official` directly. Every single change will be done using separate PRs (and therefore branches) and needs to be reviewed by at least one other WRC member or in case of a more drastic change approved by the WCA board. Letting the community review it by linking the PR on speedsolving.com might also be an option.
- We'll have only one main branch `official`**\* and several other feature aka proposal branches which contain small changes.
- `official` will reflect the current state of approved changes and is a very good approximation of what people can expect at the next release.
- All releases will be tagged (just like they already are) and the newest tag with the format `official-YYYY-MM-DD` will be the current official release. Naming them `official-YYYY-MM-DD` is great for automatically parsing the dates in `wca-documents-extra`. Release candidates can be tagged with something like `official-rc-YYYY-MM-DD`.

\* Adding the issue number to the branch provides us with the following benefits:
- Auto-completion in the shell becomes much easier. All you need to know is the issue number, no need to look up the branch name on Github.
- By looking at the branches you immediately see which ones are associated to an issue (the ones looking like `[\d]+-.`) and which ones are just floating around.
- _I had a third one in mind, but forgot it by the time I got here_ :cactus:

*\* This might end up in some discussions and several improved proposals. Just like with regular code reviews.

**\* We might also use a `draft` branch instead of `official` and merge `draft` into `official` right before the release (in software development these two branches are often called `develop` and `master`), but I don't think that overhead is necessary. Once the board approves of a change it's official and I think it's reasonable that it ends up in the `official` branch. If people expect the repository on Github to be an exact copy of the current release we should probably consider using `draft`, but it'd be also nice to have a quick glance at the current state of the changed regulations by visiting cubing/wca-documents without changing to `draft`.

Finally, @cubing/wrc-team what are your thoughts? Do you have any concerns? Did I make myself clear? I've been using this workflow for some time now in software development and it works really really well. So, I'd like to establish it here as well. It keeps the discussions and changes in one place, provides documentation of how a specific change ended up in the `official` branch and provides a way to catch errors early by requiring other people to review every (small) change.

**Comment by timhabermaas** [comment]
I forgot to mention: We could (should?) also update a `Changelog.md` in every PR. So if you fix something, you'll add a short description to the `Changelog.md`. After merging the issue 23 the `Changelog.md` would look something like this:

``` markdown
Next release
---

* Allow Best of 3 for FMC [#150]
* Fix "team team" typo [#23]

2014-01-01
---

* ...
```

This would help keeping the work required right before a release to a minimum (it could be as simple as tagging a commit) since the changes are already written out. Of course, this would require the contributor + reviewer to keep an eye on the changelog as well.

**Comment by lgarron** [comment]
Some issues with that:
- Constant merge conflicts.
- Allowing everyone to come up with their own explanations will not be as consistent. I'd be uncomfortable trying to change something that is nearly correct, but overall I'd prefer consistency.
- Changes should be associated with a short explanation. The relevant explanation may depend on ancillary discussion.
- It changes the repo from focusing purely on the text of the Regulations (and Guidelines).

**Comment by timhabermaas** [comment]
You have a point with the merge conflicts and inconsistent explanations. Writing a changelog by hand might not be as bad as I imagined when using milestones in order to filter all closed PRs.

**Comment by lgarron** [comment]
Indeed. I used the tag `announcement-worthy` to keep track of things for 2014.

**Comment by Laura-O** [comment]
Closing this issue in favor of #317
