### ISSUE TITLE
Puzzles Committee

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#151]
A brainstorming idea by Olivér Perge on the Delegate list, January 09, 2014:

> It may be a crazy idea, but is it possible to have a committe something like WPC (WCA Puzzles Committe)? They would be a group of expert speedcubers who know most varieties of the official puzzles and would help the decision making by testing them and give us exact facts as proving one side or the other.
> 
> What I have seen is that a big number of delegates are concerned of the regulations because they don't have anything to back it up (like Lorenzo said, no facts are given for understanding), we only have opinions and assumptions, but this way we would have tests to see if there is a significant reason to ban: pillowed, transparent, painted, tiled, different colored, etc. puzzles.
> 
> I understand that they give different results to different people, so if even one member of the committe would get a better result, it would mean that there is a risk of getting and advantage so it should be considered. Also I don't know yet how to measure such thing, as they would either have to do a large amount of number of solves to get consistent or would need to find a way for comparison other than doing averages.
> 
> Now I don't say it should happen from a week to another, but it might be something to consider in the long run. WCA is getting huge and I think it is better to have more source to rely on.

My response:

> I'm not sure precisely what you mean, but some the responsibility for knowing about puzzles should rely on the WRC as long as it is part of the Regulations.
> 
> I often send emails to this list trying to get feedback about what kinds of puzzles are used and what issues I have come up. There aren't a lot of responses, so I can't tell if there just aren't many things going on, or whether the email list format is just bad at producing responses.
> 
> Regarding the suggestion: I'm afraid that measuring times will be very difficult, since there is no way to do blind testing of sighted solves. It is also not clear that an advantage/cheating is as simple as "you can get a faster time". I don't think it would be reasonable to allow a 6-textured cube for BLD, even if many cubers would be slower feeling for textures than doing a proper blindsolve. I consider the use of stickerless cubes qualitatively similar, but way less extreme.
> Right now, there is no single person/policy in charge of cubes, only the guidance of many personal opinions. We're all seeing the result of an attempt to clean things up.
> That said, we _do_ need to work on a good way to evaluate what puzzles should be allowed, especially if we want to be more flexible. A dedicated group of people may be useful.

Something to consider.

**Comment by iVinshe** [comment]
I'm going to add-in some Tyson-related notes:
- The WCA could have an approved list of puzzles. Delegates will only have
  to make judgment calls on heavily modified puzzles.

If you want to go further, manufacturers could apply for approval for a
nominal fee.
