### ISSUE TITLE
Remove exception from A6g+

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#152]
A6g+ says:

```
While he is determining whether to assign a penalty for misalignment, the judge should not touch the puzzle. Exception: For Clock, the judge will usually need to pick up the puzzle to verify both faces.
```

I propose removing this exception.
1) It sounds like the judge picks Clock up only to determine misalignment, but there is no misalignment for Clock.
2) So what the judge actually does is checking if the puzzle is solved or not. So he usually does (or should do) it in any other events (especially in big cubes (especially in big cubes bld)).

**Comment by lgarron** [comment]
Hmm, that's a good point. I'll think about what to do with that, since our "exceptions for specific puzzles" are not properly structured in all places.
