### ISSUE TITLE
A6a: Stopwatch phrasing

### ISSUE THREAD

**Issue by Ilkyoo** [thewca/wca-regulations#153]
A6a) The competitor stops the solve by releasing the puzzle and then stopping the timer. The judge stops the stopwatch as soon as the competitor does this.

Even though A6a1) and A6a2) clarifies, I think changing the phrasing to something like 

A4d3) If a stopwatch is in use, the judge starts the stopwatch as soon as the competitor starts the solve.

For example:
NEW A6a) The competitor stops the solve by releasing the puzzle and then stopping the timer. If in use, the judge stops the stopwatch as soon as the competitor does this.

Opinion by Dene Beardsley. 
See also email thread.

**Comment by lgarron** [comment]
While getting all these details right is a bit pedantic, we do try to keep them correct, so this is definitely a typo. I've added it to the uncontroversial fixes for next release.

**Comment by Ilkyoo** [comment]
Thanks, Lucas.

-- ILKYOO
