### ISSUE TITLE
Update Puzzle Regulations (Article 3) after feedback from Regs 2014 ["Almost Anything Goes"]

### ISSUE THREAD

**Issue by SAuroux** [thewca/wca-regulations#155]
# Proposal

I have created a proposal version for Article 3, taking into account both feedback from the community and from the delegate mailing list:

https://github.com/cubing/wca-documents/compare/almost-anything-goes

The main goals of my proposal are simplification, better applicability, less arbitrariness and more consistency.

---
# Major key points:
- As before, Regulation 3m is the most important regulation of Article 3: if a puzzle fulfills all other regulations, the puzzle can be used in competition.
- Some vague/impracticable terms like "basic concept of a puzzle" or "make any additional information available" have been removed without replacement. As a direct result (3m), puzzles that have not been allowed for a long time would be allowed in the future, i.e. "pillowed" cubes or "stickerless" cubes.
  - Justification: Simplification and consistency. While those puzzles do undeniably provide a _theoretical_ advantage because of making more information visible, a _practical_ advantage is very questionable and at most marginal and thus negligible.
- A thickness limit for tiles is no longer defined.
  - Justification: Simplification and consistency. While thick tiles do undeniably provide a _theoretical_ advantage because of making more information visible, a _practical_ advantage is very questionable and at most marginal and thus negligible.
- "either" in 3d, "with uniform texture" in 3d2, 3d4 and "self-applied markings" in 3j have been added to cope with corner cases and possible abuse of the newly provided freedom.

**Comment by sarahstrong314** [comment]
What was the reason for removing 3h4? It was added this year to clarify that any custom clock inserts must function the same as the traditional inserts (i.e. have a clear indication of 12 o'clock). By removing it, clocks with custom inserts with no indication of 12 o'clock can have four different solved states.

**Comment by SAuroux** [comment]
Which is already not possible because of 3a3...
Am 01.02.2014 19:17 schrieb "Sarah Strong" notifications@github.com:

**Comment by sarahstrong314** [comment]
I don't think 3a3 is entirely clear about a clock being solved in different orientations. From each of the four angles on a clock with solid colour inserts, the moves, states and solutions are functionally identical to the original puzzle. I think it'd be safe to clarify that every clock insert must have one clear and consistent direction of 12 o'clock.

**Comment by SAuroux** [comment]
4 times as many solves states is obviously not the same states. ;)

2014-02-02 Sarah Strong notifications@github.com:

**Comment by sarahstrong314** [comment]
I can't seem to word what I'm trying to say. 
How about this: one could deliberately make it unclear which direction is 12 o'clock is, and insist that it was whichever of the four directions the hands ended up pointing to. 

Anyway, if it's anything it's a just a minor loophole. There are bigger things to be concerned about the puzzle policy.

**Comment by Laura-O** [comment]
The branch has been deleted, so I am closing this issue.
