### ISSUE TITLE
Whitelist of Approved Puzzles?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#157]
Tyson brought this up at the Delegate meeting at Worlds, and it comes up from time to time.

I don't want to encourage discussion on it any time soon, so I won't lay out detailed arguments for/against this right now, but I'm filing this issue to keep track of general awareness in case the WCA starts taking the possibility seriously.

References:
- [speedsolving.com post in a puzzle discussion](http://www.speedsolving.com/forum/showthread.php?46136-Towards-quot-Anything-Goes-quot-%28WCA-Puzzle-Policy%29&p=952651&viewfull=1#post952651)
- Puzzles Committee: #151

I'd like to note that any future decision to go down this path should at least be met with community understanding. Any attempt to implement it should be serious, rather than a case of "let's try this".

**Comment by Laura-O** [comment]
Keeping a whitelist up-to-date seems unrealistic, a blacklist would be more reasonable.

However, the number of puzzles which could be black-listed and which are not obviously illegal (like transparent puzzles) is quite small. The only recently released puzzles I know are a 5x5 with an overlay logo on a corner, and the phantom cube with chrome stickers.

If someone thinks we should keep track of these puzzles and volunteers to do that, please open this issue again. :smile:

**Comment by lgarron** [comment]
> If someone thinks we should keep track of these puzzles and volunteers to do that, please open this issue again. 😄

Agreed. It seems there is no appetite for this otherwise, and most new cubes being produced for speedcubers are "clearly"† okay. :-)

† I have some qualms about magnetic cubes, but it seems clear that competitors are not using them to cheat.

**Comment by KitClement** [comment]
The current Hays7 situation has made me think about a policy like this again. The fact that this puzzle has been available to only elite cubers makes me wonder if maybe a blacklisting policy on puzzles like the Hays7 are needed when manufacturers are giving certain competitors the advantage of this new puzzle for a significant amount of time. US Nats will have three competitors with this puzzle this summer, and this seems like a ridiculously unfair advantage -- nobody can even possibly compete with them given how much better this puzzle is than hardware that is available to the public.

Enforcement is a major issue for anything like this, as previously stated in this thread. It's difficult to identify puzzles as it stands, but at least in these pre-release situations, we're likely to know who the main competitors would be that possibly could have one.

**Comment by lgarron** [comment]
Here's a wild idea I brought up in a [WRC thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wca-wrc/L7QfbrzDbes/Fp2D_KJiBwAJ).

> We can do something about this when it comes to "mass-manufactured" cubes. In particular, we can consider *using it to make money to put back into the community/competitions*. Companies sometimes have bounties and payouts that incentivize contributing to charity, so some ideas might be:
> - Allow cubes from major manufacturers with limited availability as long for a limited time until the manufacturer makes them generally available, possibly for a fee.
> - Also use a model like this for world record bounties! We can either require or strongly encourage contributing to a WCA fund as part of those "win a prize if you set a world record with our cube" payouts. If done well, this helps PR for the manufacturer for them *and* the WCA.
> If we use such funds towards a particular efforts like helping new nations develop a cubing community, we can make sure that the "elite" privileges benefit those who need it most.

We can also require/encourage such puzzles to be tested in times of the year farther from major championships, so that they are required to become generally available for the championship in order for anyone to be allowed to use them.

This kind of approach requires some careful thought from a marketing and finance perspective, but I think it's possible to make it work.

**Comment by lgarron** [comment]
Oh, also: if we have standard sponsorship contracts, we can include clauses about puzzle availability in order to be allowed to sponsor certain competitions.

**Comment by xsrvmy** [comment]
From a different perspective, the hays 7 does not the reason Feliks, Max and Kevin are top 3. They have been top three all along. The only thing the hays 7 does is to make the ranking gap extremely large. Also I do not believe anyone else with a reasonable chance at podium is going to Nats. At least I am not.

I do not believe that hays 7 is a massive advantage either. I got WR4 with a wuji M with compressed springs.

Also, banning a pre-released puzzle only at a major competition is actually a disadvantage to the competitors that have actually received them.

Finally, "mass-produced" can be hard to define. A product can be released in China then take two weeks to get to the US/Canadian market.
