### ISSUE TITLE
Do a sort of case study of Skewb?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#159]
I think the international interest in Skewb has shown that it was [a good choice to add](https://github.com/cubing/wca-documents/issues/102).

(The main problem I see is that records are low/lucky, but that was clearly going to happen, and we have experience with this in 2x2x2 and Pyraminx.)

We can probably take a look at the benefits and drawbacks generated by adding the first really new events since 2007, and use that to inform the procedure for considering future events.

**Comment by Laura-O** [comment]
No case study since 2014, so as long as someone suddenly volunteers, I am closing this. :smile:
