### ISSUE TITLE
Require the competitor to notify the judge when twisting a corner?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#161]
Or at least recommend it?
- This can help competitors run into allegations of (potential) cheating, since it becomes a more serious offense to sneak it past the judge.
- Not backwards compatible for competitors who don't keep up with the Regulations in detail.
- Possibly require for puzzle repairs in general?

**Comment by lgarron** [comment]
See the [TCG Arequipa 2014 report](https://groups.google.com/forum/#!msg/wca-delegates/qlfe7g-QArY/0ujBtDRmvw0J) for a suggestion to allow corner twists only at the end of a solve.
Also, an earlier discussion about the same competition: [part 1](https://groups.google.com/forum/#!searchin/wca-delegates/Corner$20twisting$20case/wca-delegates/JOYhOB0-DNk/eXETBEEOkvgJ) and [part 2](https://groups.google.com/forum/#!searchin/wca-delegates/Corner$20twisting$20case/wca-delegates/4VgxXwzhgYY/KbsLSXvWoz0J).

This came up again [on Oct. 18](https://groups.google.com/forum/#!msg/wca-delegates/ZceBa22Nkwk/EKmLgomdessJ).

**Comment by KitClement** [comment]
Might seem obvious, but I guess we should put this to a vote:

### Should competitors notify the judge for a puzzle defect?
- Yes, required
- Yes, recommended
- No

### Should this cover all puzzle defects, or just corner twists?
- All defects
- Corner twists only

**Comment by Samuel-Baird** [comment]
I would imagine requiring competitors to inform the judge that they have a corner twist before twisting the piece would be very distracting. I definitely wouldn’t mind adding this as a reccomendation but for the time being I don’t think we should add it.

**Comment by xsrvmy** [comment]
Two issues:
What if a competitor feels a twist in mbld and wants to twist it back?
This needs to be clarified to not apply to fmc for obvious reason
