### ISSUE TITLE
Can an FMC judge also be an FMC competitor?

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#165]
Just a thought. I can't find anything in the Regulations that say that a someone judging FMC can't also compete in it.

**Comment by lgarron** [comment]
Is there anything against a competitor judging themselves for  speedsolving?»Lucas Garron

**Comment by sarahstrong314** [comment]
Common sense for speedsolving events, I suppose, but for FMC the judge has few responsibilities and could easily compete without breaking any rules.

**Comment by Laura-O** [comment]
This question is still asked frequently: https://groups.google.com/d/msg/wca-delegates/G6cvoSV1g3I/_OymNqnLBwAJ

Although 1h) does not clearly forbid to be judge and competitor simultaneously, fulfilling both roles at a time is rather unusual. I think we should finally clarify this in a guideline for E2a)
