### ISSUE TITLE
Example Puzzle Page

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#168]
A page on the WCA website with images of specific puzzles, accompanied with clear labels of whether they are legal, along with a brief explanation of why/why not.

There are always a lot of question about what puzzles are legal, and I think this is not going to change any time soon. The best way to show how to interpret the Regulations is to give examples that are clear to everyone.

The page would probably be at https://www.worldcubeassociation.org/regulations/puzzles/
It could also be, like, a Tumblr site, a forum thread, or part of the [announcements feed](https://www.worldcubeassociation.org/regulations/announcements/); some of these make it easier to "ask" about a puzzle. However, I think it would be best to have a single page where we have a complete, organized listing (with some navigation, and hopefully some reasonably compact layout).

**Comment by Laura-O** [comment]
What about using a GitHub wiki page for this?

#### Pros:
- Easy to edit, design and structure with simple Markdown. I can't compare this with the features of the WCA website (obviously the WCA website has Markdown support as well? https://github.com/cubing/worldcubeassociation.org/issues/100), but I often use Git wiki pages for work and I think it's a really good and easy way to present information.
- Every repository collaborator can edit without having access to the WCA website.
- It's probably better to mention specific puzzles and brands here than on the official site, e.g. to avoid any assumptions that a mentioned legal puzzle is an official recommendation.

### Cons:
- Nothing I can think of, despite it is not the official website. ;-)

Anyways, if there are no objections I would start to collect example puzzles.

**Comment by lgarron** [comment]
Now that we're starting work on this, I have a large collection of pictures to use.

To copy the comment from issue #419, I think we should aim for something like the Material Design guidelines: https://material.io/guidelines/motion/movement.html#movement-movement-within-screen-bounds

**Comment by AlbertoPdRF** [comment]
Ok, so let's continue here :)

First, I'll quote my post, so the conversation makes sense:

> Here I am with an idea:
> 
> ![draft1](https://cloud.githubusercontent.com/assets/26309166/24841169/bebc8468-1d7d-11e7-8101-fd31f526810b.jpg)
> 
> I think it's pretty simple, and that's why I like it :P I'll explain it a little in case that it's not clear (my drawing skills are not the best)
> 
> So, we'll have images of all the cubes ordered for instance by release date and, when an image is selected, it goes bigger and displays the name of the cube, a green or red frame depending on if it's legal or not, and maybe a little explanation below all the images but still inside the "box" where all the images are. The "box" is intended to be the same as we use for the main page of the WCA, just to keep the website homogeneous. Also, the frame and the names of the cubes could be displayed for all the pictures, and not only for the bigger one.
> 
> What do you think about it?

And now, I'll answer the other comments:

> I think it won't be easy to navigate, especially on a phone.

I don't think that this kind of design is hard to navigate, neither from a PC or from a phone, as I'm used to it, but sure we can find something that is easier.

> We should also not focus on specific cube types, but archetypes of edge cases.

Yep, I also think that putting all the cubes on the web will be a nightmare, for us and for the people that will use the web, so we better focus on archetypes of edge cases.

> I suggest copying the Do/Don't layout from Material Design: https://material.io/guidelines/motion/movement.html#movement-movement-within-screen-bounds

I think that the Do/Don't from Material Design is cool, but it will break all the homogeneity of our web. Maybe I'm taking your comment too literal, and you just mean to adapt it to our style :)

I'm not responding to the comments from @Laura-O as I don't have anything new to add, but I'll quote them just for completeness:

> Thanks for making this draft, @AlbertoPdRF.
> I agree with Lucas' comment: showing every single puzzle and model is too specific and will be nearly impossible to keep up-to-date. The number of puzzle released every month is huge and we would have to review these puzzles before we can put them on the website. On the one hand, this takes a lot of time. On the other hand, my experiences with cubing manufacturers and their willingness to cooperate with the WCA are not that good.
> 
> Apart from that, the draft is obviously for the puzzle section only, so as Lucas already suggested, we should move that to #168.

I just want to add that I'm surprised that the manufacturers don't want/don't like to cooperate with the WCA.

@lgarron Where can I see those pictures? :)

**Comment by Laura-O** [comment]
Ping @lgarron

**Comment by lgarron** [comment]
Most are here:

https://www.dropbox.com/sh/8xgc4ma0r1dlyfl/AAACJQmZp5KPaXPN3-FhxOe7a?dl=0 (Look in the "From the internet" folder.)
https://www.speedsolving.com/forum/threads/border-case-puzzle-brainstorming.46185/

**Comment by UnderwaterCuber** [comment]
I would love to see something like this created :)

**Comment by ohexter** [comment]
Closing this inactive old issue without further action. The original aims were somewhat addressed by the [3j visual guide](https://drive.google.com/file/d/1m6THsA8fXRN7QFM4ApJbm6eVODKGbMLx/view).
