### ISSUE TITLE
Delegate/Community Voting

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#169]
Right now, I believe that a complicated protocol for changes (#108) isn't as important as making sure that enough people take the time to think about a big change before it becomes finalized. If something is put to a Delegate vote with proper pros/cons, I'm confident that we will make reasonable decisions.
Here's a rough outline for handling an important topic:
- Gather the main ideas/concerns/proposals for a certain topic.
- Start a discussion on the Delegate list, explaining that this topic will be put to a vote.
  - i.e. "This is serious. If you have something to say, say it now, or it won't go into the proposal."
- With the help of the community/Delegates, the WRC submits a proposal containing the following (see the first post of issue #106):
  - An _exact_ set of proposed changes (i.e. a `git` diff)
  - A list of pros
  - A list of cons
  - A list of community considerations
- Hold a vote for a set period of time (1 week?)
  - Each person who has one of the following roles gets one vote: Delegate, Board member, WRC member
  - Each vote against the proposal must include the major "con" that influenced the decision (because proposals take a lot of work, and this allows future proposal to learn why previous ones failed).
  - Everyone's votes (and reasons) are completely public.
- The Board makes an ultimate decision on whether to accept or reject the proposal, but is expected to follow the majority of votes unless it is close to a tie.

There are some details to be figured out:
- Can "minor" details be tweaked if they come up after the start of a vote?
- What is [quorum](https://en.wikipedia.org/wiki/Quorum)?
- Do we need timelines (e.g. some number of weeks for feedback before the vote can begin)?
- What if there are more than 2 reasonable choices rather than a decision about whether to make one specific change?
- How to hold the vote. I propose the following, because it is practical and doesn't require us to use something new/untested:
  - Create a new subforum on the [WCA forum](https://www.worldcubeassociation.org/forum/) with the following permissions:
    - The WRC can create threads/polls.
    - Every voting member can vote and post in voting threads.
    - Every member of the public can view the entire subforum.
  - Each poll includes a simple accept/reject/abstain option for the proposal (to avoid biasing the main vote). In addition, I'd like to find a way to force "votes are accompanied with a reason". There are at least a few crude ways to accomplish this, which I don't think we need to discuss right now.

**Comment by lgarron** [comment]
As a test, I think the first votes should be on the following topics:
- Adding back Best of 3 for FMC (#109)
- Retroactive records for FMC Mean of 3 and 3BLD Mean of 3 (#170).

Eventually:
- Puzzle changes (stickerless/pillowed/"anything goes"). This would take a while to prepare.

**Comment by lgarron** [comment]
Some thoughts on who should vote:

## Why Delegates
- Delegates have the most experience with the Regulations and how to enforce/interpret them.
- Delegates are already a specially vetted set of people involved with the WCA.
- Delegates are privy to more detailed discussions on the Delegates list, often related to specific incidents that can addressed with Regulation changes (I don't like this, but I'm not sure we can change that very soon).
- Delegates are an _international_ set of community members, and can connect us to parts of the world who don't participate on English-speaking forums.

## Why Not Delegates?
- Some Delegates have limited experience.
- If discussions are not fully open for public participation, this limits the ability of experienced competitors from "cubing-dense" regions to contribute.
- Delegates may have biases that don't align with organizers, competitors/the community, and the general public audience of the sport.
- If Delegates become a body with special privileges like legislation (e.g. more of a "senate"), then the incentives for becoming a Delegate may change.
  - This is unlikely to be a concern in mid-2014, but we should be careful about going down that path.

## Board and WRC Members

Most Board/WRC members are also Delegates, so allowing them to vote wouldn't change much.
My main reason for stating that all Board/WRC members should vote is so that their stance is revealed publicly, in the same way as every voting Delegate.

If votes are secret, I don't think it's important for them to be allowed to vote, but I would like as much transparency about voting as possible.

**Comment by lgarron** [comment]
I originally suggested Delegates because this is a natural extension of the current _de facto_ system, and is fairly straightforward.
However, the most common concern about the idea of voting on WCA proposals is limiting it to Delegate voting. Erik has been vocal about his concerns in [this thread](http://www.speedsolving.com/forum/showthread.php?47039-Puzzle-Changes-painted-printed-colours-and-1-5mm-tiles-for-all-puzzles&p=972270&viewfull=1#post972270). I don't agree with all his concerns, but I agree that it would be nice to have a way to give a voting voice to experienced members of the community.

I was discussing this with @KitClement, and he gave the most reasonable suggestion I've heard so far:
- Allow one vote for each competitor who:
  - out of all competitors in their region _ranked by number of competitions attended_, is in the top X% (e.g. region=continent, X=5)
  - has been to at least one competition in the past year

This is definitely not perfect, but I won't discuss merits/concerns in this comment.

**Comment by UnderwaterCuber** [comment]
With all of the controversies in recent years I would definitely love to see a way for the community to vote on potential reg changes

**Comment by ohexter** [comment]
Closing this old issue without further action. The WCA continues to refine its governance. The WCA Regulations currently require approval by the WCA Board. The WRC collects and reviews Staff and Community Feedback when preparing amendments to the Regulations.
