### ISSUE TITLE
Retroactive records for FMC Mean of 3 and 3BLD Mean of 3

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#170]
Splitting out as a separate topic from #148.

This should go to a Delegate vote (#169).
I will vehemently argue against anyone who says it is "too late" to undo this.

**Comment by Claster** [comment]
They are already recognized, right?
Or probably I just don't understand what "recognize" means.

**Comment by lgarron** [comment]
They are currently recognized, but this is because the person who updated the historical records did so, and my request to change it back stalled.

Hence my statement that we should have a Delegate vote on whether these should be recognized.

**Comment by Laura-O** [comment]
Although Lucas mentioned he would argue against anyone saying this is "too late," it definitely is too late now (3 years after this issue was created). :older_man:

**Comment by jfly** [comment]
Oh, but we actually have the infrastructure to run delegate polls now!

**Comment by Laura-O** [comment]
@jfly You are kindly invited to write the proposal for this poll. :stuck_out_tongue_winking_eye:
