### ISSUE TITLE
Stickerless Puzzles

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#177]
I like my stickerless cube as much as the next guy, but our policy has always been conservative. It's been hard to have an objective discussion, partially because a lot of competitors simply want to use them (which is fine!), and are not always very sensible about expressing their reasons and discussing them (which is... unproductive).

(Note: Some stickerless puzzles are already allowed. For simplicity, this issue refers to "stickerless" puzzles with internally visible colors, like the Dayan cubes)

Here is an attempt to collect official reasons for and against allowing stickerless cubes:
## Reasons for Disallowing
- Stickerless cubes have qualitiative visual [advantages](https://github.com/cubing/wca-documents/issues/176):
  - During normal operation, extra colors on the back/sides of pieces are easily visible:
    ![img_3453](https://cloud.githubusercontent.com/assets/248078/2784741/2aae06fa-cb43-11e3-8842-978860627518.JPG)
    ![stickerless](https://cloud.githubusercontent.com/assets/248078/2784749/3d86866c-cb43-11e3-95a2-ed85425b6dd5.jpg)
  - Colors on the backs of all pieces may be easier to see (e.g. the side colors of back pieces during PLL).
    - This is not a big problem with current stickerless puzzles, but we'd need to make sure that future puzzles don't take this to an unreasonable level.
  - Colored parts span the entire sides of cubies (and into the puzzle), which makes it easier to focus on the colored parts. It is possible to approximate this using stickers, but in practice stickerless puzzles make this easier.
    - This is a subjective advantage, but it _is_ a slight advantage, and may be a useful point of comparison when discussing advantages of other puzzles.
- Our main event is about solving the Rubik's Cube. We should be careful about changes that diverge from ["basic concept"](https://www.worldcubeassociation.org/regulations/history/official/2013-05-21/#3h) of the puzzle. Current stickerless puzzles seem pretty tame, but they might enable new changes to the design (e.g. shape) of the puzzle that no one has anticipated yet. (Especially if we also allow more variation in pillowing and tile dimensions).
- The WCA puzzle policy is conservative, and disallowing stickerless puzzles is the status quo.
  - Allowing stickerless puzzles without permitting other kinds of puzzles (e.g. pillowed) may itself be criticized – for being inconsistent or because competitors want even more choice in puzzles. It is probably better to consider Article 3 as a whole (#173).
  - The current policy is not an objective reason to discourage change, but it means that the failure to adopt a proposal for change means... nothing changes. 
## Reasons for Allowing
- Stickerless puzzles are popular, and some competitors certainly would prefer them.
- The visual advantages are not especially big, and are more of an incidental part of the design and use of the puzzles.
- If all competitors are allowed to use stickerless puzzles, they all have a "fair" chance to use this advantage.
  - This argument may not hold in general – a competitor with a decent "standard" speedcube should not need to buy a different style of puzzle to stay competitive. But given the point about speed below, it is reasonable to allow competitors to use their preference.
- It does not appear that _fast_ competitors get a significant speedup from using stickerless cubes.
  - It's unclear if slower competitors might, but this is arguably not important.
- No stickers: Competitors do not need to purchase/replace stickers in order to maintain stickerless cubes. (via [cube-o-holic](http://www.speedsolving.com/forum/showthread.php?46136-Towards-quot-Anything-Goes-quot-%28WCA-Puzzle-Policy%29&p=972178&viewfull=1#post972178))
- No stickers: Pieces are harder to distinguish by touch (compared to worn/cracked/slightly displaced stickers). (via [cube-o-holic](http://www.speedsolving.com/forum/showthread.php?46136-Towards-quot-Anything-Goes-quot-%28WCA-Puzzle-Policy%29&p=972178&viewfull=1#post972178))
- No stickers: As long as the sides do not have prominent marks/scratches, it would easier to tell that a stickerless cube is competition-legal.

**Comment by lgarron** [comment]
Just came across this video: [Noah demonstrates that you can memorize a cube without ever looking at the bottom/back](https://www.youtube.com/watch?v=RiPpc9Bh0gc).

This is an advantage, although it's perfectly fine to say that the advantage is not very useful. In particular, I could see an argument that this doesn't matter much because it can't save a significant amount of time. (However, just because we haven't seen anyone use it to save time doesn't prove anything about whether it's possible.)
I think the best justification would be that we're willing to take the _risk_ that this can save competitors time. I would like to say that we can reconsider it if we notice competitors using it, but I think it would be a hard decisions to reverse. Another solution is not to allow stickerless cubes for BLD.

**Comment by pedrosino** [comment]
I think that the "more information is visible when the layer is at 45 degrees" thing is not very strong.
I dont' believe that could actually be used to gain an advantage, at least not at 6-seconds solves where you can barely see what people are doing, even if it's slow motion.

Considering the benefits (people like the plastic/feel/look of the cube, no stickers) I think they should be allowed.

**Comment by lgarron** [comment]
For the record: Kit sent an email to the Board today asking whether they would be in favor of considering stickerless cubes.
This wouldn't be a guarantee that they would be legal, but hopefully the intention to try to allow them will help focus the discussion on more important issues instead.

**Comment by ghost** [comment]
http://prntscr.com/9acdr2 I thinks is legal to use stickerless cube.  The main reason why I believe this: The WCA regulations say so.

**Comment by lukasjuhrich** [comment]
@TimMm3105 I think you don't realize that this is the very issue which lead to that point. See the referenced commit above (https://github.com/cubing/wca-regulations/commit/238ff5cd0ac093c5a0dfb1eda6e6e2727ade8c12).

**Comment by myrdinwylt** [comment]
I think that the advantage that stickerless cubes give is not much considering the fact that while speedcubing you will not spend to much time looking at the the corners to see the colors of other pieces.

**Comment by AlphaZetta** [comment]
Why was this a thing

**Comment by lgarron** [comment]
> Why was this a thing

We were evaluating whether stickerless puzzles should be allowed in the WCA Regulations, and how we could make it clear what would/wouldn't be allowed!
