### ISSUE TITLE
Filming/Recording Devices/Smartphones

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#178]
Under what circumstances should a competitor be allowed to film himself?
- The competitor bringing a small camera to the table.
- A competitor [filming using one hand while using the other for OH](https://groups.google.com/forum/#!searchin/wca-delegates/OH$20film/wca-delegates/EJDNqsGIVjg/BWTfr9QmuV4J).
- A [GoPro camera mounted on the head](https://groups.google.com/forum/#!topic/wca-delegates/-g2MJLXzFcE).
- Tripod in the audience
  - Can (s)he adjust this (before each solve) to point at the next solving station?
- Google Glass?
  - There are probably a few reasons this shouldn't be allowed. In particular, it's impossible to tell if someone is receiving assistance.

We have a strong tradition of allowing solves to be filmed, and close-up solves are great for reconstructions (which are very popular now). I don't see anything wrong with allowing most of the kinds of filming I've seen at competitions.

In addition to being a distraction/advantage during the solve, recorded video can easily be shared from a smartphone to any competitor. However, anyone in the audience also has that ability.

**Comment by lgarron** [comment]
I believe we should allow filming if:
- the competitor does not interact with the device between [beginning of the attempt](https://www.worldcubeassociation.org/regulations/#A3b2) and [stopping the solve](https://www.worldcubeassociation.org/regulations/#A6a), and
- it it does not provide the competitor an advantage during the attempt.
  - In particular, the camera must not have a live LCD display facing the competitor curing the attempt.

Minor consideration: would a competitor be allowed to restart a camera during a long multi BLD attempt?

**Comment by KitClement** [comment]
Potential change that I proposed in the Cornell delegates thread, and updated a bit here to conform to Lucas' terminology of "beginning of the attempt" and "stopping the solve."

2i2) Competitors can use cameras at the solving station, so long as between the beginning of the attempt and stopping the solve:
  2i2a) Any live monitor or screen attached to the camera is out of sight of the competitor.
  2i2b) The competitior does not make any contact with the camera.

**Comment by lgarron** [comment]
I've added a change:

> - 2i2) Competitors may use cameras at the solving station, but the following restrictions apply from the beginning of the attempt until the competitor stops the solve. Penalty for breaking a restriction: disqualification of the attempt (DNF).
>   - 2i2a) Each camera monitor must be blank or out of sight of the competitor (see [Regulation A5b](regulations:regulation:A5b)).
>   - 2i2b) The competitor must not interact with (e.g. operate, touch, hold, wear) any active camera.

In the interest of clarity, this forbids any interaction with the camera, which pretty much bans GoPros.

I'm happy to take alternate suggestions 2i2b), as long as they are are clear enough to apply to _any_ recording situation a competitor might think of.

**Comment by lgarron** [comment]
Note: Even Felix is doing [POV vids](https://www.youtube.com/watch?v=qKTWn5QSRYM) these days.

**Comment by Claster** [comment]
What can go wrong if we remove 2i2b, leaving only 2i2a?

2014-12-21 14:23 GMT+03:00 Lucas Garron notifications@github.com:

> Note: Even Felix is doing POV vids
> https://www.youtube.com/watch?v=qKTWn5QSRYM these days.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cubing/wca-documents/issues/178#issuecomment-67767286
> .

## 

Best regards,
Oleg Gritsenko

**Comment by lgarron** [comment]
> What can go wrong if we remove 2i2b, leaving only 2i2a?

From the first post: "A competitor filming using one hand while using the other for OH."
They could also reach over to "adjust" or "restart" the camera, which can quickly devolve into a gray area.

The competitor should be performing a solve, not operating a camera. If we want to change it, we should make sure we only allow passive operation.
