### ISSUE TITLE
Puzzle Policy/Spirit?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#180]
e.g. an explicit Regulation in Article 3. A policy for "(almost) anything goes" might be:

> The WCA policy for puzzles is "almost anything goes". A competitor may use any reasonable variant of a mass-produced puzzle, as long as [something about not gaining an unfair advantage, except with something less vague than "unfair"].

**Comment by KitClement** [comment]
This seems like a reasonable way to modify regulation 3h.  I still like the text of "modifications that enhance the basic concept of a puzzle" verbage, so maybe we can just make this change:

3h) The WCA policy for puzzles is "almost anything goes". A competitor may use any reasonable variant of a mass-produced puzzle, as long as the modifications do not enhance the basic concept of a puzzle.  Modified versions of puzzles are permitted only if the modification does not make any additional information available to the competitor (e.g. orientation or identity of pieces), compared to an unmodified version of the same puzzle.
3h3) Any modifications to a puzzle that result in poor performance by a competitor are not grounds for additional attempts.
3h4) For Clock, custom "inserts" (the same shape and size as the traditional paper inserts) are permitted, at the discretion of the WCA Delegate. The inserts must have a clear indication of 12 o'clock that matches the original inserts.

It seems weird to use the same language, but I think that if we do say that competitors can use variants of mass-produced puzzles, then disallowing any _further_ information would still make stickerless/pillowed okay. 

The only thing I'm a bit concerned about are transparent puzzles, which could give quite a bit of an advantage if they became transparent enough that stickers could be seen on the other side.
