### ISSUE TITLE
Criteria for new events

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#183]
This comes up once in a while, and has a few details that distinguish it from [Regulation changes in general](https://github.com/cubing/wca-documents/issues/106).

I'm starting this to collect points we _may_ want to use to evaluate new puzzles.
- Community Interest
- Practicality
- Consistent with the [spirit and mission of the WCA](https://www.worldcubeassociation.org/about), as well as [Regulation 9a](https://www.worldcubeassociation.org/regulations/#9a) (though any of these _could_  change).
- Interesting to solve and watch (from [Sarah](http://www.speedsolving.com/forum/showthread.php?47301-The-quot-Why-I-hate-this-event-quot-and-quot-Why-this-event-should-be-added-quot-thread&p=974947&viewfull=1#post974947))
- A unique challenge compared to other events

Also see the addition of Skewb (#159, #102).

**Comment by Laura-O** [comment]
As I'd like to get rid of the old issue which will never be closed, I copied the criteria to a wiki page: [wiki/Criteria-for-new-events](https://github.com/thewca/wca-regulations/wiki/Criteria-for-new-events)
