### ISSUE TITLE
"Summary" of changes from 2010 Regulations to 2012 Regulations

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#187]
Here's a summary of the changes from the 2010 version of the Regulations to the 2012 version. It includes the new Regulations that were added (either as a whole new Regulation or as a part of an old Regulation) as well as all changes in numbering and significant changes to wording.

_• Art. 1a updated. Art. 1g2, 2j, 3l, 11d, 11e, 11f, A6b1 and A6bh updated. Removed main judges as officials. The Delegate now has former responsibilities of main judges.
• Art. 1b updated. Formerly Art. 1b1. 
• Art. 1c updated. The Delegate can delegate responsibilities to other members of the organisation team.
• Art. 1c1 updated. The Delegate report should include the overall course of the competition, and any incidents. It must be submitted to the WCA Board.
• Art. 1c3 updated. Art. 1c3a and 1c3b added. The Delegate sends the competition results to the WCA Results Team, along with all scramble sequences used in the competition, labeled with the event rounds, and heats for which they were used.
• Art. 1c9 added. The Delegate is responsible for any decisions about changes to the schedules times of rounds.
• Art. 1c10 added. Formerly Art. 1b2.
• Art. 1e1a added. A judge can judge multiple competitors simultaneously at the discretion of the Delegate.
• Art. 1h2 updated. Formerly Art. 4e. 
• Art. 2c1 added. The Organisation team determines whether a competitor is eligible to compete without a registration that does not provide all information required by them.
• Art. 2e updated. Competitors must represent a country in which they hold citizenship, and can be disqualified retroactively and/or suspended for being ineligible to represent a country under which they have registered.
• Art. 2h updated. Competitors can be disqualified from the competition for wearing inappropriate clothing, at the discretion of the Delegate.
• Art. 2j2 added. If a competitor is disqualified during an event, his results from earlier events remain valid.
• Art. 2s3 added. Competitors with disabilities, other than hearing and physical disabilities that can prevent them from abiding by one or more WCA Regulations can request special accommodations with the Delegate.
• Art. 3a1 added. Formerly partially Art. 3a. Competitors can be disqualified from an event for not being present and ready to compete when they are called to compete.
• Art. 3d1 updated. Competitors with a medically documented visual disability can use textured puzzles with different textures on each face.
• Art. 3i (new) updated. "Pillowed" and other modified versions of puzzles are permitted only if the modification does not make any additional information available to the competitor as compared to an unmodified version of the same puzzle.
• Art. 3i1 added. Clarified that pillowed 7x7x7 cubes are the only pillowed puzzles that are permitted.
• Art. 3i2 added. Clarified that "stickerless cubes" are not permitted.
• Art. 3j (new) updated. Formerly Art. 3i.
• Art. 3k (new) updated. Formerly Art. 3j.
• Art. 3l (new) updated. Formerly Art. 3k. 
• Art. 3m (new) updated. Formerly Art. 3l. 
• Art. 3m1 added. Colourless engravings (max. 1 per colour) are not considered logos.
• Art. 3n updated. Formerly Art. 3m.
• Art. 4b1 added. Generated scrambles must not be inspected before the competition, and must not be filtered or selected in any way by the Delegate.
• Art. 4b2 added. Formerly partially Art. 4b. Scramble sequences for a round must be available only to the Delegate and the scramblers for the event, until the end of the round.
• Art. 4d1, 4d2 and 4d3 added. The scrambling orientation for all puzzles.
• Art. 4f updated. Scramble sequences must be generated using the current official version of the official WCA scramble program.
• Art. 5a updated. Pieces twisted in place is considered to be a puzzle defect.
• Art. 5b1 updated. When a puzzle defect occurs and the competitor chooses to repair the puzzle, tools must not be used.
• Art. 5b3a added. When a puzzle defect occurs, a competitor is permitted to place back any pieces that have fallen out or moved out of place.
• Art. 5b3b added. Formerly Art. 5b3.
• Art. 5b3c added. After a puzzle defect has occurred, resulting in the puzzle being unsolvable but can be made solvable by rotating a single corner piece, the competitor can correct the corner piece by twisting it in place without disassembling the puzzle.
• Art. 5b5 added. At the end of an attempt, if parts of the puzzle are still defective or not fully placed, the worst possible state obtainable by reassembling the puzzle determines the result.
• Art. 7f1 added. Defined the parts of a solving station.
• Art. 7f2 added. The timer must be attached to the mat and placed directly on the table or desk, with the timer on the side of the mat nearest to the competitor. The mat must be placed flush against the surface of the table.
• Art. 7f2a added. For Solving With Feet, the timer must be placed directly on the floor, with the timer located on any side of the mat.
• Art. 7h1 updated. The organisation team can require that a competitor who has been called to compete must remain within the Competitors Area until he has finished all of his attempts for the round.
• Art. 7h3 updated. A competitor can be disqualified for communicating to other competitors about the scrambled states of the puzzles of the round in progress.
• Art. 8a4 updated. A competition must be announced on the WCA website at least two weeks (2010 version: one month) before the beginning of the competition.
• Art. 8a7 updated. Pro Speed Stacks Stackmat timers can be used.
• Art. 8a8 added. Competitions must be open to all who wish to compete. Restrictions must be approved by the WCA Board and clearly when the competition is announced.
• Art. 9a1 added. Formerly partially Art. 9a.
• Art. 9a2 added. Formerly partially Art. 91.
• Art. 9b1 added. Formerly partially Art. 9b.
• Art. 9b1a added. Formerly partially Art. 9c.
• Art. 9b2 added. Formerly partially Art. 9b.
• Art. 9b2a added. Formerly partially Art. 9c.
• Art. 9b3 added. Formerly partially Art. 9b.
• Art. 9b3a added. Formerly partially Art. 9c.
• Art. 9f9 updated. Formerly partially Art. 9f7.
• Art. 9f12a added. Defined "better" for timed results.
• Art. 9f12b added. Defined "better" for FMC.
• Art. 9f12a added. Formerly Art. 9f16. 
• Art. 9i2 added.  Results of official WCA competitions are dated to the calendar date of the competition. If a competition spans multiple days, the results of each round are dated to the last scheduled calendar date of the round.
• Art. 9p3 added. For an event with more than one round, if a qualifying competitor withdraws from a round, he can be replaced by the best-ranked competitor below the cutoff from the preceding round.
• Art. 9r1a added. Formerly partially Art. 9r.
• Art. 9r1b added. Formerly partially Art. 9r.
• Art. 9r1c added. Formerly partially Art. 9r.
• Art. 9r1d added. Formerly partially Art. 9r.
• Art. 10f1 added. Formerly partially Art. 10f.
• Art. 10f2 added. Formerly partially Art. 10f.
• Art. 10f3 added. Formerly partially Art. 10f.
• Art. 10f4 added. Formerly partially Art. 10f.
• Art. 11b updated. If an incident occurs, the Delegate determines an impartial and appropriate course of action.
• Art. 11e1 added. If a competitor is awarded an extra attempt, the extra attempt must be scrambled using a different scramble sequence, generated using the same scrambling program.
• Art. 12a1a added. Formerly partially Art. 12a1.
• Art. 12a1b added. Formerly partially Art. 12a2.
• Art. 12a1c added. Formerly partially Art. 12a3.
• Art. 12a2a added. Formerly partially Art. 12a1.
• Art. 12a2b added. Formerly partially Art. 12a2.
• Art. 12a2c added. Formerly partially Art. 12a3.
• Art. 12a3 (new) updated. Formerly partially Art. 12a1.
• Art. 12a3a added. Definition of Block Turn Metric
• Art. 12a3b added. Formerly Art. 12a19.
• Art. 12c2 added. Formerly partially Art. 12c1.
• Art. 12c3 added. Formerly partially Art. 12c1.
• Art. 12g added. Explained notation for Clock.
• Art. A1a updated. The organisation team can enforce time limits for attempts and/or rounds.
• Art. A1a1 added. For Speed Solving attempts, the default time limit is 10 minutes, but the organisation team can announce a different time limit.
• Art. A1a2 added. Cumulative time limits can be enforced, where the time elapsed in a DNF result counts towards the cumulative time limit.
• Art. A1a3 added. For each round, any time limits must be announced before the round starts, and should not be changed after it has begun. Changes must be made at the discretion of the Delegate.
• Art. A1a4 added. The competitor must end each attempt within the time limit. For all events, except Multiple Blind Solving, if a competitor reaches the time limit for an attempt/round, the result is a DNF. 
• Art. A1a5 added. For all events, except Multiple Blind Solving, an attempt is considered to meet the time limit if and only if the original recorded time, before any time penalties are applied, is strictly less than the time limit. 
• Art. A1b1 added. Formerly partially Art. A1b.
• Art. A1b2 added. Formerly partially Art. A1b.
• Art. A1c added. A competitor participating in an event must be able to fulfill the event's requirements. A competitor competing with expectation of a DNF result can be disqualified from the event, at the discretion of the Delegate.
• Art. A2c1 added. During scrambling, the scrambler places a cover over the scrambled puzzle that makes it impossible for any competitors or spectators to see any part of the puzzle. The cover remains over the puzzle until the beginning of the attempt.
• Art. A3b1 updated. The competitor must be ready to start the attempt within one minute of being called. Penalty: disqualification of the attempt (DNF), at the discretion of the judge.
• Art. A4d1 and A6i updated. Time penalties for starting a solve and ending the solve are both cumulative.
• Art. A6a1 added. If a stopwatch is in use as the timing device, the competitor ends a solve by releasing the puzzle and notifying the judge that he has stopped the solve.
• Art. A6a2 added. When using a stopwatch without a Stackmat, the competitor's default notification signal consists of releasing the puzzle(s) in his hand and placing his hands on the surface, with palms down. The competitor and the judge can agree on another appropriate notification before the beginning of the solve.
• Art. A6e updated. If the competitor touches or moves the puzzle at the end of the attempt but no moves have been applied, a +2 penalty can be assigned instead, at the discretion of the judge.
• Art. A7b1 updated. If penalties are assigned, the judge records the original recorded result displayed on the timer, along with any penalties. The format is "X + T + Y = F", where X represents the sum of time penalties before/starting the solve, T represents the time displayed on the timer, Y represents a sum of time penalties during/after the solve, and F represents the final result. If X and/or Y is 0, the 0 terms are omitted.
• Art. A7c1 added. If the competitor or the judge refuses to sign the score sheet, the Delegate can sign in their place.
• Art. A7f updated. If the result is DNF, then judge calls "DNF" (2010 version: "NO FINISH").
• Art. B1d updated. The competitor must use a puzzle without textures, markings, or other features that distinguish similar pieces.
• Art. B4c updated. For Blindfolded Solving, the judge must ensure that there is an opaque object between the competitor's face and the puzzle while the competitor is solving.
• Art. B4c1 added. For Blindfolded Solving, the competitor must wear the blindfold such that his view of the puzzle would still be clearly blocked if the opaque object were not in the way.
• Art. B4c2 added. For Blindfolded Solving, the judge should place the object between the competitor and the puzzle while the competitor is wearing the blindfold.
• Art. B4c3 added. For Blindfolded Solving, if the judge and competitor agree beforehand, the competitor can choose to place the puzzle behind a suitable object by himself during the blindfolded phase.
• Art. C1b updated. For One–Handed Solving, the competitor must use only one hand to touch the puzzle during the solve.
• Art. C1b2 updated. For One–Handed Solving, if a puzzle defect occurs, and the competitor chooses to repair it, he must repair it using only the solving hand. Using anything else results in a DNF.
• Art. C1b3 added. If a puzzle defect occurs, and pieces of the puzzle briefly come in contact with other body parts without the competitor's intention, this is not considered touching the puzzle, at the discretion of the judge.
• Art. E2b1 updated. For Fewest Moves Solving, a judge calls "5 MINUTES REMAINING" at 55 minutes, and call "STOP" at 60 minutes (2010 version: times are also announced at 30, 50 and 59 minutes).
• Art. Ed2 updated. For Fewest Moves Solving, the length of the solution is calculated in Block Turn Metric, not Half Turn Metric.
• Art. E3e1 added. Formerly Art. E2f.
• Art. E3 updated. Formerly partially Art. E3 and E3a.
• Art. E3a (new) updated. For Fewest Moves Solving, the judge supplies paper and pens.
• Art. E3b added. For Fewest Moves Solving, the competitor can use 1-3 self–supplied puzzles.
• Art. E3c added. For Fewest Moves Solving, the competitor can use self–supplied coloured stickers.
• Art. F2 (new) updated. Formerly Art. F2a.
• Art. F3 (new) updated. Formerly Art. F3a. For Clock Solving, if the competitor changes the positions of any pins from the scrambled position, he will receive a +2 penalty.
• Art. G1a updated. For Magic solving, the competitor can do at most two practise solves on the competition timer.
• Art. H1b1 updated. For Multiple Blindfolded solving, the competitor can signal the end of the attempt at any time. The time limit for the attempt counts as the original recorded time.
• Art. H1b2 added. For Multiple Blindfolded solving, when there are 10 seconds until the time limit, the judge calls "10 SECONDS REMAINING. PLEASE FINISH YOUR ATTEMPT". If the competitor is still holding any puzzles when the judge stops the attempt, they are judged as unsolved.
• Art. H1d added. For Multiple Blindfolded solving, time penalties for the puzzles of the attempt are cumulative._

**Comment by Laura-O** [comment]
@lgarron What's the source of those changes? I didn't know there was a regulation change from 2010 to 2012?

**Comment by sarahstrong314** [comment]
I don't know where the original is, but a copy of it is saved here:
http://www.stefan-pochmann.info/diff.html

**Comment by Laura-O** [comment]
Thanks for the clarification, Sarah.
However, the existence of 2012 Regulations confuses me. :confused:

**Comment by lgarron** [comment]
The 2013 Regulations were originally going to be the 2012 Regulations. Maybe we just accidentally referred to the 2013 ones as 2012?

**Comment by Laura-O** [comment]
Copied to Google Drive for the sake of consistency, so this issue can be closed.
