### ISSUE TITLE
Suggestion: Regulation A2c2

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#188]
I've noticed that when scramblers place Square-1s in covers, they are often "upside-down" because it's natural to place them in the (upside-down) covers in the same orientation as they were scrambled. This is a problem since this would cause square-1 solvers to rotate the puzzle one of the two natural orientations, during which it is very easy to accidentally turn the puzzle, resulting in a DNF if noticed.

So, I suggest the following to precede Regulation  [A2c1](https://www.worldcubeassociation.org/regulations/#A2c1):

A2c2) When the scrambler places a cover over a scrambled Square-1, it must be placed such that the Square-1 will have the the smallest slice of the middle layer on the left side at the beginning of inspection.

**Comment by Claster** [comment]
Umm, what? A competitor rotates a puzzle, thus turning it accidentally? Never seen this.
Is it really a problem? Turning the puzzle is not a DNF, if you turn less then 90 degrees (I mean "/"-axis).
This regulation is method-dependent. What if I solve square-1 with largest middle layer slice of the left? With smallest (or largest) slice on the right, i.e. i'm left-handed? And also this is a regulation not only for a scrambler, but also for a judge who must somehow place the puzzle with specific orientation on a table while hiding it from a competitor. Sound complicated.

**Comment by lgarron** [comment]
I presume that this is motivated by the recent delegate report.

Indeed, I think that trying to force/keep track of Square-1 orientation is too difficult. There's a reason we gave up on trying to give everyone the same orientation for regular BLD.

**Comment by Claster** [comment]
> I presume that this is motivated by the recent delegate report.

Ouch. Could you point which report, please?

**Comment by lgarron** [comment]
Ouch for whom?

I was actually mistaken, this is from an email to the Board and WRC about C^3 Cube Open that was sent today. I presume it'll be in the Delegate report when it comes out.

**Comment by Laura-O** [comment]
We now have [A2b1)](https://www.worldcubeassociation.org/regulations/#A2b1) for these cases, so I think we have a good solution and this can be closed.
