### ISSUE TITLE
Guideline on Record Ties

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#191]
If there are multiple (identical) best results in region, they all count as a regional record, even if some of them were set by the same competitor and regardless if any were set on the same day.

As for round rankings, average/mean ties are not broken (e.g. the specific results in the average/mean do not matter for determining whether it is a record).

**Comment by lgarron** [comment]
I'd still like to see a Guideline on this, so that the documents are clear without WST/Board interpretation.

Mind if I keep it open for now?
(Feel free to assign to me if you want to see it get done soon.)

**Comment by Laura-O** [comment]
Sure, if you think we still need this, I don't mind keeping it open.

**Comment by Laura-O** [comment]
@lgarron You have added the 2017 label here. Do you still plan to add a guideline?
If yes, please create a PR soon.
