### ISSUE TITLE
Turns/alignment during Inspection

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#192]
We currently try to co-opt solved state alignment rules for inspection, but this is especially flawed for Square-1: http://www.speedsolving.com/forum/showthread.php?47773-Kunaal-Parekh-DNF-(15-03)-Square-1-Single

**Comment by Claster** [comment]
How about "A competitor can round the puzzle to the nearest valid puzzle state"?
I.e. if a layer on 3x3 is misaligned, and if you can turn less then 45 degrees to align it, you can do it during inspection. In square-1, this regulation will allow you to make aligns less then 15 or 30 degrees most of the times (though there is a shape where you will be allowed to turn by 90 degrees).

**Comment by KitClement** [comment]
I tried to make a proposal similar to Claster's idea:

https://github.com/KitClement/wca-documents/commit/c9911bf48b7d8204c2aa64291ad5ce15ffd4e2e7

**Comment by lgarron** [comment]
I'm not sure if this has been handled yet: On Square-1, valid moves may be quite far away. Consider the following shape:

```
/ (-3, 0) / (-3, -1) / (0, 1) / (0, 2) / 
```

![img_4106](https://cloud.githubusercontent.com/assets/248078/3451695/1b59faf6-019e-11e4-8e86-d15eb4715799.jpg)

If you turn the top, the next valid move is (6, 0) or (-6, 0). It's unclear when "a new valid state is created". In particular, I don't think there's a good, intuitive answer for whether (2, 0) is a new move. But saying that you're still in the same state (as far as alignment is concerned) seems wrong. It's also hard to judge, especially if you're not very familiar with Square-1.

What if just consider each 30-degree rotation a new move for alignment purposes? That way, the limit is consistently 15 degrees.

In any case, I think we'll need to get our act together and define things like "move", "position/state", and  "closest state".

**Comment by Claster** [comment]
Your alg is wrong :-P
Ok, I understand what you mean. If you get this shape and do (2, 0), you won't receive a valid state because you can't do slice move. Therefore a competitor can round it to the nearest valid state by making (-2, 0). If you would do (3, 0), a competitor could do (3, 0) or (-3, 0).

But now I realize it would be a pain to explain it to new judges -_-
The fixed 15-degree limit has a disadvantage that it can be not enough to come to a valid state. How about rise this limit to 45 degrees?

**Comment by KitClement** [comment]
What I don't like about always limiting it to 15 degrees is that the competitor should be able to bring the puzzle to a state where "/" moves are possible.  For example, what would a competitor do if the scramble were brought to the station like this?

![win_20140702_095644](https://cloud.githubusercontent.com/assets/6166412/3456714/8688abee-01f1-11e4-8a6a-f9853663673c.JPG)

Similarly, the competitor would have to do a turn that should have been unnecessary if a (2, 0) were added to Lucas' picture.

**Comment by lgarron** [comment]
In my mind, your last point also brings together two problems:
- [What if the judge makes a mistake](https://github.com/cubing/wca-documents/issues/121) and doesn't transport the puzzles so it arrives at the competitor with exactly the correct scramble still applied?
- If the competitor submitted a puzzle that is so loose that this easily happens, it is [their responsibility](https://www.worldcubeassociation.org/regulations/guidelines.html#5c+) to deal with problems like this. But they shouldn't be able to cheat, either.

Also, we might be able to avoid misalignments during transport with [standard puzzle covers/platforms](https://github.com/cubing/wca-documents/issues/67) in the future.

At the moment, we don't have a good answer for what the competitor should do. I believe this requires an explicit decision by the Board / Delegate vote.

**Comment by sarahstrong314** [comment]
Here's a simple solution to prevent a Square-1 from accidentally being misaligned while it's being transported (mostly Kit's idea): have the scrambler place a small sheet of paper in the slice, then have the judge remove it during the "check" in  [A2d](https://www.worldcubeassociation.org/regulations/#A2d).

Here's an example with a cut-up sticky note inside the slice of my Square-1. It's easy to slip in, and it's snug and doesn't fall out.
![2014-07-02 18 25 06 custom](https://cloud.githubusercontent.com/assets/5139750/3468923/0c60b1bc-02a6-11e4-9e0e-5edb2929d6c6.jpg)

**Comment by KitClement** [comment]
We implemented Sarah's sticky note suggestion at Michigan 2014 with much success.  If we can get this to be used widespread, I'd suggest:
- Making the misalignment limit 15 degrees
- Any square-1 that can't be brought to a state where "/" can be performed in 15 degrees is a judge error, and should be awarded an extra scramble.  (Hopefully, usage of the sticky notes will make this nearly irrelevant.)

EDIT: In retrospect, I don't like this.  Competitors that receive a square-1 as described in my second point can use this to get good cubeshapes to their advantage, as they can take a misaligned puzzle with a good cubeshape, or report a puzzle with a bad cubeshape.

**Comment by Laura-O** [comment]
The sticky notes solution is really good.
However I don't think that these regulations are applicable in competition
for two reasons:
1. It's not possible to notice if a competitor does a >15 degrees move any
time. Especially when people grab the puzzle and bring it into their
solving orientation quickly. So this can be easily used as a cheating
method, i.e. to get a better scramble/cubeshape with an extra attempt.
2. This will probably result in a delegate decision in most cases. At least
for judges who are not able to solve a Square-1 themselves it will be
difficult to decide whether a misalignment is more or less than 15 degrees
when it's not in cubeshape.

2014-07-15 5:55 GMT+02:00 KitClement notifications@github.com:

**Comment by KitClement** [comment]
Hard to come up with a proposal now for this, but here are the issues we should vote on:

### What should be the inspection misalignment limit?
- 15 degrees
- 30 degrees
- 45 degrees

Main pro/con thing here is that larger degree movements are easier to detect in inspection by the judge, but that also means competitors may be able to get away with moves in inspection.  Despite the difficulty for judges, my recommendation would be to make this 15 degrees.

### Should we codify the use of paper in the puzzle for preventing misalignements?
- Yes
- No

Given that a scorecard is always available, I don't think that this should be hard for organizers to do.  This also forces judges to check the state of the puzzle to make sure that it is valid, which makes it easier to enforce 15 degrees during inspection.

**Comment by viroulep** [comment]
I just noticed this.
For Square-one there is another possible issue if for some reason the use of a thin object is not enforced, consider the state after `/(3,3)/(1,2)/(2,2)/`:
- If it comes with a misalignment of about (-0.8, 0) you can align with (0.8, 0), (-0.2, 0), (-1.2, 0) while staying within the `10f` 45° limit.
- After exactly (-1.5, 0), you have 4 alignment "choices".

This is a borderline case but it's still annoying (there is a bunch of other states where at least two valid states may be reachable under 45°).
Adding @Claster original suggestion to align only to the closest valid state would solve this and @lgarron example state (`/(-3,0)/(-3,-1)/(0,1)/(0,2)/`), where no valid state may be reached within 45° if the misalignment is like (3,0).
#364 was recently created to clarify the metric we use for Square-one, it could be a good opportunity to state clearly what a "move" is for this puzzle, and fix this misalignment issue.
