### ISSUE TITLE
Tile Thickness

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#194]
For a long time, the stance on tile thickness has been close to an "anything goes" policy.  Until the beginning of 2014, we used the "generally available thickness" rule for non-cubic puzzles, specifically to allow the thick tiled megaminxes.  When we switched to the somewhat arbitrary 1.5mm limit for thickness on all puzzles in 2014, we received much negative feedback to this, specifically for those megaminxes that have thicker tiles.  Currently, it stands so that megaminx can have tiles thicker than 1.5mm at delegate discretion, but we would like to find a more consistent way to handle this.

Here are some of the official reasons for having a limit/not having a limit.
## Reasons for not having a thickness limit.
- Any specified maximum level of thickness is arbitrary, and difficult to measure.  Our current specification of 1.5mm is very precise and thus difficult to measure, and delegates often do not have the equipment to measure this.  
  - If we do have a tile thickness limit, it should be easy to measure, and the measurement devices must be cheap/available worldwide.  (Something like a coin would be the best, but of course coin thicknesses can change from country to country.)
- Manufacturers, especially mf8 and Meffert's, often make puzzles with tiles thicker than 1.5mm.  Competitors (specifically Erik Akkersdijk) often use the tiles from these puzzles on other puzzles.  We'd rather not have to disallow puzzles made by popular puzzle manufacturers.
- Having thick tiles changes the feel of a puzzle, and not allowing puzzles that have been long available for use in competition significantly undermines the work/practice of competitors on these puzzles.
- Many competitors like to use tiles for their durability as compared to stickers.
## Reasons for having a thickness limit.
- Thick enough tiles do provide an visual advantage over stickers, in being able to see the colors of stickers adjacent to a given face.  One could argue that certain stickers have this advantage as well, but thicker tiles would make this advantage more apparent.
- Sometimes, puzzles can have unnecessarily large tiles, when there are clearly better options for stickers/tiles.  For example, I would find the "tiles" of this cube unneccessarily thick.

![10437440_650424741698551_3986044358576577009_n](https://cloud.githubusercontent.com/assets/6166412/3379049/799ccb24-fbeb-11e3-92a9-612336fa4896.jpg)
- It is known that certain competitors perform better with tiles as opposed to no tiles as a result of the changed grip (not extra visual information), especially with Megaminx.  This could be seen as a competitive disadvantage to those who prefer a brand of puzzle that does not provide tiles.
- WCA regulations have always been conservative, and a thickness level prevents competitors from creating puzzles that may provide an advantage that we did not think of in advance.

**Comment by lgarron** [comment]
That looks like a great summary of the issues. I've paid a lot of attention to the issue, but I can't think of anything substantial to add.

**Comment by UnsolvedCypher** [comment]
I really like the idea of a coin being used to judge thickness - if a coin was chosen, delegates could easily test the thickness of any puzzle. Even if the coin was from another country than the delegate, the delegate could simply obtain a few of these coins and bring them to competitions just like timers and displays are brought. I would be against having any thickness allowed, because while I think the thickness limit should increase a little to allow for a few slightly thicker tiles, I don't see a valid reason for crazy thick tiles, while there is a lot of potential for abuse.

**Comment by Laura-O** [comment]
Ti[ml]es are changing: I think tiles have become pretty unpopular and I haven't heard any complaints about the tile thickness rules since years, so this can be closed.
