### ISSUE TITLE
Pillowed Puzzles

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#195]
Before 2009, pillowed puzzles were not allowed, and most (if not all) manufactured puzzles were cubic regardless.  With the introduction of V-Cubes in 2008 and the addition of 7x7x7 as an event in 2009, the pillowed V7 was the only puzzle available for this event.  Today, pillowed versions of virtually every cubic puzzle exist, and these are not allowed in competition, with the longstanding exception of 7x7x7.  
## Reasons for Allowing
- While the majority of cubers prefer the new cubic Shengshou 7x7x7 cube, many cubers (including the current single WR holder, Lin Chen) prefer to use the pillowed V-Cube.  Not allowing any pillowed puzzles will have a significant competitive impact on these 7x7x7 cubers.
- The advantages of a pillowed puzzle over a cubic one are arguably minimal.  These include:
  - A visual advantage (parts of 5 sides potentially visible)
  - A gripping advantage (potentially easier to hold around a pillowed puzzle compared to a cubic one)
- The new MoYu 7x7x7 that is soon to be released will be pillowed.  Given MoYu's track record with puzzle quality, this will be a widely popular puzzle, and banning pillowed puzzles will be widely unpopular.
- Consistent regulations - allowing some cubic puzzles to be pillowed while others must be cubic makes the spirit of this regulation rather unclear.
## Reasons for Disallowing
- While it seems technical, we call our puzzles "cubes," and pillowed puzzles do not look like cubes.  Practically, this may give those who prefer pillowed puzzles an advantage visually as well as with their grip.
- An "anything goes" policy on pillowed cubes would open the door to many other puzzles that have never been WCA legal - including fully spherical puzzles.  Do we need to draw a line for how much pillowing is allowed?
- As stated in the reasons for allowing, disallowing all pillowed puzzles would also be consistent.

**Comment by Laura-O** [comment]
JFTR: In the past, there were rarely any pillowed 3x3x3s available that were interesting for speedcubers.
There's now a [YuXin Pillowed 3x3](http://thecubicle.us/yuxin-pillowed-p-5746.html), which seems to be a proper speedcube.
