### ISSUE TITLE
Specifically forbid alcohol and drugs

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#197]
[WCA Delegate Group Thread](https://groups.google.com/forum/#!topic/wca-delegates/zhUWHfUIR28)

Suggestion by Adam Polkowski:

> Bringing alcohol and drugs to any official competition area (stages, waiting area, competitor area) is forbidden. Penalty: Disqualification from the event.
> Organization team may check the sobriety status of suspected competitors. The persons being under alcohol influence can not stay in any official competition area (stages, waiting area, competitor area). Penalty: Disqualification from the event.

This was brought up by Adam, who says it can be in Poland. Ron said he had a similar request from Russia recently. I'm not aware of anywhere else, but if it becomes a problem in a lot of places we can start keeping track of it in this issue.

**Comment by lgarron** [comment]
Personally, I think we should avoid policing alcohol and drugs through an explicit Regulation, since 2f and 2k3 cover this. We don't want to be associated with those, even by mentioning them to ban them.

In addition, the kind of competitors who would act like this probably not going to change the behaviour based on such a Regulation. Thus, it might not be more effective than 2f and 2k3 already are.

**Comment by sarahstrong314** [comment]
I agree that it shouldn't be explicitly written in the Regulations, or even in the Guidelines. I believe that the Regulations should be as family-friendly as possible to appeal to young competitors.
