### ISSUE TITLE
Picking up the puzzle before the end of the attempt. (A6e)

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#200]
In [A6e](https://www.worldcubeassociation.org/regulations/#A6e), the phrase "until the judge has inspected the puzzle" is not clear.

> A6e) The competitor must not touch or move the puzzle until the judge has inspected the puzzle. Penalty: disqualification of the attempt (DNF). Exception: If no moves have been applied, a time penalty (+2 seconds) may be assigned instead, at the discretion of the judge.

Discussion on Delegates List (in the US Nationals 2014 thread): https://groups.google.com/forum/#!topic/wca-delegates/g1WhtgfSbrs

**Comment by lgarron** [comment]
Suggestion by Tim McMahon:

> Clarification of A6e would be good. "until the judge has inspected the puzzle" is ambiguous. A7a could be used to confirm that the judge has inspected the puzzle. 
> 
> Perhaps A6e could be made stricter with:
> A6e) The competitor must not touch or move the puzzle until the judge has given verbal confirmation "OKAY, you may take your puzzle". Penalty: disqualification of the attempt (DNF)

https://groups.google.com/d/msg/wca-delegates/g1WhtgfSbrs/cpKFaosdVeIJ

**Comment by lgarron** [comment]
Suggestion by António Gomes:

> I think to avoid these situations, it would be less ambiguous if A6e) would state "until the attempt is over" or "for the remainder of the attempt" instead of "until the judge has inspected the puzzle."

https://groups.google.com/d/msg/wca-delegates/g1WhtgfSbrs/zkNFb-lB-GgJ

**Comment by lgarron** [comment]
My comments:

In principle, I agree that it is sensible to forbid the competitor from touching the puzzle until the attempt is complete.
However, this is a natural instinct for the competitor, and (as has been pointed out in this thread) is often not an issue.

I see a parallel with forbidding/allowing the second hand to be used for OH inspection. It used to be forbidden, but I think Ron wanted to change it to be more lenient to competitors who might do it by accident. The [official reason for that](https://www.worldcubeassociation.org/regulations/history/files/regulations_history2010.html):

> Art. C1, changed. Using two hands during inspection is allowed. Two handed inspection does not influence the result. [fairness]

I don't want to change this, only for us to want to change it back because it is affecting competitors unfairly. In particular, unless we're very strict about it (as if we don't have enough strict details to worry about), I can imagine certain judges being more lax, and competitors suffering because of inconsistent or lax instructions. Fortunately, the risk is smaller for this particular issue (+2 instead of DNF).

https://groups.google.com/d/msg/wca-delegates/g1WhtgfSbrs/1TUB-GNnOIIJ

**Comment by pedrosino** [comment]
I believe something like
"the competitor must not touch the puzzle until he has signed for the result"

is clear.

**Comment by lgarron** [comment]
It's clear, but not [DRY](http://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
I suppose I don't mind being redundant for clarity, but I think it is conceptually safest to say that you must not touch the cube until the end of the attempt.

**Comment by pedrosino** [comment]
That's fine too. Maybe say "until the end of the attempt (according to A7c)"

**Comment by lgarron** [comment]
[Schleswig-Holstein Open 2014](https://groups.google.com/forum/#!msg/wca-delegates/s4T_sbU9oIk/IQI_JlD0QGUJ)

> A competitor solved pyraminx and stopped the timer. Somehow the pyraminx fell off the table and the competitor used his legs to prevent the cube from falling on the ground.
> As the judge was 100% sure, that the cube was already solved before that action we decided to let it count.

"Voluntary action" or not, I believe that A6e clearly specifies a +2 for this. Henrik and Björn (Delegates at the competition) thought otherwise. :-(

**Comment by Laura-O** [comment]
To solve the "voluntary or not"-problem, we should implement this suggestion by Philippe [(here)](https://groups.google.com/d/msg/wca-delegates/oX7rUqxuCxk/oULv3J2pBQAJ):

> A clarification was suggested by Kit but I don't think there has been a follow up. Simply adding "intentionally" to A6e may be enough to please everyone!

**Comment by pedrosino** [comment]
The case of cube falling on competitor's lap came up again. Philippe made some good points about why it should be a +2 (Lucas also mentioned it earlier here).

**Comment by pedrosino** [comment]
Quoting Laura and Philippe, the current interpretation seems to be that a puzzle falling on the competitor's legs/lap should be penalized, because they prevented it from falling and maybe getting a +2 or DNF.

The proposed fix (adding intentionally) is good but doesn't cover this.
Either way, a clarification would be good.

**Comment by lgarron** [comment]
> The proposed fix (adding intentionally) is good but doesn't cover this.

Indeed. Unambiguous application is easier to get right, and I think it's reasonable.

**Comment by pedrosino** [comment]
Just posted at the delegates group:

From Indian Nationals:
>"10. In Skewb Finals, a competitor's solve ended up with the puzzle in his lap, he was given a +2 because competitor touched it after the solve (with his lap)"

Laura replied:
>"Hi Akash,
>regarding #10:
>I have argued that a puzzle falling into your lap is not the same as intentionally touching the puzzle in the past. However, I think it's reasonable to give a +2 for the reasons Philippe stated here."

Which points to Philippe saying:
>"Hi all,
>As far as I remember us discussing incident 5 and 6 during the competition, I thought the decision were +2 and no penalty (respectively).
>We really had both ways of applying A6e, we have a general issue tracking this here.
A few cases are here, here, and here.
>When a cube is resting on a competitor's lap (intentionally or not) it *is* touching the competitor. Also (intentionally or not) the competitor prevented the cube from falling on the floor after stopping the timer, and by doing so they prevented the risk of any puzzle pop(s) that may have resulted in a DNF state.
The competitor is responsible for dropping their puzzle correctly and stopping the timer.
If this is done carelessly and the puzzle is prevented one way or another from eventually changing state after the timer is stopped and before it reaches its resting state, then I don't find absurd to give a penalty for that."

There is no mention of the competitor at Indian Nationals trying to stop the cube from falling, and that's not possible to evaluate correctly, IMO, because it all happens so fast.

I even made a comment yesterday about this (new) intrepretation at https://github.com/thewca/wca-regulations/issues/200, but now I'm confused again :)

There is a corner case, though. If the cube falls from the table, hits the competitor's legs and falls to the ground, should it be a +2 or not?

**Comment by AlbertoPdRF** [comment]
FTR: A part of this (puzzles falling in the lap) was fixed in #497
