### ISSUE TITLE
Competitors Communicating About Easy Scrambles

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#202]
There have been several recent Delegate reports that mention easy scrambles in 2x2x2 where competitors talked about easy scrambles, or where a competitor shouted out about an easy scramble. There are a few topics that come to mind:
- How well can we prevent this _in practice_?
- (How) should the competitor be punished?
- What should be done with solves where it is known or suspected that a competitor knew it was easy?
- Should we filter scrambles more aggressively? (#201)

My answers:
- I don't think we can do too much, given the way competitions are currently run. We can encourage smaller groups and/or certain layouts of the stage/competitors area, but I don't see these solving much of the problem. Unless competitors stay in isolated booths/rooms, it is always easy to see an audience response to an especially easy scramble.
- I believe that any competitor who shares _any_ information about any of the scrambled states should immediately be disqualified from the event. No tolerance. They can save their excitement for a few minutes.
- If the competitor did not actively seek out information about the scramble, I believe substituting scrambles or changing results in this case would be subjective or unfair.
  - If we replace scrambles that have been talked about (i.e. the easy ones), this creates an incentive for competitors to push to do their solves first.
- I think this particular issue is the biggest issue with easy scrambles and short puzzles. We should take it into consideration before making any future changes for scramble filtering.

**Comment by lgarron** [comment]
In one case, the Delegate happened to be scrambling 2x2x2 and withheld the final (5th) scramble from everyone, because it was easy. This meant that competitors would not have as much time to learn about easy scrambles. However, this is not a sustainable solution because: 
- We have a clear policy that scramble filtering is handled by the scramble program, and not the Delegate. I think this should extend to any decision about how to run the competition based on the scrambles.
- If this becomes common, then the fact that everyone is being held on a particular solve is a conspicuous indicator that the scramble is easy.
- It's unclear how to handle this if the easy scramble is not last. (_Moving_ it to last gives competitors a hint that the last scramble of a round might be easier.)

**Comment by pedrosino** [comment]
I agree that people shouldn't talk about solves when they are competing. This is hard to control, though, since usually we have like 15 people waiting between solves, and we can't put a microphone on everybody...

But if caught, people should be disqualified from the event. Of course this must be clearly announced before the competition, and maybe reminded during it.

**Comment by IlyaTereshko** [comment]
How do I know there is a rule that specifically describes what to do in a given situation:

2g3) Competitors in the Competitors Area must not communicate with each other about the scrambled states of the puzzles of the round in progress. Penalty: disqualification of the competitor from the event, at the discretion of the WCA Delegate.

The only question is how to catch "an offender". I suggest that in the area of ​​the participants to put the observer, who will monitor violations and report them to the delegate.

**Comment by lgarron** [comment]
Unfortunately, 2g3 is usually not enforced. It doesn't give guidance on when exactly to enforce it (so Delegates only issue a warning), and is very harsh.

**Comment by lgarron** [comment]
Also, competitions can't spare a staff member for each competitors area just to be an "observer".

And if the observer is not dedicated (and mandatory), we're still not going to catch everything, nor apply fair/equal punishments for violations.

Even an dedicated observer would have a hard time keeping track of all the competitors – even if the competitors can be trusted while they're at the solving station, and stay exclusively in the competitors area at other times.

**Comment by IlyaTereshko** [comment]
So it is necessary to supplement this rule :-)
The observer must be an impartial person, namely non-cuber.

**Comment by lgarron** [comment]
1) Who?
2) If they're not a cuber, how will they be able to tell which communication should not be allowed?

A lot of the communication might be fairly casual, such as two competitors talking about a scramble that they've done. They might judge this to be okay, because neither of them gets an advantage from it. But someone else might overhear them.

It would be a lot _more_ casual, like someone coming back from a certain scramble with a smile on their face, or excitedly sharing their result. Or maybe just saying that they were glad not to get parity on a 4x4x4 solve (while this doesn't say anything directly about the scrambled state, good competitors are more likely to solve the scramble similarly, so this _does_ statistically communicate some information).

And if people _do_ want to cheat, there are very many ways to evade being caught (not all communications are overtly audible/visible).

We've had several discussions about Regulations enforcement where we've come to the conclusion that we just need to trust the competitors. An attempt to enforce things strictly would just provoke competitors.

**Comment by lgarron** [comment]
By the way, I don't want to discourage competitions trying to implement an observer like that. I merely think that

1) we can't and shouldn't mandate such observers in the near future, and 
2) such an observer is not sufficient.

It might be interesting to encourage Delegates to keep better track of what is actually happening, so that we can make decisions about what we should actually do.

**Comment by IlyaTereshko** [comment]
Indeed, I agree that it is always possible to find a way to transmit information.
I realized that the idea of ​​the observer is not approached.
Then I suggest we strictly distinguish between the concept of "discussion scramble"
Personally, I believe that the phrase "now was very easy scramble" is not a violation, since each participant the same scramble looks differently. Just the phrase "I did not have parity," not provide an advantage to other competitors, in my opinion.
I consider it necessary to develop this idea.

**Comment by lgarron** [comment]
> Personally, I believe that the phrase "now was very easy scramble" is not a violation, since each participant the same scramble looks differently

This is false for 2x2x2. That's the current problem.

**Comment by IlyaTereshko** [comment]
Therefore I propose to develop the idea to restore an exemplary list of phrases that will be considered grounds for disqualification.

**Comment by Claster** [comment]
How about ask competitors and audience to be completely silent, just like in blinds?

**Comment by lgarron** [comment]
> How about ask competitors and audience to be completely silent, just like in blinds?

That:
- is possibly not very fun,
- is possibly not easy to enforce, and
- as discussed, can't really prevent everything either.

The Competitors Area is often where I make new friends, and I wouldn't like to be forbidden from talking with them. It's also nice to be encouraging towards each other (which certainly doesn't have to involve communicating about any scrambles).

**Comment by Claster** [comment]
Oh, sorry, I meant only to be silent for 2x2 since it is the current problem.
People who make new friends in Competitors Area endure during blinds so they should endure during 2x2 :)

**Comment by Laura-O** [comment]
> Oh, sorry, I meant only to be silent for 2x2 since it is the current problem.

Although the current problem is 2x2 doesn't mean this is restricted to 2x2.
I can imagine a ton of simple comments which might give people hints for scrambles in different events, i.e. "easy xcross" in 3x3 might motivate competitors to inspect better, "LL skip" in Pyraminx might motivate someone to use a specific method....

**Comment by shelchang** [comment]
Most competitions I've been to don't ask everyone to be completely silent
for 3x3 blind (i.e. this certainly isn't a requirement that is or should be
in the regulations), and even when they do it's impossible to enforce. It
might be a little easier to enforce silence within a competitor area, but
even then they may still get communications from the audience.

**Comment by PZcuber** [comment]
I agree I have recently been breaking world records in 2x2 while practicing my best is 0.375. The scrambles are way to easy. I got a average of 5, as 0.84. it's way to easy.
