### ISSUE TITLE
Require competitors to take every attempt seriously

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#204]
Came up in [the Delegate thread about FMC move limits](https://groups.google.com/forum/#!topic/wca-delegates/Y5LtG-9u4fk) (see #203).

We currently have:

> [A1c](https://www.worldcubeassociation.org/regulations/#A1c)) A competitor participating in an event must be able to fulfill the event's requirements (e.g. know how to solve the puzzle). A competitor competing with expectation of a DNF result may be disqualified from the event, at the discretion of the WCA Delegate.

Given the discussion, it would be desirable for the Delegate to have a way to disqualify competitors if they are wasting competition resources (e.g. taking up timers/judges, causing FMC graders to spend more time), but _without punishing competitors simply for being inexperienced_.
## Some Existing Suggestions

Form the Delegate list thread:

> ... intention of DNF, or deliberately not performing to the best of their abilities in good faith...

Or:

> A competitor competing with expectation of a DNF result or intentionally poor result may be disqualified from the solve or the event, at the discretion of the WCA Delegate

Personally, I like the idea of "good faith", because it gets to the point. I have the feeling that "intentionally poor result" will result in more discussion about exactly how to interpret it. (What if a competitor finds a way to waste competition resources without getting something that is strictly a "poor result"?)

We need a much better phrase. I think most organizers aren't against fooling around _per se_, but something that tries to curb any such attempts that have an _undesirable effect_. The best notion I have right now is "wasting competition resources", but I think we can come up with something clearer. (The word "resources" is too vague for our audience.)

**Comment by lgarron** [comment]
Related: doing OH/BLD during speedsolves: https://groups.google.com/forum/#!topic/wca-delegates/YXNx-EOSpUc

**Comment by Laura-O** [comment]
In this context I want to suggest a clarification of

> A3b1) When the judge believes the competitor is ready, he asks "READY?". The competitor must be ready to start the attempt within one minute of being called, else he forfeits his attempt (DNS), at the discretion of the judge.

Competitors sometimes interpret this as a minute to fool around and do unrelated things (e.g. talking into their camera) which just delay the attempt unnecessarily. It would be good to emphasize that this is meant as a timeframe to prepare for the attempt (find a good sitting position, concentrate, etc.).

**Comment by lgarron** [comment]
In general, I think that we don't need _mandate_ that competitors don't ever waste time/resources – i.e. we don't need to write our intentions into every relevant Regulation; we just need to give the Delegate the ability to enforce it when needed.

But I agree that any fix for this issue should make it clear that wasting time in A3b1 is covered; thanks for pointing it out.

**Comment by Laura-O** [comment]
This was [changed in 2015](https://github.com/thewca/wca-regulations/commit/ba0308c1e5ed93964811dddc27aaf9b0c39e17a2).
