### ISSUE TITLE
Officially require all cases of "Delegate discretion" to be reported.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#205]
[Brought up by Chris Krueger](https://groups.google.com/d/msg/wca-delegates/Y5LtG-9u4fk/NdE692Jy0BEJ) during the discussion of #204:

> [Lucas Garron] At least one addition: I would like to require every single one of these disqualifications to be _explicitly recorded and described_ in the Delegate report (doesn't have to be long, just enough to make it clear what happened).
> This allows us to know the power disqualify competitors like this isn't being abused, and to converge on a reasonable policy for when to enforce this.
> 
> [Chris] I'd like to think that all 'delegate discretion' situations are being reported. That would probably be worth codifying.

**Comment by Claster** [comment]
This regulation together with 1c1-1c5, 1c8, 2s+, 4b1, 4b1+, 4f+, 4f++ concerns only Delegates, they are redundant for competitors and probably should be moved in the separate document, kinda "Delegate codex" (probably private).

**Comment by lgarron** [comment]
Move to somewhere else? In favor.
Private? Absolutely not. I'm prepared to fight for that.

**Comment by Claster** [comment]
Ouch. I thought of moving into "Delegates crush course"

**Comment by lgarron** [comment]
Almost nothing in that document is confidential. I'd prefer to place that
somewhere no the site, as long as it's not somewhere distracting (e.g.
taking up space in the Regulations).

In fact, I think having these things public doesn't make things more
difficult, and makes it easier for competitors/the community to get answers
about how things work.

»Lucas Garron

**Comment by SAuroux** [comment]
Slightly paranoid? :P

I can't see Oleg asking for a non-public document.

Commenting on his porposal I think this is a pretty good idea to slim down
the regulations, which has been discussed many times before, so that
unfamiliar competitors are not so afraid of such a large document. :)

2014-08-22 13:05 GMT+02:00 Lucas Garron notifications@github.com:

**Comment by lgarron** [comment]
Less paranoid, and more slow-fuming about the current state of things. :-P
(He said "probably private".)
