### ISSUE TITLE
Competitors asking for DNF after the End of the Solve

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#206]
Traditionally, we do not allow competitors to change or remove results after they have been recorded. Based on [9i](https://www.worldcubeassociation.org/regulations/#9i), a competitor is committing to putting the result in the WCA database as soon as they sign the scorecard fro an attempt.

Competitors sometimes ask for a result to be changed to DNF after they see that they got a bad time.
I think this kind of "picking and choosing" is usually frowned upon (and I have never seen it accepted), but there hasn't been an official decision about this.
It has been pointed that the competitor can reset the timer, but ) the judge may have already seen the time), and 2) I agree with the people that think we should not allow this kind of "tampering".

Just to imagine a weird scenario: if we start allowing this practice, I can imagine that a competitor might do it instinctively for something they _think_ is a bad time... and then ask for the judge to write down the time that was briefly displayed instead.

So:
- Should we allow requesting a DNF after the end of the solve but before the competitor has signed for the attempt?
- If not, what should be the penalty for turning off the timer or doing something else for the purpose of changing the result to DNF?
- How do we distinguish this from a pure accident?

This was discussed on the Delegates list in response to the [Iran Summer with Cubers 2014 report](https://groups.google.com/forum/#!topic/wca-delegates/Pd6OJuh_iA0).

**Comment by lgarron** [comment]
Personally, I think we could add a Guideline clarifying that a competitor must not request/create a DNF for an otherwise valid solve. If they try to do it once (e.g. reset the timer), I think a warning is fine, and we can let the Delegate deal with repeated infractions.

Hopefully, it will continue to remain the case that competitors only reset timers by "accident". (Who knows, maybe someday we'll have timers that are even remotely reliable about accidents like that.)

**Comment by shelchang** [comment]
I don't think there's really a way to reliably enforce this. Even if we
manage to resolve the timer reset issue, the competitor could always
intentionally commit another action resulting in a DNF (eg. picking up the
cube and immediately making moves, then feigning ignorance or saying it was
an accident). While I agree that requests to DNF an otherwise valid result
should not be honored, I don't think a competitor intentionally DNFing
himself actually gives him an unfair advantage that we need to protect the
others from.
