### ISSUE TITLE
Organize the WCA Goal and Spirit?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#211]
The only official guidance we have when making new decisions are the WCA goal and spirit at https://www.worldcubeassociation.org/about

> The goal of the World Cube Association is to have
>   **more competitions in more countries with more people and more fun, under fair and equal conditions.**
> 
> The spirit of the World Cube Association is that
>   **people from all over the world have fun together in a friendly atmosphere, help each other and behave sportsmanlike.**

I don't like citing these, because I feel like I usually need to cite both, and it looks pedantic when I do.  Both of them contain three very similar parts, stating that the WCA should strive to be:
- international, 
- fun, and
- fair.

During discussions, I don't think it's ever been of any use that these are separate – although it's sometimes useful that word _spirit_ implies that it is a standard we can hold competitors to. Eventually, I'd like to have a discussion about whether we can turn these into one sentence.

If we want more details, we can put them in the mission section of the about page.
Such details should not just be ornamental. They should give us concrete guidance for making decisions about 1) incidents and 2) changes in the Regulations

**Comment by Laura-O** [comment]
As we now have the WCT who supports the communication with the community and the public. Is that something we should ask them to do (or rather to make a proposal)?

**Comment by lgarron** [comment]
It's not really a community thing, but more foundational for self-guidance.
I think this is a matter for the WCA By-laws now, and I gave Ron feedback specific to the draft by-laws. I'm alright with closing this issue.
