### ISSUE TITLE
Proposal: Change the 'Records only count at the end of the day' regulation

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#212]
As suggested by Daniel on the mailing list.

My proposal is as follows:

9i2)  All the results of a round are considered to take place on the last GMT time of the round. If a regional record is broken multiple times on the same round, only the best result is recognised as breaking that regional record.

**Comment by lgarron** [comment]
I'm still waiting for the Delegate discussion on this to settle.

Technical things:
- Rounds don't really "have" GMT times. I'd say something about the last solve, or the time the round ends ("recorded in GMT")
- This assumes rounds have a well-defined ending time. If someone (e.g. an organizer doing an event out of order) does their solves later, does that push everyone else's solves farther into the future?
- Does this time need to be recorded and included with the results for every round?

**Comment by lgarron** [comment]
Relevant mailing list discussion started by Daniel Sheppard on Sep. 1: [Regulations Proposal: Change the 'Records only count at the end of the day' regulation](https://groups.google.com/d/msg/wca-delegates/qy2xuoHPjGY/0NjXsr3teEcJ)

**Comment by lgarron** [comment]
We should try to determine why people prefer different ways to calculate records, e.g.
- Calculating records should be easy.
- Records should be "logical" according to time (e.g. your record should not count if someone else in there world has actually gotten a faster time before).
- We should let more people get WRs if they "deserve" it.

**Comment by EdHollingdale** [comment]
Should this be reconsidered in light of the new competitions requirements policy? The policy requires the schedule tab on the competition to be filled out before the competition is announced. Additionally, when submitting results, Delegates are required to check a box to confirm that this schedule accurately reflects what took place on the day. Now have in the database information about when the event took place (we have timezone information for the competition as well) there are less computation limitations.

**Comment by xsrvmy** [comment]
There are still other issues to consider. Some times a round is spread over a large period of time, and in the extreme case there are staff comps. We already have this issue, but the new proposal would still be unfair to people in staff comps, or earlier in a long round.

**Comment by EdHollingdale** [comment]
> We already have this issue, but the new proposal would still be unfair to people in staff comps, or earlier in a long round

Currently it is unfair on everyone, I'm not sure saying that it would still be unfair in some circumstances after a change that makes it fairer for most is a logical argument against that change. Yes, some records may miss out on recognition if they occur early in a 3 hour round. We have to draw a line of recognition somewhere (hence the current regulation) - I am just saying we should draw it as close as possible to reality using the information available in the database already.

**Comment by lgarron** [comment]
> Currently it is unfair on everyone, I'm not sure saying that it would still be unfair in some circumstances after a change that makes it fairer for most is a logical argument against that change.

I think everything will lead to "unfair" cases by some measure, so I would prefer to err on the simpler side until there is a strong concrete proposal for something better.
