### ISSUE TITLE
Clarify mat requirements for feet

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#216]
See WCA email thread "Attempt with Feet" started on Oct. 25.

**Comment by lgarron** [comment]
Also, [UK Championship 2014](https://groups.google.com/forum/#!msg/wca-delegates/ro1rz1FZk_w/KooKSYO7EScJ).

**Comment by lgarron** [comment]
Also, [this thread started by Natán](https://groups.google.com/forum/#!msg/wca-delegates/DWqU7-IM_W4/O2Rq9C4MAI0J).

**Comment by lgarron** [comment]
Also see the email "Attempt with Feet" by Areli Rubí Gordillo ("ARU catsize").

**Comment by Laura-O** [comment]
Discussion about mats, [Daniel:](https://groups.google.com/d/msg/wca-delegates/50Y_0gfxCiw/IGA8KnRMAwAJ)

> [...] Extending further, for feet I'd be all for allowing competitors to bring any material they want to put under the mat. For me, that is fair for everyone still. We don't require everyone to use the same cubes etc, so why should we not give the competitors a choice of surface for feet?

**Comment by Laura-O** [comment]
At China Championships 2015 a competitor requested and used two mats for Feet (see [here](https://groups.google.com/d/msg/wca-delegates/i1jDJpIiTlU/euRRbvsKDQAJ)).

**Comment by AlbertoPdRF** [comment]
We have a requirement for mats, and the discussion if something can be put under them is taking place in #404, so I'm closing.
