### ISSUE TITLE
Consistent FMC Requirements

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#217]
Some things that are enforced inconsistently:
- No one may join the attempt after it has started
- No cellphones
- Availability of clocks/timers
  - ... which sometimes leads to cellphone use

There have been a few Delegate reports with instances of suspected/potential cheating.
It gets harder to trust everyone when a lot more competitors and organizers are holding the event, but organizers should only hold the event if they can make sure no one is cheating.

**Comment by Laura-O** [comment]
This has been solved by adding Guideline [E3d](https://www.worldcubeassociation.org/regulations/guidelines.html#E3d+).
Competitors being late for the start of the attempt are sometimes allowed to compete, but I think delegates are aware of potential issues, so I am closing this.
