### ISSUE TITLE
Handling Incomplete Times

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#218]
There's some confusion about what to do with times found incomplete after the fact compared to times that are incomplete due to the competitor resetting the timer.  A guideline should likely be added to A6f to fix this.

**Comment by lgarron** [comment]
Relevant thread: [UK Championship 2014](https://groups.google.com/forum/#!msg/wca-delegates/ro1rz1FZk_w/KooKSYO7EScJ)
