### ISSUE TITLE
Improve FMC Scramble Sheet

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#226]
- Better move descriptions (don't be concise, but be explicit and list moves).
- Include both round and attempt number.
- Place for more than one judge to sign off on the result?

Oleg [wrote a script to customize the FMC sheet](https://groups.google.com/forum/#!msg/wca-delegates/LaAS2QF2RTs/4k6lL1cZsHgJ) for Ural Open 2014.

Also: [support translations](https://github.com/cubing/tnoodle/issues/109)?

**Comment by Laura-O** [comment]
Just another idea for an improvement of the FMC sheet:
after clarifying that the solution must not turned in on the FMC sheet in the guidelines (#215), it might be a good idea to include that on the sheet as well.

**Comment by lgarron** [comment]
> must not turned in on the FMC sheet

Note: "must not" is incorrect here. That would mean that turning in a solution in the FMC sheet is never permitted. ;-)
("may not" is technically correct, but I would say something like "not required to")

I'm a bit worried that making this explicit will cause more competitors not to use the form, and therefore submit separate sheets (which are less consistent, slower to check, and lead to incidents about how to interpret them).

But it's probably best to remind all competitors, so they don't have to ask. We can probably still phrase it to encourage submitting the FMC sheet (e.g. it will make it easier for the judge to tell what the intended solution is).

**Comment by Laura-O** [comment]
Thanks for correcting me. I probably tried to quote the mentioned issue and failed. ;-)

I see your point, we should not encourage competitors to not use the form.
However, I don't think it makes sense that the standard notation is explained on the sheet and this FMC specific guideline is not. There are probably not many competitors who do not know what ' means, but many who would just DNF their attempt if they don't have the time to write down the solution on the FMC sheet.

**Comment by Laura-O** [comment]
The FMC sheet now has round and attempt numbers. The current discussion about better move descriptions is here: #456.
