### ISSUE TITLE
More Detailed Guidelines about Extra Attempts

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#228]
We have a bunch of precedents, but Delegates are still making inconsistent decisions. :-(

Also see  [#121](https://github.com/cubing/wca-documents/issues/121#issuecomment-64724071).

**Comment by Laura-O** [comment]
Doing extra attempts after the regular attempts can be confusing in combined rounds:

From [SCMU Open report](https://groups.google.com/d/msg/wca-delegates/yKEwUsxPDDw/Rcxn4HguBwAJ):

> I wasn't aware that in a combined round the resolve was to be performed right after the awarding. [...] I realised while verifying data, had she got this at the second attempt itself it would have certainly disqualified her. I didn't want to let that happen due to my own mistake, so I kept the times in her solving order instead. I'm taking note of this and will be more careful next time.

I experienced similar situations in competitions I attended.

**Comment by Laura-O** [comment]
The delegate poll has shown that a majority of the delegates prefers this regulation to be changed so that
extra attempts should be done immediately after they were granted.

I also think that's the best way to avoid incidents like the one quoted above and others, which were also reported by delegates.

**Comment by lgarron** [comment]
> The delegate poll has shown that a majority of the delegates prefers this regulation to be changed so that
> extra attempts should be done immediately after they were granted.

Just to be accurate, a _plurality_ of 44% of Delegates prefer this choice. Sharing just the aggregate statistics:

<img width="723" alt="screen shot 2016-02-22 at 14 06 57" src="https://cloud.githubusercontent.com/assets/248078/13234465/90691d24-d96d-11e5-8fc0-02e4c9863a76.png">

However, only 33% prefer keeping it as is, so I support changing the recommendation to doing the extra attempt immediately after.

**Comment by viroulep** [comment]
I also support this change, it has very minor drawbacks and solves rather annoying issues.

**Comment by viroulep** [comment]
I'd like to take on this, unless someone is already working on it. I'll come with a PR soon.

**Comment by viroulep** [comment]
Dealt with in #341.
