### ISSUE TITLE
Proposal: If the competitor resets the timer before the end of the attempt, they receive a DNF.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#230]
## Proposal

If the competitor resets the timer ([A6f](https://www.worldcubeassociation.org/regulations/#A6f)) after the solve, but before the end of the attempt ([A7c](https://www.worldcubeassociation.org/regulations/#A7c)), they receive a DNF.
(Exception: if they can demonstrate that the timer was accidentally reset for a reason that is is not their fault, the Delegate may still award them an extra attempt.)
## Pros
- Handles all of the following issues:
  - #206: Competitors asking for DNF after the End of the Solve
  - #218: Handling Incomplete Times
  - #222: Clarify whether/when the result is valid if the timer has been reset.
- Easy to to understand and apply.
  - Unreliable evidence -> simply a DNF.
## Cons
- Competitors can use this to DNF solves if they don't like the time.
- In cases where the time was visible for long enough before the competitor reset the timer
- Judges may be inconsistently lenient, if they've already seen/recorded the time.

---

To handle the cons, we could relax this if if:
- the judge already wrote the time down (but the competition hasn't signed it),
- the judge saw it clearly before the timer was reset, or
- there is video evidence.

In these cases, we could either allow the result to stand, or we could apply a +2 time penalty. For comparison, see [A6e](https://www.worldcubeassociation.org/regulations/#A6e).

> A6e) The competitor must not touch or move the puzzle until the judge has inspected the puzzle. Penalty: disqualification of the attempt (DNF). Exception: If no moves have been applied, a time penalty (+2 seconds) may be assigned instead, at the discretion of the judge.

However, if there is no concrete evidence (i.e. a video that _clearly_ shows the timer halted with a certain time) and the judge did not see and remember the time, the result is a DNF.

**Comment by Ranzha** [comment]
Competitors intentionally DNFing attempts in lieu of have a bad result recorded (item 1 on the Cons list) is an existing possibility.
Is denying competitors such a possibility a goal?

**Comment by SAuroux** [comment]
I'm not quite sure: Is this supposed  to replace A6b? Or A6f? Or both?
Am 10.01.2015 09:35 schrieb "Ranzha" notifications@github.com:

**Comment by lgarron** [comment]
> Is denying competitors such a possibility a goal?

No. The whole point of this proposal is to make it an explicit non-goal.

Competitors can DNF their attempts in various ways, and I've personally been won over by the argument that we can't (and don't need to) prevent it. If they want to do it once in an average, whatever. If they want to ruin an average by doing it twice, their loss.

> I'm not quite sure: Is this supposed  to replace A6b? Or A6f? Or both?

A6f. I thought the references (and context) would make it clear, but I'll edit the first post to mention it explicitly.

**Comment by SAuroux** [comment]
I think you should add a reference to A7c, to make fully clear what "the
end of the attempt" is.

2015-01-11 20:18 GMT+01:00 Lucas Garron notifications@github.com:

**Comment by lgarron** [comment]
> I think you should add a reference to A7c, to make fully clear what "the
> end of the attempt" is.

Done.
