### ISSUE TITLE
Smartwatches

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#232]
Even I have one of these now. Their whole point is to send you information unobtrusively (either by vibration, or a decently high-resolution screen), which opens up yet another channel for cheating.

Someone could seriously just spend an afternoon writing an app that shows you hints for 4x4x4 parity when you make a certain gesture (e.g. holding your wrist still for 2 seconds while solving) – and continue pretending to be an innocent clock at other times.

There's even [an app that shows you a live preview of your phone camera](https://play.google.com/store/apps/details?id=com.pixtogram.wear.zicam) – without turning on the phone(!). If we allow smartwatches, I can see people asking to mount their camera on a tripod and start the video using their watch.
Pixtocam happens to freeze the first frame when you take a video, so there is an argument that you can't receive assistance – but this makes me unwary.

I don't want to lose the boundary between incidental things worn by the competitor (e.g. glasses) and something with the ability to let you cheat in various new ways without being noticed, so I'd prefer to disallow smartwatches: the competitor should not be allowed to bring one to the table, or at least they have to put the screen out of sight.

It can still vibrate, but so can a smartphone – see #103 for a dicsussion on that.

**Comment by StachuDotNet** [comment]
Personally, I feel like this is only an issue for BLD or FMC events.
I don't care if some noob spends 5 minutes on a 4x4 solve and has r2 B2... scrolling across some tiny screen.

**Comment by Laura-O** [comment]
I just wanted to set a reminder on that issue.

I recently played around with the [Pebble SDK](http://developer.getpebble.com/guides/). It's quite easy to write apps which use the 3 axis accelerometer.
There are several ways you could use this for cheating. One of them would be to define gestures to input a FMC scramble and then calculate optimal blocks or even a whole solution.

**Comment by kingmathyall** [comment]
I say that we should all together not allow smartwatches to be worn while solving. To me, this can be compared to wearing headphones while solving. It's very unlikely for a competitor to take advantage of it and cheat, but you never know! People will go to extensive lengths to cheat.

This could be added through the following:
2i3) Competitors must not be wearing Smartwatches during the attempt. Penalty: disqualification of the attempt (DNF).

Or this could be through a guideline:
2i+) Addition - Competitors must also not be wearing smartwatches during the attempt

Thoughts?

**Comment by viroulep** [comment]
I'd disallow smartwatches.
Adding them as an example to 2i is probably not enough, as people will argue that "using" is not "wearing".

Adding a guideline sounds fine.

**Comment by Laura-O** [comment]
I generally support disallowing smartwatches, but I am sure that a "Competitors must not wear smartwatches"-regulation would be applied very inconsistently and there would be many WRC decisions when other competitors identify smartwatches in recordings of official solves.

The main problems I see:

- What is a smartwatch?
Everyone probably agrees that a watch with cellular connectivity is a smartwatch.
But what about watches which you can use to track GPS data, heart rate, food etc. (usually called "fitness tracker")?
These are smart features and you can use them to cheat (for example, enter your parity algorithms as your food).

- How can delegates/judges identify smartwatches?
I am sure this will be Russian roulette: most delegates would probably identify a smartwatch when the display shows a message or a call. However, smartwatches are becoming more and more popular and there are many which just look like a classic watch.
To give an example: which of [these watches](https://www.wareable.com/media/images/2016/03/11541-b2cef7f28d123337ce0f461cb6b1d436-1458570310-Tdg1-column-width-inline.jpg) is a smartwatch? (they all are)

And a "real life" example: [https://youtu.be/Dxyu06lf8NM](https://youtu.be/Dxyu06lf8NM): Leon is wearing a smartwatch. The smartwatch lights up right when he starts the timer. Would it be possible to identify this watch as smartwatch if this didn't happen?

**Comment by Samuel-Baird** [comment]
I think it's reasonable to just disallow competitors from wearing any type of mechanical or electronic wristwear. I'm unaware of any electronic or mechanical wristwear that is necessary for medical reasons or such but if there are any that I'm unaware of then let me know.

**Comment by xsrvmy** [comment]
@UnderwaterCuber there is an issue here: what if you are wearing a wrist band that you cannot removing during the comp (eg. if it is used for admission to the venue)

**Comment by Samuel-Baird** [comment]
> @UnderwaterCuber there is an issue here: what if you are wearing a wrist band that you cannot removing during the comp (eg. if it is used for admission to the venue)

Could you provide an example of a venue which would require competitors to wear mechanical or electronic wristwear in order to be in the venue?

**Comment by xsrvmy** [comment]
@UnderwaterCuber We need to draw the line of what's allowed and what's not allowed somewhere. There are those electronic wrist bands these days, and disallowing anything that looks like them is where problems start to come in.

**Comment by Samuel-Baird** [comment]
> @UnderwaterCuber We need to draw the line of what's allowed and what's not allowed somewhere. There are those electronic wrist bands these days, and disallowing anything that looks like them is where problems start to come in.

If you draw the line at no electronic or mechanical wristwear it makes it clear and unambiguous which is why it seems to be a good option to me. What electronic wrist bands are you talking about specifically? Could you share an image or describe it?

**Comment by xsrvmy** [comment]
For example, a MI band

**Comment by Samuel-Baird** [comment]
> For example, a MI band

Yeah those are completely unnecessary and they look like they may be able to give a competitor information.

**Comment by xsrvmy** [comment]
I'm just saying that regular wristbands look like those, so we should not be banning things by looks

**Comment by Samuel-Baird** [comment]
> I'm just saying that regular wristbands look like those, so we should not be banning things by looks

Well, if the delegate thinks it could be electronic then they can always just disallow it to be safe, it shouldn’t cause any problems for the competitor other than looking a little less fashionable :P

**Comment by Ivan-Brigidano** [comment]
In my opinion, completely disallowing smart-watches is excessive (except FMC). Honestly, I can't see any significant advantage rather than looking for algorithms on the screen (and this can easily be caught by the judge).
This would introduce an inconsistent regulation that would be very difficult for the Delegate to grant that every competitor complies with.

**Comment by Samuel-Baird** [comment]
> In my opinion, completely disallowing smart-watches is excessive (except FMC). Honestly, I can't see any significant advantage rather than looking for algorithms on the screen (and this can easily be caught by the judge).
> This would introduce an inconsistent regulation that would be very difficult for the Delegate to grant that every competitor complies with.

The point of disallowing them all is to provide consistency, one delegate might allow a Fitbit but another might not for example.  Disallowing then all also means the delegate doesn’t have to check every competitors watch to make sure it isn’t a smart watch and that every competitor doesn’t have to worry about whether their watch is or isn’t legal.

**Comment by xsrvmy** [comment]
@UnderwaterCuber I see no problem actually banning wearable devices with wireless capabilities because they enable communication with the audience. I have a problem with banning anything that looks like one. Plus this comes down to trust anyways, cuz someone could hide something in their sleeve for example
