### ISSUE TITLE
A4b Clarification

### ISSUE THREAD

**Issue by Mollerz** [thewca/wca-regulations#233]
https://www.worldcubeassociation.org/regulations/#A4b

Currently this says "The competitor places his hands on the elevated sensor unit of the timer. His fingers must be touching the sensors with palms down. Penalty: time penalty (+2 seconds)."

I've seen lots of interpretations of this, because it's not entirely specific. I interpret this as all of his fingers must be touching the sensor, but I've had people argue against this.

I've seen people start the timer with their fingertips, but with their little fingers off of the timer, which I would think is perfectly acceptable (Example: http://i.imgur.com/vHibA0C.jpg). However, is it technically not acceptable?

There are also situations where someone has started the timer with perhaps one finger touching the timer. In the following picture, my index is definitely touching the sensor, but the other 3 are not. I personally would not accept this, but people have argued against this one. (http://i.imgur.com/J98GmPc.jpg)

Now I will admit I am not good with wording, so I am struggling to find a way to correct this regulation, but it needs to be more specific in my opinion.

**Comment by lgarron** [comment]
See if the change in #43 addresses all your concerns.
