### ISSUE TITLE
Bathroom Breaks

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#234]
There was [an incident](https://groups.google.com/forum/#!msg/wca-delegates/DIbaSIJVYXg/AnEsLKzeAUUJ) at X'an New Year 2014.

My last post in that thread:

> I would prefer to standardize, at least with a Guideline.
> If we're not comfortable with forbidding bathroom breaks, how about allowing only the following?
> - During FMC.
> - During memo in long BLD events (4x4x4, 5x5x5, multi), but not during the blindfolded phase.
> 
> Everything is at most one hour, and these events are the only ones usually expected to take over 10 min. (But I also think it was a good comment that FMC and multi are possible to abort before the "end" without an automatic DNF.)
> 
> If the Delegate has enough foresight to announce whether bathroom breaks are allowed, I would prefer they forbid them and make sure to ask competitors to go to the bathroom right before long events. (If a competitor asks to go right before an event, accommodate them a bit.)
> 
> For unplanned emergencies (and a bathroom emergency is... exactly that), I would prefer to have a consistent policy.

**Comment by lgarron** [comment]
I should note that some Delegates currently do allow competitors to go to the bathroom during FMC.
Also, back when multi BLD was not limited to one hour, bathroom breaks were more expected.

I personally would not trust a competitor to go to the bathroom alone – _in particular_ if they're going with a phone. But we need to trust competitors a little, anyhow. Perhaps a reasonable compromise is to specify that the judge must ask the competitor to leave behind their cellphone (/similar devices) if they go to the bathroom.

**Comment by lgarron** [comment]
[From Mike Hughey](https://groups.google.com/forum/#!msg/wca-delegates/DIbaSIJVYXg/T4Xlq8mIpu0J) in the X'an New Year 2014 delegate list thread:

> FMC is much scarier than BLD, in my opinion.  A competitor could very easily use a bathroom break to try to find a solution or partial solution electronically somehow.  I realize it's unlikely and would be terribly dishonest, but it seems somewhat risky to me.
> 
> (I'm just remembering all the stir caused by the Kramnik bathroom breaks in the 2006 chess championship.  I realize this is much different, though, since there's generally not money on the line for FMC, and even if there is, it's much less than the chess championship was.)
> 
> For BLD, it seems highly unlikely that a significant advantage could be obtained, as long as the break were taken before donning the blindfold.

**Comment by Laura-O** [comment]
Just a short note: asking competitors to leave their cellphone behind seems
pointless to me. It's pretty easy to circumvent this by bringing a second
cellphone and hide it somewhere (e.g. behind the toilet tank like someone
did at my university).

2015-01-04 23:51 GMT+01:00 Lucas Garron notifications@github.com:

**Comment by lgarron** [comment]
I don't think it's pointless. "Trust but verify" (in this case, "verify that they're not taking a phone to the bathroom") can be useful.

This makes casual cheating difficult for the common competitor.
If a competitor uses an extra phone on the way to/at the bathroom _in any way at all_, then they've explicitly broken a requirement, and we have clear grounds for disqualification. (Instead of having to judge whether they "cheated".)

**Comment by Laura-O** [comment]
I basically agree that it _can_ be useful in some cases. However there are
many more things that we should verify then.

Most often it's not difficult for a competitor to receive information by a
fellow competitor (who had finished his attempt earlier) on his way to the
bathroom. I can think of several easy ways to communicate in this situation
with a low chance that anyone is noticing.
So should we provide a competitor with a blindfold and a hearing protection
for his bathroom break?

2015-01-06 14:04 GMT+01:00 Lucas Garron notifications@github.com:

**Comment by Claster** [comment]
I wouldn't allow a bathroom break during FMC, especially after cheating
incident
https://www.worldcubeassociation.org/forum/viewtopic.php?f=9&t=1221. I
also don't favor allowing it during multi-bld or 4x4-5x5 bld, and can
imagine a situation when it can help a competitor: suppose one forgot how
to perform an algorithm, then he goes to the bathroom, obtains a cube and
tries to execute this alg. (Of course, I'm not trying to accuse Lorenzo).
If a competitor has an unplanned bathroom emergency, he can stop the
attempt. The world won't stop if he gets one DNF on a competition. If it is
a valuable attempt for him, he should do his business before.

2015-01-06 17:42 GMT+03:00 Laura Ohrndorf notifications@github.com:

> I basically agree that it _can_ be useful in some cases. However there are
> many more things that we should verify then.
> 
> Most often it's not difficult for a competitor to receive information by a
> fellow competitor (who had finished his attempt earlier) on his way to the
> bathroom. I can think of several easy ways to communicate in this
> situation
> with a low chance that anyone is noticing.
> So should we provide a competitor with a blindfold and a hearing
> protection
> for his bathroom break?
> 
> 2015-01-06 14:04 GMT+01:00 Lucas Garron notifications@github.com:
> 
> > I don't think it's pointless. "Trust but verify" (in this case, "verify
> > that they're not taking a phone to the bathroom") can be useful.
> > 
> > This makes casual cheating difficult for the common competitor.
> > If a competitor uses an extra phone on the way to/at the bathroom _in
> > any
> > way at all_, then they've explicitly broken a requirement, and we have
> > clear grounds for disqualification. (Instead of having to judge whether
> > they "cheated".)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/cubing/wca-documents/issues/234#issuecomment-68862438>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cubing/wca-documents/issues/234#issuecomment-68873036
> .

## 

Best regards,
Oleg Gritsenko

**Comment by SAuroux** [comment]
A serious question: If bathroom breaks are explicitely not allowed, would a
competitor be punished for peeing on place during a competition?

2015-01-13 23:53 GMT+01:00 Oleg Gritsenko notifications@github.com:

**Comment by Claster** [comment]
Well, if you consider his action as "distracting others during the
competition" or "damaging venue facilities". If you don't, a competitor can
pee on a place even if bathroom breaks are allowed, and you can do nothing
about it.

2015-01-14 2:05 GMT+03:00 SAuroux notifications@github.com:

> A serious question: If bathroom breaks are explicitely not allowed, would
> a
> competitor be punished for peeing on place during a competition?
> 
> 2015-01-13 23:53 GMT+01:00 Oleg Gritsenko notifications@github.com:
> 
> > I wouldn't allow a bathroom break during FMC, especially after cheating
> > incident
> > https://www.worldcubeassociation.org/forum/viewtopic.php?f=9&t=1221.
> > I
> > also don't favor allowing it during multi-bld or 4x4-5x5 bld, and can
> > imagine a situation when it can help a competitor: suppose one forgot
> > how
> > to perform an algorithm, then he goes to the bathroom, obtains a cube
> > and
> > tries to execute this alg. (Of course, I'm not trying to accuse
> > Lorenzo).
> > If a competitor has an unplanned bathroom emergency, he can stop the
> > attempt. The world won't stop if he gets one DNF on a competition. If it
> > is
> > a valuable attempt for him, he should do his business before.
> > 
> > 2015-01-06 17:42 GMT+03:00 Laura Ohrndorf notifications@github.com:
> > 
> > > I basically agree that it _can_ be useful in some cases. However there
> > > are
> > > many more things that we should verify then.
> > > 
> > > Most often it's not difficult for a competitor to receive information
> > > by
> > > a
> > > fellow competitor (who had finished his attempt earlier) on his way to
> > > the
> > > bathroom. I can think of several easy ways to communicate in this
> > > situation
> > > with a low chance that anyone is noticing.
> > > So should we provide a competitor with a blindfold and a hearing
> > > protection
> > > for his bathroom break?
> > > 
> > > 2015-01-06 14:04 GMT+01:00 Lucas Garron notifications@github.com:
> > > 
> > > > I don't think it's pointless. "Trust but verify" (in this case,
> > > > "verify
> > > > that they're not taking a phone to the bathroom") can be useful.
> > > > 
> > > > This makes casual cheating difficult for the common competitor.
> > > > If a competitor uses an extra phone on the way to/at the bathroom
> > > > _in
> > > > any
> > > > way at all_, then they've explicitly broken a requirement, and we
> > > > have
> > > > clear grounds for disqualification. (Instead of having to judge
> > > > whether
> > > > they "cheated".)
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > 
> > > https://github.com/cubing/wca-documents/issues/234#issuecomment-68862438>
> > > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/cubing/wca-documents/issues/234#issuecomment-68873036>
> > > 
> > > .
> > 
> > ## 
> > 
> > Best regards,
> > Oleg Gritsenko
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/cubing/wca-documents/issues/234#issuecomment-69837463>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cubing/wca-documents/issues/234#issuecomment-69839101
> .

## 

Best regards,
Oleg Gritsenko

**Comment by lgarron** [comment]
[WWU 2015 Report](https://groups.google.com/forum/#!msg/wca-delegates/qnL4XRB3loc/6QbVYs3-kYgJ) by Ilya Tereshko:

> At 3rd attempt of FM Oleksandr Kirieiev (2014KIRI02) came up to me, gave his work and his smartphone and asked me allow him to go to the WC. I allowed him. He came back in few minutes and continued his attempt. What are your thoughts?
