### ISSUE TITLE
Clarify that displays are not required?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#237]
This [came up on the Delegate list](https://groups.google.com/forum/#!msg/wca-delegates/wbV_Nhfz5P0/pdJ6rBqdNHkJ).

**Comment by SAuroux** [comment]
Is this necessary? The displays are mentioned nowhere in the regulations.
Assuming that the use of displays is necessary is simply wrong and there is
no reason to do that. We could as well assume that there needs to be a
lollipop at every timer station.

2015-01-06 13:42 GMT+01:00 Lucas Garron notifications@github.com:

**Comment by lgarron** [comment]
The difference between displays and lollipops is that displays _are_ usually at every station.

We have lots of unwritten conventions, but since timers are expensive it might be worth being clear on this point.
