### ISSUE TITLE
Adding Rounds

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#238]
This comes out of the [Oxford Winter 2014 Delegate report thread](https://groups.google.com/forum/#!msg/wca-delegates/AiUE2QrtAiU/oAlnYZy9hf8J).

James Molloy:

> I also had a strange incident with the parent of a competitor as a result of adding rounds. On the final day we went really far ahead of schedule, and we decided that we wanted to add a final round of pyraminx. It was planned to be Pyraminx Final, 5x5 Final, 3x3 Final. We decided to make the Pyraminx Final the second round, and add the new Pyraminx Final between the 5x5 and 3x3 finals. Before the Pyraminx second round started, it was announced that there would be an extra round after the 5x5 final for the top 8 competitors. One of the parents came over to me and asked me why we were changing the schedule at the last minute. I explained that a lot of competitors just want to do as many solves as possible, and if we have the time we will usually always give people the option to break their PBs, NRs, and such for another time. I also explained that this a common occurrence depending on the competition. And at a few competitions, rounds are even removed based on the amount of competitors and the time invested in other rounds.  She complained that they lived around a 4 hour drive away and they had planned to leave after the 5x5 final and could they not add the pyraminx final immediately after the second round. I explained to her that once the round is over we generally move straight onto the next round, and you have to input all of the results and prepare the scorecards for the next round and that takes time. She then proceeded to complain about how her son won't be able to do all the solves on the schedule because of unprofessional planning. I then explained to her, because of how far ahead we were, that the pyraminx final that will take place, will finish before the planned time for the 5x5 final anyway and that regardless of if he does the remaining round, he will still get as many solves as were scheduled in the first place. At this point Daniel joined and asked about the situation and suggested what we will do is input the results for the second round as soon as possible, and her son can do the final scrambles as soon as the results are in and he is confirmed to be in the final. They accepted, and we continued with the competition. The competitor in the end did not make the final, and he apologised for his mother and he understood all the situations, and I followed up by apologising about the situation to the mother and explained how it is very normal for this to happen and she accepted this as well.

Ron van Bruchem:

> Adding rounds sounds OK to me:
> - if the results of the previous round are already known, you can only add rounds if all proceeding competitors agree
>   (I have seen cases where one competitor, often the winner of the event, disagreed. Understandable.)
> - the competition should end on the planned time

Daniel Sheppard:

> For Oxford,  we adopted a new policy with adding rounds:
> 
> If the round is added after the "final" has happened, all competitors must agree to the addition of a round. Medals/prizes will be awarded as per the original "final", even though the official results might indicate a different podium in the end.
> 
> If the round is added before the original "final", this will be announced, and we must make sure all competitors are able to attend the newly scheduled round or at least be catered for in some way if they can't. The new final can be used for prizes.

**Comment by lgarron** [comment]
Berkeley has added rounds on the same day, usually as follows:
- The final round of the end has taken place, but some competitors want another round.
- There is time for the round (without removing anything else that has been scheduled).
- The top three competitors (i.e. those on the podium) from the old final round all agree to the new round.
- Prizes are awarded based on the new final round.

**Comment by lgarron** [comment]
[Anders](https://groups.google.com/forum/#!msg/wca-delegates/AiUE2QrtAiU/b839tqF0aV4J):

> Although 1c6 appears to give the Delegate full freedom to change whatever he wants regarding events, rounds and formats during the competition, maybe it would be a good idea to have some guidelines of when such changes are acceptable/recommended. I can think of six cases to consider:
> 
> Adding an event
> Removing an event
> Adding a round
> Removing a round
> Adding/increase a time limit/cut-off
> Removing/decrease a time limit/cutoff

**Comment by AlbertoPdRF** [comment]
Adding an event now can only happen with Board approval
Adding or removing a round has to be announced before the prior round (#490)
About time limits and cutoffs, we have [A1a3)](https://www.worldcubeassociation.org/regulations/#A1a3) and [A1a3+)](https://www.worldcubeassociation.org/regulations/guidelines.html#A1a3+)

I think this one can be closed now!
