### ISSUE TITLE
Regulation 9s and A1a are in conflict

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#239]
9s) Each round of each event must have a time limit (see Regulation A1a).

A1a) The organisation team may enforce time limits for solves and/or rounds. 

One says limits are a must, the other says they may be enforced...

**Comment by pedrosino** [comment]
My proposal:
A1a) The time limit can be enforced for solves and/or rounds.

Oliver's proposal:
A1a) The organisation team may enforce the time limits for solves and/or rounds.

**Comment by lgarron** [comment]
I prefer the clarity that there is always a time limit.
The time limit can always be set higher than 10 minutes (A1a1), and can be changed during the competition if it's really necessary (A1a3).

Assuming no one objects, I think the easiest change is to change "may" to "must" in A1a.
