### ISSUE TITLE
Necessary mid-year citizenship change

### ISSUE THREAD

**Issue by pochmann** [thewca/wca-regulations#240]
2e2 should also allow someone to change their represented country in the middle of the year if they actually lost the former citizenship and thus _can't_ represent the former country for the rest of the year.

**Comment by lgarron** [comment]
I wouldn't say it's _necessary_.
If they still represent the old country, it might be _undesirable_, but not
really the end of the world.

In practice, the Board also overrides this kind of stuff in appropriate
situations.

Feel free to suggest an exact change, though.

»Lucas

**Comment by pochmann** [comment]
2e makes it necessary: "Competitors must represent a country of which they hold citizenship".

**Comment by pochmann** [comment]
Oh a suggestion. Ok:

2e2) Competitors with updates to their citizenship status may change their country of representation in their first competition of a calendar year or when necessary due to not holding the old citizenship anymore.

That is if we do want people to represent countries they're citizens of. If we don't, then we could do this instead:

2e) Competitors must represent a country of which they hold citizenship or which they represented at an earlier competition the same year. [...]

**Comment by pochmann** [comment]
What do you mean with "overrides this kind of stuff in appropriate situations"? (example?)

**Comment by pochmann** [comment]
I just realized that 2e2 appears weak, btw. It says you may change your country in your first competition of the year, but it doesn't say you may _only_ do it then.

**Comment by Laura-O** [comment]
@SAuroux as you are probably the person who knows about most citizenship changes.
Do you think this is an issue and we need a regulation change?

**Comment by SAuroux** [comment]
Good question. Well, technically Stefan has a very valid point. 2e and 2e2 are kind of contradictory for people losing a certain citizenship they used to compete with. Actually, 2e2 only really makes sense for people with multiple citizenships, to prevent them to switch their citizenship regularly. Everything else is pretty much governed by 2e already. Why not reflect that specifically:

2e2) Competitors with more than one citizenship may only change their country of representation in their first competition of a calendar year.

**Comment by Claster** [comment]
Or maybe add an exception to the current 2e2:

Exception: if the citizenship of the country which the competitor represents is lost, they can change this country of representation any time (as soon as possible).

**Comment by SAuroux** [comment]
That's also good, possibly even better than my suggestion. :)
