### ISSUE TITLE
Proposal: add a definition for stopwatch

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#242]
Recently Gregor released an Android app called "CompAssistant" which includes a timer for inspection ([see speedsolving.com](https://www.speedsolving.com/forum/showthread.php?51409-CompAssistant-an-Android-competition-toolbox&p=1053957)). The name already suggests that this is a tool for competitions. 

This reminded me of a question I had earlier: what do we understand by the term "stopwatch" and what do we want to allow to be used in competitions?

I personally don't like the idea that people bring their own smartphones and use them for timing inspection or MultiBLD attempts. I don't have any evidence for this, but I think it's obvious that there are way more possible failures than when using simple stopwatches (e.g. apps can crash, more difficult handling).

**Comment by tristaaan** [comment]
> I don't have any evidence for this, but I think it's obvious that there are way more possible failures than when using simple stopwatches (e.g. apps can crash, more difficult handling).

Not only possible failures but also rule breaking. With access to source code one could alter the rate at which the display updates, here's a crude example: [codepen](http://codepen.io/tristaaan/pen/PwjWQK)

**Comment by Laura-O** [comment]
# Proposal

Although we don’t require stopwatches to meet any quality level, I want to suggest to add a definition of the term stopwatch to the regulations:

_7f1e) Stopwatch: A handheld watch with the main purpose to measure an amount of time. Other devices (e.g. smartphones) may be used at the discretion of the WCA delegate._

I don't know if the use of smartphone apps has caused any incidents in competitions. However I noticed several smaller issues in competitions, especially concerning the handling (e.g. the judge had to tap on the touchscreen several times to stop the timing).

Recently there were also introduced two tools designed to measure the inspection time:

[Competition Inspection Tool](https://www.speedsolving.com/forum/showthread.php?48791-Competition-Inspection-Tool)

[CompAssistant for Android](https://www.speedsolving.com/forum/showthread.php?51409-CompAssistant-an-Android-competition-toolbox)

## Pros
- Eventualities like phone calls, low battery warnings etc. might interrupt the timing (also mentioned by [António Gomes](https://www.speedsolving.com/forum/showthread.php?48791-Competition-Inspection-Tool&p=1021654&viewfull=1#post1021654)). 
- Smartphone apps can be manipulated easily. This might seem unrealistic at first sight, but using visual programming tools like the App Inventor for Android even an unexperienced programmer can create a stopwatch app which is running a bit slower than normal.
- It's nearly impossible to check during competitions if a smartphone app is suitable to be used as a stopwatch. Especially when timing longer attempts it's not easy to observe if the displayed time is the actual time.
- Smartphones are more difficult to handle than a simple stopwatch, especially when using them one-handed (which is necessary when uncovering the puzzle at the beginning of the inspection phase).

## Cons
- Stopwatch apps for smartphones are an easy alternative if there aren’t any stopwatches available.
- Additional functions (e.g. flashing/color changing at 8 and 12 seconds) can help to observe the regulations.
- Stopwatches are not fail-safe either. Timing might be interrupted through low batteries or non-working buttons as well.

**Comment by lgarron** [comment]
I'd like us to figure this out at some point, but I think it's more important to have a way to determine what kind of smartphone timer should count. 

One option is to allow only a pre-approved handful of timers with the desired properties (e.g. continues timing even if you switched apps or locked the phone accidentally), and/or the built-in device app.

**Comment by Laura-O** [comment]
Allowing some pre-approved timers will make things a lot more complicated as the delegate has to check whether the timer used is allowed or not.
Furthermore, this doesn't solve the problem of mishandling and manipulated timers.

**Comment by lgarron** [comment]
> Furthermore, this doesn't solve the problem of mishandling and manipulated timers.

If a judge wants to do this on purpose, we can't realistically stop them.

We should have an answer the Delegate can give if a judge asks "can I use my smartphone for timing inspection/the solve?"
We can leave it as a catch-all "discretion of the Delegate", but as you point out not all possible uses of a smartphone timer may be good.

**Comment by Laura-O** [comment]
Here is another example why I don't like the use of smartphones as stop watches:
https://youtu.be/dCE1-su2BAI  (first attempt)

When the competitor puts his hands on the timer, the judge is looking at the smartphone display. Doing so, he isn't able to see any irregularities in the starting procedure.
After the timer has been started, he is still looking at the display, turning his head to the competitor 2-3 times, but mainly looking down, using his smartphone. You can't see what he is doing: if he is trying to reset the stopwatch or if he is doing something else. However, seeing this reminded me of this issue again.

I have also noticed that judges ask if they can use their smartphone for timing more frequently. For example, at Cubelonia 2016 there was a competitor who asked if he could use his smartphone for judging a BigBLD attempt although there were stop watches available.

I would be happy if we could find a way to clarify that smartphones should only be used as stop watches under exceptional circumstances.

**Comment by Claster** [comment]
> When the competitor puts his hands on the timer, the judge is looking at the smartphone display. Doing so, he isn't able to see any irregularities in the starting procedure.

What would be the difference if this judge used stopwatch? He would still need to look at both the stopwatch and competitor's hands. I think the problem is with this judge, not the fact he uses smartphone.

**Comment by Laura-O** [comment]
> What would be the difference if this judge used stopwatch? He would still need to look at both the stopwatch and competitor's hands. I think the problem is with this judge, not the fact he uses smartphone.

I think the main difference is that you can stop a simple stop watch without looking on it. When you use an app it's more difficult because there is usually only a very small button to start/stop it. I attached a screenshot of the default stop watch on my smartphone. It's not easy to touch the start button when holding the phone firmly in my hand. Of course, this is even more difficult for people with smaller hands.

You're right with saying that he is a bad judge. The judge of the other attempts does his job much better.
I have a strong opinion against the use of smartphones as stop watches, so my perception might be influenced, but I am quite sure this judge would pay more attention having only a boring stop watch in his hand.

This issue might also be a good topic for a delegate voting.

![screenshot_2016-01-12-13-06-33 1](https://cloud.githubusercontent.com/assets/362249/12263238/c33e40f4-b92d-11e5-8675-53ee2017e86b.png)

**Comment by lgarron** [comment]
> I think the main difference is that you can stop a simple stop watch without looking on it.

I paid attention to stuff like this with http://www.cubing.net/inspection/
You can touch anywhere on the screen to start/stop, and you can see 8 and 12 seconds out of your peripheral vision.

![inspection](https://cloud.githubusercontent.com/assets/248078/12266052/b6af813c-b8f5-11e5-85c7-11f6374cdb0d.gif)

I won't claim that my tool is the only smartphone stopwatch we should allow, but I think the best way for us to avoid bad smartphone stopwatches is to require using apps from a specified list on the WCA website.

> This issue might also be a good topic for a delegate voting.

I don't really see why it would be. It would be valuable to hear from Delegates about issues with stopwatches, but I feel like the votes themselves would be arbitrary opinions.

**Comment by Laura-O** [comment]
> I won't claim that my tool is the only smartphone stopwatch we should allow, but I think the best way for us to avoid bad smartphone stopwatches is to require using apps from a specified list on the WCA website.

Yes, that would be an alternative. Still, they should be used in exceptional cases only, like if delegates forget to bring their stop watches.
Making the possession of a smartphone a requirement for being a judge is not a good idea.

**Comment by lgarron** [comment]
> Still, they should be used in exceptional cases only, like if delegates forget to bring their stop watches.

I disagree. I'm definitely a more reliable judge when I use my inspection timer.

> Making the possession of a smartphone a requirement for being a judge is not a good idea idea.

Definitely agreed. The organizers should be responsible for making sure they have sufficient equipment to run their competition.

**Comment by Laura-O** [comment]
Closing this issue originally opened by me. I was young and naive back then.
