### ISSUE TITLE
Require tentative time limits / round advancements / rounds to be explicitly marked as tentative

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#244]
This has been suggested several times for transparency/fairness, and I think tentative events are a great way for organizers to handle uncertain amounts of competitor attendance.

However, I don't know of a good way to require this that doesn't invite organizers to create a blanket disclaimer like "All rounds and time limits are tentative subject to change."

**Comment by Laura-O** [comment]
This was already implemented by the Board, so I'm closing this here.

**Comment by jfly** [comment]
Sort of. The WCA website does not yet have support for marking events as tentative. See: https://github.com/thewca/worldcubeassociation.org/issues/1821.
