### ISSUE TITLE
Back-up solves for misscrambles?

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#245]
If a competitor finds out that he received an incorrect scramble before the competition ends, can he request doing an extra solve (e.g. a 6th solve for avg5 events) to potentially replace the incorrectly scrambled solve, if it's unsure whether it'll be invalidated after the competition ends?

For example, Nathan Soria received a 6-move Skewb scramble at St. Francis Winter Open 2015, which he solved in 1.71, and the solve was declared a DNF by the Board a week later. If Nathan noticed at the competition that his scramble had a 6-move solution, which is against Regulation 4b3c, could he have asked to do a solve on scramble E1, as a precaution, to replace his 1.71 in case it's later invalidated?

I believe it makes sense to allow this, since it would be like how extra solves are usually rewarded for incidents. However, I also think that allowing an originally unofficial solve to become official is strange, and could create loopholes.

Thoughts?

**Comment by Laura-O** [comment]
If the competitor finds that out during the competition that's an incident
for me and is therefore covered by 11d).

I actually don't like the idea of mentioning the possibility of a backup
solve in the regulations. How do you want to prove that there was an
incorrect scramble?
Furthermore how could we assure that the competitor doesn't know something
about the extra scramble when this is awarded after the end of the round?

2015-02-08 6:22 GMT+01:00 Sarah Strong notifications@github.com:

**Comment by lgarron** [comment]
Also see suggestion #4 in [this comment](https://github.com/cubing/wca-documents/issues/121#issuecomment-64724071).

> If the competitor finds that out during the competition that's an incident
> for me and is therefore covered by 11d).

Unfortunately, competitors and Delegates don't like inconsistencies over stuff like this.

Sometimes issues like this get discussed and reach consensus on the Delegate list, which means some/most (but not all) Delegates are consistent, but competitors have no way of knowing. 11d) is fine for one-off things, but incidents like this are becoming common enough that many people would probably prefer an official policy - which the Regs/Guidelines are for.

In any case, Sarah had an example where the competitor could have proved it (especially if there was video).
I think the basic premise is safe: allow competitors an extra attempt if there was an incident, and only let it count if it was found that the original attempt was invalid _without any fault of the competitor_. But I share Sarah's concern that this could probably be abused
