### ISSUE TITLE
Does discussing scrambles count as cheating/defrauding?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#248]
Discussed in the [New Avge Open 2015 Report](https://groups.google.com/forum/#!msg/wca-delegates/usjApqvZyQg/rGrAys7y-ooJ). The issue was whether to disqualify a competitor's first round scramble based on their violation of 2j2 (discussing scrambles) during round 2.

> 2g3) Competitors in the Competitors Area must not communicate with each other about the scrambled states of the puzzles of the round in progress. Penalty: disqualification of the competitor from the event, at the discretion of the WCA Delegate.
> 2j2) If a competitor is disqualified during the course of an event, his earlier results remain valid. Exception: cheating or defrauding (see Regulation 2k2a).

(Sébastien pointed out 2j2 until it prevailed.)

**Comment by hanwu85** [comment]
From the discussion, it seems like it is no longer an issue.
If someone is disqualified after the X attempt, all the attempt after X should be DNF.
The X attempt should stand; the previous rounds should also stand.

Closing this issue.
