### ISSUE TITLE
2i - slight problem

### ISSUE THREAD

**Issue by a-Maass** [thewca/wca-regulations#249]
2i) While competing, competitors must not use electronics or audio equipment (e.g. cell phones, MP3 players, dictaphones, additional lighting).
2i1) Competitors may use certain non-electronic aids that do not give the competitor an unfair advantage, at the discretion of the WCA Delegate. This includes:
2i1a) Medical/physical aids worn by the competitor (etc. glasses, wrist brace, hearing aids).
2i1b) Earplugs and earmuffs (but not electronic noise-cancelling headphones).

The problem with that is that regulation allows hearing aids as a non-electronic aid, but pretty much all  hearing aids nowadays are electronic. (At first glance it may look like it says hearing aids are an exception to the non-electronic aid rule but it isn't)

I propose that this regulation is changed to something similar to this:

2i) While competing, competitors must not use electronics or audio equipment (e.g. cell phones, MP3 players, dictaphones, additional lighting). Exception: Medical devices/aids, at the discretion of the delegate. (etc. hearing aids, pacemakers)
2i1) Competitors may use certain non-electronic aids that do not give the competitor an unfair advantage, at the discretion of the WCA Delegate. This includes:
2i1a) Medical/physical aids worn by the competitor (etc. glasses, wrist brace).
2i1b) Earplugs and earmuffs (but not electronic noise-cancelling headphones).

**Comment by lgarron** [comment]
Thanks. Issue #231 covers the general issues as well as the specific case of hearing aids.

I'd also like to find a way to phrase this so that the exception isn't listed twice (in 2i and 2i1a)

**Comment by lgarron** [comment]
(By the way, I'm not closing this because it wasn't valid – just because it happens to be straightforward duplicate of #231. I'd still like to fix this, and I encourage further discussion on the #231.)

**Comment by a-Maass** [comment]
Okay, hopefully this will be fixed, right? Didn't know this was a duplicate of that issue.

**Comment by lgarron** [comment]
Yeah, it should definitely be fixed, even if it's a minor formatting issue (with clear intentions).

**Comment by lgarron** [comment]
It can also be tricky to find past issues about things, but GitHub's issue search is pretty good: https://github.com/cubing/wca-documents/issues?q=is%3Aissue+is%3Aopen+hearing
