### ISSUE TITLE
Leniency for newer competitors

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#251]
It's been a common practice in some parts of the world to give leniency on certain parts of the regulations, such as not waiting for green light, touching the cube before the judge has inspected it, going over the inspection time, among others.  However, others believe that we should strictly follow the regulations, asking that this should only be done if this "leniency" was somehow codified.  

Is this something we desire, and if so, how do we incorporate this?

**Comment by KitClement** [comment]
My suggestion:

2t) Each competitor must be familiar with and understand the WCA Regulations before the competition.
2t1) A first time competitor may be awarded a resolve or be exempt from a time penalty if it was clear that the issue was caused by a misunderstanding of the regulations, at the discretion of the WCA delegate.

**Comment by lgarron** [comment]
Instead of restricting it to new competitors, I would have suggested generalizing it so that the Delegate can be lenient based on the (perceived) _intent_ of the competitor.

That basically happens in practice, anyhow.

**Comment by KitClement** [comment]
Fair enough -- would it be better to say an "inexperienced competitor" just
so it's clear that this kind of leniency shouldn't be given to competitors
that are expected to know better?  I'm afraid that too few restrictions
could lead this to be interpreted too loosely.

**Comment by pedrosino** [comment]
I agree with Lucas. Maybe the competitor is not a first-timer, but a young kid (we get a lot of 6-10 kids here), and the same principle could apply.

Replacing with "inexperienced" sounds good, since there is the "discretion of the delegate" at the end.

**Comment by Laura-O** [comment]
I'm fine with leniency in general.
However I am not sure if we need to add this to the regulations especially with the term "at the discretion of the WCA delegate". I doubt that this will change something in practice.
Furthermore: isn't this an incident ("Incorrect execution of event procedures, by officials or competitors", 11a1)?

**Comment by KitClement** [comment]
Yes -- thank you, Laura.  Here's an update:

2t1) An inexperienced competitor may be awarded a resolve or be exempt from a time penalty if it was clear that the incident was caused by a misunderstanding of the regulations, at the discretion of the WCA delegate.

I guess the question is now if we should specify what penalties are allowed to be exempt, as I agree with Sebastien's thoughts from the thread -- as written, this gives a little too much liberty.

**Comment by lgarron** [comment]
[Report for SP Open 2015](https://groups.google.com/forum/#!msg/wca-delegates/qoFK7h1wrOw/CYSnYjollesJ) by Gaurav Taneja 

> There were many participants who were attending it for the 1st time and some of them didn’t know how to operate the timers. I had instructed the judges to do so, but they forgot to give them. So I had to give them resolve for the 1st solve.

**Comment by lgarron** [comment]
I'm wondering if there's a way we can strengthen this to be about competitors who are inexperienced at competing in general, and not about competitors who are "inexperienced" about something in particular ("Oh, I didn't know! Really!").

An example from [Report for Oficina Open 2015](https://groups.google.com/forum/#!msg/wca-delegates/z-At0SxoS4c/f0xItzhXKN4J):

> I saw a guy filming his solve with the frontal camera of his cellphone. I explained to him why he couldn’t do that and he understood. I didn’t DNF’d because I saw he didn’t even look at it during his solve.

However, since we specify that this results in an entirely new attempt, I'm inclined to say we can trust the Delegate to judge this.
