### ISSUE TITLE
A6b2) "delegate" is inconsistent with the rest of the Regs

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#253]

**Comment by Claster** [comment]
If you are up to this, you could also fix 1e1a, 1e2, 1f2, 2h, 3d3 and 3l+.
And maybe 2s+.

2015-04-21 12:19 GMT+02:00 Lucas Garron notifications@github.com:

> Closed #253 https://github.com/cubing/wca-documents/issues/253.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cubing/wca-documents/issues/253#event-286049581.

## 

Best regards,
Oleg Gritsenko

**Comment by lgarron** [comment]
Good point.
