### ISSUE TITLE
Allow competitors to bring their own chairs/stools for feet

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#255]
Delegate thread: [Can a competitor bring his own chair for WF?](https://groups.google.com/forum/#!msg/wca-delegates/41Iw6cKyHYw/d9k6oRRuQRUJ). The particular example in question was small children being allowed to bring their own chairs in case the competition doesn't have them.

**Comment by AlbertoPdRF** [comment]
Is this something we need? Regulations don't explicitly allow it, but neither forbid it.

**Comment by lgarron** [comment]
> Regulations don't explicitly allow it, but neither forbid it.

Right. But if a tall/short competitor prefers them and can't consistently rely on a Delegate judgment about whether they're allowed to bring their own chair, it's not fair.

(Also, bringing a large piece of equipment like a chair is a burden, and I would rather have a Regulation that states either that competitors must use the chair provided, or that the Delegate should be able to accommodate competitors of various sizes to a specific extent, e.g. by having chairs of different heights on hand if competitors ask ahead of time.)

**Comment by Samuel-Baird** [comment]
@lgarron this issue can be closed
