### ISSUE TITLE
Require all competitions to announce total competitor capacity

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#256]
There have been several recent competitions where the demand for signups outgrew the venue size at the last minute. A simple way to address this: every competition is required to declare a realistic upper for the number of competitors the venue can accommodate.

The Board can be flexible about this if there are venue changes.
We can also allow an unlimited capacity, as long as the organizer is willing to commit to accepting every competitor who would like to sign up.

**Comment by Laura-O** [comment]
That's implemented on the website now.
