### ISSUE TITLE
Require competitions to announce conditions for advancing from each round, before the round has begun

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#257]
These decisions are often made after the round as finished, which is not really accountable, and a bit unfair (it's easy to shift the cutoff around based on how nice you want to be to people near the cutoff... which are often your friends).

Proposal: require organizers to specify a cutoff (number of competitors or time limit) for advancing from each non-final round. This cutoff must be selected before the rounds start, and should preferably be listed on the website before the competition.

In case there are not enough competitors for a round, the Delegate can use his/her judgment. A simple policy is to allow the maximum number of competitors in that case.

**Comment by pedrosino** [comment]
Sometimes you advance more people because there is time left, which you only find out after the previous round is over...

I agree that announcing this before the non-final round starts, but it may be a shot to the foot if you end up running later after that event/round.

**Comment by viroulep** [comment]
For the record, back in 2010 you had to announce this before the beginning of the round : 

```
9p2) Either the best x competitors proceed to the next round,
or all competitors who beat a specific result (announced before the round).
```

**Comment by lgarron** [comment]
I haven't tried to keep track of incidents, but [Athens Fall Late Night 2016](https://groups.google.com/d/msg/wca-delegates/r0RQh8Y-9PA/X8M98UemAwAJ) is relevant.
