### ISSUE TITLE
Authority of the Board

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#262]
This was addressed in the draft of the WCA constitution, but is currently not addressed in the regulations, which is the only governing document of the WCA at this time.  In practice, board decisions are held in higher power than the regulations themselves, but there is no exception given for the Board to modify results that contradict the regulations.

**Comment by lgarron** [comment]
Articles 8 and 11 are the most relevant. I think we decided Article 8 makes more sense, since this is more general than individual "incidents".

**Comment by viroulep** [comment]
The changes are in `official`, I don't think any further action is needed for this issue.
