### ISSUE TITLE
O-Ring Information

### ISSUE THREAD

**Issue by FatBoyXPC** [thewca/wca-regulations#265]
Would it be appropriate to put the oring size information on the guidelines? I feel like this would make the information more readily available and I wouldn't have to search my email for it.

**Comment by KitClement** [comment]
Ideally, based on the evidence we have from delegate reports, we would like to make O-rings mandatory.  Realistically, this is probably not possible.  It would be nice to explicitly allow the usage of O-rings in the regulations, and then make a guideline that discusses the sizing.  Thoughts?

**Comment by KitClement** [comment]
Closing and adding discussion to #243.

**Comment by lgarron** [comment]
Since this is about the exact size, let's reopen this one.

I think the most appropriate thing would be a link to a separate page, perhaps in a section for organizers on the WCA website.

**Comment by Laura-O** [comment]
Ming recommended a size of 1.5cm inner and 2.2cm outer diameter

**Comment by Nanush7** [comment]
This was opened 7 years ago 👀 
Is "1.5cm inner and 2.2cm outer diameter" still the recommendation? I assume the answer is yes, but just to be sure before opening a PR. @Laura-O and maybe @thewca/wqac

**Comment by KitClement** [comment]
Yeah, I believe that hasn't changed. However, there are 3d printed button protectors that often work better than O-rings and are easier to glue to timers. Speedstacks has this one for Gen 4, but hasn't released one for Gen 5 yet. https://www.speedstacks.com/stackers/free-stuff/
