### ISSUE TITLE
Remove Clock Scrambling Orientation?

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#269]
This is often not done in practice, and serves little purpose other than the colors matching the pictures in TNoodle.  It also makes it easy to "misscramble" simply by not using the correct side at the start.

**Comment by lgarron** [comment]
> This is often not done in practice

To clarify: At competitions, scramblers often don't orient clocks according to the Regulations.

(I don't know how true that is, but anecdotal evidence from Delegates suggests it certainly happens.)

**Comment by Laura-O** [comment]
Fixed in 3cd54d8acad2e0d2a48eb1abfdb92f4eb6e4aabe
