### ISSUE TITLE
Using video evidence to obtain result when competitor resets timer

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#270]
Our recent changes state that judges should not write down times from memory if a competitor resets the timer before a judge inspects.  To simplify this process, I'd like to not allow video evidence to retrieve the time -- it goes against what the well-defined penalty for this given in A6f and is not always a reliable way to retrieve a time (display turns off at end of solve,  video may be a different solve, display often has long delay to show the actual time when the timer is stopped, etc.).

**Comment by viroulep** [comment]
This has been dealt with by 718f5a0a6d34d5b5450b10f197fa3be5b6e84861.
