### ISSUE TITLE
Ambiguities in Article 3d1 for partial color-blind solvers (Accessiblity issue)

### ISSUE THREAD

**Issue by ghost** [thewca/wca-regulations#271]
PROPOSED CHANGE

3d1) Exception: Competitors with a medically documented visual disability may use textured or patterned puzzles with different textures or patterns on different faces.   Textures/patterns must be uniform per face.  Patterns may be painted, drawn by marker, or applied with an overlay sticker.  If the visual disability prevents the solver from seeing only a range of colors, textures/patterns need not be present on every side.  Each face should have a distinct colour, to aid in scrambling and judging.

Article 3d1 is confusing when applied to partial colorblindness.

Article 3d1 currently states:
3d1) Exception: Competitors with a medically documented visual disability may use textured puzzles with different textures on different faces. Textures/patterns must be uniform per face. Each face should have a distinct colour, to aid in scrambling and judging.

Sentence 2 mentions patterns, yet patterns are not mentioned in section 1.  Also "patterns" are not defined. 

People with partial colorblindness (the most common forms) can usually find 6 colors that they can easily distinguish, and therefore resticker 1 or 2 sides of a cube.  However with Megaminx finding 12 distinct colors can become much more difficult for solvers that do not perceive 1/3 of the color spectrum, which is a fairly common form of color-blindness.

Does 3d1 intend that that a partially colorblind solver should be able to draw a simple pattern, such as and X or a dot (with a sharpie, for instance) on one side of a cube?  
I propose that this exemption should be specifically allowed.  I do not see the potential for abuse since medical documentation is required to qualify for the exemption.

The use of patterns also becomes a greater issue with the acceptance of the new generation of stickerless cubes.  If this proposed wording is used, colorblind solvers, with a preference for the "feel" of the stickerless cube would have the same access to the new cubes as non-visually impaired solvers.

**Comment by DeneBeardsley** [comment]
I would suggest a slightly more distinct update to the regulation:

3d1) Exception: Competitors with a medically documented visual disability are entitled to a suitable modification:
3d1a) Blind competitors may use textured puzzles with different textures on different faces. Each face should have a distinct colour, to aid in scrambling and judging.
3d1b) Colour blind competitors may use puzzles with different patterns on different faces where no distinct colours are available. Patterns may come from stickers or be drawn.

3d1b+) CLARIFICATION Patterns do not need to be present on every face, but only on faces where a distinct colour cannot be found. Patterns must not have any texture that makes them distinguishable from similar pieces.

**Comment by KitClement** [comment]
The only thing I would like to see is that the patterns should be reasonably uniform (similar to acceptable sticker wear)

Maybe update this clarification?

3d1b+) CLARIFICATION Patterns do not need to be present on every face, but only on faces where a distinct colour cannot be found. Patterns must not have any feature (e.g. textures, pattern irregularities) that significantly distinguishes them from similar pieces.
