### ISSUE TITLE
A1c clarification

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#272]
The most talked about regulation in this update seems to be A1c.  I should have followed up with Sarah on getting a clarification written sooner, that was definitely my fault.  After talking with her, we came up with this:

> A1c+) [clarification] When using discretion, delegates should consider preventing competitors from being a severe detriment to the competition while still upholding the spirit of the WCA and providing a fun atmosphere for competitors. Delegates should also not punish competitors for "poor" results when they are competing to the best of their abilities.

It's a bit open ended, but I think that's the idea -- the application of this regulation should really depend on the context of the competition being held and whether the intentionally poor result is a significant detriment to that competition.  For example, at a small, side-events competition with FMC, an intentionally poor FMC solution may not be a large detriment, but at a larger national/regional competition, grading these solutions may be a detriment. 

Thoughts?

**Comment by lgarron** [comment]
That seems like an awfully fancy clarification to go in Article A.
I guess I mostly feel like "while still upholding the spirit of the WCA and providing a fun atmosphere for competitors" doesn't really help much here. Maybe actual examples (e.g. wasting time) would be better.

Apart from that, looks fine to me.

**Comment by KitClement** [comment]
Fair point -- it is a bit philosophical for a section that's more procedural.  Based on your comments and a few of my own thoughts, I propose this:

> A1c+) [clarification] WCA delegates should only use their discretion to prevent competitors from being a severe detriment to the competition (e.g. wasting time and/or competition resources). Competitors should not be penalized for a "poor" result when they are competing to the best of their abilities.

Again, any comments are appreciated.
