### ISSUE TITLE
Using Stackmats for 4BLD, 5BLD, MBLD

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#273]
As it stands currently, stackmats seem to be required for all events by the regulations, however, in practice, 4BLD, 5BLD, and MBLD often go without stackmats in competitions.  This isn't too big of a deal to require for 4BLD or 5BLD, but is often unnecessary for competitiors who will undoubtedly go over 10 minutes.  For MBLD, it's a nuisance, as it can get in the way when picking up and putting down cubes, and aid in accidentally rotating/pushing cubes.

I'd like to make stackmats not required at least for MBLD, and consider it for 4/5 BLD.

**Comment by lgarron** [comment]
> stackmats seem to be required for all events by the regulations

[Not quite](https://www.worldcubeassociation.org/regulations/#A1b1):

> A1b1) ... For events without inspection where the competitor is expected to exceed 10 minutes, use of the Stackmat timer is optional.

**Comment by KitClement** [comment]
Ah -- thanks for that clarification.  But that still requires the use of
the mat, right?  That might be annoying in MBLD with those two little knobs
on the newer mats.

It also begs the question -- is the mat really necessary?  I can see it providing a somewhat consistent landing surface, but this matters little for long events.

**Comment by lgarron** [comment]
Ah, then you should talk specifically about the mat. ["Stackmat"](https://www.worldcubeassociation.org/regulations/#7f1a) includes the timer.

**Comment by LorenzoVP** [comment]
In my personal experience, it is annoying with the new mats.
Also, I don't really see the point in requiring mats for MBLD, sometimes it
means that you have to take out mats from the main stage for a side event.
Could we just consider not requiring them for big blinds and multi?

Lorenzo

2015-06-18 1:26 GMT+08:00 Lucas Garron notifications@github.com:

**Comment by lgarron** [comment]
> Could we just consider not requiring them for big blinds and multi?

Sounds fine to me. I've never been to a major competition that used them for those events, and I suspect this is common.
Mats standardize the properties of the surface for faster events, but I don't see a need to require them here.

**Comment by KitClement** [comment]
Thoughts on these additions?

```
   - 7f2b) Exception: For 4x4x4 Cube: Blindfolded and 5x5x5 Cube: Blindfolded, the mat is optional when the timer is not in use.
   - 7f2c) Exception: For Rubik's Cube: Multiple Blindfolded, the use of a Stackmat is optional.
```

This still requires a full stackmat for 4BLD/5BLD when the time is expected to be under 10 minutes.  Since we round all times in MBLD to the nearest second, 

But maybe this should this be something in Article A or B?  The current exception lives in Article A for any solve above 10 minutes and pertains to solves that are greater than 10 minutes, which wouldn't cover the case for MBLD.

**Comment by KitClement** [comment]
Now that I think about it, I think this is cleaner:

> - A1b1) For events with inspection, a Stackmat ~~timer~~ must be used in addition to the stopwatch. For events without inspection where the competitor is expected to exceed 10 minutes, use of the Stackmat ~~timer~~ is optional.
> - A1b2) For Rubik's Cube: Multiple Blindfolded, use of the Stackmat is optional.
> - A1b3) If a time from the Stackmat timer is available, it is the original recorded time. Otherwise, the stopwatch time is the original recorded time.

I've seen that there is precedent for renumbering regulations in cases similar to this, so that should be fine as well.
