### ISSUE TITLE
A7a1) "they call" should be "the judge calls"

### ISSUE THREAD

**Issue by kotarot** [thewca/wca-regulations#281]
In statement A7a1,

```
they call
```

should be

```
the judge calls
```

like A7a2 or A7a3.

Note that similar expressions appears in A3d2 and A3d3.

**Comment by KitClement** [comment]
I find this okay, as the sentence has only one possible antecedent, which "they" refers to.

**Comment by lgarron** [comment]
I have been using "they" when 1) it's unambiguous, and 2) the relevant person has explicitly ben mentioned earlier in the sentence already. This allows us to keep it simple, but readable and consistent.

Both conditions apply here, so I would prefer to keep it the same.

**Comment by kotarot** [comment]
I understand.
Then, base on the conditions above, I think `the judge calls` in A7a2 should be `they call`, as we use `they call` in A7a1.

**Comment by KitClement** [comment]
Yes, for consistency, I would agree that "they" is suitable for A7a2.  In case I'm missing something, I'll wait for Lucas to make a comment or agree as well.

**Comment by KitClement** [comment]
Just to make sure I don't forget about this, I'm going to push a commit to change A7a2, but I will leave this issue open in case there is more input.

**Comment by kotarot** [comment]
OK, thanks!

**Comment by lgarron** [comment]
If person X appears twice in a sentence (and no one else does), I've been writing:

> ... X ... they ...

rather than:

> ... X ... X ...

That said, being explicit is not bad, as long as it's clear, and not too awkward.
