### ISSUE TITLE
"submit", "hand in", and "turn in" in Article E

### ISSUE THREAD

**Issue by kotarot** [thewca/wca-regulations#282]
There are three different words "submit", "hand in", "turn in", which all seem to be almost the same meanings in Article E in Guilelines.
I'm not an English speaker and I don't know the difference among the meanings of these words,
but they can be unified for clarity.

**Comment by KitClement** [comment]
I don't see the instance of "hand in" but I will change the "turn in" to "submit" shortly.

**Comment by lgarron** [comment]
"Submit" sounds good. We should add this to the [style guide](https://github.com/cubing/wca-documents-extra/blob/master/style-guide.md#recommended-word-choices).

**Comment by KitClement** [comment]
Added to the style guide.  Thanks, all.
