### ISSUE TITLE
WCA Delegate vs delegate

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/wca-regulations#290]
It looks like for some places in the regulations, 'delegate' got changed to 'WCA Delegate,' but not in all places. Is there a reason behind this?

**Comment by KitClement** [comment]
The latest commit that I checked shows no such differences (that I can see), do you have any places where you see this?

**Comment by Claster** [comment]
A7g, A1c+ have the word "delegate" with lowercase letter.

**Comment by Laura-O** [comment]
Thanks @Claster, fixed now.

**Comment by lgarron** [comment]
Looks good. Thanks for starting a new `fixes` branch, @Laura-O!
