### ISSUE TITLE
A1a2: cumulative time limits for more than one event?

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#296]
A delegate asked me if he can define cumulative time limits for two events.

[A1 + A1a2](https://www.worldcubeassociation.org/regulations/#A1a2) say:

> A1a) The organisation team must enforce time limits for attempts and/or rounds.
> A1a2) Cumulative time limits may be enforced (e.g. 3 attempts with a cumulative time limit of 20 minutes). The time elapsed in a DNF result counts towards the cumulative time limit.

That means that you can enforce time limits for any combination of attempts as "attempts" is not restricted to a specific round or event. Correct me if I am wrong, but I couldn't find a regulation that forbids this.

I basically like this option for BigBLD events (e.g. 2 hours for all 4BLD and 5BLD attempts). However, I am undecided if this makes sense in general (1:30 minutes for 3x3 and Square-1?).

**Comment by pedrosino** [comment]
I'm not sure I understand the question...
Cumulative limits are just another type of limits, and they can be set in any event/number of events.
They are more commonly used in bld, as you said, but could be used for other events too.

**Comment by Laura-O** [comment]
To clarify this (I think you got that wrong): I'm talking about having 
cumulative time limits for more than one event combined (like having two 
hours for 3 attempts of 4BLD _and_ 3 attempts of 5BLD together) and not 
having a cumulative time limit in several events at one competition.

**Comment by pedrosino** [comment]
Oh, I see. Does it mean that I can take 1:30 for 5x5 and then do 3 attempts for 4x4, in 5 min each?
I don't see the point, but this is interesting...I guess you could set a x-hour window for both events and have a cumulative limit for each.

**Comment by lgarron** [comment]
I haven't seen this abused, but allowing cumulative limits on multiple events sounds more like an Article Z exception. I wouldn't mind a clarification, but I'll leave @Laura-O to pursue it. :-)

**Comment by Laura-O** [comment]
I'm not sure yet if we need a clarification. I think I will wait for more feedback and/or how this works in practice (if the mentioned delegate uses it).

**Comment by Laura-O** [comment]
As far as I know the mentioned delegate hasn't enforced such a cumulative limit.
I still like this idea in theory, but I think it's really hard to manage: the delegate/organizer would have to keep two scoresheets (or even more) synchronized to make sure the results of both results are considered.

So this should be changed to "Cumulative time limits for rounds may be enforced[...]".

**Comment by KitClement** [comment]
I have actually employed this before (with the justification Laura originally provided) for that exact purpose: 4BLD and 5BLD. When I do this, I am sure to switch scrambles very frequently, as some competitors will do 4BLD then 5BLD, and others will go the reverse order.

I agree that it doesn't make much sense at all outside of long BLD events.

**Comment by viroulep** [comment]
I'm closing this since it has been dealt with.
