### ISSUE TITLE
Logo on stickerless Cubes

### ISSUE THREAD

**Issue by MatteoColombo** [thewca/wca-regulations#298]
I have some doubts on stickerless cubes ang logos: 

Are logos allowed on stickerless cubes? 3d says that coloured parts must be of the same material, a logo is considered a coloured part? 

> 3d) Puzzles must have coloured parts, which must be one of the following: coloured stickers, coloured tiles, coloured plastic, or painted/printed colours. All coloured parts of a puzzle must be made of a similar material. 

In case logos are allowed on stickerless cubes, I think we should specify that they are forbidden during blindfolded events, improving 3l2 which says: 

> 3l2) The logo may be embossed, engraved, or consist of an overlay sticker. Exception: The logo must not be distinguishable by feel for blindfolded events (i.e. no embossings, engravings, or overlay stickers).
> 
> Exceptions: The logo must not be distinguishable by feel for blindfolded events (i.e. no embossings, engravings, or overlay stickers); logos are forbidden on stickerless cubes for blindfolded events

**Comment by Laura-O** [comment]
Logos are allowed on stickerless cubes. According to 3l ("A puzzle may have a logo on a coloured part.") a logo is not considered as a coloured part.

I don't understand why it should be specified that logos on stickerless cubes are forbidden during blindfolded events. 3l2 already says that any logo must not be distinguishable by feel for blindfolded events.
Maybe you can explain what should be specified?

**Comment by lgarron** [comment]
I think we're clear enough here.

Various other Regulations wouldn't make sense if you tried to consider the logo a colored part, and overlay stickers are clearly covered. Feel free to comment with more detail if you think there's still something to fix.
