### ISSUE TITLE
Clarify that any part of the body is permitted, by default

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#300]
From [this thread](https://groups.google.com/forum/#!msg/wca-wrc/92nUKJ6gRtw/W-gP1murAAAJ) in the Delegate list.

Most Delegates agree that using the knee (or any other body part) is fine. But people sometimes ask about this, and I think it's better to be explicit. An `A5b+` Guideline is probably the most appropriate place.

**Comment by pedrosino** [comment]
I agree with this. 
What is the policy on these small changes for the WRC?

**Comment by Laura-O** [comment]
I don't see a reason why such an issue should be changed in-between, separated from the next major change. It's just a small, uncontroversial clarification for a reappearing question, not an urgent fix.

In my opinion we should collect these issues (there are several more) and release them together. Anything else would eventually lead to an unstructured regulation-updates chaos and it would be really hard to keep track of the changes.

**Comment by Laura-O** [comment]
A similar incident was reported [here](https://groups.google.com/d/msg/wca-delegates/YmwvySyQWMk/MXG3LoSxzHsJ): two competitors used their legs to fix pops.
