### ISSUE TITLE
Current application of A7g

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#305]
I'm not happy to create this issue, but I am more and more under the impression that A7g is not applied in a way that we wanted it to be (see #251). Instead of "legalizing" what many delegates already did before (i.e. exceptional extra attempts for new competitors), it gives many more options to grant extra attempts. The problem is that this is extensively used by some delegates and very rarely by others.
Furthermore, there have been several incidents where A7g was discussed or even applied just because the competitor was a newcomer and not because the incident was caused by his inexperience.
I don't want to cite specific examples here, but giving extras to a new competitor accidentally stopping the timer in OH or a competitor failing to start the timer in his first attempt of a new event but at his third competition, does not meet the intention of this regulation.

I think we can improve the situation by defining when this regulation can be applied and for whom (competition newcomers only, not event newcomers). Maybe this can be done with a clarification in the guidelines.
I know this might be harsh in some cases, but I think it's the only way to assure fairness and equal conditions.

**Comment by lgarron** [comment]
Would it be sufficient to scope the A7g to competitors at their first competition, rather than the more general notion of "newcomers"?

**Comment by viroulep** [comment]
From the reports I read I _think_ that most of the A7g uses concerns first timers, and that most delegates use this not to be too harsh on them, which is the original intent of the regulation.
So I'd be fine with restricting it to first timers.

**Comment by Laura-O** [comment]
Yes, in general that would be sufficient.
However, A7g might also be relevant for newcomers in blindfolded events, even if it's their second or third competition.

**Comment by Laura-O** [comment]
I think we have reached a point where A7g is applied consistently.

We should learn from this and remember to provide the Delegates with some more examples and background information when similar regulations are introduced in the future.
