### ISSUE TITLE
Inconsistency in Guidelines

### ISSUE THREAD

**Issue by Luis-J-Ianez** [thewca/wca-regulations#309]
Where it says

```
## <article-12><incidents><incidents> Article 12: Notation
```

it should actually say

```
## <article-12><notation><notation> Article 12: Notation
```

**Comment by viroulep** [comment]
Oh this has actually already been fixed by @lgarron in 8cc0b0e1a3c8e42bf3a7962bf0bdacebfa5b32f9.

**Comment by viroulep** [comment]
Nevermind I was looking at the regulations file... (.....)
I've fixed it and will push it soon.

**Comment by Laura-O** [comment]
Awesome! Thanks for fixing this!
