### ISSUE TITLE
Misinterpretations of 3d) 

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#312]
As a result of [this discussion on the delegate list](https://groups.google.com/d/msg/wca-delegates/p3W7ots20_M/E47ifjNUBAAJ), I would like to suggest to improve the formulation of 3d). This was not the first time 3d) was brought into question, so I think it's time to change it.

My suggestions:
- Clarify that the "or" in 3d) is meant as an exclusive-or, i.e. coloured plastic, stickers and tiles may not be combined.
- Clarify that these coloured parts of the puzzle define the colour scheme and the paragraph is not about any other parts of the puzzle.

Spontaneous suggestion: _Puzzles must have coloured parts, which define the colour scheme of the puzzle and must be only one of the following: coloured stickers, coloured tiles, coloured plastic, or painted/printed colours. All coloured parts of a puzzle must be made of a similar material._.

**Comment by pedrosino** [comment]
I also suggest we slighty change 3d2 to

3d2) The colours of _**the coloured parts of the**_ puzzles must be solid, with one uniform colour per face. Each colour on the puzzle must be clearly distinct from the other colours.

Having only "colours of the puzzles" can be understood as the base plastic's colour.

**Comment by viroulep** [comment]
I'm not sure we are totally done with this after #337.
Additionally to Pedro's suggestion, I'd suggest to remove "on the puzzle", as the puzzle may _be_ the coloured parts.
I'll submit something.
