### ISSUE TITLE
"must remove" -> "should remove" in A3c4 (remove thin objects from Square-1)

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#315]
Sébastien [here](https://groups.google.com/d/msg/wca-delegates/Euslrb6v-lk/ky8cMZUZCwAJ):

> the use of "must" in A3c4 is indeed weird, since this is something the competitor simply "should" do to avoid a worse time. Nothing else but the time of the solve is affected if the competitor removes the object after starting the timer. 
> In this context I think "may" or "should" makes more sense for this rule.

**Comment by lgarron** [comment]
As pointed out in the thread, there is also no penalty for this.

If this is changed, we should make sure it remains clear that it's the competitor's responsibility to remove the object, not the judge's. (Contrast with [A3c3](https://www.worldcubeassociation.org/regulations/#A3c3), where the judge is at fault if the competitor does not do it.)
