### ISSUE TITLE
A7b1, "original recorded result" should be "original recorded time" (?)

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-regulations#316]
Following some discussions on the french forum, I think there may be a typo in A7b1 : "orginal recorded result" should probably be "original recorded time".

Everywhere else in the regulations "result" refers to the recorded/final result where here it refers to the original recorded time. There is also 4 occurences of "original recorded time", one being in the same regulation.

**Comment by sarahstrong314** [comment]
I've fixed the typo. The next version of the Regulations should have that error fixed.

Here's the commit: https://github.com/cubing/wca-regulations/commit/37c3680b68544c3f40294313560966053ee81955

**Comment by lgarron** [comment]
Thanks. The change is more consistent with my interpretation when I last tweaked things around this Regulation.

**Comment by viroulep** [comment]
Thanks Sarah, I guess I'll close this now.
