### ISSUE TITLE
Add a Readme explaining how to contribute here

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#317]
This is quite similar to #147, but I would like to emphasize again that we need an easy explanation on how to contribute in the Readme file.

Reading the WRC applications I received from non-delegates it was striking that most of them do not know how to participate in discussions here. Some of them are active in their local communities, leading regulation discussions at competitions or creating regulation quizzes for newcomers and would love to share their experiences and ideas. I think the WRC could benefit a lot from this.

I don't want to bother people with how to fork this repository and create pull requests. [Tim explained that two years ago on speedsolving.com](https://www.speedsolving.com/forum/showthread.php?45314-WCA-Regulations-2014-Logos-and-Stickers&p=940015&viewfull=1#post940015). I might have missed something, but except from the "usual suspects" no one has created a pull request for regulation issues since then.

I am sure the actual problem (or at least the main problem) why people hesitate to participate here is that they are unsure if they are welcome. Some of them might also miss the "Issues" tab on top of the page. We should clarify this in the Readme file, so people know what to do and where to go right away.

Initial drafts and ideas are welcome! :smile:

**Comment by lgarron** [comment]
I was initially afraid that encouraging _too_ much participation here would make it devolve into non-productive arguments (similar to a lot of speedsolving.com threads). However, I agree that we should make it easier to contribute; updating the README sounds like a good step.

In the [translation instructions](https://github.com/cubing/wca-regulations-translations#translation-instructions), I made sure that people could contribute just by emailing us the edited files. Just a thought.

**Comment by viroulep** [comment]
Maybe we should open a small wiki there with some information ?

There is also the style guide which is currently hidden in another repository : https://github.com/cubing/worldcubeassociation.org/blob/master/regulations/style-guide.md.
