### ISSUE TITLE
Some guidelines are missing the "SEPARATE" label

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-regulations#319]
5c+, for instance, refers to a removed regulation and should have the "SEPARATE" label.
I'll do a full check to see if there is some other cases.

**Comment by lgarron** [comment]
For reference: some of this was handled in #321 by 9ace12a12a7e0633d2d6721419c91cffcd57d0bf.
If you're going to check all of them, perhaps you could write a script?
Feel free to add one into [this folder](https://github.com/cubing/worldcubeassociation.org/tree/master/regulations).

**Comment by viroulep** [comment]
Since there is few guidelines I actually checked them by hand and only found these three, but indeed I could write a simple script to do that. It could be useful to check this in the translations.
