### ISSUE TITLE
4d2) "adjacent"?

### ISSUE THREAD

**Issue by Luis-J-Ianez** [thewca/wca-regulations#32]
Might sound fussy, but in this regulation:

4d2) Pyraminx are scrambled with the yellow face (if not possible, then the lightest face) on bottom and the green face (if not possible, then the darkest adjacent face) on the front.

the adjective "adjacent" is superfluous.

**Comment by lgarron** [comment]
Not really. If green is the darkest face and is opposite yellow, the instructions would technically be impossible to follow.

**Comment by pochmann** [comment]
Lucas, Pyraminx doesn't have opposite sides.

**Comment by lgarron** [comment]
That's a good point. I like the consistency with [4d1](https://www.worldcubeassociation.org/regulations/#4d1), but it doesn't really matter in the end.

**Comment by lgarron** [comment]
I prefer the consistency with 4d1, because it makes the intent clear. It doesn't affect the interpretation.
I'm going to close this without a change. If anyone _really_ minds, feel free to comment again.
