### ISSUE TITLE
Require Judges to take a Judging Quiz and A5a and A7f revision

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#320]
Require that the judge takes a standardized mandatory quiz before being able to judge.Throughout my past few competitions it has been brought to my attention that judges make many mistakes that go unnoticed, but can potentially hinder a competitors performance. Some of the issues: A3b (timer reset), A3b1 (asking if ready), A3d2-3 (8 and 12 seconds), A5a (must not talk to anyone other than the judge) A7(score taking).
Those are just some examples. My organization team and delegate have attempted several ways to correct this issue. Simply telling each new judge the rundown of how to judge is not always concrete and not specific at all, many judges cant retain the information they are told 5 minutes later and make mistakes judging. Me and my co-organizer have attempted to make a required instructional video that they must watch before being eligible to judge, but we failed to make the video simple and understandable for everyone. My delegate recently tried making judge cards to have at each station, but these went unnoticed by everyone. 
My next idea is some sort of quiz to require judge's completion. This would require the judge to familiarize themselves with regulations (which many have never read) and possible bring some past issue to the judges attention so that they will be aware not to make those mistakes. How is this different from giving them a rundown by mouth? Well by reading and making some sort of educated guess allows the judge to better retain that information.
I will admit I am a bit biased as my region is primarily consumed of "younger people." for reference my last competition had 5-6/35 of competitors with a high school degree. So I'm sure that these issues will go away as the experience and maturity of the region increases, but they are something that need to be addressed early. Other regions, possibly with more older competitors, probably experience these issues on a smaller scale. But I am sure that there is some region that has inexperienced judges that might need this resource to aid them.
Just some food for thought, I might start implementing this myself and see if it helps at my competitions.  

Now for some possible revisions that I came across while looking at this.

A5a) While inspecting or solving the puzzle, the competitor must not communicate with anyone other than the judge. Penalty: disqualification of the attempt (DNF).
    This rule has great intention but the competitor should only talk about logistics of the puzzle and not a seemingly meaningless conversation.
    The revision is Clarification: The judge may only talk to the competitor to notify him/her of some penalty or logistic
    Often a problem at our competitions we have issues with this.
    Example: Anthony Brooks was solving and the judge at ~5 seconds said "OMG world record" which in turn ruined the solve and cause him to get a really bad solve. He was giving an extra attempt once but the issue happened again with a different judge and he had to bite the bullet. This issue can also happen with an audience but as he said it is not noticeable with them but is extremely prevalent when the person next to you does it. This has happened an unbelievable amount at our competitions

A7f) When a competitor's score sheet for a round is complete, the judge delivers the score sheet to the score taker.
I know that WCA does not recognize the role of a runner, but generally the runner does this and if the judge were to do it, this can ruin a flow and make weird things happen (like giving a solved cube to a station). The runner also knows more about where that particular sheet goes, since a score taker may not be present throughout the entirety of the competition.

**Comment by shelchang** [comment]
While the requirements for being a judge should be reexamined (requiring every competitor to be available to judge isn't a practical regulation anymore as these days so many competitors are inexperienced and/or young), I don't think a standardized quiz should necessarily be codified in the regulations. It's certainly a good idea to try out for now at competitions that can afford the extra time and personnel.

**Comment by KitClement** [comment]
I think there are too many logistical issues with requiring a quiz, and
could handicap many organizers who have a small pool of judges that are
qualified. Are delegates accountable for keeping track of who has taken
such a quiz? How will a delegate know if a competitor has taken the quiz?
How will it be provided to non-English speaking countries?

**Comment by Laura-O** [comment]
In general, I agree with what Shelley and Kit wrote.
Also, if someone fails in this quiz, he wouldn't be allowed to judge... isn't that what some people want? So if you give wrong answers, you will have a relaxed day. I don't think that's a good approach.

However, why not make this an "unofficial" project?
I think there are more people who are interested in such a quiz or at least in a collection of good regulation questions.

Btw, there is a quiz made by two Indian guys, one of them might be reading here, so maybe you can get in contact. It was posted on the delegate list and it was quite nice. There were some challenging questions (least required moves for Square-1), so this was not for beginners only.

**Comment by Laura-O** [comment]
Closing this for now as this is not a practical idea.
