### ISSUE TITLE
Z4: qualification times -> qualification results

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#325]
[Regulation Z4](https://www.worldcubeassociation.org/regulations/#Z4) currently allows to limit the number of competitors per event based upon times and rankings:

> The organisation team may limit the number of competitors per event, on either a "first come first serve" basis or based upon qualification times or rankings in the WCA world rankings of a previously announced calendar date.

In order to make this applicable to FMC and MultiBLD, _times_ should be changed to _results_.

**Comment by viroulep** [comment]
Closed via #327
