### ISSUE TITLE
Spelling inconsistency in 3d1b)

### ISSUE THREAD

**Issue by Randomno** [thewca/wca-regulations#328]
Hi, this is just a minor spelling inconsistency unless I'm missing something.

> 3d1b) Competitors that cannot distinguish between the necessary number of **colors** may use coloured parts with patterns, if it has been explicitly approved according to Regulation 2s. Patterns may come from stickers or be drawn.

This is the only use of the US spelling in the regulations.

**Comment by Laura-O** [comment]
Hi,
we have already taken care of this and it will be fixed with the next regulation change.
But thanks for reporting this!

**Comment by KitClement** [comment]
This is what happens when you let an American lead the WRC. :P

**Comment by Randomno** [comment]
Thanks. I didn't find anything when I searched for the regulation.
