### ISSUE TITLE
Logos/markings/transparent overlay logo stickers

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#33]
See [delegate discussion, Aug. 13, 2013](https://groups.google.com/forum/#!searchin/wca-delegates/logos/wca-delegates/0NZPgoQgp9c/FlJjf11bE7sJ), and [Apr. 29](https://groups.google.com/forum/#!searchin/wca-delegates/logos/wca-delegates/czQpI0GfjII/VKhqBWLj_T0J), and [Oct. 20, 2012](https://groups.google.com/forum/#!searchin/wca-delegates/logos/wca-delegates/vtEhNO3YedI/7DPndMqoYf8J) and issue #51.

---

[Email to delegate list, December 08, 2013](https://groups.google.com/forum/#!topic/wca-delegates/kB09C6eObFo)

**Comment by iVinshe** [comment]
I would be okay with this.

**Comment by sarahstrong314** [comment]
Another thing to consider: make an exception for Square-1s to have at most 2 logos on the equatorial pieces on R and L faces.

See: http://www.speedsolving.com/forum/showthread.php?44849

**Comment by lgarron** [comment]
I would prefer not to allow two logos, ever. There is no intrinsic need for it, and competitors can easily resticker any of the official puzzles (or Calvin can adapt and figure out how to make things with one logo... I seem to recall Cube4You shipped with optional brand logos).

I think it's actually _reasonable_ to disallow logos of any kind, because it's simple and fair. 
I don't see a reason to disallow them, though (and I like my "Lucas's Cube" stickers :-P ).

**Comment by lgarron** [comment]
Here's a proposed change: https://github.com/cubing/wca-documents/compare/logos

Basically: be as strict as possible about logos to prevent advantages, while still allowing the most popular uses.

Stefan will try to poke holes in the fact that non-symmetrical logos can tell you how much a center has been rotated (parity), but I think 3l1+) in the proposal is sufficient.

**Comment by KitClement** [comment]
Based on community input, I would advise these changes to the current proposal.
1. Keep the change for 2x2x2 logos.  Logos shouldn't appear on a piece that has more than one sticker, as it makes information available without being able to see that piece.  In reality, this is covered by the current regulations.  There was pushback from this, but I didn't see any valid reasons, other than one puzzle that cannot be made legal under new regulations.
2. Continue to allow logos for 4x4x4/6x6x6.  The possible gains would be minimal, and anyone that could learn a method to track parity in a fast manner would likely be able to do this without a logo.  I would say that in this situation, allowing competitors to use logos to identify their own puzzles trumps this concern.
3. Custom logos should be up to the discretion of the WCA delegate.

As for what to do about overlays/engravings, this is unclear to me.  My proposal would be this: no logos for BLD, no exceptions; allow logos for speed events.  This is incredibly easy for delegates to track, as they can simply return any puzzle with a logo to the competitor, and not have to worry about keeping track of which ones can be identified by feel.  Also, competitors who have custom overlay logos won't have to feel the need to remove them from all of their speed puzzles.  BLD competitors won't be able to easily identify their BLD puzzles, but it's likely that most who compete in BLD will be able to use separate cubes (or already use a separate cube) for this event, and just make sure they don't use a logo.  Not a perfect resolution, but I think it does a good job of keeping the regulations simple (no need to make regs for engravings/overlays/any feelable sticker), makes it easy for the delegates to regulate, and keeps the majority of competitors happy and able to mostly use their custom logos.

Any thoughts?

**Comment by lgarron** [comment]
Interesting. Issues:
- Although I don't inherently mind stricter rules for BLD, this would not allow me to use any of my usual speedcubes for BLD... unless make them all unmarked. If we're going to have stricter rules for BLD, I think it should be aimed at eliminating an advantage by feel.
- Not being able to use your existing cube for BLD also puts a slight barrier against trying it in the first place ("I don't have a cube I can use!").
- Multi BLD cubers would have to maintain many logo-less cubes, and won't be able to borrow as many cubes from others. (For example, I and some others lent Chester some of cubes for multi BLD this summer. This would be more complicated.)
- Visual logos are arguably less useful during BLD, because they don't move, and can't give you additional information while solving.

I'd like it to be the case that most cubes that competitors will use for speed are usable for BLD (and vice-versa). Requiring adaptations for BLD makes me uncomfortable.

**Comment by lgarron** [comment]
Can we get data on how many competitors use puzzles with engravings/tiles?

As far as I understand, it's almost exclusively Megamixes now, and maybe a few 4x4x4's. If so, I think adding an exception for Megaminx is _quite reasonable_, and not very complicated.

**Comment by SAuroux** [comment]
How is adding an exception for Megaminx more reasonable than adding an
addition for Blindfolded events?

I really think that we should care about simplicity of our rules only up to
an reaonable amount. It is still very simple to say that puzzles with
markings/overlay stickers/engravings/etc. are only disallowed for BLD.

I strongly disagree with allowing no logos at all for BLD.

2013/12/12 Lucas Garron notifications@github.com

**Comment by KitClement** [comment]
I'm not sure how to make a proposed change in GitHub, so I'm just commenting them here.  My regulation writing is not too strong, so feel free to be nit-picky with my wording, or if I'm missing any considerations.

3l) A cube puzzle may have a logo, but it must have at most one logo. For cube puzzles, this logo must be on one of the most central pieces with only one color.
3l1) Colourless engravings (max. 1 per face) are not considered logos.
3m) Any logos or engravings that allow the competitor to identify a certain piece by feel are not allowed for BLD events.

3l+) [CLARIFICATION] A logo is only allowed on the following puzzles: 3x3x3/5x5x5/7x7x7 (on the unique central piece of one side), 4x4x4/6x6x6 (on one of the four centers of one side), Megaminx/Skewb (on the center of one side), and Square-1 (on one of the stickers on the middle slice).

**Comment by Claster** [comment]
> 4x4x4/6x6x6 (on one of the four centers of one side)

It seems to me that 6x6x6 has more than four centers on one side :-P
Ok, you probably mean, on one of the four INNER centers of one side. But why not to have a logo on the outer center? And same question to the 5x5x5 and 7x7x7.

**Comment by lgarron** [comment]
How is an exception for Megaminx more reasonable than an exception for
3x3x3?
An exception for 3x3x3 would will result in _different rules for the same
puzzle_.

This means that you can't tell someone whether a cube is legal without also
knowing what even they're asking about.

It also might mean that you have to maintain two competition-legal sets of
the same puzzle. If we decided not to allow logos for BLD, I would still
prefer them to identify mot of my cubes. I would have play a game and
figure out which cubes I want to leave unlogoed for use for BLD (or
resticker at the competition). I certainly prefer the option of taking
whichever of my speedcubes is currently the best, and using it for BLD.

If the Regulations are the same for ay given puzzle, this all goes away.

»Lucas Garron
