### ISSUE TITLE
8a4+ refers to an unexisting regulation

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-regulations#332]
8a4+ refers to qualification rounds that were removed with #49, I think we should simply remove this guideline, right ?

(I'm also going to assume we should follow the same policy as the Regulations and not rename the 8a4++ guideline)

**Comment by lgarron** [comment]
Yes, that sounds good to me. (Remove 8a4+ and don't renumber 8a4++.)

**Comment by Claster** [comment]
Shouldn't it refer to Z4 instead ("limit the number of competitors per event")?

**Comment by viroulep** [comment]
The Guideline was originally designed to apply to qualification rounds, where you could explicitly increase the number of competitors qualified, so it feels like it's another context.

I get your point though, that when using Z4 one should announce any change in advance.
I would assume that the board has to approve the limit too, to avoid any dumb low limit, and thus that any change afterwards should be validated by them too. So should we rely on them to ensure it's done in advance, or clarify this ?

My opinion is that as it's a board exception and that it is fine "as is".
