### ISSUE TITLE
Extra attempts when misalignment is between two valid states

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#336]
Sometimes delegates give extra attempts in cases where a puzzle has a misalignment in between of two states (e.g. 60º turn in skewb and pyraminx). However [A3c2](https://www.worldcubeassociation.org/regulations/#A3c2) covers these cases, implying that a competitor can round this to any adjacent state. On the other hand, this can in theory contradict [4b3](https://www.worldcubeassociation.org/regulations/#4b3) family: if a competitor receives, say, a skewb with misalignment that had 7 moves optimal solution, he can round it in the wrong way and to obtain 6 moves optimal solution.

So, either A3c2 should be rephrased (e.g. "don't do this if a misalignment is exactly between two valid states"), or delegates should stop giving extra attempts in these cases.

What do you think?

**Comment by Laura-O** [comment]
To ensure we are talking about the same thing: this is about the start of the inspection phase, after the judge has lifted the cover and the puzzle has a misalignment right?

Stopping to grant extra attempts would not be fair. It is not the job of the competitor to analyse misalignments and correct them in the inspection phase. Of course, it is not a big deal to correct misalignments of 10 degrees or less and you can do this blindly, but deciding about a 55 degree misalignment in Skewb definitely cuts the inspection time. I have always asked for an extra attempt in these situations without even touching the puzzle.

I think it's difficult to have a definite approach here: on the one hand we don't want to encourage someone to correct a misalignment he isn't really sure about. On the other hand we don't want to encourage people to ask for extra attempts for every small misalignment.

**Comment by Claster** [comment]
Yes, I'm talking about this thing.
