### ISSUE TITLE
Unify start/begin and stop/end

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#339]
Right now the [style guide](https://github.com/cubing/worldcubeassociation.org/blob/master/regulations/style-guide.md) states:

> - "Start" instead of "begin".
> - ...
> - "Start" and "stop" (verbs).
> - "Beginning" and "end" (nouns).

The Regulations follow this, although the Guidelines use "begin" instead of "start". (There are also a few occurrences of "finish", but these seem appropriate.)
It would be nice to simplify this and use fewer words. However:
- DNS stands for "Did Not **Start**", so we should continue to say that the competitor "starts the attempt".
- There is no natural noun form of "stop" – "the stop of the solve/attempt/round" is wrong.

Proposal: Start by changing "begin"/"beginning" to "start".

**Comment by Laura-O** [comment]
Yes, that makes sense.

I just realised that there are other inconsistencies in the Guidelines:
- "Permitted" instead of "allowed" or "accepted".
- "Grant" an extra attempt instead of "give" or "award".
- "Scramble sequence" instead of "scramble".
