### ISSUE TITLE
Extends A3d1 to "anywhere but the mat"

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-regulations#343]
Right now A3d1 states : 
`A3d1) The puzzle must not rest on the timer. Penalty: time penalty (+2 seconds).`

Following this thread : https://groups.google.com/forum/#!topic/wca-delegates/K0CBpf-wdTY, I believe we should extend this to handle the case where the competitor put the puzzle anywhere but on the mat (like in this video : https://youtu.be/7E6ZfCoYplA?t=163).

What do you think ?

**Comment by SAuroux** [comment]
But this is handled already by:

A3d) At the end of the inspection, the competitor places the puzzle on the mat, in any orientation.

What could be clarified however is, that the penalty also applies if the puzzle is put anywhere else.

**Comment by viroulep** [comment]
I must have expressed myself poorly, your suggestion is exactly what I intended to suggest : literally changing "on the timer" to "anywhere but on the mat".

**Comment by Claster** [comment]
Do we want only to give +2 to such solves, or disqualify them completely?

**Comment by pedrosino** [comment]
I believe DNFing is better.

**Comment by Laura-O** [comment]
For Clock a penalty is defined in F3). Although the main intention of this regulation is probably to penalize changing the pin positions, it also mentions that the puzzle has to be placed on the mat. Therefore, in Clock this would be a DNF:
_F3) At the end of the inspection period, the competitor places the puzzle onto the mat in a standing position. The competitor must not change the positions of any pins from their scrambled positions before the beginning of the solve. Penalty: disqualification of the attempt (DNF)._

**Comment by SAuroux** [comment]
Why is that? +2 is absolutely consistent with A3d1.

2016-03-08 12:27 GMT+01:00 Pedro Santos notifications@github.com:

**Comment by pedrosino** [comment]
@Laura-O I didn't realise that part. It is weird that only clock has this "almost-well-defined" DNF and the other puzzles only have A3d1.
( @SAuroux maybe I subconciously knew this and wanted everything to be DNF)

**Comment by SAuroux** [comment]
Haha, Laura is techniocally correct, even though this certainly isn't the
intention of F3. The empesis here is on the standing position, not on the
mat.

2016-03-08 13:22 GMT+01:00 Pedro Santos notifications@github.com:

**Comment by pedrosino** [comment]
Indeed, I think the "correct" interpretation here is about the position and not moving any pins, but since it's all in the same sentence, the DNF applies if you didn't move any pins, set the clock in a standing position but not on the mat.
I guess this closes the case on the indian competition...

**Comment by Claster** [comment]
+2 will lead to a simpler rule: you won't need to memorize different levels, like, if a puzzle is here, it is DNF, if a puzzle is there, it is +2.
Though I would prefer DNF as a more stricter rule :-P

**Comment by Laura-O** [comment]
Fixed in #347
