### ISSUE TITLE
Conflict between A1a and A1a1 (attempt x solve)

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#349]
> A1) Speed Solving attempts must abide by the following procedures.
>    A1a) The organisation team must enforce time limits for attempts and/or rounds.
>        A1a1) The default time limit per solve is 10 minutes, though the organisation team may announce a higher or lower time limit.
>        A1a2) Cumulative time limits may be enforced (e.g. 3 attempts with a cumulative time limit of 20 minutes). The time elapsed in a DNF result counts towards the cumulative time limit.

A1a says the limits should be enforced on "attempts and/or rounds", but A1a1 says the default limit is "per solve".
I think the latter is correct, since the limit is actually on the "solve" portion of the attempt, and not the whole attempt, which includes inspection, checking the puzzle and recording the result.

This also relates to the proposed change here: https://github.com/cubing/wca-regulations/commit/c7ab1122ec9f848a8e1c8741bc6d344a0cc8be32
It should be changed to "solve" instead of "result"

**Comment by Laura-O** [comment]
First of all: Strong disagree to changing "result" to "solve". A "solve" is a successful attempt, i.e. with such a regulation everyone could DNF as many attempts as he likes until he finally has 3 successful attempts.

As Lucas has written in the discussion (#293), I would suggest to change every mention under A1a to "attempt".

**Comment by pedrosino** [comment]
My point is that attempt = (inspection + solve + checking + writing + signing), and we don't want to put a global limit on all of that, but only on the _solving part_ of the attempt.

I don't agree that "solve" = "successful attempt". A4, A5 and A6 describe the "solve". A6 states that we end the "solve" by releasing the puzzle and stopping the timer. After that the puzzle will be checked and the result will be assessed. 9f defines this well, I believe:

> 9f4) The result of an attempt is recorded as DNF (Did Not Finish) if the attempt is disqualified or unsolved/unfinished.

I see "result" as what is recorded into the database (the "official result"), and you can't sum a DNF with a time to check if they meet the time limit. Anyway, I think the DNF is covered by 

> The time elapsed in a DNF result counts towards the cumulative time limit.

Maybe we should have a clarification in the guidelines in the sense of

> "solve" is used to refer to the solving part of the attempt

As for A1 and childs, maybe rephrasing it like:

```
A1) Speed Solving attempts must abide by the following procedures.
    A1a) The organisation team must enforce time limits for solves and/or rounds.
        A1a1) The default time limit per solve is 10 minutes, though the organisation team may announce a higher or lower time limit.
        A1a2) Cumulative time limits may be enforced (e.g. a cumulative time limit of 20 minutes for 3 solves). The time elapsed in a DNF result counts towards the cumulative time limit.
```

**Comment by Laura-O** [comment]
Well, if the cube is not solved when the competitor is stopping the timer, he receives a DNF (= did not finished). Therefore, the solve is not complete and therefore I think a DNF is not a solve.

However, I think your reasoning regarding the changes in A1 makes sense. I am still a little bit unsure about this:

> A1a2) Cumulative time limits may be enforced (e.g. a cumulative time limit of 20 minutes for 3 solves). The time elapsed in a DNF result counts towards the cumulative time limit.

Is there any regulation that prevents the interpretation that a cumulative time limit allows to do solves until either you have 3 successful solves or you exceed the time limit?

Maybe we can avoid that by not being too specific in the example and say: "a cumulative time limit of 20 minutes for all attempts of a round"? That matches the description of the round formats in 9f) ("For "Best of X" rounds, each competitor is allotted X attempts.").

**Comment by pedrosino** [comment]
Well, the problem seems to be that we call "solve" the process of attempting to solve the puzzle, i.e., the time when the competitor is making moves. It would be like the "process of solving".
A DNF is assigned after the "solve" is over, and it's opposed to a "solved" result.

As I said, I think the second phrase (The time elapsed in a DNF...) is very clear, and doesn't allow the interpretation that you can keep trying until you have N "solved solves".
But I like your idea of not saying "3 solves" and saying "all attempts". 
We'd have to add a guideline saying that "Eventhough an attempt includes the solving portion and the procedures before and after that, the time limits only apply to the solving portion of the attempt".

**Comment by Ranzha** [comment]
Perhaps additional vocabulary is required in order to allow "solve" to keep its meaning.
Maybe "Starting the solve" -> "Starting the execution phase"?
Then a solve is a successful result recorded after the execution phase at the end of an attempt.

**Comment by viroulep** [comment]
According to the style guide there is a "general" definition of a solve : 

> Solve: Generally, the part of the attempt when the timer is running.

We should probably bring in more definitions from there, like #104 which was supposed to clarify to attempt/solve distinction. Maybe we could just make a section/appendix with definitions for commonly used keywords ?.

**Comment by lgarron** [comment]
> Maybe we could just make a section/appendix with definitions for commonly used keywords ?.

I do not think we should include a new section just for this; the structure of the Regulations + Guidelines is already confusing enough to some people.

> Then a solve is a successful result recorded after the execution phase at the end of an attempt.

I don't think this is appropriate. If you start a solve, it should not later become possible for you not to have had a solve.

**Comment by pedrosino** [comment]
Lucas words complement mine. A solve is not the result, but the process. So it makes sense to apply limits on solves, and not on the whole attempt, because there are things in there that are not in control of the competitor (like the judge drops the pen, writes something wrong, signs on the wrong place, etc)

**Comment by Laura-O** [comment]
I prefer to keep this as simple as possible and avoid adding new definitions. So I still think changing the example to "a cumulative time limit of 20 minutes for all attempts of a round" is a good way to clarify a cumulative time limit. I will create a PR for that.
I also think we should simply keep A1a1) as it is, because it actually defines that the default time limit is for a _solve_ and not any other possible time frame.

**Comment by viroulep** [comment]
I would actually be in favor of changing all "solve"/"result" occurrences to "attempt" in A1a scope. 

Especially changing "solve" to "attempt" in A1a5 makes it clear that the part of the attempt counting towards the time limit is the final result, and that it excludes inspection/checking/etc : 

> - A1a5) An attempt is considered to meet the time limit if and only if the final result, after any time penalties are applied, is less than the time limit. Exception: Multiple Blindfolded Solving (see [Regulation H1b1](regulations:regulation:H1b1)).

**Comment by Laura-O** [comment]
I'm fine with these changes with one exception. By simply replacing "solve" with "attempt" A1a4 would start like this:

> A1a4) The competitor must end each attempt within the time limit. [...]

I don't think that makes sense. The attempt finishes when judge and competitor have signed the score sheet (A7c), so the competitor isn't even able to end an attempt without the "help" of the judge.
How could we fix this?

**Comment by pedrosino** [comment]
Proposal:
https://www.diffchecker.com/bxyrf2mp

It keeps A1a1 as Laura mentioned.

@viroulep changing everything to attempt doesn't work because, as has been discussed, the attempt is composed of several phases, and not all of them are in control of the competitor. The only part that makes sense to have a limit on is the "solve" part, as defined by A4 to A6.

**Comment by viroulep** [comment]
Did you see I emphasized that the reworded A1a5 would clearly states : an attempt would meet the time limit if and only if its final result is less than the time limit, therefore cutting off the other phases ?

> The only part that makes sense to have a limit on is the "solve" part

I do agree with that, and I don't think the suggestion using attempts contradict that at all (once A1a4 correctly worded). An attempt has a time limit (which may depends on previous attempts), and the final result of this attempt must meet it.

The time limit is an attribute of an attempt, just like the final result is.
(What is going in my mind is that I see an attempt as an encapsulation for multiple phases and data)

@Laura-O, I overlooked the beginning of A1a4.
I have two suggestions for the beginning, the first one emphasizing again which part count towards the time limit :

> The competitor must end each solve within the time limit for the attempt.

The second one getting rid of "solve" :

> The competitor must meet the time limit for each attempt.

**Comment by pedrosino** [comment]
The main problem I have with using "attempt" is that when we say "the time limit for 4x4 is 3 minutes", we mean that your "solve" part can't take longer than 3 minutes.
Your attempt, which is made of inspection, solving, checking, recording and signing is not limited to 3 minutes, and should not be. There could be a misalignment which is hard to tell, and you may have to call the delegate to look, and he may be busy, etc, which takes like 2 minutes after your solve is done.

I don't think that "The competitor must end each **solve** within the time limit **for the attempt**" makes much sense. If the limit is for X, why do I need to end Y within that limit? If that's the case, then the limit is for Y, and not X.

Sorry, maybe I'm a bit too annoying...

**Comment by Laura-O** [comment]
I completely agree with @viroulep.
In the round formats we use a competitor is allotted a number of X attempts. That is like a unit with each of these attempts following the same procedures. A solve is part of an attempt and an attempt consists of a maximum of one solve. Therefore, the time limit is also defined for an attempt. That's not a contradiction.

**Comment by pedrosino** [comment]
Well, I won't pursue this any longer :)

But just for the record, they way I see it, an attempt has a limit which is
15 seconds (inspection) + 
2 minutes (solve) + 
??? (final procedures)

That limit will never be defined correctly, and that is my main concern.

But I guess we can make clear what is the correct interpretation of the regulations when someone asks and/or at the announcement.

**Comment by pedrosino** [comment]
Sorry to revive the year-old thread. I'm having a "PR-making day", so I thought I'd make another try at this.

As discussed before, we have 3 concepts here: attempt, solve and result.

"Attempt" is (inspection + solve + checking + writing + signing) (See A2, A3 and A7c) 
"Solve" is the part in which the timer is running (except of course for FM) (See A4, A5 and A6)
"Result" is the final outcome of the attempt, which can be some time, number of moves or points, or a DNF or DNS.

The portion we want to limit is the solve/result, not the whole attempt. This is tricky because if I have a solve of 2:59 and a +2 penalty, I won't meet a 3 minutes limit. I think the current wording of A1a4 and A1a5 is fine for this.
We could change A1 and A1a2 to be consistent. I'll send a PR.
