### ISSUE TITLE
Introduce a `draft` branch.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#356]
In the past, I used `fixes` for... well, uncontroversial fixes. As we start handling more controversial issues, the name becomes less appropriate. 

WRC folks: What do you think of switching to development on a branch named `draft` after the next release?

Something like `dev` would also work, but I think `draft` makes more sense. We're working on text, not code.

**Comment by viroulep** [comment]
I totally don't mind switching names ;)

I'd also like to have your opinion on setting the 'draft'/'fixes' branch as the default one.
Right now we basically have to close manually each issue we "fix" because the commit has to land into the default branch to automatically close the related issue.

**Comment by Laura-O** [comment]
Yes, `draft` and making it the default branch sound good.
This also make it easier to find the recent changes. Just last weekend someone asked me if we do not use the repository anymore because he couldn't find any new commits here...

(Side note: the structure of the branches is also something we could add to a Readme file, see #317)

**Comment by lgarron** [comment]
Re:

> I'd also like to have your opinion on setting the 'draft'/'fixes' branch as the default one.

and

> (Side note: the structure of the branches is also something we could add to a Readme file, see #317)

I think we should combine these:
- Make `draft` the default branch.
- At the top of the `README`, put a clear disclaimer that competitions must always use the official English version at https://www.worldcubeassociation.org/regulations/ (and that this should be in sync with the [`official`](https://github.com/cubing/wca-regulations/tree/official) branch).

**Comment by lgarron** [comment]
I've gone ahead and done this. Let's keep `draft` and `fixes` in sync until next week, and then switch to `draft` entirely.

**Comment by lgarron** [comment]
> I've gone ahead and done this. Let's keep draft and fixes in sync until next week, and then switch to draft entirely.

Laura, would you feel comfortable removing the `fixes` branch and doing as follows?
- Updating https://www.worldcubeassociation.org/posts/wca-regulations-april-2016 to reference https://github.com/cubing/wca-regulations/compare/216ded3...draft#files_bucket
- Emailing https://github.com/cubing/wca-regulations/compare/216ded3...draft#files_bucket to the Delegates list.

**Comment by lgarron** [comment]
> 216ded3...draft#files_bucket

Actually, this can (should?) reference the tag for the previous official version instead of the hash:

https://github.com/cubing/wca-regulations/compare/official-2015-07-01...draft#files_bucket

**Comment by Laura-O** [comment]
Forgot to answer here: the link in the announcement has already been changed. I will remove the fixes branch next week.
