### ISSUE TITLE
Competitor resets the timer in a round with cumulative limit

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#358]
Inspired by Berkeley Spring 2016 delegate report.

Suppose there is a cumulative limit in an event. A competitor makes a DNF and then (accidentally or intentionally) resets the timer before the judge writes anything in the scorecard. How does this count towards the cumulative limit?

A simple solution would be to disqualify the competitor from further attempts in this round, as this is his fault.

Another related question: what if the judge forgets to write a time for a DNF solve?

**Comment by SAuroux** [comment]
Well, there is one more scenario that happened to me (as a competitor) at
BOND Open 2016: I got a DNF solve in 3x3x3 BLD and had a timer reset.

2016-04-18 14:02 GMT+02:00 Oleg Gritsenko notifications@github.com:

**Comment by Laura-O** [comment]
Yes, I can actually remember several similar situations.
At German Open 2016 a competitor reset the timer before the judge could write down the time, both said the time was 3:xy, so we wrote down 3:59.
There was also someone at German Nationals last year who decided that it's not necessary to write down the time for fast competitors, so the time was actually missing. As this was right after the start of the event and barely 2-3 minutes had passed, we wrote 3 minutes on the sheet (if I remember that correctly).

I think it's nearly impossible to have a strict and clear regulation for this, as there are many circumstances that could lead to such a situatIon.

**Comment by pedrosino** [comment]
I think the judge would know at least the minutes of the solve, so writing X:59 would be "fair" as a punishment for the competitor, in my view. This is to the original question, though.
Judge forgetting to write it maybe could be done the other way. Judge says it was 3:xy, it counts as 3 minutes for the cumulative limit.

**Comment by lgarron** [comment]
Should this be closed like #462?

Or should we add a Guideline about estimating the time?

**Comment by pedrosino** [comment]
I think it would be good to have something in the Guidelines. If not, competitor may "accidentally" reset the timer to get more time for the next attempts.

**Comment by lgarron** [comment]
Done in 52ce26093bd769dcee90ec925cef0d7a002dbdfa (#669).
