### ISSUE TITLE
Obsolete link to contact WRC

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#361]
Regulations contain a link to WRC contact (https://www.worldcubeassociation.org/contact/wrc). This link is obsolete, and he who seeks wisdom of WRC will find it at wrc@worldcubeassociation.org.

Also, same thing for all translations.

**Comment by jfly** [comment]
Any update here? This is kind of embarassing, and should be an easy fix. (Thanks to Roman Strakhov for notifying me of this)

**Comment by viroulep** [comment]
The [diff](https://github.com/cubing/wca-regulations/compare/official...draft) between `official` and `draft` currently contains nothing but non-Regulations stuff + one typo, I guess we could consider fixing this too and merge `draft` into `official` without a release?

**Comment by lgarron** [comment]
> without a release

Well, I don't think we should pretend it's not a "release". There should be some explicit documentation of the fact that the Regulations page changed.

However, we can re-introduce the idea of "Latest textual revision" (see e.g. [here](https://www.worldcubeassociation.org/regulations/history/files/regulations2010.html)), and add a smaller sort of note at https://www.worldcubeassociation.org/regulations/history/
