### ISSUE TITLE
Change 1c4 (Board -> Results Team)

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#365]
1c) The WCA Delegate may delegate responsibilities to other members of the organisation team, but is ultimately accountable for how these responsibilities are carried out. The WCA Delegate for a competition is responsible for: 
1c4) Sending corrections to the competition results to the WCA Board.

Corrections are sent to the Results Team instead (it includes Board members).

**Comment by Claster** [comment]
Fixed together with #417.
