### ISSUE TITLE
A6a and A6a1 have repeated information

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#367]
A6a) The competitor stops the solve by releasing the puzzle and then stopping the timer. **If a stopwatch is in use, the judge stops the stopwatch as soon as the competitor does this.**

A6a1) When using a stopwatch as the only timer, the competitor ends the solve by releasing the puzzle and notifying the judge that they have stopped the solve. **The judge stops the stopwatch as soon as the competitor does this.**

I think A6a1 is enough.

**Comment by AlbertoPdRF** [comment]
The text is repeated, the idea is the same, but both situations are different. If we remove the text from A6a), the case were both a timer and a stopwatch are in use is uncovered by the Regulations. I'm closing this one, but feel free to re-open it if you think that a change is really necessary here.
