### ISSUE TITLE
Guidelines REMINDER label missing a word

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#368]
(Sorry for being annoying, I'm translating the regulations and guidelines and finding these small things)

```
REMINDER Information that may be addressed other Regulations/Guideline, but whose relevance is worth reiterating.
```

I think there is a "in" or "at" missing: "...may be adressed _**in**_ other Regulations..."

**Comment by viroulep** [comment]
Don't worry, thanks for the whole review :p 
Probably "by" in this case?
