### ISSUE TITLE
Guideline 4b4+ (exceeds?)

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#369]
4b4+) CLARIFICATION All attempts that have been started within the time frame follow the standard solving procedure (i.e. they are not stopped when the time frame of the relevant scramble sequence **exceeds**).

Maybe it should be "expires" instead?

**Comment by Laura-O** [comment]
Why do you think that it should be "expires" instead?

**Comment by pedrosino** [comment]
Because exceeds requires an object (exceeds what?). I think the intention here is "if the time frame is over when an attempt is still on course, it continues normally, so saying that "the time frame ... expires" makes more sense.

**Comment by Laura-O** [comment]
[dictionary.com](http://www.dictionary.com/browse/exceed) lists "exceed" without an object.

I am not opposed to change this, but I'm not completely convinced yet. :-)

**Comment by pedrosino** [comment]
They don't give any examples :P

I don't feel too strong about this. Just had a little trouble understanding at first.
(http://dictionary.cambridge.org/pt/dicionario/ingles/exceed Has no examples without object, though)

**Comment by AlbertoPdRF** [comment]
Any native speaker has a strong opinion here? @jfly? :P

**Comment by jfly** [comment]
I definitely agree that a time frame doesn't exceed anything, but it can expire. I like @pedrosino's original suggestion.

As for the dictionary.com definition, it's talking about **object**, not **subject**. In the guideline above, the subject of this verb is still "time frame", and the time frame is not doing any "surpassing of others; excelling or being superior".
