### ISSUE TITLE
Remove Article 6 from Guidelines?

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#371]
I know this is mentioned in the beginning, but having guidelines about a regulation that doesn't exist anymore doesn't make much sense, and could lead to confusion.

**Comment by Laura-O** [comment]
Well, the guidelines supplement the regulations as a whole and not individual regulations, so I think it's fine to keep these Guidelines.

Furthermore, I think that especially 6c+) and 6d+) are still relevant, so I do not see a reason why they should be removed.

**Comment by lgarron** [comment]
I agree fully with Laura's stance and reasons.
