### ISSUE TITLE
Clarify whether a regular and cumulative limits can exist together

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#374]
Relevant Regulations:

> A1a) The organisation team must enforce time limits for attempts and/or rounds.
> A1a2) Cumulative time limits may be enforced (e.g. 3 results with a cumulative time limit of 20 minutes). The time elapsed in a DNF result counts towards the cumulative time limit.

So it is not clear whether cumilative limits exist instead of regular ones or together with them. In practice I didn't see organizers set them both (though one could say that if an organizer sets a cumulative limit and doesn't set a regular one, the regular limit is 10 minutes by default).

If it is allowed to use them together, as a side effect it is allowed to use cumulative limit for multi-bld.

Inspired by French championship 2016 report.

**Comment by viroulep** [comment]
I see one borderline case if you can't specify/don't have a time limit: assuming you want a 20 minutes cumulative time limit on 7x7, one could use the 20 minutes for their first solve, when you may want each result to be also under 10 minutes.
(It's a made up example that is unlikely to happen, I just wanted to point it out)

What about simply explicitly prevent the use of cumulative time limit for multi?

Also, is there an issue with making a cumulative time limit and a time limit an exclusive or?
(beside having to deal with solves over 10 minutes)

**Comment by Laura-O** [comment]
I do not think having a time limit as well as a cumulative time limit for a round is a problem. However, the cases where this actually makes sense seem to be rare or rather non-existent.
The main purpose of time limits is to avoid that slow competitors block the solving stations for too long. With cumulative time limits, those slow competitors get a chance to complete at least one solve even though they are slow. So the combination of both intentions seems a bit odd.

In general, cumulative time limits are a type of time limit, so one could argue that it is only possible to set one time limit. In this case we might want to clarify this in [A1a2](https://www.worldcubeassociation.org/regulations/#A1a2) - maybe just something like this: _"Time limits may be enforced as cumulative time limits..."_.

**Comment by lgarron** [comment]
It is absolutely useful to have both.

In California, we often have a combined limit of, say, 15min for three BLD
attempts.
But we still use Stackmats, so each attempt also has a limit of 10min.

**Comment by Claster** [comment]
Cumulative limit for blindfold, e.g., 15 mins is used in other countries as well, but then (in these competitions I've visited) it means that regular limit is 15 mins too.

> But we.still.use Stackmats, so each attempt.also.has a limit of 10min.

You can use stopwatches too :-P
E.g., run a stopwatch when a competitor reaches 9:00.00.

**Comment by Laura-O** [comment]
Well, we kind of switched to combined limits in BLD here at last year's Nationals and many organizers here have adopted this format, usually with cumulative limits between 12-15 minutes. I cannot remember there ever was a competitor expecting a result >10 minutes, but I think it would have been fine if someone asked his judge to use a stopwatch.

I found several examples for BLD results >10 minutes when only a cumulative time limit (and no regular time limit) was announced on the website of the competition: [1](https://www.worldcubeassociation.org/competitions/SoCalSupercomp2015/results/all#e333bf), [2](https://www.worldcubeassociation.org/competitions/PugetSoundSpring2016/results/all#e333bf), [3](https://www.worldcubeassociation.org/competitions/MinnesotaWinter2016/results/all#e333bf).
Furthermore, if announcing a combined limit and not announcing a regular time limit means that there is a default time limit of 10 minutes, we would have to DNF a lot of BigBLD results... ;-)

So I think the common interpretation is that cumulative time limits replace regular time limits and also the default time limit of 10 minutes. That doesn't mean that there is no option to use both, but that should be clarified in the regulations.

**Comment by lgarron** [comment]
> So I think the common interpretation is that combined time limits replace regular time limits and also the default time limit of 10 minutes.

As I stated above, this is not the common interpretation in the US.

**Comment by Laura-O** [comment]
> As I stated above, this is not the common interpretation in the US.

So the results I mentioned above were all done at competitions where a higher regular time limit was announced on-site? For all of them there was only a cumulative time limited announced on the competition website.

I'm not questioning your statement, I'm just wondering.

**Comment by lgarron** [comment]
As far as I understand, we assume that there is still an implicit time minute of 10 minutes for each individual attempt.

Then again, I can't recall an example where someone showed up an expected to go over 10 minutes, so we may not have had to think about it closely, and there may be conflicting opinions.

If there is a possibility that some competitors might go over 10 min, it certainly would be nice to be consistent and require every attempt to use a Stackmat as usual. But I don't feel strongly.

@jfly, @iVinshe, @shelchang, how do you interpret this at CA/US comps?

**Comment by jfly** [comment]
I have always interpreted this as @Laura-O said: a 15 minute cumulative time limit means someone who takes 13 minutes to do a BLD solve can get a chance at one if they really want it! I see no value in having a time limit if you have a cumulative time limit, other than giving some people more time at the stations than other people (which is not desirable, IMO).

**Comment by Jambrose777** [comment]
One question in this thread that hasn't been answered:
What about multi-blind?

Imposing a cumulative limit on this event completely goes against the spirit of the event. Instead of trying to be as successful as possible in as many Cubes as possible in 1 hour, It encourages worse results and allows competitors to attempt grind 20 minute solves.

One example being: https://www.worldcubeassociation.org/competitions/VisayasChampionship2017/results/all#e333mbf

**Comment by jfly** [comment]
Tangent related to @Jambrose777's comment. The [schedule says](https://www.worldcubeassociation.org/competitions/VisayasChampionship2017#1201-event-schedule-day-2): there was a 1 hour time limit for multi bld:

![image](https://user-images.githubusercontent.com/277474/30119818-d1d50d80-92db-11e7-9db8-5a9a91623acb.png)

But given @Jambrose777's comment above, and the fact that only 1 hour was scheduled for the event, this must have actually been a 1 hour **cumulative** time limit.

@Jambrose777, I don't get why the cumulative time limit for multibld at VisayasChampionship2017 would encourage people to grind 20 minute solves. It was a best of 2, so people had 30 minutes per solve, not 20. Furthermore, the winner of the event is still going to be the person with the most points, right?

**Comment by Jambrose777** [comment]
The 20 minutes was just an example of what can be done.

At VIsayas Championships, the delegate has confirmed that the 1 hour time limit was for both attempts.

I think that this is more of a fairness issue: they are allowing competitors who attempt a low amount of cubes to have more attempts than a competitor who attempts a high amount of cubes. This causes the competitors who are good at multi-blind to be limited on their number of attempts. 

This is the OPPOSITE of the intentions of a cumulative limit. 
> With cumulative time limits, those slow competitors get a chance to complete at least one solve even though they are slow.
