### ISSUE TITLE
Clarification of A1b1

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-regulations#375]
Right now A1b1 states:

> A1b1) For events with inspection, a Stackmat must be used in addition to the stopwatch. For events without inspection where the competitor is expected to exceed 10 minutes, use of the Stackmat is optional.

As pointed out by @cubizh, @Claster and Daniel, one scenario is not covered:

> events with inspection => Stackmat must be used
> events without inspection where the competitor is expected to exceed 10 minutes => optional
> events without inspection where the competitor is not expected to exceed 10 minutes => ???

Also, there is the edge case where the competitor is expected to maybe exceed 10 minutes, but has a chance to solve under 10 minutes. I don't think it's too much trouble to use a Stackmat just in case.

I propose to change A1b1 to:

> A1b1) A Stackmat must be used in addition to the stopwatch. For events without inspection where the competitor is expected to exceed 10 minutes, use of the Stackmat is optional.

And add a clarification about unsure expected results, where a Stackmat should be used in case the result happens to be under 10 minutes.
If it sounds impractical to organizers used to hold big blind, please let me know!

Also, we have H1e:

> H1e) Use of the Stackmat timer is optional for timekeeping.

The interaction with the "new" A1b1 would be weird in case the competitor is expected to solve their multiblind attempt under 10 minutes: Stackmat would be mandatory but stackmat timer optional?
It seems to go in the opposite direction of the previous discussion: https://github.com/cubing/wca-regulations/issues/273, where it was going towards making the mats optional for multiblind.

So we could either simply remove H1e to make the whole Stackmat mandatory for multiblind expected to last less than 10 minutes (and optional otherwise), or keep H1e and make the whole Stackmat optional for every multiblind attempt.
(Or something else?)

Related report and videos leading to this issue:
https://groups.google.com/forum/#!topic/wca-delegates/FTU06Vg4xJ4
https://www.youtube.com/watch?v=MSLVXQg_qs0
https://www.youtube.com/watch?v=tmWxSZtqOkw

**Comment by Claster** [comment]
Nit: your first sentence of A1b1 is unconditional and it supersedes the second one. I would say:

> A1b1) If the event has no inspection and the competitor is expected to exceed 10 minutes, use of the Stackmat is optional. Otherwise a Stackmat must be used in addition to the stopwatch. 

Also if events with inspection rarely have limits greater than 10 minutes, we can drop "the event has no inspection" part for simplicity.

Regarding whether it is practical to require stackmats for multi-blind and big blinds when a competitor is expected to be fast, I think sometimes these events are held in a side venue, and it may be some pain to move stackmats back and forth.

**Comment by viroulep** [comment]
Merged after I changed the default branch, closing this manually.
