### ISSUE TITLE
Moving the doc from the website to here

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-regulations#378]
I'm in the process of doing a big clean of the [`regulations`](https://github.com/cubing/worldcubeassociation.org/tree/master/regulations) directory of the website.
There is some information hidden over there in [`doc`](https://github.com/cubing/worldcubeassociation.org/tree/master/regulations/doc), should we start a small wiki with the information there?
(maybe even add the style-guide as a wiki page, link it in the readme, and remove it from the repo?)

**Comment by lgarron** [comment]
I would prefer to place the files in a folder in the wca-regulations repo, but wiki sounds okay if we find an easy way to back up the wiki regularly.

**Comment by Laura-O** [comment]
Well, in fact there is not much information hiding there. ;-)

Most of the content is not relevant anymore and obsolete (e.g. referring to Drupal, old mailing list, etc.), so I don't think we should keep it.
I would rather suggest that we delete them and write new guides from scratch. A wiki sounds like a good idea. I will get this done when I am back home from Euro.

@lgarron Can you enable the wiki for this repository? Obviously only the organization owners have the rights to do that.

**Comment by viroulep** [comment]
Yes, there is a few things that should be kept/wrote:
- What to do to add a new WRC member
- What to do when uploading a new Tnoodle (or maybe this belongs in the website wiki)
- What to do when releasing a new version of the Regulations or uploading a new translation (basically edit the static pages of the website, adding a new history version).

I activated the wiki with restricted write access.

Also I found [that](https://gist.github.com/rodw/3073987). I didn't try it yet, but from reading it wikis appear to be stored in "hidden" git repositories, which makes them easy to backup.

**Comment by lgarron** [comment]
> @lgarron Can you enable the wiki for this repository?

Already seems to be the case.

**Comment by lgarron** [comment]
> Already seems to be the case.

Oh, I just saw @viroulep enabled it, and mentioned so above.

**Comment by lgarron** [comment]
`git clone https://github.com/cubing/wca-regulations.org.wiki.git`

Perhaps we should back up all WCA project repo wikis with our cron job.
