### ISSUE TITLE
Staff competitions

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#379]
It is becoming more commonplace to hold staff competitions on the days before events are stated to begin.  While it makes perfect sense for major competitions to hold these, local competitions are often doing this when it may not seem the most appropriate.  Also, It might be sensible to add an optional regulation to cover how staff competitions should be run, considering:
- what rounds can be done there
- where they can be held (I've heard, via Facebook, of a competition that had a staff competition at the delegate's house the night before)
- privacy of results from staff rounds
- possibly a minimum anticipated competition size?

I would suggest that staff competitions can only complete first rounds of events that have multiple rounds, they should be held in the venue of the main competition so that the environment is similar for all competitors, and that results should not be made known from staff competitions until the round is scheduled to begin for all competitors. I don't know how I feel about having a minimum competition size to hold a staff competition; by being an optional regulation, it can be up to the board to determine if holding one is necessary.

**Comment by lgarron** [comment]
There has also been talk about requiring certain kinds/numbers of delegate based on competition size.

Perhaps we can standardize what kinds of competitions exist – what qualifies a competition for a certain type (number of delegates, events/rounds, frequency), and what special situations they may have (things you listed above, using qualification times, number of competitors, no on-site registrations, venue expectations).

**Comment by lgarron** [comment]
> There has also been talk about requiring certain kinds/numbers of delegate based on competition size.

Specifically, #377.

**Comment by AlbertoPdRF** [comment]
Just as #377, I think that this would make more sense on the Delegates Crash Course + Organizer Guidelines than on the Regulations. Thoughts?

**Comment by lgarron** [comment]
> Just as #377, I think that this would make more sense on the Delegates Crash Course + Organizer Guidelines than on the Regulations. Thoughts?

As we have larger and larger competition staff, including arbitrary competitors who volunteered, I think we need to make it clear to everyone how staff rounds work and what is/isn't allowed. I think the Delegates crash course is too specific a place.
