### ISSUE TITLE
Pending/withdrawn registration fees

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#380]
The Board asked to add a regulation that allows to refuse registrations of competitors who owe any fees to the WCA and/or organizers

> Pedro suggested this as a possible idea:
> "I'd propose a 2c1a) Registration may include payment of due fees from past competitions."

**Comment by lgarron** [comment]
Sounds fine to me in principle, but the proposal sounds like a fix in the wrong place. Without knowing the motivation behind it, the wording is very vague (the competitor... can pay for past competitions... if they want?).

2a doesn't actually say the competitor has to pay any fee to compete.

I think there are two better general solutions:
- Formally address the topic of competitor suspensions, and consider this a temporary suspension.
- Specify that an organizer and/or the Board has discretion to refuse registrations from a competitor for specific reasons. I can imagine other ways that a competitor can violate the wording of the spirit of the Regulations after the competition is over, such as 2k3, or by harassing/threatening organizers after the competition.

**Comment by operge** [comment]
I definitely agree with the idea here, this is something we already do at out competitions.

As for the regulations: How about a 2c1+)?

2c1+) EXAMPLE For example, the registration may include mandatory online registration, pre-payment or paying the registration fee for previous competitions.

**Comment by viroulep** [comment]
I support the idea of a generic solution to handle issues related to registrations to past competitions.

In France we sometimes have troubles with no-shows. Lately we've sometimes added a confirmation step during registration, especially when we start to have a waiting list.

I'd like something in the Regulations that permit the organization team to deal with repetitive no-show-ers.
Something like lowering the priority on the registrations list for the people with 2 no-shows in a row, or several no-shows over his past competitions.

So I would definitely support something providing flexibility to the organizers/board to deal with any issue a competitor may have caused with one of his previous registrations (as long as it's fair of course).
