### ISSUE TITLE
Guideline: (Non-final) round results should be available at the venue

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#383]
[This suggestion](https://www.speedsolving.com/forum/threads/suggestion-require-competitions-to-have-a-projector-displaying-cubecomps-results.62380/) was a little strong, but there is certainly inconsistency across competitions, and in some cases competitors can be left waiting a long time without knowing whether they will make it to upcoming rounds.
Depending on the structure of a competition schedule, this can affect whether they need to be at the venue for a few more hours, or can go home because they're done (consider that they might live far away).

We could add a Guideline stating some reasonable time frame by which competitors should be able to know their results for a round, especially if they want to know whether they advanced.

**Comment by Laura-O** [comment]
Well, I don't see the need to add this to the Guidelines. This would be another guideline which is observed by the vast majority of organizers and if it is not, there are no consequences.

We should not add guidelines for issues which affect very few people at very few competitions and have a marginal effect. If we start to do this, other guidelines need to be added as well: I remember a competition where the certificates were printed on thin, cheap paper and some competitors were disappointed. So should we also add that certificates should be printed on paper with at least 100g/m^2?

Furthermore, speaking as an organizer who usually prints all results shortly after the end of a round and someone who has been helping out at many competitions, I can also say that there are usually reasons if this doesn't happen in time. Having a guideline like this will definitely not help to fix the printer or find a missing score sheet from the prior round...  :wink:

**Comment by shelchang** [comment]
The incident in the first post in that thread sounds like the result of poor organizational practice - people who made round 2 should at the bare minimum be announced before the start of round 2!

The method of announcing this can be left up to the organizer, but even when the equipment for Cubecomps or physical printouts is not available, someone should at least read out a list of names or announce the cutoff result.

**Comment by lgarron** [comment]
> If we start to do this, other guidelines need to be added as well: I remember a competition where the certificates were printed on thin, cheap paper and some competitors were disappointed. So should we also add that certificates should be printed on paper with at least 100g/m^2?

Of course not. Certificates are completely optional, but results (and whether you advance) are a core part of the competition.

I don't feel strongly, but the Guidelines are currently the best place for this.

**Comment by garrett-webster** [comment]
At my competitions, we usually don't decide how many move on till a few minutes before the round starts (Based on time, and sometimes if there's a good, clean time that we can make the divide at). I've made a decision on how many advance and then made it smaller based on time before.  I don't know how most places do it, but that's what I've done.

**Comment by shelchang** [comment]
I think that practice should be discouraged in general because it's easy
for a less scrupulous organizer to look at the results and go ”X is my
friend, so I'll set the cutoff lower so they can make the next round” or ”I
don't like/don't want to compete with X, so I'll set the cutoff higher so
they won't make the next round”. Fairer for everyone to decide on a cutoff
ahead of time (e.g. top 16 advance, or average time under 25 seconds
advance), announce it, and stick to it.

**Comment by garrett-webster** [comment]
Is there any reason that if you're using cubecomps (or some other live results system) that you'd have to print out results? Pretty much everyone has a phone/laptop/tablet that can access the internet, and if they don't then a friend or parent does.

**Comment by shelchang** [comment]
It should suffice for the results to be available and accessible by competitors somewhere. Printouts or online live results (especially these days when most people have smartphones) are fine.

**Comment by Laura-O** [comment]
> At my competitions, we usually don't decide how many move on till a few minutes before the round starts (Based on time, and sometimes if there's a good, clean time that we can make the divide at). I've made a decision on how many advance and then made it smaller based on time before. I don't know how most places do it, but that's what I've done.

And what do you announce before?
Sorry, but that is really bad and unprofessional. The number of people advancing to the next round of an event is an important information before the competition and also a reason why some people attend a competition.
Apart from this, you obviously have some experience in organizing competitions, so it should be possible to create an realistic schedule before the competition. If the competition is running late, you can adjust the number of competitors advancing, but that shouldn't be a general approach.

> Is there any reason that if you're using cubecomps (or some other live results system) that you'd have to print out results? Pretty much everyone has a phone/laptop/tablet that can access the internet, and if they don't then a friend or parent does.

Although people can access results online, more than a few like to have them on paper, so they do not have to scroll up and down on small smartphone displays. Furthermore, there might be competitors from other countries, who do not have access to the internet (if there is no free wifi).
