### ISSUE TITLE
3a+++ wording

### ISSUE THREAD

**Issue by Randomno** [thewca/wca-regulations#390]
Pedantic/pointless change but anyway:

3a+++) CLARIFICATION Competitors may borrow puzzles from other competitors privately, to use in competition.

A competitor is also allowed to borrow puzzles from others who are not competing, right?

**Comment by lgarron** [comment]
Yeah, that's probably not a bad idea, since this is a clarification for 3a:

> 3a) Competitors must provide their own puzzles for the competition.

How about just "may borrow puzzles from others"?
