### ISSUE TITLE
Condition for proceeding to the next round should be announced beforehand

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#391]
Clarify that organizers should announce cutoff ranking or cutoff time (see 9p2) before the round starts. This criterion shouldn't change (similar to A1a3+). A good reason to change the criterion is that according to the current one more than 75% competitors pass to the next round; in this case organizers should let 75% pass.

Changing the condition or announcing it after the current round ends could be interpreted as organizers/delegates favor themselves or their friends, which may or may not be true.

**Comment by pedrosino** [comment]
You provided a good reason to change the number, but there is another one: if you are running late, keeping the numbers may imply having to eliminate rounds/events. I would prefer having smaller finals for all events over having big finals for some and no finals for others.
