### ISSUE TITLE
What happens with results if a competitor is disqualified?

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#392]
Say, a round has format average of 5, and a competitor is disqualified after the first attempt according to A1c. What should be the remaining results? 4 empty results, 4 DNS or 4 DNF?

Laura's reply:

> he [delegate] has applied A1c), which says that either the attempt can be disqualified (DNF) or the competitor can be disqualified from the event.
> 
> For the latter the regulations refer to 2j):
> 2j) The WCA Delegate may disqualify a competitor from a specific event.
> 2j1) If a competitor is disqualified from an event for any reason, they are not eligible for any more attempts in the event.
> 
> And then there is this guideline:
> 9f5+) CLARIFICATION The result for an attempt is DNS if the competitor was eligible for the attempt and did not start it (see Regulation A3b2). If the competitor did not qualify for an attempt (e.g. in a combined round), they have no result for the attempt.
> 
> So in this case, the result would be just one DNF and not 4 additional DNS.
> 
> If [delegate's] intentions was to disqualify the attempt only, the competitor was eligible to do the remaining 4 attempts and as these were declined, the result should be DNF, DNS, DNS, DNS, DNS. This decision doesn't make much sense here, but I think it's possible.
> DNFing all attempts does not seem to be a reasonable option here: in prior discussions (I think that was about cumulative time limits) we concluded that an attempt can only be DNFed when the competitor has started the attempt.

**Comment by HippolyteM** [comment]
Hi,

Both DNF and DNS sound weird results to me in a case like this, as the competitor did not fail to solve the cube, nor declined the attempts.
Maybe we should try to be as simple and clear as possible, and a new term could be created, like DIS for Disqualified, which would be use for cases like the one you mentioned and also for retroactive disqualifications, and which would make the results pages more understandable.
The question is: Do you want all the disqualifications to be public?

Hippolyte

**Comment by pedrosino** [comment]
I like Hippolyte's idea. We could have DSQ for disqualified attemps.

**Comment by pedrosino** [comment]
Actually we already have this:
> 9f4) The result of an attempt is recorded as DNF (Did Not Finish) if the attempt is disqualified or unsolved/unfinished.

So there is no question what should happen to results if the competitor is disqualified. The question is wether we want to differentiate between disqualified and unsolved/unfinished.

**Comment by lgarron** [comment]
Also see https://github.com/thewca/wca-regulations/issues/92
