### ISSUE TITLE
Change regulation 4g to include checking to prevent duplicate cube scrambles in MBLD

### ISSUE THREAD

**Issue by a-Maass** [thewca/wca-regulations#394]
It seems like duplicate cube scrambles in MBLD is an issue, I know Mark Boyanowski has had it happen where he was memorizing the cube and he realized the cube was the same scramble as a previous cube, and Marcin Kowalczyk (Maskow) has told me he has had this problem in the past.

Proposal: Change regulation 4g to include checking for duplicate cube scrambles in MBLD, the proposed new 4g is written below:

4g) After scrambling a puzzle, the scrambler must verify that the puzzle is scrambled correctly. If the puzzle state is wrong, the scrambler must correct it (e.g. by solving the puzzle and applying the scramble sequence again).
4g1) Exception: For the 6x6x6 Cube, 7x7x7 Cube, and Megaminx, it is not necessary to correct the puzzle state, at the discretion of the WCA Delegate.
4g2) For Multiple Blindfolded Solving, the scrambler(s) should make sure that they do not accidentally apply the same scramble on two different puzzles, and if the competitor is attempting more than 5 puzzles, they should take extra care to assure this does not happen.

**Comment by lgarron** [comment]
Talked a bit with Alex about this; I like the spirit of trying to address mis-scrambles, but I am strongly against such a specific change. For two main reasons:
- 4g) clearly coves multi BLD already, both in letter and in spirit.
- This would basically be a redundant reminder buried inside the Regulations. We have lots of evidence that "requiring" scramblers to pay more attention is not enough. Even if this proposed change would have an impact on the number of incidents (which are regular but infrequent enough that this will be hard to measure), it won't sufficiently stop us from having to deal with frustrating incidents in the future.

As proposed, 4g2 is also a "should", not a "must", which is weaker than 4g, and would belong in the Guidelines. I do not believe that it is worth making a Guideline for this – reminders are weak for these types of incidents, and a reminder buried in a document that most scramblers read at most once is not useful.

I strongly believe the only systematic, accountable way to fix multi BLD mis-scrambles is to mandate scramble checkers.

**Comment by a-Maass** [comment]
I guess it would be better to have this in the WCA guidelines for the delegate to make sure the scramblers for MBLD ensure that there isn't any duplicate cube scrambles? I think that would be more effective.

**Comment by lgarron** [comment]
> I think that would be more effective.

I think it will not, but perhaps I'm not seeing something you're seeing.
Could you explain why you believe this specific change will have a significant impact, and why it is the right change?

So far, we've had [evidence](https://github.com/thewca/wca-regulations/issues/214) that suggests that this is not simple to fix.

To appropriate a great [list of high-level questions](https://news.ycombinator.com/item?id=12839020) I recently encountered:
- What concrete problem are you trying to solve?
- What do you think is the root cause of that problem? (This is not specific to multi BLD here.)
- How, specifically, is this idea going to address that cause?
- What might be other possible solutions?

**Comment by Laura-O** [comment]
Requiring that scramblers "take extra care" for attempts with more than 5 puzzles is awkward: our goal is that there are no duplicate scrambles - no matter if a competitor is attempting 2 or 50 puzzles. For that reason, differentiating between attempts <= 5 and >5 cubes is definitely the wrong way to go.

**Comment by a-Maass** [comment]
@Laura-O Yeah you're right, I did that because the chance of error is much higher for 20 cubes compared to 2 cubes. 
@lgarron I guess it looks like even telling them in person is not always effective, but I guess telling the delegate in the guidelines looks like it would have an effect but not that much. It seems like it might not be worth implementing.

**Comment by Claster** [comment]
What can be done is to make sure that all cubes of one competitor are scrambled by one scrambler (i.e. different scramblers scramble cubes of different competitors). This reduces a chance of duplicate cubes, but not to zero; and also, I don't think it should be in Regulations or Guidelines, just a note for Delegates, how to hold multi-blind.

Another advice for scramblers is to arrange cubes into groups of 7 and to check upper faces with upper faces of scrambles on a paper (maybe software team could implement drawing only upper faces separately, somewhere on the bottom of a page). And still, this advice is not to be in Regulations, neither we need one more "check goddamn scrambles" regulation.

**Comment by pedrosino** [comment]
> What can be done is to make sure that all cubes of one competitor are scrambled by one scrambler (i.e. different scramblers scramble cubes of different competitors).

This is not always practical. Consider you have two competitors both attempting 20 cubes. If you only use two scramblers, it takes about 5 minutes to scramble them all. If you use 4 scramblers instead, that time is much lower. What we usually do is "I scramble the odd numbers and you scramble even numbers".

**Comment by lgarron** [comment]
> This is not always practical.

Then we have to make it practical.
If we can't maintain the quality of scrambling at our current pace, then we need to find a way to get more helpers or hold fewer events.

**Comment by pedrosino** [comment]
I'm not sure if you misunderstood me, but I meant that having one scrambler per competitor is not always practical. I don't see how we can make it be. If one sole person has to scramble all 50 of Maskow's cube, that is not a good idea, I think.

**Comment by lgarron** [comment]
Ah, I misunderstood slightly. It still applies in the case where we believe a single scrambler would help avoid duplicate scrambles (although I would need some solid data to be convinced of that).
