### ISSUE TITLE
Make the Regulations gender-neutral

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#40]
Or at least not male-centric.

Original title of the issue was: "Switch the default gender of the Regulations to "she"?"

Maybe not, but I'm serious about considering it
Arguments against this should not be rooted in gender-biased conventions.

**Comment by iVinshe** [comment]
Why/how so?

Vincent Sheu
University of California, Berkeley
vsheu@berkeley.edu

**Comment by lgarron** [comment]
More of a "why not"?

Like removing "+2" for misalignments, or removing inspection, I think that the first few arguments that come to mind against something like this are really just rooted in bias. ("That's not usually how gender neutral documents are written.", "It would just confuse everyone.", "It seems like an unnecessary way of taking a stance.")

As for why we might, I don't want to re-write essays about gender issues in our society, but it would avoid the implicit presumption that speedcubing is a male-only sport.

**Comment by jbmertens** [comment]
Pointed out by a competitor during dinner conversation: probably all of the regulations using gender-specific pronouns such as 'he' and 'his' can be re-worded using a gender-neuteral pronoun 'they'/'their' (and plural subjects).  Should be just as easy to read, and no disclaimer needed at the top.

**Comment by lgarron** [comment]
For the record, my reply to @jbcm627 's email with the above note:

> I'm interested in trying to change from the male-centric status quo. I think the plural meaning of "they" would easily confuse international competitors.

**Comment by lgarron** [comment]
By the way, see https://github.com/cubing/wca-documents/blob/she/wca-regulations-2013.md

**Comment by lgarron** [comment]
Implemented as of 9a7082da933a892a42b976dde2a34a885e403eb8. :-)
