### ISSUE TITLE
Regulation for edge twists

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#400]
At my past competition, a competitor had an edge twist during a feet solve. It was found that this could be easily don't on that puzzle without dissasembling the puzzle. The current version of the regulations do not permit twisting the edge in place as we do for corner twists. I would recommend something like:

5b3d) If the puzzle is unsolvable, and can be made solvable by rotating a single edge piece, the competitor may correct the edge piece by twisting it in place without disassembling the puzzle.

I think this is needed with some of the new hardware that competitors as using.

**Comment by a-Maass** [comment]
Maybe just change 5b3c) to include edges too?

5b3c) If the puzzle is unsolvable, and can be made solvable by rotating a single corner or edge piece, the competitor may correct the corner or edge piece by twisting it in place without disassembling the puzzle.

**Comment by lgarron** [comment]
I am against such a change. I do not believe such an accommodation is
needed, and I think it's better to stay more strict where we can.

**Comment by a-Maass** [comment]
btw what 3x3 was this?

**Comment by Jambrose777** [comment]
So if a competitor's cube can edge twist and finds that he has a defect with an edge twist, he must fully remove the edge and correct it in order to complete the attempt, even if he can simply twist the edge in places just the same as a corner twist?

If a competitor did do an "edge twist" should they be awarded a DNF?

(currently in the process of finding out the specific cube). Edit: The cube was a Gans, But I am now informed that this was due to a screw not being fully screwed in.

**Comment by lgarron** [comment]
> So if a competitor's cube can edge twist and finds that he has a defect with an edge twist, he must fully remove the edge and correct it in order to complete the attempt, even if he can simply twist the edge in places just the same as a corner twist?
> 
> If a competitor did do an "edge twist" should they be awarded a DNF?

Yes. [5b3](https://www.worldcubeassociation.org/regulations/#5b3) is very clear on this.

**Comment by Jambrose777** [comment]
Okay! That's okay.

Could you possibly explain the reasoning that it should be okay to do this with corners and not edges?

**Comment by slaz0** [comment]
It makes no sense why corner twists are allowed but edge twists are not. I don't see how the WCA needing to be strict means that we should ignore problems with the regs.

**Comment by lgarron** [comment]
> Could you possibly explain the reasoning that it should be okay to do this with corners and not edges?

> It makes no sense why corner twists are allowed but edge twists are not.

Corner twists are mechanically more likely, and have been so since the beginning of the WCA. That's why there is a specific allowance in the Regulations. Cubers have base their cube choices on it since a long time.

Allowing the same for edges would be a *new* allowance (which no one has asked the WRC for outside of this thread). And we should generally be careful about making any changes to the Regulations that are more lenient.

**Comment by Samuel-Baird** [comment]
Edge twist don’t seem to be uncommon with modern megaminx hardware. I think it would be good to rethink this and potentially allow for twisted edges. I think we should keep an open mind about potential hardware changes in the future that could make edge twist very easy, for example, if edge twist became as easy as corner twist in a few years then many people would want it to be legal. I think that to maintain consistency we should either allow edge twist or we should disallow corner twist to make everything fair. I don't think allowing edge twist would cause any problems.
