### ISSUE TITLE
Hand position for starting the timer (also stopping?)

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#401]
(I'm not sure about the protocol on linking to a delegate's group thread here)

We've seen many cases of borderline ugly starts and/or stops, and some are very hard to judge.
I feel we are maybe too nice on people who do this, since we can't prove they are not touching the timer with their fingers (since palms are down).

I would be in favour of a more restrictive rule, of maybe having a line drawn on the mat and the competitor can't cross that line with the fingers. Also we could require that the puzzle rests beyond that line.

As for stopping, we are already less strict, and I think only clear violations are possible to catch (karate chops, wrists, etc). Not sure how to improve this part.

(I couldn't find any issue specifically about this, but if there is already one, feel free to close this).

**Comment by pedrosino** [comment]
I found some picture I took almost 2 years ago:
https://goo.gl/photos/RjADEgQ9xGU2Huyq9

I can't remember exactly the context and what I was trying to show back then, but the ones labeled 1-7 show hand positions with a tape marking the end of the fingers. Then there's one with a line drawn on the paper, and the last ones are probably to show hand positions without the tape, and how it is hard to judge.

**Comment by pedrosino** [comment]
There was a recent report on a competition and a video showing some very bad starts:
https://www.youtube.com/watch?v=sYILBzm0ITw

I feel it's impossible for the judges to be sure the competitor is doing it correctly, since most of the time the hands stay on the timer for just a second, and more importantly, palms are down, so we can't see the fingers touching the sensors or not.

**Comment by Laura-O** [comment]
Well, I am not completely opposed to this, but I think that this will make things complicated and it has some loopholes.

I do not really understand how you measure the 7 cms. In your pictures, the line looks very close to the timer, so this is probably 7cms from the front side?

Furthermore, how did you come up with the 7 cms?

**Comment by pedrosino** [comment]
7 cm was an educated guess. Here are some pics showing 7, 5 and 3 cms from the "back side" (i. e. the part farthest away from the cuber:
![20170501_164857](https://cloud.githubusercontent.com/assets/1881933/25592578/aa8e68d0-2e8f-11e7-92bf-5cb077f5b098.jpg)
![20170501_165009](https://cloud.githubusercontent.com/assets/1881933/25592593/b73924e4-2e8f-11e7-9576-74988a363a14.jpg)
![20170501_165037](https://cloud.githubusercontent.com/assets/1881933/25592600/be225974-2e8f-11e7-9148-f7668ce340aa.jpg)


I would prefer 3 cm, since it would "educate" people to a proper hand position (which can also affect how they stop the timer).
Also the line should be longer than 10 cm. I will update the PR accordingly.

**Comment by rwcinoto** [comment]
What about the limit being the timer?
![timer](https://cloud.githubusercontent.com/assets/13766465/25604620/38d2d41e-2edb-11e7-8894-0fa0ed831d89.png)

There will be always borderline cases, but with this limit, even if the person pass the timer limit by one phalanx, he would still be touching the timer with his fingers a lot.

**Comment by Laura-O** [comment]
With the curved sensor pads of the G4 timer, this hand position seems to be predestined for causing starting failures.
On these timers the hands automatically slide into a WCA legal position. I don't have a G4 here at the moment, but avoiding that your fingers pass the upper edge of the timer is quite an unnatural and cramped posture.

**Comment by xsrvmy** [comment]
Just a comment about stopping:
I think as long as the hand is stopping the timer (rather than the wrist) no advantage is given to the competitor. After all, the purpose of the stackmat timer is to make sure that the puzzle is released when the timer is stopped

**Comment by AlbertoPdRF** [comment]
I like the line being drawn at 3cm. For future timer generations (or even for the currently being produced ones), maybe the line can be directly incorporated in the design of the mat by Speedstacks? @Laura-O

**Comment by xsrvmy** [comment]
I can foresee several problems with introducing the line

1. The competitor need to take extra care when starting the timer, but time keeping is not technically his responsibility.
2. The judge is likely looking at the stopwatch during inspection, and might miss a finger that crosses the line (esp. if only by 1-3 millimeters)
3. Whether or not the puzzle is resting over the line may be hard to judge on certain puzzles, such as megaminxs, clocks, tiled puzzles and pillowed 7x7s.
4. Without video evidence from a good angle, disputes are nearly impossible to resolve.

Response to comment above:
The Gen2 mat will need lines too.

**Comment by KitClement** [comment]
> 1. The competitor need to take extra care when starting the timer, but time keeping is not technically his responsibility.

Timekeeping is of course the competitor's responsibility. Even with the current structure of penalties, it's clearly their responsibility to avoid them. While about stopping the timer, [A6b](https://www.worldcubeassociation.org/regulations/#A6b) implies it's their responsibility to make sure the timer is working appropriately.

> 2. The judge is likely looking at the stopwatch during inspection, and might miss a finger that crosses the line (esp. if only by 1-3 millimeters)
> 3. Whether or not the puzzle is resting over the line may be hard to judge on certain puzzles, such as megaminxs, clocks, tiled puzzles and pillowed 7x7s.
> 4. Without video evidence from a good angle, disputes are nearly impossible to resolve.

These are already larger problems with the current set of regulations. Judges currently need to simultaneously watch during inspection for whether a competitor is touching the puzzle, whether their fingers are on the timer, how much inspection they have used, if moves have been applied to the puzzle, and if their hands are face down. These are incredibly difficult things to judge, either in the moment or on video. Having a line on the stackmats would at least collapse the first two requirements for judges into one, and the line would increase awareness of these penalties for judges at the very least.

**Comment by Laura-O** [comment]
> I like the line being drawn at 3cm. For future timer generations (or even for the currently being produced ones), maybe the line can be directly incorporated in the design of the mat by Speedstacks? @Laura-O

Well, that's possible. However, it will take a long time until they will be widely used at competitions, which brings up another problem: similar to the issues with rented timers & attaching O-rings, there is also the problem that organizers/delegates can't draw these lines on rented mats.

Of course, you could use tape for the marking and remove it after the competition. But that's quite a lot of work before a competition...

**Comment by xsrvmy** [comment]
Just a concern, would changing the regulations make it significantly harder to break the 2x2, pyra or skewb wr singles (or 2x2 average)?
Especially, if the puzzle must rest beyond the 3cm line, the time taken to start the timer will (possibly) increase a little, which is a big difference when it comes to sub 1.5 times.

**Comment by Laura-O** [comment]
@thewca/wrc-team 
We need a conclusion here to decide whether we want to merge (or change) Pedro's PR or not.

For the reasons I already stated here, I am not a big fan of this change. These are:
* It makes judging more complicated. Judges already have to look at the stopwatch and the hands during the inspection. This regulation adds three more places judges have to look at: both fingertips and the puzzle.
* I think this might be an advantage for people with long fingers: if your hands are small, the distance between your fingertips and the puzzle is larger.
* There will be problems with rented mats.
* Additionally, I just realized that it will be difficult to see such a line on the [dark Gen4 mats](http://speedstacks.com.hk/wp-content/uploads/2015/12/image4.jpeg).

**Comment by pedrosino** [comment]
About the first point, it would "remove" the need to look at hands. Puzzle+line+fingertips would be sort of a single picture to check.

About rented and dark mats, I believe white tape would be good enough. It can be easily removed after the competition.

**Comment by Laura-O** [comment]
> About the first point, it would "remove" the need to look at hands. Puzzle+line+fingertips would be sort of a single picture to check.

You would still have to check if the competitor is starting the timer with palms facing down. Sure, you can probably see that from the position of the fingertips, but you would still have to check that. It's definitely complicating the judging procedure.

> About rented and dark mats, I believe white tape would be good enough. It can be easily removed after the competition.

Yes, you probably have to replace that tape anyway after a competition because it wears off. I do not consider myself as a lazy person (at least regarding WCA issues :-P), but preparing 12-20 mats before each competition would be a very annoying task for me. Putting some tape on a mat takes like no time, but if you want to do that precisely and not crooked, you need some time.

Another problem I see: with the bent Gen4 timers the distance is different and doesn't really work for me. When I put my hand in a relaxed position over the curved sensor pads it looks like this with a 3cm line from the center of the timer: 
![img_20171030_194856](https://user-images.githubusercontent.com/362249/32189962-8e284ce0-bdac-11e7-935a-62932a919772.jpg)

To move my fingers behind the line I have to either move my fingers back or lift my middle finger, which does not feel very comfortable and less intuitive.

With the old Gen3 timer that's not a problem:
![img_20171030_195057](https://user-images.githubusercontent.com/362249/32189966-8e7af68e-bdac-11e7-8068-8829bf299bd5.jpg)

It probably seems that I am heavily attacking this proposal. However, I am mainly concerned that this will create much more problems than it helps. Even with this proposal, it's still possible to quickly slide your hands from the "3 cm" position to the front and start the timer when your fingers are next to the puzzle (like a starting airplane). It still would be difficult to judge when the timer was started, so these ugly starts would still be happening.

**Comment by pedrosino** [comment]
I don't feel you are attacking it :)
You make valid points. I was just looking for a way to improve this thing, which really annoys me.
