### ISSUE TITLE
Reorder and Rename events in 9b

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#405]
Recently the order of events was changed on rankings and competitions pages. For consistency, we should change them in Regulations (9b) as well.

The new order of events:

Rubik's Cube
2x2x2 Cube
4x4x4 Cube
5x5x5 Cube
6x6x6 Cube
7x7x7 Cube
3x3x3 Blindfolded
3x3x3 Fewest Moves
3x3x3 One-Handed
3x3x3 With Feet
Megaminx
Pyraminx
Rubik's Clock
Skewb
Square-1
4x4x4 Blindfolded
5x5x5 Blindfolded 
3x3x3 Multi-Blind

This implies that we should change 9b1 to:
9b1) Rubik's Cube, 2x2x2 Cube, 4x4x4 Cube, 5x5x5 Cube, Rubik's Cube: One-Handed, Megaminx, Pyraminx, Clock, Skewb, and Square-1.

9b2 to:
9b2) 6x6x6 Cube, 7x7x7 Cube, Rubik's Cube: Fewest Moves, and Rubik's Cube: With Feet.

No changes to 9b3.

**Comment by Claster** [comment]
Oh wait, we should also rename events (probably that is the most important part :P) .

9b1) Rubik's Cube, 2x2x2 Cube, 4x4x4 Cube, 5x5x5 Cube, 3x3x3 One-Handed, Megaminx, Pyraminx, Clock, Skewb, and Square-1.

9b2) 6x6x6 Cube, 7x7x7 Cube, 3x3x3 Fewest Moves, and 3x3x3 With Feet.

9b3) 3x3x3 Blindfolded, 4x4x4 Blindfolded, 5x5x5 Blindfolded, and 3x3x3 Multi-Blind.

**Comment by Laura-O** [comment]
I think this is fixed by renaming and reordering the events in 9b*.

We could change the headings of C-F, but I think that's not necessary and it might be confusing to have 4 paragraphs starting with "3x3x3...".

**Comment by AlbertoPdRF** [comment]
This was fixed in #479
