### ISSUE TITLE
Change inspection time calls?

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#410]
As per the discussion going on at the delegates list, I present a proposal of a rewording of article A3:

https://www.diffchecker.com/iPPskxoW

**Comment by Randomno** [comment]
Any summary of the discussion?

**Comment by jfly** [comment]
Urg, sorry @Randomno, the discussion is still ongoing. Let's continue the discussion about transparency over on https://github.com/thewca/wca-regulations/issues/388.

@pedrosino, the fact that you linked to a diff in this issue tells me this should probably just be a PR =)

**Comment by pedrosino** [comment]
Well, I just wanted to present the changes in a friendly way. I won't make the PR until we have a somewhat clear position on actually making the change or not.

**Comment by garrett-webster** [comment]
Uh... I really like 8 and 12 seconds. What's the argument for changing it to 10 only?

**Comment by Laura-O** [comment]
Well, I'd say this discussion/proposal died as fast as it started, so I am closing this issue.
