### ISSUE TITLE
Switch to American spelling

### ISSUE THREAD

**Issue by jfly** [thewca/wca-regulations#411]
(Sorry if there is already an issue for this, I couldn't find one.)

Ron told me that since we're going to incorporate as a NPO in the US, we are going to go with American spelling on the website and in the Regulations.

(Related: @pedrosino recently went to the effort of changing all occurrences of "organisation" to "organization" on the WCA website. See https://github.com/thewca/worldcubeassociation.org/pull/1119#issuecomment-274271742.)

**Comment by pedrosino** [comment]
I may have missed one organisation somewhere. I glanced at it and put a
note on my phone to check, but didn't have time yet.

Em 14/02/2017 15:07, "Jeremy Fleischman" <notifications@github.com>
escreveu:

**Comment by AlbertoPdRF** [comment]
I just merged this directly into draft instead of making a Pull request. I reversed the changes and I'll do it correctly now.
