### ISSUE TITLE
8a4: Clarify announcement deadlines for competitions

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#415]
It should be clarified that competitions may only be announced less than 4 weeks before in exceptional cases.

Suggestions for 8a4):
1. _Be announced on the WCA website at least four weeks before the start of the competition. Exception: In special cases, competitions may be announced up to two weeks before, at the discretion of the WCA Board._

or

2. _Be announced on the WCA website at least four weeks before the start of the competition. Exception: In case of unforeseen and inevitable cases, competitions may be announced up to two weeks before, at the discretion of the WCA Board._

**Comment by garrett-webster** [comment]
I should be noted that this would make 8a4++ obsolete. I'm fully in favor of this, and say it is put before the board immediately.

**Comment by lgarron** [comment]
> Exception: In case of unforeseen and inevitable cases, competitions may be announced up to two weeks before, at the discretion of the WCA Board.

I like the idea of being more specific, but I would keep it simple and just say "In unavoidable cases".

> I should be noted that this would make 8a4++ obsolete. I'm fully in favor of this, and say it is put before the board immediately.

This came at the request of the Board. :-)

**Comment by AlbertoPdRF** [comment]
Sorry, for closing and re-opening this! I thought I was closing a quote :P 

> 1. Be announced on the WCA website at least four weeks before the start of the competition. Exception: In special cases, competitions may be announced up to two weeks before, at the discretion of the WCA Board.

For me, it would be perfect to just have:

Be announced on the WCA website at least four weeks before the start of the competition. Exception: In unavoidable cases, competitions may be announced up to two weeks before, at the discretion of the WCA Board.

**Comment by pedrosino** [comment]
I'm fine with the idea, but "unavoidable" seems hard to define. I would be happy with the "special cases".
