### ISSUE TITLE
1c4: Change "Board" for "Results Team"

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/wca-regulations#417]
1c4 should say:

> Sending corrections to the competition results to the WCA Results Team.

Instead of:

> Sending corrections to the competition results to the WCA Board.

Thanks @pedrosino and @Luis-J-Ianez for pointing that out!

**Comment by Luis-J-Ianez** [comment]
You can better credit @pedrosino :)

**Comment by AlbertoPdRF** [comment]
Done!

**Comment by AlbertoPdRF** [comment]
Fixed!
