### ISSUE TITLE
Document with regulations, guidelines and additional information for organizers

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#420]
As discussed with the Board, we need a document which gives (potential) organizers a clear idea about regulations and policies.

Among other topics, this should include (edited):
* General approach how to become an organizer (frequently asked question to the WRC :grimacing:)
* Deadlines for announcing competitions (cited from the regulations)
* Proximity policy
* Competitor limits
* Waiting lists
* Tasks during the competition
* More?

**Comment by AlbertoPdRF** [comment]
Just to have it documented here too:

I've created the document "Organizer guidelines" in our Drive, and I'll start working on it when I have the time. Any help is appreciated :)

**Comment by Laura-O** [comment]
Related: #237 and #265

**Comment by Luis-J-Ianez** [comment]
- Management of the registration: competitors limits and waiting list control.

**Comment by pedrosino** [comment]
What organizers should do on competition day.

I know this varies from place to place, but some stuff is common and very important, like actually managing the competition.

**Comment by Laura-O** [comment]
> I know this varies from place to place, but some stuff is common and very important, like actually managing the competition.

Seems difficult as the overlap of the tasks organizers are expected to do in different countried is really small. But I'll put it on the list.

**Comment by Laura-O** [comment]
[Organizer guidelines](https://www.worldcubeassociation.org/organizer-guidelines) are on the website now.

**Comment by AlbertoPdRF** [comment]
Should we make a public announcement about this? It would encourage a lot of people to read the document :)
