### ISSUE TITLE
Cleanup the regulations about cutoffs

### ISSUE THREAD

**Issue by jfly** [thewca/wca-regulations#423]
I just did a careful read of how the regulations talk about cutoffs (with the intent of documenting these things in our competition JSON format (see https://github.com/thewca/worldcubeassociation.org/issues/946)). There are some ambiguities and inconsistencies with how the relevant regulations are worded that I think we could clean up.

The regulations define 2 kinds of cutoffs:

- [9g2](https://www.worldcubeassociation.org/regulations/#9g2): Advancing to the next phase of a combined round ("decided by ranking (best x competitors) or by result").
- [9p2](https://www.worldcubeassociation.org/regulations/#9p2): Advancing to the next round of an event ("determined by either a cutoff ranking or a cutoff time in the preceding elimination round").

## My complaints

1. The regulations do not define good terms to distinguish between these 2 concepts. As things stand right now, it's ambiguous what "cutoff" refers to. IMO, this ambiguity is part of why it has been so difficult to stamp out usage of the phrases "hard cutoff" and "soft cutoff".
2. 9p2 uses the phrase "cutoff time", which seems to exclude 333mbf and 333fm, events which are not ranked by time (see #429).
3. 9p2 uses the phrase "elimination round", which shows up nowhere else in the regulations. I know what it's referring to, but I think the word "elimination" only serves to increase cognitive load, forcing the reader to ask: "how does an elimination round differ from a regular round?"

## How I'd address my complaints

1. Invent new terms to distinguish between "next phase cutoff" and "next round cutoff" and remove all references to vanilla "cutoff" from the regulations. Here are some suggestions:
    - 9g2: "next phase cutoff", "phase cutoff", "combined round cutoff", "combined cutoff", or "soft cutoff"
    - 9p2: "next round cutoff", "round cutoff", "advancing cutoff"
2. Change the phrasing of 9p2 to be exactly the same as the phrasing of 9g2: "decided by ranking (best x competitors) or by result".
3. Remove the word "elimination", I don't believe it adds any value here.

I'm happy to send in a PR with some or all of these changes if you like these ideas.

**Comment by AlbertoPdRF** [comment]
There's also the same problem with [9p3)](https://www.worldcubeassociation.org/regulations/#9p3):

> 9p3) If a qualifying competitor withdraws from a round, they may be replaced by the best-ranked competitor below the cutoff from the preceding round.

And shouldn't the "they" be an "it"? Maybe I'm not understanding it well because I'm not a native speaker, but for me the "they" doesn't make sense if we are speaking of "a qualifying competitor" instead of "qualifying competitors". **CLARIFIED BY @jfly** 

Also, the word elimination isn't present on 9p3), and I think it shouldn't be present on 9p2) neither.

I think that we could rephrase 9p2) to:

> 9p2) The competitors who advance to the next round must be determined by ranking (best x competitors) or by result (all competitors with a best result under x) in the preceding round.

Although this phrasing could make people mistakenly think that you can qualify for the next round of an event with a single better than x, or mistakenly think that more than 75% can make it to the next round of an event if they all average under x. Thoughts? Suggestions?

And rephrase 9p3) to:

> If a qualifying competitor withdraws from a round, they may be replaced by the best-ranked non-qualifying competitor from the preceding round.

My idea is to not define more terms in order to keep the regulations as simple as possible, but I'm not happy at all with my suggestions.

*I edited the post to fix some grammar issues

**Comment by jfly** [comment]
> And shouldn't the "they" be an "it"? Maybe I'm not understanding it well because I'm not a native speaker, but for me the "they" doesn't make sense if we are speaking of a "competitor" instead of "competitors".

In English, "they" can be a single person gender neutral pronoun. See #40 and [the Wikipedia article on singular they](https://en.wikipedia.org/wiki/Singular_they).

"it" is also a word some people use as a gender neutral pronoun, see [this Wikpedia article](https://en.wikipedia.org/wiki/Third-person_pronoun#It_and_one_as_gender-neutral_pronouns), but it's not the direction @lgarron decided to take the Regulations.

**Comment by AlbertoPdRF** [comment]
Thank you for the clarification! I'll edit my previous post accordingly :)

**Comment by jfly** [comment]
> My idea is to not define more terms in order to keep the regulations as simple as possible

I disagree with this. Simplicity is great, but not when it makes it impossible for us to actually talk about things. As things currently stand, the word "cutoff" simply has no meaning.

**Comment by AlbertoPdRF** [comment]
> I disagree with this. Simplicity is great, but not when it makes it impossible for us to actually talk about things. As things currently stand, the word "cutoff" simply has no meaning.

But if we could get rid of the ambiguity of the term, wouldn't that problem be solved? My suggestions of rephrasing were trying to address this problem, leaving the word "cutoff" stand for "next phase cutoff" only.

**Comment by jfly** [comment]
Ohh, sorry I see what you did now, you removed the word "cutoff" from 9p2) and 9p3). That does make the word "cutoff" unambiguous, which does address my main concern. It feels like a bit of a copout, we programmers on the WST need to give these things reasonable variable names, and it's nice if we can use terms from the regulations to do so =) That said, software concerns probably shouldn't drive the way we write our regulations.

**Comment by AlbertoPdRF** [comment]
Let's wait for other members of the WRC to express their opinions, maybe they see more reasonable to define the terms "next phase cutoff" and "next round cutoff" :)

**Comment by Laura-O** [comment]
I support Alberto's suggestion.

I just realized that I always found the phrasing of [9p2](https://www.worldcubeassociation.org/regulations/#9p2) confusing because of the term "cutoff", so simply removing it (and adding an explanation) is a good idea.

**Comment by AlbertoPdRF** [comment]
Should #426 be taken into account here too?

**Comment by AlbertoPdRF** [comment]
Taking #426 into account, the changes proposed would be:

> 9p2) The competitors who advance to the next round must be determined by ranking (best x competitors) or by result (all competitors with a better result than x) in the preceding round.
> 
> 9p3) If a qualifying competitor withdraws from a round, they may be replaced by the best-ranked non-qualifying competitor from the preceding round.

I'd also like to add a Regulation like [5b5e)](https://www.worldcubeassociation.org/regulations/#5b5e) or a Guideline clarifying that if more than 75% obtain a better result than x, only the top 75% can proceed to the next round. Thoughts?
