### ISSUE TITLE
What's the difference between an "event format" and a "round format"?

### ISSUE THREAD

**Issue by jfly** [thewca/wca-regulations#424]
The WCA regulations refer to "round format" in a 4 places, and "event format" in exactly one place ([9b](https://www.worldcubeassociation.org/regulations/#9b)). I'm pretty sure I know what a "round format" is, but what's an "event format"?

**Comment by Laura-O** [comment]
My interpretation: an event format is a format for a specific event, e.g. "Mean of 3" is an event format for FMC, but not an event format for 3BLD.

**Comment by jfly** [comment]
(I realize this all probably sounds pretty nitpicky, but I like to make our code consistent with the regulations whenever possible, and these issues arise when naming tables/columns/variables/methods.)

I see. So a "round format" is something a round has, whereas an "event format" is something an event has? By that definition, I don't think it makes sense that regulations 9b1a, 9b2a, 9b3a use the phrase "round format" instead of "event format".

## Currently

9b1a) Round formats for these events are: "Best of X" (where X is 1, 2, or 3), and "Average of 5".

## Arguably more consistent

9b1a) **Event** formats for these events are: "Best of X" (where X is 1, 2, or 3), and "Average of 5".

**Comment by Laura-O** [comment]
Well, that was my guess... let's hear if @lgarron has something to add. :-)

**Comment by SAuroux** [comment]
Hm, my understanding is rather that for example 3x3x3 One-Handed is an
event format of puzzle 3x3x3.

Am 04.04.2017 12:54 vorm. schrieb "Laura Ohrndorf" <notifications@github.com

**Comment by lgarron** [comment]
I don't remember if we ever carefully looked at this. I think it's fine to say "round format" everywhere to make it clear that individual rounds have formats (rather than all rounds of an event at a competition having the same format).

**Comment by jfly** [comment]
> Hm, my understanding is rather that for example 3x3x3 One-Handed is an event format of puzzle 3x3x3.

@SAuroux, that's an interesting interpretation that would explain the wording of the regulations! However, by that definition, I don't see the value in distinguishing between an "event" and an "event format". Also, the multiple meanings of the word "format" is quite confusing (kind of like the multiple meanings of the word "cutoff", see #423).

**Comment by lgarron** [comment]
> However, by that definition, I don't see the value in distinguishing between an "event" and an "event format".

Ah, so: shortening to this?

> The official puzzles and **events** of the WCA are:

On reflection, I think this is actually better, because nowhere else do we define events. (We also say "for these events" in sub-regulations of 9b.)

**Comment by SAuroux** [comment]
I would guess that this is just a part that was never really refined. Why
not simply: "The official events of the WCA are:" ?

I think the term "event format" is caused by the fact that the same
sentence mentions "official puzzles" and that for example "3x3x3:
One-Handed" is not a "puzzle".

2017-04-04 2:00 GMT+02:00 Lucas Garron <notifications@github.com>:

**Comment by jfly** [comment]
I agree with @SAuroux, the word "puzzle" adds nothing to that sentence, except maybe some confusion.

**Comment by lgarron** [comment]
> I agree with @SAuroux, the word "puzzle" adds nothing to that sentence, except maybe some confusion.

I think there's value in reiterating that the WCA is about puzzles. But 9a) already covers that, so I'd be in favor of removing "puzzles", too. :-)

**Comment by pedrosino** [comment]
I'm in favour of removing the "format" from 9b1 and keeping the rest as it is.
