### ISSUE TITLE
Get rid of ranking based combined round cutoffs

### ISSUE THREAD

**Issue by jfly** [thewca/wca-regulations#425]
[9g2](https://www.worldcubeassociation.org/regulations/#9g2) says:

> 9g2) Whether a competitor proceeds to next phase of a Combined round, must be decided by ranking (best x competitors) or by result (all competitors with a best result under x) of the first phase.

I propose removing the part about ranking and changing this to:

> 9g2) Whether a competitor proceeds to next phase of a Combined round, must be decided by result (all competitors with a best result under x) of the first phase.

I just chatted with @Laura-O about this. We both have never seen a ranking based cutoff actually used, and in practice, it would be a big hassle to enforce. As Laura just said to me "it doesn't really make sense... enter the results first and then decided who may proceed to the next phase... yay :stuck_out_tongue:"

As the WST works on the WCIF spec and adding support for announcing round cutoffs and time limits, we're intentionally *not* going to support ranking based cutoffs.

**Comment by Claster** [comment]
This was used at Polish Championship 2016. I'm not aware of other usages though.

> - ranking cutoff - I think it didn't work as expected. We used them for 6x6 and 7x7 events. After first solve we had to enter all results to get a cutoff. It caused a little delay, as nothing was held on the main stage for a while. Cutoff cannot be changed in cubecomps during a round, so all first attempts had to be rewrite once more. I have impression that fast cubers could do their next 2 attempts like in a normal round with time cutoff instead of waiting for slowest cubers and entering the results. Maybe mixing the order (1st attempt of 7x7, 1st attempt of 6x6, 2nd and 3rd attempt of 7x7, 2nd and 3rd attempt of 6x6) would not cause a delay but it can make a confusion.

Sounds like it is a mess to use ranking cutoffs (one of the reasons though is that cubecomps.com doesn't support it, because nobody uses it), so let's get rid of them.

**Comment by Laura-O** [comment]
Urgh... thanks for digging this out. I didn't expect anyone used this is the last years.

In general, this is also against the idea of announcing cutoffs before the start of a round. We always say that this can influence the strategy how you do your attempts. With this format, you only have a slight idea what the cutoff will be...
But yes, let's get rid of it!

**Comment by AlbertoPdRF** [comment]
I'm also in favor of getting rid of this type of cutoff

**Comment by pedrosino** [comment]
I support Jeremy's proposal as well.
