### ISSUE TITLE
DNS for signing empty results after an attempt

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#427]
Quoting @SAuroux:
>When reading Nikkhil's reply, I first thought "no way, this is only DNS if the competitor signs before starting the attempt".
>But reading A7c2, that paragraph really says that the situation where a competitor solves normally, but then signs before the judge writes down the time is a DNS as well. 
>Problem: This contradicts with the definitions of DNS and DNF:
>9f4) The result of an attempt is recorded as DNF (Did Not Finish) if the attempt is disqualified or unsolved/unfinished.
>9f5) The result of an attempt is recorded as DNS (Did Not Start) if the competitor is eligible for an attempt but declines it.

My initial though was that changing this to DNF wouldn't be much better as this would override the call of the judge. However, the situation is similar to a competitor resetting the timer before the judge has written down the result, so DNF should be fine.

**Comment by lgarron** [comment]
> My initial though was that changing this to DNF wouldn't be much better as this would override the call of the judge. However, the situation is similar to a competitor resetting the timer before the judge has written down the result, so DNF should be fine.

A7c2 only addresses signing before the beginning of an attempt.

> If a competitor signs (or otherwise marks) ***an attempt before they have begun it***, ...

**Comment by Laura-O** [comment]
Maybe I am just not getting what you want to point out, but the part of A7c2 you didn't quote is:

> ... or before the judge has finished recording the result...

So it's not "before an attempt" only.

**Comment by lgarron** [comment]
Ah, yes. I *thought* we had a bug about that and took it out.
Seems we haven't, so this is still relevant.

**Comment by mande-nikhil** [comment]
Shouldn't the final scoresheet reflect what the outcome is?
I'd rather pull some stuff from A7c2) and change 9f5) to 

9f5) The result of an attempt is recorded as DNS (Did Not Start) if the competitor is eligible for an attempt but declines it, or signs (or otherwise marks) an attempt before they have begun it, or before the judge has finished recording the result, they forfeit the attempt and the result will be considered DNS.

I don't have a strong opinion on this though, like Laura said

> However, the situation is similar to a competitor resetting the timer before the judge has written down the result, so DNF should be fine.

**Comment by lgarron** [comment]
> I don't have a strong opinion on this though, like Laura said

I strongly believe that we should follow the existing definition of DNS. There should be three states for an attempt:

- Did not start
- Started, but did not finish
- Finished

Once someone understands these, I've never seen them make a mistake about what the result should be in the first two cases.

I think signing after the start of the attempt, but before the judge write the result, should definitely be a DNF.

**Comment by Claster** [comment]
Another suggestion:

9f5) The result of an attempt is recorded as DNS (Did Not Start) if the competitor is eligible for an attempt but declines it **(see also Regulation A7c2)**.


> I think signing after the start of the attempt, but before the judge write the result, should definitely be a DNF.

How can we be sure that this attempt was actually started?

**Comment by Laura-O** [comment]
> How can we be sure that this attempt was actually started?

Because this regulation is applied in cases when the attempt was started? :confused:

Are we talking at cross purposes?

**Comment by pedrosino** [comment]
I agree that signing after solving but before the judge recording the time should be DNF.

Proposal:
> A7c2) The competitor must not sign an attempt on the score sheet before the judge has recorded the final result for that attempt. If a competitor signs (or otherwise marks) an attempt before they have begun it, they forfeit the attempt and the result will be considered DNS. If the competitor signs (or otherwise marks) an attempt after solving but before the judge has finished recording the result, the result will be considered DNF.

**Comment by SAuroux** [comment]
I was just checking for exactly something like Pedro's last proposal. I hope this well be taken into account for the next regulations release?
