### ISSUE TITLE
Does Article Z allow for multiple qualifying times per event?

### ISSUE THREAD

**Issue by jfly** [thewca/wca-regulations#428]
For example, US Nationals 2017 [announced the following qualification for FMC](https://www.cubingusa.com/nationals2017/qualifying.php):

```
FMC	35 single OR 45 mean
```

Is this actually allowed by [Z4](https://www.worldcubeassociation.org/regulations/#Z4)?

**Comment by garrett-webster** [comment]
"based upon qualification results" is the relevant section. I don't see why not. It uses the plural "results" so I don't see why you can't check against multiple results. It's pretty open ended on how it can be used (which is a good thing) as I see it.

**Comment by jfly** [comment]
> It's pretty open ended on how it can be used (which is a good thing) as I see it.

It's not a good thing if it makes our software more complicated (see the [WCIF spec](https://docs.google.com/document/d/1hnzAZizTH0XyGkSYe-PxFL5xpKVWl_cvSdTzlT_kAs8/edit#heading=h.oyub92s3oi50)).

**Comment by Claster** [comment]
It is not prohibited by Z4. Do you want to prohibit things just to make spec simpler? :P

```
  "type": "ranking"|"single"|"average"|"single_or_average",
  "ranking": Integer,          // Only used if "type" == "ranking".
  "single": AttemptValue,      // Only used if "type" == "single" or "single_or_average".
  "average": AttemptValue      // Only used if "type" == "average" or "single_or_average".
```

**Comment by Laura-O** [comment]
When Jeremy asked me this question yesterday, I remembered a discussion we had after US Nats were announced. So it's not a new question.

In general, we shouldn't adjust our regulations to make software simpler. However, we can take this as evidence that the specific regulations might be unclear and need further clarification.

In this case, having both average and single qualification times doesn't make much sense for me.
It makes some sense in FMC if you want to avoid to exclude people who didn't have the chance to get a 'mean of 3' result in a competition (I think that was the idea at US Nats).
But why would you want to set average *and* single qualification times for speedsolving events?

**Comment by Claster** [comment]
Correct, that shouldn't be used for speedsolving events. However, such spec will be even more messy:
```
// "single_or_average" only if id is "333fm"
"type": "ranking"|"single"|"average"|"single_or_average",
```

Btw, WRC was asked once whether it is possible to use results of one event as a qualification for another (e.g., 3x3 bld sub-1:00 passes for 4x4 bld). Despite this thing is not prohibited by Regulations either, after some discussions it was decided not to do it. You see, Jeremy, spec could be much harder :-P

**Comment by jfly** [comment]
> Do you want to prohibit things just to make spec simpler?

Yes, if the things we're prohibiting seem to have no use, which is how @Laura-O and I feel about allowing multiple qualifications for an event. If we allow `single_or_average`, then do we also allow `single_and_average`? It's a slippery, useless slope.

**Comment by Claster** [comment]
Well, this thing does have some use, US 2017 is an example; and single_and_average doesn't, to my knowledge. I'm happy to get rid of both and to clarify it in Regulations though if we get a proof this was the only usage (e.g., from the Board, as they should approve all qualifications).

**Comment by AlbertoPdRF** [comment]
I'm with @Claster here: we can get rid of both if they are not used. It seems clear that `single_and_average` is not used, but we should ask the Board if `single_or_average` has been used more than once. Should I e-mail them and ask? Or someone else wants to take care of it?

EDIT: once we have the answer, we will have to clarify what's permitted and what's not.

**Comment by Laura-O** [comment]
Yes, can you please ask the Board, @AlbertoPdRF ?

**Comment by AlbertoPdRF** [comment]
Done! I will take care of the issue once we get an answer :)

**Comment by AlbertoPdRF** [comment]
The Board does only remember one usage of `single_or_average`, and any of `single_and_average`. I'm in favor of getting rid of both. Thoughts?
