### ISSUE TITLE
A4b is vague

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#43]
It's been clear enough for now, but Oscar Roth Anderson is interested in making sure this is more clear. Email, June 25, 2013:

> Straight to the point:
> A4b: The competitor places his hands on the elevated sensor unit of the
> timer, with his fingers touching the sensors and palms down. Penalty: time
> penalty (+2 seconds).
> 
> In other words:
> 1) The competitor needs to touch the sensors with all his fingers. (If this
> is not meant, then the meaning of this rule is absurd, because 2 fingers is
> multiple fingers)
> 2) palms should be faced down.
> 
> If the competitor is supposed to touch the sensors with all fingers (read:
> http://en.wikipedia.org/wiki/Finger if you are unsure what is considered a
> finger), it would mean solves like Mats' 5.55 should be +2'ed because of the
> cuber not touching the sensors with their thumbs. (There's a lot more
> incidents of this)
> 
> If the competitor is supposed to touch the sensors with just multiple
> fingers, then I would be able to start like http://i.imgur.com/b5jzrdX.png 1
> thumb per hand=2 fingers (yay, multiple fingers). palm facing down, check!

**Comment by lgarron** [comment]
Make sure that it's clear what the penalty is for.

**Comment by lgarron** [comment]
Draft idea that Oscar dug up and sent to me today:

> A4b) The competitor places his hands on the elevated sensor unit of the timer, with at least 2 non-thumb fingers from each hand touching the sensors and with the palms facing down. Penalty: time penalty (+2 seconds).

**Comment by lgarron** [comment]
I've changed A4b to the following:

> - A4b) The competitor uses his fingers to touch the elevated sensor surfaces of the timer. His palms must be facing down, and located on the side of the timer that is closer to him. Penalty: time penalty (+2 seconds).

I don't think we need to specify how many fingers the competitor needs to use. As long a we're using a standard timer+mat setup and the palms are on the competitor's side, I think we're fine.

**Comment by Mollerz** [comment]
Personally I'd still like it to be all fingers (not necessarily including thumbs), because of recent events in the delegate discussion.

**Comment by lgarron** [comment]
There is another thread about this on the Delegate list. I really wish the discussion should be open, but at least it's productive. :-/

Here's the current version under consideration:

> - A4b) The competitor uses his finger[tip]s to touch the elevated sensor surfaces of the timer. The rest of his hands must be located on the side of the timer that is closer to him, with palms must be facing down. Penalty: time penalty (+2 seconds).

("fingers" vs. "fingertips" is still under discussion.

**Comment by lgarron** [comment]
Also discussed in the [Lifestyle Seasons Summer 2015 Delegate's Report](https://groups.google.com/forum/#!msg/wca-delegates/ttWcMdUQLAc/sQKow74zlxoJ).
