### ISSUE TITLE
Limit for a competition day

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/wca-regulations#430]
At White City Cubing we had 3 attempts FMC. The 1st and the 2nd was in the beggining and in the end of 1st comp day.
We were far behind the schedule at the 1st day. Comp was started in 9:15 AM and was ended in ~10 PM. Competitors were tired and some competitors (6/14) refuse 2nd attempt. 

I suggest to set a limit for one competition day: about 8 hours (not including breaks).

Pros: This will motivate organizers to make schedule more responsible and take into account the possible backwardness. 
Cons: It is unclear what to do, if the day was not in limit or what to do, if it's clear that competition's end will be delayed.

**Comment by Laura-O** [comment]
I understand your frustration, but that's nothing the regulations should define.

On the one hand, most competitions probably have a net cubing time above 8 hours. So that seems to be an amount of time people are fine with. Competitions are exhausting and stressful, but that's why they are competitions.
On the other hand, what would you do if you reach the 8 hours right before the 3x3 final? Cancel it and go home? That doesn't sound like fun.

You can be sure that most organizers and delegates pay attention to design a good and reasonable Schedule. However, there can always be unforeseen incidents, which can destroy the best planning. For that reason, defining strict time limits for competitions in the regulations is not an option.

**Comment by lgarron** [comment]
@Laura-O: I think it's pretty reasonable to set an international guideline for what a competition length should be. Guidelines can always be broken for good reason, but I think there definitely should be a good reason if your competition approaches 10 hours for a day. An explicit Guideline makes this consistent and clear across all Delegates.

What do you think of adding something to the Guidelines about 8 hours?

**Comment by Laura-O** [comment]
Sorry, but 8 hours do not reflect the reality. I quickly checked the competitions next weekend: 17 out of 24 competitions have competition days >8 hours.

All 5 competitions I (co-)organized in the last 12 months fell in the >8 hours category. Saturdays are usually ~10 hours.
The reason for that is: competitors want to do as many attempts as possible. We regularly receive questions from competitors asking if we could add another round of event xy at the end of the day.

And apart from that, competitors do not relax and then go to bed right after a competition. They sit together, get something to eat and solve cubes. I agree that this is less stressful than a competition, but I do not think we are overstressing competitors with a >8 hours schedule.

**Comment by KitClement** [comment]
Agreed with Laura. I do think there's potentially some value in having a
guideline of what is an appropriate amount of time to be competing in one
day, as I get many requests from potential organizers that want to have one
day competitions from 8am-8pm. But 8 hours doesn't reflect reality. Maybe a
guideline of no more than 10 hours of competition time would be more
realistic. Of course, organizers and delegates can agree to more when
planning a competition, but such a guideline may inform new
competitors/organizers of the usual length of competitions.

**Comment by AlexKatyukov** [comment]
OK, 10 hours. 
But, really, it is not normal, when competitions is really big. 
For guests and parents especially.

**Comment by AlbertoPdRF** [comment]
I don't think that this should be in the guidelines. For me, competitions that last up to 12 hours on Saturday is pretty normal, and I like it.

Also, what is normal depends on where you live and your habits: for example, in Poland is normal to start competitions at 8 (or sooner IIRC) in the morning, but if you ask in Spain, no one would like to start a competition at 8.
