### ISSUE TITLE
Regulation 2e) only forces delegates to verify citizenship

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/wca-regulations#432]
Regulation [2e)](https://www.worldcubeassociation.org/regulations/#2e):

> Competitors must represent a country of which they hold citizenship. The WCA Delegate should verify citizenship standing by means of documents (e.g. a passport). If a competitor is found ineligible to represent the country under which they have registered, the competitor may be disqualified retroactively and/or suspended, at the discretion of the WCA Board.

It's the only regulation that forces a delegate to check legal documents against registration data at the competition's registrations, and only for citizenship. I think we should include a more general regulation in [Article 2](https://www.worldcubeassociation.org/regulations/#article-2-competitors) to force delegates to check legal documents against all the registration data (name, dob, etc.).

What do you think?

**Comment by lgarron** [comment]
> that forces a delegate to check

Not even that, right? ("should")

I don't think we should create a strict Regulation if we don't expect Delegates to strictly enforce it, but I think it would be reasonable to add a stronger Guideline, e.g. checking all details for first-time competitors from other countries.

**Comment by AlbertoPdRF** [comment]
Yes, maybe "force" wasn't the best word to describe the situation :P 

Adding a strong guideline should be enough I think.

**Comment by AlbertoPdRF** [comment]
Maybe it's time to close this, as it didn't seem to raise a lot of attention :P 

If someone thinks that this is necessary, feel free to re-open it!

**Comment by SAuroux** [comment]
Maybe this just didn't raise so much attention because it is very non-controversial? I certainly think that adding a Guideline there would be a good idea. The WRT often tells delegates "you should always verify name, DOB and citizenship of all newcomers" and it would be great to have a clear Guideline as a reference for this statement.

**Comment by AlbertoPdRF** [comment]
Ok, I'm re-opening it and we'll see if we can come up with such a Guideline then :)
