### ISSUE TITLE
Change "WCA Board" to "WRC" on Regulation 11e3) 

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/wca-regulations#433]
Regulation [11e3)](https://www.worldcubeassociation.org/regulations/#11e3):

> If it is unclear whether an incident should result in an extra attempt, the competitor may be granted a provisional extra attempt that will be used only if it is later found that an extra attempt was appropriate (e.g. by a decision of the WCA Board).

Should we change "WCA Board" to "WRC"?

**Comment by garrett-webster** [comment]
I don't think so. If it gets to a point that a delegate can't make a ruling, then it's a big enough problem to send it to the board. The WRC could advise of course.

**Comment by AlbertoPdRF** [comment]
But it's the WRC who is deciding when to keep the original result or the provisional extra attempt.

**Comment by Laura-O** [comment]
Yes, that's a regulation that should have been changed when the WRC started to decide about incidents. That should definitely be changed.
Good catch! 👍

**Comment by AlbertoPdRF** [comment]
Fixed!
