### ISSUE TITLE
Places the cube can touch during a one-handed solve

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#435]
At the moment, it seems unclear whether or not the cube can touch certain places during an OH solve.

More specifically, I think it should be clarified if the cube can touch
a. parts of the timer
Guideline c1b+++ clearly states that the surface can be used. However, regulation 7f1d states that the timer is not part of the surface. The cube can easily touch the timer on release and I think this should be clarified in the regulation/guideline.

b. body parts other than your other hand
Regulation C1b appears to be ambiguous. The phrase "using only one hand" could refer to "not using any other part of the body other than the solving hand" or "not using the non-solving hand". If the second interpretation is used, I also think the wording of C1b3 should be changed to "contact with the other hand" to avoid confusion.

c. the floor (unintentionally)
Drops are more common for OH solves than normal ones and can result in the puzzle hitting the floor. I think this may need clarification.

Also, I think A6e might need revision, especially with OH. When stopping the timer after an OH solve, the cube may accidentally hit the non-solving hand after the timer has stopped. I think there should be a regulation under OH looking like the following:
> After the timer stops, if the competitor accidentally touches the puzzle with the non-solving hand when it is resting on the timer, no penalty should be applied.

Finally, for C1b3), I think dropping the cube by accident should also be considered, not just pops.

**Comment by Laura-O** [comment]
**Touching** the timer and **using** the timer are two different things. I don't see a problem here.
The same applies to the puzzle hitting the floor.

For b) I can actually not see the problem. "Only one hand" is "only one hand". Why would you want to add a negation here?
And yes, you are not allowed to use your chest, your legs or any other part of your body during OH.

**Comment by xsrvmy** [comment]
So what about the puzzle dropping on my body?

**Comment by pedrosino** [comment]
> So what about the puzzle dropping on my body?

That would be a DNF nonetheless.

**Comment by Laura-O** [comment]
This is currently discussed in #464.
