### ISSUE TITLE
Make clear that competitors MUST be divided into groups if you can't have all competing at once

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#437]
Given recent discussion about Virginia Open Spring 2017, this could be a "solution":

1h) Competitors in the same round of an event may be divided into groups.
    1h1) Competitors must be divided into groups if there is no way to have all competitors in a round to be in the same group (i. e. having all competing at the same time), to ensure that no competitor can watch others solving with the same scrambles they will attempt **_at a later group/time_**.
    1h2) (was 1h1)Scramblers and judges for a round should not scramble for/judge competitors in their own group before they have finished all of their attempts for the round. They may scramble for/judge competitors in their own group at the discretion of the WCA Delegate, but the organisation team must ensure that scramblers and judges cannot see any scramble sequences for their attempts that they have not attempted yet.

**Comment by pedrosino** [comment]
EDIT
add "at a later group" to the end of 1h1

**Comment by SAuroux** [comment]
Well, this formulation would prevent a very common way of 2-at-a-time podium finals, where the remaining participants are kept in a seperate room until their turn.

**Comment by Laura-O** [comment]
"At the same time" is vague. Are competitors waiting to do an attempt for 10 minutes competing at the same time? And what about podium finals?
In any case, is that really a common problem which should be explained in the regulations?
I don't think it is, so I think this should rather go into the delegate crash course (added that to my todo list).

Side note: we do not change the numbering of regulations to avoid confusion. Therefore, 1h1) should not be replaced.

**Comment by pedrosino** [comment]
> Well, this formulation would prevent a very common way of 2-at-a-time podium finals, where the remaining participants are kept in a seperate room until their turn.

We could change to wording to "...(i. e. having all competing at the same time or unable to see other competitors solving)".

I'm not sure this MUST be in the regulations, but it could be good if we could find a clear wording. I personally wouldn't mind having it at the crash course (with more detail and explanation) too, but maybe in the future someone will argue that the crash course is not regulation and must not be followed to the letter...

**Comment by Laura-O** [comment]
Well, yes, maybe. I could make a long list with "delegate mistakes", which are not clearly stated in the regulations.
However, there is a huge difference between regulations for competitors and regulations for delegates. We trust our delegates, so we should rather educate them instead of regulating them.

**Comment by AlbertoPdRF** [comment]
I also think that this would fit better on the Delegate's Crash Course than in the Regulations. As Laura already took note of this, I'm closing this issue.
