### ISSUE TITLE
Explicit rules about repairing lockups and center pops

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#440]
Right now, the only rule about putting pieces back into place in the regulations is

>5b3a) If any parts have fallen out or moved out of place, the competitor may place them back.

I see two problems here.

1. Can the competitor remove the piece that moved out of place and then put it back in the puzzle?
2. According to the current regulation, removing other pieces is not allowed when fixing lockups/pops. However, with certain bad lockups or center pops, the repair can be almost impossible without removing a wing piece, and sometimes there is the risk of a center piece breaking if the puzzle is not loose enough. I propose allowing the removal of 4 pieces to accommodate this.

**Comment by Laura-O** [comment]
This seems similar to what you asked in #455, closing this.
