### ISSUE TITLE
Recommending the use of an object to prevent to cube from sliding of the table

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#441]
I think there should be such a guideline to reduce the chance of a cube being thrown of the table at the end of a solve. The object just needs to be long and should not be tall.

**Comment by KitClement** [comment]
Such a recommendation would likely lead to inconsistencies. From my
experience, the vast majority of competitions have no such protection. It
should be the competitor's responsibility to end the attempt appropriately,
and having only some competitions with a stopping device would make
conditions less equal among competitions.

Admittedly, this is already an issue with o-rings, but those prevent issues
that shouldn't exist with better timers, and timekeeping isn't the
competitor's responsibility. Placing the puzzle on the mat after a solve is
the competitor's responsibility.

**Comment by lgarron** [comment]
> It
> should be the competitor's responsibility to end the attempt appropriately,
> and having only some competitions with a stopping device would make
> conditions less equal among competitions.

I agree with this. Dropping the highest solve gives room for occasional accidents in most events, but I don't believe it's a good idea to forgive the competitor for things that can be entirely within their control. Mats already have enough friction that a competitor can consistently rely on.
