### ISSUE TITLE
Placement of 3x3x3 Multi-Blind cubes

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/wca-regulations#444]
Right now, there's no Regulation allowing or forbidding to keep the scrambled cubes in MBLD in a shape that the competitor desires, so a change in the lines of "Puzzles must not be intentionally arranged in a way which gives the competitor an unfair advantage." will be made.

**Comment by akashrupela** [comment]
This is not fully clear to me: Does this mean 
1. the puzzles must be kept in the shape of a rectangle? 
2. the puzzles must be kept in any shape except which the competitor submits in?

I do not understand what kind of advantage do we treat as 'unfair'?

**Comment by lgarron** [comment]
I'm also worried that this is very had to define.

There is nothing that prevents competitors from using cubes of different sizes or textures (and such restrictions might make it impractical for some competitors to gather enough cubes – all other events require a single affordable puzzle), which would sort of be a loophole.

Can we ask multi blind cubers to tell us how advantageous a good layout of puzzles is?

**Comment by akashrupela** [comment]
I asked Shivam Bansal (WR 2) and these are his views:

> "It allows an advantage yes. Not a significant one (around 10-15 sec for me personally) and can vary from person to person depending on the number of cubes and their layout).
> 
> I can memo the first cube in less than 15 seconds on average so it might play a part after a certain speed but still it's not worth the problems it will impose. (preserving layouts)
> 
> I don't think it's against the spirit of mbld to allow cubes to be grouped according to the competitors wish if they are being scrambled on the solving table.
> 
> However many competitions submit cubes elsewhere and transport so asking and successfully delivering everyone's cubes in desired layout will be too much of a hassle and not feasible. 
> 
> So for consistency throughout the competitions I think something like "cubes must be placed by the scrambler in a shape as close to being a rectangle as possible with no gaps between cubes" could work. 
> 
> If the regulations are ok with leaving it to organisers to have it either way, thinking it's a less enough time that it doesn't make a difference then that's an option too.
> 
> I would also like to mention people like Gianfranco Huanqui who's layout is a vertical rectangle itself and mark boyanowski who takes a cube at a time from the pile and sets it in his layout after memorising it.
> 
> Also another notable point is that Maskow's world record had cubes grouped pretty precisely (and had same orientation but that's already settled) so this is an "advantage" that the WR had."

**Comment by Claster** [comment]
To me, that has zero advantage. I still need to take every cube in my hands, whether cubes are ordered in the groups of 8/10/whatever or lying randomly.

**Comment by pedrosino** [comment]
See #403 which is very similar.

I agree that "way which gives the competitor an unfair advantage" is close to impossible to define. I like the suggestion of making it as close as possible to a rectangle. This would need some guidelines, though. Do we arrange 20 cubes in 4 rows of 5 or 5 rows of 4? Or 2x10?

**Comment by lgarron** [comment]
If we want a standard arrangement, I propose "rows of 10, filled from front to back and left to right"
 (if there is an incomplete row, place it in the back left).

Easy to do correctly, and easy to check the arrangement against the number of cubes at a glance. (3 full rows + 7 in the back = 37 cubes.)
Also makes it easy for the competitor to take cubes starting with the row closest to them, and know which cube # they're on.

However, that doesn't address different cube sizes (or textures).

Edit: turns out that's also what I wrote at https://github.com/thewca/wca-regulations/issues/403 :-P

**Comment by Laura-O** [comment]
Making rows of 10 will not work. It will happen quite often that you can't fit them on a table or there's not much room left, which is especially bad when there are two competitors sitting at one table.

A classic school table with two seats is 120 cm and a line of 10 cubes is about 57 cm. If you don't want to put the cubes at the edge of the table and you add some additional space for a cover, the rows of two competitors nearly touch each other.
Furthermore, covers for long lines are difficult to find/make.

I think having a strict rule how cubes should be arranged will not work. Table sizes are different, so it will sometimes not be possible to make long lines and sometimes it will not be possible to have many rows (with tables like [this](https://youtu.be/BpWND8Ngd3c)). So we definitely need a flexible rule here which allows exceptions.

**Comment by KitClement** [comment]
The table isn't the only issue, the cube cover is too, I would think. For
those doing 40+ cube attempts, that would be quite a large cover needed.
Stacking cubes is almost a necessity for attempts that large, and forcing
those attempts to go flat on the table completely is rather hard, unless
multiple boxes/covers are used.

**Comment by lgarron** [comment]
What about specifying something that fits on our [definition of a full-size mat](https://www.worldcubeassociation.org/regulations/guidelines.html#7f1a+)?

Layers of 5 wide and 4 deep should fit.

**Comment by pedrosino** [comment]
I'm fine with 5 wide and 4 deep. Proposal:

> H1a3)** Before the attempt, the judge places the scrambled cubes on the table in an arbitrary orientation while ensuring that they remain completely covered. The cubes must be arranged in layers of at most 5 cubes wide (left to right) and 4 cubes deep (front to back***). (See Regulation A2e)

** I'm not entirely sure about placing it here, but I guess it makes since since H1a talks about stuff "before the attempt".
*** I personally would prefer back to front, but it's fine either way.

**Comment by Laura-O** [comment]
> H1a3)** Before the attempt, the judge places the scrambled cubes on the table in an arbitrary orientation while ensuring that they remain completely covered. 

I think explicitly mentioning "the judge" here is confusing. In MultiBLD it's often not the judge who places the cubes on the table, but a scrambler, the organizer or a delegate.

> The cubes must be arranged in layers of at most 5 cubes wide (left to right) and 4 cubes deep (front to back***). (See Regulation A2e)

Hm, this is not really specific. What happens if I attempt more than 20 cubes? I guess they should be stacked, so that should be added.
And do I have to fill this 5x4 shape first or can I also stack 3x3 squares?

**Comment by Claster** [comment]
Pedro, what do you mean by "front to back" or "back to front"? Do you want that cubes would be guaranteed to be scrambled in some fixed order? That is, the left front cube must be scrambled with the first scramble and so on?
`11 12 13 14 15`
`6  7  8 9 10`
`1 2 3 4 5`
`<competitor>`

To me, the idea of arranging cubes still seems like adding more pain to organizers without benefits or solving any problems.

**Comment by pedrosino** [comment]
No, I don't mean the order (from scrambles), but rather the order we fill the layers.

13 cubes can look like

x x x x x
x x x x x
x x x
competitor

or

x x x 
x x x x x
x x x x x
competitor

I personally prefer the 1st option (filling from back to front).

**Comment by lgarron** [comment]
> To me, the idea of arranging cubes still seems like adding more pain to organizers without benefits or solving any problems.

If we have sample images, I think a standard arrangement would make it easier to to teach new volunteers. "How do I do this?" "Make it look like this."

**Comment by pedrosino** [comment]
New attempt

>H1a3)** Before the attempt, the scrambled cubes **are placed** on the table in an arbitrary orientation while ensuring that they remain completely covered. The cubes must be arranged in layers, each consisting of rows of 5 cubes, up to 4 rows per layer. The rows must be filled from left to right (in the competitor's view) and from front to back (in the competitor's view) (See Regulation A2e)

**Comment by Laura-O** [comment]
In general, I like Pedro's proposal, but I think this should be a 'should"-regulation.
Some setups do not allow putting 5 cubes in a row or covers you want to use are not large enough. I think this regulation is not that essential, so I suggest this:

> H1a3)** Before the attempt, the scrambled cubes must be placed on the table in an arbitrary orientation while ensuring that they remain completely covered. The cubes should be arranged in layers, each consisting of rows of 5 cubes, up to 4 rows per layer. The rows must be filled from left to right (in the competitor's view) and from front to back (in the competitor's view) (See Regulation A2e)

**Comment by pedrosino** [comment]
The should sounds good enough to me.

**Comment by AlbertoPdRF** [comment]
Should sounds better than must to me also, although I'm not sure I'm convinced with @pedrosino's proposal. I would be happy with something that forbids arranging cubes in groups and says that the shape of all the cubes put together should be as squared as possible.
