### ISSUE TITLE
Confusing use of word "Stackmat" in regulation 7f1b

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#445]
The use of Stackmat can lead to the interpretation that the mat must be an official stackmat mat, but the previous regulation says any compatible mat can be used.

**Comment by Laura-O** [comment]
"Stackmat" is explained in [7f1a)](https://www.worldcubeassociation.org/regulations/#7f1a):
_Stackmat: The Speed Stacks Stackmat timer and a full-size compatible mat._

I think the term "a full-size compatible mat" makes it completely clear that any kind of mat can be used.
