### ISSUE TITLE
Implementation of the competitor limit

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#446]
Not all websites are handling competitor limits properly. For instance, on the cubingchina website, as long as the number of paided competitors is under the cap, anyone can click in, so more people end up on the list than there should be.

Also something needs to be done about people only registering for 3x3. Perhaps competitor limit per event?

**Comment by Laura-O** [comment]
Please contact the website owners, that's nothing the regulations can handle.

And surprise, surprise: we have a competitor limit per event:
_Z4) The organization team may limit the number of competitors per event or per competition, on either a "first come first serve" basis or based upon qualification results or rankings in the WCA world rankings of a previously announced calendar date._

**Comment by lgarron** [comment]
I agree with Laura.

> Not all websites are handling competitor limits properly. For instance, on the cubingchina website, as long as the number of paided competitors is under the cap, anyone can click in, so more people end up on the list than there should be.

In this case, competitors may not count as registered until they have paid,.
Per [2c1](https://www.worldcubeassociation.org/regulations/#2c1), it is totally  to continue to allow registrations until enough competitors have paid.

> Also something needs to be done about people only registering for 3x3. Perhaps competitor limit per event?

As Laura says, it's possible have a competitor limit per event. In any case, competitions have always balanced a lot of 3x3x3 competitors with advanced competitors in multiple events. But many people start with only 3x3x3 at their first competition. I don't think we should attempt to take any official action to prevent this – if anything, we should be especially welcoming to 3x3x3-only competitors.
(Note that competitions without 3x3x3 are possible, and regularly occur.)

**Comment by xsrvmy** [comment]
With the 3x3 thing I just meant like a lot of new competitors take up registration spots. But if event competitor limit is in the regulations then everything is already covered.
