### ISSUE TITLE
Changing results after they were signed?

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#452]
There is some inconsistency about this. Some results have been changed if the judge made a mistake while writing down the time and the competitor has proof.

I'm personally against this because we are being lenient with our own regulations:
>A7c) The judge and competitor must each check the recorded result, and sign (or initial) the score sheet to acknowledge that the result is correct, complete, properly formatted, and clearly readable. This finishes the attempt. 

If we say the competitor must check and sign to acknowledge, but we let them come up later with proof (video/photo/whatever) and change it, we are saying "you must check the time before signing, but if you didn't pay attention you may get it corrected - if you filmed yourself".

This is bad because it takes away responsibility from competitors, making them lazy to check, and also is not fair because not everyone is filming themselves the whole time.

That being said, I think a competitor contacting the results team saying their result is better than it should be is valid and should be encouraged. The opposite is not true, in my opinion.

I'm not sure if we need a regulation/guideline change, but a clear, consistent policy is necessary, I think.

**Comment by lgarron** [comment]
> I'm not sure if we need a regulation/guideline change, but a clear, consistent policy is necessary, I think.

So far, the Board and WRC have almost always preferred to change the result to the "correct" one whenever there is enough clear evidence that the initial result is incorrect. (But we can break with that precedent.)

**Comment by Laura-O** [comment]
I am against any kind of "if it's better, then..."-rules. That's a bad rule of thumb, which is very assumptive. The long version would be like "if you want a better result, we think you are lying. If you want a worse result you are telling the truth". That's just weird.

As @lgarron said, our aim is to have results which are correct and if there is enough proof that the initially entered result was wrong, we should accept this.

I doubt that this has any influence on the way people check their results. I can't remember the number of cases where we actually changed results although a different result was signed, but I don't think there were more than 10 in the last 12 months. That's an extremely low number compared to the number of attempts done in this period.

**Comment by pedrosino** [comment]
Maybe I'm a bit too legalistic :)

The reason we introduced competitor signing was to prevent wrong results being entered, but unfortunately the culture of checking results is not easy to enforce :(

**Comment by Laura-O** [comment]
> The reason we introduced competitor signing was to prevent wrong results being entered, but unfortunately the culture of checking results is not easy to enforce :(

No offense, but that sounds like complaining for the sake of it.
We do not know how many people do not properly check their results, but judging from the number which is found later (through videos or whatever) it is quite low. Just remember how many attempts are done every weekend and how many times we had this issue.

**Comment by pedrosino** [comment]
No offense taken. It was just a comment from my experience. I know a lot of people here don't check what is written and just sign.
The fact that we have a low number of changes later is probably because a small portion of people film themselves and check each video afterwards.
