### ISSUE TITLE
Changing possible formats for events?

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#453]
Following discussion about a recent case of 2x2 being held as Best of 1, Oleg said:

```
Currently it seems to be possible to have some weird cut-off formats like best of 3 / average of 5 for 3x3, or best of 1 / best of 3 for 3x3 bld.

How about the following?
1) For events from 9b1 only "avg 5" and "bo2 / avg2" are possible;
2) For events from 9b2 only "bo1", "bo2", "mean3" and "bo1 / mean3" are possible;
3) For events from 9b3 only "bo1", "bo2", "bo3" and "bo2 / bo3" are possible.

What could be valid reasons to use anything else?
```

about 1) I don't think we have any "avg2" format. I guess you mean "bo2 / avg5"
about 3) I would prefer "bo1 / bo3" if we did combined rounds limitations. See below

I don't see a problem with the regulations allowing different formats for each event, and also regulating how combined rounds must be can get complicated.

I think there may be valid reasons to hold best of X instead of Avg of 5 for some "popular" events. Not that I like the best of 1 for 2x2, for many reasons :P 

(EDITED because my numbering was changed automatically to 1) and 2) instead of the desired 1) and 3)

**Comment by Laura-O** [comment]
As I already mentioned in the discussion thread: the best way to deal with that is probably to define the standard formats (the ones Oleg listed/with Pedro's correction) and allow all others combinations with Board approval.

I don't have an example, but there might be reasons to have a different format, so we should leave this backdoor open.
