### ISSUE TITLE
Final scrambles for Blindfolded

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#454]
Walker brought up an interesting point to me today -- during his final 4BLD solve, he gave up in the middle of execution, with corners left untouched from the original scramble. Not that this was his intent, but he realized later that his 4x4 was carrying partial scramble information, and one could use it to determine the corner memo for that scramble, and many competitors were yet to be called for the third scramble.

To prevent a potentially malicious competitor from ending their solve early to share scramble information, I propose adding this regulation: (wording is rough)

B5d) Competitors with a DNF result must solve their cube before leaving the competition area. 

I had thought about using a conditional with it being their final attempt, but many competitions will schedule attempts individually rather than have them all in one period. In the case where it's not a competitor's last attempt, they would normally just sit and solve their cube for the next attempt anyways, and we clearly don't want them walking out of the competition area without that cube.

**Comment by Claster** [comment]
Interesting idea, but what would be the penalty for not solving?

In some cases that seems to be unnecessary (e.g. the competitor is the last, or everybody else had started their last attempt), so requiring always to solve the cube sounds a bit bureaucratically.

**Comment by KitClement** [comment]
Yeah, of course, this would be nothing more than a procedural regulation,
can't penalize after the fact. I think it would be a nice reminder to
include though, as I think it's a relatively easy way to cheat that some
may not consider.

**Comment by kingmathyall** [comment]
I think you could have the competitor solve or sufficiently scramble the puzzle (might be quicker) before leaving the competitor area.

As for the "unnecessary" comment, with the regulation involved with not discussing the scrambles, if everybody has finished all their solves except for one person, they could potentially still discuss them even though they are the last person, so I don't think having this as a regulation would make it an issue of any sorts, it'd just sorta be protocol for the competitor's last solve.

As for a penalty if they don't do this could be disqualification from the rest of the competition even though I think that might be too harsh, I'm not sure what could be done.

**Comment by lgarron** [comment]
> As for a penalty if they don't do this could be disqualification from the rest of the competition even though I think that might be too harsh, I'm not sure what could be done.

I think this is definitely too harsh. We should also avoid adding penalties we don't really need.
Ideally we should just make it the judge's responsibility and focus on (the big problem of) training judges?

**Comment by Laura-O** [comment]
> Ideally we should just make it the judge's responsibility and focus on (the big problem of) training judges?

I think that's self-contradictory: if we want to focus on training judges, adding more responsibilities does not make that easier.

I see the problem of this issue, but I am not sure that we can handle this with adding a regulation. As already mentioned by Oleg, there would be no penalty and I think it's also difficult to monitor in some situations.

**Comment by kingmathyall** [comment]
How about adding a Recommendation along the lines of:

During blindfolded solving, if an attempt ends in a DNF, the competitor should solve or sufficiently scramble the puzzle before leaving the competitor area

I'm not sure where this would go and what regulation this would be in reference to. Any thouguhts?

**Comment by Mollerz** [comment]
What about a recommendation that states that after the competitor signs for any attempt in BLD, the cubes must be solved before leaving the timing station in a new section "B6) After the solve:"? - B6a) After an attempt has been signed for, the cube must be solved before the competitor leaves the timing station.
