### ISSUE TITLE
Remove partially misplaced piece from the puzzle

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#455]
Regulations current only allows one immediate repair: putting a piece back in place. On some defects where a piece gets stuck between two layers, the piece must be removed first, or will pop out during the repair. Should this be explicit in the regulations?

Something like this can do:

If a piece moves out of place, the competitor may remove the piece from the puzzle, and optionally place it back in.

**Comment by Laura-O** [comment]
Maybe I misunderstand your description, but I think the regulations already take care of that:

_5a) Examples of puzzle defects include: popped parts, pieces twisted in place, and detached screws/caps/stickers.
5b) If a puzzle defect occurs during an attempt, the competitor may choose to either repair the defect and continue the attempt, or to stop the attempt._

These regulations do not exclude misplaced pieces. If there is something I am missing or you were talking about different regulations, please quote them here to make your intention clearer.

**Comment by xsrvmy** [comment]
I was referencing 5b3 about permitted repairs. What happens if a piece that is jammed inside falls out when attempting a repair?

**Comment by Laura-O** [comment]
Then it's part of the puzzle defect and can be repaired as well. Sorry, but I still don't get the point how this should not be a legal repair.

**Comment by xsrvmy** [comment]
I think I probably misread the intention of this regulation.
