### ISSUE TITLE
Is article D1a necessary?

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#459]
> D1a) During the attempt, the competitor must sit in a chair, sit on the surface, or stand.

I feel this is somewhat unnecessary. We don't say anything about regular Speed Solving, and I can't see a problem if the competitor wants to lie down on the floor and look at the cube between the legs.

Also, "sit **_in_** a chair" may be wrong (correct would be "on")

**Comment by Laura-O** [comment]
Having a clear definition what is allowed is usually better than having no definition. The three options mentioned in D1a) also guarantee that the judge is able to see the solve and the puzzle. If someone would solve in a push-up position or doing a handstand on the mat that wouldn't be possible.

And I am not a native speaker, but Google told me that you can also sit in a chair. ;-)

**Comment by jfly** [comment]
Apologies for English, but "sit in the chair" and "sit on the chair" both sound fine to me.
