### ISSUE TITLE
Allow some age information to be released

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#46]
http://www.speedsolving.com/forum/showthread.php?42842-Should-WCA-Bring-Back-Age-Statistics

My post from that thread:

---

I'm mostly the person responsible for the push to ensure that competitor birthdates are completely private, after several years of inconsistency. The only concrete thing I ever found someone tell me is that birthdates were being collected solely to tell apart competitors with the same names, but clearly we weren't adhering to that.

The issue basically comes down to this:

> [Originally Posted by sneaklyfox]
> Birthdates are used for things like ID, credit cards, other security type things. And some people just don't want their ages made public for the world.

We have birth data from a lot of countries, where competitors might have various expectations about how data is used.
At the very least, I will always argue against publishing data "in mass", e.g. putting birthdates on WCA profiles. Listing the age as a year isn't much better, because it still reveals some information, and it's possible to find out ages by checking pages every day to see when the age increases.

As a comparison, consider Facebook. Even with their usual disregard for privacy defaults, they help you keep your age private, and generally only show your birth month+day to your friends.
_Unfortunately_, the useful statistics for the WCA are the other way around: comparisons are interesting when you know the age, and the day of the year doesn't tell you much.

Now, there's no reason this policy couldn't change.
I think the most reasonable approach is to publish ages only when we have the competitor's explicit consent , and with a specific license to use it for e.g. age statistics (rather than a free "the WCA can publish it how they want"). That way, young/old competitors who care about age statistics can be visible on them. We could also ask organizers to contact competitors privately, saying "you would be on this record page, do you give us permission to display your name and age?"

But any decent proposal should address a few things:
- We have birthdates of competitors who may never compete again, who have not given consent for their age may be published, and quite possibly expect it to be private
- This policy either be opt-in, or very clear when a competitor registers.
- It shouldn't be too much of a logistical burden on competitors, organizers, and the WCA website team.
- Unlike sports with age divisions, there's no fundamental _need_ for us to have birthdates in order to operate. So we should be clear to competitors about what it means to give their birthdate.

I think the simplest solution _if we had accounts on the WCA website_ would be to make his a preference that can be selected during registration, with a specific and positively worded "do you allow us to publish your age for X, Y, and Z?" checkbox.

If people like age statistics, discussion is welcome. However, we need a concrete proposal for any changes. Preferably one that doesn't assume that competitors would like their ages to be published by default (even only some competitors, in statistics).

**Comment by iVinshe** [comment]
I saw this. I think that unless someone really does come up with a serious
proposal (and defends it with citations), we should table it for now.

**Comment by lgarron** [comment]
Given that several older competitors want it back [solely for age statistics](https://www.speedsolving.com/forum/showthread.php?42842-Should-WCA-Bring-Back-Age-Statistics&p=1037930&viewfull=1#post1037930), I think it's fine to display some limited statistics for competitors who have opted in.

Concerns:
- This requires action from the WCA website team. In particular, the only good way to implement this is with user accounts.
- We should be careful to publish statistics only on competitors who have opted in.
- We should still not publish birthdates on profiles, given that people are specifically interested in statistics.
- Parents who push their young children to compete.

**Comment by Laura-O** [comment]
So this was recently discussed again. As publishing age information is legally complicated, the Board was asked to figure out what we can or should do.

**Comment by theoleinad** [comment]
How about adding a policy that states that starting 2020, all competitors that compete, will grant WCA the permit to use their DOB to provide "Age Statistics" without the intention to harm or spread their DOB information. 
This way we could  prevent the extra effort for the WCA website team. 
If by any chance the competitor do not agree or want to "block" that information, they can send an email or request to their Delegate.

**Comment by UnderwaterCuber** [comment]
I would try and stay away from age statistics to avoid any potential legal complications. If you really do want age statistics then I think 3 things are a must.

1. competitors must be aware of exactly what their age is going to be used for
2. competitors must opt-in for age statistics
3. competitors can opt-out of age statistics at any time they would like to do so

**Comment by Jambrose777** [comment]
This is something the WDPC should handle if it is the direction WCA is going (which is also something the WDPC would look into and decide)
