### ISSUE TITLE
D1b being vague

### ISSUE THREAD

**Issue by a-Maass** [thewca/wca-regulations#460]
D1b) During the attempt, the competitor must use only their feet and the surface to manipulate the puzzle. Penalty: disqualification of the attempt (DNF).

apparently I've heard of a few cases where the delegate thought that this didn't prohibit inspecting the cube with your hands, which seems false to me, I think this regulation should be rewritten to make it clear that you DO NOT use your hands for feet inspection

**Comment by Randomno** [comment]
I don't think it's vague, it's just that a lot of people don't know what an attempt is and how it differs from a solve.

Definitely worth clarification/reminder in Guidelines, considering there's one for 2H inspection in OH

**Comment by lgarron** [comment]
We're currently discussing this in a WRC email thread. My suggestion was to add a Guideline:

> D1b++) The competitor must not touch the puzzle with any part of their body other than their feet.

**Comment by Laura-O** [comment]
Another solution would be to allow inspecting with hands.

- We already allow using both hands in OH inspection, so using both hands in feet would be consistent.
- It removes confusion, DNFs and general regulation violations.
- Although inspection with hands is easier, I am not sure if that's really a large advantage. It probably takes 2-3 seconds to take the cube and put it back, so you have less "pure" inspection time.
