### ISSUE TITLE
Regulation B2c does not make sense

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#463]
Regulation B3c states: The competitor must have no physical contact with the puzzle before the start of the attempt. The penalty associated with this is a plus 2. Should this be a DNF, since the competitor almost certainly saw the puzzle?

**Comment by Laura-O** [comment]
> Regulation B3c states: The competitor must have no physical contact with the puzzle before the start of the attempt.

It doesn't. You are referring to [B2c](https://www.worldcubeassociation.org/regulations/#B2c).

B2c is basically the equivalent of [A4b1](https://www.worldcubeassociation.org/regulations/#A4b1) in speedsolving events. Competitors could arrange the cover in a way that they are already touching the cube, but have not completely lifted the cover yet.
And of course, if the competitor lifts the cover before starting the attempt (and therefore sees the puzzle), it should be a DNF.
