### ISSUE TITLE
C1b should be more specific

### ISSUE THREAD

**Issue by Mollerz** [thewca/wca-regulations#465]
[C1b](https://www.worldcubeassociation.org/regulations/#C1b) is a bit open for interpretation. I would prefer to make the regulation more specific in regards to touching the cube with other parts of the body during the attempt. I recommend a change to the following:

C1b) During the solve, the puzzle must only have contact with one hand and the surface. Penalty: disqualification of the attempt (DNF).

This means if it is dropped in the lap, or touches any other part of the body, then it is a DNF by default, whether or not the touch was intentional or not.

**Comment by Laura-O** [comment]
This topic is currently discussed in #464. I am closing this topic to avoid parallel discussions.
