### ISSUE TITLE
Reword regulation 2g3

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#468]
It would appear that regulation 2g3 prevents competitors from discussing scrambles for the current round that are no longer in use, for example due to multiple heats in the same round. The other problem is with FMC, where a competitor could technically be disqualified for talking about the first scramble after finishing the second attempt.

**Comment by Laura-O** [comment]
_2g3) Competitors **in the Competitors Area** must not communicate with each other about the scrambled states of the puzzles of the round in progress. Penalty: disqualification of the competitor from the event, at the discretion of the WCA Delegate._

2g3 is about communication in the Competitors Area, which is the area where competitors are waiting before they are called to compete.

It's completely fine that competitors in this area are not allowed to talk about any scrambles of the round in progress. Competitors often do not know how scramble sets are assigned to groups and if all competitors in a group have finished their attempts, so it's reasonable to have a rule for the whole round.

For FMC there is not competitors area. Therefore, this regulation cannot be applied for FMC.

**Comment by xsrvmy** [comment]
oops. missed that
