### ISSUE TITLE
Adding stricter regulations for managing registrations

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#469]
Because of reoccurring issues with competitor limits and the handling of waiting lists, I propose to add the following restrictions to the regulations:

- If there is a competitor limit and the competitor limit was reached before the competition, on-site registrations are not allowed.
- Competitor limits can only be changed with Board approval and only for a legitimate reason (e.g., when the venue was changed).
- Registrations may not be opened again once they were closed.

**Comment by Jambrose777** [comment]
Could you elaborate on what bullet 3 means?

**Comment by Laura-O** [comment]
> Could you elaborate on what bullet 3 means?

If the organizer decides to close the registration (so nobody is able to register anymore), the registration may not be opened again.

So to give an example of a situation that would be forbidden with this regulation:
* Competition with a competitor limit of 90
* The organizer decides to close the registration after 90 people registered (80 approved, 10 on the waiting list) and writes an announcement on the competition website.
* The organizer gets several emails with complaints by people who would have liked to register but were too late.
* One week later he decides that it might have been too early to close the registration and opens it again. He sents a reply to all the people who complained so they get another chance to register.

This is an unfair situation for everyone who did not complain about the closed registration. Furthermore, re-opening registration could even be abused to give friends an exclusive chance to register.

Thinking a bit more about it, we probably should also make this "Board approval only".

**Comment by Jambrose777** [comment]
Thanks for the clarification! Maybe change "registrations" to be "the registration period".

I often set a registration close time to be 1 week before the cometition. However, if registration is not full and the organization team is okay with handling the competition work at an expedited rate, we often extend this registration period to being open a few extra days. This is done before registration ever closes.

I think that this type of senario is fair and wouldn't be susceptible to abuse, but it might be beneficial to still have the board oversee such changes.

**Comment by Luis-J-Ianez** [comment]
Yes, I would leave some door open for special cases in the third point.

**Comment by xsrvmy** [comment]
The wording of the third point seems to be against how China handles people dropping out. In China, there is a second registration after the dropout deadline to fill up the remaining spots.

**Comment by Claster** [comment]
But what is the reason for this? Does the second registration happen during the competition itself or earlier?

**Comment by xsrvmy** [comment]
The second registration period happens before the competition. It replaces the waiting list that most other places have.

**Comment by Laura-O** [comment]
How can a registration period *replace* a waiting list? Can you please describe the whole process?

Maybe @Baiqiang can also help here?

**Comment by xsrvmy** [comment]
I heard the idea is that no one know who will get the spot they give up so there are no scandals. It's just a different way to fill up the registration cap.

On a sidenote, will registration overflows be considered a legitimate reason for changing a competitor limit (like ending up with 44 people more than the cap on the registration website)?

**Comment by Laura-O** [comment]
Ok, this doesn't really answer how the complete process looks like.
I will send an email to the Chinese delegates and ask them if they can help us.

**Comment by viroulep** [comment]
I strongly support adding the first two bullets.
Right now we handle the first point by reminding the organizers and Delegates to clearly state if on-site registrations are possible or not, so we may as well enforce it by making it a Regulation.
