### ISSUE TITLE
9a1: What are "Rubik's puzzles"?

### ISSUE THREAD

**Issue by jfly** [thewca/wca-regulations#484]
Regulations [9a1](https://www.worldcubeassociation.org/regulations/#9a1) says:

> 9a) The WCA governs competitions for: 9a1) Puzzles known as Rubik's puzzles.

What are "Rubik's puzzles"? There are a number of puzzles/toys out there that have "Rubik" in the name that are not actually governed by the WCA, such as: magic, master magic, snake, and probably other things I don't know about. Do we think this regulation actually has any value as it currently is?

**Comment by Laura-O** [comment]
Good point!

To fix this we could summarise both bullets in 9a:  _The WCA governs competitions fo puzzles that are manipulated by twisting the sides, commonly known as "twisty puzzles"_

The mission of the WCA is pretty similar btw: "_The World Cube Association governs competitions for all puzzles labelled as Rubik puzzles, and all other puzzles that are played by twisting the sides, so-called 'twisty puzzles'_.

**Comment by jfly** [comment]
Oh wow! I had no memory of "Rubik puzzles" being in the mission.

In fact, if you look at [WCA Motion: 1.2017.1 - Spirit and Mission](https://docs.google.com/document/d/1VHGJHFYA5QM31_aPExRavzfWFqmI-Jn0a3jxWHoUS9A/edit), you'll see that the mission of the WCA is simply "The Mission of the World Cube Association is to have more competitions in more countries with more people and more fun, under fair and equal conditions.". Our website is apparently out of date here: https://www.worldcubeassociation.org/about, because it has a 4 paragraph mission with a "goal" and a "spirit". I'll ping @pedrosino to ask him to take a look as a Board member.

As something of an aside, it's kind of annoying that our mission on the website talks about "Rubik Puzzles", and our regulations talk about "Rubik's Puzzles". At the very least, we should make them consistent with each other.

**Comment by pedrosino** [comment]
I believe we should replaced all mentions to Rubik's in the regulations and other documents.

We currently have a lot of them:

>9a) The WCA governs competitions for:
>__9a1) Puzzles known as **Rubik's** puzzles.
>__9a2) Other puzzles that are manipulated by twisting the sides, commonly known as "twisty puzzles".
>9b) The official puzzles and event formats of the WCA are:
>__9b1) **Rubik's Cube**, 2x2x2 Cube, 4x4x4 Cube, 5x5x5 Cube, Clock, Megaminx, Pyraminx, Square-1, Skewb, and **Rubik's Cube: One-Handed**.
>____9b1a) Round formats for these events are: "Best of X" (where X is 1, 2, or 3), and "Average of 5".
>__9b2) **Rubik's Cube**: With Feet, Rubik's Cube: Fewest Moves, 6x6x6 Cube, and 7x7x7 Cube.
>____9b2a) Round formats for these events are: "Best of X" (where X is 1 or 2) and "Mean of 3".
>__9b3) **Rubik's Cube**: Blindfolded, 4x4x4 Cube: Blindfolded, 5x5x5 Cube: Blindfolded, and **Rubik's Cube**: Multiple Blindfolded.
>____9b3a) Round formats for these events are: "Best of X" (where X is 1, 2, or 3).
>____9b3b) For **Rubik's Cube**: Blindfolded, the WCA also recognizes "Mean of 3" rankings and records based on the times from "Best of 3" rounds.
>
>(...)
>
>E3b) **Rubik's Cubes** (at most 3, self-supplied), as described in Article 3.
```

**Comment by Laura-O** [comment]
Well, we just recently discussed the event names and decided the "Rubik's" should be kept, didn't we?

**Comment by pedrosino** [comment]
> Well, we just recently discussed the event names and decided the "Rubik's" should be kept, didn't we?

Actually we kept Rubik's only for Rubik's Cube. All others have just 3x3x3. 
See https://www.worldcubeassociation.org/results/events.php and https://www.worldcubeassociation.org/competitions/GuilinOpen2017 for one example

**Comment by lgarron** [comment]
> To fix this we could summarise both bullets in 9a: The WCA governs competitions fo puzzles that are manipulated by twisting the sides, commonly known as "twisty puzzles"

+1, although it would make me happy if we pick a better word than "manipulated" (e.g. "operated"). I offer:

*The WCA governs competitions for mechanical puzzles that are operated by twisting groups of pieces, commonly known as "twisty puzzles".*

**Comment by Laura-O** [comment]
> Actually we kept Rubik's only for Rubik's Cube. All others have just 3x3x3.

Yes, sure. We already have this in #405 (I just changed the title as it was incomplete).

**Comment by jfly** [comment]
Thanks guys! I've pinged @pedrosino about updating our [/about](https://www.worldcubeassociation.org/about) page.

Is there any language in our bylaws potentially referring to "Rubik's puzzles" that should be updated as well?
