### ISSUE TITLE
[Suggestion] New Idea for Proximity Policy

### ISSUE THREAD

**Issue by Z4chy** [thewca/wca-regulations#519]
So we all know of the 100km/19 days policy, which prevents competitions from being too close in proximity. However, this deprives competitors in highly dense areas (such as the northeast), from competing, where competitions fill up within minutes. 

I don't take credit for this idea, a delegate in my area suggested something similar. The idea was to remove the proximity policy, but allow competitors to only go to one competition, per 100km, per 19 days. This would essentially leave the amount of chances a single competitor gets to compete unaltered, while it would also allow more competitors to participate. 

Let me know what you think of the idea.

Thanks,

Zachary (2013ZWER01)

**Comment by AlbertoPdRF** [comment]
This doesn't fall on the scope of the WRC, so I'm closing this issue.

FYI: the WCA is already aware of this proposal.
