### ISSUE TITLE
DNF when more than N pieces have popped out?

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#52]
Article 5 states that popped pieces is an examples of a puzzle defect, and that they can be repaired if the competitor chooses to. The competitor is not supposed to repair it in a manner that gives an advantage in solving it, but if too many pieces are being repaired, it's hard to judge what they're doing, and whether they're making it easier for him to solve. Where should we draw the line for how many pieces is too much to repair?

**Comment by pedrosino** [comment]
I don't think someone should be forbidden to repair the puzzle if "too many" pieces fall out.
Imagine a mean of 3 event, where each solve counts for the average. If someone has 10 pieces falling out, they probably want to try to fix it before giving up on the average.

And as you said, it's really hard to judge if what they're doing makes it easier, so we should give them the benefit of doubt here.

**Comment by sarahstrong314** [comment]
I don't think 10 pieces on a 6x6x6 or 7x7x7 is a big deal, but if more than half of the puzzle falls apart? I don't think they should be allowed to repair it and be given the benefit of the doubt when too many pieces fall out.

**Comment by shelchang** [comment]
For most speedsolvers, actually solving the puzzle is much more efficient
than trying to reassemble in a certain order, especially if there are a lot
of pieces and they're all scattered, so I can see giving them the benefit
of the doubt.

**Comment by Laura-O** [comment]
I think [5b2](https://www.worldcubeassociation.org/regulations/#5b2) is enough to handle those case.

We cannot ask judges to learn how many pieces are OK for each puzzle. Also, it is difficult to count how many pieces actually popped - what if the judge is unsure if there were 9 or 10?
