### ISSUE TITLE
Multi-BLD and illegal puzzles

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#521]
It appears that with the new edits to the regulations, a single illegal puzzle used in a multiblind attempt can cause the entire attempt to be DNFed. Also, regulation H1a1 may cause problems if submitted puzzles have been declined. Therefore, I propose the following so that only puzzles in question are affected. (Wording probably need changing)

* If a puzzle is found to be illegal during or after the attempt, that puzzle is considered to be unsolved.
* If it is unknown whether the illegal puzzle is originally solved, a penalty of 1 solved cube (2 points) is applied to the attempt (which may result in a DNF).
* If a puzzle is found to be illegal before the attempt, the competitor must replace it (per regulation H1a1). Penalty: The cube will count as an unsolved cube. If more than half the puzzles fail to be replaced, the result is an immediate DNF

**Comment by Laura-O** [comment]
I can't see the difference between MultiBLD and any other BLD event: the competitor is always responsible for submitting legal hardware. I don't think it would be fair to create an exception for one BLD event.

**Comment by xsrvmy** [comment]
I'm thinking along the lines of a malicious competitor seeking to win by DNFing large attempts by finding one (barely) illegal puzzle

**Comment by Claster** [comment]
The question is, if one cube found to be illegal, would the whole attempt be disqualified, or only one cube be considered unsolved?
