### ISSUE TITLE
New regulation suggestion regarding solving stations 

### ISSUE THREAD

**Issue by SpeedCuber71** [thewca/wca-regulations#525]
Hello, I'm Alaik Bhatia (2014BHAT09) from India and i had a small suggestion that my or may not be pplicable but i wanted to share it regardless. I wanted to suggest there being a regulation for chair heights relative to the solving tables at competitions. The reason i suggest this is because often t cubing competitions, me and a bunch of other competitors have to find extra chairs (which is sometimes not available) or borrow a judge's chair (maybe even another chair making the total 3) to pile it on top of ours in order to be able to solve properly. Its very difficult/uncomfortable to solve well with what is provided which often leads to unsatisfactory results and not being able to solve/ look ahead.  It is more of a hassle when the competitions use a runner system and every solve is at a different table. This is just a suggestion from me and i would love to hear your thoughts on this.
Also, i love all the new regulations/ changed regulations added today :D 
Thank you.

**Comment by hagmer** [comment]
I like to sit higher up than most people so i always fold one of my legs to sit on in comp. At home i use a pillow to get higher cuz sitting on one of your legs for more than 10 minutes gets really umcomfortable, but in comp it works perfectly fine.

**Comment by Laura-O** [comment]
It's difficult to implement such a regulation as it is a) sometimes difficult to find out before a competition, b) difficult to fix and c) defining penalties/consequences is impossible.
I mean, what would you do if you find out that the tables do not meet the requirements on a competition day? Cancel the competition and send everyone home?

I'd rather suggest you bring a pillow or, as suggested before, sit on your leg during your solves.

Therefore, I'm closing this issue. Thanks for your nice words regarding the regulation changes. 😄

**Comment by SpeedCuber71** [comment]
Thank you. What you said is correct. I was looking for ways to ensure the
solving stations are good, relative heights is difficult to do, yes. I hope
there is another way to deal with this but I will definitely try sitting on
one leg. Thank you for the advice! :)
