### ISSUE TITLE
3j3 and internal differences

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#526]
Does regulation 3j3 forbid old designs on which the inside of the pieces can technically be used to tell orientation? Specifically, were there no legal 5x5s before stickerless ones came out?
Another similar one is the yuxin little magic 3x3. There are dots on the edges which are exposed on a 45 degree turn, but the dots are sometimes on the same side and sometimes on different sides.

**Comment by Laura-O** [comment]
I don't understand the question regarding legal 5x5s. Can you please provide a concrete example and include a photo?
Same for the Yuxin Little Magic: I found [this](https://thecubicle.us/images/yuxinmagic3x3pre4.jpg), but I can't see any dots on the edges.

And once more: can you please stop creating GitHub issues for simple questions you want to ask?
The purpose of this GitHub repository is to collect concrete issues with regulations (like inconsistencies, loopholes, etc.) or propose improvements. You can always contact us via regulations@worldcubeassociation.org if you just have a question about the application of a regulation.

**Comment by xsrvmy** [comment]
About the 5x5: I was talking about the asymmetry in the design of some non-stickerless corners. On stickerless cubes, an unstickered corner looks the same on all three sides. On a non-stickerless, sometimes there is a cap on the inside of the corner, and the competitor can potentially figure out the orientation of a corner by running his fingernail along the inside of pieces.
