### ISSUE TITLE
Timer: specification / certification system

### ISSUE THREAD

**Issue by ldez** [thewca/wca-regulations#529]
> 8a7) Use the authentic Speed Stacks Stackmat timer (Generation 2, Generation 3 Pro Timer, or Generation 4 Pro Timer) for time measurement.

In order to allow more innovations, it would be interesting to define the expected standards (latency, precision, display, ...) by the timers rather than referring to a specific brand and specific products.

It would also require the definition of a timers certification system, and create a list of approved products.

It would be nice to see obsolete technologies disappear, such as:
- [RS-232](https://en.wikipedia.org/wiki/RS-232)
- 2.5mm communication port

And to see "new" technologies:
- Ethernet port, USB port, Bluetooth, Wifi
- timer server for competition
- fingerprint signature
- etc.

PS: Have the regulation on GitHub is awesome!

**Comment by tristaaan** [comment]
> In order to allow more innovations, it would be interesting to define the expected standards (latency, precision, display, ...) by the timers rather than referring to a specific brand and specific products.

I totally agree with this and I think a lot of people would like to use something different from speedstacks. However [the patent](https://www.google.com/patents/WO2003107013A2?cl=en) for the timers is rather broad, it would be difficult and potentially litigious to make a timer that retains the key features the current timers have. I believe it expires in 2023 (20 years from filing date?) so it would definitely be something to explore by then?

For now, there are some projects out there tackling alternatives to the 90 USD audience display, and that's where I believe this issue goes out of scope of the regulations committee.

**Comment by Laura-O** [comment]
I definitely support your thoughts @ldez. However, I don't think this will help us now. It would be awesome to have a "WCA official timer" or a list of "Approved timers", but it's unlikely that this will happen in the next 10 years for several reasons (especially money, but also time). If you are interested in working on this, writing done some standards, testing them, etc. you are welcome to do that, but I doubt it will influence the use of Speed Stacks timers anytime soon.

The reason why we use Speed Stacks timers is that they are available everywhere, they are reliable (yes, not always in terms of quality, but I think at least in terms of accuracy) and for that reason using them guarantees some worldwide fairness. Additionally, timers are comparably cheap, especially with the discount the WCA gets, so I don't think it will be possible to develop, test and produce cheaper timers.

**Comment by ldez** [comment]
I think a first step can be:
- to replace the term "Speed Stacks Stackmat timer" by "WCA approved timer"
- to add an appendix with the list of approved timers (from Speed Stacks) 

This don't really change the regulation, it's just more open to the future 😃.

**Comment by lgarron** [comment]
> I think a first step can be:
> 
> to replace the term "Speed Stacks Stackmat timer" by "WCA approved timer"
> to add an appendix with the list of approved timers (from Speed Stacks)
> This don't really change the regulation, it's just more open to the future 😃.

I agree with Laura that this is not a priority, but it's not a bad approach. We basically do this with the scramble program and list of citizenship countries already.

**Comment by J-Rohault-dF** [comment]
The question becomes more important with MoYu timers now.

**Comment by lgarron** [comment]
> The question becomes more important with MoYu timers now.

Is there demand for MoYu timers from organizers or competitors?

**Comment by J-Rohault-dF** [comment]
Looking at the prices for a few timers:

- Speedstack Stackmat: $32
- YuXin: $15
- QJ: $13
- MoYu: $11

If they are allowed, other brands' timers could have demand!

Also: even if only Speedstack Stackmats are allowed by the regulations, is it allowed to connect that to other brands' displays?

**Comment by lgarron** [comment]
> is it allowed to connect that to other brands' displays?

Yes.

If we're going to start allowing other timers, I would *strongly* prefer to use this opportunity to work with manufacturers on a better standard, e.g. one that:

- is free and open to implement and use like RS-232
- supports much lower latency to the display
- supports higher time resolution on the display
- is compatible with future innovation for digital time entry, without 1) baking too many assumptions into the hardware, or 2) including an IoT software stack that we can't be confident will be secure and maintainable (or at least possible to disable).

I think any hardware we approve initially should also have a port that is compatible for RS-232, in order to allow a gradual transition of hardware and to allow old and new sets of timers to be used together (whether planned, or in an emergency situation where old hardware was not expected to be used).

If someone with contacts to manufacturers is interested in working on this, I'd be happy to work through such requirements.

**Comment by ldez** [comment]
@Ivan-Brigidano could you explain why you closed this issue?

**Comment by ldez** [comment]
Maybe it's related to #973 :thinking:

**Comment by Ivan-Brigidano** [comment]
> Maybe it's related to #973 🤔

That's it. There is already a post [there](https://forum.worldcubeassociation.org/t/looking-for-timing-alternatives/3199).
