### ISSUE TITLE
Blindfolded Solving: No Solving Behind Back?

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#53]
B4c3 does not prevent a cuber to use his body is as the object between him and the cube, during the blindfolded phase, if he and the judge agree beforehand. While B4c implies that the cube must be in front of the solver, it should probably be explicitely written that the cube must be solved in front of the cuber's body

**Comment by lgarron** [comment]
I don't think we need to forbid "behind the back" explicitly. We could clarify that the competitor's torso is not a "suitable object", but I don't think anyone has tried to do it, and I don't think a delegate would usually consider it reasonable. Not that this rule is a bad idea, but it just adds one more thing to make the Regulations longer without addressing a problem that we really anticipate (although you're free to argue that we should anticipate it).

**Comment by timhabermaas** [comment]
While there's currently a discussion going on about adding an exception to [B5c](https://www.worldcubeassociation.org/regulations/#B5c), I came across this issue. You can't really solve a cube behind your back in a natural way without violating B5c, can you? You either need to stop the timer behind your back or drop the cube behind your back and turn around.

**Comment by shelchang** [comment]
Bring the cube in front of you, stop timer, remove blindfold? I would think
the blindfold is still required when solving behind the back, or else the
competitor could potentially obtain information to help him.

**Comment by timhabermaas** [comment]
Oh, sorry, somehow I got confused with another discussion. I meant rule [B4c3](https://www.worldcubeassociation.org/regulations/#B4c3). If the competitor brings the cube in front of him he's still in the solving phase and there isn't a _suitable_ object between him and the cube anymore. Reading the rule again: I don't think using the table is a good example, because it has the same problem.

**Comment by lgarron** [comment]
I don't think there's anything to do here.
