### ISSUE TITLE
New rule item about clock pins

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/wca-regulations#532]
There is a paragraph **A3c2** (_If the parts of the puzzle are not fully aligned, then the competitor may align the faces, as long as misalignments stay within the limits of Regulation 10f_). But if the clock's pins are not pushed to the end competitors should not align it (according to **F3a**: _The competitor must not change the positions of any pins from their scrambled positions before the start of the solve. Penalty: disqualification of the attempt (DNF)_).
Often judges (or runners) according to various reasons carry clocks inaccurately and change pins position.
I suppose that adding new rule allowing competitors press pins to nearest position will be good.

Pros:
+ If competitor A have 4 putted in the middle pins and competitor B have 4 normally located pins, competitor B have advantage compared to competitor A because competitor A must press 4 pins to locate their to desired position and competitor B must press 0-4 pins (according to scramble)

Cons:
- It allows to competitors cheat easier

**Comment by Torenu** [comment]
totally agree

**Comment by xsrvmy** [comment]
Actually, F3a is not entirely clear, since a non-fully placed pin technically is not a proper state for the puzzle. But this is definitely an improvement.
#382 is a more substantial change to fix this but that changes the nature of the event.
