### ISSUE TITLE
A5b+ Removal (Ignore)

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-regulations#535]
This guideline refers to the old regulation, of not being to inspect with your hands, in 3x3x3 with feet. Now you are allowed to do that, hence making the "Execption" part of no meaning.
It should therefor be removed now, or tell that "in the past competitors was not allowed to inspect with any part of their body, in the 3x3x3 with feet event, but are allowed now". It is worth to note that it says that last part in D1b++, so the first option would most likely be the best option.
https://www.worldcubeassociation.org/regulations/guidelines.html#A5b+

Best Regards, Daniel Egdal

**Comment by AlbertoPdRF** [comment]
It says while "inspecting or solving", so it still makes perfect sense.

**Comment by DanielEgdal** [comment]
Never mind then, I certainly did not remember it that way either. This makes the post complety pointless, I will just close it then.
