### ISSUE TITLE
Clarify how MBLD interact with other regulations

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#536]
MBLD is the only event that concerns multiple puzzles, and sometimes the wording of the other rules do not make sense in the context of MBLD or are not clear. Here are several examples:
- Many DNF penalties use the phrase "disqualification of the attempt", while for MBLD only the single cube should be disqualified.
- What happens if a competitor attempts to put hands on table to signal a stop, but accidentally touches puzzles when lifting their hands? Is it in the spirit of the WCA to penalize this kind of accidents? What about this? https://www.youtube.com/watch?v=PSGgbphKAo8
- What if a competitor fails to submit enough puzzles after submitting the number of cubes to attempt (e.g. invalid puzzles, stolen puzzles)?

For the first one, I can propose the following two guidelines:
- **CLARIFICATION** If the result on a single puzzle is deemed to be DNF due to a violation, the attempt is not considered DNF. Exception: If the competitor is guilty of cheating, he should be disqualified (DNF), at the discretion of the judge/delegate.
- **CLARIFICATION** Using an invalid puzzle does not constitute cheating. However, taking advantage of an invalid puzzle (e.g. attempting to distinguish pieces by feel) is considered cheating.

**Comment by abunickabhi** [comment]
I propose a solution to address the confusion that can occur prior to the competitor's MBLD attempt.

Just like the FMC event, the competitor will be handed out a sheet, where he/she will specify the number of cubes that they will be attempting. The delegate and the scrambler will check if the cubes specified are legal and match with the number that the competitor specified. 
If there is the case of cubes being stolen, or cube with missing stickers that the competitor notices after starting his/her attempt, the changes should be made on the sheet by the judge, and then finally the delegate decides on whether to DNF controversial cubes or take some other action.

**Comment by Laura-O** [comment]
> Just like the FMC event, the competitor will be handed out a sheet, where he/she will specify the number of cubes that they will be attempting.

Well, this sheet is usually called a score sheet. 😄 

It's quite common that delegates write down the number of cubes on the score sheet when competitors submit them. So there basically is no need for a new solution, it's rather the need to make delegates follow this approach.
