### ISSUE TITLE
DNF for times of 0.05 or better

### ISSUE THREAD

**Issue by cubewhiz** [thewca/wca-regulations#537]
I disagree that times of 0.05 or better are caused by timer malfunction. In fact, I propose the opposite. I have noticed that when times of 0.05 are achieved, they are usually by the same person or persons. I propose that all times of 0.05 are treated as DNF because they are caused by an error in the competitor's starting procedure and not a malfunction by the timer.

**Comment by xsrvmy** [comment]
I think the 0.05 problem may actually be caused by competitors that are careful about timer starts. Apparently the gen4 timers seems to fail a lot easier if the hands are further back because of the curved surface.

**Comment by xsrvmy** [comment]
I though that one of the stackmat timers actually prevents times less than .1, but it's definitely not the gen 4. Maybe the pro?

**Comment by cubewhiz** [comment]
The original model (Gen1) prevented times below 0.32 seconds. I wasn't aware of a model that prevents times below 0.1 seconds.
