### ISSUE TITLE
Clock Modifications (3h is vague)

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#54]
The wording "additional information" in 3h is vague when it comes to clock modifications. It's arguable whether clock inserts that have bigger markings for noon give extra information. It's also arguable whether thicker or unmatching markings on the nine clocks do the same.

Also, what about this? 
http://www.speedsolving.com/forum/showthread.php?42686-Clock-Thread&p=871186&viewfull=1#post871186

(I have a bit more to add on this, later.)

**Comment by lgarron** [comment]
@Sa967St, could you figure out what we should do about this?

**Comment by sarahstrong314** [comment]
3j2 in clock-modifications covers the markings problem on the inner clocks, by defining all nine inner clocks to be considered similar pieces.

I added "at the discretion of the WCA Delegate" in 3h4 to cover suspicious markings on inserts that can give additional information.
