### ISSUE TITLE
Requiring the timer to be visible to the competitor during MBLD

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#540]
I believe that being able to see the timer is very important doing MLBD attempts that are going to close to the limit, since the competitor can give up on the last few cubes if time is not enough.

Right now, some competitions are held in rooms that may have a clock in them, and the competitors will be able to keep time. Adding this new regulation should give all competitors a fairer environment.

Note: From talking to other cubers, some judges/delegates already allow this, so maybe a guideline is sufficient.

**Comment by lgarron** [comment]
A compromise idea: don't require this, but allow competitors to request it before the start of the attempt.

**Comment by xsrvmy** [comment]
Yeah. Seeing the timer is probably useless for small safety attempts.

Also, forgot to mention that 4BLD and 5BLD are affected as well because of potential extra reviews for safety.
