### ISSUE TITLE
Article 12 Notation: Rotations

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-regulations#542]
Under [Article 12](https://www.worldcubeassociation.org/regulations/#article-12-notation), I think it would make more sense, to add the current [12b](https://www.worldcubeassociation.org/regulations/#12b), as a part of [12a](https://www.worldcubeassociation.org/regulations/#12a). I think the 12b should become 12a3, and the current [12a3](https://www.worldcubeassociation.org/regulations/#12a3), would then become 12a4. I would consider rotations to be a part of the notation, and it would make the explanation about OBTM better, since it would then only be explained with 'things we have already been informed'. It would also be easier to refer to, in the "Fewest Moves Solving" Article, when refering to 12a, since rotations would then also be explained there.

**Comment by xsrvmy** [comment]
I believe that previous regulation numbering is kept for backward compatibility, so doing this would mess up old links.

**Comment by lgarron** [comment]
> I believe that previous regulation numbering is kept for backward compatibility, so doing this would mess up old links.

Indeed, [we avoid renumbering](https://github.com/thewca/wca-regulations/blob/draft/style-guide.md#formatting-the-document). In this case, renumbering would break old references without placing 12b any closer to 12a, so I don't think we should do it. I'll close this for now, although other WRC/WCA folks are welcome to reopen it.

Cleaning up the FMC article references sounds like a good idea, but I think we should track that in a new issue. Could you file one, @DanielEgdal?

**Comment by DanielEgdal** [comment]
Done @lgarron :)

**Comment by lgarron** [comment]
> Done @lgarron :)

Thanks!
