### ISSUE TITLE
Reference in Fewest Moves Solving (Article E)

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-regulations#546]
Currently in [E2c](https://www.worldcubeassociation.org/regulations/#E2c) it refers back to [Regulation 12a](https://www.worldcubeassociation.org/regulations/#12a) when describing what OBTM is. This creates an issue, since the rotations aren't described in 12a. 
As I got in response to my [previous isssue](https://github.com/thewca/wca-regulations/issues/542), I was told to create this, and that renumbering wasn't possible to do.

**Comment by lgarron** [comment]
Done in 8104b4b795b2e9e993cdd220b071354c4ffb0591.
