### ISSUE TITLE
Discretion of the WCA delegate for A1c

### ISSUE THREAD

**Issue by julesDesjardin** [thewca/wca-regulations#551]
Right now the [A1c](https://www.worldcubeassociation.org/regulations/#A1c) rule forbids a competitor not to do their best at a round. However, some delegates seem to use their discretion (and especially the one written in guideline [A1c+](https://www.worldcubeassociation.org/regulations/guidelines.html#A1c+)) to allow this if the competition is not running behind on schedule. This leads to inconsistent rulings, and some delegates allowing stuff like solving 3x3 blindfolded in a regular round, or flipping a coin to choose your One-Handed hand, while other don't.

I think we should take off this discretion, and only DNF the attempt. If the competitor expected to do their whole average this way, in the end the result would be the same as DNFing the average.
The first part of the guideline would also go away, but we probably want to leave the last part as it is right now.

**Comment by SAuroux** [comment]
In my opinion this is a very bad idea and will probably only lead to way more inconsistency. The reason for this is that *must not compete with expectation of [...] an intentionally poor result* as such is already very vague. For example, what about executing a PLL slower than usual or stopping the timer slower than usual for an already bad solve (e.g. [this solve](https://youtu.be/fNxTpvKsck0?t=44) :P)? 

I think that removing the discretion part will only lead to (1) delegates feeling forced to assign DNFs for situations that would have never been judged DNF so far and (2) other delegates ignoring this regulation as they feel it is unjustified or simply have another working definition of *intentionally poor*. 

By the way, A1c was originally introduced to have a way to stop competitors fooling around when it is hurting the competition flow. With this in mind, I think that A1c is actually applied consistently as is right now.

**Comment by julesDesjardin** [comment]
I see your point in the vagueness of "intentionally poor", and I don't think solves like the one you linked should be DNFed (even though technically I could have done slightly better :p).

My point in removing the discretion (which, as you showed, is in fact not a good idea) was to explicitly either allow or forbid most common practices, such as solving blindfolded in regular solves (being more in favor of forbidding them), because I don't think it is applied consistently in those cases (which usually don't significantly interfere with the competition flow). It would be nice to have other people's thoughts about this.
If we finally agree that such cases should be explicitly dealt with, adding a guideline will do just fine.

**Comment by lgarron** [comment]
> If we finally agree that such cases should be explicitly dealt with, adding a guideline will do just fine.

Is there anything important our existing guideline does not cover?

> A1c+) CLARIFICATION WCA Delegates should only use their discretion to prevent competitors from being a severe detriment to the competition (e.g. wasting time and/or competition resources). Competitors should not be disqualified for a "poor" result when they are competing to the best of their abilities.

**Comment by dancing-jules** [comment]
Banning things like doing (sighted) 3x3 with a blindfold is against the spirit of that regulation. What if a competitor has sub15 memo and an execution that is faster than what they achieve with other methods (e.g. CFOP or Roux). This applies to Gianfranco Huanqui, for example: https://www.youtube.com/watch?v=0cXTrtDHIn4.

**Comment by lgarron** [comment]
> Banning things like doing (sighted) 3x3 with a blindfold is against the spirit of that regulation.

A1c+ makes it clear that this is not against the spirit of the Regulations if they are not wasting competition time in the view of the Delegate.

**Comment by lgarron** [comment]
For what it's worth, I believe A1c and A1c+ are sufficient and I'm against  the proposal in its current form (removing Delegate discretion and forcing DNF).

In particular:
- The mission of the spirit of the WCA both include fun, and I think it's fine to let competitors have fun as long as the Delegate does not find they are not being a detriment – even if this is not a consistent line across competitions.
- Competitors with poor results do not gain an advantage – they do not harm anyone else's rankings. (At *most*, they can contribute to a time delay that prevents other competitors from competing in a tentative event/round – but if that's a significant risk then it's exactly where the spirit and wording of the current A1c/A1c+ give the Delegate power.)
- I'm skeptical that it's possible to set a harsh line for an "intentionally" poor result without inadvertently including common, harmless behaviour. @SAuroux 
gives good examples in his comment above.
