### ISSUE TITLE
Different groups in 1h+

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#554]
The end of 1h+ reads:
```
Different groups should use different scramble sequences.
```
At some competitions, consecutive groups are called at the same time in order to assign each puzzle to the correct scrambling station, and these groups would use the same scrambles. Should this guideline be revised to accommodate this? For example:
```
Groups competing at different times should use different scramble sequences.
```

On a side note, should 1h+ belong somewhere in section 4 because it is about scrambling?

**Comment by Laura-O** [comment]
> At some competitions, consecutive groups are called at the same time in order to assign each puzzle to the correct scrambling station, and these groups would use the same scrambles.

I think the competitions where competitors are divided into groups which are run at the same time and these groups use different scrambling sequences are quite rare.
So having this as a "should"-regulation should be fine.

Regarding the section 4: section 4 focuses on the technical side of scrambling, while 1h focuses on dividing competitors into groups, so I think that's fine as well.
