### ISSUE TITLE
A6b1 does not specify a penalty

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#555]
```
A6b1) If the timer stops before the end of the solve and the timer shows a time strictly below 0.06 seconds, then the attempt is replaced by an extra attempt. A competitor forfeits the right to the additional attempt if the WCA Delegate determines that the timer was stopped deliberately.
```
Note that A6b2 specifies a DNF penalty for any other times shown.

Also, "before the end of the solve" is weird since the competitor would not have really started the solve.

**Comment by pedrosino** [comment]
I don't understand why it would need to specify a penalty. We're saying that if that happens, there's an extra attempt.
Or do you mean the part about "...competitor forfeits the right to the additional attempt..."?

The solve actually began. See A4d:

A4d) If a Stackmat timer is in use, the competitor **starts the solve** by confirming that the timer light is green and then removing their hands from the timer (thus starting the timer).

**Comment by xsrvmy** [comment]
I meant that the part about forfeiting the attempt does not specify DNF or DNS.

**Comment by HippolyteM** [comment]
You should read the regulation you quoted more carefully.;)
There's no forfeiting the attempt, only the extra attempt, meaning that the original result is kept, the said result clearly being a DNF (attempt started, cube unsolved).
So everything is completely fine with this regulation. You should not try to find voids where there is none.

**Comment by AlbertoPdRF** [comment]
Indeed, A6b1) is totally fine. I'm closing this issue.
