### ISSUE TITLE
Competition information in English - Article 8 

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-regulations#559]
Currently, multiple competitions are being announced, with all the information about the competition in the native language only. I think we should start to have all information to be in English as the primary language for the information.
It is already stated the main language of the WCA is American English, so I think that every competition, and announcement at a competition should be made in English, and then the organization team can choose to also do that in other languages. 
I believe adding a regulation along the lines of this: Have all information written on the competition page must be in English. 
Then it could be added under 8a. I belive adding a guideline like this, would be nice to have: ADDITION Any other language, of the targetted demographic may be written on the competition page.

I hope this is helpful
Best Regards,
Daniel V. Egdal

**Comment by Laura-O** [comment]
I'm not sure if it's reasonable to add this to the regulations. I think it's rather an organizational issue which should be mentioned on the website like it's already done for the registration requirements.

**Comment by garrett-webster** [comment]
I agree that requiring it is unreasonable, but what about recommending it? There's no way to enforce this really, but some is better than none.

**Comment by cubewhiz** [comment]
I think with translation tools that are available these days, this is not much of an issue. However, I do have a related software suggestion that I will make in the software Github.

**Comment by Laura-O** [comment]
Closing as this does not seem to be a regulation issue.
