### ISSUE TITLE
Publish list of 2013 changes.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#56]
The partial [here](https://docs.google.com/document/d/1lk7h98lhc_5EmKhkGyINt_NGMy2DWhn3G7xxFoaL-nw/edit) was never finished and published for the 2013 announcement. Since there's quite a bit of confusion abotu the changes, an explicit [announcement](http://worldcubeassociation.org/regulations/announcements/) would be good.

**Comment by lgarron** [comment]
@Sa967St or @timhabermaas Could you take this? It's not in a hurry (and doesn't require very detail), but I would eventually like to have it available on the WCA website.

See https://github.com/cubing/wca-documents/issues/112 for the current example and https://www.worldcubeassociation.org/regulations/history/files/regulations_history2010.html for an old one.

**Comment by sarahstrong314** [comment]
Sure.

**Comment by sarahstrong314** [comment]
#199
