### ISSUE TITLE
Unclear DNF situation : Article 2i2b

### ISSUE THREAD

**Issue by AlexandreCarlier** [thewca/wca-regulations#560]
Hello,
  I am Alexandre CARLIER and I would like to deal with a regulation for which I've been DNF'ed (on the second solve of the final of France 2018, after the final was done), and I propose to modify/clarify it :

> 2i2b) The competitor must not interact with (e.g. operate, hold, wear) any active camera. Exception: the competitor may wear a camera mounted on their head, as long as it is out of their sight and it is clear that they are not interacting with it (apart from wearing it).

- First, what are the possible ways a competitor could get help by interacting with an active camera (given that any screen must be out of his field of vision (if there is even a screen, mine hadn't))?
   What is the purpose of this rule?

   Some delegates explained me that a possible reason could be that rather than being passive about it and dealing subjectively with possible litigious cases, we will be arbitrarily too strict to avoid those cases and simplify it whatever happen. But it is not rightful at all, especially in this particular case*****.

- The formulation of the first sentence is not clear : in this case I pushed the on/off button while the camera was off, but the camera was considered as active? The regulation should not apply from my point of view. I propose to clarify this point, the fact that the competitor isn't trying to cheat is enough legitimate, it does not give any advantage (it's just a tiny waste of time like if the timer turned off during inspection and the judge doesn't see it).

   In my case, I turned on the [off] camera at the first second of inspection [[video of the stream](https://www.twitch.tv/videos/245715980) at 5:54:40] because i forgot to do it just before, but this is not in trouble with the sense of  the regulation, because the camera was not active, it was off. 
Moreover the camera was a Gopro, and there is a time to become active, at that time I was not touching or interacting with the camera anymore, because I just briefly pushed the top button when it was off (as we can see on the stream video), not in contradiction with the reg. I think it's the reason why the word active is used in, to globally avoid this scenario.

  The solve had not been DNF'ed at the moment, but after the final, so the time was considered legit until then, and the DNF had a huge impact on the final ranking (from 1st to 8th position) which I find really unfair for that sort of litigation : litigation as timer reset causes a concrete physical problem, while in this case there isn't , it could clearly and easily be avoided.

  Also, when the delegates decided to give me a DNF, they never specified me that the regulation concerned an active camera which I must no interact with, but just the fact that I touched or pushed the button during inspection, which doesn’t match the regulation for a DNF.

  That is all why I’m bothered with that DNF, and I asked by mail the WRC yesterday for :
-first, the legitimacy of the actual solve according to the regulations;
-second, for an accurate article, because this situation goes beyond understanding.

Alexandre

***** **EDIT : About the article itself, I might be wrong, but I don't see any "possible litigious case" that could give any sort of advantage to the competitor. This rule is based on nothing. Even worst, it actually creates unnecessary "litigious cases" when there is an accident or minor mistake like mine, when the person forget to start his camera. Should we keep a regulation that solves nothing but create unnecessary/inappropriate sanctions? I think the regulations are there to solve real problems, not to creates ones where there aren't.**

**Comment by dancing-jules** [comment]
I'd also like to know the reason for this regulation. As of now it seems to be pretty arbitary and it complicates things unnecessarily. I'd be happy to change my mind, if someone can present a situation where it would result in an advantage. Or some other reasoning as why this is a logical conclusion of the other regulations.

**Comment by lgarron** [comment]
Here's (an excerpt of) what @Claster replied to @AlexandreCarlier via email on behalf of the WRC, which expresses my view on this fairly well:

> Its [2i2b's] main goal is to provide a clearly enforceable line of what interaction is okay, while still allowing most competitors a practical way to record.
> This actually matches your comment: we do realize that turning on a camera the way you did doesn't provide you with an advantage, but rather than making a list of exceptions of what interactions with a camera would be ok, we chose to implement an easy-to-apply rule.
> It's stricter than necessary, but we think it's reasonable to expect the competitor to respect it: competitors should be solving a puzzle during an attempt, not interacting with a camera.
> ...
> We agreed that we want to keep a regulation preventing the competitor from interacting with a camera during the attempt, and we also think making it "at the discretion of the Delegate" would lead to inconsistent decision.

I don't think we can draw a good line other than the one we currently have. Allowing the Delegate to waive the penalty for some interactions introduces another avenue for unfairness due to inconsistent ruling, and could lead to more subjective calls for (and additional load on) Delegates/the WRC.

> As of now it seems to be pretty arbitary and it complicates things unnecessarily.

Could you expand on this? The rule was crafted to be simple to understand and enforce.
Violations are entirely under the control of the competitor, and can be judged objectively.

**Comment by xsrvmy** [comment]
Not really relevant to the incident, but does the interaction need to be intentional? One thing that comes to mind is hitting the camera with a puzzle drop. Of course knocking it over so the screen faces up results in DNF.

**Comment by dancing-jules** [comment]
@lgarron 

> Could you expand on this? 

Why do we need a rule to limit interactions with a camera at all? What kind of interactions would not be okay at all? (Other than the camera telling you how to solve a cube, of course, but that's what we have [A5b](https://www.worldcubeassociation.org/regulations/#A5b) for)

**Comment by xsrvmy** [comment]
@dancing-jules maybe seeing the screen by accident

**Comment by lgarron** [comment]
While we occasionally revise Regulations to be more lenient, I believe the WRC is in agreement that the current Regulations regarding cameras are the best tradeoff. I'm closing this issue for now.
