### ISSUE TITLE
Move A1a2+++++) to Regulations

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#561]
`A1a2+++++)` has a **must**, so it should be in the Regulations.

(That said, at the most recent BASC competition I was at competitors were given an hour to do 4BLD/5BLD/multi during which you were expected to do all your solves. It might be nice to e.g. allow competitors to compete in multiple attempts and/or multiple combinations of events like that without making them exclusive.)

[WRC email thread](https://groups.google.com/d/msg/wca-wrc/lz_Kb5gx5co/gEqbQm7KBAAJ) for Kansai Open 2018.

**Comment by Jambrose777** [comment]
I don't see that as fair at all, Competitors who are particularly skilled at Bld events are going to take an hour to compete in multiblind at their best. If they would want to do 4Bld and/or 5Bld they would end up impeding their time in multiblind just to compete in the other events.

**Comment by lgarron** [comment]
Closing this in favor of #611.
