### ISSUE TITLE
A2b1) Thin object inside of the square-1 to prevent accidental moves

### ISSUE THREAD

**Issue by ClemAntarctica** [thewca/wca-regulations#562]
Hi, this is my first post here, sorry if I miss a point or if the organisation of my message isn't appropriate.
I want to point the unclearness of [A2b1](https://www.worldcubeassociation.org/regulations/#A2b1). 
For World Championships 2017, I was scrambling square-1 finale and I have a very clear memory of Jayden McNeil asking to the scrambler to do not add this thin object (paper) inside of the square-1, and (but I'm not entirely sure about it) he also was asking to his judges to remove the paper before inspection starts (that's where I'm not entirely sure if he was asking the judge to check if there was a paper or if he was clearly asking to remove it).
I faced the same situation on the 1st of April, at French CHampionships 2018, in Lyon, France, during the square-1 final. During the first round, I had some issues removing the paper, I wasted time, I wasn't able to have my full inspection because some of my time was wasted trying to remove a small square of paper. It was barely longer than the height of the cube so taking it out wasn't convenient.
Because I need my full inspection in order to do a CSP tracing, I thought about asking to the scrambler to do not put any paper during finales. The delegates were here and made me notice that it wasn't allowed, because it was giving different solving situations for me, and other solvers, and because the word "enforce" was used in the regulations, which could be quite clear.

I'm aware that this paper put inside of the cube is to prevent accidental moves, but, in my case (only mine, I don't know or I don't remember for other cubers like Jayden) my square-1 is magnetic, quite tight, and lubing made it quite slow. Accidental moves are very hard in this situation.

I would like to ask for a clarification on this point. The paper made me **really** waste time during some inspections, and Jayden as well apparently, and probably other cubers. Couldn't cubers ask to the judge or scramblers to do not insert this paper ?

Best regards,
Clément Cherblanc.

**Comment by julesDesjardin** [comment]
Hi,

The issue with such a request is that it's not fair to other competitors. Everyone wastes time removing the paper, so you shouldn't be allowed to have it removed for you, as it would give you more inspection time than others.

**Comment by viroulep** [comment]
> The delegates were here and made me notice that it wasn't allowed, because it was giving different solving situations for me, and other solvers, and because the word "enforce" was used in the regulations, which could be quite clear.

No, it's not allowed because [A3c4+](https://www.worldcubeassociation.org/regulations/guidelines.html#A3c4+) explicitly forbid it.

If we're enforcing the paper for some competitors, we have to enforce it for everyone, so that everyone compete in the same conditions.

> I'm aware that this paper put inside of the cube is to prevent accidental moves, but, in my case (only mine, I don't know or I don't remember for other cubers like Jayden) my square-1 is magnetic, quite tight, and lubing made it quite slow. Accidental moves are very hard in this situation.

Accidental moves during transport and when dropped on the table by the judge can be quite likely.
It's true that magnetic and/or tight square one will significantly lower the risk, but we cannot just make an exception for you when everyone else has to remove a paper during inspection.

> I would like to ask for a clarification on this point. The paper made me really waste time during some inspections, and Jayden as well apparently, and probably other cubers.

How so? Could you not remove it *while* tracing your pieces?

If I recall correctly we have also made sure to have big enough blockers, so that removing them is not a hassle.

**Comment by viroulep** [comment]
To clarify my first point:
> Because I need my full inspection in order to do a CSP tracing, I thought about asking to the scrambler to do not put any paper during finales.

This incident was reported to me as you asking the *judge* to remove the paper, which is covered by A3c4+.
Asking the *scramblers* to not put the paper is a "no" because the organization team is enforcing the use of a thin object.

**Comment by ClemAntarctica** [comment]
> No, it's not allowed because A3c4+ explicitly forbid it.

I wasn't aware of this, then the case can be closed.
