### ISSUE TITLE
Is a time limit assigned to an event or a round?

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#564]
Regulation 9s uses "event", but regulation A1a uses "round". So what is a time limit assigned to -- event or round? Specifically, can two rounds of an event have different time limits?

For example, in 3bld, the organization team may wish to only allow moderately fast blders to make safety attempts, so set the time limit for round 1 to 2 mins and round 2 to 4mins.

Similarly, what about the same question for cutoffs? Can two rounds have different cutoffs?

**Comment by Laura-O** [comment]
I find this issue confusing. 9s speaks about "Each round of each event must have a time limit", which probably clarifies that **each round** has a time limit. Rounds may share time limits with other rounds by using a cumulative limit.
Therefore, different rounds can have different time limits and I think that's what is done at 99% of the competitions.
