### ISSUE TITLE
Clear verbal confirmation of readiness to solve.

### ISSUE THREAD

**Issue by ChrisBLD** [thewca/wca-regulations#570]
I've been working on a new routine before solves to make sure I'm entirely focused and prepared to go. Since my main event is BLD, this is normally fine as I can just lift the cover whenever I'm ready myself. However in other events with judges asking if I'm ready, I notice that as I take a few seconds to get comfortable and crack my knuckles etc., some slight movements I make are taken as confirmation and the cover is lifted prematurely to when I expected it to be. I always prepare myself and then say clearly "I'm ready" to avoid ambiguity, but with lots of judges often seeing competitors just nod or say "yep" they may just take any slight head nod or hands on the mat to signal readiness. 

I propose a clarification to the following regulation:

A3b2) The competitor starts the attempt by confirming that they are ready, and the judge uncovers the puzzle and starts timing the inspection.

As such that clear, verbal confirmation is required before the judge is to lift the cover. I am aware that extra solves are awarded for premature cover lifts in the case of competitors being taken completely off guard by it, however I feel that introducing this as a requirement for most competitors (excluding those who are incapable of communicating readiness verbally) would be beneficial to avoid situations in which competitors intend to make the most of the time they are allotted to prepare themselves to solve.

Such a change could be implemented:

A3b2) The competitor starts the attempt by verbally confirming that they are ready by saying "I am ready" or providing other explicit confirmation, upon which the judge uncovers the puzzle and starts timing the inspection.

**Comment by lgarron** [comment]
Does this happen to you with experienced judges?

Unfortunately, I feel that such a Regulation change isn't likely to improve the behaviour of most judges, given that they're often not even following `A7a`. :-/

If we introduce this as a technicality that judges should know, but it doesn't improve the situation in practice... there is no benefit here. You can still say you weren't ready and point out that the judge wasn't looking for a signal from you correctly, but that doesn't help you with regard to your goal.

**Comment by lgarron** [comment]
@ChrisBLD: have you tried / would you be comfortable asking judges "please wait for inspection until I say something out loud"?

I know that's more work for you, but I think it's likely to be more effective for you than any change we could make to to the Regulations.

**Comment by lgarron** [comment]
In particular, I'd like to note that we can't provide an incentive for judges to wait for a clear verbal signal. If they do it wrong, all the Delegate can do in practice (if they hear about it) is ask the judge to be more careful – but for most competitors it still won't matter if they're careful.

**Comment by xsrvmy** [comment]
@ChrisBLD You can always put your puzzle on top on the box so a cover lift is impossible. Credits to Kian
