### ISSUE TITLE
Proposal: Combined Best of 3/Best of 5 Rounds for 3BLD

### ISSUE THREAD

**Issue by sebastianotronto** [thewca/wca-regulations#571]
I would like to propose the following new format for 3x3 Blindfolded rounds: **combined Best of 3/Best of 5**.

- After the first 3 solves, competitors meeting a specified cutoff time can procede and do two more attempts.

- In competitions, the final ranking is still based on best single.

- "Average of 5" would replace "Mean of 3" in the average rankings for 3BLD, as has happened recently for 3x3 With Feet and for other events in the past. For 3BLD, this has no effect during the competition itself.

- The ideal cutoff should be somewhat low, like 1:30 or 1:00, to prevent the round from lasting too long.

## Reasons
At high level, 3BLD times are comparable to 4x4 and 3x3 with feet. These events are already held in "Average of 5" format (the latter having been changed lately), and even longer events (5x5 and Megaminx) get 5 solves per round. Thus, it seems reasonable to allow 5 solves for 3BLD as well. This means more fun and more chances of setting new records.

## Pros

- **More attempts = more fun!**

- **Bigger chances of setting new records**
There is quite a big gap between the the best known unofficial results and the official world records. This is true for any event and I think the main reason for this is that people can do many more solves at home than in competition. This is in particular true for 3BLD, according to the [speedsolving UWR page](https://www.speedsolving.com/wiki/index.php/List_of_Unofficial_World_Records): below you can see a table showing this gap for 3x3 Cube, 3x3 Blindfolded and events with solving time comparable to the latter (4x4 Cube and 3x3 With Feet). I think this new format can help reducing this gap.

 Event | UWR single / WR single | UWR average / WR average
---|---|---
3x3 Cube |  2.99/4.22=**70.85%** |  4.84/5.80=**83.45%**
4x4 Cube |  16.13/18.42=**87.57%** | 19.95/21.13=**94.42%**
3x3 With Feet | 14.50/16.96=**85.50%** | 19.40/23.69=**81.90%**
3x3 Blindfolded | 12.56/17.87=**70.29%** | 16.27/22.36=**72.76%**

- **It's easier to get a succesful Average of 5 than a succesful Mean of 3**
If one's success rate is better than 25%, see [attachment](https://github.com/thewca/wca-regulations/files/2083621/Mo3_vs_Avg5.pdf). This is a matter of basic probability computations, assuming the success rate is the same for all attempts. This doesn't take into account the fact that one might get tired after some solves, or that one can influence their own success rate at will.

- **The competition strategy doesn't change**
In a Best of 3 round one has to get at least one good solve out of 3, so the "minimum success rate" is 1/3. In a Bo5 round this is 1/5, but using the combined Bo3/Bo5 format we can allow for more solves, while keeping this minimum success rate at 1/3. The only thing that changes is how to get an average, but this doesn't matter for the competition, and in any case it would become easier (see previous point).

## Cons

- **Slower cubers might not get an average**
This is true for any "combined" round. Since the ranking would still be based on single, this is less revelant with the proposed format. There may be a bigger disproportion between beginners' and world-class times than what we have in other events, but it doesn't take an insane amount of practice to get down to, say, 1:30 average.

- **It is more tiring to do 5 solves**
I believe for anyone faster than, say, 1 minute, doing 5 solves in a row is not a problem. This is consistent with the cutoff time suggested above. Moreover, if one finds it tiring to complete the last two solves, they can always DNS them and have no big disadvantage (the format is still "Best of X").

- **It will slow competitions down**
That's what cutoffs and time lmits are for. If they are low enough, this will be no problem. And in many cases faster competitiors can complete 5 solves faster than slower competitors doing 3 solves, so the extra solves for them would not be the bottleneck. It is also possible to have a cutoff time hardwired in the regulations, but I would rather specify it in the guidelines or in some other way. Moreover, it is still possbile to use cumulative time limits to ensure the round doesn't last too long.

- **With low cutoffs, very few competitors may be able to complete the round**
This is true, but as I mentioned before it is not as bad as in the case of Bo2/Avg5 or Bo1/Mo3 combined rounds: competitors are ranked by single in any case. Missing the average doesn't change anything from the point of view of the competition. Even if nobody meets the cutoff it shouldn't be a problem.

- **Inconsistency: there is no other event with such a format**
Personally, I don't think this is a good reason to keep things like this. The point of the regulations is to make competitors have fun and compete under fair conditions, not to give a satisfactory sense of order when read.

## Conclusions
  
I think this new format has the advantage of giving more opportunities for records and more fun to faster solves, while not giving any true disadvantage and not changing anything about the event competition-wise.

I haven't checked the community's opinion, but I can make polls on speedsolving.com or on Facebook, if someone wants.

**Comment by lgarron** [comment]
I don't have strong opinions or concerns on this change. Since no one else has commented here, would you mind making a poll to see if the community (especially blindfolded cubers) wants this change?

**Comment by sebastianotronto** [comment]
I have made polls [in the speedsolving.com forum](https://www.speedsolving.com/forum/threads/proposal-combined-best-of-3-best-of-5-rounds-for-3bld.69657/) and [on facebook](https://www.facebook.com/groups/BLDSupportGroup/permalink/1747424005378347/) (the latter may not be accessible to everyone).

**Comment by sebastianotronto** [comment]
The votes have pretty much stabilised now, so I am posting the outcome, along with some other remarks people have made.

The speedsolving.com poll didn't get a lot of attention. In total 22 people have voted, 12 (54.5%) for keeping the current format and 10 (45.5) for changing to Bo3/Bo5.

In the Facebook poll 115 have voted. 42 (36.5%) for keeping the current system and 71 (61.7%) for changing; 2 (1.7%) have voted for "other".

In my opinion, the distribution of votes is not too surprising, considering that the speedsolving.com forum is nowadays only used by the most "old school" and "conservative" cubers. The Facebook poll was in a group dedicated to blindsolving, but this doesn't mean that the voters are good/fast a 3BLD, just that they like the event.

The most interesting remarks, in my opinion, are the following:

- (Pro) Avg5 records will be less influenced by luck than the Mo3 records. In all Mo3 events, a very lucky single can make an average ridiculously good, or ridiculously better than it should be. Changing to Avg5 will help avoiding this.
- (Con) With Avg5, the best single will be excluded from the average, which may seem inconsistent for an event ranked by single.

Other formats proposed include:

- Avg5 instead of single for determining the winner. This seems less popular among experienced blindsolvers.
- Bo5 with cumulative time limit instead of combined Bo3/Bo5. I explained why I prefer the latter in my first post. Notice that a combined round doesn't exclude the possibility of introducing combined time limits.
- "Mean of best two solves out of four" or "Mean of second and third best solves out of 5". These seems interesting, but are maybe a bit too far-fetched.

**Comment by Laura-O** [comment]
Just leaving some quick comments here for later reviews:
- This would require many modifications in software (website, schedule tools, result tools, cubecomps, and probably others) as this would be a completely new format.
- This poll only reflects the opinion of BLDers, so I think it's not surprising that they want to do as many solves as possible. Maybe they would even vote 'yes' for a Bo3/Bo12 combination. (no offense, just noting this here).

**Comment by lgarron** [comment]
I think we don't have a clear community consensus for a change. If enough BLDers are interested, though, I would be interested in a non-binding Delegate poll next time we run some of those.

> This poll only reflects the opinion of BLDers, so I think it's not surprising that they want to do as many solves as possible.

I know you're just making a note, but I think think is a good reason in favor! The mission of the WCA includes "more fun", and I think more fun for experienced BLDers is good if it doesn't come at a significant expense for anyone else. But it certainly is not a good enough reason on its own, at least here.

**Comment by gregorbg** [comment]
I would like to re-initiate the discussion on this change, especially now that Cumulative Limits have become more "usual" and frequently used.

Briefly put, I believe that holding three attempts is a relic of the past, from the times back when even the best BLDers in the world would need several minutes for one solve.
Nowadays, solving times of 1:30 and below are very common (for reference, as of writing this comment ranking #1000 has a `1:32.08` single). I absolutely admit my personal interest in the topic, but that being said it feels very strange to be done with all my attempts of an entire round after 3 or 4 minutes, while the rest of the group carries on for half an hour.

At a recent competition, I had a discussion with a friend of mine who takes competing in 3BLD extremely seriously. He argued that it exerts tremendous additional pressure when practicing at home for hundreds of solves and then travelling (potentially very far) for only 3 or 6 attempts at achieving a good result.

I partially share his opinion, as somebody interested in 6x6 or 7x7 could easily argue the same and I wouldn't consider introducing Ao5 for those. But the length and - more importantly - the nature of these events are significantly different.
As a very simple example, if your hands slip and the cube drops you can easily pick it up and continue the solve in non-BLD events (that is, you have active, conscious control over not DNF-ing) whereas if the same happens during 3BLD you are almost certainly lost.

Lastly, the previous arguments from this discussion also seem well-conceived and I agree with all of them. Competition Organisers and Delegates nowadays do indeed have the tools necessary to keep a schedule manageable, even with this change.
The only major disadvantage that I can personally see is the "rat tail" in terms of Software that a format change would induce.

**Comment by xsrvmy** [comment]
I think one thing we need to consider is that it might significantly change the strategy of good competitors: it is now possibleto safety the first solve and then rush all four others without ruining the ao5.

Personally I wouldn't like the change because it forces the organizer to use a time limit instead of a cumulative limit, and therefore makes the tim e limit of the first solve 3 to 5 times lower if the schedule needs to remain the same. (On that note is a cumulative and a cutoff allowed to be both used on the same round?)

**Comment by gregorbg** [comment]
I don't see your point here, @xsrvmy.

> Personally I wouldn't like the change because it forces the organizer to use a time limit instead of a cumulative limit

That is absolutely not true in my opinion, and quite in the contrary the proposed change even **encourages** organisers to enforce cumulative time limits.

Imagine a competition under the current Regulations (i.e. Bo3) that has a cumulative time limit of 10:00 minutes and two groups are assigned. In total, I can safely assume that the round will take 30 minutes - including group changing, scramble extras and a comfortable buffer for incidents.

- If a competitor needs >= 7 minutes for one successful BLD solve, he will have only one attempt within the constraints of the time limit -- no matter if there are 3 or 5 attempts.
- If a competitor needs ~3 minutes for one successful BLD solve, he will have 3 attempts in the old format as well as in the new format
- If a competitor needs < 3 minutes he will only be able to do 3 attempts in the old format **and leave some X minutes unused** out of the total 10 minutes time limit. These X minutes could then be spent towards the remaining (new) 2 attempts.

Why do you think this poses a disadvantage for organisers?

**Comment by xsrvmy** [comment]
Can a round have both a cutoff and a cumulative time limit? I have never seen it in practice.
If these were not allowed at the same time, then a normal time limit must be used, and therefore the time limit will be significantly lower than the old cumulative time limit.
Btw I was talking about disadvantage for new competitors not organizers.

**Comment by gregorbg** [comment]
What?? A cumulative time limit and a cutoff serve exactly the same purpose. You generally enforce cutoffs to avoid that a slow competitor does all 3 (or 5) attempts, therefore "wasting" time in your schedule. Similarly, a cumulative limit ensures that no competitor takes > X minutes. Why would you ever want to combine them?

Secondly, what is the disadvantage for new competitors? Motivation that you can do more attempts if you practice more is something I would hardly ever call "disadvantage".

Forgive me, but I find your arguments very confusing. Can you please help me understand them through the use of a concrete example, where the suggested Bo5 would be inferior to the current system?

**Comment by sebastianotronto** [comment]
> What?? A cumulative time limit and a cutoff serve exactly the same purpose. You generally enforce cutoffs to avoid that a slow competitor does all 3 (or 5) attempts, therefore "wasting" time in your schedule. Similarly, a cumulative limit ensures that no competitor takes > X minutes. Why would you ever want to combine them?

I also don't understand xsrvmy's point, but I have explained in my first post why I believe we should use both a cutoff after the first three solves and a cumulative time limit in this case:

"In a Best of 3 round one has to get at least one good solve out of 3, so the "minimum success rate" is 1/3. In a Bo5 round this is 1/5, but using the combined Bo3/Bo5 format we can allow for more solves, while keeping this minimum success rate at 1/3. The only thing that changes is how to get an average, but this doesn't matter for the competition, and in any case it would become easier (see previous point)."


Anyways, thanks for bringing this up again - I really think this will make comps more fun for fast BLDers without taking anything away for anybody else :)

**Comment by xsrvmy** [comment]
@porkynator sorry about that, I thought cummulative and cutoff cannot be used together.
