### ISSUE TITLE
Ad4 and A3c3 - resetting the timer during inspection, "timer tests"

### ISSUE THREAD

**Issue by dancing-jules** [thewca/wca-regulations#573]
Hello, I just got into a discussion on Facebook whether a "timer test" would be legal during inspection (starting, stopping and resetting the timer).

The other person argued that it would be legal per A3c3:

> A3c3) The competitor may reset the timer before the start of the solve.

Where as I argue, that it would result in a DNF because of A4d:

> A4d) If a Stackmat timer is in use, the competitor starts the solve by confirming that the timer light is green and then removing their hands from the timer (thus starting the timer). 

The way I see it, this regulation makes clear that any time you start the timer during inspection, you start the solve. 

The way I see A3c3: as long as you don't start the timer, you can push the power and reset buttons as often as you want to. 

Further I argue that if "timer tests" during inspections were legal, it would make it impossible for judges to discern whether a competitor starting the timer is doing a timer test or actually starting the solve.

**Comment by lgarron** [comment]
I'd be disappointed if we have to clarify this.

A3c3) allows resetting the timer, and would explicitly include more details else if starting the timer were allowed.

> Further I argue that if "timer tests" during inspections were legal, it would make it impossible for judges to discern whether a competitor starting the timer is doing a timer test or actually starting the solve.

oya.
Even if the competitor communicates this to the judge, there is a possibility for misunderstanding by the judge as well as people watching/video evidence.

We do have a roughly analogous situation in that you're technically allowed to take off the blindfold in BLD before stopping the timer as long as you don't do any moves. It's arguably safe for the competitor to do what they want with the timer as long as it starts running within 15 seconds of the start of inspection. But the competitor controls the timer in BLD (at least for Stackmat solves), and for normal inspection the judge needs to be able to tell when it's over (so that they can stop using their inspection stopwatch). I don't see enough benefit from starting to allow timer tests after the attempt has started – only more potential for incidents.

I'd be alright with adding A3c3++ for this, if there is a chance competitors would actually want to argue that they're allowed to do a timer test.

**Comment by xsrvmy** [comment]
To be clear, timer tests before inspection is legal, right?

**Comment by dancing-jules** [comment]
@lgarron - Thanks for your reply. I invited the person who argued with me to contribute here. They said they think the regulations should be a bit more specific.

@xsrvmy - the way I see it it shouldn't be a problem. Before inspection the attempt hasn't started yet - you are allowed to do a lot of things that aren't allowed during inspection (e.g. interacting with electronics, warm-up, ...)

**Comment by lgarron** [comment]
Reopening for https://github.com/thewca/wca-regulations/pull/579

**Comment by xsrvmy** [comment]
Should the competitor be allowed to reset and restart the timer if it shows a time of less than 0.06, or does the competitor have to take the extra? (Assuming no inspection DNF of course)

**Comment by Laura-O** [comment]
Of course he is not allowed to restart the timer. We follow a clear approach for each attempt and steps like timing inspection wouldn't be possible.

**Comment by pedrosino** [comment]
I think the text at #579 is maybe not clear enough.
Technically, if one didn't confirm that the light is green, they didn't start the solve.

Also, it's weird that the "if a stackmat is in use" appears only at A4d, but not at A4b.

One last

I'd suggest this:

```
A4) Starting the solve:
    A4b) If a Stackmat timer is in use, the competitor must use their fingers to touch the elevated sensor surfaces of the timer. The competitor's palms must be facing down, and located on the side of the timer that is closer to the competitor. Penalty: time penalty (+2 seconds).
    A4d) The competitor must start the solve by confirming that the timer light is green and then removing their hands from the timer. 
        A4d1) The competitor must have no physical contact with the puzzle between the inspection period and the start of the solve. Penalty: time penalty (+2 seconds).
        A4d2) The competitor must start the solve within 15 seconds of the start of the inspection. Penalty: time penalty (+2 seconds).
            A4d2a) If the competitor doesn't start the solve within 17 seconds of the start of the inspection, the attempt is disqualified (DNF).
    A4e) If a stopwatch is in use, the judge starts the stopwatch as soon as the competitor starts the solve.
    A4f) Time penalties for starting the solve are cumulative.

A4d++) [CLARIFICATION] The competitor cannot "test" or "restart" the timer during inspection, since inspection ends once the competitor removes their hands from the timer (see [Regulation A4d](regulations:regulation:A4d)). If the competitor stops the timer after they have started it for the first time, their solve is disqualified (see [Regulation A6f](regulations:regulation:A6f)), even if they do so within 15 seconds of starting inspection.
```

**Comment by lgarron** [comment]
> I think the text at #579 is maybe not clear enough.
> Technically, if one didn't confirm that the light is green, they didn't start the solve.

I believe fff14fe406fbe42b4f034d6ffe2df35462f3f994 addressed this.

> Also, it's weird that the "if a stackmat is in use" appears only at A4d, but not at A4b.

That's a good point. Care to send a PR? :-D

**Comment by xsrvmy** [comment]
Does fff14fe actually clearly address what happens if the competitor attempts to start the timer but fails and retries again? I think someone suggested above that this is a DNF.

**Comment by pedrosino** [comment]
See #684
