### ISSUE TITLE
Advancement Criteria for National and Continental Championships

### ISSUE THREAD

**Issue by sam596** [thewca/wca-regulations#574]
I'm not entirely sure how common this is, but at the UK Championship and European Championship at least, there are additional advancement criteria in that it is required that a certain number of UK or European (respectively) Nationals must advance to the final, for obvious reasons if only they are eligible for prizes.

9p2) makes no exception regarding these advancement conditions, and I can't find any exception anywhere else.

Would this be something that needs to be explicitly mentioned in the regulations?

**Comment by lgarron** [comment]
This is indirectly allowed by 9p2) as long as everyone with better results than those competitors also advances (and at least 25% of competitors are eliminated):

> - 9p1) At least 25% of competitors must be eliminated between consecutive rounds of the same event.
> - 9p2) The competitors who advance to the next round must be determined by ranking (best x competitors) or by result (all competitors with a better result than x) in the preceding round.
>   - 9p2a) For each round, advancement conditions must be announced before the round starts, and should not be changed after it has begun. Changes must be made at the discretion of the WCA Delegate, who must carefully consider the fairness of the change.

That said, dynamic changes to advancements can allow favoritism, and it is best of `x` is fixed ahead of time. I'd be supportive of a change that explicitly clarifies whether pre-announced conditions like the ones you described are allowed.

**Comment by jfly** [comment]
@lgarron, just to be clear, this is ok because 9p2a uses the word "should" in the phrase "and should not be changed after it has begun", right? If this were instead a "must", then nationality based advancement conditions would not be allowed?

**Comment by lgarron** [comment]
> @lgarron, just to be clear, this is ok because 9p2a uses the word "should" in the phrase "and should not be changed after it has begun", right? If this were instead a "must", then nationality based advancement conditions would not be allowed?

Yes, my interpretation is that this is what allows advancement conditions like the ones described above to remain legal.

**Comment by AlbertoPdRF** [comment]
To me, saying something like "20 competitors proceed (minimum 4 from x place)" is like saying "75% competitors will proceed": we don't know the exact number in advance, but the advancement criteria is crystal clear and doesn't leave room for abuse*.

*If it's not changed during the competition, obviously :P

**Comment by lgarron** [comment]
> To me, saying something like "20 competitors proceed (minimum 4 from x place)" is like saying "75% competitors will proceed": we don't know the exact number in advance, but the advancement criteria is crystal clear and doesn't leave room for abuse*.

I'm not sure there's *no* room for abuse, but I agree it's crystal-clear.

However, can't quite tell what you're arguing for. Are you saying we should not change anything/if we should change anything, then what?

**Comment by lgarron** [comment]
Just as a point of comparison, "Alberto and everyone faster than him will proceed (up to 75% of competitors)" is also crystal-clear and possible using 9p2a), but I don't think that should be allowed.

**Comment by AlbertoPdRF** [comment]
> I'm not sure there's no room for abuse, but I agree it's crystal-clear.

Which kind of abuse would be possible? I can't see it now.

> However, can't quite tell what you're arguing for. Are you saying we should not change anything/if we should change anything, then what?

I think it's not necessary to change anything, but if it's decided that a clarification is needed, I would be completely fine with that.

**Comment by lgarron** [comment]
> Which kind of abuse would be possible? I can't see it now.

Let's assume competitors might place in the following order, and 4 Europeans + everyone faster than the 4th European advances:

- [1] A, European
- [2] B, European
- [3] C, European
- [4] D, European
- [5] E, foreign
- ... more foreign competitors
- [25] Y, foreign
- [26] Z, European
- ...

If #5-#25 convince D not to compete, they all get to compete in an extra round – at significantly more expense to competition resources. Now, speedcubing is not a sport where I would expect to see bribery or backdealing in this kind of situation, but it's logistically *possible* to incentivize abuse.

**Comment by xsrvmy** [comment]
@lgarron Wouldn't the competitor that convinced #4 to quit get disqualified for cheating?

**Comment by jfly** [comment]
Approaching things from a software perspective for a second: it's kind of nice if the regulations are explicit about exactly how you are allowed to phrase advancement conditions, because then we'd be able to have software support for exactly those things. For example, currently [the WCIF `AdvancementCondition`](https://docs.google.com/document/d/1hnzAZizTH0XyGkSYe-PxFL5xpKVWl_cvSdTzlT_kAs8/edit#heading=h.o9mb257pyp8t) supports ranking, percent, and result, but does not have support for something like "at least N of this kind of person advance".

**Comment by dancing-jules** [comment]
@lgarron - ah, I see the problem. But these criteria usually also say that a minimum of x competitors advance. So if it says "20 proceed (at least 4 Europeans)" then kicking out D will only help #21-#25. I don't know if there is a way to avoid easily abusable advancement criteria.

**Comment by theoleinad** [comment]
Is there a way to lock the number of competitors who will advance before the round starts?
Once defined it should not be changed and we avoid any issues...

**Comment by Laura-O** [comment]
> Is there a way to lock the number of competitors who will advance before the round starts?
> Once defined it should not be changed and we avoid any issues...

Exactly this regulation and the application has been mentioned and discussed a few comments above yours. Please try to avoid asking duplicate questions or repeating comments (same applies to your comment in the other thread).
Thanks!

**Comment by theoleinad** [comment]
Sorry Laura-O
It was not clear for me (and after reading the whole thread again is still unclear)
I’ll try to re-read the regulation and try to understand it better, sorry for duplicated/repeating comments.
