### ISSUE TITLE
Get rid of Best of 1 and Best of 2 Formats for 6x6 and 7x7

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#576]
For 6x6 and 7x7 there have only been 9 rounds ever that are not in the mean of 3 format:
1 Bo1 6x6,
2 Bo2 6x6,
2 Bo1 7x7,
4 Bo2 7x7.
All but one of these were 2012 and earlier

I think these roundtypes should no longer exists in our regulations for 6x6 and 7x7. These events should only be allowed to have mean of 3 and best of 1/mean of 3 for combined rounds.

**Comment by Laura-O** [comment]
Your post is actually missing the reasoning: It's fine that you think it should be different, but why? 😄 
The fact alone that something is not used frequently is not a reason to remove it completely.

We already changed possible formats in the last regulation release (see #453). We decided to keep the option for Bo2 and Bo3 because it might be helpful to have an alternative. I can't remember the examples when this could be helpful, but as it obviously doesn't hurt (i.e. it's not used and not abused), I do not see a reason to remove it.

**Comment by Jambrose777** [comment]
Consistency among competitions.
Right now an organizer can hold a bo1/bo2 round of these events, and thus not offer the potential for a mean to all competitors attending the competition. Whenever having the competition approved, it can only be recommended to not use this format to ensure fairness among all competitions, but they can ultimately have the format with no rhyme or reason. 

As well, this will provide less confusion among the competitors of wca. They will know that every time they sign up for one of these event, it will be in the mo3 or bo1/mo3 format without having to investigate the competition site to ensure this. 

If I attend a competition that has a bo1 format in 6x6. I wouldn’t know until after my first solve, which would honestly be very discouraging.

**Comment by Laura-O** [comment]
If we want consistency among competitions, wouldn't we have to remove a ton of other options as well?
Why does a round format of either Bo1 or Mo3 in FMC not confuse competitors?
Same for all other events and the application of combined rounds: new competitors are frequently confused when (or if) they are allowed to do 2 or 5 attempts.

I personally couldn't care less about whether to keep the formats or not. I just don't see how keeping these options would hurt, especially as we also allow Bo1 for the shorter events (9b1, at the discretion of the WCA Board) and, as mentioned in the first comment, they are not used frequently.

**Comment by Claster** [comment]
> If I attend a competition that has a bo1 format in 6x6. I wouldn’t know until after my first solve, which would honestly be very discouraging.

I don't think a problem of competitors who don't care enough to check the schedule before a competition is worth to solve.

**Comment by Jambrose777** [comment]
I think fmc and mbld are special events aside from this due to the solid hour a single attempt takes. Varying formats for these are fine since it is so dependent on how much time is available.

3x3 and 2x2 being held as a best of 1 format is an exception that the board can grant. I think this exception can also apply to the other events as long as there is good reason, but with the current regulations bo1 formats for 6x6 and 7x7 can be announced without a good reason, and there’s nothing we can do to stop it since it is within the regulations.

At a wca Compeititon, you have guarantees. I’m guaranteed that an official will be present, that I’ll have a chair to sit in while competing, my results and records going into the website, etc...

I would like round formats to be one of these guarantees. Though we shouldn’t remove the option of a cutoff (cutoffs provide an easy way to control the amount of time), we Should know what the round format is of a given event without having to dig for it. Of course the choice between 2 round formats is fine (the presence of a cutoff) and for fmc and mbld, it’s a little different. But guaranteeing this as much as we can is important.

**Comment by Claster** [comment]
> but with the current regulations bo1 formats for 6x6 and 7x7 can be announced without a good reason, and there’s nothing we can do to stop it since it is within the regulations.

And this is bad, because... ?

> I would like round formats to be one of these guarantees.

Why do you want such guarantee? Why not to guarantee the cutoff at least 2:00 in 5x5 and time limit at least 5:00? I want to know what cutoff and time limit are without having to dig for them 😃

Furthermore, what bad happens if after solving one attempt of 6x6 or 7x7 you would suddenly know that it was your last attempt? You were still doing the best you could, so what's the problem?

**Comment by pedrosino** [comment]
Sorry Jacob, but I still fail to understand what you're saying about "I wouldn’t know until after my first solve, which would honestly be very discouraging."

Board requires round formats to be clear in the schedule. It's not like you "Should know what the round format is of a given event without having to dig for it." That already happens.

So you're saying that if we have time for a best of 1 round of 7x7 we should instead not have it? And only hold the event if we have time for a bo1/mean3?

**Comment by Jambrose777** [comment]
> So you're saying that if we have time for a best of 1 round of 7x7 we should instead not have it? And only hold the event if we have time for a bo1/mean3?

Yes. I don’t even think anyone considers holding the event in bo1 to save time, otherwise we’d see it happen more. It’s either a question of “do we have time for 7x7 or not?”. Not giving the competitors the option to achiever a mean of 3 puts them at a disadvantage to the rest of the work, which has rankings on mean of 3.
