### ISSUE TITLE
Defining a combined round for events not in 9b1

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#577]
The phases for a combined round are only defined for 9b1 with the 1st phase being best of 2.

For the events in 9b2 and 9b3, if a cutoff is present there is no definition to what the first phase of the round can be. 

An addition to these regulations may look like:
9b2a) Round formats for these events are: "Best of X" (where X is 1 or 2) and "Mean of 3". For a Combined Round, the round format is "Best of 1" or "Best of 2" for the first phase and "Mean of 3" for the second phase.
9b3a) Round formats for these events are: "Best of X" (where X is 1, 2, or 3). For a Combined Round, the round format is "Best of 1" or "Best of 2" for the first phase and "Best of 3" for the second phase.

Note: This wording would disallow for a combined best of 1/best of 2 round, which is currently possible.

**Comment by Laura-O** [comment]
I think the logic behind this is that for 9b2 and 9b3 the cutoff is self-explanatory as all combinations are equally allowed. For 9b1, this is different as BoX exist, but it is not allowed to be used for the first phase (the only possible combination is Bo2/Ao5).
I don't think this needs to be fixed, but let's hear other opinions. 😄

**Comment by xsrvmy** [comment]
Another question is, should bo1/bo3 be a disallowed format for 3/4/5bld.
IIrc a major competition used bo1/bo2 for mbld before (Euros 2016?).

**Comment by Jambrose777** [comment]
I think we should have a consistent and uniform format per event across all wca competitions. This would allow for less confusion on round formats and simplify organization choices that can be chosen without fairness in mind.

**Comment by xsrvmy** [comment]
The multi blind format is always going to change depending on available time though.

**Comment by Jambrose777** [comment]
Indeed, multi blind and fmc may need their own categories since they are more time consuming events and their formats change drastically comp to comp.

**Comment by AlbertoPdRF** [comment]
By the way, with #661 9b2) is not a problem anymore. I agree with @Laura-O that this doesn't need a fix. Others?
