### ISSUE TITLE
Does the competitor immediately need to repair a puzzle defect?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#578]
Based on a discussion about an incident at Tangerang Open 2018.

> 3j) Puzzles must be clean, and must not have any markings, elevated pieces, damage, or other differences that significantly distinguish any piece from a similar piece. Exception: a logo (see Regulation 3l).
> 5b) If a puzzle defect occurs during an attempt, the competitor may choose to either repair the defect and continue the attempt, or to stop the attempt.
> 5b5b) If one part with one colored face is affected, the puzzle is considered solved.

My interpretation of this is that 5b gives the competitor several options they *may* take, but they *must* take one of those options to avoid violating 3j).
5b5b) covers if the puzzle defect happens at the very end.

We should either add a "must" somewhere in 5b, or explicitly clarify what is okay.
In particular, if the consensus is that the competitor does not need to repair the puzzle, I think we should add at least a Guideline clarifying whether this also applies to BLD.

5b doesn't really mention anything about "intentional" vs. "accidental" puzzle defects, so this affects whether a competitor can allow themselves to feel the puzzle orientation for blindfolded (by e.g. popping a center cap).

**Comment by xsrvmy** [comment]
A problematic scenario would be if a spectator picks up a center piece.
Also there are unfixable pops. For example, a broken center, or a center pop that requires taking out other pieces to fix

**Comment by lgarron** [comment]
> 5b doesn't really mention anything about "intentional" vs. "accidental" puzzle defects, so this affects whether a competitor can allow themselves to feel the puzzle orientation for blindfolded (by e.g. popping a center cap).

#538 just landed, clarifying that the competitor is not permitted to cause puzzle defects intentionally.

> A problematic scenario would be if a spectator picks up a center piece.
> Also there are unfixable pops. For example, a broken center, or a center pop that requires taking out other pieces to fix

Do those add any considerations specific to this issue?
(They might – I'm just not seeing any.)

**Comment by xsrvmy** [comment]
1. The competitor unintentionally receives assistance from the spectator. This is already a problem if the spectator touches an edge, but edge pops are extremely rare nowadays.
2. These pops only occur on 6x6 and 7x7 usually, which are mo3 events. I think a competitor should be allowed to finish the solve if only a center pops out.

An additional point: In FMC, the puzzles are not required to stay 3j compliant throughout the attempt. The same principle should probably apply for any other defects.

I think one way to deal with this is to specify that choosing to not fix the defect must not provide a significant advantage in solving the puzzle (eg. bld, different moves are possible). #533

**Comment by notkevin888** [comment]
Given the nature of some defects (such as corner twists - this is specifically coming from Incident 16 from CubingUSA Nationals 2018), I think it should be reasonable to add some kind of modification saying that a competitor may wait to fix defects until a later time in the solve.

**Comment by xsrvmy** [comment]
https://www.youtube.com/watch?v=v-wyJgLfW58
Also here is an example of a former NR broken after a unfixed pop. It is unlikely that this gave the competitor any advantage.

**Comment by xsrvmy** [comment]
Similarly, what if a piece breaks in the middle of an attempt? Does that then automatically DNF the attempt? These occurences could be problematic considering that pieces mostly break on 6 and 7, which are also mo3 formats.

**Comment by xsrvmy** [comment]
Another clarity issue: What is considered 'immediate'?

**Comment by lgarron** [comment]
> Another clarity issue: What is considered 'immediate'?

Before they perform new moves.

**Comment by xsrvmy** [comment]
@lgarron That definition has unintended consequences though. If a center cap pops off in the middle on a pll you would likely have done moves before realizing a pop occurred. Also sometime you make moves when fixing a pop.

**Comment by theoleinad** [comment]
I guess a clarification is needed for center pieces...
For example:
If a piece with only one colour Is deattached from the cube accidentally, the competitor may continue with the attempt. (Since there's no advantage of 1 color missing from the solved state)
e.g. center, edge or corner cap...
Afterwards the rule 5b5b will apply at the end.

Or do the competitor must put the missing cap piece right after it pops (center for example)?
