### ISSUE TITLE
5b3b: What about big cube defects?

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#58]
If a big cube pop involves two corners, this might result in CP parity, which requires more than 4 pieces to be taken out to fix. 

Suggestion: Allow 8 pieces for 4x4x4,  11 pieces for 5x5x5, 14 for 6x6x6, and 17 for 7x7x7. Or limit how many pieces are allowed to pop (DNF if >N pieces pop out) so you can't get CP parity when the puzzle is being repaired.

**Comment by lgarron** [comment]
Question: how much of this can be solved by leaving it at the judge's/Delegate's discretion? This goes under the umbrella of "how do we avoid hurting competitors who aren't trying to cheat, while still preventing cheating". (Or replace "cheating" with "gaining an unfair advantage".

**Comment by lgarron** [comment]
@Sa967St: If you'd like to do something about this, could you take the initiative?

**Comment by SAuroux** [comment]
Keep it simple...

## Proposal

5b3b) If, after repairing the puzzle but before the end of the attempt, the competitor finds that the puzzle is unsolvable, he may disassemble and reassemble a reasonable amount of pieces to make the puzzle solvable, at the discretion of the delegate.

**Comment by lgarron** [comment]
How about at the discretion of the judge?

Making this a Delegate responsibility is a bit weird. Are you supposed to
stop and call over the Delegate before proceeding?

»Lucas Garron

**Comment by SAuroux** [comment]
no, you're right. just replace "delegate" by "judge".

2013/12/11 Lucas Garron notifications@github.com

**Comment by Laura-O** [comment]
This hasn't been updated in nearly 4 years.
Closing this for now as this has obviously never been a problem in practice.
