### ISSUE TITLE
What happens if a puzzle is moved by impacting another object after timer stop?

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#585]
This is due to a recent incident at Waterloo for Square-1. When my puzzle was released, it was in a non-+2 position, but attempted to roll to a plus 2 position, before it was aligned by hitting my phone camera mount. From what I heard from my delegate, someone from the WCA called for a DNF by regulation A5b for assistance, but that regulation does not apply in the timeframe of when this occurred. No penalty has yet been applied to this solve, but a +2 would be fair.

So what should be the verdict in this case? I also remember my delegate saying that if the cube hit the display timer then there would not have been that discussion since the timer is part of the normal setup.

Incidentally, the camera partially prevents the puzzle from falling off the table. Is a competitor allowed to use anything else for this purpose? (eg. a warm-up puzzle, the cube cover)

**Comment by saranshgrover** [comment]
I think A5b applies until a "solved state" has been reached and according to 10b, the collision with the phone would occur before the solved state. Hence, it should be a DNF.

**Comment by xsrvmy** [comment]
@saranshgrover A6a) The competitor stops the solve by releasing the puzzle and then stopping the timer.

**Comment by Laura-O** [comment]
The "resting state" ([10b](https://www.worldcubeassociation.org/regulations/#10b)) of the puzzle is considered at the end of the attempt. As the puzzle was in a +2 puzzle then, it should be a +2. There are several precedents for this case.

A5b is more about receiving active help while inspecting or solving. You also don't get a DNF when a puzzle falls down and touches the floor although you could argue that the floor assisted.

**Comment by xsrvmy** [comment]
@Laura-O How can a puzzle be considered resting if is it moving towards the camera and a face is attempting to move?
Also I am not personally even sure that the puzzle even reached a +2 state (the cube was out of frame when this happened), but it was likely going to result in a +2. I am only bringing this up because there is not clear decision as to what happens if the camera affects the puzzle state after release.

**Comment by jfly** [comment]
> @Laura-O How can a puzzle be considered resting if is it moving towards the camera and a face is attempting to move?

It is *not*. Resting means when the puzzle has stopped moving. Whatever state the puzzle is in when it stops moving, that's what we care about. It doesn't matter if it hits a camera on the way or not. I could see a camera being just as likely to help as to hurt.

**Comment by xsrvmy** [comment]
If this is true my attempt should not be a +2 without question. I would have given myself a +2 if this happen at home though. That's why I brought it up.

**Comment by jfly** [comment]
@xsrvmy, according to my understanding of your original description, this should not be a +2. It's possible I'm misunderstanding the description, though.

I don't think we're going to make any more progress on this until we start talking to the person you mention in your first post: "someone from the WCA called for a DNF by regulation A5b" Who is this person? Can we add them to this thread and hear their thoughts on this?

**Comment by xsrvmy** [comment]
Unfortunately I do not know who the person is.
