### ISSUE TITLE
Can previous results be disqualified 

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#586]
2k appears to allow disqualification of previous events. This appears to be inconsistent with 2j, where previous results from an event cannot be disqualified.
Note that 2k is the penalty named for not staffing when asked to (1e2 1f2).

**Comment by pedrosino** [comment]
If the results are suspect (2k2a), I believe yes.

1e2 and 1f2 refer to 2k in general, which talks about possible disqualifications.

**Comment by xsrvmy** [comment]
I'm talking about the following scenario:
- Competitor finishes 3x3 round 1.
- He is asked to judge the next group and refuses.
Can his results from 3x3 round 1 be disqualified? If the answer is no, the wording in 1e2/1f2 penalties should probably be changed.

And yes, I know that 2k2a is an exception.

**Comment by Laura-O** [comment]
Once more: please read the regulations and do not use Github issues as Q&A.

Answer to your question:
2j2) If a competitor is disqualified during the course of an event, their earlier results remain valid. Exception: cheating or defrauding (see Regulation 2k2a)

There is absolutely no reason to change 1e2/1f2. If a competitor has no attempts to do, a disqualification for not judging has no consequences.
