### ISSUE TITLE
Clarify what happens if a competitor using a camera gets a pop/drop and needs to go to the other side of the table

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#587]
The current regulations would require that the camera monitor be out of sight/off. If the monitor is on, the competitor inadvertently sees the camera and the result is a DNF.
However, seeing the camera screen in this manner does not provide an advantage, and not allowing this gives competitors who are unable to turn off their camera screens a disadvantage.
Should there be a clarification for what happens?

**Comment by theoleinad** [comment]
They can ask the judge to cover the screen.
They can configure the camera to turn the screen off after few seconds.
Or they can just cover the screen before the attempt starts.

There might not be an advantage, but the rule is clear, they can't interact with electronic devices...
**_2i) While competing, competitors must not use electronics or audio equipment (e.g. cell phones, MP3 players, dictaphones, additional lighting)._**

Perhaps the word "use" should be changed to "use and/or interact" ...
