### ISSUE TITLE
Is DNF a fair penalty for a misscramble?

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#588]
Disregarding isolated incidents, most misscrambles are either replaced with extra or dnfed post-comp. However, is a DNF too harsh for a misscramble since it is not the competitor's fault? This is mostly a problem if the average already has a DNF, the competitor fails to make cutoff if the misscramble is replaced with a DNF, or if the competitor fails to podium/advance to next round because of a misscramble. This can especially be a problem with 4bld and 5bld.

A possible, less harsh penalty would be to replace the solve with the slowest non-DNF single in the average. This has the same effect as giving a DNF unless there is already a DNF in the average. The problem with affecting rankings/cutoffs still remains.

**Comment by Claster** [comment]
> most misscrambles are either replaced with extra or dnfed post-comp.

Umm... What? When are they dnfed?

**Comment by xsrvmy** [comment]
If a scramble for a record is found to be incorrect after the competition, isn't the solve DNFed?

**Comment by dancing-jules** [comment]
@xsrvmy - have you ever heard of 6.88 OH? The only identified it as a mis-scramble after the comp and they decided to leave it. Had they identified it during the comp, he would have gotten an extra.

**Comment by AlbertoPdRF** [comment]
The general approach is to not punish the competitors for something that's not their fault. I'm closing this issue.
