### ISSUE TITLE
Extra attempts and advantage

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#589]
This is related to #399.

A competitor can potentially gain an advantage by choosing to (or not to) appeal for an extra attempt if an incident occurs that does not invalidate the attempt (eg. early cover lift, distractions, incorrect callouts during inspection, new competitor +2). For example, if a judge lifts the cover before the competitor confirms readiness, but he is not affected by this, he can still ask for an extra attempt if he messes up. Should this be clarified?

**Comment by lgarron** [comment]
The competitor has the right. It's on the organization team to minimize the chance of this happening.

We have the WCA Mission/Spirit and https://www.worldcubeassociation.org/regulations/#11d for edge cases, so I don't think there's anything useful to do here.
