### ISSUE TITLE
Should A1b1 exception be moved to a separate regulation in article B?

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#596]
A1b1) A Stackmat must be used in addition to the stopwatch. Exception: for events without inspection where the competitor is expected to exceed 10 minutes, use of the Stackmat is optional.

The only events without inspection are blindfolded events and FMC, and FMC never requires a stackmat. Should the exception be moved to article B due to its scope?

**Comment by Laura-O** [comment]
> The only events without inspection are blindfolded events and FMC, and FMC never requires a stackmat. Should the exception be moved to article B due to its scope?

No.

It is exactly the logic we want to have here: describe the general procedure in A, mention exceptions in A and supersede procedures in B.
