### ISSUE TITLE
Clarify if the competitor can test the timer right before a BLD attempt

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#599]
We recently clarified that [you can't test a timer during inspection](https://github.com/thewca/wca-regulations/pull/593).

We just had an incident at CubingUSA Nationals where the competitor tested the timer before a BLD solve.

B2 is a little unclear about how the competitor indicates readiness:

> B2a) The judge resets the timer(s) and asks "READY?" as in Regulation A3b1. The competitor must be ready to start the attempt within one minute of being called, else the competitor forfeits the attempt (DNS), at the discretion of the judge.
> B2d) The competitor starts the attempt by removing their hands from the timer, thus starting the timer. (This also starts the solve.)

> A3b1) When the judge believes the competitor is ready, the judge asks "READY?". The competitor must be ready to start the attempt within one minute of being called, or else the competitor forfeits the attempt (DNS), at the discretion of the judge.
> A3b2) The competitor starts the attempt by confirming that they are ready, and the judge uncovers the puzzle and starts timing the inspection.

I think we should clarify that testing the timer is clear as long as the competitor didn't indicate readiness and didn't touch the cover while testing.

**Comment by lgarron** [comment]
Alternatively, I think it's sufficiently clear and fair if we add a Regulation saying that putting your hands on the timer indicates readiness.

However, I don't quite feel comfortable with the idea of taking away the ability to test your timer for BLD.

**Comment by xsrvmy** [comment]
How about the competitor is not allowed to touch the cover during a timer test?

**Comment by cubewhiz** [comment]
I don't understand why a competitor in BLD needs to confirm readiness at all. I especially don't see the need to test the timer--it's probably been working all day, so it still works when you sit there to do a BLD attempt.

**Comment by pedrosino** [comment]
I agree with Bob here. I never confirmed to being ready before a bld attempt.

**Comment by xsrvmy** [comment]
@pedrosino It's more like the judge needs to confirm he is ready to start the stopwatch on multi/big blind.

**Comment by dancing-jules** [comment]
I think we should allow timer tests in blind events. There are multiple cases:

1. Competitor expects to take more than 10 minutes and foregoes the stackmat timer: No stackmat timer means not timer test. Case closed. 

2. The (possibly cumulative) time limit is 10 minutes or less: No stopwatch involved at all. The competitor can reset all they want as long as they don't lift the cover. The result is counted the moment the stackmat timer stands still for the first time after the cover is lifted. 

3. There is a time limit of more than 10 minutes and the competitor chooses to use a stackmat timer as well: This is where things get interesting. So the competitor lifts their hands off the timer. The judge assumes it's the beginning of the attempt and therefore starts a stopwatch. The competitor resets their timer without lifting the cover. The judge now stops and resets their stopwatch. 

The problem with the procedure in 3 is of course that the judge might need a few seconds to reset their stopwatch while the competitor might not grant them that time. Will the competitor then DNF if they exceed 10 minutes? (The second problem is of course irregular enforcement of A1b in the first place.)

**Comment by cubewhiz** [comment]
I still don't understand what the "test" is for. Is it to see if the timer is working?

**Comment by lgarron** [comment]
> I still don't understand what the "test" is for. Is it to see if the timer is working?

Yes.

**Comment by cubewhiz** [comment]
The problem is that B2a is rarely followed in practice. At a recent competition, I noticed that a vast majority of competitors start the timer to begin their solve before they are even asked if they are ready (and worse, that almost all judges don't bother to ask if the competitor is ready).

**Comment by dancing-jules** [comment]
@cubewhiz - what do you mean? How does the judge decide when to lift the cover if they don't know whether the competitor is ready? Why would a competitor start the timer if the cube was still covered? (unless it eas a timer test).

Or are you talking about blindsolving?

**Comment by dancing-jules** [comment]
@cubewhiz - Do you mean for blindsolves specifically? In a blindsolve the competitor starts the attempt. So there is no need for the judge to ask them whether they're ready. If anything the competitor should make sure the judge is ready.

In sighted solving the judge starts the attempt by lifting the cover - hence the need to make sure the competitor is ready.

**Comment by cubewhiz** [comment]
> @cubewhiz - Do you mean for blindsolves specifically? In a blindsolve the competitor starts the attempt. So there is no need for the judge to ask them whether they're ready. If anything the competitor should make sure the judge is ready.

Yes, I'm referring to blindsolves. It's in the title of this thread, after all, and I'm referring to Article B.

Did you read [B2a](https://www.worldcubeassociation.org/regulations/#article-B-blindfolded)? I'm referring to specifically the first part:
B2a) The judge resets the timer(s) and asks "READY?" as in Regulation A3b1.

Since this is practically never done, I suggest removing it. Instead, I'd prefer if a BLD competitor wants to test the timer, they specify such to the judge. Timer testing in BLD wouldn't be a problem if B2a is followed, but since it rarely is, I think it should be on the competitor to let the judge know they are testing the timer. Otherwise, it could be construed as starting the attempt.

**Comment by dancing-jules** [comment]
You're right. I had not looked up the specific reg and had assumed it was a general reg that applied to all solves. 

Yes, it doesn't make any sense there. If anything, the judge should say that they are ready to judge (especially if the time limit is over 10 minutes). 

Maybe something about timer tests in blind should be put into the guidelines. Like "Timer test (starting, stopping and resetting the timer before the solve, without lifting the cube cover) are allowed, if the competitor informs the judge beforehand."

**Comment by cubewhiz** [comment]
I don't think the judge needs to be asked to be ready--if they are present at their station with the competitor and the covered puzzle, they should be ready. I would like to see the first part of B2a removed, but the rest of it can stay. Even if the judge is not ready, once the competitor starts, they have some time before they need to take any action (other than watch to make sure moves are not made or something like that).

I think the guideline is an agreeable solution.

**Comment by dancing-jules** [comment]
In general I agree, the judge should be ready at all times. The only exception is see is when a stopwatch is in use.

The one-minute-rule about getting ready also makes sense.

**Comment by lgarron** [comment]
> Timer testing in BLD wouldn't be a problem if B2a is followed, but since it rarely is, I think it should be on the competitor to let the judge know they are testing the timer.

While I would *like* judges to act consistently, I think it's okay to expect more of blind solvers, and I agree with you that this seems like the best tradeoff at this point.
