### ISSUE TITLE
Guidelines for allowing competitors to bring their own equipment and accommodations

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#603]
We've had many questions around what the competitor is allowed to have at a solving station:

- Are they entitled to a chair?
- Does the chair or table need to be some reasonable height?
- Is the competitor allowed to bring something to adjust the chair height/comfort (e.g. a pillow) or even bring their own chair?
- How large of a mat does a competition need to provide? (This one is specified now.)
- How thick of a mat?
- What surfaces are allowed below feet solve mats? Can the competitor bring their own?
- Can a competitor request alternative Square-1 inserts, e.g. plastic instead of paper?

I think we're converging on the answer that the Delegate may accommodate a request, as long as:

- it still meets the Regulations, and
- if the competitor brings their own equipment for a solving station, it must be available to all competitors, and
- the Delegate notes any requested accommodations in the report.

So a competitor might be allowed to bring their own chair as long as any competitor may use it. Perhaps they could bring their own surface to put below a feet mat as long as any competitor may use it.

The Delegate still has discretion to reject anything they feel is unfair, difficult to vet, or would disrupt the competition. And they could require the competitor to bring enough to level the playing field, e.g. one mat surface per planned feet solving station, or enough Square-1 plastic inserts to use for all competitors.

**Comment by lgarron** [comment]
Some past issues:

- #90 Stackmat requirements/loopholes
- #91 Is every competitor entitled to one?
- #216 Clarify mat requirements for feet
- #255 Allow competitors to bring their own chairs/stools for feet
- #304 Allow custom mats?
- #335 Define size of full-size mats
- Recent email to WRC about Square-1 paper inserts

**Comment by pedrosino** [comment]
There used to be something in the regulations that said the solving stations should "...suit solving while standing or sitting down..." or something related.

I think it's fine to expect (and maybe to request via Regulations) that tables and chairs are of reasonable height. If a competition has 1.5m-high tables and no chairs, that's not going to work.

About competitors bringing their own chair/mat/whatever, this part concerns me:

> So a competitor might be allowed to bring their own chair as long as any competitor may use it. Perhaps they could bring their own surface to put below a feet mat as long as any competitor may use it.

>And they could require the competitor to bring enough to level the playing field, e.g. one mat surface per planned feet solving station, or enough Square-1 plastic inserts to use for all competitors.

In some cases it is not practical or possible at all for someone to bring 6-8 chairs or 6-8 mats. If they bring only 2, and everybody wants to use them, it could set the competition to a very big delay.

I know it would probably be "...under the Delegate's discretion", but someone said we already have too many of those rules, and they are hard to apply uniformly.

**Comment by xsrvmy** [comment]
Additional point to add: Can a competitor bring an object to prevent cube from sliding off the table at the end of the attempt? This could be an advantage because it can potentially prevent cap pops/breaking. (Eg. At Quanzhou side events 2017, a 6x6 fell of a narrow table at the end of an attempt, landed off the stage and exploded).
