### ISSUE TITLE
Clarify whether qualification for an event must be based on only results for that event

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#604]
The UK Championship wanted to allow competitors to compete in 4BLD and/or 5BLD as long as they have an official success in either. I believe this consistent with the mission of the WCA ("more fun"), but the Board doesn't usually allow this. Z3 does, and it's unclear how Z4+ affects it.

Either way, I think we should clear it up.

**Comment by Jambrose777** [comment]
Although in this in the spirit of WCA, you could use the same to be not in the spirit.

Qualifying time: Must be a bronze member (have a result in every event) in order to compete in 3x3. Though this is extreme, the dependency on other events irrelevant to 3x3 would be allowed.

A more practical example may be: if you want to compete in 5x5 you must have a 4x4 time under a minute. But even this is still very sketchy.

**Comment by lgarron** [comment]
> Although in this in the spirit of WCA, you could use the same to be not in the spirit.

Mission, not spirit. ;-) https://github.com/thewca/wca-bylaws/issues/2

Indeed, I should clarify that I feel this particular instance was consistent with the mission (and therefore I don't have a moral problem with the Board approving it), but I agree that the current flexibility could be in a way that goes against the mission of the WCA.

**Comment by danielkcsheppard** [comment]
A more normal qualifying criteria for 5bld would be that you need a success in 5bld to qualify.
Our requested qualifying criteria include the subset of competitors who would qualify under that, plus more.
@Jambrose777 examples don't follow that, so there's a clear differences between our case and others.

The intention is to be more inclusive and accept that some people simply haven't had enough chances to get a 5bld success.

I don't think anybody would find it strange to use 4bld success towards qualification of 5bld as they are clearly very similar events.

**Comment by xsrvmy** [comment]
I feel like if success in 4bld qualifies for 4bld, then a success in 5bld should definitely qualify for 4bld.

I feel a bit more skeptical about 4bld qualifying for 5bld though. A possibility is 4bld and 3 or 4+ points in mbld qualifies for 5bld, but then the same issue with too much freedom comes up.

**Comment by Laura-O** [comment]
@xsrvmy It doesn't matter which events qualify for which events. We need a clear rule here and that's definitely not a matrix showing all event "matches".

I think the easiest way to clean this up is allowing only qualifying limits for the specific event in the specific event, which would be a success in 4BLD to qualify for 4BLD and a success in 5BLD to qualify for 5BLD, etc.

**Comment by cubewhiz** [comment]
Sometimes you need to sacrifice inclusivity for clarity. While it would also be more inclusive to allow qualifications based on singles or averages, we now require organizers to choose only one.

**Comment by lgarron** [comment]
Given that the UK has expressed repeated desire to use results from one event as qualification for another, I'm going to refrain from pushing to clarify this in the 2019 Reg. The WCAT has discretion over this, and this may need to go in the Competition Requirements policy doc anyhow.

**Comment by AlbertoPdRF** [comment]
This is handled now in https://github.com/thewca/wca-documents/pull/40, so I'm closing this issue!
