### ISSUE TITLE
Proposal: A competitor must not interact with a mobile phone

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#605]
We've had several cases of competitors receiving notifications on a phone and dealing with them in different ways depending on a nuanced interpretation of the situation. I believe that the only enforceable line is that interaction with phones, computers, smartwatches, and similar devices is not permitted.

Therefore, I'd like to propose that the competitor competitor should place their phone in silent/"do not disturb" mode, and is not allowed to interact with a phone or similar device:
- from the start of the attempt to the end of the solve in timed attempts,
- any time during the attempt for FMC.

If they touch the phone, interact with the phone, or *receive any notification on the phone* (regardless of whether they act on it), the attempt is disqualified.

This is a fairly strict line, but unfortunately a single bit of information (receiving a certain innocuous notification or not) can be used for cheating, e.g. for an audience member to tell you if you have parity left in BLD.

There are practical steps a competitor can take to place their phone in this mode during a round, which we can document in Guidelines. For example, an iPhone cannot disturb the competitor if they:
- place it in "do not disturb" mode
- make sure there are no alarms scheduled (there's an icon in the upper right of the phone to indicate this), and
- keep their phone in their pocket, or place it face-down on the table.

@thewca/wrc-team: Do you think this is reasonable?

**Comment by pedrosino** [comment]
I think this is a good idea from the perspective of not allowing cheating, but may become hard to put to practice. If I have my phone in my pocket, the judge may not be able to tell that I received a notification (it could be on vibrate-only mode).
We'd probably have to require phones to always be put on the table, but if the competitor says they have no phone, will the judge inspect their pockets?

**Comment by lgarron** [comment]
> If I have my phone in my pocket, the judge may not be able to tell that I received a notification (it could be on vibrate-only mode).

Indeed, I think this is the point at which we have to trust the competitor. If they ignore it, they're probably not cheating. And if they're willing to cheat using notifications in their pocket, they have other undetectable options (e.g. putting a device in their shoe, or using a small second phone in an additional pocket). I'm willing to live with that.

**Comment by xsrvmy** [comment]
@pedrosino Some phones screens are not covered completely when put face down, so that might not work if your phone settings are incorrect.

Also, does this include cameras (eg. a camera turning off during a bld attempt and beeps in the process)?

**Comment by vinitnalhe** [comment]
I believe this rule should be enforced. At the same time competitors should be discouraged from using their mobile phones as stop watches for events such as big bld and muiltblind.

**Comment by cubewhiz** [comment]
Where do you draw the line? What if a competitor is wearing a smart watch and glances at the notification on it during a solve?

**Comment by lgarron** [comment]
> Where do you draw the line? What if a competitor is wearing a smart watch and glances at the notification on it during a solve?

The line is not interacting with electronics. Smartwatches would be treated like smartphones here.

**Comment by xsrvmy** [comment]
I think that if this is implemented, there needs to be something about the competitor must actually see the notification (eg. receiving a notification on a phone used as a camera should not be a DNF unless the notification is audible).
