### ISSUE TITLE
Clarify when Delegate discretion is "routine"

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#607]
Delegate reports can have a lot of incidents these days. I think it would be easier to keep up with them if incidents were divided into two parts:

- These incidents were happened and we think they were clearly covered by the Regs.
- These incidents happened and:
  - we want Delegates/the WRC to take note, or
  - we're not sure we took the right approach / are looking for feedback / think the Regs should be changed.

We could annotate all instances of Delegate discretion with whether they should go in the Delegate report, and whether they should be considered "routine" (e.g. judge didn't reset the timer) or not.

**Comment by Laura-O** [comment]
We had a discussion about the format of reports in a meeting with team leaders and seniors some weeks ago. I think at least most of us agreed that with the current way we write reports, they should be more concise and incidents which are 100% clearly covered by the regulations shouldn't be mentioned at all.

The report form also says: "Please make sure to mention only concrete cases, not generic events (e.g., regular +2 and DNF).". So I think the first part shouldn't even be in the reports now.

**Comment by Mollerz** [comment]
I think the note mentioning generic cases and stuff should be made more prominent on the page.

It's a pet peeve of mine seeing standard +2s and DNFs in the report, or the very first incident being "Usual +2s and DNFs!" - Argh!

**Comment by julesDesjardin** [comment]
I still prefer to read reports full of basic cases, this way we're sure we don't miss any more serious incident. An almost empty report with only "Just the regular +2/DNF" always makes me wonder whether the delegate took decisions that they thought were correct, but were actually more complicated and needed some feedback from other delegates/WRC.

**Comment by cubewhiz** [comment]
I've been transitioning to a hybrid approach in which I record all incidents (including routine ones), but only reporting the interesting ones. We did this for CubingUSA Nationals. Otherwise, there would have been nearly 80 incidents. Maybe we should ask Candidate Delegates to be more thorough and report all incidents and ask Full Delegates to report only non-routine incidents.

**Comment by AlbertoPdRF** [comment]
Yep, for Euro's we also had a bunch of routine incidents that we got rid of before posting the report.
