### ISSUE TITLE
A2 and A3 don't describe "calling the competitor"

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#608]
As they are now, there's no mention to the competitor being called from the waiting area.
Also, it's not clear when the 1-minute-to-be-ready-to-start-the-attempt begins.
Lastly, perhaps we should revisit B2 about judge asking "READY?".

**Comment by xsrvmy** [comment]
Should it even be 1 minute from being called? Sometimes a competitor still needs to wait for a station after been called and won't have enough time to setup the camera.

**Comment by xsrvmy** [comment]
Bump: Should there also be a warning that the 1 minute time limit is almost up like in inspection and FMC, since this concern the validity of a result?

**Comment by pedrosino** [comment]
Re-reading this now, I think we don't need to explain what is "calling the competitor".
However, I think a clarification about the 1 minute would be good. It's not clear if the deadline is from when the competitor is called by the judge/runner, or when they arrive at the station, or when the judge asks Ready?

Something like
A3b1) When the judge believes the competitor is ready, the judge asks "READY?". The competitor must be ready to start the attempt within one minute of _**arriving at the solving station**_, or else ~~the competitor~~ _**they**_ forfeit~~s~~ the attempt (DNS), at the discretion of the judge.
