### ISSUE TITLE
Would it be legal to have a box to put finished cubes in so that they aren't all in a messy pile on the desk/table during a MBLD attempt?

### ISSUE THREAD

**Issue by TommyCherry** [thewca/wca-regulations#609]

**Comment by lgarron** [comment]
I think this could be incorporated into #603.

What would be the main purpose of this box? To avoid bumping them off the table? To make them easier to count?

**Comment by xsrvmy** [comment]
I think the purpose is to reduces the possibility of confusing a completed puzzle with an untouched puzzle, especially on smaller tables

**Comment by abunickabhi** [comment]
This will be very useful if the size of the table is quite small at the MBLD venue.
