### ISSUE TITLE
Add more puzzles to 4g1? (allow incorrect scrambles)

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#61]
> [4g1](http://www.worldcubeassociation.org/regulations/#4g1)) Exception: For the 6x6x6 Cube and the 7x7x7 Cube, it is not necessary to correct the scramble, at the discretion of the WCA Delegate.

In particular, Megaminx. Sometimes, Delegates already allow this. See [Bob's post](http://www.speedsolving.com/forum/showthread.php?39847-WCA-Documents-Updated-January-1-2013&p=883117&viewfull=1#post883117).

**Comment by pedrosino** [comment]
I agree that megaminx should be added. It's very hard to check, because of the multiple different color schemes, and if you do a ++ instead of -- it's not a big difference, just the same way as the 6x6 and 7x7.

Oh, and not always you have a 1-minute solver, so solving and rescrambling can take some time.

**Comment by sarahstrong314** [comment]
I also agree that Megaminx should be added to 4g1. It takes a considerable amount of time to solve if you're not familiar with different colour schemes, which really does slow down the competition. Plus, theoretically, the scramble doesn't affect the solve time as much as it does for cubic puzzles. It's also one of the easier scrambling notations to mess up performing.

**Comment by jbmertens** [comment]
What about 5x5?  It is logistically more of a hassle than megaminx, typically taking longer to both (mis)scramble and (re)solve.

**Comment by sarahstrong314** [comment]
I'm neutral on adding 5x5x5. It's not that difficult to scramble correctly (relative to 6x6x6, 7x7x7 and Megaminx).
