### ISSUE TITLE
Move competition requirements into a separate document

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#610]
Hello WRC,
The following are items that are needed for a competition to be official, I have also listed what changes require board / competition announcement committee(WQAC) approval to change the information and changes that can be made at the discretion of the delegate. Some of this information probably requires a conversation about the necessity of it, but I felt like I'd list everything that is needed.

# An official competition must have:
- A date that the competition is held on
- One or more official events
  - Events may be tentative, tentative events must be listed in the official events
  - Any events not listed as official events will not be accepted as official results 
- One or more locations
  - A location may be listed as a general location and the specific location must be sent to the competitors prior to the competition with board approval
- At lease one competitor
- Clear instructions on how to register, state if on-site registration is allowed or not, and state a refund policy
- A registration period
- A schedule
- May have one or more organizers (not must) (covered in 1a?)

- Change 8a3) Have a designated WCA Delegate in attendance. to 8a3) Have **one or more** designated WCA Delegate**(s)** in attendance.
  - The delegate must be of the country the competition is in
  - or the competition is in a country which has no delegates
  - Exception: the local delegate is in agreement with the foreign delegate delegating.
- Move Z4 to a must regulation (competitor limit)
- Change 8a4) to remove remove exception (the exception is currently used, and I'm pretty sure it will make things easier for the approvers and delegates to just remove the exception)
- A name complying with the Competition Naming Policy (insert naming policy to the regulations?) 
- Comply with the proximity policy with exceptions (insert naming policy to the regulations?)

# Requires approval from board / competition announcement committee(WQAC) to change:
- Deletion of the competition (before or after the competition occurs)
- Changing the name of the competition
- Changing the location of the competition
- Changing the date of the competition
- Changing the events of the competition
- Changing the competitor limit of a competition
- Changing the delegate(s) of a competition
- Changing the organizer(s) of a competition
- Additional registration periods
- Shortening a registration period
- Extending registration periods which have not yet been closed

# Can be changed without approval:
- Ending a registration period early
- Changing event information (# of people in rounds, time limits, cutoffs, # of rounds)

# Questions:
- 8a5+) RECOMMENDATION The competition should have at least 12 competitors. - Where did the number 12 come from? there are plenty of competitions that have <12 competitors for very valid reasons.
- Should 8a7 be moved to environment? Otherwise it seems like we should also list items like, use official generated scrambles, otherwise it's kind of redundant.
- What is the specific reason to have a policy over a regulation? If these policies are to be followed in order to hold competitions, shouldn't they also be part of the regulations?
- Isn't 8a3 redundant via 1a?
- Isn't 8af violated by anything in Z4?

I'd like to know if the above can/should be implemented into our regulations. Sorry that this is a lot, we can also create subissue for some of this if needed.

**Comment by AlbertoPdRF** [comment]
The Board had compiled a list with some of these changes too, but we have not shared it yet :P We would rather prefer to figure out all the competition announcements thing first and then request all the changes at once.

For now, I will make two comments only:

- I believe that the things that are covered by policies should not be included in the Regulations, at least not now. These are things that can constantly change and probably not fit in there.
- Regarding 8a3), as we have [1c+)](https://www.worldcubeassociation.org/regulations/guidelines.html#1c+), there's no need to make the change that you propose. 1c+) is cleaner than to add what you say to every Regulation that says "WCA Delegate".

**Comment by SAuroux** [comment]
> Change 8a4) to remove remove exception (the exception is currently used, and I'm pretty sure it will make things easier for the approvers and delegates to just remove the exception)

I don't understand this. Is a _not_ missing somewhere? How does it make things _easier_ if the exception is removed?

> # Requires approval from board / competition announcement committee(WQAC) to change:
> - Additional registration periods
> - Shortening a registration period
> 
> # Can be changed without approval:
> - Extending registration periods which have not yet been closed

I find this rather inconsistent and complicated. It would be way easier to handle all changes to registration periods uniformly.

**Comment by Jambrose777** [comment]
> I don't understand this. Is a not missing somewhere? How does it make things easier if the exception is removed?

Removing the exception is something that has been talked about a lot. We have some competition requests come in after the 28 day marker and it requires a sometime controversial vote that is not always consistent. Being able to have the 28 days be an absolute date to announce by just gets rid of the grey area. Plus the competitions announced within the 4-2 week period often may not have the upmost quality that a competition needs since they were ill prepared to make the 4 week announcement.

> I find this rather inconsistent and complicated. It would be way easier to handle all changes to registration periods uniformly.

This is how things are currently handled. Maybe all changes should require approval.

@AlbertoPdRF Sorry, I had had a quick conversation with Bob, and it resulted in me compiling this message. Sorry if it had jumped the gun on anything.

**Comment by lgarron** [comment]
For what it's worth, I think the Regulations are currently the right place for this. I'd welcome a PR to add this.

If we make it a separate document, I think we should think about structuring requirements that are outside of the Regulations (e.g. scrambles, list of countries) better. A good start might be:

- Mention them in the section at the top o the Regs where we current mention the Guidelines.
- Link them all from https://www.worldcubeassociation.org/regulations/about/

We should also have one of those links specify how they can be updated.

**Comment by Jambrose777** [comment]
I'll just tack this on here:
> Z4b+) EXAMPLE Examples for reasons which justify a change of the competitor limit after the competition was announced: the venue was changed or the number of registrations is higher than expected.

Since we generally recommend setting a limit even if one is not selected, "the registrations is higher than expected" argument isn't really used anymore. This is because the highest expecting number of registrations is usually what is inserted into the competitor limit. Maybe we should remove the second example.

**Comment by Laura-O** [comment]
> For what it's worth, I think the Regulations are currently the right place for this. I'd welcome a PR to add this.

I think we should discuss this in the WRC and decide about it.
This is would be quite a radical addition to the regulations as this adds a lot of rules which are either not relevant for competitors or even completely invisible to them. The regulations currently already describe some internal organizational approaches, but these parts are not very comprehensive.

Adding so many regulations for the competition approval process opens the doors for a lot of other internal regulations from individual committees and we should be careful that this doesn't make the regulations unreadable for competitors.

There is also one thing that confuses me and I am surprised to see this in the list:

- The delegate must be of the country the competition is in
- or the competition is in a country which has no delegates
- Exception: the local delegate is in agreement with the foreign delegate delegating.

I think this is against the spirit of the WCA.
On the one hand, we do not have "delegates of countries" and it's not clear to me what that means. We have several delegates who do not live in the country of their citizenship and frequently delegate competitions in these areas and other delegates who frequently delegate competitions in several countries although there is a local delegate. On the other hand, the WCA does not really care about countries. We have open national and continental championships and usually avoid any sense of nationality. Therefore, talking about "regions" would be way more reasonable to me.

**Comment by Goosly** [comment]
@Laura-O Those 3 points are taken [from the delegates crash course](https://www.worldcubeassociation.org/delegate/crash-course#on-accepting-to-delegate-a-competition), but reworded by Jacob. Over there, it also mentions countries, not regions.

**Comment by Laura-O** [comment]
Well, the fact that someone wrote this in an internal document doesn't make it better. 😄 

I would not consider the crash course an official document as it mainly grew through individual people adding content when they realized that it could be helpful for delegates and/or avoid issues.

If we make this an official regulation/guideline or also an official document, it should be as precise as possible and reflect the reality. I might be wrong, but I doubt that delegates who live in another country and frequently delegate competitions in this country are always asked to provide an agreement of other delegates in this country.

**Comment by Goosly** [comment]
Yeah, I assume the most important part of those lines in the crash course is coordinating with other "local" delegates (whatever that may be) to avoid conflicting nearby competitions being planned, which should all happen well before confirming a competition, and the "being in agreement" is rather informal.

I was just pointing you to the source of those points, because you were confused and surprised :-)

**Comment by cubewhiz** [comment]
It would be nice if the WRC could discuss this and decide if these points would be better placed in the Regulations or in a separate policy. There are already policies in place regarding competition names and competition locations, so my gut feeling is that a policy may be a better place than the Regulations, but I'd love to hear your thoughts about this, too.

**Comment by Claster** [comment]
Hi,

The conclusion from WRC was not to put these requirements into Regulations, rather into a separate document, near proximity and naming policies.

Reasons for such conclusions are:
1) These requirements are not relevant for a majority of competitors, but only for organizers (and Regulations are already pretty long);
2) Since these requirements come from WQAC, it would make sense for WQAC to maintain this document, while Regulations are maintained by WRC. This will also remove a burden from us to ask the Board for Regulations' changes approval every time WQAC wants to change the requirements.

From our side, we could probably move the whole Article 8 (and partially, the Article 7) to this new document, and to replace them with "8a) An official WCA competition must satisfy these requirements (link)".

**Comment by cubewhiz** [comment]
Thank you for reaching a conclusion. I agree with you.

I will draft a policy on behalf of the WCA Board that addresses this information and we will consult the WRC for review before publication.

**Comment by dancing-jules** [comment]
I agree that the part about having to use a delegate of your own country makes no sense whatsoever. What if the delegate of your own country is unavailable? What if they live at the other end of the country and a delegate from a neighboring country is closer? What if you just like a different delegate better?

**Comment by cubewhiz** [comment]
It is not a requirement that the Delegate is from the country, but we expect proper communication in such cases. There have been competitions requested in the past that the local Delegate was unaware of, which created proximity issues to competitions that were being planned.

**Comment by lgarron** [comment]
The current plan is to move requirements out of the 

WRC thread about this: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wca-wrc/FQkUwfV5qeo/2tqazT0xBAAJ

**Comment by AlbertoPdRF** [comment]
This is handled now in https://github.com/thewca/wca-documents/pull/40, so I'm closing this issue!
