### ISSUE TITLE
Clean up definitions for cumulative time limits.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#611]
A1a2+++++ specifies that multi BLD and FMC cannot have an applicable cumulative time limit. Unfortunately, a recent competition was approved with such a format, and we had to disqualify some attempts.

(WRC-only link: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wca-wrc/W9nsUnX-_l0/uqijc_XLDwAJ)

I think we should clean up the time limit Regs. This allows us to
- Remove some implicit interpretations by replacing them with clear wording.
- Remove some Guidelines with a lot of `+`es. (A1a2+++++ is the only Guideline with 5.)
- Codify two current conventions:
  - Time limits must be announced before the competition, not just before the round.
  - Only one cumulative time limit can apply to to a given round.

**Comment by xsrvmy** [comment]
Is there any reason to not allow both normal and cumulative time limits at the same time?

**Comment by Jambrose777** [comment]
> Is there any reason to not allow both normal and cumulative time limits at the same time?

Why should you? It would be like defining 2 time limits with one overwriting the other. They both accomplish the same thing and both are used in different scenarios to help the competition flow.

**Comment by lgarron** [comment]
> Is there any reason to not allow both normal and cumulative time limits at the same time?

That debate was in #374. I don't plan to try to revise that in this PR.
