### ISSUE TITLE
Policy regarding cubes and "reasonable wear" of stickers

### ISSUE THREAD

**Issue by julesDesjardin** [thewca/wca-regulations#617]
Hi,
This topic is mostly motivated by the last Asian Championships, where delegates refused cubes because of wear of stickers, that other people (delegates or not) found perfectly acceptable.

Accepting such cubes is at the delegate's discretion, which I think creates unfair situations across the world, whether delegates are lenient are not. However it is quite hard to have an objective measurement of what "reasonable wear" is.

This is why I suggest reversing the policy, and accept any cube (for sight solving), as long as colors are reasonably recognizable. One could argue that we could use the wear of particular stickers (or pieces, which is very common on stickerless big cubes, especially corners) to gain unfair advantages, but this was already the case for stickerless puzzles altogether, and we decided that such an advantage was not significant enough, which explains why they went from forbidden to accepted. I think everyone would benefit from applying the same mentality to wear of stickers.

Delegate discretion would still exist in this rule, but instead of being between the areas of "perfect cube" and "cube with a bit of wear", would be between "cube so worn some stickers are gone" and "cube with a lot of wear", which would create less controversy.

As a side effect, by following this logic, we should also allow transparent cubes, although they are quite rare now.

What are your thoughts about this ?

**Comment by Mollerz** [comment]
In the UK we generally follow the principle that if you can clearly feel a difference between different sides based off the stickers, or if they do not take up a majority of the face, we will ask them to replace the puzzle. For example if there is a big hole in one of the stickers on one face and you could feel it we would not allow it.

If it is getting towards this point, we will ask first if they can replace it. If they cannot then we will just give a warning and say "Please resticker this cube for your next competition". We always try and lean on the side of giving a warning and not straight up disallowing it, however sometimes they are so bad that we just cannot allow it.

I think this is fair as we allow reasonable wear but do not allow potential intentional wear or too much wear. Sometimes you can receive a new cube and immediately catch a sticker which removes it from the "perfect" category which could potentially be disallowed which is extremely unfair in my opinion.

**Comment by lgarron** [comment]
Personally, I think the current policy is fine. It's becoming less and less of an issue as more competitors switch to stickerless puzzles (which is a very strong trend I observed this year for championship competitors).

> This is why I suggest reversing the policy, and accept any cube (for sight solving), as long as colors are reasonably recognizable.

Do you mean to allow any arbitrary sticker shapes?

> If it is getting towards this point, we will ask first if they can replace it. If they cannot then we will just give a warning and say "Please resticker this cube for your next competition".

While this is well-meaning, it doesn't sound like a consistent policy. :-/
The effect is that a puzzle just past a reasonable threshold is effectively allowed in some places unless maybe someone notices the same competitor's cube it across multiple competitions.

> I think this is fair as we allow reasonable wear but do not allow potential intentional wear or too much wear.

That's the spirit of the current policy, isn't it?

**Comment by xsrvmy** [comment]
> It's becoming less and less of an issue as more competitors switch to stickerless puzzles (which is a very strong trend I observed this year for championship competitors).

Stickered puzzles are still relevant for 3x3 though. The current WR puzzles for 3x3 and 3bld both do not have stickerless versions.

An additional comment for this issue:
I see the huge inconsistency as a result of two delegate discretion regulations applying to this one case. The difference between similar pieces can either be insignificant or be considered reasonable wear, and both are decided by the delegate.

**Comment by pedrosino** [comment]
> Personally, I don't think the current policy is fine. It's becoming less and less of an issue as more competitors switch to stickerless puzzles (which is a very strong trend I observed this year for championship competitors).

Do you mean "I think the current policy is fine"?

I agree that defining "reasonable wear" is difficult. Even with the original proposal, we'd still have the problem for bld events, and in those I think bad stickers matter more than sighted solving.

**Comment by lgarron** [comment]
> Do you mean "I think the current policy is fine"?

Uh, yes, that. Thanks!
(I've fixed the original post.)

**Comment by lgarron** [comment]
How would you feel about a Guideline with a rule of thumb, such as "no more than 1mm missing or ripped from an original rounded square border covering most of the surface below the sticker"?

It's not exact (and this isn't the kind of thing we should break out rulers for), but it sets *some* reasonable bound by which competitors and judges can orient themselves.

**Comment by Mollerz** [comment]
> How would you feel about a Guideline with a rule of thumb, such as "no more than 1mm missing or ripped from an original rounded square border covering most of the surface below the sticker"?

This is really arbitrary and not fun in the slightest. I definitely don't want to be getting a ruler out when I need to judge sticker wear. I have routinely accepted puzzles with reasonable wear that have more wear than this, although not much more. And 1mm of a sticker varies wildly depending on puzzle, compare a 2x2 and a 7x7 sticker sizes. What if someone has fully fitted stickers on a puzzle and there's 1mm of wear, compared to someone with regular stickers which are brand new? The fully fitted stickers that are 1mm worn are still probably covering more of the piece than regular stickers! What about stickers that are worn consistently as well, where does the original sticker start?

Maybe it's time to get some example images out? :P

**Comment by lgarron** [comment]
> I have routinely accepted puzzles with reasonable wear that have more wear than this, although not much more.

Sounds like... it's roughly the right rule of thumb?

> Maybe it's time to get some example images out? :P

That might actually be the most practical solution.

**Comment by xsrvmy** [comment]
While on this topic, 3h seems to not allow any wear on center pieces at all. This is probably a bug. #632
