### ISSUE TITLE
MultiBlind submitting number of Cubes (H1a)

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#618]
> H1a) Before an attempt, the competitor must submit to the organization team the number of puzzles (at least 2) they wish to attempt.
H1a1) A competitor is not permitted to change the number of puzzles after submitting their number to the organization team.

There are currently 2 issues with this regulation:
- the organization team can require # of puzzle submission months in advanced. Though it is useful to have this information for generating scrambles and finding appropriate assistance for the attempt, it is not very fair to have to submit months in advance as your interest and skill in the event may change.
- submitting these numbers to the organization team can cause an unfair advantage in favor of the organizers who are competing. They will have more of an idea on what score they need to achieve for their attempt, and can even base their number off of the other competitors.

**Comment by cubewhiz** [comment]
To clarify, I don't think H1a explicitly allows the org team to require the number months in advance. However, at least one org team has requested this as part of the registration process. By my interpretation, competitors are in the right to say they are not ready to submit that number and wait until just before the attempt to submit that number. Maybe a clarification is due?

**Comment by lgarron** [comment]
> submitting these numbers to the organization team can cause an unfair advantage in favor of the organizers who are competing. They will have more of an idea on what score they need to achieve for their attempt, and can even base their number off of the other competitors.

That sounds counter to the spirit of H2a2. If an organizer who cares about multi puts themselves in charge of collecting requests to break the spirit of H2a2, that's not okay.

> H1a2) A competitor may request to keep their submission private until all competitors have submitted their numbers. Once all competitors have reported their numbers, the information becomes public (e.g. a competitor may ask for the numbers of any other competitors before starting their attempt).

**Comment by Claster** [comment]
How about this change?

H1a) Before the moment that was explicitly announced by the organization team, but not until the competition starts, the competitor must submit to the organization team the number of puzzles (at least 2) they wish to attempt.

**Comment by xsrvmy** [comment]
There is another problem actually: the competitor submits all 25 cubes he brought, and the delegate rejects one of them. If the number of cubes must be specified in advance (as in strictly before puzzle submission), how can this kind of situation be resolved?

**Comment by cubewhiz** [comment]
My opinion is that the missing cube should be a DNF unless they can obtain a replacement.

**Comment by xsrvmy** [comment]
How about this?
A competitor may confirm that his puzzles are valid before deciding on the number of cubes to attempt.

**Comment by Laura-O** [comment]
> My opinion is that the missing cube should be a DNF unless they can obtain a replacement.

Why should someone get a DNF for a cube which was not even scrambled (i.e. used for the attempt)?
In general, it would be good if you would avoid sharing opinions here or at least provide an explanation why this is your opinion.

I also can't see the problem: if one cube is rejected, the competitor either hands in a different cube or he does his attempt with one cube less. Everything else would be unfair and could create very unpleasant incidents.

**Comment by xsrvmy** [comment]
@Laura-O there is a problem if the competitor is required to determine the number of cubes to attempt before submitting the puzzles, since changing the number of puzzles is not allowed.

**Comment by Laura-O** [comment]
I think the main problem is that there is no problem. 😛 

I also have asked competitors how many cubes they want to try before the competition in order to generate enough scrambles. This was just a friendly question and if I would not have gotten an answer I would have generated 50 scrambles. It's not that the number of cubes is infinite.

I simply think we should not force competitors to define the number of puzzles they want to try before they submit them. The main reason is that this only adds additional problems while it solves a problem that rarely exists.

**Comment by cubewhiz** [comment]
There is a reason for the number of cubes not being allowed to be changed and there is some room for abuse if we allow it. Here's an example:

Person A and Person B are the favorites to win.
Person A says they will solve 10 cubes and Person B says they will solve 15 cubes.
Person A goes in the first group and gets 8/10.
Person B realizes that 6 points is enough to win now, so they change their submission to 7 cubes.

Alternatively, let's say the number of cubes submitted can change when submitted puzzles are invalid.
Person B submits 15 cubes, but 8 have logos so now Person B does only 7 cubes.

**Comment by Laura-O** [comment]
That's a good example of why all competitors who are eligible to win a competition should compete in the same group.
Additionally, no offense, but this example does definitely not represent "WCA reality": competitions with different groups competing at different times are extremely rare in MultiBLD and even if they would be used, it would be very unlikely that competitors in the second group could submit their puzzles after the first group is finished.

The acceptance criteria for puzzles are often different and some delegates are stricter than others (see #617). This makes it unpredictable for competitors and giving them a DNF if they did not predict that a delegate might refuse a puzzle is unfair. This would be a regulation that might be correct for some individuals but would punish everyone else.
