### ISSUE TITLE
End Support of Gen 2 Timers

### ISSUE THREAD

**Issue by cubewhiz** [thewca/wca-regulations#619]
Production of Speed Stacks Generation 2 timers was discontinued by 2012, so all of these timers are at least six years old now (which poses a reliability issue). The Gen 2 timers were notorious for the problem of time distribution, so newer models are proven to be more accurate.

**Comment by Laura-O** [comment]
So what line of action do you propose?

Two thoughts:
- Is there any new data about the time distribution available?
I know about the gaps in the time distribution of Gen2 timers and that they were filled after Gen3 timers were introduced, but the fact that there are fewer gaps in the overall distribution now doesn't mean that Gen3/4 are more accurate. That's a wrong conclusion. Additionally, both Gen3 and Gen4 obviously have other issues (especially timer resets and other malfunctions).

- There are still a lot of Gen2 timers in use. If we decide to remove Gen2 timers, delegates/organizers will be forced to buy new hardware to replace their old timers. As long as there is no 100% clear proof that using newer timers is an improvement, I think we shouldn't do that.

**Comment by lgarron** [comment]
> but the fact that there are fewer gaps in the overall distribution now doesn't mean that Gen3/4 are more accurate.

Indeed. This shouldn't be *too* hard to test, though. (I have a 1000 FPS camera.)

> There are still a lot of Gen2 timers in use.

Do we have data on how many?

**Comment by cubewhiz** [comment]
There should be a transition period (perhaps one year) for communities that heavily rely on Gen2 timers if there are enough in circulation.

It should be easy enough to determine approximately how many Gen 2 timers are in use by scraping through some Delegate reports since that information is recorded in each report.

**Comment by Laura-O** [comment]
> Indeed. This shouldn't be too hard to test, though. (I have a 1000 FPS camera.)

How does a camera help with that?
The exact time of starting/stopping is pretty imprecise with all timers. The sensors have different sensitivities and it's impossible to define the "trigger" by 0.01 seconds, so using a camera is definitely not a reliable test setup.

> Do we have data on how many?

Delegate reports... As most delegates use the default text it should be quite easy to get an estimation.

We still have 8 Gen2 timers in Germany, which work perfectly fine and which are even preferred by some competitors.

**Comment by SAuroux** [comment]
I find the idea to ban working timers (no matter how many) that have been allowed for years absurd.

In any case, Gen2 timers are apparently still very popular:

year | used gen 2 timers | comps with gen 2 timers
-- | -- | --
2010 | 172 | 16
2011 | 248 | 27
2012 | 212 | 23
2013 | 117 | 17
2014 | 154 | 23
2015 | 106 | 18
2016 | 392 | 90
2017 | 442 | 133
2018 | 233 | 65

(Ugly) Code:
```
SELECT RIGHT(competition_id, 4) as year, SUM(CAST(SUBSTR(equipment, 12+LOCATE('Gen 2 Timer: ', equipment), 3) AS UNSIGNED)) as gen2timers, 
SUM(IF(CAST(SUBSTR(equipment, 12+LOCATE('Gen 2 Timer: ', equipment), 3) AS UNSIGNED) > 0, 1, 0)) as compswithgen2timers
FROM `delegate_reports`
WHERE LOCATE('Gen 2 Timer: ', equipment) > 0
GROUP BY year
```

**Comment by Mollerz** [comment]
I agree that they should be discontinued, but only due to the time distribution problems rather than for any other reason. Also there are some Gen2 timers that have the problem of running faster as the battery runs down, which poses a potential huge threat to result accuracy.

**Comment by xsrvmy** [comment]
Is the timer accuracy going to become 0.001 instead due to this change?

**Comment by Mollerz** [comment]
> Is the timer accuracy going to become 0.001 instead due to this change?

I think if we were to move away from Gen2 timers, then this should definitely be done. The biggest problem will be the database and how this will be formatted with the mix of times with different decimals which is a separate issue that can be discussed if this proposal goes through.

**Comment by xsrvmy** [comment]
The bigger problem is records (eg. is the AsR going to be 4.591, 4.590 or 4.599)

**Comment by jfly** [comment]
Let's not get into milliseconds on this github issue. Feel free to start a new one to discuss this if you guys are keen to!
