### ISSUE TITLE
Add 1c+) to explain delegate responsibilities.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#62]
[Regulation 1c](http://www.worldcubeassociation.org/regulations/#1c) carries a lot of weight:

> 1c) The WCA Delegate may delegate responsibilities to other members of the organisation team, but is ultimately accountable for how these responsibilities are carried out...

It's not completely obvious from a simple read of the Regulations + Guidelines how much this is used in practice. I would like to add a rule that documents our practices more clearly to anyone who is reading the Regs+Guides in order to understand the structure of our official competitions.

A simple draft:

> 1c+) [EXPLANATION] In practice, it is expected that the Delegate will delegate many responsibilities to the organisation team, such as generating scramble sequences, sending results, and allowing selected officials to make judgments on his behalf.

**Comment by lgarron** [comment]
No one's really said that they found this confusing (maybe because no one really reads the entire Regulations, but still...). Marking as `2014-wontfix`.

**Comment by LorenzoVP** [comment]
I don't think we should permit delegates to delegate generating scramble sequences and sending results to anyone. If you accept to be the delegate of a competition, these tasks are the least you can do...

**Comment by lgarron** [comment]
I don't think we have problems with the reliability of scramble generation/sending results in practice.

Closing this issue so it doesn't just linger.
