### ISSUE TITLE
Separate extra attempt for FMC and MBLD

### ISSUE THREAD

**Issue by campos20** [thewca/wca-regulations#620]
Since FMC and MBLD last 1 hour, the extra attempt should be treated differently. It's more likely to be affected by environment, other factors or interrupted somehow, since it takes longer than any other regular event.

Points I considered so far:
- We should mind the venue's schedule since it might add close to 3 hours in the competition.
- The threshold should be at delegate's call, based on her/his experience on the local. It's OK to give an extra attempt because someone's cellphone rang during a (let's say) 7x7 attempt, but I don't think an extra attempt should be given in the same situation for FMC and MBLD if it happens like once.
- Each competitor should say if they got affected to receive the extra.
- Extra for FMC might be a logistic challenge since it requires printing stuff.

**My particular case:** in my [last competition](https://www.worldcubeassociation.org/competitions/BrasiliaWinter2018), which happened in a school, a music started in the venue very loudly. It lasted for about 3 min, we had 30 min left. About 15 min later, the music started again and lasted for about 1 min. It was not on the delegate's/organizer's hands, the music is the sign for the students to leave and it is controlled by a computer. I got very distracted by the situation and it ruined my solution (I usually avg 28 and I got a 45 for that attempt).

After the attempt ended, a competitor said to the delegate: we could have more time due the music. We all know this is not permitted. I asked for an extra about 50 min later via message and the delegate cited [11e](https://github.com/thewca/wca-regulations/blob/7a0a63eb9f8fe87f4c228e72d83dcd57c3e953a9/wca-regulations.md#L306) to decline, and I think his decision was the right one based on how the regulations are as of nowadays. For this particular case, the delegate was competing as well, so it would make no sense to ask during the attempt. If I wanted, anyways, to ask during the attempt, I could wait until like 59 min, when it was clear I'd get an outlier result and bug the delegate with it during his attempt.

**Comment by Laura-O** [comment]
@campos20 I am not really sure what your proposal is and/or if there is one.

You are completely right that these events are different and the threshold when an extra attempt should be granted is higher and also affected by organizational/logistical conditions. Also, I think competitors should be expected to take more precaution in longer events (i.e. use earplugs/earmuffs).

The points you mentioned pretty much describe how these extra attempts are handled at the moment.

**Comment by campos20** [comment]
@Laura-O, ok

Proposal:

Change 11e) so the competitor may ask for an extra during the attempt or after the delegate ended her/his current attempt.

**Comment by theoleinad** [comment]
I don't think you could ask for an extra (or you shouldn't) at the very end... 
You should report the incident immediately and start the new attempt right away.

Since the delegate is competing you should not disturb him. 
But the judge should be able to give you the extra attempt, since he's the one in charge at that moment. 

So delegate basically has to "delegate" that power to the judge to decide if you might get the extra attempt or not.

**Comment by Laura-O** [comment]
Yes, @theoleinad is right: if the delegate is competing, there should be someone else who is responsible. I know this situation can be difficult for delegates (especially at small competitions when there is nobody else available), but this is definitely nothing the regulations can improve.
Therefore, I am closing this for now.
