### ISSUE TITLE
B2c makes no sense (touching cube before blindsolve)

### ISSUE THREAD

**Issue by dancing-jules** [thewca/wca-regulations#625]
> B2c) The competitor must have no physical contact with the puzzle before the start of the attempt. Penalty: time penalty (+2 seconds).

This regulation talks about blind-solving. The competitor physically cannot touch the puzzle because it is under the cube cover. It makes more sense to replace "puzzle" with "cover":

>  The competitor must have no physical contact with the **cover** before the start of the attempt.

**Comment by Goosly** [comment]
Why should a competitor not be allowed to touch the cover?
I regularly move the cover closer to the Stackmat timer before an attempt (judges usually place them in the middle of the mat) - without touching the cube, of course.

Also, in multi-blind, cube covers are replaced by papers (or similar) and it often is possible to touch cubes directly. Removing or changing B2c would allow that.

**Comment by dancing-jules** [comment]
@Goosly - ah, you're completely right - touching the cover is absolutely valid as long as you don't uncover the cube. And cube covers in multi should cover all visible parts of the cubes anyway. 

What about "The competitor must not remove the cover before the start of the attempt." Or "The competitor must not uncover the puzzle(s) before the start of the attempt."

**Comment by xsrvmy** [comment]
Cube covers are not always flat at the bottom so the competitor might be able to touch the puzzle before lifting the cover.

**Comment by xsrvmy** [comment]
Also I have already brought this up before and the issue was closed.
