### ISSUE TITLE
Cameras and flash

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#626]
The regs specifies that additional lighting is not allowed at a solving station. How does that interact with camera regulation? Specifically, can flash be on, and do indicator lights count as additional lighting?

**Comment by lgarron** [comment]
> Specifically, can flash be on

No.

> do indicator lights count as additional lighting

No, but I don't have any clever ideas other than ignoring them, since it's really unlikely anyone would use them to gain an advantage.

**Comment by xsrvmy** [comment]
On the topic of cameras, in the following regulation (2i2b)


> Exception: the competitor may wear a camera mounted on their head, as long as *it* is out of their sight...

Should "it" be replaced with "the monitor"?

**Comment by lgarron** [comment]
> Should "it" be replaced with "the monitor"?

Here, "it" was intended to refer to the camera.
