### ISSUE TITLE
Revisit clock similar pieces (3j2+)

### ISSUE THREAD

**Issue by qam022** [thewca/wca-regulations#627]
> 3j2+) CLARIFICATION On Clock, the nine inner clock faces on one side are considered similar pieces.

This guideline currently prohibits "checkerboard"-style clocks.

Example (expertly drawn in ms paint):
![illustration](https://user-images.githubusercontent.com/18506088/46216618-e953c900-c337-11e8-85c0-c54c3f5cc02c.png)

Some people like this sort of thing because of aesthetic reasons but cannot use them at competition, even though they present no advantage.

I can see why this guideline exists -- because you could put the different coloured clock faces at the top to emphasise the solved orientation. (I won't get into how currently legal custom inserts can do this too)

While trying to avoid being too complicated, making all "edge" and "corner" faces on each face similar would be a possible fix. (letters on this image illustrate which pieces should be similar)

![illustration](https://user-images.githubusercontent.com/18506088/46216712-215b0c00-c338-11e8-9fc9-f1fbc0f43208.png)

**Comment by xsrvmy** [comment]
It's not just aesthetics. Some people mix the rubik's and lingao clocks.
Is there any reason to still enforce similar pieces for clocks at all? Inserts can already do the job (the lingao insert actually has a person at the bottom), and wearing is common on clock.

**Comment by kingmathyall** [comment]
I think checkerboard and other pattens should be okay as the insert already can be customized to help determine orientation, thus this would give no advantage that isn't already available to the competitor.

**Comment by UnsolvedCypher** [comment]
In addition to banning checkerboard patterns, this regulation also makes it so that Clocks have to be rejected due to excessive markings on pieces. It seems unnecessarily harsh to have to do this given the complete lack of advantage these markings give. I would be in favor of not considering any of these pieces to be similar as I don't see distinguishing colors or markings as providing an unfair advantage.
