### ISSUE TITLE
FMC start with all cubes solved

### ISSUE THREAD

**Issue by campos20** [thewca/wca-regulations#631]
As of today, FMC regulations doesn't say the cubes must start solved, but I think they should. One of the reason is for consistency (competitors must deliver their cube to scramblers in a solved state), but the main reason is that a not solved cube may encode information.

**Comment by campos20** [comment]
(This is kind of specific, that's why I decided not to include it on the _caput_)

Eg.: suppose one is getting familiar with a certain 2E2C alg. Shifts of it are also 2E2C alg, but it's usually hard to get used to (about 10 cases). Using letter pair, a certain scramble and the memory cycle (as in BLD), one could encode the letters of the shift (or part of it) to save time. So if a competitor end up with a 2E2C skeleton, s/he could pick the scrambled and check the letters. Hopefully that was clear enough.

**Comment by xsrvmy** [comment]
Similar problem: Does a competitor need to remove any insertion stickers before the start of an attempt (if two attempts are done back to back)?

**Comment by campos20** [comment]
> Similar problem: Does a competitor need to remove any insertion stickers before the start of an attempt (if two attempts are done back to back)?

Makes sense to me, for the same reasons.

I don't see problem in using cubes which has some glue left, due the stickers. It could be not feasible to check all cubes looking for this detail.

**Comment by lgarron** [comment]
I think this is reasonable in an ideal world, but hard to deal with in practice – with a harsh penalty for accidents.

I think it would be appropriate to have something saying "you can't bring information into the attempt" with the understanding that competitors are worth trusting the vast majority of the time.

**Comment by xsrvmy** [comment]
Would bringing information into the attempt be covered under cheating? That is already in the regs.

**Comment by J-Rohault-dF** [comment]
It seems normal that cubes should start solved, but things considered normal can easely be abused. Adding a rule forbidding to bring non-solved cubes wouldn't harm normal cubers, and could prevent potential abuse (notably since this issue was posed, it may give ideas to cheaters).

**Comment by jfly** [comment]
> Adding a rule forbidding to bring non-solved cubes wouldn't harm normal cubers

Are you sure? I could totally see this harming normal cubers. Imagine some kid who is competing at his very first FMC competition, and doesn't know about this rule, so he brings some some scrambled cubes for FMC. The attempt begins, and a delegate notices that this kid started with unsolved cubes. The delegate will now have to DNF this poor kid who wasn't trying to cheat.

**Comment by HippolyteM** [comment]
I don't see this as a valid argument. Same could be argued about cellphones during fmc, or visible screens during regular attempts.
Competitors should know the regulations, and more important, delegates should do a good job ensuring that everyone knows what's forbidden (have you ever seen an fmc attempt without an introduction speach? That sound about the right moment to remind that scrambled cubes are not allowed. After that, if someone, even a kid, cannot listen properly, then DNF doesn't seems unfair.

**Comment by jamesquinn1** [comment]
Another problem on this semi-old post
Should insertion stickers be allowed to be written pre solve?
This could easily cause cheating by putting them in a certain order, or using them to write out an algorithm.

**Comment by timreyn** [comment]
I think this is overly harsh, and likely to lead to non-uniform enforcement.

FMC frequently starts with a 5-10 minute wait while everything is set.  Competitors don't always know exactly when the event is going to start.  If a competitor is playing with a cube while they wait, and the judge gives a 5-second warning, the competitor doesn't have a chance to not get a DNF.  If this becomes a rule, I'd also want to add a rule that the judge needs to give a 1-minute warning before the beginning of the event.

I worry that the judge won't be able to accurately tell whether all competitors have only solved cubes exactly when the event starts.  They can confirm while passing out material, they can watch what competitors do during the event, but checking the state of (20 to 100 competitors) * 3 cubes simultaneously seems unreasonable to do accurately.  I don't want this rule to lead to selective enforcement where judges have to pick which 2-3 competitors they're watching at the exact moment the event starts.

In general I think that this is going in a direction of adding too many "gotchas", where we're adding subtle things that competitors can accidentally do wrong and get disqualified.

**Comment by campos20** [comment]
Checking stickers might be a painful task, since it's too much stickers. I'm ok with writing on stickers in advance. Another thing, regulations doesn't say what type of stickers competitors can use. What if we forbid competitors from pre writing on stickers, but a competitor buy a sticker written by default.

Checking solved cubes can be done by just looking, it seemes easy to do.

**Comment by kingmathyall** [comment]
I personally don't believe this should be pursed any further (bringing solved/scrambled cubes to FMC). I feel like bringing unsolved cubes will give a competitor as much information and an advantage as stickerless cubes - so minimal that it really doesn't matter. I don't know of any issues that has ever come of this and thus I don't think it needs to change.

**Comment by timreyn** [comment]
@campos20 I think this is much harder than you think.  Remember also that judges won't be able to see more than one or two sides at a time from the front of the room.

What judge : competitor ratio do you usually use for FMC?  Even with 1 judge and 10 competitors I have a hard time imagining that I could confirm 30 cubes simultaneously.  If I thought one was not solved, I'm not sure what I would do, especially if the competitor immediately picks it up and starts turning it I probably wouldn't be confident enough to DNF them.
