### ISSUE TITLE
Bug - Regulation 3h "orientation of pieces"?

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#632]
"Modified versions of puzzles are permitted only if the modification does not make any additional information available to the competitor (e.g. orientation or identity of pieces), compared to an unmodified version of the same puzzle."

Literally intepreted, 3h potentially bans logos (since logos can be used to distinguish orientation), which is probably not intended. Similarly, it potentially unintentionally bans puzzles that only have a gap between the center cap and the main part of the center piece on 1 or 2 corner/side of the piece instead of all 4. This probably should be fixed.

**Comment by dancing-jules** [comment]
Huh. Good observations!

Logos are explicitly handled by the regs, so I don't see any real problem there.

And one could argue that center pieces don't have an orientation (because they only have one color).

**Comment by lgarron** [comment]
I don't see a strong need for it, but I suppose that 3l and 3l+ are sufficiently clear that it wouldn't hurt to add "Exception: a logo (see Regulation 3l)." to 3d.

> Similarly, it potentially unintentionally bans puzzles that only have a gap between the center cap and the main part of the center piece on 1 or 2 corner/side of the piece instead of all 4.

From my perspective, this is definitely by design. We need to draw the boundary somewhere reasonable, and I don't think competitors are particularly bothered by not being able to use such puzzles.
(And if Delegates are unintentionally allowing them, someone should let us know.)

**Comment by xsrvmy** [comment]
I have actually never heard of this reg being applied in the way I mentioned. Maybe I'm not communicating myself very well.

The logo exception probably needs to be clarified (center orientation, and identity on big cubes).

A bigger problem with that regulation is that 3h, unlike 3j, does not have an exception for reasonable wear. A strict interpretation would ban any big cube with any damage to centers. Also missing is the wording for "significantly different".

My understanding (not that it matters in any way) is that 3h bans puzzles that change the concept of the puzzle in question, such as increasing visibility or changing solved states (eg. super cubes), but should not also cover damage, which is covered in 3j. The current wording does not seem to reflect that.

> From my perspective, this is definitely by design. We need to draw the boundary somewhere reasonable, and I don't think competitors are particularly bothered by not being able to use such puzzles.
(And if Delegates are unintentionally allowing them, someone should let us know.)

Examples of popular cubes (or cubes that used to be popular) with center pieces indents on only some of the faces:
- Aolong v1 and v2
- Shengshou 7x7 (the vid I just checked might be the mini)
- MF3RS2 (Not the v1)
- Yuxin (the 5.25 one)
Note that the orientation part in the example was added in 2014 but these puzzles are all released after.

Also a lot of puzzles have some sort of trace of plastic flash on one of the four sides of the center pieces, but going there is probably too far, and taking advantage of that during BLD is easily noticable

Examples where center orientation is actually visible from the surface:
- Rubik's 2.0 speedcube (only mod 180, there are two indents in center pieces)
- Shengshou Gem (plastic flash on center cap is easily visible from the surface)

A possible way to draw the line is that the difference cannot be significant when view from the surface, so only the second list would be invalid.

Additional question: how does center orientation help the solver, other than BLD?

**Comment by Claster** [comment]
Hh, how exactly does a logo help to distinguish an orientation, that the coloring part itself doesn't?

**Comment by xsrvmy** [comment]
@Claster Orientation of the center piece, not the puzzle. Anyways, I don't see an advantage of telling orientation in solving except in bld. I always thought the mention of orientation in 3h was to ban super cubes.

**Comment by lgarron** [comment]
> Hh, how exactly does a logo help to distinguish an orientation, that the coloring part itself doesn't?

It tells you the number of CW-CCW turns done on that face, mod 4. It's definitely possible to use this information, though I don't expect to see a competitive method that does.

**Comment by lgarron** [comment]
Added the `help wanted` label for this:

> I suppose that 3l and 3l+ are sufficiently clear that it wouldn't hurt to add "Exception: a logo (see Regulation 3l)." to 3d.

@xsrvmy, would you be interested in sending a PR for this?

**Comment by dancing-jules** [comment]
> .... I don't think competitors are particularly bothered by not being able to use such puzzles.

I'd be bothered very much. The Cubing Classroom 50mm (my OH main) has this "feature" (though the difference is barely noticeable).

**Comment by lgarron** [comment]
> The Cubing Classroom 50mm (my OH main) has this "feature" (though the difference is barely noticeable).

I see. Do you have a picture showing this?

**Comment by dancing-jules** [comment]
> I see. Do you have a picture showing this?

[One](http://www.zcube.hk/image/catalog/cube/MY/MY-333-Mini-50-10.JPG), [two](http://www.zcube.hk/image/catalog/cube/MY/MY-333-Mini-50-05.JPG), [three](http://www.zcube.hk/image/catalog/cube/MY/MY-333-Mini-50-13.JPG).

**Comment by Claster** [comment]
> It tells you the number of CW-CCW turns done on that face, mod 4. It's definitely possible to use this information, though I don't expect to see a competitive method that does.

Oh, I see. It tells you the number of turns mod 4 that were done in the scramble (if you cared enough to memorize the logo state before the scramble). However, I don't think it tells anything about the scramble state itself. One U-turn can be replaced with several moves of other faces. Thus for every scramble state and for every number 0<=x<=3 there exists a scramble that leads to this state and uses  U move x times (mod 4). The open question here is how many of these scrambles can be really generated by the 2-phase algorithm we use in TNoodle.

**Comment by lgarron** [comment]
> However, I don't think it tells anything about the scramble state itself.

I guess it does if you look at 5 out of 6 faces. But I mainly meant to convey that it can be used during a solve, similar to how you could use a touch-detectable logo in BLD or a Square-1 middle slice to keep track of a parity. (I understand that it's extremely unlikely people are using this for and advantage in 3x3x3 speedsolve, though, at least not on purpose.)

**Comment by xsrvmy** [comment]
Quite a few important puzzles actually had this problem (ss 7x7, aolong v1 and v2, mf3rs2). The interpretation of the reg also depends on whether or not the original puzzle had this feature.
