### ISSUE TITLE
Discussion in the waiting area : What counts as cheating?

### ISSUE THREAD

**Issue by J-Rohault-dF** [thewca/wca-regulations#633]
The WCA regulations state that "Competitors in the Competitors Area must not communicate with each other about the scrambled states of the puzzles of the round in progress" (https://www.worldcubeassociation.org/regulations/#2g3).
What can be considered about "communicate [...] about the scrambled states"?
- Solves difficulty ("I got an easy solve")
- Precise difficulty ("It's an easy cross")
- Even more precise difficulty ("Blue cross gets to an easy F2L")
- Times ("I got an 19.67")
- Scrambles manipulations ("I got a low time even with low TPS")
- Results ("There was a WR single")
- Many results ("I broke my PB single and many other people did so")

Also, should it be made clearer that re-watching videos of the solve, or trying to reconstruct them while in the waiting area should be forbidden?

**Comment by xsrvmy** [comment]
I think we can agree on several things that definitely shouldn't be allowed, such as:
- Good cross colors (makes inspection easier)
- Parity on sq1 (helps people using csp)

One consideration is that competitions in different countries have different setups. For instance, in China, all solvers stay at their stations, so there is less chance for people to talk to each other.

**Comment by J-Rohault-dF** [comment]
So that means that every communication that helps planning at least 1 move is considered cheating.
Also, for my 1st competition, I was re-watching my solves on my camera when I was told it wasn't allowed (I stopped right away- I precise that no one could see the screen clearly)

**Comment by TeebooGH** [comment]
Afaik, noone really talks about sq1 parity in the waiting area, since there are multiple ways to alterate parity in Square-1.
Oh and by the way, people use different CSP tracing methods. But I get your point.

**Comment by xsrvmy** [comment]
@teebooGH I meant like if someone gets 2 move cs into parity and someone using csp hears that.

**Comment by J-Rohault-dF** [comment]
To sum-up:
Every communication helping to plan at least 1 move is considered as cheating.

Re-open if you're not agreeing with this conclusion!
