### ISSUE TITLE
Problems with regulation 2i2b

### ISSUE THREAD

**Issue by J-Rohault-dF** [thewca/wca-regulations#634]
In regulation 2i2b, it is precised that "The competitor must not interact with (e.g. operate, hold, wear) any active camera" and it is precised that is applies "from the start of the attempt until the competitor stops the solve".
(https://www.worldcubeassociation.org/regulations/#2i2b).

I got a problem with it recently: during my 3rd attempt of the 1st round of 2x2 from Paris Open 2018, I slightly re-adjusted my camera that was a bit too low while I was saying "Ready". As I was technically interacting with the camera during the attempt, that became a DNF (that followed the regulations, so I signed it).

I think the 2i2 regulations could be rephrased to:
```
- 2i2) Competitors may use cameras at the solving station at the discretion of the WCA Delegate, but the following restrictions apply. Penalty for breaking a restriction: disqualification of the attempt (DNF).
  - 2i2a) Each camera monitor must be blank or out of sight of the competitor (see Regulation A5b) from the start of the attempt until the competitor stops the solve.
  - 2i2b) The competitor must not interact with (e.g. operate, hold, wear) any active camera during the solve. Exception: the competitor may wear a camera mounted on their head, as long as it is out of their sight and it is clear that they are not interacting with it (apart from wearing it).
```
By moving the restrictions durations to the individual restrictions, that would allow to keep 2i2a for all of the attemp (it can give an advantage during solve and inspection) and to have 2i2b reduced to only the solve (it can be justified to slightly move a camera during the inspection)

**Comment by Goosly** [comment]
Why is this a problem?
2i2 is very easy to apply. It's also very easy to not get a DNF: just don't touch your camera.

**Comment by xsrvmy** [comment]
I doubt the WCA is changing this one since a 6x6 (former) WR mean has already been DNFed for touching camera in inspection.

**Comment by J-Rohault-dF** [comment]
Well this doesn’t make cheating easier (2i2a still doesn’t apply) and it reduces DNFs caused by inattention

**Comment by lgarron** [comment]
I don't think we should allow interacting with the camera during inspection. We have revisited 2i2 several times since it was crafted, and found that it is the most practical line to draw.

In particular, 2i2 is easy to understand and enforce right now, and I think using two separate periods for 2i2a and 2i2b is more likely to cause confusions or mistakes.

(WRC folks: feel free to reopen this if you disagree.)

**Comment by J-Rohault-dF** [comment]
Here is still a video of the solve for more detail (even if the issue was closed): https://youtu.be/SZxD5MlvpF8
