### ISSUE TITLE
Clarify that limited registrations at the door are allowed

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#635]
Some competitions have a registration schedule of "register for anything up to date X, else you can register for 3x3x3 even at the door". I strongly support allowing this, since it makes our competitions available to beginners no matter when they learn about a competition. This is especially important if they find out about the competition due to publicity in the days leading up to the event, which is actually how I ended up hearing about the first competition I ever attended.

This relies on a loose interpretation of Article Z, and I'd at least like to add a Guideline clarifying that this is allowed.

WRC thread link: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wca-wrc/FQkUwfV5qeo/2tqazT0xBAAJ

**Comment by AlbertoPdRF** [comment]
This is handled now in https://github.com/thewca/wca-documents/pull/40, so I'm closing this issue!
