### ISSUE TITLE
Ephemeral Events

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#636]
I would like to seriously consider [Arnaud's suggestion of non-permanent events](https://www.speedsolving.com/forum/threads/idea-alternating-1-year-event.70659/). He suggests 1 year, but I think we should go for ≈2 years so that every puzzle can have a world champion once.

We have had several discussions that touch on the issue that adding or removing events is a big deal. Major competitions have a lot of pressure to hold all events, and the combination of 1) modern scheduling and 2) the lack of a maintained database for unofficial events at official competitions means that unofficial events are very uncommon. 

We can always adjust the cadence to allow for more events or more frequent events, but here is rough idea for an event that would be active from 2020 to 2021:
- In January 2019 we announce some set of events (say, ≈5) that we want to consider for the next cycle. We encourage competitions to hold these unofficially in order to work out the format and give the competitors a chance to try it out.
- Around August (after the major competitions are held), we hold a vote of all active WCA competitors to select an event.
- The event becomes an official event from January 2020 to the end of 2021.
- In January 2021, we start a new cycle for an event to become active in 2022.

We have already retired events in the past, so this shouldn't require special tweaking from the website. What I really like about this idea is that it lowers the commitment for adding an official event, without setting unfair expectations and fueling debates about which events are worth keeping.

I believe that new events are a benefit to the community because:
- We regularly get questions or requests for new events, so competitors want them! Listening to community wishes may become more important as we try to stay relevant compared to other efforts like Red Bull.
  - We do have [rough criteria](https://github.com/thewca/wca-regulations/wiki/Criteria-for-new-events) for adding new events, but telling those to a community member tends to cut off their interest rather than energizing them to promote an event. A regular process could get more engagement.
  - If we regularly engage with the community for this one point of feedback, we have a chance to keep community conversations going between WCA officials and competitors. (I feel like we have a tendency for the two to disconnect over time.)
- The cubing community is large enough that puzzle manufacturers are likely to invest resources into puzzles that we consider for official events. And once a well-engineered puzzle is on the market, it will hopefully stay available for longer. I would love for us to incentivize even more perpetual innovation in new types of speed puzzles.
- Novel puzzles encourage research into algorithms and software development, whose effects also stay around. We now see a lot of cubers focused on advanced techniques and tweaks to existing methods, but I think we're losing out on more classical development of methods.
- I would really like to see us explore less classic event formats, such as team BLD or FMC duel.

**Comment by lgarron** [comment]
Just a thought: If we're willing to consider adding two events in the same cycle, I'd love to see a pairing of a new "speed" puzzle event (e.g. Kilominx, Domino, Astrolabacus, Helicopter) and one with a novel format (e.g. speed BLD, team BLD, FMC duel, speed FMC, match the scramble, or maybe even robot cubing).

**Comment by J-Rohault-dF** [comment]
I propose to also have the idea of proposals and voting from the community via the website. Also, having a vote at the end of the 2-years term to decide whether the event is kept or removed could be considered

**Comment by pedrosino** [comment]
Maybe this is a good idea, but I'm not sure having an event be official for just 2 years is that great. It could happen that when people are finally getting good hardware and techniques we remove it because there's not enough interest.

I would probably prefer if we removed some existing old event to add new stuff. As you said, big competitions are already very crowded and hard to run. If we add more, we may need 1-week long competitons in the near future.

**Comment by xsrvmy** [comment]
There is actually an unofficial statistic problem here regarding sum of ranks/kinch ranks as well as bronze/silver/gold/plat members. Does that come into play at all?

**Comment by Jambrose777** [comment]
I'm absolutely in favor of this idea. This also gives competitors who have "maxed out" a chance to find interest in new events and continue to have WCA grow with its members.

I dont see the reason to remove events just to add more. Every year we can look at every event for the specific specifications we are looking at (for example popularity) and make the official event a Ephemeral status and Ephemeral Events to be removed or added to the official events to stick around for a while.

**Comment by Jambrose777** [comment]
> There is actually an unofficial statistic problem here regarding sum of ranks/kinch ranks as well as bronze/silver/gold/plat members. Does that come into play at all?

I dont see how the first is affected. You can either base it on official events or all events.
I'd imagine the community can find an appropriate way to redefine unofficial membership statuses.

I don't think the unofficial statistics should impede WCA in progressing.

**Comment by timreyn** [comment]
I'm fairly neutral about the overall proposal, but a few points:

### This proposal has ongoing cost to the WCA

- Some events mentioned in this thread, like Team BLD and FMC Duel, are huge changes from the way current competitions run.  I don't think this is a blocker, but it means that we would need extensive regulations work, and that should be factored into the timeline for adding a new event.
- New puzzles, like Kilominx and Domino, will require software support to implement scrambles.  Keep in mind that the WST has a huge amount of work on their plate, and think about whether adding a temporary event is important enough to delay launch of wca-live, the redesign of the WCA homepage, or other essential work they're doing to keep the website running.

### The WCA should retain decision-making authority on what events we recognize

- Any proposal should be accepted by the WRC before appearing in a poll.  I don't want to end up in a situation where a meme like OHITABLD ends up as an official event, or where it wins the poll and then has to be rejected.
- I think the decision to keep events after 2 years should not be done by poll, but rather by the WRC taking into account all factors.  Many of the costs of adding more events (e.g. organizational difficulty particularly for championships, long-term complexity of regulations and software) are invisible to most competitors.

I agree with Jacob that unofficial statistics should not be a part of this decision.

**Comment by J-Rohault-dF** [comment]
About what Timreyn wrote:
### Costs to the WCA
- There are regulations work to do, but some of the work could be done in advance: for example, making a whole regulations point for relays, that would be used for all relays whatever their type. But it's true that there is still a huge work behind that. However, unofficial events have already been implemented in no competitions, like No Stress Solving 2017.
- The scrambles are also a big amount of work. There are 2 ways this could be done: Either we have 2 ephemeral events every 2 year (synchronized) or there is 1 every year (still for a 2-years term). The first option would give more work on the scrambles and regulations every other year, the second one would make work more even.
### The authority of the WCA
- Of course, the WRC should approve proposals. But proposals should also have reasons for and against. A new committee could (I'm not saying it should) be created to synthesize the proposals and their arguments.
- The WRC (for obvious reasons) should have a say on that, but also the WST (they make and handle the scramble programs but also the website), and also the Board of Directors (I don't think I have to explain why) and the Board of Delegates (they have their part on competitions organisation).

Also, ephemeral events should be announced 1 year before their implementation, to let the time for companies to produce good hardware.

Finally, I created a **fully unofficial** list of possible events. Comments if you want to suggest new events into this list, and if you want to add points for and against, I'll add them. https://docs.google.com/document/d/1zb9WGbF4bquuiZPWp4YONMH5NVApQxsZ_5xusA6KQNw/edit?usp=sharing

**Comment by lgarron** [comment]
The WRC took an internal vote on this, and has decided *not* to pursue this for now.

I'm personally still very interested in exploring the idea, but will start my efforts by working on getting an unofficial results site up again.

**Comment by J-Rohault-dF** [comment]
> I'm personally still very interested in exploring the idea, but will start my efforts by working on getting an unofficial results site up again.

Apparently, a website has been created recently for that purpose: https://funcubing.org/
Any competition can be added by just emailing the creator, Konstantin Solovbev (unofficial results from 2003 to 2010 are not included)
