### ISSUE TITLE
When is the delegate not allowed to invoke 1e2?

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#637]
Should there be explicitly listed circumstances where the delegate is never allowed to force a competitor to judge/run/scramble (by threatening a dq)?
Some examples I can think of (these are debatable of course):
- Competitor is competing in the immediately following group
- Competitor is not at the venue (related: can a delegate require a competitor to stay at venue to staff when he has no events for several hours?)
- Low scrambling accuracy (especially 5x5)

**Comment by Laura-O** [comment]
> Should there be explicitly listed circumstances where the delegate is never allowed to force a competitor to judge/run/scramble (by threatening a dq)?

Do you have an answer to this question? If not, why are you asking here? Or rather, what's your intention for asking here?

If you think adding such a clarification is useful please tell us why.
If you do not think so... well, then I wonder why you are creating this issue. 🙂 

> Competitor is competing in the immediately following group

By adding such a restriction you (at least theoretically) kill most rounds of side-events at competitions without dedicated staff.

Adding my own opinion here as well: we should trust Delegates to make fair and good decisions. Removing bad scramblers is not releated to 1e2 but making sure the competition runs well. For other cases, this often depends on the situation.

**Comment by lgarron** [comment]
I think Delegate discretion is enough to handle this for now. In practice, we struggle with Delegates using 1e2 *enough*, rather than too often.
