### ISSUE TITLE
Proposal: competitions "should" use scramble signatures.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#640]
Based on https://github.com/thewca/wca-regulations/issues/591 and the public + private discussions based on it, I'd like to offer an updated proposal:

> 4g2) After applying a scramble sequence, a the scrambler must sign the score sheet to certify that they have applied and verified the correct scramble. Exception: the scrambler does not need to sign for Speed Solving events, One-Handed Solving, Solving with Feet, or Clock Solving, at the discretion of the Delegate.
> [Remove A2d1]

This strongly encourages scramble signatures without strictly requiring them, except for BLD events. I believe that it's worth enforcing for BLD events becaus
- BLD attempts tend to take longer, which means that this is not as much of an impact on the schedule.
- Duplicate scrambles in BLD events are much more likely to give a competitor an advantage. And duplicate multi BLD are especially frustrating and time-consuming for the competitor.
- Having a moderately common event like 3BLD with required scramble signatures forces most organizers to think about scramble checking (e.g. having a way to put a field on score sheets) for at least *some* events. This reduces the work to use them for other events.

We can then work with the WQAC on figuring out if this works well enough to expand to all events int he future.

@thewca/wrc-team, would you be in favor of this?

**Comment by SAuroux** [comment]
First question: is the title wrong? "scramble checkers" has always been something entirely different than "scrambler signatures"

Assuming this is about scrambler signatures: After trying scrambler signatures at German Nationals 2018, I learned that they definitely help to reduce scramble incidents, help to resolve the ones still happening and really cost way less extra time than initially suspected. Therefore, I fully support scrambler signatures and I would even say that having them is a very logical step given how strictly we already handle judge and competitor signatures these days. 

But only introducing them for BLD events is a terrible half-baked approach in my view. Just require scrambler signatures for all event - period. People will moan in the beginning as usual, then adapt very quickly and soon cherish the benefits. It happened with competitor signatures for every solve and it will happen again.

**Comment by lgarron** [comment]
> First question: is the title wrong? "scramble checkers" has always been something entirely different than "scrambler signatures"

Yes, thanks for catching. I've updated the title.

**Comment by xsrvmy** [comment]
Statistically does China have a lot less misscrambles? (A lot of comps also uses designated scramblers so maybe this is not a fair comparison. I remember a comp required 80%+ accuracy for 5 scrambling)

**Comment by AlbertoPdRF** [comment]
Shouldn't this issue have been closed with #662?

**Comment by lgarron** [comment]
This proposal wasn't completely implemented in #662. However, we can close this issue for now.
