### ISSUE TITLE
Require a time period between a competition being announced and registration opening

### ISSUE THREAD

**Issue by sam596** [thewca/wca-regulations#641]
We have Z4c mandating 48 hours notice before opening an additional registration period, but why is there no regulation requiring such notice before the initial registration period opens?

**Comment by lgarron** [comment]
Probably because the relevant Regulations were written when competitions rarely met the limit.

I think this should go in https://github.com/thewca/wca-regulations/issues/610 , though.

**Comment by AlbertoPdRF** [comment]
This should be handled now in https://github.com/thewca/wca-documents/pull/40, so I'm closing this issue!
