### ISSUE TITLE
Parentheses in FMC solutions

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#642]
There is currently disagreement over whether parentheses are allowed in FMC solutions.

I maintain that E2c and E2c++ make it clear that any notation outside OBTM as defined in Article 12a3 – which includes only moves from 12a1, 12a2, and 12b – is not allowed.

At this point, I think we need to make a new decision. I'm okay with allowing more than currently defined in 12a1, 12a2, and 12b, but I strongly feel that we should define exactly what notation is allowed. That is, I don't think we should leave it up to the interpretation of the Delegate, given the increasing complaints about inconsistent FMC-related rulings.

@thewca/wrc-team, would any of you be able to draft wording that specifies this? This should be able to handle whether to allow and (if so) how to interpret any possible edge case, such as `(R U)2`, `R U(')`, `() R`, `R(2 2Fw)`, `{R2}`, `[F2}`, `R )U(`, `R (D)))`. One option is to ignore all characters that are not defined in moves, but it would be nice to have something more intuitive and semantic.

Alternatively, would you be okay with putting the responsibility on the competitor and disallowing any undefined notation like parentheses?

**Comment by xsrvmy** [comment]
There is a weird edge case: what if there is an argument on whether the competitor wrote `(r)` or `[r]`? Or even worse, `(u)` vs `[u]` (since `(u)` and `(U)` look similar)?

Another thought is to allow the competitor to possibly clarify any ambiguous notation or characters. A similar scenario happens for recorded times already. Even though the competitor already confirms that the written time is legible, the score taker can still ask the judge to clarify anything ambiguous.

**Comment by kingmathyall** [comment]
I think it would be so much simpler if we just let parentheses, brackets, and braces ((), [], and {}) to be interchangeable. So (r) would be as much of a ration as {r} or [r] is. Along with this, we could say parentheses, brackets, or braces must be around the letter (and apostrophe/number - not sure how to word this) - this should cover U('), R(2), and most everything else @lgarron mentioned.

I see nothing wrong with allowing these symbols to be interchangeable.

**Comment by lgarron** [comment]
> So (r) would be as much of a ration as {r} or [r] is.

So, I'm fine in principle with parentheses being used as an effectless grouping move –  `(x)`, `(R U)`, and `(F [r] D)`. I'd be still be concerned about edge cases where competitors don't put syntactically valid parentheses, or if they try to use undefined notation like `(R U)2`.

However, I have *very* strong objections to defining `(r)` to be the same as `[r]`, because `(r)` [means something else](https://alg.cubing.net/?alg=(r)) in SiGN, which is fairly widely used by the community. `r` also used to mean yet another thing (`Rw R'`) in the Regulations until 2012, although I was glad that we were able to remove it. I really would not like to see a new situation with contradictory interpretations in different contexts.

It would also invite the issue that `(U)` and `(u)` look similar, but mean different moves.

(And while this doesn't preclude its use in official FMC solutions, I have always had a personal aversion to `[u]` style notation it conflicts with the similar syntax but different semantics of commutator/conjugate notation – it makes the first move of `[u...` ambiguous. alg.cubing.net doesn't support `[u]` style rotations like this, and I plan to never support them.)

In my view, it's the job of the competitor to write down a sequence of moves that can be directly interpreted by the judge, and that the judge should not have to do anything like inverses, cancellations, repetitions or insertions themselves. It's much easier to ensure consistent rulings if we say "these exact moves are valid, and nothing else" (which I want to put on a judge reference sheet) than to say "use your best guess at the intended interpretation".

The new FMC sheets were designed to try to make the notation clear to understand and copy: https://github.com/thewca/wca-regulations/issues/456
For those who have competition FMC sheets at home: is it possible that parentheses are actually in fairly low use now?

**Comment by julesDesjardin** [comment]
I'm not sure what was Matthew's idea behind this proposal of allowing all kind of braces, but this is why I thought it would mean :
(r) [r] {r} (R) [R] {R} all mean x. (RU) or (R)2 or R(') or (x) don't mean anything, and disqualifies the attempt.

I think we need to treat (u) and (U) as the same thing because as you said, we can't really see a difference (same reasoning for (r) and [r]), which is why I think we should allow all braces surrounding only 1 character to be rotations.

**Comment by lgarron** [comment]
Now, for actual solutions rather than objections:

Since the brackets are causing confusion, what about introducing notation that doesn't have this problem, such as `Uo`/`Lo`/`Fo`/`Ro`/`Bo`/`Do`? I know that this is not used right now, but I don't think `[u]` style rotations were used by the community before the WCA adopted them. (And we've revised notation for WCA purposed before, in the case of clock.) Putting them on the scramble sheets should make it easy to make competitors aware, and `[u]` style could be removed in 2020.

> is it possible that parentheses are actually in fairly low use now?

If this is not the case, and we really want to insist on allowing `(r) = [r]`, then I think the only thing that I would be comfortable with is to say that the Delegate can consider a competitor who wrote `(r)` to have meant `[r]`. This would also allow `(r')` and `(r2)`, but not `(U)`, `(r)'`, `(r)2`. How does that sound?

**Comment by lgarron** [comment]
> I think we need to treat (u) and (U) as the same thing because as you said, we can't really see a difference (same reasoning for (r) and [r]), which is why I think we should allow all braces surrounding only 1 character to be rotations.

In this interpretation, would you interpret `(B)` as `[b]`? I'm not comfortable with that.

**Comment by julesDesjardin** [comment]
> In this interpretation, would you interpret `(B)` as `[b]`? I'm not comfortable with that.

I don't really see a problem with this, and I've also seen people use smaller uppercase to write lowercase (it wasn't related to cube though)

> If this is not the case, and we really want to insist on allowing `(r) = [r]`, then I think the only thing that I would be comfortable with is to say that the Delegate can consider a competitor who wrote `(r)` to have meant `[r]`. This would also allow `(r')` and `(r2)`, but not `(U)`, `(r)'`, `(r)2`. How does that sound?

That can also be a solution (basically the same, but limited to lowercase)

**Comment by kingmathyall** [comment]
I completely agree with Jules that I don't see any problem with (B) being [b]. Basically, any one move (R, R', U2, etc.) surrounded by [], (), or {} regardless of it's case (upper or lower) is treated as a rotation. This would not allow cases such as (r)' and (r)2, but would allow cases such as (r'), (R2), (R).

This way there is no guessing if a [U] is actually [u], no issue with people putting (u) instead of [u].

**Comment by kingmathyall** [comment]
I could also get behind allowing X, Y, and Z to be used along with of x, y, z. I would also allow (x) = (X) = x = [x] = [R] = (r).

**Comment by lgarron** [comment]
> I could also get behind allowing X, Y, and Z to be used along with of x, y, z. I would also allow (x) = (X) = x = [x] = [R] = (r).

It also seems a bit wild to me to have 10+ ways of writing a given rotation, both pedagogically and logistically. I would strongly prefer *reducing* the number of moves that we consider valid, in order to facilitate a written whitelist.

**Comment by kingmathyall** [comment]
I understand that - I think rather than listing that (r) = (R) = [r] = etc. we just note that (), [], and {} are interchangeable for rotations and the move within those characters will be applied regardless of the letter case.

**Comment by AlbertoPdRF** [comment]
Just as we don't allow `b` as a move, I don't think we should allow `(B)` as a rotation.

**Comment by kingmathyall** [comment]
How come? I think any letter, upper or lower case, between something such as () or [] is _clearly_ the competitor trying to do a rotation - so why not let them? I find it silly that attempts are often DNFed because they write these things that are very clear, but _technically_ not allowed.

**Comment by xsrvmy** [comment]
I would assume u and U is a bigger problem because they look similar?

**Comment by lgarron** [comment]
> we just note that (), [], and {} are interchangeable for rotations and the move within those characters will be applied regardless of the letter case.

As noted before, I am *strongly* opposed to this, because it's not necessary and contradicts notation used by everyone else in the community.

> I find it silly that attempts are often DNFed because they write these things that are very clear, but _technically_ not allowed.

I consider it the competitor's responsibility to make it clear what their solution is.

**Comment by AlbertoPdRF** [comment]
> I think any letter, upper or lower case, between something such as () or [] is clearly the competitor trying to do a rotation

If that was the case, we wouldn't be having this discussion. As @lgarron, I think this is not the way to go, as this isn't used by anyone and it will just create more confusion.

**Comment by kingmathyall** [comment]
I think the problem is that it isn't clearly allowed. People use that stuff and they clearly mean for it to be a cube rotation - attempts are DNFed because it isn't _technically_ allowed. I think we should allow it so it does seem to be the case.

**Comment by pedrosino** [comment]
I don't remember seeing people write parentheses meaning rotations (I also don't remember ever seeing parentheses recently). The ones I recall were meant as grouping of movements.

**Comment by xsrvmy** [comment]
Is there any reason not to just tell everyone to use xyz? Or is rotation direction too hard?

**Comment by kingmathyall** [comment]
@pedrosino Parentheses have been used many times for rotations before:

Vladislav's 19 has (x2), (y), and (z)
https://www.speedsolving.com/forum/threads/fmc-19-moves-vladislav-ushakov-psu-open-2016.62184/

I still, even after reading through this, cannot figure out any good reason why we wouldn't allow for () and [] to be interchangeable - I have never seen or heard of brackets so I don't think that's super necessary, but I don't think it'd hurt to throw that in there either. 

@xsrvmy there are many people who can't grasp that x moves the whole cube as an "R" - many of the younger cubers

This could be in the form of a clarification or addition in the guidelines for 12b

**Comment by Samuel-Baird** [comment]
Since rotations are being removed I think we can safely disallow all parentheses and brackets

**Comment by SAuroux** [comment]
Wide moves are not being removed only [r]-styled rotations are.

Actually you can just as well conclude the exact opposite: we can now safely allow (and ignore) all sorts of parentheses/brackets.

**Comment by Samuel-Baird** [comment]
> Wide moves are not being removed only [r]-styled rotations are.
> 
> Actually you can just as well conclude the exact opposite: we can now safely allow (and ignore) all sorts of parentheses/brackets.

Why would we allow them?

**Comment by Goosly** [comment]
Because one of the missions of the WCA is more fun and DNF'ing FMC solution for silly reasons like "Oh no they wrote parentheses" is not fun.

**Comment by Samuel-Baird** [comment]
> Because one of the missions of the WCA is more fun and DNF'ing FMC solution for silly reasons like "Oh no they wrote parentheses" is not fun.

Well it’s the competitors fault for not reading the regs if they use parentheses, I don’t see why the regs should have to be changed to allow them to use unnecessary and unhelpful notation which can cause confusion
