### ISSUE TITLE
More clear words for A4b1

### ISSUE THREAD

**Issue by Baiqiang** [thewca/wca-regulations#644]
The current version is:
> A4b1) The competitor must have no physical contact with the puzzle between the inspection period and the start of the solve. Penalty: time penalty (+2 seconds).

However, the inspection period technically ends at the start of the solve. This means there's 0 second between the inspection period and the start of the solve.

**Comment by Mollerz** [comment]
You could even go to start the timer, realise you might want to use some more inspection, release your hands from the timer (before the green light turns on) so it never starts, and inspect further.

Perhaps rewording to something along the lines of: The competitor must have no physical contact with the puzzle whilst starting the timer.

Maybe we should add an A4b2 that states that once the timer is started, this is deemed as part of the solve. We've had incidents in the past where competitors start the timer, stop it, reset, and start again without ever touching the puzzle.

**Comment by xsrvmy** [comment]
> Maybe we should add an A4b2 that states that once the timer is started, this is deemed as part of the solve. We've had incidents in the past where competitors start the timer, stop it, reset, and start again without ever touching the puzzle.

Exception for BLD?

**Comment by lgarron** [comment]
> Maybe we should add an A4b2 that states that once the timer is started, this is deemed as part of the solve. We've had incidents in the past where competitors start the timer, stop it, reset, and start again without ever touching the puzzle.

Fortunately, we've already done that! :-D

https://github.com/thewca/wca-regulations/pull/579/files

@Baiqiang: would you be able to submit a PR to remove the "between the inspection period" part? :-)

**Comment by Baiqiang** [comment]
@lgarron I've submitted a PR here #645. Please have a check.
