### ISSUE TITLE
Provision for accidental contact/interaction with the camera during BLD

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#646]
Should there be a similar provision to C1b3 for accidentally contacting the camera during bld? Possible ways of accidental interact would include
- throwing the box into the camera
- hitting the camera with a finished puzzle during MBLD
- accidentally coming into contact with the camera during execution, especially MBLD
- Sight blocker hits the camera
If anything causes the camera to fall over or turn around to face the competitor, it should probably be removed from the table.

Another way that can happen in other events is a dropped puzzle/popped piece hitting the camera WITHOUT the camera screen becoming visible.

On a related note headmounts should probably be explicitly banned in BLD simply because the competitor indirectly interacts with the camera when pulling down the blindfold.

**Comment by J-Rohault-dF** [comment]
Well interacting with the camera is allowed if it's because it's mounted on the head, so the last point doesn't seems valid.
For the rest, everything seems fine, but I think it shouldn't be reserved to blindfolded

**Comment by lgarron** [comment]
I don't think changing the camera Regulations here is necessary, or a good idea. The competitor needs to take some responsibility for doing it in a way that does not facilitate getting extra information, and we don't really see many incidents caused by the accidental interactions described.
