### ISSUE TITLE
Disallow other cubes as "assistance"?

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#649]
A5b says that "While inspecting or solving the puzzle, the competitor must not receive assistance from anyone or any object other than the surface"

It is common for competitors to put their warm up cube on the table before solving.
I was asked this weekend if it should be forbidden in case of odd cubes (4x4, 6x6) since it could give information about the centers.
I wasn't sure, but replied it was fine.

Should we disallow this?

**Comment by Laura-O** [comment]
That has been more or less discussed in #103

**Comment by xsrvmy** [comment]
Other things that are part of the solving station (eg. mats and covers) might also give this information. Is the advantage significant, since the same information can already be found on the corner pieces of the puzzle being solved?

**Comment by kingmathyall** [comment]
I think disallowing other cubs is silly. Orientation is the only "useful" piece of information you could get, but that can just as easily be figured out by looking at the corners of your puzzle.

**Comment by lgarron** [comment]
I agree that this isn't something that:
- We can regulate well without being too onerous. 
- Is used by competitors to cheat in practice, especially not to set record times.

I'll close this for now, since I don't think we'd come up with any actions to take.
