### ISSUE TITLE
Clarify that the competitor may not request a puzzle orientation

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#65]
This hasn't been allowed since, like, 2003. But some people note that there's no explicit provision for this, so... time to make things just one line longer? Probably just a Guideline.

See [this speedsolving thread](http://www.speedsolving.com/forum/showthread.php?36691-Competitor-requested-orientation) about former BLD records.

**Comment by pedrosino** [comment]
I'm not sure what you mean, but A2e is exactly for this...

**Comment by lgarron** [comment]
Yeah, that was the intent, but I'm not sure if it's being followed, and people ask about what arbitrary means. I'm just creating issues for everything in my backlog, whether it's particularly actionable or not.
