### ISSUE TITLE
Increase minimum time of physical record keeping

### ISSUE THREAD

**Issue by campos20** [thewca/wca-regulations#650]
The guidelines asks delegates to keep physical records for at least on month (see [1c3++](https://www.worldcubeassociation.org/regulations/guidelines.html#1c3++)). This seems a very short time. WDC's investigation would be easier if delegates kept records for a longer time rather than just relying on photos. My suggestion is 2 years. I know this can be a lot of paper to keep.

**Comment by Laura-O** [comment]
I would love to see that in an ideal world.
However, just make a simple calculation: a Delegate delegates 10 competitions a year, each with 100 competitors and each competitor competes in 10-15 rounds (which is realistic here, but probably not in other parts of the world). This adds up to a number of 20.000-30.00 sheets of paper.

I don't think this is something you want to keep, especially as many Delegates are students and probably rather live in small apartments than in their own houses.

Which information do you consider as helpful after this amount of time? Judge signatures? Or DNF times for cumulative rounds?

**Comment by campos20** [comment]
> Which information do you consider as helpful after this amount of time? Judge signatures? Or DNF times for cumulative rounds?

I'm more interested on times for cumulative rounds. WDC used this in a recent case. What do you think of keeping the DNF time or DNF reason? Perhaps we should keep this on database. Judge signature would be nice to, but not feasible.

**Comment by Laura-O** [comment]
I think recording results of DNFs in rounds with a cumulative limit is good and it was discussed for the new scoretaking tool ([wca-live](https://github.com/thewca/wca-live)). Not sure if they decided to add it or not. Maybe @ronaldmansveld can say more about it.

About the DNF reasons: that's a difficult one as it's not easy to actually define categories/codes for DNF reasons. Of course, judges could write this down in natural language, but if you want to add it to the database, there should be some kind of encoding. This seems to add a lot of effort just to keep information which is pretty useless for >99% of the cases. 🤷‍♀️

**Comment by ronaldmansveld** [comment]
IT is indeed one of the ideas for a future feature in WCA live to keep
track of extras, dnf times and dnf and +2 reasons. However, this is
something that won't happen anywhere in the near future, as it will require
a lot of changes in different parts of the software we use, and likely
regulation changes as well.

As for dnf and penalty categorization: these would most likely be the
actual regulation identifier.

Dnf times may land in WCA live before anywhere else, but won't yet be
stored anywhere initially, as WCA live will use it to determine the
validity based on cumulative time limit. But as that information will be
local only as a start, it won't help in this case just yet.

More on the actual topic: while not a delegate, I do have plenty of score
taking experience, and I know how much scoresheets are produced for a
regular comp. 2 years is way too long to keep those around, but I can see
why people feel a month is too short.
Can we make a distinction between events on how long scorecards must be
kept? Say a default of 2 months, but bld events and events with cumulative
time limit must be kept for 3 or 4 months?


Ronald

**Comment by cubewhiz** [comment]
While 10 competitions is probably an average per year, some Delegates have done 30-50 competitions in that span. I can't imagine having to keep that much paper stored for that long. Maybe 2-3 months is more reasonable.

**Comment by Baiqiang** [comment]
What about keeping the electronic records? Like taking photos or scanning them.

**Comment by kingmathyall** [comment]
Sitting there scanning hundreds of scorecards seems would take a LONG time and seems very unrealistic. I wish there was a cheap way to electronically record times during a competition (for each scorecard) - that would save a ton of paper, but I don't know if anything has ever been in the works :/

**Comment by campos20** [comment]
Since delegates double check before submitting results, I really don't see a point in keeping all the scores cards (perhaps checking who was the judge). I think we should keep longer those that have info that might be handful and are bit on the db, so, keeping BLD longer sounds good to me.

**Comment by jamesquinn1** [comment]
What if we suggested organizers held on to the papers? If organizers are doing ~2 comps at maximum per year, that shouldn't be too much.

**Comment by campos20** [comment]
> What if we suggested organizers held on to the papers? If organizers are doing ~2 comps at maximum per year, that shouldn't be too much.

Organizers might not be WCA members at all, so it's hard to do this.

I've made my mind. Sensitive information that might be handful, in my opinion, is:

- DNF time for cumulative rounds
- Checking who was the judge

For the first one, we could add DNF time on WCA database [another issue?], if applicable. For the second one, we could really increase minimum time for 2 months, which I believe is feasible for possible investigations.

I'm not sure if by closing this issue this will be lost as proposal, but I think we already gathered a lot of information. @Laura-O @lgarron could you help me?

**Comment by lgarron** [comment]
> What about keeping the electronic records? Like taking photos or scanning them.

For FMC, https://github.com/thewca/wca-regulations/issues/125 might help.

> I'm not sure if by closing this issue this will be lost as proposal, but I think we already gathered a lot of information. @Laura-O @lgarron could you help me?

I'm interested in hearing how long after a competition the WEC/WDC usually need to be able to track down evidence.

**Comment by Claster** [comment]
Sorry, is this request coming from WDC? I'm trying to understand which problem we are trying to solve. If we don't trust our delegates to check that attempts outside of cumulative limits should be disqualified, I don't see how keeping scorecards for 2 years can help with that.

**Comment by lgarron** [comment]
I sent an email to the WDC and WQAC, and only got a reply from Lorenzo suggesting that holding on to physical records for more than a month is not useful in the vast majority of cases. I'm going to close this issue for now, although we can reopen if there are new arguments.

See #125 for publishing FMC sheets in particular, which is almost as useful as physical records.

**Comment by lgarron** [comment]
The WEC referenced https://www.worldcubeassociation.org/documents/motions/16.2017.1%20-%20Disputes.pdf , which indicates that:

> 2. Disputes must be filed within sixty days after the disputed act or decision.
> 3. Disputes must be handled within sixty days of the date of dispute.
> 4. Appeals to decisions on disputes must be filed within sixty days after the decision.
> 5. Appeals must be handled within sixty days of the date of appeal.

If this time frame becomes standard, it suggests that at least a little more than 60 days is appropriate – perhaps 90 days.

I don't think we need to address this immediately, but I'm reopening the issue to consider this next year.

**Comment by AlbertoPdRF** [comment]
Actually, with #673 this doesn't belong in this repository anymore!

**Comment by cubewhiz** [comment]
In that case, now is the perfect time to change it. Since disputes must be filed within 60 days, I think a 60-day minimum is appropriate for retention of paper records (though 90 is probably better to be safe).

**Comment by AlbertoPdRF** [comment]
This should be handled now in https://github.com/thewca/wca-documents/pull/40, so I'm closing this issue!

**Comment by Jambrose777** [comment]
sorry if this is the incorrect place to continue discussion.

From a results standpoint, keeping scorecards is very advantageous to any inquires from investigations that we conduct. For instance we had one investigation that dealt with old competitions, for one of the questions we had the delegate was able to provide a scorecard from 2013, which really helped cleared things up.

As well, as one of the delegates who has delegated the most over the past 2 years, I do not see keeping scorecards as that much of a hassle. I have filled up 1 and 1/4 small storage bins which do not take up much space.
