### ISSUE TITLE
FMC: Allow the competitor to add a missing name in front of the judge

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#653]
We had several incidents with competitors forgetting to write their name on FMC sheets, with some people feeling that a strict application of [E2c](https://www.worldcubeassociation.org/regulations/#E2c) (DNFing for a missing name) is too harsh:

Draft from #575:

> - E2c1+) [ADDITION] If the competitor forgot to write their name on their intended solution paper before the end of 60 minutes, they may be allowed to add their name (without modifying their solution or making any other changes) under direct supervision of the judge, at the discretion of the Delegate. The competitor must ask and write their name before they finish submitting their solution (e.g. placing it in the judge's hands and allowing the judge to move on to the next competitor, placing it on the judge's table and walking away), and are not allowed to add their name later.

**Comment by lgarron** [comment]
Also discussed: explicitly allow the competitor to write their name on the back of the solution sheet.

**Comment by kingmathyall** [comment]
I'd like to see an addition that they may write their name on the back, however I'm not too stuck on that - this should be enough

**Comment by campos20** [comment]
If we change [E2c](https://www.worldcubeassociation.org/regulations/#E2c) from

> At 60 minutes, each competitor must give the judge a legibly written solution with the competitor's name, using...

to
"At 60 minutes, each competitor must give the judge a legibly written solution, using..."

the competitor can write in advance or after it.
