### ISSUE TITLE
Get rid of the exception in 9b1a)

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/wca-regulations#658]
These formats have been requested just a couple times during 2018 and I think an acceptable reason to hold them was never provided, so all the requests were declined. If we can't find any good reason to allow holding these formats, the best would be to just get rid of the exception that makes it possible to request them.

**Comment by jamesquinn1** [comment]
What about a head to head second round of 3x3? I've seen that happen a few times. Also, I don't really care too much either way on this, but is there any reason not to allow them? Is consistency the reason?

**Comment by CarterKoala** [comment]
Yes, head to head 3x3 round 2 is a thing. Here’s an example:

https://www.worldcubeassociation.org/competitions/RacetheClock2018

**Comment by AlbertoPdRF** [comment]
@CarterKoala The format of the 3x3 second round is still average of 5 on that competition, the bracket tournament is listed as an unofficial event.

It's true that this has happened in the past a couple of times, but back then any format was approved without questions, which is not the case anymore.

**Comment by jamesquinn1** [comment]
I still have the same question as before, that I also had with 6/7 bo1/2. Is there any reason not to allow any format? I don't see any harm in having bo1, bo2, or bo3 rounds.

**Comment by CarterKoala** [comment]
@AlbertoPdRF Oh OK my mistake, It was bo1 second round last year, so I just assumed it was the same this year. Now that I look at how that’s done I think I agree with you, it’s kind of unnecessary to allow those types of rounds.

**Comment by lgarron** [comment]
Sounds fairly uncontroversial, like the removal of qualification rounds.

@AlbertoPdRF, would you mind sending a pull request for this?

**Comment by AlbertoPdRF** [comment]
Sorry @jamesquinn1, I overlooked your first comment! Yes, consistency is probably the most important reason. Fairness is also a reason.

@lgarron Sure thing! Should we get rid of 9b+) too as part of this change? Seems (almost) irrelevant to me now after this change and #661.
