### ISSUE TITLE
Keep a (official) list of unofficial events

### ISSUE THREAD

**Issue by campos20** [thewca/wca-regulations#659]
Adding and removing events is being a thing nowadays. I think it would be a nice idea if WCA kept a list of all events in a competition (eg.: Redi, 2-7 relay, TeamBLD...). Besides enforcing the community character of WCA, this could also be helpful if WCA decides to add new events.

**Comment by lgarron** [comment]
This might work well on an additional reference page on the website.

I'll also keep it in mind for https://unofficial.cubing.net/ (an unofficial project).

**Comment by J-Rohault-dF** [comment]
Well I already had an idea to make a list (but it's fully unofficial for now) in #636

**Comment by abunickabhi** [comment]
Is [https://unofficial.cubing.net/](url) a sort of site to relate SS comp events to standard WCA events,
pipelining all the events that can possibly transit from SS comp like Redi, 2-7 relay, TeamBLD, to official WCA events in the future?

**Comment by lgarron** [comment]
> Is [https://unofficial.cubing.net/](url) a sort of site to relate SS comp events to standard WCA events,
> pipelining all the events that can possibly transit from SS comp like Redi, 2-7 relay, TeamBLD, to official WCA events in the future?

Yeah, all current events became official by trying them at comps before they were official.

**Comment by campos20** [comment]
As of wcif, this has become easier. It's just a matter of looking the schedule and search for the activies starting with "other" :)
We need to encourage delegates to fully schedule unnoficial events.

**Comment by J-Rohault-dF** [comment]
Something I found on the old WCA forum, I don't think it doesn't needs any comment
![image](https://user-images.githubusercontent.com/44101077/53629482-f1c56e00-3c0d-11e9-942a-acce3c9d8c7a.png)
Also, skewb was added after 8 competitions (as of 2010, there have been others before 2014), while Kilominx was organized at, at least, 22 competitions since 2016.

Also, I am currently working on the organization of a competition which will be the logical follow-up to No Stress Solving 2017: a competition mainly organizing unofficial events.

**Comment by jamesquinn1** [comment]
That discussion was in 2010, were more held 2011-2013?

Also I would think # of competitions would have more than tripled since 2010, so just 8v22 isnt enough.

**Comment by Jambrose777** [comment]
Here is data that was collected for Kilominx: https://docs.google.com/spreadsheets/d/1agWq6j8HW80swbtKiI1iVvGD9KtIeKNrqreb02-0GLQ/edit#gid=1590136832

Sadly it is not everything as it only contains competition where people sent in the results. So Kilominx could have been held, but just not mentioned.

I think there were around 5-6 competitions in 2018 after WRC declined its addition.

**Comment by campos20** [comment]
> Here is data that was collected for Kilominx: https://docs.google.com/spreadsheets/d/1agWq6j8HW80swbtKiI1iVvGD9KtIeKNrqreb02-0GLQ/edit#gid=1590136832
> 
> Sadly it is not everything as it only contains competition where people sent in the results. So Kilominx could have been held, but just not mentioned.
> 
> I think there were around 5-6 competitions in 2018 after WRC declined its addition.

Did you use WCIF?
