### ISSUE TITLE
Add incident log entries for Regs violations due to Regs maintenance mistakes

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#664]
Per https://github.com/thewca/wca-regulations/pull/661/files/8b3346c868d88802c6be24c5b47cc427e82ba5a1#r239482851 it looks like combined rounds were technically not allowed for 6x6x6 and 7x7x7.

I'd like to add an incidents log entry for this, so that we acknowledge that the letter of the Regs has been violated (although we were following the intention).

Filing this quick bug so I don't lose track.

**Comment by Claster** [comment]
> it looks like combined rounds were technically not allowed for 6x6x6 and 7x7x7.

Why?
