### ISSUE TITLE
Explicitly forbid Bluetooth cubes

### ISSUE THREAD

**Issue by MatteoColombo** [thewca/wca-regulations#665]
Bluetooth cubes should be forbidden by [3h](https://www.worldcubeassociation.org/regulations/#3h) and  [2i](https://www.worldcubeassociation.org/regulations/#2i), but I think it would be better to explicitly specify that they are illegal and that they cannot be used in competitions.

I think that an addition to rule 3h would be sufficient to avoid any confusion.

**Comment by xsrvmy** [comment]
A guideline should be enough for this.

**Comment by abunickabhi** [comment]
As long as the rule, to not having any screen facing the competitor, I do not see how Bluetooth cubes can give an unfair advantage to the competitor.

If the cube is not giving haptic feedback (eg, touch or vibration) to the solver, then the puzzle fits in the WCA description of a valid puzzle.

If not for now, after a few months/years of deliberation, Bluetooth cubes should be allowed in official solves. Competitors already use GoPro for recording their solves, for the sole purpose of self-analysis after the attempt. Bluetooth cube also serves that purpose to the competitor.

**Comment by Epride** [comment]
@abunickabhi Bluetooth cubes can give the advantage of knowing the scramble before you receive it. This information could be simply broadcast to the competitors phone and would be impossible for the Delegate to police as heaps of competitors check their phone in the waiting area for all sorts of reasons. I agree with these cubes being explicitly forbidden

**Comment by zeecho** [comment]
Well, it's actually really easy to cheat with this cubes since you can know the scramble through your phone while it is applied by the scrambler, right? Moreover, it would be really contradictory to forbid interactions with "electronics or audio equipment" while accepting an electronic cube… 

IMO, it must definitely be forbidden and I do not see any valid reason for authorizing this cubes in your message

Edit: a bit ninja'd by @Epride 

Edit2: By the way, [2i](https://www.worldcubeassociation.org/regulations/#2i) already clearly forbid this cubes so I guess we do not need to add anything to the regulations

**Comment by viroulep** [comment]
I don't see how 2i is not clear about that:

>2i) While competing, competitors must not use electronics or audio equipment (e.g. cell phones, MP3 players, dictaphones, additional lighting).

A bluetooth cube is an electronics device, and therefore must not be used while competing.
We could add it to the list of examples given, but to be honest I don't see where the confusion could come from.

**Comment by lgarron** [comment]
I also agree that 2i is sufficiently clear.

(I would love to find a way to allow smart cubes that cannot transmit information about their state before the attempt, but we're clearly not there yet.)

**Comment by lgarron** [comment]
We contacted Gan about their [Gan 356i](https://www.youtube.com/watch?v=QkfIPcIFGm0) to ask them to make sure that it can be distinguished from a normal puzzle:

> The demo video for the 356i looks indistinguishable from a regular cube. Other Bluetooth puzzles have different shapes, or have visible holes in some of the stickers for charging, but other colorings or markings would work.
> 
> A distinguishable puzzle will help us mitigate the potential for cheating at WCA competitions. If the 356i looks like a regular 356 cube, then every similar-looking cube could potentially be used for cheating. It would be great to avoid a situation where every puzzle that looks like a GAN 356 needs to be inspected.
> 
> I understand that it can be easy for a competitor to get around certain modifications, e.g. by switching center caps. However, if we find that a competitor did this intentionally then this makes it much easier to establish cheating vs. accidentally using the wrong puzzle.

Gan confirmed:

> ... it is distinguishable--the center piece is different, it has 4 grooves on the corners for scrambler to grab it. 

I think this is a reasonable line for now, and I hope all manufacturers keep their Bluetooth cubes distinguishable.

**Comment by lgarron** [comment]
I sent this email on the WRC-internal thread:

> I've spent a lot of time thinking about this, and my conclusion is that we *cannot prevent cheating in general and should not expect a practical solution*. We can perform checks in high-profile situations, but we need to trust competitors.
> 
> 1) Checking puzzles at all competitions is not practical.
> 2) It's easy for competitors to receive covert information.
> 
> # Checking for Puzzles
> 
> Firstly, I don't there is a reliable detection mechanism that we can use at most competitions.
> 
> ## Hardware
> 
> The first Bluetooth puzzle models on the market already look like normal speedcubes, and it can only get harder to tell them apart form here.
> 
> As demonstrated in the incident in this thread, it's easy to resticker a GiiKER Bluetooth cube so that it looks like a normal cube that scramblers would not find suspicious.
> 
> The WRC asked Gan to make sure that the Gan 356i is distinguishable from other puzzles, and we learned that it currently has a different center cap from other Gan puzzles. I've ordered one, so we'll see how hard it is to disguise.
> 
> So for current models we can remove look at/remove center caps to check. But removing center caps from every puzzle at every competition is not practical. So we either need a non-visual way to check puzzles, or to find a limited number of situations to check.
> 
> If someone finds a portable electronics scanner that can single out Bluetooth puzzles with a sufficiently low false positive (is the prevalence of magnetic puzzles a hindrance here?). However, I'm skeptical of this and I expect that not nearly every organization team could afford this.
> 
> In the short term, we could theoretically make a list of puzzle models with Bluetooth variants that should be inspected closely. I think this way too impractical, given that we regularly have situations where competitors make it through attempts "illegal cubes" (e.g. logos in BLD).
> 
> So I strongly believe that we can't detect hardware this in general. We could encourage checking center caps for high-profile situations (e.g. major championships), although I'm also sceptical of that.
> 
> ## Software/Signals
> 
> Once a Bluetooth puzzle has been built, it's a not difficult software change to do one of the following:
> 
> - Disguise the device name as something innocent (e.g. "Alice's Phone", or a common IoT device name).
> - Pause Bluetooth signals until the puzzle thinks it's being transported to a station, in proximity to a competitor (by checking signal strength to a device with the competitor) or the competitor gives the puzzle a signal (e.g. holding it in a special sequence of orientations during inspection).
> - Encrypt Bluetooth packet contents.
> - Obfuscate the metadata for Bluetooth packet sos that they don't look like normal communication with a single device.
> 
> Note that the state of a puzzle fits inside a single Bluetooth packet. If the puzzle sends its state only once per attempt, you'd have to catch a single, stray, innocent-looking Bluetooth packet every few minutes. Bluetooth puzzles use BLE, which is specially designed to support such one-off packets rather than continuous communication.
> 
> And even if we could perfectly detect Bluetooth, there are other cheap radio technologies. In particular, a lot of Bluetooth-capable consumer devices also support Wi-Fi, and I wouldn't be surprised to see manufacturers do so in the future.
> 
> Since this rules out *detecting* signals, the only alternative I can think of would be to block them. That would also take expensive hardware and extreme diligence (e.g. Faraday cages for scramblers and puzzle covers).
> 
> ## Swapping Puzzles ⇒ Checking for Every Attempt
> 
> It takes barely any sleight of hand for a competitor to swap an identical-looking practice puzzle with their official puzzle at the end of an attempt. It's also easy to make look like an innocent accident if someone in case anyone was watching/filming.
> 
> Possible mitigations:
> - Ban any puzzles in the competitors area. This would probably be very unpopular, and it's still possible to "accidentally" a spare puzzle in your pocket and "absent-mindedly" swap it at the end of an attempt so that the judge is unlikely to notice.
> - We could mark all submitted puzzles. But then we need an unforgeable indicator that we can put on a puzzle, but then also remove it before letting the competitor take back a puzzle.
> 
> I think that someone who's willing to use a Bluetooth puzzle for cheating would certainly also be willing to pull off a swap. So we'd have to keep track of puzzles carefully, and check puzzles every time they return to the scrambling station.
> 
> ## Competition Resources
> 
> Recent experience with scramble integrity and scramble secrecy suggest that it's hard to get organizers to take it seriously enough to dedicate significant competition resource. The risks are too low to prioritize Bluetooth puzzle detection at every competition.
> 
> Consider that the following are still probably still common occurrences that don't even make it into Delegate reports:
> 
> - Duplicate scrambles. (The competitor literally knows the entire solve ahead of time!)
> - Competition layouts where competitors can easily peek at the stage or the scramblers! (See "Peeking!" below.)
> - Temporarily losing track of a puzzle, or conditions where a competitor can cause a puzzle to bypass the normal submission process (e.g. get it directly to the scrambler table rather than the submission table)
> - Inexperienced judges/runners
> - Competitors being able to walk around between attempts. (See "Peeking!" below.)
> - Audience members wandering into the competition area. (In my experience, parents often come up to scramble stations with questions!)
> 
> # Covert Information
> 
> It would take me an hour to write a phone app that detects when a GiiKER cube is scrambled, and sends me a nice cross via Morse code vibrations in my pocket that no one else can notice. If that's not enough, I can hand you my normal phone to show that I'm not cheating, and use a second phone in my shoe to receive the vibrations instead. (https://en.wikipedia.org/wiki/Borislav_Ivanov) This costs me $0 in resources, I could pull it off at any competition, and I challenge you to think of a measure that would prevent it.
> (Note: I would never actually do this at a competition. However, experience with Bluetooth cubes tells me that a decent programmer could implement this from scratch in a day or two, so it's pointless to try to prevent the community from gaining the knowledge or tools to do this.)
> 
> Therefore, it's practical for a person to receive covert signal unless we physically remove all electronics from them. Note that this would probably entail:
> - Banning cameras.
> - Implementing strong punishments for someone who "accidentally" kept a device with them
> - Keeping exceptions for competitors with medical aids. (Note: There are Bluetooth hearing aids, whose whole purpose is to surreptitiously communicate to a person's ear!)
> 
> Also:
> - Competitors like using headphones between attempts!
> - What about notifications and phone alarm? https://github.com/thewca/wca-regulations/issues/567
> - Smartwatches: https://github.com/thewca/wca-regulations/issues/232
> 
> Note that this is not unique to Bluetooth puzzles. There are other ways to cheat:
> 
> ### Peeking!
> 
> At many competitions, it's easy to peek at scramble stations from the Competitors Area. (https://www.worldcubeassociation.org/regulations/guidelines.html#4b2++) In my experience, it's not uncommon to hold competitions in an auditorium with a small stage. A row of chairs may be only ≈2m away from a solving station.
> 
> And even if the competitors area is not close to the solving stations, I think it's often easy for competitors to wander around innocently — even walking into the audience or behind the scrambling table:
> 
> - "Innocent" example with permission: I urgently need to go to the bathroom!
> - "Innocent" example without permission: Oh, I didn't know this was outside the Competitors Area. I'm sorry, I'll go back!
> - "Innocent" example without permission: I wanted to retrieve a puzzle/phone/snack/something from my bag.
> 
> ### Communicating about Scrambles
> 
> Competitors in the Competitors Area are very likely to have the same scrambles for their attempts. It's easy to design a secret code to convey information. But even without secrecy, something like an exclamation of "scramble 1 had an awesome green X-cross" is unlikely to result in more than a warning from Delegates.
> 
> ### Audience Accomplice
> 
> Someone in the audience can observe a scramble and communicate information to the competitor. Note that there are cases where *a single bit of information* is useful to the competitor, such as the presence of permutation parity in a blindfolded solve. An audience member can easily use a small number of coughs to communicate. https://en.wikipedia.org/wiki/Charles_Ingram#Who_Wants_to_Be_a_Millionaire?
> 
> Example: Competitor using M2 for BLD. Competitor pauses and gives an innocent signal like placing a hand on the table. Accomplice coughs once to indicate that the M slice is solved, twice to indicate that it's not. Alternatively, a slightly fancier cough pattern can communicate exactly which piece is at UB. This may sound a bit far-fetched, but it's a straightforward two-person version of the method used in the WCA's most infamous cheating scandal.
> 
> ### FMC Examples
> 
> There are ways of cheating that would be hard to catch for FMC, such as an competitor sneaking printed algs with a pen or a snack item:
> https://www.worldcubeassociation.org/regulations/#2i1d
> https://geekologie.com/2013/04/the-editable-print-a-cheat-sheet-on-an-a.php
> https://www.telegraph.co.uk/news/2016/05/11/10-crazy-and-inventive-ways-students-have-cheated-in-exams/
> 
> In fact, we recently had an FMC world record where much of the community strongly suspects that the competitor cheated, but our resources are insufficient to resolve that concern.
> 
> I don't mean that we should ignore one avenue of cheating just because there are other ones, but we fundamentally need to put some trust in competitors.
> 
> # What should we do?
> 
> I recommend the following:
> 
> - Don't attempt to prevent cheating for every attempt of every competition.
> - While verifying major records, do a quick check for electronic hardware.
> - For high-profile rounds, work with competitors in a semi-trusted model.
> 
> ## Don't Attempt General Prevention
> 
> While I don't think we should be tolerant of cheating, I also don't think we can catch a moderately motivated cheater with an unremarkable result, like the example in this thread. And if we make a big fuss about preventing all possible such cheaters, then we just add the the "glory" of successful cheating.
> 
> I think it would make sense to take some simple measures like trying to make Delegates aware of current known models, and empowering/encouraging them to check if they have develop a moderate suspicion. But I don't think it makes sense to mandate anything.
> 
> ## Quick Checks for Records
> 
> We do have a process for handling notable results like WRs, for which we e.g. do a scramble check. For the time being, we can provide Delegates with ways to check for known hardware.
> 
> Less notable results (e.g. NRs) often go unnoticed by the Delegate, and I would say that they fall under "don't attempt general prevention". (That is, don't make organizers go out of their way to detect "high-profile" results immediately after the attempt.)
> 
> ## Trust Competitors in High-Profile Rounds
> 
> There are situations where we know significant results are at stake, such as final rounds of championships. In this case, I would suggest that we do no more than the following:
> 
> - Make sure that every competitor is actively watched at all times (e.g. by the judge, the runner, or a staff member in the Competitors area).
> - Ask competitors to submit general-purpose mobile devices like phones. Allow special-purpose MP3 players for those who want to listen to music.
> - Trust them not to be using sneaky methods.
> 
> However, I think this should be up to the championship, not required.
> 
> In fact, I think it might be reasonable to go farther and argue that this model of trust might make it reasonable to *allow* Bluetooth puzzles in certain rounds/situations. (After all, the problem isn't whether someone is using a Bluetooth puzzle, but whether they are using it to *cheat*.) But that's a separate discussion.
