### ISSUE TITLE
Allowing a different type of 'time limit' for Multi-Blind

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-regulations#666]
(Basically a copy of what I wrote on the "Multi-Blind Discussion" thread, which seemed to have been overlooked).

For mostly all events, there is specified a time limit for the event by the organisation team, with the exception of Fewest Moves, and Multi-Blind. It would not make much sense to add a regular time limit here either. 
However, I would like to propose the possibility of adding a different type of time limit for Multi-Blind. What I am proposing is a 'limit of minimum points' which could be set by the organisation team, just like a regular time limit is for other events. For example, it could be set so you would need at least 5 points to be able to compete/not get a DNF. Because of Regulation A1c, a competitor would not be able to submit 4 cubes in this case, as there is no possible way the competitor would be able to get at least 5 points, which would violate A1c, as you would then know you are getting a DNF beforehand. 
This could save some time/free up more of the stations, as most of the competitors competing in Multi-Blind (at least in my area) attempt few cubes, as you would then drastically cut the amount of people down. 

I can give a local example of how it would affect [an upcoming competition which I am delegating](https://www.worldcubeassociation.org/competitions/DenmarkFriends2019) : At the moment we have 51 competitors signed up for Multi-Blind, of those 51, 38 has a result. 38 is a lot, and might be something that would be hard to pull off. So, if we were to set a 'limit of minimum 5 points', we would then cut it down to 20 eligible participants, plus a few more as some are likely going to attempt more than their current PR. This would make the event a lot easier to overcome for a competition with few resources. 

I'd like to hear what others think about this proposal!

**Comment by xsrvmy** [comment]
I feel like this might not be comparable since MBLD results vary significantly from attempt to attempt, so even moderately good competitors can DNF. Enforcing a point limit might also make competitors attempt more/less cubes for a better chance of success, whereas a time limit does not affect the range of possible results in this way.
However, requiring a minimum number of attempted cubes or successfully solved cubes could be a better idea.
