### ISSUE TITLE
Notation question regarding NxNxN puzzles

### ISSUE THREAD

**Issue by scottbedard** [thewca/wca-regulations#667]
Hi, I'm working on a project and I'd like it to follow WCA rules and notation as closely as possible. After looking at [`rule #12a`](https://www.worldcubeassociation.org/regulations/#12a), it looks like we only have the following types of moves....

- `Face Moves`, your basic `U`, `L`, `F`, `R`, `B`, and `D` turns.
- `Outer Block Moves`, which are simply a face move that also moves inner slices

My question though is how do we describe an "inner slice turn"? For example, imagine a 5x5 where the turns `Fw F'` have been made. Is there any way to describe this with a single piece of notation? After a bit of googling I ended up [on this page](https://meep.cubing.net/wcanotation.html), which would describe the above sequence as `f`.

Is there any standards or spec for this type of notation? If not, is the above convention commonly used?

**Comment by HippolyteM** [comment]
Dear Scott,

I've no idea on how people would note this kind of move, but I know for sure that this question isn't relevant from a WCA point of view, as these moves are in no way required. The only use of this notation is for scramble sequences.
(note that even for 333 where we have a Fewest Moves event we don't have any notation for slices as the OBTM notation we officially use count them as two moves.)
If you need to know what's currently in use amongst the community to note some sequences including slices without using two moves (if there's something used at all), you should better post on speedsolving or any other non-official cubing network.

Best,
Hippolyte

**Comment by scottbedard** [comment]
Perfect, thank you for the clarification and the fast response! I'll dig around and see if there are any common conventions, and if not I'll implement my own notation for these turns.
