### ISSUE TITLE
More explicit provision about incorrect scrambles

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#668]
This issue is talking about receiving a scramble that the competitor is not intended to receive, not about misscrambles.

Right now, the only regulations regarding scrambles appear to be:
- must be generated by TNoodle
- must be live at the start of the attempt (have not been used for 2 hours)
- competitor must not have seen the scramble when judging or scrambling

There should probably be regulations explicitly allowing/disallowing any of the following:
- the entire group of scramble is for the wrong group
- switching groups halfway through an average
- scramble out of order (this is usually detected next solve by a duplicate)
- incorrect extra
- extra when normal scramble is expected
- scramble from wrong round/event (eg. oh scrambles in 3x3)

Similarly, it might be a good idea to prevent a competitor from switching assigned scramble groups after an event has started without reason (eg. stuck in traffic).

**Comment by EdHollingdale** [comment]
> scramble from wrong round/event (eg. oh scrambles in 3x3)

I'm not sure this is required - it should be covered by the wrong group case. Especially since this can be fixed up in WCA workbook assistant before results are submitted. E.g. 3x3 R3 scrambles are used for OH R2 G2. Then OH R2 G2 are used for 3x3 R3 and they are switched later on in workbook assistant so the "correct" scrambles were used for each round. I think this case is fine - provided it is not a case of OH R2 G2 being _re-used_ for 3x3 R3.

**Comment by jamesquinn1** [comment]
switching groups halfway through an average

Should this not be allowed? On the local level, this would require comps to have had everyone finished before they can move on to the next group, but at the local comps I go to we call the next group when some slower people still have one solve left. We could have multiple sets open, but that would likely result in confusion and the wrong scrambles being given. I feel that this isn't that important for the time it would add.

**Comment by xsrvmy** [comment]
@jamesquinn1 I just meant these situations need to be considered. I don't care about this specific case as long as the scramblers are not combining easy scrambles or anything like that.
