### ISSUE TITLE
Summary of changes for the 2019 Regulations

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#681]
(Note: this post has been updated a few times. Old copies like the [call for feedback](https://www.worldcubeassociation.org/posts/call-for-feedback-wca-regulations-2019-draft) may be slightly out of date.)

The WRC invites the WCA Ccommunity to discuss and [send feedback](https://www.worldcubeassociation.org/contact) on a new draft version of the WCA Regulations for early 2019. This version is not final, and we welcome suggestions on any aspect of the set of changes.

If there are no major issues, we plan to send a final draft to the WCA Board for approval at the beginning of March. (See [Motion 14.2019.1](https://www.worldcubeassociation.org/documents/motions/14.2019.1%20-%20Amendments%20of%20Regulations.pdf) for details about the process.)

The changes listed in this summary are publicly available at https://www.worldcubeassociation.org/posts/call-for-feedback-wca-regulations-2019-draft. You can review all individual changes in this [comparison on GitHub](https://github.com/thewca/wca-regulations/compare/official...draft-2019-02-18). If you do not want to open all the individual changes, you can click on "Files changed" to see the full textual changes to the Regulations and Guidelines. All changes and additions are marked green and removals are red.

Round format changes:

- Means are now recognized for 4x4x4 Blindfolded and 5x5x5 Blindfolded "Best of 3" rounds. ([commit](https://github.com/thewca/wca-regulations/commit/8b3a38bf71836c42eab409f574612daee6a124f4) | [discussion](https://github.com/thewca/wca-regulations/issues/539))
- The "Best of X" format has been removed from all events except blindfolded events and 3x3x3 Fewest Moves. ([commit](https://github.com/thewca/wca-regulations/commit/bc7e6cc28c5e1f4928951460159db5861b6fe773) | [discussion](https://github.com/thewca/wca-regulations/issues/576), [commit](https://github.com/thewca/wca-regulations/commit/92e626ba258998524cfe279d88f9c7b0d7acee93) | [discussion](https://github.com/thewca/wca-regulations/issues/658), [commit](https://github.com/thewca/wca-regulations/commit/76157f0013a3de06c50f413e4194e6a439d4382e) | [discussion](https://github.com/thewca/wca-regulations/issues/693))

Competition organization changes:

- Scramble signatures should be used for all competitions in 2019 ([commit](https://github.com/thewca/wca-regulations/commit/8ef591a2c276ce775149de5e6bba30ae160d14e3) | [discussion](https://github.com/thewca/wca-regulations/issues/214) | [discussion](https://github.com/thewca/wca-regulations/issues/591) | [discusssion](https://github.com/thewca/wca-regulations/issues/640))
  - Scramble signatures are planned to become mandatory in 2020.
- The WCA Delegate must not give scramblers (or anyone else) access to scramble sequences for any group before it has begun. ([commit](https://github.com/thewca/wca-regulations/commit/fb33a890cff5ecc10107691fee550084dad36209))
  - Note that [TNoodle 0.14.0](https://www.worldcubeassociation.org/posts/tnoodle-0-14-0) includes scramble set PDFs with individual passcodes to help with this.

- Time limits have been clarified ([commit](https://github.com/thewca/wca-regulations/commit/ea2d719fe5d7eb11ce210a9499aa1c5f4627560d))
  - Time limits must be announced before the competition, rather than just before the
  round.
  - Only one cumulative time limit can apply to a given round.
  - Cumulative time limits include time elapsed in DNF attempts.
  - The judge and WCA Delegate may estimate cumulative elapsed time ([commit](https://github.com/thewca/wca-regulations/commit/52ce26093bd769dcee90ec925cef0d7a002dbdfa))
- Scramblers should be visually isolated from competitors. ([commit](https://github.com/thewca/wca-regulations/commit/21c1c3cc44816c1064d9ac4dbb14bc0e53b8ecaa))
- Many competition requirements have been moved from the Regulations to the new [WCA Competition Requirements Policy](https://github.com/thewca/wca-documents/pull/40) ([commit](https://github.com/thewca/wca-regulations/commit/476f11632d025ec500cdedd5b964b35051f7bd4f))

Other substantial changes and clarifications:

- Individual non-permitted puzzles in multi BLD may count as unsolved instead of DNFing the whole attempt, at the discretion of the Delegate. ([commit](https://github.com/thewca/wca-regulations/commit/dfaecca2213de51e7d638b623d3976f95c671fbd) | [discussion](https://github.com/thewca/wca-regulations/issues/545))
- Clarified that competitors start the attempt for blindfolded events, and that they must ask the judge before "testing" a timer. ([commit](https://github.com/thewca/wca-regulations/commit/2879c0dbdb3f4c33f7bca80b8dc5a725fc7f8f5f) | [discussion](https://github.com/thewca/wca-regulations/pull/717))
- Competitors are allowed to have hand warmers and food at certain times, at the discretion of the Delegate. ([commit](https://github.com/thewca/wca-regulations/commit/7802b0e2f48f6c7f87e78162aaad99601da33fcf) | [discussion](https://github.com/thewca/wca-regulations/issues/700))
- The competitor must not ask for assistance during a pop, and the judge should prevent others from assisting. If someone picks up a popped part for the competitor, the judge or competitor may ask them to place it on the solving station and not to assist any further. ([commit](https://github.com/thewca/wca-regulations/commit/e3f2769c27d1d0e5039fa799d5be1922122da328) | [discussion](https://github.com/thewca/wca-regulations/issues/624))
- The competitor may touch the official stopwatch, unless the organization team provides an unofficial stopwatch for the competitor. ([commit](https://github.com/thewca/wca-regulations/commit/c66106e266e5b580218f4273f7db4dddd5a55b8d) | [discussion](https://github.com/thewca/wca-regulations/issues/581))
- Starting the timer always ends inspection and begins the solve. This means that the competitor cannot "test" the timer once inspection has begun. ([commit](https://github.com/thewca/wca-regulations/commit/fff14fe406fbe42b4f034d6ffe2df35462f3f994) | [discussion](https://github.com/thewca/wca-regulations/issues/573))
- It is explicitly forbidden to cause puzzle defects intentionally. ([commit](https://github.com/thewca/wca-regulations/commit/18a136749214dbfd8248f58153e23c0d4eb7d95b) | [discussion](https://github.com/thewca/wca-regulations/pull/538))
- If there are multiple green faces next to the top face, the darkest is placed in front for scrambling. ([commit](https://github.com/thewca/wca-regulations/commit/38e00b10f793e7830ee3dafccdf18f753e6cc43e))
- We've specified that Multi-Blind result times are always rounded to seconds, matching the results database. ([commit](https://github.com/thewca/wca-regulations/commit/2d3bac31ed17f8c21d275f3f9fe7674ae8bb92bf))
- Notation for NxNxN cubes has been clarified ([commit](https://github.com/thewca/wca-regulations/commit/8104b4b795b2e9e993cdd220b071354c4ffb0591))
  - Outer Block Moves that move n slices (e.g. nFw) must have 1 < n < N (where N is the number of layers in the puzzle).
  - Execution Turn Metric (ETM) is defined, and used to define the move limit for 3x3x3 Fewest Moves.
- Clarified that any center piece may have a logo, not just the most central one. ([commit](https://github.com/thewca/wca-regulations/pull/714/files) | [discussion](https://github.com/thewca/wca-regulations/issues/710))
- Clarifications for Fewest Moves ([commit](https://github.com/thewca/wca-regulations/pull/678))
  - Information to identify an attempt is defined as name, WCA ID, or registrant ID (at least one), and optionally competition name/round/attempt number.
  - The competitor may write information to identify the attempt before the attempt has begun.
  - The competitor may write information to identify the attempt in front of a judge while submitting a solution (but the information must not be added after).
  - Competitors should black out/scribble out moves that are not part of the solution.
  - Judges may interpret `{r}`, `<r>`, or `(r)` as `[r]` for inexperienced competitors.
  - Competitors may supply their own pens for Fewest Moves if they wish. ([commit](https://github.com/thewca/wca-regulations/commit/5f9e2a09bbaa1ec5c8ae1d3bf859c6e00e32e353))
  - Pencils and similar writing implements are explicitly permitted for Fewest Moves.
  - Competitors may join a 3x3x3 Fewest Moves attempt late, if there is no risk they could have information about the scramble ([commit](https://github.com/thewca/wca-regulations/commit/0eabb1602740bcab6e426a8f955318308a454b38))

**Comment by jamesquinn1** [comment]
Is it necessary to specify that bo1 and bo2 are not allowed for 6/7 if they are being not allowed for any event in the next bullet? Seems a bit redundant to me.

Also, would it be better to ask that spectators accidentally touching pieces should place them back where they fell? That seems like what most people would do naturally if they are told not to touch pieces after accidentally touching a piece, and also could prevent someone from placing a spectator in the crowd to help them if they pop.

**Comment by lgarron** [comment]
> Is it necessary to specify that bo1 and bo2 are not allowed for 6/7 if they are being not allowed for any event in the next bullet? Seems a bit redundant to me.

They were substantially different decisions, so they have separate commits and discussions. But you make a good point that it's simpler for readers to understand if we combine them, so I'll try to combine them.

> Also, would it be better to ask that spectators accidentally touching pieces should place them back where they fell?

Could you comment at #624? (I'd like to keep this issue focused on announcement logistics.)

**Comment by jfly** [comment]
For the event format changes, can someone from the WRC send in a PR to the WCA website to reflect the changes? @viroulep, do you have time to take care of this? I think there are two pieces to this:

1. Changing the edit events page to not allow selecting no longer allowed formats.
  - Ideally this would be done in a way that wouldn't break stuff for past competitions, but that might get tricky, and I don't think is critical that we do well, as the edit events page doesn't get used often for past competitions.
2. Updating the results uploading scripts/the workbook assistant to not allow these unsupported formats?
  - Off the top of my head, I don't actually know what sort of validation the results admin scripts and the workbook assistant do here, if they don't do any such validation, then I don't think we need to add that right now.
3. Non WST work, but still important. Updating cubecomps. @ronaldmansveld, maybe you could work with Luis to get this change done?

**Comment by viroulep** [comment]
I can't do anything before the first week of January due to holidays, but I'll handle 1 at that point.
About 2: I don't know the source code of the workbook assistant at all :s 
I'll update thewca/worldcubeassociation.org#3127 at that point too (although I suspect both the events page and the various upload scripts are using the same "allowed format" sources!).

**Comment by lgarron** [comment]
I'm locking this issue because I want to link to it, but want to encourage constructive discussions to take place on individual issues. Click on the links in the first post above for details on an issue. If something isn't covered there, consider [searching for other issues](https://github.com/thewca/wca-regulations/issues) or [filing a new one](https://github.com/thewca/wca-regulations/issues/new).

**Comment by lgarron** [comment]
Posted for public feedback at https://www.worldcubeassociation.org/posts/call-for-feedback-wca-regulations-2019-draft
