### ISSUE TITLE
Have 4x4x4 Blindfolded & 5x5x5 Blindfolded implemented onto the WCA site

### ISSUE THREAD

**Issue by kingmathyall** [thewca/wca-regulations#682]
With the new addition of having 4/5BLD recognized, it should be implemented into the site to show up on all appropriate pages (i.e. history, records, profiles)

**Comment by J-Rohault-dF** [comment]
Well they are, where is the problem?
![image](https://user-images.githubusercontent.com/44101077/50372216-a9188580-05ca-11e9-8f9e-8928c359f43a.png)

**Comment by J-Rohault-dF** [comment]
Or maybe you're talking about means, in that case this in not the right place to talk about it.
Here is more appropriate: https://github.com/thewca/worldcubeassociation.org/issues

**Comment by kingmathyall** [comment]
You see..,the one time I try and strt something on github and I do it incorrectly. I’ll make another issue in the correct place with the correct wording once in actually awake. Thank you!

**Comment by lgarron** [comment]
For what it's worth, we can transfer issues between repositories now.
However, https://github.com/thewca/worldcubeassociation.org/issues/3721 is just created, so I'll close this one.
