### ISSUE TITLE
A7 incorrect times 

### ISSUE THREAD

**Issue by jpbulman** [thewca/wca-regulations#685]
If a time is recorded by a judge incorrectly, and the competitor signs for it anyways, the attempt should be a DNF. Is there somewhere else this is addressed that I don't know about? I know this is not a pressing issue because it is rare that attempts get fixed afterwards, but if the result is always a DNF, this is something I would think should be added in.

**Comment by lgarron** [comment]
Well, in practice usually:

- find out the correct result and replace it, or
- lack enough info to replace the time. In that case, we essentially have someone certifying on behalf of the WCA that the solve is correct.

Can you describe a scenario where it's important to make this a DNF?

**Comment by jpbulman** [comment]
That's a good point, I guess the result should be fixed if the time is found. Well in that case, should it be clarified that this is the procedure? My initial thought was really just to make a concrete regulation for this rather than to have it be delegate discretion. I guess the only scenarios where I think it would be acceptable to DNF are
1. It is somehow known the competitor is intentionally trying to get a better time by having the incorrect time be written down.
2. The result is knowingly invalid and the original results cannot be retrieved (ie, a much better than world record time for an average competitor). This I could see being a bit more difficult to deal with because it is the competitors word against the delegate, but I think it could resolved with things like asking for a reconstruction and talking to judges.

**Comment by xsrvmy** [comment]
Well case 1 would be considered cheating and is an automatic DNF.

**Comment by xsrvmy** [comment]
I recently saw this again and think that for the second case, we might be able to give the worst possible time instead (time limit -0.01).

**Comment by Jambrose777** [comment]
> I recently saw this again and think that for the second case, we might be able to give the worst possible time instead (time limit -0.01).

There is no reason to muck up the database with knowingly incorrect information. I don't think this is a reasonable solution.

**Comment by xsrvmy** [comment]
@Jambrose777 isn't it more inaccurate to give a DNF if we know the solve was successful but just written down wrong?

**Comment by Jambrose777** [comment]
> @Jambrose777 isn't it more inaccurate to give a DNF if we know the solve was successful but just written down wrong?

If you can't get the original time and can't give an extra, DNF is preferable.

Kinda a different case, but when times are written as 14.3 and we enter as 14.39, this would be a case where we go against that due to missing data.

**Comment by xsrvmy** [comment]
Is it still preferable if it denies a competitor a podium (like 5bld success) or first avg/mean in an event?

**Comment by Jambrose777** [comment]
I don’t see why podiums or first average/mean in an event changes how you should rule on a single solve.

Ie, should you rule a close +2 as good cause it’s the competitors pb? No you should rule it based on 45 degrees and under.
