### ISSUE TITLE
Should an analog of A3d apply to BLD events?

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#695]
I know that A3d currently does not apply to BLD, but shouldn't a competitor also receive a +2 for moving the entire cube + cover set-up in front of the timer, if the stackmat is actually in use?

**Comment by lgarron** [comment]
For what reasons?

**Comment by xsrvmy** [comment]
So the competitor cannot have his hands 'around' the cover when starting

**Comment by lgarron** [comment]
> So the competitor cannot have his hands 'around' the cover when starting

Hmm, is this a problem in practice? Does anyone seem to be trying to get an unfair advantage from this?

**Comment by xsrvmy** [comment]
Never seen this in practice. However I was just wondering if this was intended. IIRC A3d originally prevented the competitor from putting the puzzle on top of the timer, but of course that would be a DNF in a blind event. The current A3d actually makes sense for BLD but is not applicable because BLD has no inspection.

**Comment by xsrvmy** [comment]
Actually starting the solve with box between hamds/touching the box might be common for no stackmat solves
