### ISSUE TITLE
Allow pencils for FMC (in addition to pens)

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#696]
I have never used a pencil (or observed one used), but some Delegates said that they regularly allow pencil. A pencil doesn't really give an advantage over a pen, so I think we should make the Regulations reflect reality.

Also brought up:
> pencil, marker, crayon
https://groups.google.com/a/worldcubeassociation.org/d/msg/staff/uHJo5FNa7wE/_HMflRCbEQAJ

**Comment by lgarron** [comment]
@kingmathyall, would you be interested and have time to draft a small change for this in the coming week?

It's not completely trivial, since the cleanest way to do it would be to split E3a, but putting either paper or pens as E3e is also unsatisfying. Putting it into E3a is a tad tricky, because we probably want to allow more flexibility for writing devices competitors are allowed to use vs. what the judge is allowed to supply.  But I'm sure there's a reasonable way to finagle it.

**Comment by dancing-jules** [comment]
The general issue with pencils isn't any advantage but erasability (is that a word?). It might make it easier to change things post-attempt. That should of course never happen in the first place. What are other people's thoughts on this?

**Comment by xsrvmy** [comment]
Well technically erasable pens are already allowed. The bigger issue is that pencil can smudge when organizing the solution sheets.
