### ISSUE TITLE
Remove bo1 and bo2 formats for 3x3, 4x4, and 5x5 blindfolded

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#697]
For the 3x3 blindfolded, 4x4 blindfolded, and 5x5 blindfolded events. I'd like to propose to only have bo3 be a valid format.

Here is some data on these formats in use:
All time:
SELECT eventId, formatId, COUNT(DISTINCT competitionId, roundTypeId) FROM Results WHERE eventId IN ('333bf', '444bf', '555bf') GROUP BY eventId, formatId

event | format | # of rounds
-- | -- | --
333bf | 1 | 13
333bf | 2 | 165
333bf | 3 | 5156
444bf | 1 | 68
444bf | 2 | 238
444bf | 3 | 1047
555bf | 1 | 68
555bf | 2 | 146
555bf | 3 | 794

2018 only:
SELECT eventId, formatId, COUNT(DISTINCT competitionId, roundTypeId) FROM Results WHERE competitionId LIKE '%2018' AND eventId IN ('333bf', '444bf', '555bf') GROUP BY eventId, formatId

event | format | # of rounds
-- | -- | --
333bf | 2 | 1
333bf | 3 | 1037
444bf | 1 | 2
444bf | 2 | 6
444bf | 3 | 245
555bf | 2 | 4
555bf | 3 | 196

**Comment by xsrvmy** [comment]
Should a bo1 cutoff also be disallowed? A bo1 cutoff essentially creates a bo1 and a bo2 round.

**Comment by Jambrose777** [comment]
I'd say so. You can accomplish any form of time save the competition needs by using a cumulative limit (which is certainly a lot fairer of an option than a cutoff in a DNF heavy ratio event).

**Comment by xsrvmy** [comment]
How about bo2 cutoff? I saw on a wca stats post that it has happened before.

**Comment by Jambrose777** [comment]
It has happened before, but again I'd like to point out that this is very unfair and doesn't save a comparable amount of time.

Often we will see a high cutoff (ie 6 minutes). Meaning that someone who just makes the cutoff on solve 1 will likely take around 18 minutes to complete all 3 solves. Whereas someone taking 30 seconds can easily DNF their first two solves and not be allowed a 3rd, though they would not have cost the competition any time in reality. This changes the "strategy" of competing in the event to try to get a success on one of the first two just to complete a 3rd attempt.

**Comment by lgarron** [comment]
Overall, I think this makes sense.

I have a fewer minor concerns, but not enough to be against the proposal as a whole.
Copying some of my thoughts from the internal WCA thread:

> - Each attempt has overhead (scrambling, starting + ending the attempt), so a Bo3 with a time limit of 10min can take more resources than Bo1. In particular, note that puzzles for a Bo1 can be scrambled in "in one go", while more attempts require scramblers after the round has started.
> - If someone can only 1 solve within the time limit, they can DNF early to get an extra attempt, effectively choosing their scrambles. This may not be "morally okay", but after a few years of trying to figure out to address such behaviour my conclusion is that it's hard to prevent completely. (For example, a competitor can say "I made an unrecoverable memo mistake" when they stop a solve early and many Delegates would probably wouldn't consider that cheating.)

Additionally, this requires the Delegate/judge to use a lot more judgment for slow competitors.

If a competitor took 18 minutes for their first attempt and the time limit is 30min, does it makes sense to give them another attempt? What it the competitor says the solve was a safety, and they can solve in 10 min? What if the competitor *usually* takes 15min, but could get <12min on a good solve?

**Comment by lgarron** [comment]
We had an internal email thread about this, and there were lots of opinions in favor and none against! I think we should implement it, assuming we get no major concerns during public feedback.

**Comment by xsrvmy** [comment]
Slightly relevant change: when talking to another competitor at my last comp, I learnt that a comp recently indirectly implemented a cumulative attempt limit, where a competitor was only allowed exactly one attempt of 4/5/mbld in an hour, no matter how fast the attempt is, and there were three blocks. I believe these should be explicitly forbidden.

**Comment by lgarron** [comment]
> I learnt that a comp recently indirectly implemented a cumulative attempt limit, where a competitor was only allowed exactly one attempt of 4/5/mbld in an hour, no matter how fast the attempt is, and there were three blocks. I believe these should be explicitly forbidden.

Was it a single attempt per event, or exclusive individual attempt?

The latter has come up more often recently; would you mind filing an issue for it?

**Comment by Jambrose777** [comment]
Can you provide the competition? That shouldn’t be allowed.

**Comment by Baiqiang** [comment]
@lgarron @Jambrose777 I think the competition @xsrvmy said was this: https://www.worldcubeassociation.org/competitions/PleaseBeQuietWPIWinter2018#2788-schedule

**Comment by Jambrose777** [comment]
Ahh thanks. I thought it was a more recent competition.

That comp had special approval from board/WRC if I recall correctly, however I feel that the idea has a lot of flaws.
- normally if a competitor attempts The third attempt in fmc they have dns for 1 and 2, however this wasn’t possible to correctly do for this competition, which caused a results headache.
- 1h++ was completely ignored, which I don’t feel is fair.
- this type of restriction would need to be approved similar to z5 and stated on the new comeptitions requirements and I don’t think we need this for competitions

**Comment by lgarron** [comment]
Done in #704

**Comment by jamesquinn1** [comment]
@Jambrose777 
How does fmc play into that competition? It wasn't included in the your choice slots.

https://www.worldcubeassociation.org/competitions/SouthernChampionship2018#4719-schedule
This did have fmc included, but it only had 3 slots so I don't think this would have caused issues.

https://www.worldcubeassociation.org/competitions/MentalBreakdownGermany2018/#3044-events-and-schedule

This is another competition where someone could DNS 5bld attempt 1 then attempt 2+3, would this be allowed?
Looking through results it seems a few (3) people did do this in 4bld.

**Comment by Jambrose777** [comment]
My bad, That competition had FMC, but the other events were what was affected. The logic still applies for the other events.

For Southern champs, there were a lot of issues here that WRC approved (like using the same scramble set for all 3 time slots, but someone was able to compete 3 4bld attempts in slot 1 and then someone else has them in slot 3.

Overall, I don't see these formats being approved in the future.
