### ISSUE TITLE
10e1 is really confusing  and interacts weirdly with article 12, 10e3, 10e4 and 4b3 (especially in square-1)

### ISSUE THREAD

**Issue by dancing-jules** [thewca/wca-regulations#699]
Currently 10e1 is the following: 

> For every two adjacent parts (e.g. two parallel, adjacent slices of a cube) of the puzzle that are misaligned by more than the limit described in Regulation 10f, the puzzle is considered to require one additional move to solve [...].

This effectively describes a turn-metric for every WCA-puzzle except clock. 

Article 12 additionally describes turn metrics for NxN puzzles and square-1. For NxN (12a3) the definition of OTBM is consistent with 10e1. For square-1 (12c4) the definition is not consistent with 10e1.

---

4b3 describes valid scrambles (as in "puzzle needs to be at least x moves from solved").

There are no problems with NxN (because all turn metrics are consistent) and Mega, Skewb or Pyra (because only 10e1 defines a turn metric for those). 

The problem for clock: No turn metric exists at all (because 10e1 does not make sense in reference to clock) - so 4b3 is not applicable and arguably the solved state could be considered "scrambled".

The problems for square-1: 4b3d cites "11 moves", but does not explicitly state whether it refers to "moves" according to 10e1 or "moves" according to 12c4. 10a3 and 10a4 cite "one move" but do not clarify whether refer 10e1 or 12c4 either (though in this case, the spacial proximity to 10e1 suggests that and 10f4+ confirms 10e1). 

---

My suggestions:

1. Completely re-work 10e1 to be readable and understandable, if necessary with sub-points. (Unfortunately I don't have a specific suggestion on how exactly to formulate an understandable version of 10e1.) 

2. Completely remove turn metrics from article 12.

3. Re-write 4b3d to something that does not mention turn metrics. E.g.: "The (random) state must require at least 6 (x,y) pairs to solve" (should be identical to the current definition for most scrambles)

4. Clarify valid clock scrambles.

---

Additional related nit-picks:

* According to popular belief, there is nothing with 10f4 - as long as the rest works.

* 10e1+ says that the different turn metrics for square-1 exist "because of the shape-shifting property of the puzzle" - I don't see how shape-shifting has much to do with it - but please prove me wrong.

* 10f4+ talks about "counting the moves in the case of a misalignment" in square-1, but 10f and it's sub-points don't actually count anything. 10e1, 10e3 and 10e4 are the ones who do the counting.

**Comment by lgarron** [comment]
I agree that this could be improved significantly, and would love to see some improvements in clarity. Would you mind proposing a full set of textual changes as a starting point?

**Comment by xsrvmy** [comment]
Don't we need article 12 for FMC scoring?

**Comment by dancing-jules** [comment]
> Don't we need article 12 for FMC scoring?

**Comment by dancing-jules** [comment]
Sorry for the close and re-open.

> Don't we need article 12 for FMC scoring?

Oh, thanks. We do need a metric. But we could use just refer back to (new) 10e1. And we only need FMC for 3x3, where HTM suffices. We don't need full OBTM for FMC.

On a side note: I finally understand what current 10e1 is trying to say.

@lgarron What about something like this (as long as we don't add redi-cube, because redi-cuts aren't planar):

>> 4b3d) Square-1: The (random) state must require at least 6 (x, y) pairs to solve.

> 10e1) For any plane that divides the puzzle into two distinct sets of pieces, turning one set in relation to the other by more than the limit described in Regulation 10f, is considered one move. 

>>10e1a) For clock, turning any wheel by any amount in any pin configuration is considered one move. 

> 10e3) If one move is required, the puzzle is be considered solved with a time penalty (+2 seconds). Exception: Clock one move from solved is DNF.

> 10e1+) CLARIFICATION For NxNxN puzzles this definition is congruent with "Outer Block Turn Metric"

> 10e1++) CLARIFICATION For square-1 top and bottom are counted separately. Example: (5, 5) is considered two moves. 

Completely remove 12c4, possibly tweak or remove 12a3. 

Alternatively don't define a metric for clock (and leave 10e3 as it is) and add the following:

>> 4b3g) Clock: The (random) state must require at least two turns of a wheel with distinct pin configurations to solve.

**Comment by dancing-jules** [comment]
If we do this, we can completely remove 10e1+ and 10f4+ (which is replaced by 10e1++)

**Comment by xsrvmy** [comment]
I think one thing we actually need is a general consesus on what exactly is a plus 2/DNF on square 1. I have actually had debates with people over whether things like (1,0)/(-1,-1) is a +2 or DNF. Does the WCA have an actually opinion on this?

**Comment by dancing-jules** [comment]
@xsrvmy the way I read 10f4 I'd say (1,0)/(-1,-1) is +2 and not DNF. But I understand why that's controversial.

@10e1+) Shape-shifting definitely doesn't have anything to do with it. Imagine a hypothetical square-2 barrel. The puzzle would not shape-shift. But notation and metrics would presumably be identical to square-1.

**Comment by ColorfulPockets** [comment]
It's not easy to codify formally, but the way I interpret OBTM and move counting on puzzles is generally the number of wrist turns (not flicks) required to solve the puzzle.

By this standard, though, (1,0) / (-1,-1) would be a DNF because of the puzzle's bandaging?  Which seems inconsistent then with the 45º definition for +2 on U/D.

Squan really is a mess lol

**Comment by ColorfulPockets** [comment]
I think that a clarifying method would be to stop defining "moves" the same way for scrambling and assessing penalties.  We have a certain definition of "move" for scrambling (for minimum optimal solution length generation), but we assign penalties based on a different definition.  I think this is where most of the confusion comes from, and those two different types of moves should be explicitly defined differently and given different names (this is a horrible name suggestion, but something like "scramble unit" and "move")

**Comment by dancing-jules** [comment]
@colorfulpockets - While I agree that separating the definitions would make the most sense from a logical point of view, I think it would in practice only complicate things further. And the regs are already complicated enough.

My attempt was to define exactly one metric per puzzle, but something other than that metric when needed.

**Comment by dancing-jules** [comment]
Issue #778 brought up that we need a metric for "move in inspection". So completely removing the scramble-metric is unfortunately not the solution.
