### ISSUE TITLE
Solved state of clock

### ISSUE THREAD

**Issue by clementgallet** [thewca/wca-regulations#7]
We may want in the next regulations to remove rule `10h)`
    Puzzles not specified in this article are judged according to the solved state as defined by the generally accepted goal of the puzzle, applying the relevant regulations for the Rubik's Cube.
and define the solve state of the Rubik's Clock.

**Comment by lgarron** [comment]
Sarah, could you add this to [clock-clarifications](https://github.com/cubing/wca-documents/compare/clock-clarifications)?
