### ISSUE TITLE
1e2 & 1f2 are vague

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#70]
In [1e2](https://www.worldcubeassociation.org/regulations/#1e2) and [1f2](https://www.worldcubeassociation.org/regulations/#1f2) what exactly is a "capable competitor"?

Also, how often are these two regulations used against competitors?

**Comment by sarahstrong314** [comment]
What do you think about changing 1e2 and 1f2 to this?

1e2) Competitors must be available for judging, if needed by the organisation team. A legitimate reason, at the discretion of the WCA Delegate, must be given for competitor to be dismissed from judging.

1f2) Competitors must be available for scrambling, if needed by the organisation team. A legitimate reason, at the discretion of the WCA Delegate, must be given for competitor to be dismissed from scrambling.

They can probably be worded better. I think the current penalty is unnecessary. If a "capable" competitor refuses to scramble or judge just because he doesn't want to, [2f](https://www.worldcubeassociation.org/regulations/#2f) and some other regulations would probably cover any penalty toward the competitor.

**Comment by SAuroux** [comment]
I like Sarah's rewording. The penalties should be kept though. These 2 regulations are very crucial, and the threat of being disqualified should be easy to perceive for people reading through the regulations in a rather sloppy way.

**Comment by lgarron** [comment]
Note to whoever creates this change: 2j2 needs something more general than "during the course of an event".

**Comment by sarahstrong314** [comment]
https://github.com/cubing/wca-documents/compare/1e2-and-1f2

**Comment by lgarron** [comment]
@Sa967St , could you also fix 2j2 to make it crystal-clear how it interacts with this?

**Comment by sarahstrong314** [comment]
Are you referring to the inconsistent meanings of "event"? Why not change all occurrences of "event" to "the competition" when that's what it means?

**Comment by lgarron** [comment]
Sure, that looks sufficient to me. I just wanted it to be grouped with this change.

**Comment by sarahstrong314** [comment]
Wait a minute, all the occurrences of "event" are indeed referring to a puzzle event, not the whole competition. What's the issue with 2j2 then?

Edit: I just got it. It's the conflict between being disqualified from the whole competition for not judging/scrambling after already competing in an event, right?

Edit 2: I updated the 1e2-and-1f2 branch with an addition to 2j2.

**Comment by lgarron** [comment]
Oh, I think we should keep the policy that every result remains valid after the end of the attempt (unless there was cheating).

I thought it would just good to be clear that "during the course of an event" doesn't have to mean "because of something that was directly associated with the event".

**Comment by lgarron** [comment]
I just realized that 2k includes "(i.e. from all events of the competition)", so that actually handles 2j2. It doesn't come up much, anyhow.

How's the following?

> - 1e2) Every competitor must be available for judging. If he is requested to judge, a competitor may be excused from the responsibility only for a legitimate reason (e.g. being unfamiliar with a puzzle), at the discretion of the Delegate. Penalty: disqualification from the competition (see [Regulation 2k](regulations:regulation:2k)).

(Analogous wording for 1f2.)

**Comment by SAuroux** [comment]
Sounds ok. But on a second thought: wouldn't this allow someone to just
leave everytime he is not competing, so that he just never gets asked to
help?

2013/12/19 Lucas Garron notifications@github.com

**Comment by lgarron** [comment]
Depends on whether the Delegate considers that a valid reason.
Those competitors are usually the ones who come, say, for 3x3x3 only.

I would prefer to keep it simple, but maybe it can be tweaked to make it clear that evasive actions (leaving and coming back) are not okay. I had considered "need" instead of "request". Alternatively, we could have a stern Guideline that clarifies that any kind of evasion is no okay.

**Comment by SAuroux** [comment]
I'm fine with all of this, just wanted to bring up that thought.
Am 19.12.2013 18:44 schrieb "Lucas Garron" notifications@github.com:

**Comment by lgarron** [comment]
Replaced "requested" with "required", which also applies if a competitor is not present at the moment (and therefore can't be "requested" directly), but also has the implication that they're only needed if their skills are relevant, or if they're part of a group of participants whose help is needed to judge/scramble for each other.

**Comment by Claster** [comment]
So now if a competitor needed for judging leaves and comes back, he can be disqualified from the competition, right?

**Comment by lgarron** [comment]
Yeah, at the Delegate's discretion.

I think that's about the best we can make this Regulation given the volunteer nature of running competitions.
