### ISSUE TITLE
Explicitly allow competitors to use hand warmers / drinks bottles

### ISSUE THREAD

**Issue by Mollerz** [thewca/wca-regulations#700]
As discussed in a few recent reports, the WRC has allowed the use of hand warmers during an attempt. Does this also include electronic hand warmers?

Also discussed is that it is quite common for competitors to want to have a drinks bottle with them during longer events, e.g. 5BLD, MBLD, FMC. I think we should be allowing any non-alcoholic beverage to be consumed during an attempt as opposed to just water. Consider a diabetic that might need to drink a sugary beverage to increase blood-sugar level.

Both of these should append to A5b most likely.

**Comment by lgarron** [comment]
I think this is pretty reasonable.

> As discussed in a few recent reports, the WRC has allowed the use of hand warmers during an attempt. Does this also include electronic hand warmers?

I don't think we have full consensus on that yet, but now's a good time to discuss.
I don't see a problem with electric hand warmers before the attempt begins, but I think we should keep heavy restrictions on electronic interaction during an attempt. So, I'd vote for only non-electric hand warmers during an event.

Drink labels shouldn't be used to cheat (e.g. have algs encoded on them), but I can't think of anything clever. I think it's fine to just allow a moderate amount of food and drink, at the discretion of the Delegate.  (There are situations where the Delegate would need to be restrictive, e.g. if the venue strictly disallows foods or beverages.)

Would you be interested in drafting a change for this?

**Comment by lgarron** [comment]
Alright, I think this is fairly solved for now.

Discretion of the Delegate can handle misc. edge cases.
