### ISSUE TITLE
4b4 and 4b4+ clarifications regarding MultiBLD

### ISSUE THREAD

**Issue by c-goodyear** [thewca/wca-regulations#703]
The wording of [4b4)](https://www.worldcubeassociation.org/regulations/#4b4) and [4b4+](https://www.worldcubeassociation.org/regulations/guidelines.html#4b4+) could be improved/loosened, when MultiBLD is considered. If organizers want early puzzle submission, for example using [Z1](https://www.worldcubeassociation.org/regulations/#Z1) so that they can get a head start on a large amount of 3x3x3 cubes that need to be scrambled, they would be restricted by 4b4.

4b4 states that a scramble sequence can only be applied within the time frame, but 4b4 and 4b4+ don't account for the fact that the first time the scramble is attempted doesn't have to be near the start of the time frame.

Currently scramblers can't already start scrambling the puzzles and leave them locked in a secure location if they will be there for more than 2 hours.
Since all participants could be made to start at (roughly) the same time, only scramblers would be a source of issue. Delegates should know who is trustworthy/capable of such scrambling such attempts to avoid .
Everyone would get the same scrambles, which is preferable in BLD events, especially in MultiBLD where there can be great ranking variance due to the points system.

**Comment by lgarron** [comment]
Since 4b4 is a *should*, I don't see this as particularly important to address. However I'd be happy to review a PR for this!

**Comment by c-goodyear** [comment]
Thanks for getting back Lucas, it was pointed out that it's a _should_ from goosly. I'll try and think of a way to phrase a clarification as per the email thread regarding Denmmark & Friends 2019 MultiBLD feedback.

**Comment by c-goodyear** [comment]
"Delegates may apply scramble sequences prior to the start of the time frame. The time frame then begins when a competitor sees the scramble or scramble sequence."

I think that this should suffice, possibly as 4b4++?
