### ISSUE TITLE
FMC signatures

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#707]
From @Ivan-Brigidano:

> Become mandatary to have three signatures: the competitor's one, the judge's (usually a WCA Delegate) and the solution checker's one.

Reply by @xsrvmy: 

> I think this might cause scheduling issues and also forces the competitor to stay longer at the venue after the attempt

**Comment by lgarron** [comment]
@Ivan-Brigidano: Do you have a particular problem you're trying to solve with this idea? What do the signatures certify? (See Regulations A7b and A7c for what normal score sheet signatures certify, and A2d1 in the draft for what the scramble signature signifies.))

The main issue we have is competitors forgetting to write their name (even though it's required), and I don't quite see this helping with that. However, it seems like it would introduce significant overhead.

**Comment by theoleinad** [comment]
I don't see any further regulation or clarification requried with current ruling. 
Is there something specific to address with this issue? @lgarron ?? 

Maybe we could close this issue.

**Comment by Ivan-Brigidano** [comment]
I initially made this proposal thinking that it would be easy for someone to steal an FMC sheet.
But after competing several times in FMC, I think that my old proposal is unnecessary and could cause delays in competitions.
