### ISSUE TITLE
Should we keep the Guidelines?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#71]
The Guidelines were very useful in helping us sift through which Regulations were important. I haven't heard too many complaints, but maybe that's because noone bothers looking at the Guidelines (there are no links from the Regulations to the Guidelines).

We have a few options:
- Keep the Guidelines separate as is.
- Keep the Regulations + Guidelines but merge them into a single document.
  - Guidelines could still keep the "+" designations.
- Get rid of the Guidelines, and move everything important back into the Regulations. Maybe put the rest of the stuff into an FAQ (which would be an appropriate place to answer common questions like "what cube am I allowed to use?").

I don't know which is best, and I don't even know what we should be optimizing for. (Easy to read through? Easy to look up information? Easy for organizers/delegates? As simple as possible?)
We should probably make a thread for this.

---

[Email to  Delegates list, December 08, 2013](https://groups.google.com/forum/#!topic/wca-delegates/U6xZvrA8ZqI)

**Comment by lgarron** [comment]
[Email to delegates, December 07, 2013](https://groups.google.com/forum/#!topic/wca-delegates/U6xZvrA8ZqI):

> I'd like Delegate feedback on the Guidelines. We've had almost a full year with the official documents split up as Regulations/Guidelines.
> It's helped us separate things into things I think of as "normative rules" vs. "official FAQ".
> 
> I'd like to know, as delegates/organizers:
> - Have you found the Regulations/Guidelines separation useful?
> - Have you had issues with the Regulations/Guidelines separation?
> - Would you change anything?
> 
> No one has really complained, but having two documents can be confusing at times. Sometimes I find that competitors don't have an opinion about the separation because they don't know about the Guidelines (!).
> 
> I see a few possible options:
> - Keep the Regulations or Guidelines as is.
> - Combine the Regulations into one document, but keep the distinction between Regulations and Guidelines. (Essentially, using the "+". We could hide the Guidelines when we need a more concise document.)
> - Remove the Guidelines and combine them back with the Regulations _like before_. That is, keep anything important, and throw away anything that's not actually important. We could create another document, like a less official FAQ or guide.
> 
> I would prefer to keep the Guidelines as they are, because:
> - They have has been useful, and not really caused problems.
> - Changing things would take time, and I don't think anyone cares enough to put in the effort.
> 
> I expect no one will have strong opinions. But if you have had any concerns building up, I'd love to hear them now.
> 
> »Lucas Garron

**Comment by lgarron** [comment]
I want to add the Guidelines after the Regulations on the same page this year. The Guidelines have been marginally helpful, but the maintenance of two documents hasn't really worked out.

Splitting up the Regulations into smaller chunks and guides is a separate issue.

**Comment by maconard** [comment]
I think "additions" in the guidelines should be regularly merged into the regulations and removed from the guidelines.

All others should have a smooth way of overlaying with the Web regulations, such as a "hover over to see clarifications and examples from the guidelines" or similar.

**Comment by Samuel-Baird** [comment]
> I think "additions" in the guidelines should be regularly merged into the regulations and removed from the guidelines.
> 
> All others should have a smooth way of overlaying with the Web regulations, such as a "hover over to see clarifications and examples from the guidelines" or similar.

I agree that additions should be merged into the regulations. I’m still not entirely sure why they have their own places in the guidelines :P

**Comment by maconard** [comment]
I feel similarly, but it does make sense to put them in the guidelines for a sort of "testing" phase of the addition. It's structurally easier to remove an addition from the guidelines than to make a change to the regulations (which people read more frequently and numbering/lettering changes are significant).

**Comment by dancing-jules** [comment]
@maconard - I agree, there should be an easy way to navigate from a guideline to its regulation and back.

**Comment by Samuel-Baird** [comment]
maybe a dropdown box could be at the end of each reg and when clicked it will show guidelines? for example

1h) Competitors in the same round of an event may compete as a single group or be divided into multiple groups [+]

when the [+] is clicked 1h+ and 1h++ could drop down beneath 1h in a slightly smaller text, [+] is replaced by [-] which when clicked hides 1h+ and 1h++

Also maybe at the top of the regs there can be an "expand all" button for those people who want to ctrl + f to search for something specific

**Comment by hanwu85** [comment]
One problem we will face with the drop down option is the printed version.
We need to find a way to optimized it.
(Maybe a printed version can just show them all)

Basically, it will be a Regulations overhaul.  😆
