### ISSUE TITLE
Define a center piece

### ISSUE THREAD

**Issue by sam596** [thewca/wca-regulations#710]
> 3l1) The logo must be placed on a center piece.

I don't think it's clear on 5x5 and 7x7 if a center piece means any of the pieces in the step we commonly refer to as 'centers' or whether it is solely the very middle piece.

There was a very brief discussion on slack about it. Up until now, I've always considered that for 6x6 it can be on any of the centers, whereas for 5x5 and 7x7 it has to be the middle. This doesn't seem to be clear though so could we clarify this?

**Comment by dancing-jules** [comment]
Interesting, just recently saw a 5x5 with a logo on an X-centre and the competitor got told to remove it.

**Comment by lgarron** [comment]
I think this would be worth clarifying.

Given that we have been edging towards "anything goes", I think we should stick with allowing any center piece. How about adding this?

> 3l1+) On NxNxN puzzles, a center piece is any piece with a single colored part. For example, the 5x5x5 Cube has 9 center pieces on each face.

**Comment by xsrvmy** [comment]
Actually a printed logo can be swapped off if it on an x or t center for 5bl, where as a dead center logo will need to be removed fron the piece, so this is actually beneficial to blders.

**Comment by sam596** [comment]
@xsrvmy I don't see your point? Logos are completely banned in blind events?

**Comment by xsrvmy** [comment]
@sam596 I meant that it would be easier for blders to obtain a proper replacement piece that do not have a logo if the manufacturer fails to provide one

**Comment by sam596** [comment]
@xsrvmy Ah right, I totally see what you mean.

@lgarron I like the sound of that :)

**Comment by dancing-jules** [comment]
I think the fact that there are 4 X-centres per colour actually speaks against allowing logos on X-centres. The logo being on the middle centre means that it's in the one place where it gives least tactile information about the state of the cube.

**Comment by lgarron** [comment]
> The logo being on the middle centre means that it's in the one place where it gives least tactile information about the state of the cube.

While I think this is a good principle in theory, I've found that such rules end up being too much purism in practice.

@Claster, @viroulep: Do either of you have concerns about logos on X-centers?

**Comment by hanwu85** [comment]
Since the guideline regarding logo on center pieces has been updated, I will close this issue.
See [Guideline 3l1+)](https://www.worldcubeassociation.org/regulations/guidelines.html#3l1+l)(May 2019 ver.)
