### ISSUE TITLE
When does 2i apply exactly? And other comment

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#713]
Regulation 2i is rather unclear about when it applies. If we consider current conventions a reasonable time range would be from the start of the attempt to the end of the solve.

2i also uses the generic word 'use', and that can antually cause some disputes. For example, one could technically argue wearinga bluetooth headphone without turning it on is not considered using the headphone. I think wee need a wording that is clearer but not so strict that carrying an electronic device in a pocket becomes a DNF.

Finally I think electronic watches (but not smart watches) as well as electronic hand warmers (this has been previously mentioned) should be exceptions to 2i. Should FMC stopwatches also be listed as an explicit exception to 2i?

**Comment by lgarron** [comment]
> If we consider current conventions a reasonable time range would be from the start of the attempt to the end of the solve.

I think that time range makes sense, and it would make sense to specify that. I think the Delegates need some flexibility, but the Regs already give them reasonable authority for that.

> 2i also uses the generic word 'use', and that can antually cause some disputes. For example, one could technically argue wearinga bluetooth headphone without turning it on is not considered using the headphone. I think wee need a wording that is clearer but not so strict that carrying an electronic device in a pocket becomes a DNF.

I'm happy to consider suggestions!

> Finally I think electronic watches (but not smart watches) as well as electronic hand warmers (this has been previously mentioned) should be exceptions to 2i.

https://github.com/thewca/wca-regulations/commit/c66106e266e5b580218f4273f7db4dddd5a55b8d

**Comment by xsrvmy** [comment]
That commit only references stopwatches. I am talking about electronic watches because they were quite popular in school when I was in China. However we do need to be slightly careful because
1. Many electronic watches beep on the hour, which can be distracting to nearby competitors (especially during BLD)
2. A competitor can set an alarm which might given them an advantage (and is extremely distracting).

**Comment by xsrvmy** [comment]
Seems like time to bump this after recent events. Is there actually any reason to disallow electronics before signing? I don't see any, and doing so would also create inconsistencies if a competitor uses a phone to film.

**Comment by xsrvmy** [comment]
Bumping this. This incident https://www.worldcubeassociation.org/incidents/36 really highlights the need for a more exact definition for speedsolving and FMC. The camera timeframe makes sense for speedsolving but not FMC.
IMO the sensible with restriction for FMC is that the competitor is no longer allowed to write on the submitted paper after using electronics, since then there is no way of cheating with the electronic device. Not allowing electronics during the 60 minutes makes sense, but we need to make sure there is an exception for early submissions.
(BTW I'm not arguing the solve should be reinstated, but "it's a clear violation of regulation 2i" isn't really a good argument given the vagueness of 2i)
