### ISSUE TITLE
Modifying puzzle orientations

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#715]
I may be biased because I almost exclusively use cubes that have black instead of white, but with our current regulations, the chosen scrambling orientation is very non-intuitive. Intuitively, one would think that because black replaces white that the orientation of these cubes is black on top with green in front. For any scrambler that doesn't know the regulations, this is the only reasonable guess to the scrambling orientation of the puzzle if all you know is white top/green front. When I travel to new locations to compete, even seasoned competitors are unsure of what to do with my puzzle -- I've noticed several times when reviewing my own solve videos that I have been given scrambles with inconsistent orientations due to the scrambler's lack of awareness of the current regulations. On puzzles like Megaminx, this is even more confusing, as the lightest color is very subjective when more colors are added, and the orientation that is chosen can depend on the scrambler, even if the scramblers are familiar with the regulations. 

I'd like to propose a change to 4d that aligns with these intuitions about black being a replacement color for white to allow for the regulations to be applied more consistently.

4d) Scrambling orientation:
4d1) NxNxN puzzles and Megaminx are scrambled starting with the white face on the top and the green face on the front.
4d1a) If there is no white face, a black face is used instead if available.
4d1b) If there is no white or black face, the lightest face is used instead.
4d1c) If there is no green face adjacent to the top face, the darkest face is used instead.
4d2) Pyraminx is scrambled starting with the yellow face on the bottom and the green face on the front.
4d2a) If there is no yellow face, the lightest face is used instead.
4d2b) If there is no green face, the darkest face is used instead.
4d3) Square-1 is scrambled starting with the darker color on front (out of the 2 possible scrambling orientations).
4d4) Clock is scrambled starting with either side in front and 12 o'clock pointing up.
4d5) Skewb is scrambled starting with the white face on top and the green face on the front-left.
4d5a) If there is no white face, a black face is used instead.
4d5b) If there is no white or black face, the lightest face is used instead.
4d5c) If there is no green face adjacent to the top face, the darkest face is used instead.

I am indifferent about applying these regulations to pyraminx for yellow/black being identical, but did so above to make the regulation structure consistent. I don't think there are any unintended consequences of a change like this, but let me know if I am not considering something.

**Comment by xsrvmy** [comment]
Is there a reason white is not considered second before black on pyra?
Also, I think I remember suggesting that green should explicitly refer to the darkest adjacent green color

**Comment by KitClement** [comment]
Fair point, I've edited my original post. Would be easy to add additional subregs to address the very strange corner case of multiple green sides as well.

**Comment by lgarron** [comment]
I am not really in favor of this, since it complicates the Regulations. We have multiple issues with incomplete scrambler/judge education, and I don't like adding a complicated patch that doesn't really address this.

In the medium term, I think I'd like to see reference sheets at competitions clarifying scramble orientations for scramblers.

**Comment by xsrvmy** [comment]
@lgarron I think actually allowing black on top would make checking whether or not a scramble is correct easier

**Comment by theoleinad** [comment]
Usually in 3x3 the only color that change is yellow/white for black.
So my suggestion is:
> Scramble should be applied using green front / white on top
> If there's no white, then the scramble is applied where at least 3 faces match following criteria and priority:
1. Front : Green
2. Up : White
3. Down : Yellow
4. Right : Red
5. Back : Blue
6. Left : Orange

Note: 
Discuss about priority and colors is open.

**Comment by dancing-jules** [comment]
@theoleinad - "at least 3 faces match the following criteria"? Shouldn't it be two? Because you only need 2 faces for orientation. And that sounds even more confusing that everything else I heard.

**Comment by theoleinad** [comment]
@dancing-jules 
Ok then make it at least 2 following above criteria.
1,2
1,3
1,4
1,5
1,6
2,3
2,4
2,5
2,6
3,4
3,5
3,6
4,5
4,6
5,6
Hope this is cleaerer than before :) 
Or I need to think on a better approach...
