### ISSUE TITLE
Re-add surface to C1b

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#718]
There has been some debate as to whether table abuse is allowed due to the wording of C1b. I believe part of the reason is that when we changed 'touch'to 'operate', the argument that 'the table must touch the cube a millisecond after the timer starts' no longer holds. 

I would suggest readding the surface to C1b and remove C1b+++

**Comment by lgarron** [comment]
C1b+++) covers this, but a small fix update to C1b itself might be good!
