### ISSUE TITLE
Clarify that certain camera displays are allowed

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#721]
This camera (from the Franconia Spring 2019 report) displays mode, time, and battery:

![IMG_20190331_122758](https://user-images.githubusercontent.com/248078/55550907-5735d000-568e-11e9-8e0a-f57fa4260743.jpg)

In practice, several camera include blinking lights or elapsed time indicators. While these *could* be used to communicate information, the risk of cheating/advantage from this pretty low. I think the best approach would be to:

1) add a Guideline clarifying that a limited display of common information is acceptable (i.e. does not count as a "monitor" for 2i2a or "interacting" for 2i2b), and
2) have a page of examples, once we have example pages (see #168, which I want to prioritize soon).

**Comment by xsrvmy** [comment]
One thing to be careful with: the guideline must specify that this does not apply to other devices (eg. phones or smartwatches) which might be used as a camera

**Comment by Mollerz** [comment]
Maybe the clarification needs to be that if a screen is in sight then it cannot display a live (reasonably live) feed. This means screens that are off, LEDs, battery indicators, etc. are fine.

**Comment by xsrvmy** [comment]
@Mollerz is time considered a live field?

**Comment by Mollerz** [comment]
> @Mollerz is time considered a live field?

By "live feed" I mean a copy of what is actually happening in real life in some regard. So a time or timer is not a live feed.
