### ISSUE TITLE
Change Date for New Regulations

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#722]
`<version>Version: January 01, 2018`
`<version>Version: May 01, 2019`
Line 3 in both regulations and guidelines.

Sorry if this is not the correct place to leave a comment about this, I wasn't able to find a better way.

**Comment by xsrvmy** [comment]
hmm... May 01 2019 is in the future

**Comment by lgarron** [comment]
Indeed, we'll need to do this when we merge `draft` to `official`.

**Comment by oyyq99999** [comment]
and also the last revision date.
