### ISSUE TITLE
Some typos in release-candidate-2019-04-04(0b4dee9)

### ISSUE THREAD

**Issue by oyyq99999** [thewca/wca-regulations#723]
1. Reference to E2c1 in E2a1 should have parentheses
2. in A3c3++ `(See Regulation A6))` should be changed to `(See Regulation A6)`
3. There should be a blank line below Article 12 title in source of guidelines.

**Comment by lgarron** [comment]
Thanks for noticing! Could you send a PR against the `draft` branch for this? :-D
