### ISSUE TITLE
Rename "opaque object" for BLD to "sight blocker"

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#724]
"Sight blocker" seems to be the most common modern term for it.

**Comment by Samuel-Baird** [comment]
The term “sight blocker” may not be as clear to someone reading the regs as an opaque object. If the term sight blocker was to be defined in the regulations as an opaque object to be used for obstructing the competitors line of view between them and the cube during the execution phase then I think it would be good :)

**Comment by dancing-jules** [comment]
I agree with renaming it. A fork is an "opaque object", but it's terrible as a sight blocker.

**Comment by Samuel-Baird** [comment]
How’s this? Define the sight blocker as an opaque object which prevents the competitor from seeing the puzzle (so no one uses forks :P)

B4c) The judge must ensure that there is an sight blocker object between the competitor's face and the puzzle while the competitor is solving. The sight blocker is opaque and must fully block the competitors view of the puzzle.

**Comment by lgarron** [comment]
I will gladly approve and merge a pull request to change B4c and B4c1!

(If not, we'll get around to it with the 2020 Regs.)
