### ISSUE TITLE
Document Regulations release steps

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#725]
I'll collect steps in this comment for now.

- Amend per the Motions
- Announce:
  - website (e.g. https://www.worldcubeassociation.org/posts/wca-regulations-may-2019)
  - staff
  - WCT
  - `organizations@`
- Followup:
  - Ask WCAT to check future competition formats comply with new Regs
- Update branches
  - Update main date, remove textual revision date (e.g. 962213a30fbd1157f61fbf49a319c13245262144)
  - Merge `draft` into `official` (this should just be a fast-forward if we've been keeping `draft` up to date with `official`).
  - Create a tag (e.g. [`official-2019-05-01`](https://github.com/thewca/wca-regulations/releases/tag/official-2019-05-01))
- Deploy website: https://github.com/thewca/worldcubeassociation.org/wiki/Merging-and-deploying#how-to-merge-and-deploy-a-pr
  - Note: The website automatically pulls the latest Regs from the `wca-regulations` repo, so there's usually no need to update the main website codebase.
- Post announcement (e.g. https://www.worldcubeassociation.org/posts/wca-regulations-may-2019-now-in-effect)

## Misc/TODO

- Try to get translations?
- Update history

# References

Past WRC posts on the WCA website: https://www.worldcubeassociation.org/posts?tag=wrc

**Comment by mirandapedro** [comment]
I've started a [page](https://github.com/thewca/wca-regulations/wiki/The-Process-of-Ammending-the-Regulations) on our wiki meant to document and detail the process of ammending the regulations.

**Comment by lgarron** [comment]
> I've started a [page](https://github.com/thewca/wca-regulations/wiki/The-Process-of-Ammending-the-Regulations) on our wiki meant to document and detail the process of ammending the regulations.

Thanks, that looks like a great start!
