### ISSUE TITLE
New FMC regulation concerns

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#727]
`E2c) At 60 minutes, each competitor must submit to the judge a single piece of paper with a written solution and information to identify the attempt.
E2c1+++) [EXPLANATION] The competitor is not required to submit a paper with the competition name, round, and/or attempt number, but may wish to do so in order to help the organization team keep track of submitted solutions.
`

These two regulation/guidelines are a contradiction to one another. Not only that, but this is encouraging cheating as a competitor who DNFs may now not turn in a solution in hopes to be awarded a DNS instead. This only increases the inaccuracy of our results and can become more of a burden on organizers. 

A solution that I use at comeptitions is to take attendance before he attempt to guarantee that we always award the correct DNF/DNS result for the competitors. This simply isn’t possible at competitions like Euros or US Nationals, where a competitor can easily sneak out and nobody ever realize that they complete the attempt.

`E2c1++) [ADDITION] If the competitor forgot to write information to identify the attempt on their intended solution paper before the time limit, they are permitted to add it in front of a judge. In this case, the competitor must ask the judge while submitting their solution and then immediately write information to identify the attempt (and make no other changes) under direct supervision of the judge. Once a competitor has finished submitting their solution (e.g. placing it in the judge's hands and allowing the judge to move on to the next competitor, placing it on the judge's table and walking away), they are not permitted to add any information. If the competitor writes anything after the time limit but before asking the judge, the attempt remains disqualified (DNF).`

The wording of this is very dependent on the comma and can be easily mistaken as “If the competitor forgot to write information to identify the attempt on their intended solution paper, before the time limit they are permitted to add it in front of a judge.” Which drastically changes the meaning. If we remove “before the time limit” the regulation maintains its original meaning and doesn’t cause any possible misinterpretations.

**Comment by xsrvmy** [comment]
What would even be the penalty for not handing in then? Also with your same argument, by removing that reg you require that competitors tell someone that they are choosing not to do the attempt, but sometimes the attempt might be the first thing in the morning, or the person is late after lunch, and would get DNF when it should be DNS. It's going to be inaccurate either way. Does the difference between DNF and DNS actually matter?

**Comment by Jambrose777** [comment]
> What would even be the penalty for not handing in then? Also with your same argument, by removing that reg you require that competitors tell someone that they are choosing not to do the attempt, but sometimes the attempt might be the first thing in the morning, or the person is late after lunch, and would get DNF when it should be DNS. It's going to be inaccurate either way. Does the difference between DNF and DNS actually matter?

Yes the difference is VERY important in regards to result accuracy. A DNF means that you competed in the attempt and a DNS means you did not. This is very different.

I don't see your point. Where does it say you have to tell someone that you aren't competing? This is implied by not showing up. The guideline says quite the opposite by allowing competitors to skip out on turning something in, which makes it extremely difficult to track who actually competed.

**Comment by xsrvmy** [comment]
I meant that in either case you still have to figure out who showed up and who did not if someone failed to write their name/id.

**Comment by Jambrose777** [comment]
> I meant that in either case you still have to figure out who showed up and who did not if someone failed to write their name/id.

Correct, but without the new guideline, you can force the competitor to turn in something with their name on it in order to ensure you can account for their DNF. If the guideline is there, the regulations encourage not turning something in and can cause more DNSes to be awarded.

**Comment by xsrvmy** [comment]
OK I see your point.

Just another point, should the judge be allowed to ask the competitor to write his name? (ie. competitor hands in solution and judge immediately ask him to write name/write name for him) The only issue here is sometimes solutions are just piled up so this would vary accross comps.

**Comment by UnderwaterCuber** [comment]
“Not only that, but this is encouraging cheating as a competitor who DNFs may now not turn in a solution in hopes to be awarded a DNS instead.”

I don’t really see that as cheating seeing how they gain no advantage? There isn’t really any incentive to do that either. 

Ithe results should reflect what happened so it definitely needs to be DNF is they participate in the attempt instead of a DNS

**Comment by lgarron** [comment]
Apologies, I forgot to comment on this. If I understand correctly, I think you're misreading E2c1++?

It doesn't state that the competitor can avoid submitting a piece of paper, just that the paper doesn't need to include information that is not required by E2c. We could rephrase to "The competitor is not required write the competition name, round, and/or attempt number on their submitted paper, but..."

I'll send a PR with wording improvements.

**Comment by dancing-jules** [comment]
I agree with @lgarron,

E2c says that you have to submit some paper with some information that says who you are and what this paper is about. 

E2c1+++ says that this information does not need to follow a certain format. You don't need to write everything down, because comp, round and attempt are clear anyway (you can't submit an attempt that finished an hour ago, you can't submit an attempt that happened at a different competition).
