### ISSUE TITLE
We cannot use speed stacks timer reliably anymore

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#728]
Yesterday at Utah April Surprise 2019 we used a new batch of 14 gen 4 timers ordered recently speed stacks, this was there first use in competition. All of those 14 timers ended up failing to function properly and one timer we previously had started having issues as well. Luckily we had enough timers to run the competition without any problems but if this was a competition in a developing area that didn’t had much equipment the results could have been catastrophic. This wasn’t just a “bad batch” locally and in other places I have seen many instances of speed stacks timers failing to function in a way that make them usable for conception. Aside from making running the competitions very difficult this is expensive, if we continue having issues like this then competitor fees will always have to be higher to afford new timers. We have used speed stacks since they have been reliable in the past but as of late their quality control has gotten worse and worse (100% of timers in a batch of 14 being faulty) with issues like timers skipping seconds, not functioning when used with a display, not displaying the time correctly, not starting, not stopping and other such problems I think it’s time that we start looking towards other alternative timers which are functional and reliable.

**Comment by lgarron** [comment]
I don't have anything to add here at the moment, but I want to acknowledge here that we know this is a problem that needs to be fixed.
For now, there is WCA-internal discussion about this.

Relevant links:
- https://youtu.be/y9xzhs0XpWY

**Comment by Samuel-Baird** [comment]
It appears as though using stock batteries or low batteries also causes a large amount of the problems. Also speedstacks is aware of the issues and is working on solutions.

For now just change out batteries when you can and unplug displays if timers start acting odd :P

**Comment by lgarron** [comment]
I don't think our concerns about Speed Stacks have been successfully addressed yet. :-(

**Comment by Samuel-Baird** [comment]
There aren’t any viable alternatives at the moment so I’m going to close this for now

**Comment by Jambrose777** [comment]
Wow, @UnderwaterCuber Please stop closing important issues that you've started. @lgarron can this be reopened?

**Comment by lgarron** [comment]
Indeed, this is still a problem, so I'd like to keep this open.
