### ISSUE TITLE
Typo in 2c1

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#73]
Sorry if this has been mentioned/fixed already.

2c1) A competitor is not be eligible to compete without a completed registration, as determined by the organisation team.

**Comment by lgarron** [comment]
Since it's just a typo, feel free to go to the [fixes](https://github.com/cubing/wca-documents/tree/fixes) branch and make this change.

**Comment by sarahstrong314** [comment]
Done,
