### ISSUE TITLE
Twisted corner during scramble, but without evidence: extra or not?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#730]
This happens sometimes:

- A competitor finds a corner twist in a scramble.
- They are confident that they did not have a corner twist.
  - Often, the competitor is experienced and trustworthy. But that should ideally not factor into a decision.
- There is no video evidence or other information about whether the scrambler twisted a corner.

I believe that modern puzzles are actually reducing the chance for this — but there are many more attempts per week now. We can also remind scramblers to check all corners carefully, but that can't 100% address this issue if it still appears (and there are other priorities for making scramblers pay attention).

If there was a corner twist during the attempt, the competitor may repair it.
If there wasn't, the Delegate should give an extra.

I think it's okay to let the Delegate give an extra *if* they are confident that the competitor is correct and is not trying to use this to gain an advantage. But I'd like for us to have an objective standard, and I don't think it's good to take the competitors' word in general.

## Incidents:
- [Lincoln Open 2019](https://groups.google.com/a/worldcubeassociation.org/d/msg/reports/W6KX3GNoTlI/BknfuokBDgAJ
)
- Võru Värk 2019

**Comment by xsrvmy** [comment]
There are two additional complications we need to consider:
What happens if a competitor claims this happens on a BLD scramble, and DNFs by more than just the twisted the corner (and possibly the buffer piece?) (eg. two edges are flipped also)? I think it would not be appropriate to give the extra in that case, but that would need to be codified specifically.
What if this happens during megaminx where scrambles are not usually checked?

**Comment by lgarron** [comment]
> What happens if a competitor claims this happens on a BLD scramble, and DNFs by more than just the twisted the corner (and possibly the buffer piece?) (eg. two edges are flipped also)? I think it would not be appropriate to give the extra in that case, but that would need to be codified specifically.

The WRC has recently converged on this: If a procedural error (by someone other than the competitor) for an attempt is suspected at a competition, the competitor should be given an extra attempt. If evidence supports that the error happened in the original attempt, always take the extra.

I think we should also apply that here.

**Comment by theoleinad** [comment]
@lgarron 
> The WRC has recently converged on this: If a procedural error (by someone other than the competitor) for an attempt is suspected at a competition, the competitor should be given an extra attempt. If evidence supports that the error happened in the original attempt, always take the extra.

So, question, if I end an attempt, and when I'm going to sign, I see that the scrambler checker did not signed, I can argue that the scramble was miss-scramble to get an extra?
Let's say I'm not fast enough so I don't record my solves. 
Should I get the extra or not? (After all, scramble checkers must sign as process states.

**Comment by xsrvmy** [comment]
@theoleinad I think that is an extra regardless given where the direction is going with scramble signatures. A better example would be something like the judge picks up the puzzle before checking misalignment, but you can already tell it's a +2.

**Comment by xsrvmy** [comment]
@lgarron Now I think about it, this is the same as the misscramble incident that lead to the first sub 21 mean, so I would say take the extra. What makes it weird in this case is that the competitor would have failed to solve the correct scramble

**Comment by Samuel-Baird** [comment]
No extra to be given without solid evidence. Competitors could very well cheat using this in order to replace bad scrambles with better ones.

**Comment by theoleinad** [comment]
Missing scrambler signature is a procedural error.
So you can request an extra as soon as you notice there was a signature missing.
No cheating here, since you can get DNF'd if for some reason that scramble was found to be miss-scrambled.
So basically you're covering yourself.
