### ISSUE TITLE
Writing/disseminating valid move info for FMC

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#732]
Originally intended to make this an incident log entry, but the comp didn't end up using it. I think we should add a Guideline:

@kingmathyall requested the following:

> I’d like to write all the moves allowed (Article 12) and examples of moves not allowed (Guideline E2c++) up on the white board during the FMC attempt tomorrow during Mental Breakdown WA 2019. 

Competitors are expected to know the Regulations, and are not allowed to ask for assistance or clarification like this during the attempt. However, TNoodle sheets for Fewest moves already contain some of this information, and it does not give competitors any information that assists them in finding a better solution. Therefore, the WRC agreed that we're comfortable allowing this.

If  competitions use this approach, I'd like this to be noted in the Delegate report. I'd also like to strongly encourage organizers to contact the WRC before their competition if they intend to post/disseminate any information to competitors that is not a direct restatement of excerpts from Article 12.

**Comment by xsrvmy** [comment]
Isn't the competitor allowed to talk to the judge/delegate during the attempt?
