### ISSUE TITLE
Clarify that receiving a blindfold is assistance?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#733]
At [Le Barcarès Mental Breakdown 2019](https://groups.google.com/a/worldcubeassociation.org/d/msg/reports/ELqqF14Jwws/6IHUa5RdAAAJ
), a competitor forgot their blindfold, and someone brought them one. It seems this has sometimes been allowed in the past.

My response:

> I would say that receiving a blindfold is clearly assistance: > https://www.worldcubeassociation.org/regulations/#A5b
The blindfold is the competitor's responsibility, and I don't think we should start trying to allow > some kinds of assistance as "okay".
> (A5b++ allows people to assist you if they accidentally picked up a popped piece, but no one "accidentally" hands you a blindfold, and it's not as complicated to refuse.)
>
> I think it's okay to allow competitors to improvise, or even provide blindfolds at solving stations. > But I don't think it's a good idea to allow interaction outside the solving station.
> 
> So I think this should be DNF.

I think we should make a decision, and make a Guideline out of it.

**Comment by Samuel-Baird** [comment]
I would put it on as an example, not a clarification. 

Also maybe A5b can be improved in its wording to prevent similar issues in the future?

**Comment by dancing-jules** [comment]
Do you mean someone brought them a blindfold DURING the attempt? That was not 100% clear from your description. Before the attempt they can borrow anything, but during the attempt seems weird.

**Comment by xsrvmy** [comment]
What should happen if an audience member (eg. a parent) tries to help the competitor and brings him/her the blindfold? If the competitor must refuse assistance, doesn't that prevent the competitor from completing the attempt? Or does the person have to put the blindfold back where it was before?

**Comment by xsrvmy** [comment]
Also, since the word "improvised" was mentioned above, is the competitor allowed to use something like a jacket covering face as a blindfold if he/she forgets to bring it?

**Comment by Samuel-Baird** [comment]
Competitor should be prepared before the attempt and bring their own blindfold @xsrvmy

**Comment by xsrvmy** [comment]
@UnderwaterCuber A competitor is technically allowed to get his blindfold during the attempt right? If that is the case the action of a spectator should not make that impossible (otherwise it should be an extra attempt).
