### ISSUE TITLE
A6e and B5c clarifications

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#737]
It seems there seems to be some disagreement as to what A6e entails. I have seen several incidents where competitors have had a cube land on their hand after stopping the timer and have seen them receive no penalty or receive a penalty. Just clarifying whether a competitor touching the cube is the same or different than the cube touching the competitor would be great. 

Edit: not B5c, I was really tired when writing this :P

**Comment by xsrvmy** [comment]
The guideline on A6e already makes it look like the puzzle moving towards the competitor does make it a +2. However an extra guideline might help.
I don't see a plausible way of how a competitor would accidentally break B5c in such a manner. The only situation I can think of is if the competitor puts the puzzle on the gen 4 timer and it slides off but the competitor would notice.

**Comment by Samuel-Baird** [comment]
Bump?

**Comment by hanwu85** [comment]
@UnderwaterCuber , sorry a bump does not work in Github, but I think there was a similar discussion about this topic,  I will try to find it.

**Comment by dancing-jules** [comment]
> sorry a bump does not work in Github

it does, if people sort by "most recently updated"

**Comment by hanwu85** [comment]
Ha, thank you for that information.  But you have to manually do the filtering...
I don't know if there's any option do default "show updated first".

**Comment by kotarot** [comment]
@hanwu85 You mean #534 ?

Yeah, #534 opened firstly and it's the mainstream of discussion. We can discuss this topic there and we can close this.

**Comment by kotarot** [comment]
I'm closing this issue. We can keep the discussion in #534 !
