### ISSUE TITLE
Adding a new official role to article 1, scramble checker

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#738]
After the scrambler checks the puzzle they pass it on the the scramble checker who confirms and signs that the puzzle is scrambled correctly. The scramble checker may not apply moves to the puzzle.

1_) Each event must have one or more scramble checkers. Exception: 3x3x3 Fewest Moves.
1_1) The scramble checker receives the scrambled puzzle from the scrambler and must verify that the puzzle is scrambled correctly. If the puzzle state is wrong, the scrambler must correct it (e.g. by solving the puzzle and applying the scramble sequence again). 
1_2) Every competitor must be available for scramble checking. If required to scramble, a competitor may be excused only for a legitimate reason (e.g. being unfamiliar with scramble checking), at the discretion of the WCA Delegate. Penalty: disqualification from the competition (see Regulation 2k).

 Pros

1. Having the scrambler sign takes additional time away from scrambling which as a result slows the comp down. Having a checker do this allows scramblers to be faster. 
2. As a scrambler there is pressure to scramble puzzles to send them out quickly, and to do this they may cut corners (checking scrambles) in their haste. A dedicated scramble checker may help remove some hasty checks.
3. A scrambler can intentionally send out faulty scrambles. By having 2 people, a scrambler and checker, means you now need 2 people colluding to cheat which is less likely than just 1 person cheating.

Cons

1. Need an additional person to staff which can be difficult at smaller competitions 
2. Scramblers may take a few seconds to find the correct orientation of a puzzle before checking (such as in 2x2) which takes additional comp time

**Comment by cubewhiz** [comment]
Are you suggesting requiring that scramble checkers be mandatory (and be different personnel from scramblers)?

**Comment by Samuel-Baird** [comment]
Yep! The scramble checker would be someone who wasn’t scrambling and would be mandatory. I mean if this were to ever become a thing it may be best to recommend scramble checkers at first and then a year later make it required (similar to what is going on with scramble signatures I believe)

**Comment by xsrvmy** [comment]
I think it might be better in practice to let scramblers check each other's scrambles. Some people might take being asked to scramble check as an insult ("Why can't I judge/scramble instead?")
There is also an additional concern: What about missing signatures?

**Comment by Samuel-Baird** [comment]
The problem with having scramblers check each other’s scrambles is they have to both be done for it. If you have scramblers going different speeds or starting at different times you will be wasting scrambling time (ex scrambler 1 takes 10 seconds and scrambler 2 takes 15 seconds, scrambler 1 has to wait 5 seconds for scrambler 2 to finish and then swap cubes to check which adds up especially if they have bigger gaps)

They can deal with that I guess? 

Treated the same way as missing scramble signatures will be treated in 2020

**Comment by xsrvmy** [comment]
Maybe scranblers shouldn't be checking each other by default, but they definitely should be allowed to (so a scramble checker can help scramble)

TBH the lack of dedicated staffing in many comps make me think that this should only be enforced by organizors and not the wca

**Comment by Samuel-Baird** [comment]
It would be allowed due to 1k

Whats wrong with lack of dedicated staff? Also what do you mean by it should be enforced by organizers and not the wca?

**Comment by Samuel-Baird** [comment]
Closing due to little interest

**Comment by lgarron** [comment]
I'd still like us to think about the potential for an official role of scramble checker. We're still seeing significant issues at some competitions with only scrambler signatures.

**Comment by cubewhiz** [comment]
TBH, I expect that we will still see significant issues with scramble checkers, too. The problem is that these are all solutions executed by humans and humans make mistakes.

**Comment by lgarron** [comment]
> TBH, I expect that we will still see significant issues with scramble checkers, too. The problem is that these are all solutions executed by humans and humans make mistakes.

Indeed, this is why I haven't pushed for scramble checkers too much yet.

However, it would be nice to get to the point where we can actually gather statistics to figure out if scramble checkers make a sufficient difference in accuracy to justify the extra person.

**Comment by Samuel-Baird** [comment]
> TBH, I expect that we will still see significant issues with scramble checkers, too. The problem is that these are all solutions executed by humans and humans make mistakes.

Scramble signatures are certainly going to DNF legitimate results more often then fix issues. Hopefully we can minimize issues though and hopefully they will prevent some bigger issues.

**Comment by cubewhiz** [comment]
I'd love for this to be the impactful solution that we've been looking for, but pardon me if I don't hold my breath. I think scramble checking is tedious enough that people will only do it quickly, even if it's their only role.

**Comment by Samuel-Baird** [comment]
> I'd love for this to be the impactful solution that we've been looking for, but pardon me if I don't hold my breath. I think scramble checking is tedious enough that people will only do it quickly, even if it's their only role.

Yeah I definitely see that as a problem, our current problem is people not checking or checking too quickly and that could definitely be the case here. 

Guess scramble signatures are all we have until we can get some robots :P

**Comment by Samuel-Baird** [comment]
#591
