### ISSUE TITLE
Randomize puzzle orientation?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#74]
See #65 and #67.
Also, [delegate discussion, Aug. 13](https://groups.google.com/forum/#!searchin/wca-delegates/orientation/wca-delegates/9xBS_mfGR2o/GX_CeDdThKsJ) and [delegate discussion, July 4, 2012](https://groups.google.com/forum/#!searchin/wca-delegates/orientation/wca-delegates/3BncS7T7cNg/1o8H-7JSONsJ).

**Comment by sarahstrong314** [comment]
Yes, definitely. I assume you're referring to adding some randomly generated rotations at the end of each scramble, and having the scrambler ensure that the puzzles are placed in that orientation in the cover base (if the new cover idea you proposed works out).

**Comment by lgarron** [comment]
Delegate consensus: do this for BLD.
