### ISSUE TITLE
Disqualify individual Multi Blind puzzles if a competitor makes a move.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#740]
Precedent: https://www.worldcubeassociation.org/incidents/26

This also just came up for Please Be Quiet WPI Spring 2019.

**Comment by xsrvmy** [comment]
Should this also be the standard for any other reasons that have a DNF penalty but only the one cube is affected? For example, fixing a corner twist in the incorrect direction, turning  a puzzlebefore the judge inspects it, etc.

**Comment by lgarron** [comment]
I believe that there was an incident at Worlds where a competitor did a move on a cube for Multi-Blind. The individual puzzle was counted as unsolved.

**Comment by Ivan-Brigidano** [comment]
I removed the "2020" label as it isn't included in the draft. However this is a logical and uncontroversial proposal so we should consider it for 2020 or 2021
