### ISSUE TITLE
Expand A7g) to competitors competing since a relevant Regs change?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#742]
- BarbeCubing Spring 2019: A competitor accidentally used a front-facing camera on their second competition since a break from 2013.

**Comment by Jambrose777** [comment]
I would consider this covered by A7g already.

**Comment by xsrvmy** [comment]
I think there is ambiguity in the phrase 'new competitor', but most people would think of first timers.
To add to this discussion, some other similar scenarios would be first time competing in bld, feet, or first time competing in a non-fmc event.

**Comment by hanwu85** [comment]
In the [motion 7.2017.1](https://www.worldcubeassociation.org/documents/motions/07.2017.1%20-%20Registered%20Speedcubers.pdf), there's a definition of a Passive Speedcuber, which is someone who has not competed for 24 months.  Can we use it as line to tell whom  the A7g can apply to?  I know this is still not clear but at least it's a start.    Or what @xsrvmy said, first competed in some specific events.
