### ISSUE TITLE
Specify standards for when A7g is appropriate?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#743]
e.g. "first two competitions, or first time competing after N years of break"

**Comment by Goosly** [comment]
Amount of competitions doesn't seem like a good reference to me.

Someone who competes in 15 events at one competition is more experienced than someone who competes in 3x3 only at 5 competitions.

**Comment by SAuroux** [comment]
How about clearly stating that A7g can only be applied to someone's first ever WCA competition? I understand that it is nice to be lenient at times, but after attending a WCA competition we can probably expect someone to have a rough idea of what the WCA is and that there is such a thing as _WCA Regulations_. After all, we have [2t)](https://www.worldcubeassociation.org/regulations/#2t) for a reason, don't we?

**Comment by Jambrose777** [comment]
But that is harsher on competitors returning after a couple of years and being clueless. It also is hard on the cases where a competitor is inexperienced in an event (say first time doing blindfolded).

I’d prefer to keep this regulation up to delegate discretion, as ultimately they are he ones who can evaluate the competitor and situation and take an appropriate course of action.

**Comment by SAuroux** [comment]
Well, in **my** view there is only one good reason to apply A7g, which is for situations where competitors cannot be expected to fulfil 2t. And I only see this given for people who have never attended a WCA competition before, not really know what the WCA is, not really know that such a thing as WCA regulations exists. Of course it is harsher in the cases you describe, but I just disagree that A7g should be applied to those and it makes things way more consistent.

**Comment by xsrvmy** [comment]
@SAuroux Bld is not actually likely to cause an issue, since if the competitor asks the judge to lift the cover, the judge can explain.
There is a problem, however, with competitor who have ONLY done fmc officially since the competitor has never used a stackmat before.

**Comment by Baiqiang** [comment]
I agree with @SAuroux . It's the competitor's responsibility to know and abide the regulations.
