### ISSUE TITLE
Specify how the waiting list works after registration is closed

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#744]
I think it's common to accept competitors from the waitlist after a registration period has closed, as long as the competitor's registration was complete before that period ended. However, there's some discussion about this on the Cervantes Cubea 2019 Delegate report, so I think we should clarify this in the official documents.

Note: At this point, it should *probably* go into https://github.com/thewca/wca-documents but I'm filing the issue in `wca-regulations` first because this was subject to the Regulations until recently and the WRC was specifically consulted about this. (We can easily move the issue later).

**Comment by Ivan-Brigidano** [comment]
This is now covered by the WCRP.
