### ISSUE TITLE
[Suggestion] Remove Article 6 from the Guidelines

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/wca-regulations#746]
It seems odd that Prizes and Awards are covered in the regulations/guidelines. Longer term, should this become a seperate policy managed by WQAC? 

I think it fits more into a "making competitions good" rather than a "rules and regulations" setting. This would also give us opportunities to flesh out details and define expectations for awards ceremonies.

This may be better placed in wca-documents, but I'll leave it here for now.

**Comment by cubewhiz** [comment]
As they are all just recommendations (and nothing in there is mandatory), I think the content belongs more fittingly in a guide for organizers or something similar. I agree they don't belong in the Regulations (but I don't think they need to be specified in a policy, either).
