### ISSUE TITLE
Rankings in case of disqualification from event

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#748]
For example, if a competitor is disqualifed from an event for time wasting on last solve, what happens to the ranking of the average? 2j2 states that previous solves from the average remain valid, so an average is still possible. Specifically, can the delegate prevent the competitor from getting a podium? And if there is a next round, is the competitor illegible for the round and thus does not count towards the qualification cutoff, or does he simply get DNFed as in 2j1?

**Comment by SAuroux** [comment]
I would actually say that your questions can be clearly answered with the regulations. 2j1 says that _If a competitor is disqualified from an event for any reason, they are not eligible for any more attempts in the event._ - not less and not more. 2j2 says that (except for cheating) _If a competitor is disqualified during the course of an event, their earlier results remain valid._ As for everyone else, the competitor's ranking will be determined by their valid results. If those make him podium, so be it. However, 2j1 clearly says _event_, not _round_. Therefore, such a competitor cannot proceed to further rounds.

An interesting question, however, is how this would affect other people proceeding. For example, 12 people proceed to the final rand the competitor ranked 7th was disqualified. I would say that only 11 people shall compete in the final then, as the conditions to apply 9p3 are not fulfilled.

PS: I don't like the scenario much, as a delegate should rather use A2c in this case to DNF the attempt only. But there are certainly other cases where this could happen, just imagine _Wow, I just got a counting 1.6, the 4th scramble had a two move face with easy EG!_

**Comment by xsrvmy** [comment]
Yeah I was going to mention that case next. This looks like a wording problem, because "qualifying" in 9p3 is supposed to refer to making the top n cutoff. With the current regs we have a different problem: the disqualified competitor can optionally withdraw from the next round to let the n+1th competitor enter the round, and this choice can result in unsporting behaviour.
I partially wanted to mention this since if your example happens in 2x2 finals, the penalty would be literally none as completed attempts cannot be disqualified.
