### ISSUE TITLE
Clarify A6e and A6e+ to include pieces

### ISSUE THREAD

**Issue by Epride** [thewca/wca-regulations#751]
Taking from incident 1 of Anaheim Qualifier 2019 it is probably best to clarify if an individual piece of the puzzle landing on the competitors lap or being touched by the competitor should also attract the +2 second penalty.

**Comment by xsrvmy** [comment]
Should we actually discuss whether or not A6e should actually be applied to detached pieces?
As I take it, the intention of A6e is to prevent the competitor from changing the state of the puzzle after timer is stopped. A detached piece cannot affect the state of the puzzle, so why should this even be a +2?
Also it seems like double jeopardy to say that a detached piece that does not cause a DNF is still considered part of the puzzle.

**Comment by Samuel-Baird** [comment]
Definitely agree with Max.

 In addition to what he said it would also be possible to get +4 penalties from touching the puzzle (one from the puzzle and one from the loose piece) which is a worse penalty than just touching the puzzle normally, it doesn’t really make sense why it should be worse.
