### ISSUE TITLE
Make changing Citizenship stricter

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#752]
After discussion with WRT, WRC, and WDC:
https://www.worldcubeassociation.org/regulations/#2e2

Should be updated so that:
- By default, allows a competitor to change at a certain rate/a certain number of times/to a citizenship they haven't represented before, "no questions asked".
- Allows discretion by some WCA-association entity for cases that don't fit this.

It was mentioned the WRT should be that entity taking feedback from the appropriate delegate(s) of the competitor/country.

**Comment by Mollerz** [comment]
A number of associations only allow changing of citizenship at some arbitrary number of years. I don't think that blocking switching back to a previous citizenship is a good idea in the slightest. Geopolitics is serious business. And in some cases people's nationalities change based on current borders with warring countries.

However I am in favour of something like "If you switch citizenship within the WCA, you are barred from switching citizenship again for 3 years from the date the citizenship changed." 3 year is a long time.

**Comment by Jambrose777** [comment]
Your concerns are covered by the second bullet. That would be a case that we would accept a change back to a citizenship.

**Comment by Mollerz** [comment]
I kind of feel like the whole first point is pointless though. It's _extremely_ rare that a person ever goes through more than 2 citizenships in their lifetime. When someone does want to change more than once it will almost always be A to B to A. I'd be more in favour of adding this arbitrary time limit than to add a block.

**Comment by xsrvmy** [comment]
I do think the first comp in the year rule needs revisiting. There are definitely some ambiguity relating to what losing a citizenship entails, especially for cases like switching from China to Canada. Technically China says you lose your citizenship the moment you switch, but they never know if you have switched, and Canada lets you keep your Chinese passport. So how does the WCA deal with cases like this?

**Comment by Jambrose777** [comment]
Losing a nationality results in a change regardless of how many competitions They’ve attended this year.

**Comment by Mollerz** [comment]
It is very common for a number of countries that if they apply to be a citizen of another country then they just lose their original citizenship and the passport becomes voided.

**Comment by xsrvmy** [comment]
But does the WCA need to enforce this, or thus the competitor have to declare it?
More generally I'm just asking what happens if there is a dispute on what country a competitor represents because different countries have different rules? (eg. apparantly there has been cases where a kid is born to Chinese parents in Canada and China refuses to recognize the Canadian citizenship)

**Comment by Mollerz** [comment]
> More generally I'm just asking what happens if there is a dispute on what country a competitor represents because different countries have different rules? (eg. apparantly there has been cases where a kid is born to Chinese parents in Canada and China refuses to recognize the Canadian citizenship)

This happens all the time there are loads of countries with tons of different rules. https://en.wikipedia.org/wiki/Multiple_citizenship

It comes down to the fact that the WCA isn't a government and cannot make decisions based on country law in regards to citizenship. What we can do is ask competitors what country they would like to represent with some valid proof and within reason. So in your case above, what citizenship is actually represented by said child is a pretty big mess. But at the end of the day if they come to a competition with a Chinese passport and a Canadian passport, they can choose which they would like to represent.

I would personally change the regulation to something as follows:
2e2) Competitors with updates to their citizenship status may change their country of representation. This must be declared during registration for a competition, the change occurs on the first day of their next attended competition.
2e2+) CLARIFICATION: The competitor must provide some proof that they are eligible to represent their new citizenship at the competition. The WCA Delegate should verify citizenship by means of documents (e.g. a passport).
2e2a) Competitors must wait 3 years from the date of their last citizenship change to be eligible to change their citizenship back to a country they have previously represented.

**Comment by xsrvmy** [comment]
I was asking mainly actually because currently representing the wrong country id a disqualification.

There still should be an exception for losing the citizenship you represent in the WCA? I hope people don't give up citizenships just to force a WCA cotizenship switch

**Comment by Mollerz** [comment]
> I was asking mainly actually because currently representing the wrong country id a disqualification.
> 
> There still should be an exception for losing the citizenship you represent in the WCA? I hope people don't give up citizenships just to force a WCA cotizenship switch

Possibly this should then be changed as well. This is _incredibly_ difficult to enforce or even keep track of since we don't request ID for every registrant for every competition.

If people want to give up a citizenship purely so they can change it in the WCA then that is their prerogative.

**Comment by dancing-jules** [comment]
I think we should differentiate (if we don't already) between people who hold citizenship of multiple countries and people loose one citizenship while they gain another. 

If it's the latter, they should absolutely be allowed to switch their WCA-countryid immediately.

If it's the former, I like the idea of the 3-year-rule to prevent excessive back-and-forth-switching for the sake of national records.

**Comment by xsrvmy** [comment]
Related to this issue, we should also address what happens to national rankings if a competitor switches citizenship, but switches back a few years later. Do the old national rankings count?

**Comment by Jambrose777** [comment]
I dont see why not. Even if the comeptitor changes nationalities, their rankings for their original are still kept: https://www.worldcubeassociation.org/results/events.php?eventId=333&regionId=Belize&years=&show=100%2BPersons&single=Single

**Comment by Mollerz** [comment]
> Related to this issue, we should also address what happens to national rankings if a competitor switches citizenship, but switches back a few years later. Do the old national rankings count?

Any result obtained at a competition will stay as a result for that nation even if they switch later. So yes it would still count.



> I think we should differentiate (if we don't already) between people who hold citizenship of multiple countries and people loose one citizenship while they gain another.
> 
> If it's the latter, they should absolutely be allowed to switch their WCA-countryid immediately.
> 
> If it's the former, I like the idea of the 3-year-rule to prevent excessive back-and-forth-switching for the sake of national records.

I don't think your first point is necessary. Governments barely do this, huge sports organisations don't do this. I think it's unnecessary. Of course if someone loses the nationality they compete with then at their next competition they should be able to change their country. However we would need some kind of proof to override the 3-year rule if it applies.

**Comment by dancing-jules** [comment]
> However we would need some kind of proof to override the 3-year rule if it applies.

I'd say email a delegate with a copy of the relevant documents?

**Comment by Mollerz** [comment]
> > However we would need some kind of proof to override the 3-year rule if it applies.
> 
> I'd say email a delegate with a copy of the relevant documents?

Sure, or bring it to the next competition.

**Comment by Ivan-Brigidano** [comment]
@Jambrose777 do you have a concrete proposal to handle this?
In my opinion nationalities shouldn't be covered by Regulations but by a Motion.

**Comment by alexmaasswca** [comment]
Has anyone ever changed WCA citizenship twice? I don't really think this is an issue.

I think its stupid to require competitors to update their citizenship if they lose citizenship from a country, because how would this be enforced at all? Would the delegate/WCA force people to handover/provide personal information if they are suspected of losing citizenship?

**Comment by dancing-jules** [comment]
> Has anyone ever changed WCA citizenship twice?

Yes, 2015YAKH01, Daniel Yakhkind went from Ukraine to Israel and back again.

**Comment by alexmaasswca** [comment]
> > Has anyone ever changed WCA citizenship twice?
> 
> Yes, 2015YAKH01, Daniel Yakhkind went from Ukraine to Israel and back again.

so basically one person out of many? lol still not an issue then

**Comment by Jambrose777** [comment]
@alexmaasswca if a competitor is found to compete under a citizenship which they do not hold (with ill intent) their results can be removed/disqualified. Yes they should report citizenship loses to ensure that they compete exactly with a nationality that they hold.

Anyways, preventing back and forth switching of nationalities I feel is important or else our organization is subject to abuse from this.

**Comment by alexmaasswca** [comment]
@Jambrose777 
it is only ill intent? so if you're lets say some young cuber who lost citizenship, and doesn't think to report it to WCA, they won't  get a bunch of their solves removed?

I don't think nationality/citizenship affects the validity of their solves, they should be ranked in the world assuming the cuber has no history of cheating or anything.

Anyways, I guess it should be up to the discretion of the results committee they are abusing the system by switching nationalities very often.

**Comment by alexmaasswca** [comment]
I still think this is a non issue, because of how few people switch nationalities, and how there has only been one case of someone switching nationalities twice.

**Comment by EdHollingdale** [comment]
I think the ill intent is a much smaller problem than some are making it out to be. I think the arbitrary point about calendar years is far more of an annoyance. People may be living in a country as an immigrant and finally get citizenship of that country, but depending on the views of their new country may retain dual citizenship with their old one. I see absolutely no reason why we should deny people the opportunity to represent their new country until the following calendar year when that new country is frequently the one they live in and may feel most aligned to. 

Taking inspiration from @Mollerz I make the following suggestion:
2e2) Competitors may change their country of representation. 
2e2+) CLARIFICATION: The competitor must provide some proof that they are eligible to represent their new country (e.g. citizenship certificate, passport).
2e2a) Competitors must wait 3 years from the date of their last citizenship change to be eligible to change their citizenship back to a country they have previously represented. Exception: if the competitor loses citizenship of the country which they were previously representing, they must change the country of representation before or at their next competition (see Regulation 2c2).

I think this has a few benefits:
- No longer has phrase "updates to" which means a change doesn't need to be triggered by a change in a competitor's circumstances (although I don't think it was ever interpreted this way)
- Adds the exception for people who lose their old citizenship to the 3 year rule
- No longer places the impetus on the Delegate to do things at a competition
- Keeps the 3 year restriction, but removes the silly first competition of a calendar year limitation

It would be great to see this update in time for 2020.

**Comment by Jambrose777** [comment]
> * Keeps the 3 year restriction, but removes the silly first competition of a calendar year limitation

What’s sillier? Having to wait till next year to update a dual nationality citizenship, or being able to be the national champion of 2 different countries in the same year?

I understand that this scenario is still possible given a nationality loss, but I don’t think that every 3 years someone with dual nationity should be able to qualify for titles in 2 different national/contenential championships.

**Comment by EdHollingdale** [comment]
> What’s sillier? Having to wait till next year to update a dual nationality citizenship, or being able to be the national champion of 2 different countries in the same year?

Without a doubt the former. As you say, it is possible anyway with nationality loss, and please show me one examples of a person actually abusing it to get more national titles.

Meanwhile I have had two people in my region already flag with me that they are undertaking the long process of gaining Australian citizenship (after being residents in Australia for many years). You're telling me that when they are eventually successful (multi-year application process) I can't let them change their country to the country they live in and feel most aligned to for another 10 months because Jacob Ambrose is paranoid that they will try to become the national champion of two countries in the same year? Being a WCA Delegate already means I have to have a lot of tough conversations and disappoint people, please don't add two more to my list by having more unnecessary, stupid bureaucracy and red tape.

**Comment by Ivan-Brigidano** [comment]
As I said I think the Citizenship policy should be moved into a WCA Document rather of Regulations.

But, why should we limited the amount of times a person changes of citizenship? Imagine the case where someone actually changes his citizenships more times than the limit legally. Then, if we didn't allow him to change his citizenship on the WCA Database, we wouldn't be comply with [Regulation 2e](https://www.worldcubeassociation.org/regulations/#2e).

**Comment by Mollerz** [comment]
If someone wants to citizenship switch every 3 years so once every 6 years they can become to national champion of two countries, then by all means. It's really common in sports for people with multiple nationalities to choose which team they play for as a result of heritages and dual nationality.

Consider all of the people that have changed nationality within the database already, that number is extremely small. It seems so silly to create regulations around <0.01% of people.
