### ISSUE TITLE
Make A5a more Delegate-friendly

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-regulations#756]
A5a reads:
> While inspecting or solving the puzzle, the competitor must not communicate with anyone other than the judge or the WCA Delegate. Penalty: disqualification of the attempt (DNF).

As a Delegate, I sometimes find this a bit problematic. As the standard proceedure for article A doesn't apply to article E this is not an issue during Fewest Moves, however, it still is for the other events (mostly the longer events like Multi-Blind). I would prefer there to be added a guideline stating that if the competitor is the Delegate of the competition that they may resolve an incident (verbally) whilst their attempt is ongoing. 
My suggestion would be:
> A5a+ ADDITION If the Delegate is currently inspecting or solving they may communicate with anyone to resolve any incidents.

**Comment by Goosly** [comment]
Instead of handling incidents during your solves, is it not easier to either handle the incident after your solve, or if for some reason you really need to handle it asap, give an extra to yourself?

**Comment by EdHollingdale** [comment]
@Goosly I agree that it should always be preferable to either wait until the end of the delegate's attempt or the delegate should grant themselves an extra. But there could be instances where the delegate is happy to take the very minor inconvenience of the minor disruption and not grant themselves an extra. 

For example, the delegate is 10 minutes into memorisation of 5x5x5 Blindfolded when another judge accidentally stops the stopwatch on a different competitor. This issue can be resolved very quickly by the WCA Delegate, albeit by sacrificing ~15 seconds of their solve time to give relevant instructions to a scrambler. This ultimately saves time (don't have to wait another 20 minutes for the Delegate to finish their attempt) and the Delegate may prefer it (e.g. if they have a memorisation technique that would make it a challenge to attempt an extra).

**Comment by lgarron** [comment]
I think it's fair to say Fewest Moves is special — we hold custom FMC competitions where (often) everyone in the room is competing, and I think it would be okay to add something to explicitly allow communication.

I don't think we should allow/encourage Delegates to resolve issues during other attempts.

**Comment by DanielEgdal** [comment]
Let me explain a bit further on why I would like this added.
Basically, Ed covered it pretty well but I'll put my own words on it as well.

If a Delegate is doing a 7x7 solve or 5BF that may take a long time to finish and if the issue is easily resolveable, I think it should be allowed for the Delegate to give a quick direction of which action should be taken. For example, if the computer for scrambles went out and is requiring a password whilst the Delegate is 10 minutes into a 5BF attempt that is likely going to last a total of 40 minutes that would result in a very bad situation. Technically right now, the Delegate could just tell their judge and then the judge tells the other person which is a loophole, but that is a solution which could be taken now.

Regardless of the outcome of this, guidelines should be added for this (both for FM and non FM). I have seen Delegates speaking to other competitors whilst solving several times in the past and making it clear whether this is allowed or not will resolve those issues.
