### ISSUE TITLE
Assistance from spectators

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#76]
How do we prevent punishing competitors who popped from getting assistance on purpose, without disqualifying them when it happens by accident?

See [delegate discussion, August 15](https://groups.google.com/forum/#!topic/wca-delegates/7AupirrdwDY).

**Comment by lgarron** [comment]
I don't have any great idea. Marking as `2014-wontfix`, although anyone is free to take this on.

**Comment by lgarron** [comment]
[Vantaa Open 2014](https://groups.google.com/forum/#!msg/wca-delegates/RInv_JMJXCo/2JXn85sz_0IJ):

> Square-1 the puzzle popping, spectator touch the piece before we told him not to do that, so I gave an extra solve.

At most competitions I've been to, everyone yells at the spectator not to touch the piece. If they touch it and put it back down, it's usually interpreted as no assistance.

Giving an extra solve is definitely inconsistent with past rulings, and unfair (just pop and have someone "accidentally" assist you). We need an clear policy on what the competitor should do if an audience member has given them various degrees of assistance.
They should not be punished much more than the pop already cost them, but they must not get any unreasonable advantage due to assistance.

**Comment by Laura-O** [comment]
Similar incident:

[Prime One Chihuahua report:](https://groups.google.com/d/msg/wca-delegates/bCe8c_SZ_Pc/26iKVGgWAwAJ)

> We had a confusion with an extra attempt. A person help a competitor with a pop (he give back the piece) and I gave an extra attempt, but the judge did not write the extra attempt in the 6th space in the scorecard and this confused the scramblers and I wanted to give the second extra solve.

In addition to the discussions before we should also consider that an extra attempt can be a disadvantage for the competitor. Fixing a small pop in big cube events does not necessarily result in a bad result.

**Comment by lgarron** [comment]
I'm closing this in favor of https://github.com/thewca/wca-regulations/issues/624

The more recent view is that we shouldn't DNF a solve just because a spectator tried to help; we just need to figure out where to draw the line.
