### ISSUE TITLE
Guideline for rejecting attempts because of low cumulative time remaining.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#761]
Suppose a competition has 3-attempt round with cumulative time limit of 30 minutes for 4BLD, and a competitor gets 12:30 and 14:00 for the first two. Then they have 3:30 remaining. In most situations fairly unlikely that they could get a success in the remaining time. A Delegate *could* try to invoke [A1c](https://www.worldcubeassociation.org/regulations/#A1c), but if the situation is less clear-cut they need to ask the competitor whether they want to DNS in order to avoid "wasting" competition resources.

I think that it would be reasonable to have a Guideline that the Delegate may (but not must) decide that a competitor is not eligible for more attempts if, say, the remaining cumulative time is less than half of the competitor's best official successful result to date.

We'd need to figure out how to handle competitors who have not had any successes representative of their skill, or had some slow solves but claim to be capable of much better results at home. But if we write this correctly, we could set better expectations.

**Comment by maconard** [comment]
I'm not sure how I feel about this. Personal anecdote:

I got a 12:30 4BLD dnf followed by an 11:50 success. I had about 9.5 minutes remaining (I also used about 45 minutes of my cumulative limit for 5BLD attempts). 9.5 minutes is doable by me if I don't do extra reviews (PB at home is right around there), but the delegate and other competitors didn't really want me to do the solve because of time. Yet if I'd gone for it and pulled it out, it could have been really great. Sometimes pressure motivates people to do well.

Your example with 3 minutes left is different of course, as there's no way to improve that drastically on a final attempt. But even if they do the attempt, it took less than 30 seconds to scramble and they got stopped 3 minutes in. They technically didn't waste resources since they were allotted x minutes to do their attempts, and they simply used all of what they were granted. 

I think it's the competitor's responsibility to determine if there is a realm of possibility for them to have enough time or not. The delegate can of course give advice. In a drastic case like the 3 minute case, I'd say it's okay for the delegate to veto if needed. But if the competitor can make a case that they have a shot, I don't think they should be stopped by the regulations.

**Comment by theoleinad** [comment]
I don't like this approach. 
The solve should be Success, DNF or DNS by competitor's decision only, that's the reason the cummulative time limit exists. 

Giving "power" to a delegate to stop competitor's attempt will lead to even worse incidents. 
A proper schedule + cutoffs is enough to prevent delays in competitions.

**Comment by Goosly** [comment]
As a delegate, I believe A1c is sufficient for the original example of 3:30 left and adding more Guidelines with all corner cases will only complicate things more.

**Comment by lgarron** [comment]
> I got a 12:30 4BLD dnf followed by an 11:50 success. I had about 9.5 minutes remaining (I also used about 45 minutes of my cumulative limit for 5BLD attempts). 9.5 minutes is doable by me if I don't do extra reviews (PB at home is right around there), but the delegate and other competitors didn't really want me to do the solve because of time. Yet if I'd gone for it and pulled it out, it could have been really great. Sometimes pressure motivates people to do well.

For what it's worth, I had in mind that this cutoff would work both ways.

If we apply the "half of your best result so far" rule of thumb, half of 11:50 would be 5:50. Since you have significantly more than 5:50 of the time limit remaining, a Delegate wouldn't be allowed to reject (or pressure you to rescind) a request for a third attempt.

**Comment by lgarron** [comment]
> As a delegate, I believe A1c is sufficient for the original example of 3:30 left and adding more Guidelines with all corner cases will only complicate things more.

The tradeoff is that different Delegates will draw the boundary at different places. What if your best result so far is 12:00 and you have 6:00 remaining? 8:00? 10:00?

You could argue that the Delegate needs some flexibility here based on the pace of the competition. But right now, A1c) is a rough hammer that was not designed for this.

The alternative to adding Guidelines for more corner cases is that competitors can receive very different treatment, which they also don't tend to like.

**Comment by Goosly** [comment]
> But right now, A1c) is a rough hammer that was not designed for this.

If A1c was not designed for cumulative limits, isn't it easier to add that for cumulative limits, competitors are always allowed to start the attempt (if they want)? That's _extremely_ easy to apply consistently.

Currently I just ask the competitor what their PB at home is and discuss whether they think they can finish their solve in the remaining time or not. Whether or not we're ahead of schedule is entirely irrelevant for this, when making/checking the schedule I already assume there will be competitors using the entire time limit.

**Comment by xsrvmy** [comment]
@Goosly Fastest attempt is probably more important for this.
Also it is entirely possible that someone gets a time significantly faster than their fastest attempt at home at slower speeds. My third 5bld attempt took just over half the time of my second 5bld attempt, and my 4bld PR is still my fastest ever attempt by more than 10%.

**Comment by lgarron** [comment]
> If A1c was not designed for cumulative limits, isn't it easier to add that for cumulative limits, competitors are always allowed to start the attempt (if they want)? That's _extremely_ easy to apply consistently.

With this line, we'd be saying that there should be no problem granting a competitor a third attempt with 1 second of cumulative time left. I don't think Delegates would like it if there was no way for them to reject that.

> Also it is entirely possible that someone gets a time significantly faster than their fastest attempt at home at slower speeds. My third 5bld attempt took just over half the time of my second 5bld attempt, and my 4bld PR is still my fastest ever attempt by more than 10%.

Indeed, this consideration is part of the tradeoff.

**Comment by Goosly** [comment]
> With this line, we'd be saying that there should be no problem granting a competitor a third attempt with 1 second of cumulative time left. I don't think Delegates would like it if there was no way for them to reject that.

As a delegate I like regulations that are easy to understand and apply.

This attempt would, including scrambling, take less than one minute, which is **a lot faster** than looking up the competitor's best result in competition, calculating how long ago it was done, searching for the relevant Guideline of the 27 corner cases you're going to introduce, and then finally decide whether or not he's allowed to do the attempt or not.

**Comment by BrandonMikel** [comment]
> With this line, we'd be saying that there should be no problem granting a competitor a third attempt with 1 second of cumulative time left. I don't think Delegates would like it if there was no way for them to reject that.

I don't see an issue with granting an attempt with 1 second of cumulative time left. One second later, you DNF them and move on. It's not much time wasted. I don't think we need to set arbitrary rules about whether we should grant more attempts based on amount of time left. If there is more than 0 seconds left, grant them the solve. Once they hit the time limit, DNF the solve and stop the rest of their attempts.

**Comment by maconard** [comment]
I'm with Brandon on that. If a competitor wants to make the org team scramble a cube so they can do a one second attempt, that's their prerogative since that time was granted to them. They should be aware that doing so will make some people frustrated with them, and I'd imagine most if not all competitors wouldn't behave this way.

**Comment by xsrvmy** [comment]
Slightly off topic, but if the delegate rejects an attempt, is it a DNF, a DNS or no result?

**Comment by Goosly** [comment]
> Slightly off topic, but if the delegate rejects an attempt, is it a DNF, a DNS or no result?

If you are referring to [A1c](https://www.worldcubeassociation.org/regulations/#A1c), the penalty is written there crystal clear.
If you are not referring to A1c, well, then I don't know what you're referring to.

**Comment by xsrvmy** [comment]
@Goosly 
If A1c is applied for low cumutalive time limit remaining, and the competitor's attempts are rejected, they would all be DNF. This looks worse on a competitor's result page than one DNF for using up the cumulative time limit, then DNS/no result for not starting the rest of the attempt.

**Comment by SAuroux** [comment]
Delegates usually ask competitors to voluntarily decline remaining attempts with no realistic chance for success, which would then be a DNS. If a competitor refuses to decline the attemts, it will be DNF no matter if the attempt is started of if A1c is used.

**Comment by Goosly** [comment]
@xsrvmy Yes that is all correct. I'm not sure what your point is exactly.

**Comment by xsrvmy** [comment]
@Goosly I was merely pointing out that a delegate should not be allowed to use A1c to DNF an attempt when a competitor wishes to DNS the attempt.
Specifically A1c invocation cannot be automatic if say 1 second is left.

**Comment by Ivan-Brigidano** [comment]
As @SAuroux said, Delegates usually ask competitors to voluntarily to decline attempt in this cases. And on uncertain cases I agree with @Goosly that this might cause more troubles than solutions.
