### ISSUE TITLE
3bld format proposal

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#764]
There has been quite some talk about ao5 for 3bld recently because one lucky solve can get you a really good mean. I am proposingthe following format:
- Competitor does 5 solves
- Rank by the SECOND best single of the round (best counting solve)
- Average ranking becomes ao5
- Use best solve as tie breaker, or if not enough people get two successes
- bo3 cutoff is allowed (the typical bo2 cutoff unfairly increases accuracy requirement)

Pros:
- More solves
- Average is less luck based
- Accuracy requirement only increases slightly
- Less like that less than 8 people make second round of a three round comp due to DNFs, since one success is enough for ranking purposes
Cons:
- Takes longer, can be solved with cutoff and cumulative
- Unconventional ranking criteria and cutofd
- The ranking statistic would not be directly visible on the wca website as of right now. However this is also the case with MBLD right now.

**Comment by mintydev789** [comment]
So this is how winners are determined, right? The single rankings would still just include individual attempts, I presume. Also, I don't see how "average is luck based" is a pro. It's certain that 3bld should have 5 attempts, but I'm not sure if this is the solution (although it's a solution that I have thought of myself at some point).

**Comment by xsrvmy** [comment]
Oops missed a word. Average is less luck based.

**Comment by aneurinhunt** [comment]
Changing 3BLD to 5 attempts requires a format unique to the event. I think best of 5 is a best format if 3bld were to go to 5 attempts but then you are just giving more solves. Otherwise you have to have a unique complicated format.

**Comment by Jambrose777** [comment]
I’d agree for simplicity over special (very over  convoluted) formats.

Plus, rankings based off second best single are still  susceptible to whatever time the solve gets on the second best scramble, which doesn’t really solve there issue.

**Comment by xsrvmy** [comment]
@Jambrose777 the problem was WR means are based too much on luck, where as for in comp rankings finals usually have the same scramble, so this isn't typically a problem.
