### ISSUE TITLE
Extra/out-of-order attempts and cutoffs

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#765]
This is a bit of a weird one. Let's suppose the following happens:
In 4x4, the cutoff is 1min, and the competitor gets the following times:
1:05, 55, 58, ...
At some point after the third attempt, an extra is given for the second attempt (eg. for an incorrect scramble). The competitor gets a 1:04. Does the competitor
- miss the cutoff because the 1:04 replaces the 55 as the second attempt, or
- make the cutoff because 1:05 and 58 are the first two valid attempts in chronological order?

Similar scenario:
The competitor gets 1:05, 55, then reports a duplicate scramble for solve 3. The scramblers discover that attempt 2 was done with scramble 3, and give out scramble 2. The competitor gets a 1:05. Does the competitor make the cutoff?

Scenarios like this might happen with cumulative time limits as well.

**Comment by Jambrose777** [comment]
Both scenarios the competitor is not considered to make the cutoff.

**Comment by xsrvmy** [comment]
So does this mean a competitor can technically get an average without making cutoff in this manner? (2j2)

**Comment by Jambrose777** [comment]
No, if the competitor does not make the cutoff, they only get the number of solves before the cutoff (bo2, bo1)

**Comment by CarterKoala** [comment]
The other solves (3-5) just act as if they never happened.

This happened to a competitor a while ago. They got something like 1:0x, 32, 1:14 in Square-1 because the 32 was on the third scramble. Result was the bo2: 1:0x, 1:14.

**Comment by Goosly** [comment]
Is this an issue or a question? 🙂

**Comment by xsrvmy** [comment]
I was more commenting on the fact that the regs aren't very clear on the outcomes, especially for the second one. Is there even a regulation stating that scrambles must be given in the correct order?
