### ISSUE TITLE
WRC Projects (Mid-2019)

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#767]
Here's a rough list of what I want to tackle with new WRC members in 2019:

# [Simplifications](https://github.com/orgs/thewca/projects/4#column-6349209)
Changes that reduce what a competitor/judge/Delegate needs to know without significantly impacting the nature of the sport.

- "Solved or Not"
  - No +2 for misalignment
  - Disallow missing/misplaced pieces in the solved state
- Clock Pins
  - Allow distinguishable clock pins.
  - Simplify pins in scramble / ignore pins
- Reduce valid FMC moves to 18 basic moves.

# Scramble Accountability

- Accuracy:
  - (A2d1) Scramble signatures
  - Scramble checkers?
- Secrecy
  - (4b2a) Only the competition's designated Delegates may handle scrambles
  - (4b2++) Visually isolated scramble tables

# References/Guides/Tutorials

- FMC grading ("A printable sheet on how to judge FMC (full list of allowed moves, how to count moves, examples of allowed and disallowed notation).")
- Scrambling
  - Orientation
  - Notation
  - Multi-Blind
- Judging
  - Inspection
  - End of Attempt
  - Misalignments
  - BLD
- Hardware
  - Examples of common acceptable and unacceptable puzzles.
  - Currently known Bluetooth puzzles and how to spot/check them. (Possibly private to Delegates.)
- Advancement conditions

# Fresh Events

Ideas:

- Tiers
- Ephemeral Events
- Encourage Unofficial Events
  - As an alternative to temporary official events/rounds?

# Hardware

- Cube Covers
- O-Rings (or equivalent) at every competition
- Bluetooth Cubes

# Processes

- Ongoing
  - Manage the process of incoming emails.
  - Manage the process of making decisions.
  - Manage the process of following up decisions with documentation changes.
  - Manage the process of updating Delegates on important decisions.
  - Manage feedback from the community.
- Backlog
  - Read all 2019 Delegate reports
  - Add backlog of incidents to Incidents log
  - [`wca-regulations` issues](https://github.com/thewca/wca-regulations/issues)

# Code of Conduct

- Look at other examples and help draft

# Education/Outreach/Inclusion

- Allow/encourage competitions to reserve a certain fraction of spots for new competitors.
- How to update the Regulations competitions more welcome to newcomers.

**Comment by maconard** [comment]
"Solved or not": I would just like to reiterate that I think this is against the spirit of competitions. Whether the penalty is +2 or DNF, there will still be similar difficulty in determining if it's solved or not (at least near the decision window), unless you're suggesting that even a 1 degree misalignment be DNFed. Then, there will just be countless more DNFs, causing fast competitors to get knocked out of earlier rounds and reducing new competitors' satisfaction and desire to compete officially more. Similarly for pops as regulated currently, where the competitor clearly demonstrated their ability to solve the puzzle and it is clearly solved.

I support most everything else on this road map. Thanks for bringing it all together, Lucas!

**Comment by lgarron** [comment]
I'm locking this issue because I don't want to each of the relevant discussions to take place in their proper home. Please comment in individual issues!
