### ISSUE TITLE
Guideline 9b+ is out of date

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#768]
9b+ may be out of date now that ao5 events can no longer be held in other formats. The recommendation still stands for mo3 since FMC can be bo1/2.
However if the guideline is recommending that second rounds do not have a cutoff, then it should probably more explicit.

**Comment by dancing-jules** [comment]
Agree. 

The thing about cutoff is interesting, since there have been quite a few rounds with a combined second round (round type "e" in the export).
