### ISSUE TITLE
Has a competitor competed in a round if all results are DNS, for the purposes of 9m?

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#769]
The regs are not very clear. There are different reasons for DNSes as well, such as no-show, simply giving up, marking an attempt before it starts, waiting for more than a minute, declining an extra on an invalid attempt. A no-show and declining an extra should definitely result in a different answer, so this may need to be addressed in detail.

**Comment by Mollerz** [comment]
I recall a situation where a new competitor was filming with a front facing camera which was discovered on the second solve. We mentioned the regulation to the competitor and said as they were new we would be able to just restart the average with no problems. Unfortunately the competitor suffers with bad anxiety and was a bit flustered with the situation and decided to decline the extras, which resulted in 5xDNS results. They were not included in the results for the competition.

**Comment by lgarron** [comment]
I think it's okay to say that a result of all DNSes for a round means that you did not officially participate in that round. After all, you did not start a counting attempt.

**Comment by mirandapedro** [comment]
It's general consesus between Delegates and WCA Staff in general that an all DNS average should not count as a valid average.

So, for the purpose of 9m, a competitor has not competed in a round if he has an all DNS average.
