### ISSUE TITLE
Regulation E3b

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#77]
"1-3 puzzles corresponding to the event (self-supplied)."

We only do FM with the 3x3, so that could be replaced by

"1-3 Rubik's Cubes (self-supplied)."
or "3x3x3 cubes" (which I prefer)

**Comment by lgarron** [comment]
Our official name for the puzzle is "Rubik's Cube".

This change has been suggested before. Considering that FMC is likely to stay 3x3x3 only for a long while, I agree that the generality is probably worth it.
