### ISSUE TITLE
History page hyperlink to version 2018-01-01 leads to current version

### ISSUE THREAD

**Issue by Ranzha** [thewca/wca-regulations#771]
Easy fix probably?
https://www.worldcubeassociation.org/regulations/history/

**Comment by xsrvmy** [comment]
This duplicates thewca/worldcubeassociation.org#4323

**Comment by hanwu85** [comment]
After fixing the 2018 history link, we forgot to add the 2019-05-01 link to the page.
@Ivan-Brigidano , would you like to take this task again?
If you have no time, I can take this one.

**Comment by Ivan-Brigidano** [comment]
Do you mean a link [here](https://www.worldcubeassociation.org/regulations/history/) or inside the 2018 version?

**Comment by lgarron** [comment]
> After fixing the 2018 history link, we forgot to add the 2019-05-01 link to the page.

FYI, we usually don't include the current version on the history page.

**Comment by hanwu85** [comment]
If we don't include the current version on this page, how do the regular users know what have been changed for the 2019 version?
