### ISSUE TITLE
Armenia should be listed as Europe not Asia

### ISSUE THREAD

**Issue by Mollerz** [thewca/wca-regulations#772]
https://github.com/thewca/worldcubeassociation.org/issues/4390
https://github.com/thewca/worldcubeassociation.org/pull/2907

for ref

**Comment by AlbertoPdRF** [comment]
Are there any more changes that we should do? I'm asking because of [this discussion](https://worldcubeassociation.slack.com/archives/C0GHDBJFK/p1564482334010500). If there are, it would be better to do them all at once!

**Comment by Mollerz** [comment]
Nope, I checked - I'm pretty sure this is the only one. The only controversial one would be moving Israel to Asia as well... But for political reasons we decided not to in the past.
