### ISSUE TITLE
Consistent use of punctuation in wca-states.md?

### ISSUE THREAD

**Issue by jfly** [thewca/wca-regulations#774]
While working on https://github.com/thewca/worldcubeassociation.org/issues/4389, I noticed that we use both [unicode apostrophe](https://www.fileformat.info/info/unicode/char/27/index.htm) and [unicode RIGHT SINGLE QUOTATION MARK](https://www.fileformat.info/info/unicode/char/2019/index.htm), and I'm not sure it's intentional.

- `Côte d'Ivoire` has a regular APOSTROPHE in it
- `Democratic People’s Republic of Korea` has a RIGHT SINGLE QUOTATION MARK in it.

I feel like the RIGHT SINGLE QUOTATION MARK in `Democratic People’s Republic of Korea` should actually be a APOSTROPHE.

From https://github.com/thewca/wca-regulations/blob/draft/wca-states.md:

![image](https://user-images.githubusercontent.com/277474/62430471-c9b4cc00-b6d1-11e9-9973-43d01d646203.png)

**Comment by Mollerz** [comment]
Yes APOSTROPHE is the way forward! :)

**Comment by Ivan-Brigidano** [comment]
Thanks for notify it!
