### ISSUE TITLE
Scoresheet results that do not make sense

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#776]
A7c+ covers "incomplete or unreadable" results, but it does not cover results that do not make sense. It should probably be expanded to cover those cases, and give examples.
For instance:
- Times over 10 minutes when time limit is less than 10 minutes
- Solved > Attempted in MBLD (26/25)
- Calculation errors
  - 26.35 + 6 = 34.35 (incorrect addition)
  - 26.35 + 8 = 34.39 (incorrectly copied decimals)
  - on Chinese scoresheets, 26.35 (2) (3) (5) = 34.35 (miscount)
  - Does the policy change if the final result is incorrectly recorded as DNF (eg. 9:53.00 + 6 = 10:01.00 DNF)

**Comment by Burnsy101** [comment]
From experience:
Ask the judge / delegate what happened if it is seen to be unreadable.
If that is unable to happen, then always assume worst time - similar to how a time of just 46 will be rounded up to 46.99
if solved is > attempted then assume it is n/n or just ask the competitor / judge
If time is over time limit then dnf

**Comment by Burnsy101** [comment]
this seems like a rare case by case basis thing

**Comment by dancing-jules** [comment]
> if solved is > attempted then assume it is n/n

Huh, I'd assume that 3/2 is more likely a typo of 2/3 than 2/2. 

> this seems like a rare case by case basis thing.

I'd agree. There are too many ways people can write nonsense to list every single one of them.
