### ISSUE TITLE
Wording: 'this' is unclear

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#777]
There are several wording/grammatical issues in the regs where the word 'this' is used in an unclear way or refers to a plural object:
- 2i1) Competitors may use non-electronic aids that do not give an unfair advantage, at the discretion of the WCA Delegate. *This* includes: ... ("this" refers to non-electronic aids)
- 3h2) Puzzles whose colored plastic is visible inside the puzzle (e.g. "stickerless" puzzles) are permitted. *This* does not include the following puzzles: ... ("this" refers to puzzles)
- A2b1) For Square-1, the organization team may enforce placing a thin object in the puzzle to prevent accidental moves from being applied before the start of the attempt. If these objects are used, *this* must be announced before the round starts. (what does "this" refer to?)
- C1b3) If other body parts of the competitor come in contact with the puzzle or parts of the puzzle without the competitor's intention and without applying moves, *this* is not considered operating the puzzle, at the discretion of the judge.

I would suggest the following rewordings:
- Non-electronic aids include: ...
- are permitted, except 3h2a) puzzles with transparent parts
- If these objects are used, an announcement must be made before the round starts.
- Replace with "the competitor is not considered to be operating the puzzle".

There are also a couple of these issues in the guidelines.

**Comment by Burnsy101** [comment]
3h2: this does not include puzzles that have transparent parts.
2i1: these include
A2b1: change this to it
C1b3 I agree with you

I agree with you in that it should be changed as dodgy grammar could prove a bit of a roadblock to someone without the regulations in their mother tongue with not that confident english
