### ISSUE TITLE
Clarify fixing an illegal puzzle

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#779]
This was mentioned in another discussion. The wording of 3k1 technically requires the competitor to submit a different puzzle, but fixing the puzzle is often allowed and is also more reasonable (usually by removing a logo or replacing a piece/cap).

**Comment by maconard** [comment]
I think I was the one who pointed that out; I also support a wording fix on this.

**Comment by Burnsy101** [comment]
yes - we should add the clause 'or fix the defect so the puzzle is competition legal'
