### ISSUE TITLE
Specify how long physical records must/should be kept.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#78]
Includes scorecards and FMC sheets. See WRC email, August 27, 2013.

[Email to Delegate list, December 8, 2013](https://groups.google.com/forum/#!topic/wca-delegates/nTZPHsvlVMU).

**Comment by SAuroux** [comment]
This shouldn't be a "maybe". There should just be a guideline inlcuding a minimum time of 1-2 weeks. I see this as very uncontroversial.

**Comment by lgarron** [comment]
I've put 1 month in the diff above. I don't want to spend the time looking it up, but I think we sometimes we get correction emails after around two weeks. I think one month is reasonable (you're not required to stockpile more than a competition or two), and I've encouraged keeping them "as long as possible".

I still have all the Stanford score cards in a box in my room.

**Comment by SAuroux** [comment]
Wait, a "must" in a Guideline? 

I disagree with a month. That's far too much for a must rule and takes too much responsibility away from the competitors that should generally make sure their results are recorded correctly. My current personal practise is 2 weeks and I was never asked for corrections after those within ~50 competitions delegated. One week for a "must" is more reasonable in my opinion.

**Comment by lgarron** [comment]
Yes, a "must" in a Guideline. We have a few of those, although arguably not
as prescriptive. If you think adding something to 1c or 1c3 would be
better, we could do that, too.

Perhaps your personal practice is fine, but I'd like a reasonably
conservative standard. If no other Delegates disagree, I'd like to go with
1 month. I'm sure you could handle it. ;-)

»Lucas Garron
