### ISSUE TITLE
Clarity: which +2 penalties apply to attempts done without a stackmat (eg. multilind)

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#780]
The two +2s in question here are A6c and A6e, because all other ones are pretty obvious.  These regulations prevent the competitor from turing puzzles after the solve so they should still apply. However right now they don't make sense without the stackmat since they mention stopping the timer.
Another consideration is that there are quite a few ways to unintentionally violate A6c/A6e, eg. signalling to the judge with one hand while holding the puzzle with the other, attempting a stackmat-like signal but hitting puzzles, reaching time limit in multi while holding/touching a solved puzzle. The worst one would be making the last turn(s) on a puzzle as the judge tells you time is up.

**Comment by Ivan-Brigidano** [comment]
The Regulation [B5b](https://www.worldcubeassociation.org/regulations/#B5b) says:
> When using a stopwatch, the competitor stops the solve by placing the puzzle back onto the surface and notifying the judge that they are stopping the solve. At that moment, the judge stops the timer.

So as this defines what stopping the timer is for non-stackmat solves, I think there is no need to make a clarification.

**Comment by xsrvmy** [comment]
@Ivan-Brigidano the judge is stopping the timer, not the competitor though
