### ISSUE TITLE
Clarify that 3h2a doesn't prevent clocks from having transparent parts

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#784]
I've heard someone try to argue that 3h2a technically disallows all clocks. Obviously this is not the case, but the Regulations don't explicitly make clear that this doesn't override the intent of 3h to allow mass-produced clock models.

**Comment by xsrvmy** [comment]
Does 3h2a even matter for clocks since it is addressing specifically stickerless puzzles?

**Comment by JonEsparaz** [comment]
Stickerless puzzles are just an example in 3h2. It covers all "puzzles whose colored plastic is visible inside the puzzle", so I think clocks are technically affected.

**Comment by Burnsy101** [comment]
I agree, and also think that in 3h4 to address the issue of people possibly 'seeing' the other side of the clock whilst solving, there should be an exception to confirm that the insert is somewhat opaque

**Comment by Sixstringcal** [comment]
Should we potentially expand this idea to also allow non-visible parts of the cube to be clear?  I mean, Gan GES are clear and not visible.  If they weren't clear, it would make no difference.  Additionally, if they aren't legal that's a lot of results done on illegal cubes....

**Comment by xsrvmy** [comment]
@Sixstringcal there is an issue on that already. The proper reading of ths reg would be puzzles with transparent COLORED parts are not permitted
