### ISSUE TITLE
The Regulations do not currently allow scramble validation (via video)

### ISSUE THREAD

**Issue by JonEsparaz** [thewca/wca-regulations#785]
It is common practice for Delegate(s) to review video evidence if a record is broken to ensure that the scramble was correct. But I cannot find anything in the Regulations or Guidelines that requires a competitor to share the video with Delegate(s). So, do competitors have "right to refuse"?

Hypothetical: A competitor breaks 3x3 NAR single. Even though the scramble was correct (but the competitor has no way of knowing this), the competitor fears that their record may be nullified due to a mis-scramble. When the Delegate asks to review the video, the competitor chooses to withhold the video from the Delegate.

Although I think most high-level competitors have enough integrity to allow video review of records, if competitors are expected to hand over their personal videos for review, I think that the Regulations (or at least the Guidelines) should state this explicitly.

Proposed solutions:
- Classify breaking a record as an incident in 11a, so that 11f applies
- Clarify 2k2 to explicitly include withholding video evidence; this has a potential issue because I am unsure if this is actually "cheating or defrauding the officials"
- No solution is necessary if competitors have "right to refuse"

**Comment by lgarron** [comment]
I believe that the onus should not be on the competitor for this. It is the WCA's job to run trustworthy competitions, and competitors should not be on the hook for fixing our scramble accountability issues.

**Comment by JonEsparaz** [comment]
I am more in favour of "right to refuse" (my apologies for making it seem the opposite). But if Delegates will continue to request videos following records, I believe the Regulations and Guidelines should explicitly allow this. Otherwise, video review should not be requested (explicitly disallowed).

Regarding the WCA's job, even after scramble signing becomes mandatory, (although there is more accountability) competitors have no guarantee that their records are safe from mis-scrambles. This is veering into a different discussion, but in the Toronto-area, mis-scrambles still happen despite scramble signing.

**Comment by Claster** [comment]
I believe we are talking about cases where the video actually exists, right? E.g. a competitor cannot foresee whether they will break a record, and they accidentally won't film themselves.

If a competitor refuses to provide an existing video, the Delegate could ask WDC to investigate, suspecting something suspicious. And then for WDC we have the following sentence in the [motion](https://www.worldcubeassociation.org/documents/motions/10.2019.2%20-%20Disciplinary%20Committee.pdf):

3. All Registered Speedcubers must fully cooperate with investigations by the WCA Disciplinary
Committee.

Having what you are asking in Regulations could save some time appealing to WDC though.

**Comment by Samuel-Baird** [comment]
> I believe that the onus should not be on the competitor for this. It is the WCA's job to run trustworthy competitions, and competitors should not be on the hook for fixing our scramble accountability issues.

No need to scramble check either then.

**Comment by xsrvmy** [comment]
The scramble check has to be done at the competition, or we have a 6.88 incident. Won't it be too late if the WDC gets involved?

**Comment by Samuel-Baird** [comment]
> The scramble check has to be done at the competition, or we have a 6.88 incident. Won't it be too late if the WDC gets involved?

The 6.88 was checked and the delegate chose to not give Feliks an extra for some reason ¯\_(ツ)_/¯

**Comment by JonEsparaz** [comment]
> > I believe that the onus should not be on the competitor for this. It is the WCA's job to run trustworthy competitions, and competitors should not be on the hook for fixing our scramble accountability issues.
> 
> No need to scramble check either then.

I agree with @UnderwaterCuber here. If "competitors should not be on the hook", how is scramble validation fair? As an interesting example, I assume the 3.47 3x3 WR was not scramble validated via CCTV footage, so why should any competitor have to hand over their video to a Delegate following a record? 

The reality is that scramble validation will continue to happen following records. My main issue is that given the current Regulations, I don't believe Delegates have the authority to scramble validate (and specifically to request video of records from competitors).

IMO either:
a) Stop validating scrambles following records
b) Actually give Delegates the authority to do so

**Comment by xsrvmy** [comment]
@JonEsparaz I'd assume the scramble would be partially validated by reconstruction.
But then if the 4.69 was not recorded you have bigger problem.
