### ISSUE TITLE
Remove Regulation 2h

### ISSUE THREAD

**Issue by OrangeGreenCuber** [thewca/wca-regulations#789]
I think we should remove this regulation.  I've been to a few competitions where it was really hot and I would have really liked to have been able to take my shirt off (I'm a guy).  I know it says that you can be disqualified at the discretion of the delegate, but that being said, you're still breaking the regulation even if the delegate decides to not disqualify you.  I'm pretty sure my delegate would have understood and potentially not disqualified me, but that still doesn't change the fact that if I would remove my shirt then it would be breaking the regulations.  Maybe there can be a clause stating that if the temperature is over 80 degrees Farenheit that you can remove your shirt?

I'm also curious as to how this regulation would work if say you have a medical condition where you cannot have a body temperature above a certain temperature and you really have to take your shirt off.  I've seriously considered wearing clothes that were cut up (ie, a shirt that covers just down to the armpits with super short sleeves) since technically, fully clothed would mean you have an article of clothing for each garment someone would be expected to wear (underwear, shirt, pants).  That being said, I still feel like I'd be cheating the regulations and I don't want to do that.

Of course there would be an exception that if you're female you would have to have at least a swimsuit on as we wouldn't want any nudity.

It also brings me to another question (maybe it's worth making another issue about?) if a competition happened at a swimming pool and the stations were underwater (waterproofed of course), could the competitors wear swimsuits?

I know it sounds silly, but this is a big issue to me.  I also think it could help with body odor because it would reduce sweating I think.  My mom is always complaining about the body odor at competitions.

**Comment by Samuel-Baird** [comment]
I agree, you definitely have some good points here. I would be in favor of making 2h more lax or potentially removing it.

**Comment by weatherman223** [comment]
I don't support removing the regulation completely as most venues have code of conduct rules where you have to be fully clothed. I would support making this regulation more lax based on the rules for the venue. 

Maybe an extension or guideline such as:

2ha/2h++) Depending on venue rules and at the discretion of the delegate, the competitor may choose to remove a shirt or upper body covering.

This can also be a new 2h, but i simply support an addition or guideline as above

Edit: But as well, I would be down for a regulaton requiring deodorant haha

**Comment by Burnsy101** [comment]
The temperature of the venue should never be above 80 fahrenheit as it is recommended that the max temperature for a venue to be is 77 fahrenheit
As for the swimming pool scenario, I could never imagine that happening ever in a WCA competition ever and there will never be solving stations underwater for many other reasons.
As for the BO arguement - with experience with running, it is normally much worse if people have their armpits exposed and their tops off - have deoderant in your bag and recommend people to use it if they stink (someone did this at a comp I went to actually it did help)

And if you REALLY need to take your shirt of - even if its 90+F, it would still make a lot people uncomfortable, especially younger children - just cool off in a toilet for 5 minutes
2h is 100% necessary in my opinion so we don't have people doing innapropriate things

**Comment by UnderwaterCuber** [comment]
> The temperature of the venue should never be above 80 fahrenheit as it is recommended that the max temperature for a venue to be is 77 fahrenheit
> As for the swimming pool scenario, I could never imagine that happening ever in a WCA competition ever and there will never be solving stations underwater for many other reasons.
> As for the BO arguement - with experience with running, it is normally much worse if people have their armpits exposed and their tops off - have deoderant in your bag and recommend people to use it if they stink (someone did this at a comp I went to actually it did help)
> 
> And if you REALLY need to take your shirt of - even if its 90+F, it would still make a lot people uncomfortable, especially younger children - just cool off in a toilet for 5 minutes
> 2h is 100% necessary in my opinion so we don't have people doing innapropriate things

The temperature can be higher than recommended.

Nothing prohibits a swimming pool competition

Cooling down can help reduce the amount of sweating, removing articles of clothing can await with this.

Some people may find feet being exposed uncomfortable but we hold feet ¯\_(ツ)_/¯ I’m also sure that people wouldn’t abuse this and do inappropriate  things, on the off chance that they did then the delegate can always get rid of them for conducting themselves in an inconsiderate manner.

**Comment by UnderwaterCuber** [comment]
I see another huge problem with 2h that may big for revision or even potential removal. Several months ago I held a competition where my house was the listed venue, due to the regs and the wording my delegate had full power to disqualify from my own competition. How you may ask? Well just read 2h

2h) Competitors must be fully dressed while in the competition venue. At the discretion of the WCA Delegate, competitors may be disqualified from the competition for inappropriate clothing.

Note how it CLEARY never specifies that this must occur during the competition. The morning of my competition I took a shower, and is as standard of most Americans I removed all clothing to cleanse my body, as a result violating the regulations and giving my delegate power to disqualify me from the entirety of my own competition. 

I hope that everyone here realizes the extremely unfair powers of 2h that could be abused to harass and bully competitors worldwide. 

*note* fully dressed is also pretty subjective, also remaining clothed is part of complying with venue regs so it’s pretty redundant to have overall

**Comment by OrangeGreenCuber** [comment]
> And if you REALLY need to take your shirt of - even if its 90+F, it would still make a lot people uncomfortable, especially younger children - just cool off in a toilet for 5 minutes
> 2h is 100% necessary in my opinion so we don't have people doing innapropriate things

I think that people certainly wouldn't feel uncomfortable.  People bike, run, exercise, and do many other sports shirtless all the time.  Cubing is a sport and I don't see how being shirtless cubing is any different from being shirtless in a UFC fight.  In my experience, younger children tend to be more comfortable around shirtless people.

What I'm proposing is NOT allowing nudity.  Public nudity is very rarely allowed as far as I'm aware, which would be covered by other regulations (2f and 2k3).

**Comment by Sixstringcal** [comment]
Interesting thought: What if a venue required you to be shirtless to enter and was still publicly accessible to everyone?  Could you actually hold a comp there?  Or would the conflict between 2h and 2f prevent the comp from being held?

**Comment by UnderwaterCuber** [comment]
> Interesting thought: What if a venue required you to be shirtless to enter and was still publicly accessible to everyone? Could you actually hold a comp there? Or would the conflict between 2h and 2f prevent the comp from being held?

Also in the case of using a room in a facility where there was a pool or gym or something similar then regs do allow disqualification of competitors who use those

**Comment by Laura-O** [comment]
What if the venue was a fighting club and someone would fight during a break. Would 2k3 be applied?

**Comment by mirandapedro** [comment]
Hi.

For now, I'm closing this issue.

Article 7d+ of the Guidelines states:

`7d+) The temperature of the competition area should be 21 to 25 degrees Celsius.`

This issue is not particularly urgent and, in practice, not many problems arise from it.

If we need to, we can reopen it in the future.

**Comment by OrangeGreenCuber** [comment]
So because it's not urgent you're dismissing the entire issue?  Got it.  Let's never improve the regs.  What we have right now is fine.  I'm also guessing that #787 is not urgent either?  Or #782 and for the most part most of what's on here?  Are we only going to modify regs if someone gets physically hurt or there is a really controversial ruling?  I think we should make these regs before someone dies/gets hurt.

**Comment by weatherman223** [comment]
Okay, no one is going to die if they can’t remove their t-shirt.

>BUT OVERHEATING ILL DIE OF HEAT STROKE!!!!!!

Then ask the venue to turn on a fan or open a few windows to let a breeze come in. 

These issues are urgent but not urgent enough for immediate action, they’re urgent in the sense that they’re important to the community and need to be discussed. 

Also can we please stop overreacting with “my delegate will exclude me!!!!” That won’t happen, they are bound to a code of ethics and will immediately lose such a position.

I’m now completely opposed.

**Comment by OrangeGreenCuber** [comment]
> Then ask the venue to turn on a fan or open a few windows to let a breeze come in.
> 

On many occasions I have asked organizers to do this and nothing has happened.

> These issues are urgent but not urgent enough for immediate action, they’re urgent in the sense that they’re important to the community and need to be discussed.

And how is this not important to the community and who decides what needs to be discussed?

The way I see this is that the people on Github don't actually want to take this seriously (which is a shame because isn't this the place you are supposed to take all this seriously?).   If this wasn't an issue, I'd post it in Rubik's Cube (Speedcubing), but there's a reason I put this here and it's because it is urgent enough for immediate action and it is important to the community and it does need to be discussed.

**Comment by xsrvmy** [comment]
Agreed that 2h needs to be reworded. Currently practicing feet would technically be against 2h.
Fully dressed is not really well defined either.
Potential wording: A competitor must not be dressed in a way that is offensive to others. Then as a clarification: This regulation must only be used to deal with non-fully dressed competitors, and not clothing with possibly offensive messages.
