### ISSUE TITLE
Proposal: A6c and A6e update

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#793]
In the incident log entry for the 4x4 WR incident, there was a note saying that A6e would be updated to reflect the ruling. There has yet to be such an update.

I have a proposal here that may seem a bit controversial for the WRC, since precedence is against it, specifically the 4bld 2:05+2 incident, but here it is anyways:
- Update A6c and A6e so that it becomes one regulation
- Change the penalty:
  - If the competitor affects the state of the puzzle deliberately - DNF
  - If the competitor touches the puzzle when it is very close to the misalignment limit, give the worst possible misalignment penalty
  - Otherwise, no penalty
- Add "without holding the puzzle" to A6d. This would only apply when the competitor is clearly holding the puzzle in at least one hand, as opposed to the puzzle "rolling off the hand".

Pros:
- From a non-cuber's point of view, it does not make sense that picking up the puzzle after the solve should result in a penalty.
- If a competitor stops the timer while barely touching the puzzle, it can be hard to tell if there is one touch or two (since only second touch breaks A6e). Merging A6c and A6e would remove the necessity of making the decision.
- A competitor would no longer be penalized twice for holding the puzzle while stopping the timer (it would only be one +2 for chopping).
- Accidental touches would not result in a penalty until close to misalignment limit.
- We no longer need judges to obey A7a.
- This avoids ambiguity in what happens at the end of a multiblind attempt if the competitor touches a puzzle/is actively holding a puzzle.

Cons:
- It seems to be against precedence
- Worst possible misalignment penalty is confusing, just like the old rule on handling popped pieces
- An incident might happen if the judge is not paying attention, but this is the case right now anyways.

Notes:
- Even if the penalty for A6c/e does not get updated, I still think they should be merged.
- If +2 misalignment is removed, the worst possible misalignment penalty is no longer confusing because it would always be a DNF. Instead, the current plus 2 would become no penalty.
- There has been another suggestion before: A6e would only apply before the judge decides whether or not to give a penalty for misalignment (but not necessarily before the judge checks the back of the puzzle is solved).

**Comment by Samuel-Baird** [comment]
Bit off topic but I don’t think I have ever seen A7a1 or A7a2 done lol

**Comment by xsrvmy** [comment]
@UnderwaterCuber The exact wording is basically never used cuz it sounds dumb. "Penalty" makes no sense anyways cuz DNF is still a penalty.

**Comment by Samuel-Baird** [comment]
#534

**Comment by lgarron** [comment]
Thanks for writing up a proposal. Would you mind commenting with that in #534 to keep the discussion there?
