### ISSUE TITLE
Expand 2t to include the Guidelines

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#794]
As 2t stands it only ask that competitors be familiar with the regulations. It could be nice to expand this to the guidelines seeing how there are lots of things on there that would be good for competitors to know ex. E2b++

**Comment by dancing-jules** [comment]
Uh. Isn't part of why the guidelines exist that competitors are already to lazy to read the regs, so we don't want to make the mandatory reading material longer than necessary?

**Comment by lgarron** [comment]
Agreed with @dancing-jules's point.

A lot of people would really like to move to a point where a new competitors needs to know *less* than the full Regs, but it's the best balance for now.

**Comment by Samuel-Baird** [comment]
Maybe using “should” could help? It’s pretty useful to be familiar with them (as can be seen in my example) so just encouraging them to read it, but not requiring it, could be helpful 

2ta Each competitor should be familiar with and understand the WCA guidelines before the competition.

**Comment by SAuroux** [comment]
The fact that the Guidelines supplement the Regulations is already part of
the Regulations though. So it is not new that fully understanding the
Regulations includes knowing the Guidelines.

UnderwaterCuber <notifications@github.com> schrieb am Fr., 4. Okt. 2019,
17:35:
