### ISSUE TITLE
Require Practice Cubes to be Out of Sight?

### ISSUE THREAD

**Issue by Sixstringcal** [thewca/wca-regulations#796]
Hi,

While at Back to School Idaho 2019, a competitor brought to my attention that technically if you didn't know your color scheme for 4x4 or 6x6, it would be beneficial to have a practice cube on the table so you could see 3 faces.  This would allow competitors who know what colors are opposites of each other to be able to glance at their practice cube to figure out their color scheme.  While it's really only practical to do something like that for 4x4 and 6x6 where you don't have fixed centers, I don't think it would be fair to allow it for the rest of the events.  I do realize that we could never truly ban them (and I'd be against it anyway), but I think maybe requiring the cube cover to be placed over the practice cube would be fine?  I also realize that it's a cubing competition and there will be plenty of other people with cubes that a competitor could glance at, but the color schemes of other people are not guaranteed to be correct, and eliminating cubing outside of the competitor area is unreasonable.  I think that only allowing one practice puzzle and requiring the judge place the cube cover over the practice puzzle is totally reasonable.  The only thing is what would a penalty be for not doing that?  I feel it's kind of like when the judge forgets to put the sight blocker in front of the competitor's face for blindfolded events, so the competitor would get an extra right?  You could never put the blame on the competitor because the competitor has every right to focus entirely on their solve and should not be distracted making sure the judge covers their practice cube.

I feel like this would probably never be implemented due to what I've mentioned above, but I do believe that it is a serious problem.  Maybe even making a "judges should make an effort to cover competitor's practice cube" and also disallowing more than one practice cube.

I feel like disallowing more than one practice cube also makes it less likely that a competitor will switch a bluetooth cube in mid-average since competitors sometimes switch cubes during their average.

**Comment by xsrvmy** [comment]
what if the judge forgets to put the cover over the warmup cube?
I don't see any significant advantage. The corners of the puzzle is literally all you need. Plus there will probably be many other puzzles and posters around you can look at.

**Comment by Jambrose777** [comment]
I’d recommend ready the All Aboard 2017 report (I believe the following is in there). This gives way for judges to easily be able to steal cubes without the comeptitor noticing. It’s certainly going to cause more issues than it solves.

**Comment by Sixstringcal** [comment]
I didn't think about cube theft.

As for the corners being all you need, the corners are much more difficult to find for someone who needs another cube to check their reference scheme (or really anyone I'd imagine).

I do think that discussing this further is pointless (there were already quite a few downsides before cube theft was brought up) so I'll close this issue.
