### ISSUE TITLE
Allow pre-arranged exceptions to the Regulations

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#799]
Sometimes there are ideas or proposals that are difficult to test because the current Regulations are too restrictive. I'd like us to consider formal conditions under which we're willing to consider experimental changes. I'm thinking something like this:

- The proposed exception is publicly proposed (e.g. as an issue here).
- The exception is granted with an individual decision per competition.
  - The exception is granted with the smallest practical scope to evaluate the idea, e.g. only trying ideas with few competitors, and/or having an extra staff members overview any attempts affected by the experiment
- The proposal must clearly document steps to limit the risk of unfair consequences.
- A majority of members of the WRC and a majority of Board members must vote in favor.
- The exception is documented in the Incidents log *ahead* of the competition.
- After initially being used, the same exception can only be used for 1 year. After that, it must not be used unless:
  - the Regulations have been updated to accommodate it, or
  - a supermajority (maybe 2/3?) of the WRC and Board vote to allow experimentation for 1 more year.

Examples of the kind of things I'm thinking of:

- Allowing new camera ideas (e.g. `mentalblock`'s backpack camera).
- Allowing Bluetooth cubes for 3x3x3 finalists in order to test technology ideas (live reconstructions, "instant replay").
- Allowing a competitor without hands to compete in normal 3x3x3 but also allowing the first round 3x3x3 results to count as a duplicate 3x3x3 with feet round for the competitor.
- Head-to-head formats where competitors must start their solves at the same time.

I'm not saying any of these are necessarily *good* ideas, but there are reasons to consider trying them out.

The latter two have significant risk of cheating if we allow them at scale, but I'm confident that we can make sure competitors aren't getting an advantage if we only test at specific competitions with sufficient oversight.

**Comment by EdHollingdale** [comment]
I personally think this is a terrible idea. The WCA Mission Statement says "under fair and equal conditions". This is violates that.

Of your examples, the first is not something that needs to be tested (we should just change the regulations to be more lenient around cameras), the second is maybe the only case where I think your point is valid (I would love to see live reconstruction), the third is an extreme case where I can't see many cases of it happening (plus will 333wf be an event for much longer?), the fourth gives a massive disadvantage compared to other competitons. Plus we already test the fourth in unofficial relays.

**Comment by Samuel-Baird** [comment]
I’m with Ed here, even with a bunch of people trying to think of risk associated with this it’s going to cause unfairness in the end. If you really need to experiment with some of the things then that can always be done at unofficial competitions or during unofficial rounds at competitions. 

two examples you listed concern me as well, the feet one competitors are now able to get up to 8 rounds of feet from a normal comp, or if it’s only allowed at comps without feet they are now able to get feet results in regions where feet is not held normally. (Also smh using feet as an example when it’s getting removed) 

For head to head that would almost certainly apply more pressure to competitors.

Also, I don’t know if you were thinking about this or not but I don’t see anything about public announcements, it would make sense to require any competitions holding this to make competitors aware of changes before registration, with that there is a possibility that competitors may travel to these comps more often if they can see it as advantageous.
