### ISSUE TITLE
Proposal: Change WCA Notation to SiGN 

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#80]
I propose changing the WCA notation to [Simple General Notation](http://mzrg.com/rubik/nota.shtml)

SiGN much simpler and more intuitive than the current notation, and I believe it would be very beneficial to switch the current notation to it. The current notation is confusing (e.g. r and Rw mean different things, and it's not very intuitive to figure out which one is which), and there are other drawbacks that SiGN does not have, such as the ability to show a slice move as one move. Currently, cubers use both notations, and if we change this we could reduce the inconsistencies between the different notations being used.

SiGN is also a much more convenient and practical notation. In SiGN, single layer turns are always denoted by capital letters, and block turns are always denoted by lower case letters. Despite the fact that single layer turns aren't used in WCA scrambles for official big cube solves, it'll be helpful for cubers who like to use whatever the WCA uses as their preferred notation. Since SiGN is based off of 3x3x3  notation, it is much more 3x3x3-friendly than the current notation, too.

SiGN is also less bulky than the current notation. It takes up fewer characters (r' as opposed to Rw'), which makes it more compact and probably more readable.

I don't see too many drawbacks for changing this. I suppose that Rw is more noticeable than r in a scramble, and a lower case L might be confusing, but both of these problems can be fixed by changing the font or style of lower case letters. I don't think many people will confuse "r" for a slice move, since people who have scrambled big cubes before would generally know that slice moves aren't used in big cube scrambling.

Here's a quote from Michael Gottlieb:
"SiGN has a number of benefits over other notations. Since it's based off the 3x3 notation, it's easy to remember, and doesn't clash with a common notation that has been in use for some 30 years. It doesn't require any superscripts, subscripts, or weird characters, so it's easy to type out any move sequence. It's also complete enough to describe both multiple- and single-layer turns as one step, mirroring the way cubes behave in real life. One potential problem is that it is important to keep spaces between adjacent turns in SiGN, because otherwise there are situations 
that could be interpreted as two or more totally different things."

**Comment by lgarron** [comment]
The 2013 Regulations accomplished a major goal: Making WCA notation and SiGN compatible. "Rw" and "r" are just aliases.

I think the current notation has at least one benefit: It's pretty clear. Occasionally people ask about it, but I haven't really heard complaints that it slows down scrambling.

Two small things:
- Re-read [Article 12](https://www.worldcubeassociation.org/regulations/#article-12-notation) in detail. I think you have a few things wrong.
- "u" and "U" can be hard to tell apart on an FMC solution.

**Comment by sarahstrong314** [comment]
I don't think it slows down scrambling either, but I'd like the notation to be more practical for those who also use it outside of WCA competitions. SiGN is great for big and small cubes, but it's not used much because many cubers view the WCA notation is the official notation. 

What do you mean "Rw" and "r" are aliases? In FMC you have to use "Rw" instead of "r".

**Comment by SAuroux** [comment]
"r" is non-existant in the current notation! As a logical result, "r" cannot be confused with anything.

**Comment by lgarron** [comment]
Exactly. That was my strongest motivation for removing `r`: It allows SiGN and WCA notation to be compatible, even if one uses `r` where the other uses `Rw`.

(`r` was also defined but not used in the Regulations, which might have been enough reason to remove it. FMC hasn't had a problem without it.)

**Comment by SAuroux** [comment]
In contrast: FMC surely has less problems without it.

So, is there any actual issue? I read Sarah's text but I can't agree on any advantage that SIGN should have over our current notation. As a big Con, please remember the hassle we had at the beginning of the year because of the changes to the notation we made. I'm not in favour of annoying the community with another massive notation change for 2014, espcially as it seems very unnecessary.

**Comment by lgarron** [comment]
There doesn't seem to be demand for this, and as Sébastien's last comment points out, such a change is just going to invite arguments.

As much as I prefer SiGN, I think the current core the WCA notation is sufficient (and reasonable).
