### ISSUE TITLE
"Statute of limitations" for results

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#800]
Community sentiment and WRC decisions sometimes shift over time, leading to the question of whether to revisit past decisions (e.g. the 18.44 4x4x4 WR, Ushakov's FMC WR).

I think it would be reasonable to define a point at which results are sufficiently in the past that we don't revise them unless we have new, significant evidence of cheating/very unfair advantage.

2 years is probably enough, 1 year might also be good.

I'm aware that this might have the side effect that competitors might delay posting some of their videos until the time has passed, for fear of retroactive penalty. That is a tradeoff of this idea, and reminds us that we still need to work towards the best balance of fair, objective, and kind (#798) that we can.

**Comment by Samuel-Baird** [comment]
Define “Very unfair advantage”, I would consider not getting a +2 penalty for the same thing that hundreds of other competitors are getting +2s for when regs clearly state that you should get that penalty is pretty unfair. 

Also this idea doesn’t seem that good to me, if the decision was poorly made originally (see 18.84 WR) then nothing changes which pretty much means that all it takes it a bad judgement call to lock in your results. I don’t see any real harm in allowing the discussion of previous results which are unfair, I mean it’s literally in the spirt of the wca to have fair and equal conditions for all competitors and we shouldn’t put a deadline on that.

**Comment by lgarron** [comment]
@UnderwaterCuber I think that's also a reasonable argument! It might turn out to be the right way to resolve this issue.

I don't know what would be the approach that is overall best for the community, but we won't find out without discussing it! 😃

**Comment by xsrvmy** [comment]
I think we need to distinguish between normal incidents (eg. 4x4 18.84, 6x6 1:20.xx) and cheating incidents.
Specifically, in the case of the 19 FMC, the brackets in the solution would fall under a normal incident and be subject to the timeframe limitation, but the suspicious solution would not be subject to the timeframe. However there still should be a timeframe limit from when the cheating is suspected till a decision is made.
The reason that cheating need its own category is that cheating is often not discovered until a repetitve pattern occurs.

**Comment by Jambrose777** [comment]
I don't think we need to set a time frame. 

Once a WRC decision has been made it should stay forever unless new information presents itself.

**Comment by UnderwaterCuber** [comment]
Pros:
-You won’t have to worry your old results getting changed
-Saves time for WRC 

Cons:
-Allows unfair results to exist
