### ISSUE TITLE
Remove 2a

### ISSUE THREAD

**Issue by BlakeThompson-cuber** [thewca/wca-regulations#802]
One thing that could allow very fun competitions is having adult competitions which could involve drinking, recreational drug use, nudity etc. Allowing minors to compete in all competitions would ruin this. I propose that we change the regs to let competition organizers set age limits for competitions. 

Pros:
•allows for use of more venues
•allows for alcohol and recreational drug use
•allows for nudity 
•lets wca grow
•makes it easier to meet people your same age at competitions

Cons:
•none

**Comment by Jambrose777** [comment]
Hey fake Blake. WCA competitions don't discriminate by age, gender, race, or nationality. Everyone has an equal opportunity to compete. Regulation 2a has nothing to do with this.

@WRC, can you please close this issue as it's obviously inappropriate.

**Comment by BlakeThompson-cuber** [comment]
Why was this closed?
