### ISSUE TITLE
Modify A6f1

### ISSUE THREAD

**Issue by BlakeThompson-cuber** [thewca/wca-regulations#803]
It currently reads

If the competitor resets the timer before the result has been completely recorded, the judge must not write down the result from memory or from video or photographic evidence, and must disqualify the attempt instead (DNF).

Change it to

If the competitor resets the timer before the result has been completely recorded, the judge may write down the result from memory if they know it’s for sure correct or they may write it down from video or photographic evidence. If they can’t remember or have evidence DNF.

This is so people don’t get their times DNFd as much when they knew what the time was

**Comment by BlakeThompson-cuber** [comment]
Why was this closed?

**Comment by UnderwaterCuber** [comment]
While it seems this is some sort of alt I do think it could be good to modify A6f1 to allow video or photographic evidence to be used. Yes competitors could edit footage or photoshop images but I doubt anyone would be able to pull off anything convincing within a few minutes of a timer reset.
