### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by BlakeThompson-cuber** [thewca/wca-regulations#805]
All issues are being closed by Ivan Brigidano who I think might be a hacker or an automated bot. This is a test to see if this issue will be instantly closed with no response or if not

**Comment by blake98x** [comment]
@BlakeThompson-cuber, I don't know if I should be humbled or spooked regarding your username. If you would like to continue posting on this GitHub without your posts being closed, please be wiser about your username choice.

**Comment by BlakeThompson-cuber** [comment]
Yes it is a bot or a automated system or hacker

**Comment by BlakeThompson-cuber** [comment]
> @BlakeThompson-cuber, I don't know if I should be humbled or spooked regarding your username. If you would like to continue posting on this GitHub without your posts being closed, please be wiser about your username choice.

What’s wrong with my username? it’s just my name and then cuber, I don’t think it’s offensive or anything
