### ISSUE TITLE
Add all historical incidents to the Incidents log

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#809]

**Comment by Ivan-Brigidano** [comment]
I suggest to only add most relevant Incidents. There are like about 100 Incidents but most of them are completely irrelevant. Do you have any thoughts for starting with this?

**Comment by lgarron** [comment]
> Do you have any thoughts for starting with this?

I think a good idea might be to divide them up and ask each WRC member to transfer them, with a target deadline a few weeks in the future. ≈10 incidents per member sounds pretty reasonable to me.

**Comment by Ivan-Brigidano** [comment]
@lgarron this idea sounds strong to me

**Comment by Ivan-Brigidano** [comment]
By reading the historical incidents I have came up with two conclusions:

1. None of the remaining historical ones are that important.
2. We have had similar cases eded up with the same ruling and a Incident Log.

So I don't think this should be done as is a waste of resources. @lgarron feel free to reopen it and pushing this to be done if you disagree with me.
