### ISSUE TITLE
Plan a sustainable WRC Digest

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#810]
Depends on the Incidents log: #809

**Comment by Ivan-Brigidano** [comment]
I think the best way to do the WRC Digest is every 3-4 months to have enough incidents.

I suggest a template like this:

* A list of most relevant incidents that had happened (with links to Incident Log).
* A detailed explanation of the incidents that need it.
* A list of non relevant incidents that had happened (every case that we didn't mark as `Digest worthy`)(also with links).
* A summary of possible changes to avoid some incidents that had happened (with links to GitHub Issues).

I believe the best way to manage this is that every Digest is done by a different WRC member. Similar of how we manage Delegate Reports.

**Comment by hanwu85** [comment]
By "every digest is done by a differnt WRC", do you mean 1 person take 1 incident and make a short paragraph about it?

**Comment by Ivan-Brigidano** [comment]
@hanwu85 my original suggestion was that the whole Digest is done by a WRC member and every time is a different WRC member. But I also like your idea!

**Comment by hanwu85** [comment]
Good, I think we have a rough outline of what the digest should be.  Should we aim for a date for publishing on the website?

**Comment by Ivan-Brigidano** [comment]
WRC Digest used to be only for Delegates. It might be a good idea to make one for Delegates and other one on the website (without private details as names)

**Comment by hanwu85** [comment]
I didn't know we had a delegates only digest.
@lgarron , should we publish 2 types of digests?

**Comment by Rouxles** [comment]
In my opinion, 2 Digests should be created (really shouldn't even be too hard to code something to hide competitor names) which will also advise competitors on what they could be doing to avoid being part of these incidents.

I like Han's idea of having one WRC member take one incident and writing a short paragraph about it - it splits up the workload so it's not as daunting doing the whole digest.

**Comment by Ivan-Brigidano** [comment]
Any update with this? Do you have any thoughts or a draft for it?
