### ISSUE TITLE
Make 6x6x6 and 7x7x7 Round Format Median of 3

### ISSUE THREAD

**Issue by pd159** [thewca/wca-regulations#813]
Big cubes are all about adrenaline—while stamina is an important factor of our current Mo3 format, it allows for many frequent issues including pops/lockups (due to the nature of the puzzle) and too much variance with one fluke solve, which happens a lot on these events. It's honestly unacceptable that a world-class solver would lose to a 4-minute solver in the final round just because he DNFed one solve by a slice move; it's not an accurate representation of skill in the slightest. Because of this, I strongly recommend considering a Median of 3 format (Med3): not only would it fix these issues, but it would keep the standard 3 attempt format, meaning not much logistics-wise would be changed. For now, I profusely believe that this would optimize the current state of big cubes in competition.

P. S. This is a re-post

**Comment by lgarron** [comment]
For what it's worth, I think that "Median of 3" is actually quite a reasonable format — it has most of the benefits of Average of 5. The main drawback is that this is a new round format, while we have generally been working to simplify the number of formats.

It might be worth adapting the community survey question at https://github.com/thewca/community-surveys/blob/master/2019/draft/6-regulations.md to at least get input on this.

**Comment by Louis-dM** [comment]
Reposting what I said on the first post:

I've always thought Median of 3 could be a good format for 3BLD, perhaps it could also work well for bigcubes? I'm slightly hesitant about letting a single result decide competitions for events with such a high success rate, even if luck doesn't play a big role because of the length of the solve. (Edit: Paris' original proposition was Bo3)

(Also, this reminds me of a point from the livestream from today's WRC meeting: there was some discussion about changing misalignment +2s to DNFs. I'll admit I'm not experienced in the Mo3 speedsolving events (6x6 and 7x7) but I expect such a change could impact them significantly if their format is not changed. As mentioned in the livestream this is not a huge problem for Ao5 events)

**Comment by lgarron** [comment]
> It might be worth adapting the community survey question at https://github.com/thewca/community-surveys/blob/master/2019/draft/6-regulations.md to at least get input on this.

Done in https://github.com/thewca/community-surveys/commit/7d680937c27d003c4c29d2f7ca5194d4fad15117

**Comment by Louis-dM** [comment]
After thinking about this a bit more, I've had a thought: which records would be recognised? Would we no longer keep track of Means? We can't keep track of record singles, medians _and_ means with the current system.

**Comment by pd159** [comment]
I have an idea: don't keep track of Med3 rankings. It's merely the round format which decides the winner at a competition.

**Comment by J-Rohault-dF** [comment]
Why not having 3 different formats:
- Singles (best of 3 or 5 attempts)
- Averages/Medians (all attemps except the best and worst)
- Means (all attempts)
It would probably need, for the sake of consistency, to be applied to all events at once though.
I'm not seriously defending this idea yet, just suggesting it. What do you think?

**Comment by ccbaird** [comment]
The goal of Mo3 instead of Ao5 is time savings, right? What about either cumulative time limits, or allowing Ao5 format for 6x6 and 7x7 in final rounds? That way the people who have a chance at winning can throw away a solve without taking the time to allow somebody 5 7-minute 7x7 solves. Not that I wouldn’t be perfectly happy to take up 35 minutes of solve time on one average myself, but I can see the downside. 5 2-minute 6x6 solves not so much.

**Comment by xsrvmy** [comment]
@ccbaird Hmm... I don't think having two different avg formats for the same event works for records.
The main problem with ao5 is not someone doing 5 7-minute 7x7 solves. It's that someone might do 2 10-minute 7x7 solves (cutoff in Toronto is around 6-8 usually). I am not sure 20 would be a reasonable cumulative time limit for 7x7, and 16 definitely would not be reasonable.

**Comment by ccbaird** [comment]
@xsrvmy The same issue applies to Med3 and Mo3. Mo3 and Ao5 the issue has been addressed in the past with Megaminx and Feet, (and 5x5? That would have been well before my time) when the format was changed. Both Mo3 and Ao5 it’s averaging 3 solves, the difference is just whether you average all solves or just the middle 3. Med3 and Mo3 might have a hard time coexisting, I don’t see Mo3 and Ao5 being an issue.

**Comment by xsrvmy** [comment]
@ccbaird but I doubt you would ever recognize med3 as a record. Having mo3 and ao5 at the same time would not work well for counting records.

**Comment by ccbaird** [comment]
@xsrvmy Fair enough as far as recognizing records, but could you clarify why you see a problem with Mo3 and Ao5 coexisting? There are currently both Mo3 and Ao5 results in the WCA database for Feet and Megaminx, with no differentiation between them. What would it matter if both results were set concurrently? The only issue I could personally see would be if somebody had a good mean and felt that doing additional solves and dropping a good one would hurt their average, they might prefer to do that. I don't really see that as an issue though, just do those solves or DNF the average, if that's what the rule for the round is.

**Comment by xsrvmy** [comment]
@ccbaird it gives power to organizers to try and see a specific record type broken (especially at a 1 round comp).
There is no problem with mo3/ao5 in the database. There is a problem when they can both be held at a comp.

**Comment by Jambrose777** [comment]
> @ccbaird it gives power to organizers to try and see a specific record type broken (especially at a 1 round comp).
> There is no problem with mo3/ao5 in the database. There is a problem when they can both be held at a comp.

I would say organizers splitting up the fastest cubers into different scramble groups is more power to grind a record than the format (mo3/ao5) of big cubes could ever be.
