### ISSUE TITLE
Change misalignment +2s to include slice moves

### ISSUE THREAD

**Issue by Louis-dM** [thewca/wca-regulations#814]
_Obviously, this is only relevant if we choose to keep +2 penalties for puzzle misalignments. I'm 
not sure if this belongs in the thread about that. Apologies if this is the wrong place to post 
but I feel it's a separate enough topic even if they are closely linked and even if this may become obselete._

---

While OBTM is perfectly fine for scrambling and Fewest Moves solving, in my opinion is it not an appropriate metric to use for penalties for speedsolving where slices are treated as normal moves, the same as outer layer turns (albeit they are less commonly used). I think it's important to make this distinction between speedsolving events and Fewest Moves, which are already treated very differently in most other ways. Using the same metric for everything, while simpler, does not always make sense. Why some moves should be treated any differently from others?

I'm aware the WRC are trying to simplify some things in the regulations but if we choose to keep reg 10e3 then I think introducing a couple of new regulations under 12a would maintain some consistency with how moves are treated.

**Comment by Sixstringcal** [comment]
I'm all for this.  That being said:
How does this apply to NxN puzzles where N>3?  Is it just slice layers?  Is it just "3x3" slices?
For Square-1, does this apply like if there was a (3, -3) unsolved at the end?
Pyraminx: can this technically be defined by something like a U u'?
Megaminx: does this/how does this apply?

I guess the easy answer I'd assume would be it's just for NxN (maybe including sq-1, but probably not).  And then we just limit it to one single layer being able to be misaligned?  Maybe allow a multi-layer slice being off?

**Comment by Louis-dM** [comment]
Imo for NxN it should be "blocks", since those can be executed as one move too.

I'm not very familiar with other puzzles since I don't speedsolve them. But if I had to say something:

Square-1: count slices as one move. As far as I'm aware nobody would ever execute them as one move but it's sort of consistent with NxN, and imo this should be about what people _can_ do, not just what the majority of people do in solves. Maybe there are a couple of people who finish with a slice in this case and it would be wrong to penalise them because they are the minority.
Pyraminx: count slices as one move.
Megaminx: do not count slices as one move. A "slice" can be done using two opposite layers, but it's a bit _too_ dubious imo. I'm aware this contradicts what I said about Square-1 (about consistency across events) and is a very arbritrary decision. But the only reason I can think of for how this could happen is by accident when dropping the puzzle at the end of the solve. If this happens and the top layer is misaligned then it comes down to just luck who gets DNFed and who gets a +2 because there's no control over which way the layer will turn.

**Comment by Samuel-Baird** [comment]
what would you determine the penalty to be for a case like the image linked below? I feel like allowing slice moves would ultimately create confusion, the current one face off by 45 degrees is very easy to understand and measure whereas this you would need to evaluate two faces in relation to each other and a slice in relation to each. 

https://imgur.com/v6ax7m1

**Comment by xsrvmy** [comment]
@UnderwaterCuber that would be a +2. The nearest state is off by a slice move. SQ1 is the only event where nearest state is not well defined for this to work, but see below.
In terms of SQ1, I do not think slices should be one move. Main reason is that (3, -3) is executed like U D' instead of E.
I am definitely in support of this. I have luckily never DNFed in 6 or 7, but I have DNFed in 5 by executing my last M move poorly which may have cost me podium. This would allow some room for more risky timer stops especially in 6 and 7

**Comment by Samuel-Baird** [comment]
Would we be allowing inner slice moves on big cubes as well? What about multiple layer slice moves?

**Comment by Louis-dM** [comment]
> what would you determine the penalty to be for a case like the image linked below? I feel like allowing slice moves would ultimately create confusion, the current one face off by 45 degrees is very easy to understand and measure whereas this you would need to evaluate two faces in relation to each other and a slice in relation to each.
> 
> https://imgur.com/v6ax7m1

I was thinking that similar to the current regulations (in particular 10e1), you would compare adjacent layers to determine the "actual" state the puzzle is in. Your example would be +2.

> In terms of SQ1, I do not think slices should be one move. Main reason is that (3, -3) is executed like U D' instead of E.

What if a solve is finished like this?
https://www.youtube.com/watch?v=RTNebWtJndg

> I am definitely in support of this. I have luckily never DNFed in 6 or 7, but I have DNFed in 5 by executing my last M move poorly which may have cost me podium. This would allow some room for more risky timer stops especially in 6 and 7

Imo this should be about being more consistent, not more lenient. If anything I'm in favour of removing +2 penalties for misalignments, but that's a completely different discussion.

**Comment by xsrvmy** [comment]
I don't think removing +2s is a good idea anyways especially because 6 and 7 is mo3 but that's a different discussion. I have just seen/heard of way too many 6 and 7 DNFs by a 2R on the first solve of a round so I am for this.

**Comment by jamesquinn1** [comment]
Isn't 2R a +2 anyways?

**Comment by CarterKoala** [comment]
This is super hard to implement as seen above.

2 options really:
1. Allow any misalignments as long as it's only along one slice (so stuff like U D would be +2)
2. Keep as is

The first option I'm pretty sure most people are against
