### ISSUE TITLE
Is 2i1 superseded by E3?

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#815]
Copying and pasting this here, so it's not lost:

> The more I think about it, the more I also wonder if E3 supersedes 2i1. As E does not refer to Article A (like Article B for Blindfolded Solving does) and E3 seems to give a complete list of allowed objects, I assume it does. I am happy if someone can prove me wrong, but if this is true, using earplugs or water bottles would not be allowed during FMC attempts.

**Comment by Ivan-Brigidano** [comment]
Maybe something like this would fix it:

> E3e) Some other non-electronic aids that do not give an unfair advantage, at the discretion of the WCA Delegate (see [Regulation 2i1](https://www.worldcubeassociation.org/regulations/#2i1)).
