### ISSUE TITLE
Responsibility for wrong FMC scrambles

### ISSUE THREAD

**Issue by julesDesjardin** [thewca/wca-regulations#817]
When a competitor receives a scramble that doesn't match the expected scramble, big consequences can happen (having to give an extra to the competitor, having to regenerate new scrambles if one was given out too early,...) 

If this is not detected until after the attempt, this is the worst case. That's why I think giving the responsibility to the competitor to check the attempt number could solve some issues. If a competitor gets a scramble they already have and don't notice, the attempt would be DNFed instead of eligible for an extra. 

This raises several questions :
- does the competitor still get a whole hour?
For this one, I think we could have a small window that still grants the competitor a whole hour (something like "if the competitor notifies the judge during the first minute of the attempt, they are allowed to continue after the hour has been called, until it has been an hour since they receive the correct scramble), but after this window, the competitor only has the remaining time to work on the correct scramble, as not to cause lateness.
- what happens if a later scramble is given out early?
This is the most complicated. Ideally we should regenerate a new scramble for this attempt, but it's not always possible. We could provide some leniency (for example, saying that if it was caught during the first minute, this is basically no information, so there is no need to regenerate a new scramble. This may not be true since a minute is already quite long, but may be true with a smaller window, like a few seconds).
If that's not possible, the only fair solution would be to cancel the attempt, but this could have quite huge consequences.

**Comment by Samuel-Baird** [comment]
Competitor should always get the full hour, they should not be penalized because of poor organization. 

If a future attempt it given out early then I think it’s acceptable to use that as the scramble (as long as all competitors receive it) ex if they do the scrambles in the order 1,3,2 it is fine.

**Comment by xsrvmy** [comment]
132 definitely does not work (scramble secrecy)

**Comment by alexmaasswca** [comment]
during FMC USA 2014, one of the locations accidentally gave out something like the 3rd scramble for the first attempt, and their results weren't dnfed or anything

**Comment by xsrvmy** [comment]
@alexmaasswca At a local competition though everyone starts discussion after they are done. The scramble secrecy regulation does not apply here (no competitor's area), and it doesn't seem reasonable to enforce it because of an organization error.

**Comment by alexmaasswca** [comment]
so this issue is asking if at the same comp location, a competitor gets a later scramble than everyone?

**Comment by xsrvmy** [comment]
@alexmaasswca Yes, and scramble secrecy is lost.
Also 2 hour rule.
