### ISSUE TITLE
Clarify judge/competitor responsibilities during attempt

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#82]
Ilkyoo is currently in charge of this.

**Comment by lgarron** [comment]
See Ilkyoo's suggested changes above. While the intention is good, I would like them to be simpler. Appositive clauses are not easy for international competitors to read, and not necessarily straightforward to translate.

**Comment by timhabermaas** [comment]
Is "ensures that the timer is on and reset" not sufficient? IMO this implies that the judge has to take the appropriate actions if it isn't already turned on/reset.
