### ISSUE TITLE
Introduce a "+2 Pass"

### ISSUE THREAD

**Issue by OrangeGreenCuber** [thewca/wca-regulations#820]
Sometimes, competitors make mistakes and do things that would get them a +2.  I think that there should be certain passes that competitors can get as a way to encourage them to
a) follow regulations at home
and
b) help staff.

I think this solves the problem of people not wanting to staff, because there could be a system where if you help staff, you can get a +2 card, which would be very desirable to competitors.

It also incentivizes competitors to follow regulations at home, making them better at following them in competition.  That being said, regulations not pertaining to +2s would not need to be followed.
Imagine what this could do to the 2x2 meta.  People who regularly staff would have increased odds at world record/national record/continental records.

It also helps make new competitors feel better if they accidentally +2.

Also, could we allow competitors "working off" +2s?  Like, they get a +2 and then can staff a few rounds and the +2 is gone?  I think this gets problematic since it could modify who advances to the next round and finals are often at the end of the day.

**Comment by maconard** [comment]
I'm not sure if this user thinks they're funny or if they somehow think their posts are reasonable, but we should consider muting/blocking them from posting issues.

**Comment by EdHollingdale** [comment]
I've seen many stupid suggestions. This is, by a significant margin, the stupidest. The regulations apply to everyone, you can't apply penalties selectively. This would result in gross abuse and introduce too much subjectivity.

**Comment by OrangeGreenCuber** [comment]
I'm really sorry that you guys think it's stupid.  I'm trying to help the problems of people not applying +2s at home and make staffing more fun for competitors and make +2s less devastating.  I know the regulations apply to everyone, and that's why everyone could earn a +2 pass.  I think overall, competitions would be more enjoyable and there would be less sadness while getting people more encouraged to staff.

I don't think this would be a "gross abuse of power".  We can always use more staff, and the people with the power to receive the pass is everyone.

Also, these aren't "posts", they're "issues".  I'm trying to be a proactive member of the WCA by fixing things that I find to be "issues" with the way WCA competitions are currently done.  I know people don't generally like change, but without change, the WCA will never be able to grow.

These ideas I know can sound silly, but I put a great deal of thought into these before making the issues I've made (hence, why I've only made 2 issues so far.  I only put my best work on here).  These happen to seem silly due to the fact that the change is potentially seen as "undesirable".  I assure you, that these issues are good enough for civil discussion.

**Comment by Samuel-Baird** [comment]
First idea can be discussed in #798 

The working off +2s is a fun idea and all and could definitely motivate people to staff but +2s are given for a reason and it kind of defeats their purpose :P

**Comment by alexmaasswca** [comment]
wow I wonder where this idea came from 🤔

**Comment by lgarron** [comment]
I believe this is a bad idea. The core goal of the Regulations is to ensure fair and equal conditions. This would go against that goal in a variety of ways. And while we want good incentives for judges/staff to do their jobs well, I don't think this idea is a useful way to do it.

The issue of waiving penalties is such a significant concern that we already specify:

> A7g++) CLARIFICATION Individual penalties cannot be waived for new competitors. A full extra attempt must be granted.

I don't think that this can be worked directly into an idea that we would actually want to adopt, so I'm going to close this issue now. We can always reopen it if there is a big benefit that I missed.
