### ISSUE TITLE
Allow competitions to reserve registration spots based on competitor experience 

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#822]
This is an idea motivated by trying to trying to support:
* WCA Mission — particularly the “more fun, under fair and equal conditions” part
* WCA Objectives particularly to build and sustain an inclusive community and to keep completions well regulated. 

Many of us have been to a competition largely populated with new competitors which has caused problems. Nowadays, registration in many parts of the world can fill up with newcomers well ahead of the competition — often weeks or months ahead of time, and it often leaves experienced competitors unable to compete while the competition is heavily saturated with newcomers. 

I don't want to assume that allowing experienced competitors only is necessarily better in this case, but I think it's clear that competitions do not run as well when newcomers are involved. Newer competitors are more likely to be unfamiliar with regulations and as a result may cause incidents, take more time to make calls on penalties, make unfair calls, etc. People may conclude "this sport is not organized or taken seriously enough”.  I think many speedcubers would agree that going to their first official first competition was a critical point in their development, having a poorly run competition may deter first time competitors from returning. 

In addition, there are situations where it is desirable to have many experienced competitors:
* Staff is overall more likely to be competent and will likely be able to handle situations better.
* Fewer incidents occur in which the cause is due to lack of familiarity of the regulations. 
* Competitors have a better sense of how competitors are run and as a result will be more likely to help to keep things running well. 
* Overall at large competitions the main objective is podiums or wins, watering down the amount of slower competitors who have no chance to podium will help the competition stay on time. 
* Builds a sense of familiarity and community (you see a group of the same competitors at the same competitions and know they will return to future competitions) 

So I'd like to propose that competitions are allowed to reserve a certain percentage of their spots for returning competitors. To keep this initial proposal simple, I'm imagining this:
* The competition announces that the competitor limit is P people, with X% reserved for returning competitors.
* If fewer than X% of registrants are returning, then the next returning competitor who signs up (or the the earliest on the waitlist) is always allowed to register. If the competition fills up and a returning competitor attempts to sign up they may be accepted if they have more experience (competitions) than other competitors, the competitor with the fewest comps will be dropped from registration. 

* Competitions with this policy should allow returning competitors to sign up at any point before the competition, including on the spot.

**Comment by Samuel-Baird** [comment]
I thought of this after seeing #819 and feeling as though it is unfair to experienced competitors. After weighing in I feel as though it will be better to give priority to experienced competitors even though it is unfair to new competitors but that overall it will provide a more controlled quality growth. Basically quality over quantity concept, if we have quality competitions with few newcomers I believe it will result in those newcomers staying in the community whereas currently many comps with large amounts of newcomers (and slightly worse competitions) end up having their competitors never return to speedcubing after 1-2 competitions. 

Currently about 55.8% of competitors have only been to 1 competition, 16.77% have been to 2 competitions, and 8.23% have been to 3. So about 80% of our competitors are only competing a few times and then many never compete after that. Of course some of those numbers are first time competitors who will continue to compete but many will not return. 
Source used to estimate competitor attendance percentages: https://pastebin.com/aXd3ENHk

Edit: another way to view it, about 27% of competitors have competed in 2019, most of the competitors who never competed again only competed 1-3 times.
https://pastebin.com/j3KVAqAg

**Comment by xsrvmy** [comment]
If we want to allow this type of reserves, we could allow each competition to have a combination of these:
- Reserves for new comers
- Reserves for returning competitors
- Reserves for competitors satisfying a specific qualification time/rank
- Reserves for competitors from the country of the competition (especially championships)
We should also allow the organizors to release reserves before the end of registration. Also there should probably be a requirement to release all reserves for at the door registration if that is a thing.

**Comment by Sixstringcal** [comment]
Should there also be a reserve on age?  I've found younger cubers are the most devastated when they are told they cannot register compared to older and more mature cubers.

**Comment by Jambrose777** [comment]
I hope that these snowballs off the original post show why they are all not great to inherit.

Allowing specific competitors to have preferential treatment based on factors outside their control (age, gender, race, nationality, experience) is not an acceptable thing that we should implement into our organization.

**Comment by ghost** [comment]
I don't really see any reason for this, as it's rare to have a comp with more than 30% newcomers, and in my experience, at comps I've organized which have had nearly 1/3 of the competitors be newcomers, and my rather agressive scheduling, there were still a fairly minor amount of incidents, and the comp didn't run behind schedule.

Also someone who is an experienced competitor should know how to find comps which have been announced quicky, so I don't see a reason why we have to reserve spaces for a competitor who is too lazy to take initiative to find a comp.

On a final note if I personally see it as a good thing that more people are being involved, even though the rates of people coming to a second, or third comp are fairly low, by intentionally stopping new competitors from competing at comps it's likely to just make those numbers decrease further.

**Comment by hanwu85** [comment]
There are some good points here, but I don't think we should limit the number of newcomers just because more new comers might result in a worse competition experience.   With good organizer, delegates or even fellow competitors, the competition could turn out to be a good one.

**Comment by xsrvmy** [comment]
I only said nationality because national championships. It shouldn't be used for anything else.

**Comment by Samuel-Baird** [comment]
People don’t seem to be a fan of the idea right now so I’m closing this.
