### ISSUE TITLE
Allow A7f to be more permissive

### ISSUE THREAD

**Issue by Sixstringcal** [thewca/wca-regulations#823]
A7f) When a competitor's score sheet for a round is complete, the judge delivers the score sheet to the score taker.

Currently the judge is the only one permitted by the regulations to deliver the score sheet to the score taker.  I'm not sure I've attended a competition where that has happened (outside of maybe a PBQ competition).  It's usually the runner taking the scoresheet to the score taker or to the scrambling table where the score taker picks up the score card from there.

I'm not the greatest with wording things like this, but I think that this should be changed to maybe something like:
A7f) When a competitor's score sheet for a round is complete, the score sheet is transported to the score taker or placed in a previously agreed upon location for the score taker to pick up.

**Comment by xsrvmy** [comment]
Technically the runner is a judge, so there is no problem there. I think the most important thing to communicate is that the competitor is not responsible for the scoresheet getting lost.

**Comment by Sixstringcal** [comment]
Hmm.  Looking through I don't see "runner" mentioned anywhere in the regs.  I think it's a useful 
I'd never equate a runner as a judge.  Additionally, it says "the judge" which (at least to me) implies the judge from that attempt, which at least in America (I know some other countries have the judges be runners as well, I just can't remember which ones) is very rarely the runner.

I also think that a runner should be defined in the regs.  But I guess that's a separate issue.

**Comment by hanwu85** [comment]
The regulations currently indicate that judges are _officials that can "run"_.  Therefore, in a runner type competition, I think you could say a running judge brings the puzzle and the competitor to a solving station where a sitting judge is available.  So technically speaking, a runner is a judge although _runner_ is not defined in the regulations.  It is just a term we use in competitions.

**Comment by Sixstringcal** [comment]
I don't think that changes the fact that it says "the judge" implying the judge who judged the attempt.

**Comment by EdHollingdale** [comment]
I think saying "the judge" does not imply it must be the same individual who was judging the final attempt. The judge is, in my interpretation, the individual performing the role of a judge as defined by the regulations - in this case, a runner.

I think we should be careful defining the role of runner. The pro of defining it is that the regulations will better reflect the actualities of competiton logistics in many regions. The downside is that many regions do not use runners, and it would be challenging writing a version of the regulations that both specified the roles of runners, while had them as completely optional.

**Comment by Sixstringcal** [comment]
@EdHollingdale , I think that problem could be solved through specifying that the judge can also perform all tasks of the runner.

**Comment by Ivan-Brigidano** [comment]
Although defining types of judges could be beneficial in some cases (fixed judge, runner, scrambler checker), it could be harmful in some competitions. In some small competitions the runner and the fixed judge are the same person.

I prefer to give the organizer freedom to organize judges as they consider. And as pointed by @EdHollingdale 
>I think saying "the judge" does not imply it must be the same individual who was judging the final attempt. The judge is, in my interpretation, the individual performing the role of a judge as defined by the regulations - in this case, a runner.

**Comment by alexmaasswca** [comment]
It is commonly the case in the northeast US that a runner delivers the completely finished scorecards back to the scrambling table, where it is placed in a cube cover that fills up with the completed scorecards, which are then given to data entry. I have never seen the judge actually go to the scoretaker/data entry directly after the scorecard is completed.

**Comment by dancing-jules** [comment]
@alexmaasswca, I've seen both. Sometimes the "return finished scorecards here" box is on the scrambling table, sometimes it's on the data entry table. Sometimes the two tables are so close it doesn't really matter anyway.
