### ISSUE TITLE
Puzzle covers for blind

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#825]
Currently the organizers supply the puzzle covers for competitors to use. This usually not and issue, but with 3bld there can be inconsistencies. For example, a round cover is slightly harder to list than a box cover. Heavier boxes and shorter boxes are harder to knock over.
I propose that competitors should have the option to bring their own cube covers for blindfolded.

Several notes:
- Covers need to be regulated (bad covers, cheating by writing on cover)
- What if a competition sponsor attempts to contradict this regulation?
- Is receive someone else's (or the default) cover grounds for an extra?

**Comment by EdHollingdale** [comment]
This would be a logistically challenging to manage and would slow down scrambling significantly. It would also reduce the amount of money competiton organisers can obtain from sponsors as they have less off a branding advantage (they cannot be assured their logo will appear in all solve videos). And speculating wildly you would also use use up more delegate resources checking covers for writing or hidden cameras (not that they would give you much of an advantage).

**Comment by xsrvmy** [comment]
Should there at least be a suggestion for what a cover should be like? ie. a light a tall paper box?
I don't think there is actually a problem with the sponsor covers. It's more that I have seen really short boxes being used before and those may take longer to lift for BLD.
