### ISSUE TITLE
3h2a clarification

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-regulations#826]
The 3h2a regulation has been found to be difficult to interpret.

> [3h2a](https://www.worldcubeassociation.org/regulations/#3h2a)) Puzzles with transparent parts. Exception: An overlay sticker (see [Regulation 3l](https://www.worldcubeassociation.org/regulations/#3l)).

It make a bit unclear if semi-transparent cubes with stickers are legal or not. The truth is that they aren’t legal but the regulation is not enough clear.

So there are two options:

1. Clarify that this cubes are not allowed.
2. Allow cubes to be transparent (see Issue #736 ).

**Comment by xsrvmy** [comment]
I don't see how 736 is relevant for stickered transparent cubes.
3h2a is under 3h2, so it only concerns stickerless cubes. Stickered transparent cubes are already disallowed by 3h for revealing extra information.

**Comment by Ivan-Brigidano** [comment]
I mean, both are similar Issues

**Comment by Ivan-Brigidano** [comment]
Closed per #832
