### ISSUE TITLE
Explicitly forbid alcohol and drugs

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#828]
#197 has already discussed this but I feel like it’s nice to create a new issue for it. 

The main issues brought up in #197 where that 2f and 2k3 already cover this and that it is not family friendly to specifically state that alcohol or drug use is not permitted. 

While 2f and 2k3 may cover this issue it does not always cover this issue.

2f Competitors must obey venue rules and conduct themselves in a considerate manner.

Some venues used for competitor are also commonly used for events where alcohol consumption (idk about drug use) is allowed. Also because a competitor is intoxicated it doesn’t necessarily mean they cannot or will not conduct themselves in a considerate manner. 

2k3 Behaves in a way that is unlawful, violent or indecent; or intentionally damages venue facilities or personal property within the venue.

Depending on the venue and it’s location it may be legal to drink or use drugs, competitors may not be violent, indecent or damage any property.

Now initially I thought that 2k3 on indecency could stop it but since indecency is subjective and different culturally I figured that even that could allow things to slide. 

Another point brought up in #197 was we shouldn’t explicitly state this in the regs to keep things “family friendly” I don’t see how explicitly stating “no drugs or alcohol” ruins family friendliness, we have regs about remaining dressed, not being violent but none about alcohol or drug use, which under current regs could be legal in some circumstances (and that’s not very family friendly) 

As for reasons to add this I don’t think I need to list any reasons as to why alcohol and drugs shouldn’t be permitted in competition :P

I would like to see something similar to this 
2k3a, 2k3+, 2f1, or 2f+

Competitors must not possess or be under the influence of alcohol, drugs or any controlled substances while in the competition venue. Exception: If the competitor can prove drug or substance is prescribed medication. At the discretion of the WCA Delegate, competitors may be disqualified from the competition.

**Comment by EdHollingdale** [comment]
I feel 2f and 2k3 cover the reason why you would want to forbid drugs and alcohol. If they are not disobeying venue rules or acting indecently/unlawfully then what is the issue? I don't want to disqualify everyone who has a beer with lunch and then comes back to the competiton (especially since this would impact me).

**Comment by Samuel-Baird** [comment]
> I feel 2f and 2k3 cover the reason why you would want to forbid drugs and alcohol. If they are not disobeying venue rules or acting indecently/unlawfully then what is the issue? I don't want to disqualify everyone who has a beer with lunch and then comes back to the competiton (especially since this would impact me).

For similar reasons why many places don’t allow drinking in public, it can lead to aggressiveness, fights, damage to property, etc. 

It’s mostly preventative 

It’s not going to cause any big problems to disallow people from doing things but it can definitely cause big problems by allowing them to do so. Yeah lots of people can be responsible with how they handle alcohol or drugs but plenty of people aren’t and it can lead them to do stupid stuff which they wouldn’t normally do.

**Comment by xsrvmy** [comment]
The biggest problem is: how do you define being under the influence and how do you enforce?
I would not be against banning opening a can of beer, but even banning alchohol cometely can cause problems (chocolates).

**Comment by zeecho** [comment]
> As for reasons to add this I don’t think I need to list any reasons as to why alcohol and drugs shouldn’t be permitted in competition :P

Actually, yes, I think you should list the reasons why you want to ban people from doing something legal and not detrimental to the competition.

Since we can already disqualify people doing illegal stuff or who behave in a way that is detrimental to the competition, you're basically trying to disqualify people who consume legal products you don't like and who have no impact whatsoever on the competition. In my opinion, this doesn't make sense at all. Yes, people under drug (alcohol included) can be aggressive, dumb or whatever but as long as they behave "normally", I totally don't see why we should do anything as we can already disqualify people who behave "in a way that is unlawful, violent or indecent".

**Comment by UnderwaterCuber** [comment]
Closing due to difficulty enforcing and that many people don’t want to give it up in order to prevent potential issues

**Comment by UnderwaterCuber** [comment]
Going to re-open discussion

**Comment by Ivan-Brigidano** [comment]
@UnderwaterCuber don't you think it's already covered by the Regulations as @zeecho said?

> Since we can already disqualify people doing illegal stuff or who behave in a way that is detrimental to the competition, you're basically trying to disqualify people who consume legal products you don't like and who have no impact whatsoever on the competition. In my opinion, this doesn't make sense at all. Yes, people under drug (alcohol included) can be aggressive, dumb or whatever but as long as they behave "normally", I totally don't see why we should do anything as we can already disqualify people who behave "in a way that is unlawful, violent or indecent".
