### ISSUE TITLE
Calculate statistics for 2020 Regulations 

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#831]
Several decisions should take into account stats. Here's a place to collect them.

- [ ] 3x3x3 with Feet: fraction of competitions and fraction of competitors
- [ ] Fraction of competitions with Gen 2 timers (this info is in Delegate reports)

**Comment by hanwu85** [comment]
What's the time period that we should take into account?

**Comment by lgarron** [comment]
> What's the time period that we should take into account?

For feet:

- All of 2018
- 2019 to date

**Comment by hanwu85** [comment]
For feet, 
Regarding fraction of competitions.
All of 2018 :  247/1154 = **21.4%**
2019 to 9/22 :  216/940 = **22.98%**

**Comment by Jambrose777** [comment]
This information can be requested to wrt via 1.4 of this motion: https://www.worldcubeassociation.org/documents/motions/10.2017.1%20-%20Results%20Team.pdf

If I recall correctly the first time we ran these statistics, there was a lot of other useful information to consider, so maybe we can dig that up and rerun the queries with the new data!
