### ISSUE TITLE
Chris Olson's 2x2x2 WR Inspection Time

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#84]
http://www.speedsolving.com/forum/showthread.php?44254

From video evidence, Chris Olson clearly received in between 15 and 17 seconds of inspection on one of his solves, because the judge was distracted and called "8 seconds" and "GO" (instead of "12 seconds") late. 

Had this been noticed during the competition, Chris could have been awarded an additional attempt ([11e](https://www.worldcubeassociation.org/regulations/#11e)), but now it's too late for that.

I believe that the regulations should state what happens when incidents that usually result in penalties aren't noticed until after the competition.

Suggestion:
11g) When video or photographic analysis prove that a competitor did not receive a penalty when he should have, he will receive the full penalty at the discretion of the WCA Board.

I know that the board already practices this, but I believe that it should be stated in the regulations so that people know that they're fair and consistent rulings.

**Comment by lgarron** [comment]
In general, the Board should always address incidents where a competitor
had an unfair advantage/disadvantage, which they mostly do.
This particular incident was mentioned in the Delegate report.

If we want a rule like this, I would suggest trying to phrase it more
generally. Something to the effect of obligating the Board/Delegate to
reevaluate a decision/result if interesting evidence comes up.

(Note that Delegates were originally not allowed to use video evidence at
competitions. This was partially to protect the delegates from an
overzealous barrage of post-hoc rulings.)

»Lucas Garron

**Comment by SAuroux** [comment]
Such a rule might force us to deal with way more cases as we are realistically able to deal with. I don't think a new regulation is neede here.
