### ISSUE TITLE
Clarify how to handle new Regulations going into effect during a competition/round

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#846]

**Comment by hanwu85** [comment]
I listed all the options I can think of here:

1.  Regulations of the first day should be applied for the whole competition.

2.  Regulations of the last day should be applied for the whole competition. 

3.  Events start at a day of the old Regulations should use the old ones for all rounds, while the events start at a day of the new Regulations should use the new ones for all rounds.

4.  Old Regulations should be used for all days before the new Regulations are in effect, while new Regulations should be used for the rest of the day regardless of events and rounds.

**Comment by Rouxles** [comment]
In my opinion, 1 is the best option, as it leads to the least amount of confusion for competitors.

**Comment by lgarron** [comment]
I agree that 1 is the least confusing. However, we also have:

> 9i2) All the results of a round are considered to take place on the last calendar date of the round. If a regional record is broken multiple times on the same calendar date, only the best result is recognized as breaking that regional record.

So I think it might sense to be consistent and go by the last calendar date of the competition (or of each round).

**Comment by EdHollingdale** [comment]
I think going by the last calendar date of the competition is best. Although we would need to be careful with timezones. E.g. if a western-US comp is on a Saturday, part of it will be on the Sunday for most of the world.

Going by the last calendar date of each round could be incredibly confusing. Hypothetically if two regulations changes come into effect, one to allow 20 seconds of inspection during pyraminx, and another to have rotations count as 3 moves during FMC. If Day 1 has pyraminx  and the first two attempts of fewest moves, and day 2 has the 3rd attempt for fewest moves, then part of the new regulations would be in (the FMC regs) but others would not (the pyraminx regs).

**Comment by timreyn** [comment]
Alternate proposal: avoid having new Regulations go into effect on days with competitions.

The vast majority of competitions are on weekends, and there not many competitions on Monday-Thursday each week.  From a cursory glance, it looks like there was only one week this year with a competition every day: the week beginning July 14.  Since competitions are announced a month in advance there should be plenty of time to select a day without a competition.

It's possible that 5 years from now this solution won't work.  But until then, it would make things simpler to just avoid this scenario.

**Comment by xsrvmy** [comment]
We need the same set of regs to apply all across the worl at the same time. Otherwise we will have problems if the regulations regarding record timeframe or round advancement changes.

**Comment by hanwu85** [comment]
I think "time" is not a major issue here.  The new regulation should start being applied at 0:00 (the time zone of each competition.)  Unless we are talking about a multi-place FMC competition...that might be a headache...
The issue here is if a competition is held in multi-day, and new Regulations become effective during the course of the competition.  (For example, an 2-day  competition is held on 12/31 and 1/1, and the new regulation kicks in on 1/1)

**Comment by xsrvmy** [comment]
@hanwu85 I'm thinkong about the regulatoon that prevents more than one WR on the same calendar date.

**Comment by Samuel-Baird** [comment]
Similar to Tim’s idea, you just disallow competitions to be held for a 2 day window (to account for time zones) and have reg changes implemented on the first day. As long as reg changes are on a weekday and announced at least a month in advance it shouldn’t cause any issues. 

Basically all competitors are treated the same and if none of them are competing :P this solution would also work long term

**Comment by xsrvmy** [comment]
@UnderwaterCuber what if regs come out on a national holiday in some country then (especially big cubingcountries like US and China)? It's better just to delay the regs by several days if anything happens

**Comment by Samuel-Baird** [comment]
> @UnderwaterCuber what if regs come out on a national holiday in some country then (especially big cubingcountries like US and China)? It's better just to delay the regs by several days if anything happens

I trust the WRC to make an thoughtful decision on when exactly to release the regs in order to minimize conflict.

**Comment by xsrvmy** [comment]
@UnderwaterCuber having regs come into effect on the first day after xxxx-xx-xx with no comps is a much easier way though. Or just pick the date in the last month before the release?

**Comment by Ivan-Brigidano** [comment]
Article 1.3 of the Announcement Criteria of the [WCRP](https://www.worldcubeassociation.org/documents/policies/external/Competition%20Requirements.pdf):

> The name must end with the year of the last day of the competition.

Following this logic, the Regulations that should be used on the competition are the ones that get applied on the last day on the competition.

**Comment by xsrvmy** [comment]
@Ivan-Brigidano This could potentially cause a situation where two simultaneous competition use different regs, and if certain regs get changed there is a problem (eg. the regulation on when a regional record is counted)
