### ISSUE TITLE
Proposal: Create a non-championship tier

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#857]
This is a specific proposal for the idea of using tiers (#758).

I have spent a lot of time and energy in the past year listening to feedback about the removal of 3x3x3 with Feet (#652). My main takeaway is not that we need to make the right binary decision between keeping or removing the event, but that we need a better way to add or demote events without making this feel like a disruptive change for significant parts of the community. Many competitors would like to see new events (the WRC frequently gets requests for this), but it's difficult to add or remove an event unless we try a new approach.

I would like to propose a new "Tier 2" of events with the following restrictions:

- Tier 2 events are not expected to be held at every championship.
- Tier 2 events are limited to 2 rounds.

This allows competitors to compete and obtain regional records, while avoiding logistics and optics that the issues that come with holding an event at championships.

This tier would contain events as follows:

- Tier 2 initially contains only 3x3x3 with Feet.
- There is no plan to move other existing events into Tier 2 initially.
- New events are added to Tier 2, possibly with an evaluation period.

This is the best compromise idea that I have at this moment, and we have mild consensus in within the WRC that this could be a reasonable option. I would like to hear from competitors and organizers if this is sufficient to address their biggest concerns, or if it leaves everyone too unhappy.

**Comment by Jambrose777** [comment]
I can understand the want to not expect these events at championships, however, what would be the reasons to restrict the number of rounds these events may have? What benefits does limting rounds have for WCA?

**Comment by xsrvmy** [comment]
Would/should the non-championship tier apply to World Champs?
Also, in regards to stats, how many comps have ever had at least 3 rounds of feet?

**Comment by Tehzeebkohli** [comment]
How would this benefit the cubing community?? 
If there is a need for tier 2, new events can be added to it. 
But demoting 3x3 WF to tier 2??? 
It’s definitely better than removing it but I don’t understand why the kids who’ve spent hours on with feet should be made to feel that they are not part of the “elite events” 
I’m pretty disappointed to be honest with the way this is being handled. 
I really expected a lot more compassion, understanding and inclusivity for the cubing community from the WRC

**Comment by Tehzeebkohli** [comment]
How can an event which is alive and kicking be demoted to tier 2?? 
The world record was broken just sometime ago. The continental records are being broken frequently.
May I please have an explanation. It would be much appreciated @lgarron 
Every single CF poll is in favour of feet over clock. Not that I’m against clock.
 But isn’t this a community where we care about each other or am I mistaken??

**Comment by andrewtyberg** [comment]
I fully support having a second lower tier of events. Tier 2 events, as you stated, would be limited to 2 rounds and, I believe, should be required to NOT be held at major championships. Major championships (ie worlds, continental) should hold every tier 1 event and no tier 2 events.

I would be in favor of this for feet and clock. It's clear that the community is divided on what to do about feet. I think demoting, but not removing, feet would be a nice balance. Clock should be in this tier too, since it isn't a twisty puzzle and there are numerous other problems with the event.

I would also personally be in favor of moving 7x7 to tier 2. I know this is not something that will happen anytime soon, but I feel that it is too similar to 6x6 to remain a tier 1 event. Another event that I believe could be moved down is 5BLD, due to the immense amount of time and energy required, the similarity to 4BLD, and the very high DNF rate. However, as I have not done 5BLD, I will not say more about this.

Eventually new events could be added to tier 2. Depending on their popularity, they could be promoted to tier 1, remain at tier 2, or be removed entirely.

**Comment by Tehzeebkohli** [comment]
I wonder why is only feet being singled out for tier 2. Not that I would want any event to be demoted but I would really like an explanation for this. 
Seeing the various problems with clock pins etc  it seems clock has a lot more issues than feet. Only issue very few people seem to have with feet is that it’s yucky/ gross. 
Don’t get me wrong... I’m not for clock Or any event being demoted to tier 2, even though clock is much harder to organise.  
I would really appreciate an explanation for this 
@lgarron

**Comment by xsrvmy** [comment]
> I fully support having a second lower tier of events. Tier 2 events, as you stated, would be limited to 2 rounds and, I believe, should be required to NOT be held at major championships. Major championships (ie worlds, continental) should hold every tier 1 event and no tier 2 events.

There should be absolutely no reason why this should happen. A round limit artificially hurts the event for no reason. A championship is just a competition with a special status. Championships are allowed to have unofficial events, so why can a championship not hold certain events? It just doesn't make sense.

**Comment by AlexKatyukov** [comment]
The feet event is disgusting, IMHO. I know a lot of cubers who think similar and wait for removal of 333ft. And I understand that some community members want to compete in this event, train it etc. And anyway, information about possible 3x3x3 With Feet removal was published a year ago. A lot of time to upgrade skills and make forever record.
If 333ft will be removed and no second tier added. There is [funcubing.org](https://funcubing.org). I'm not so like it, but it is the best place to hold removed events and test event. We use it very wide in Russia. 
What about second tier at WCA? Don't know. Maybe it's a good solution.

**Comment by xsrvmy** [comment]
About 3x3wf removal, or any event removal in general, my personal opinion is that the removal should be announced well in advance. I don't have a particular problem with this tier 2 idea as long as no restrictions are being placed on the event itself. However if tier 2 events are also the ones subject to removal, then there should be a minimum time that the event has to stay in tier 2 before it can be removed. I personal stance on this has been 2 years (1 year for feet, but only because this whole savefeet thing has been going on for a year).

**Comment by alexmaasswca** [comment]
If this means feet will not be removed, then I'm for making feet a tier 2 event. 
It is kind of insulting to feet solvers if you say feet is basically a lower class event though, does it really need to be labeled negatively?

**Comment by Tehzeebkohli** [comment]
@alexmaasswca I absolutely agree. The world record was broken again just a few hours ago. This is really really sad.
Tier 2 can start for new events but to demote an event which is clearly alive to tier 2 is absolutely insulting to say the least. 
But if moving it to tier 2 means passionate feet solvers can still participate in their fav event then I guess we will have to be grateful for the crumbs that we are being served. 
I’m extremely disappointed with how this is being handled.

**Comment by jamesquinn1** [comment]
I'm in favor of moving feet to tier 2 over removing it far and away, but I believe these conditions are not the best approach.

I believe that the conditions should be:
-Feet should not have to be held at WCA Championships (continentals+worlds), but those organizers can choose to have it if they wish. (Could even be a very small one round thing with 10 competitors, which wouldn't be approved for other events but could for tier 2 events)
-There is no limit on the amount of rounds that may be held on the event.
-The event is listed on the events list as it is now, and the note about it being a tier 2 event would be explained somewhere else (possibly in a document about events), with also explaining the requirement for tier 1 events to be held at WCA Championships. This would also open the door to setting requirements on # of rounds of other events for WCA Championships quite easily, which I believe would be a good thing.
-The event is listed on competition pages as it is now.
-The event appears on the results page as it is now.

**Comment by cubewhiz** [comment]
I don't think tiered events as described here actually provide any benefit to the community. To me, it feels like a half-baked compromise to keep the people who don't want 3x3x3 with feet to be removed happy. I still believe 3x3x3 with feet needs to go and the decision of tiered events vs. other options to add/remove events should be deferred to at least next year.

**Comment by dancing-jules** [comment]
I strongly disagree with @andrewtyberg; I think Championships should have the option to hold tier2 events if they want to. And if there is a round limit, I'd set it to 3.

**Comment by jamesquinn1** [comment]
@cubewhiz Why do you describe it in such bad terms? It seems to be the best compromise between the two sides, and considering how nobody has been happy with the past year of debate, it seems to be the best option.

**Comment by Tehzeebkohli** [comment]
The ideal situation would be to keep it as it is. I can understand if an event is dead or not progressing or some major issues then maybe some stance can be taken WITH A COMMUNITY POLL. 
But even the people who dislike 3x3 with feet can never say this event is not ALIVE AND BEGGING TO STAY. 
After a year of #savefeet taking over the CF polls and the amount of feet rounds we’ve witnessed and records being broken frequently, this tier 2 decision itself seems like their voices weren’t heard. 
But if being in Tier 2 means that with feet can stay, then so be it. 
Passionate feet solvers may not care about tier 1 or tier 2. They want to do what they love and that’s incredible strength of character. 
But I agree with @jamesquinn1 that it should be held at championships and should show as an event the way it is now as well as the results.

**Comment by Samuel-Baird** [comment]
So currently with Tier 2 events not being expected to be held at every championship I don't think there will be much change to what we currently have. Currently there is no requirement for championships to hold all events, the reason they hold all events is so each event can have a champion and so that the angry mobs don't get them :P If feet were to be demoted to tier 2 I would imagine people would still continue to hold it at championships for the exact same reasons they have already been holding it. 

Just like the expectation to be held at every championship I feel limiting it to two rounds won't change much. Worlds 2019 had 2 rounds of feet while US nationals 2019 had one. I would actually be interested to see how many competitions have even gotten 3 or 4 rounds. 

In the end I feel like this system fails to do almost anything. If the problems with feet are big enough for removal then this system still keeps 99% of those problems, I would like to see it removed and for feet to be kept as an event, to remove feet as an event entirely and not add this tier system, or to change the tier system to be a bit harsher on events (perhaps removing championship titles? disallowing them from championships?)

**Comment by Jambrose777** [comment]
FYI, totals of number of rounds per event + competition with the most recent developer export:

All Years:

|eventId|1 round|2 rounds|3 rounds|4 rounds
|--|--|--|--|--|
|333|54|882|4905|266
|222|696|2925|1747|34
|444|2056|2715|615|13
|555|2572|1416|193|4
|666|1837|400|14|
|777|1784|371|16|
|333bf|3217|1342|96|
|333fm|1860|70|5|
|333oh|1597|2847|663|14
|333ft|1262|226|12|
|clock|1499|371|43|
|minx|2330|801|54|
|pyram|1575|2486|652|18
|skewb|1152|1647|333|5
|sq1|2111|887|58|
|444bf|1536|17||
|555bf|1167|7||
|333mbf|1838|4||

2018 and 2019 only:

|eventId|1 round|2 rounds|3 rounds|4 rounds
|--|--|--|--|--|
|333|15|241|1630|100
|222|136|1020|566|17
|444|551|983|203|3
|555|726|515|64|
|666|607|195|7|
|777|584|182|6|
|333bf|853|472|52|
|333fm|522|35|5|
|333oh|418|948|172|4
|333ft|362|99|10|
|clock|451|211|21|
|minx|762|354|32|
|pyram|313|1073|253|9
|skewb|408|819|158|5
|sq1|624|393|36|
|444bf|454|14||
|555bf|364|7||
|333mbf|529|1||

`SELECT eventId, numOfRounds, COUNT(*) total FROM (SELECT COUNT(DISTINCT roundTypeId) as numOfRounds, eventId FROM Results GROUP BY competitionId, eventId) a GROUP BY numOfRounds, eventId ORDER BY eventId, numOfRounds LIMIT 100;`
`SELECT eventId, numOfRounds, COUNT(*) total FROM (SELECT COUNT(DISTINCT roundTypeId) as numOfRounds, eventId FROM Results WHERE RIGHT(competitionId, 4) IN ('2019', '2018') GROUP BY competitionId, eventId) a GROUP BY numOfRounds, eventId ORDER BY eventId, numOfRounds LIMIT 100; `

**Comment by c-goodyear** [comment]
Given the amount of controversy this particular issue has caused/is causing has the WRC considered the fact that allowing events of the Continental/World championships may lead to competitors organizing boycotts?

This would lead to making organizing teams of larger competitions pressured into holding the tier 2 events anyway to appease the group who wants feet to remain a WCA-recognized event. The blame for continental and world championships not holding feet is then shifted on to the organizers because WRC have the excuse of "It's allowable by the regulations to have the event, but the organizing team chose not to". Personally I don't think that is productive to make the organization of competitions with such a scale any more difficult than they need to be. Amount of rounds and number/percent proceeding are already difficult enough to plan and schedule for, why add an entire event to this process as well?

In fact, one of the biggest advantages in my opinion of making a tier 2 system would be that those events are explicitly *not* held at Continental and World champs. This frees up time in schedules which is becoming desperately needed with the growth curve in registered speedcubers.

**Comment by jamesquinn1** [comment]
I don't think anyone boycotted US Nationals in the multiple years it didn't have feet.

**Comment by c-goodyear** [comment]
> Continental/World championships

**Comment by EdHollingdale** [comment]
@c-goodyear speaking from experience, organisers of major competitions learn quickly to ignore silly people on social media making complaints and missing the big picture. The only concern would be if the budget were to be severely impacted by large boycotts.

Even if supporters of feet might like to feel differently, the event is - numerically speaking - incredibly unpopular. A quick look at rankings shows only 3025 persons with a single in the event. This is ~2.5% of all registered speedcubers! And a smaller fraction of this group is actually passionate about it. I do not feel that a major championship would be severely impacted by a boycott of a few individuals. And although not a continental/world championship, US Nationals is a "major competition" and evidence there suggests no meaningful impact from not holding feet.

**Comment by c-goodyear** [comment]
How many who attend C/W championships have a single in feet though? your ~2.5% is quite misleading in this regard.

**Comment by jamesquinn1** [comment]
Regardless, people wouldn't boycott. I've asked a few people (all those who are passionate about feet) and none have said they would boycott.

**Comment by Samuel-Baird** [comment]
I wouldn’t imagine there being any boycotting but there would certainly be a lot of uproar about feet not being held, especially with feet being at its peak right now. We have definitely seen a lot of angry people with the announcement of removing feet as an event and will almost certainly have that carry over to the event not being held at large competitions. Organizers would definitely receive large amounts of pressure to hold it. I definitely think that if tier 2 is created then events in it will not be able to be held at championships.

**Comment by JackLove314** [comment]
I think 3x3x3 With Feet should remain an official event alongside all the other events. If a tier system was to be created and 3x3x3 With Feet was to be classed as a tier 2 event then I would recommend adding 7x7x7 Cube and 5x5x5 Blindfolded to it. The logic behind this is in tier 1 you have one event with a restriction on how you can apply moves to the cube (3x3x3 One-Handed). 6x6x6 Cube and 7x7x7 Cube are pretty similar so you have 6x6x6 Cube in tier 1. 4x4x4 Blindfolded and 5x5x5 Blindfolded are pretty similar so you have 4x4x4 blindfolded in tier 1. Major championships would be restricted to tier 1 events. This removes the problem of trying to fit in all 18 events over a few days. Personally I would prefer 3x3x3 With Feet to remain an official event alongside all the other events but if it was to be added to tier 2 then I would suggest the changes I described earlier.

**Comment by Samuel-Baird** [comment]
> I think 3x3x3 With Feet should remain an official event alongside all the other events. If a tier system was to be created and 3x3x3 With Feet was to be classed as a tier 2 event then I would recommend adding 7x7x7 Cube and 5x5x5 Blindfolded to it. The logic behind this is in tier 1 you have one event with a restriction on how you can apply moves to the cube (3x3x3 One-Handed). 6x6x6 Cube and 7x7x7 Cube are pretty similar so you have 6x6x6 Cube in tier 1. 4x4x4 Blindfolded and 5x5x5 Blindfolded are pretty similar so you have 4x4x4 blindfolded in tier 1. Major championships would be restricted to tier 1 events. This removes the problem of trying to fit in all 18 events over a few days. Personally I would prefer 3x3x3 With Feet to remain an official event alongside all the other events but if it was to be added to tier 2 then I would suggest the changes I described earlier.

The logic behind tier 2 was they were going to remove feet and there were a bunch of people angry about it so instead of actually removing it they made a system that’s supposed to cater to everyone. (It doesn’t really change almost anything though)

**Comment by Jambrose777** [comment]
If the us national championship 2018 didn’t hold feet, I’m 100% positive there would have been a second comeptition held the day before in a close location holding just feet and crowning a feet national champion. It’s not a boycott, but a pretty close way to make the other organizers look bad.

**Comment by jamesquinn1** [comment]
That actually sounds like a decent solution IMO. It allows organizers to hold what they want to hold, and still lets dedicated competitiors compete for a title.

**Comment by ccbaird** [comment]
As a competitor: I want to compete in Feet, and I will take any opportunity to do so. Relegating Feet to unofficial or second-class status is silly and petty. Second-class is better than unofficial, but still petty. 

As an organizer: I will organize competitions with Feet. If it’s not recognized as an official event it will take time and resources away from official events. 

Editing to add: limiting to 2 rounds is ridiculous. There are already limits on the number of rounds based on the number of competitors, those limits are reasonable. If enough people want to compete in an event to meet the requirements for subsequent rounds then the event shouldn’t be artificially limited on the basis that people evidently not at that competition don’t like that particular event.

**Comment by 2013SUCH02** [comment]
Why 3x3 with feet still very few people will attend Comps?
1. Ao3 Change to average of 5
2.Must organizers provide Stacks timer and mat,so many organizers won’t holding 333 FT. Why not our competitors using ourself stacks mat?
I am very sad😔

**Comment by danielA757** [comment]
I suggest moving tier 2 events to the SEE association, just like Feet has been moved to SEE. The events can be monitored on SEE, and the WRC can evaluate if any SEE event should be added to WCA based on popularity/incident reports, or if WCA events should be moved to SEE (*cough* Rubik's Clock *cough*).
https://speedcubingextraevents.org/Events

**Comment by cubewhiz** [comment]
> I suggest moving tier 2 events to the SEE association, just like Feet has been moved to SEE. The events can be monitored on SEE, and the WRC can evaluate if any SEE event should be added to WCA based on popularity/incident reports, or if WCA events should be moved to SEE (_cough_ Rubik's Clock _cough_).
> https://speedcubingextraevents.org/Events

The WCA has no affiliation with SEE. To proceed with a plan like this, a proper collaboration would need to be coordinated. Preferably, we would monitor and track the top candidate events internally.

**Comment by ccbaird** [comment]
I’ve been thinking about this, and I think I have a reasonable proposal that addresses the shortcomings of a tier system as previously proposed:

**Tier 1:**
- 3x3 Speedsolve
- 3x3 Blindfolded (possibly tier 2a or 2b)

Restrictions:
- All championships must hold all tier 1 events.
- No restrictions on number of rounds beyond the minimum competitor requirements for subsequent rounds. 
- The final round at any championship must use a single scramble set. 

Reasons:
 - These events, especially 3x3 Speedsolve, are the cornerstone events of the WCA

**Tier 2a:**
- 2x2
- Clock
- Pyraminx
- Skewb
- Square-1
- 3x3 Blindfolded (possibly)

Restrictions:
- No tier 2a event may include fewer rounds than any tier 2b event at a championship. 
- No further restrictions on rounds or inclusion beyond the minimum competitor requirements for subsequent rounds. 
- The final round at any championship must use a single scramble set.
- If any competition has multiple rounds of a tier 2a event the final round should use a single scramble set. 

Reasons:
- Heavily luck- or scramble-dependent events 

**Tier 2b:**
- 4x4
- 5x5
- 6x6
- 7x7
- 3x3 One Handed
- 3x3 With Feet
- Megaminx
- 4x4 Blindfolded
- 5x5 Blindfolded
- 3x3 Multiple Blindfolded
- 3x3 Blindfolded (possibly)

Restrictions:
- No tier 2b event may include more rounds than any tier 2a event at a championship. 
- No further restrictions on rounds or inclusion beyond the minimum competitor requirements for subsequent rounds. 

Reasons:
- Not heavily luck- or scramble-dependent events. 

**Tier 2c:**
- FMC

Restrictions: 
- No restrictions on rounds or inclusion beyond the minimum competitor requirements for subsequent rounds.
- All competitors at a competition must use the same scramble sets

Reasons:
- Heavily luck- or scramble-dependent for records, but if all competitors use the same scramble then no competitor has an advantage over any other. 
- Unlike tier 2a events, it is feasible to allow all competitors to use the same scramble for all rounds.

**Comment by xsrvmy** [comment]
Two big objections:
- While I think a tier like this works for worlds, popularity of events in different parts of the world may be different. Having a tier system globally with round restrictions may not agree with what people locally want.
- Requiring  the same scramble set for most of the 2b events would require non-competitors to scramble for the first group. Also, rounds over 2 hours exist.

**Comment by ccbaird** [comment]
> Two big objections:
> 
> * While I think a tier like this works for worlds, popularity of events in different parts of the world may be different. Having a tier system globally with round restrictions may not agree with what people locally want.

The round restrictions I proposed are based on the element of chance in the result, not popularity. 

> * Requiring  the same scramble set for most of the 2b events would require non-competitors to scramble for the first group. Also, rounds over 2 hours exist.

I suggested the same scramble set for the final round of tier 1 and tier 2a events, not tier 2b. Rounds prior to the final round would not require a single scramble set, and final rounds over 2 hours would have to be an extremely rare occurrence that would probably justify an exception.

**Comment by xsrvmy** [comment]
Sorry I missed that the scramble requirement was for 2c not 2b lol
Actually if the difference is not due to populatrity, then it makes even less sense to require more rounds of 2a events. What if only 7 people show up to pyra for example? Is 4x4 now restricted to 1 round as well?

**Comment by ccbaird** [comment]
>What if only 7 people show up to pyra for example? Is 4x4 now restricted to 1 round as well?

Round restrictions as I have suggested apply only to championships, where there will almost certainly be enough people to have at least 3 rounds of every event.

**Comment by xsrvmy** [comment]
Small national champs though
And continental/world champs probably probably shouldn't have a reg specifically just for them.
