### ISSUE TITLE
Visual Barrier requirements for 2020

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#858]
The WRC is aiming for two changes for 2020. From #856.

# Scramble Table

- A visual barrier is required between the Competitors Area and scramble table.
  - Pro: This prevents opportunistic cheating while dropping off puzzles or waiting.
  - Con: This is extra work for the organizers.
    - Counterpoint: The WRC has been collecting venue photos to understand how practical this is. Many organizers already do this, and have found affordable solutions that could be adopted elsewhere.
  - Con: This does not prevent the competitor from peeking at other competitors when they are on the stage for their attempt.
    - Counterpoint: In an ideal world, we would do more to prevent that. However, isolating the scramble table is the most practical and useful step we can take right now.

# Solving Stations

- A visual barrier is recommended between the Competitors Area and the solving stations.
  - This is similar to the visual barrier for the scramble table. Many major champions already do this.

Off the top of my mind, I'm aware of the following solutions so far:

- Venue walls (e.g. a different room, or a separated section of the room).
- Large portable walls or posters.
- Cardboard dividers placed around scramble table.
  - In cases where isolating one side isn't enough, I've believe I've heard of puzzles passed by the side, over the divider, or through holes in the cardboard.
- Cloth draped over a bar suspended between two stands.

I think any of these should be allowed (please let use know if you know of more!), as long as competitors can't see the puzzles while they're scrambled or transported.

**Comment by xsrvmy** [comment]
The PR for this mentions that the scrambler needs to be isolated as well. Is that necessary? Isn't visually separating puzzles and the scramble algorithm itself enough?
Also what should happen if the barrier is knocked over?

**Comment by alexmaasswca** [comment]
Different room would slow down the competition a ton, depending on where the room is.
Cardboard dividers are extremely cheap, so that minimum I think is fair.

**Comment by aneurinhunt** [comment]
In New Zealand we have a cardboard barrier that can be put up around the scramble table, it not always used since transporting it isn't always possible but some kind of barrier is made anyway. Here is an example of it https://youtu.be/AgYM7mLQLfo?t=54. Something like that is enough and should be a requirement. The competitor should not be able to see the scrambles.  

For solving stations this is a lot harder to implement and is venue dependent.

**Comment by EdHollingdale** [comment]
I think having visual barriers is good and we should move towards enforcing them, but Delegates need a few more examples of what is and isn't of sufficient quality. I also have a couple of concerns about the wording of the current PR. This is meant to mean the scramble table is visually isolated from the competitor waiting area, however I don't think this is what the current wording says. I will copy some of what I sent to the WRC:

> I am also concerned with the wording of the proposed PR, which actually says “The organization team must ensure that scramblers, scramble sequences, and partially/fully scrambled puzzles are visually isolated from competitors”. This does not actually say that we now require a visual barrier between the competitors area and the scramble table - if we want that we should say it. It actually says “the organisation team must ensure … partially/fully scrambled puzzles are visually isolated from competitors”. Does this mean competitors should be blindfolded until they begin inspection, lest they see a partially unscrambled puzzle at the station next to theirs?

Obviously the last sentence is exaggeration, but we should reword the PR to actually implement what we want to!

**Comment by Sixstringcal** [comment]
I'm not for the required storage of something like this and I'm not for repurchasing them frequently.  Obviously we should make an effort to not have scrambles visible, but if they're behind a laptop in the corner of a room not near the competitors with something small to cover other areas, I don't think it's an issue.  If a competitor wanted to see that much or more, they'd look at someone solving, which is generally possible in the competitor waiting area.  I don't want to store more than I have to, especially since I have to store all of the Utah equipment in my bedroom while I'm living with my parents.

**Comment by cubewhiz** [comment]
I'd prefer to keep these as recommendations for now as I am not convinced that all competitions could implement this at the start of 2020 without a significant increase in overhead for some organizational teams.

**Comment by lgarron** [comment]
> I'm not for the required storage of something like this and I'm not for repurchasing them frequently.

The issue of storage is a good aspect that isn't covered in the points at the top of this issue. I know that US Nationals has used USPS shipping boxes in the past because it was easy to procure a reasonable number of them for free/low cost. Shipping boxes are also available from some places. If something like this is sufficiently accessible at most locations, it would be an alternative to storage.

> I'd prefer to keep these as recommendations for now as I am not convinced that all competitions could implement this at the start of 2020 without a significant increase in overhead for some organizational teams.

Making this a recommendation was already an indication that organizers should be doing this, and I'm concerned that we won't really make progress until the requirement comes into effect.
(For example, I'm seeing some of this happen with scramble signatures.)

What would you think of a requirement with a grace period of allowing pre-approved exceptions?
e.g. the Delegate would have to contact (some subset of WCAT/WRC/WQAC) and explain why this is impractical for the organizers at this venue. This requires only a few extra emails, and gives us a very clear picture of what specific resource issues we need to address before making it a hard requirement.

**Comment by Laura-O** [comment]
> Making this a recommendation was already an indication that organizers should be doing this, and I'm concerned that we won't really make progress until the requirement comes into effect.
> (For example, I'm seeing some of this happen with scramble signatures.)

Source?
My impression is that most Delegates already use scramble signatures.

**Comment by lgarron** [comment]
> My impression is that most Delegates already use scramble signatures.

I've observed competitions on two continents not using scramble signatures because they haven't upgraded to a score card program that includes a field for it.

I've also had one Delegate confide in me that they're explicitly not planning to use scramble signatures at every comp until it becomes a requirement.

Based on Delegate reports I also have a general impression that this is more widespread, but these are particular cases I remember.

**Comment by Samuel-Baird** [comment]
> The WRC is aiming for two changes for 2020. From #856.
> 
> # Scramble Table
> * A visual barrier is required between the Competitors Area and scramble table.
>   
>   * Pro: This prevents opportunistic cheating while dropping off puzzles or waiting.
>   * Con: This is extra work for the organizers.
>     
>     * Counterpoint: The WRC has been collecting venue photos to understand how practical this is. Many organizers already do this, and have found affordable solutions that could be adopted elsewhere.
>   * Con: This does not prevent the competitor from peeking at other competitors when they are on the stage for their attempt.
>     
>     * Counterpoint: In an ideal world, we would do more to prevent that. However, isolating the scramble table is the most practical and useful step we can take right now.
> 
> # Solving Stations
> * A visual barrier is recommended between the Competitors Area and the solving stations.
>   
>   * This is similar to the visual barrier for the scramble table. Many major champions already do this.
> 
> Off the top of my mind, I'm aware of the following solutions so far:
> 
> * Venue walls (e.g. a different room, or a separated section of the room).
> * Large portable walls or posters.
> * Cardboard dividers placed around scramble table.
>   
>   * In cases where isolating one side isn't enough, I've believe I've heard of puzzles passed by the side, over the divider, or through holes in the cardboard.
> * Cloth draped over a bar suspended between two stands.
> 
> I think any of these should be allowed (please let use know if you know of more!), as long as competitors can't see the puzzles while they're scrambled or transported.

The wording implies you have to visually isolate the entire table, is that the intention or is it to just isolate the cubes and the scrambles?

**Comment by xsrvmy** [comment]
Is there any reason not to continue discussing this for the next reg change?

**Comment by Ivan-Brigidano** [comment]
> Is there any reason not to continue discussing this for the next reg change?

The WRC has discussed this topic with the WQAC. We finally concluded that this should be better to be an independent WQAC policy/document/guide.
