### ISSUE TITLE
Require the competitor to finish signing (not just for the judge to finish signing) before the competitor may reset the timer.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#859]
I'm not sure we have an issue for this yet, so I'm filing a separate one.

**Comment by xsrvmy** [comment]
What if the judge resets the timer before the competitor is able to sign?

**Comment by Samuel-Baird** [comment]
> What if the judge resets the timer before the competitor is able to sign?

Extra

**Comment by xsrvmy** [comment]
That doesn't directly follow from the regulation so it falls under an incident, and I do no think giving an extra would be fair sportsmanship (especially if there is any other evidence like video)

**Comment by lgarron** [comment]
> > What if the judge resets the timer before the competitor is able to sign?
> 
> Extra

Indeed, I have yet to see a good general way to deal with judge mistakes: #1 

If there is strong evidence of the time and an extra is not available, I believe we usually let it stand — we try not to punish competitors if it was not their mistake.

**Comment by xsrvmy** [comment]
@lgarron What if there is an extra available but also there is video? I don't think it's fair sportsmanship to take the extra inthis case either.
