### ISSUE TITLE
Introduce a list of potential new events, with a plan to hold more "unofficial" events and evaluate them for official status.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#861]
I'm breaking this out from #856, since we don't have an issue specifically for it.

We haven't officially solicited the community for what new events they want, but I think we should — and then we should encourage holding the ones that are most popular and practical. We have questions on the draft community survey dedicated to this.

**Comment by casiku** [comment]
Unofficial events are already being held at many competitions, but they don't have many competitors. The most popular is TBLD, but it's also the most difficult to introduce as an official event. People don't want unofficial events. Don't add or remove official events.

**Comment by aneurinhunt** [comment]
Having a better way to keep track of unofficial results is needed for this. Like the old cubing.com site had. That way you know how frequently there are held and how many compete.

What events would be considered for this? How would you make a list?

**Comment by cubewhiz** [comment]
If someone decided to keep track of unofficial results in some place (I do not think it should be on the WCA website), it could encourage others to hold events unofficially. This is currently the best pathway to showing that there is a demand to add new events.

**Comment by Jambrose777** [comment]
> If someone decided to keep track of unofficial results in some place (I do not think it should be on the WCA website), it could encourage others to hold events unofficially. This is currently the best pathway to showing that there is a demand to add new events.

This has been done multiple times (all Kilominx results were stored of about 1 1/2 years and then the event was rejected for official status, which caused loss of interested. Now we have https://funcubing.org/ which most people don't know about)

**Comment by aneurinhunt** [comment]
> If someone decided to keep track of unofficial results in some place (I do not think it should be on the WCA website), it could encourage others to hold events unofficially. This is currently the best pathway to showing that there is a demand to add new events.

A semi-official or at least recommended place be a good solution to centralise these results. Having a set of requirements in order for new to be considered for official status could help with people wanting to actually hold unofficial events more. 

> > If someone decided to keep track of unofficial results in some place (I do not think it should be on the WCA website), it could encourage others to hold events unofficially. This is currently the best pathway to showing that there is a demand to add new events.
> 
> This has been done multiple times (all Kilominx results were stored of about 1 1/2 years and then the event was rejected for official status, which caused loss of interested. Now we have https://funcubing.org/ which most people don't know about)

This could be used as the recommended spot.

**Comment by ccbaird** [comment]
If Feet is removed, would it then be eligible for consideration as a potential new event?

I would also like to see curvy copter somewhere down the road: it’s just a different type of puzzle than anything we have now. I don’t think it’s quite ready, but in a few years possibly.
