### ISSUE TITLE
FMC Facebook group poll is heavily against the WRC's proposal to remove rotations and wide moves from FMC

### ISSUE THREAD

**Issue by alexmaasswca** [thewca/wca-regulations#862]
![image](https://user-images.githubusercontent.com/48773372/66709803-7dbd7d80-ed39-11e9-929b-58a26a4f19e0.png)
![image](https://user-images.githubusercontent.com/48773372/66709838-0a683b80-ed3a-11e9-9226-75841b2ee89c.png)
This shows that obviously the changes proposed by the WRC should not be implemented.

**Comment by lgarron** [comment]
Thank you for helping get this feedback!

Could you possible help determine the rough response population of this survey, e.g. geographical distribution, experience competing, and experience organizing FMC?

**Comment by lgarron** [comment]
Also, it's alright to file new issues, but given that we have an active issue for this topic, I'm going to close it in favor of continuing at #757!
