### ISSUE TITLE
Clarify if A1c applies to FMC

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#867]
I recently saw someone on Facebook say that they have rejected competitors solutions in the past for wasting competition resources when competitors use an excessive amount of rotations or wide moves. That of course is completely legal according to the regs but then a member of the WRC stated that the WRC confirmed that A1c can be applied to FMC for things like competitors using excessive rotations, wide moves or intentionally making their solutions longer. A1c doesn’t apply to FMC according to the regs and I haven’t been able to find anything public stating that such practices are illegal so I’m wondering if this is the case.

**Comment by Ivan-Brigidano** [comment]
Solved in PR #868
