### ISSUE TITLE
Disallow movable magnets in BLD

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#869]
I think we should explicitly disallow movable magnets in BLD (ie. yuexiao edm and gan xs) because they can be moved during the memo phase and be used to cheat (especially in mbld where judge might not be concentrating)

**Comment by Ivan-Brigidano** [comment]
And how can someone use it for cheating?

**Comment by HippolyteM** [comment]
I think 3h already do the job.

**Comment by Samuel-Baird** [comment]
3h does cover this but it could be nice to add to the guidelines as an example

**Comment by xsrvmy** [comment]
I don't think 3h covers this (at least in my mind movable magnets are fine for regular 3x3), although you could argue that deliberately violating 3h midsolve is a DNF.
@Ivan-Brigidano for instance, moving magnets of flipped edges.

**Comment by Samuel-Baird** [comment]
> I don't think 3h covers this (at least in my mind movable magnets are fine for regular 3x3), although you could argue that deliberately violating 3h midsolve is a DNF.
> @Ivan-Brigidano for instance, moving magnets of flipped edges.

3h definitely covers this, if I know that my white, red, and green corner has a dislodged magnet I can turn all the sides until I can hear the magnet turning. By doing that you are able to find the position and potentially orientation of a piece

**Comment by xsrvmy** [comment]
@UnderwaterCuber It really depends on how you interpret 3h (specifically, what is the standard to judge "additional information", and also what "modification" means). You example is obviously illegal but IMO by 3j.
