### ISSUE TITLE
Do we need "5c) Puzzle defect doesn't give right to an extra attempt"?

### ISSUE THREAD

**Issue by timhabermaas** [thewca/wca-regulations#87]
In my opinion this is already covered by [5b](https://www.worldcubeassociation.org/regulations/#5b)

> If a puzzle defect occurs during an attempt, the competitor may choose to either repair the defect and continue the attempt, or to stop the attempt.

and its subrules.

Also, I expect 5b to have two subrules which are about a) repairing and b) what happens if the competitor stops the timer without repairing the puzzle first. But instead rule 5b1, 5b2 and 5b3 are about repairing the puzzle, 5b4 talks about BLD and 5b5 finally talks about what happens if the competitor chose to stop the attempt. Should we structure this in a more intuitive (well, at least for me) way? I'm not sure how to do this without adding a new level of indentation for 5b3a and its siblings, though.

**Comment by SAuroux** [comment]
sounds reasonable and uncontroversial.

**Comment by lgarron** [comment]
This is the kind of thing that might help to have in stone. I'll move it to the Guidelines for now.

As for 5b, I object to adding another level of indentation. We've never needed it, and I don't think the current structure is especially bad. Create a new issue if you'd like to address this in particular, though.
