### ISSUE TITLE
Require the WRC to publicly announce “unwritten regs”

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#871]
Not 100% sure if this is the right place for this, if it isn’t the please direct me to the right place :P 

Recently I have seen two rulings about the regs made by the WRC, one was never announced in a public way and neither are easily findable. The first was allowing speedcubeshop's PVC coated cubes to be used, the cubes have a transparent coating which has clear stickers embedded, this isn’t allowed by 3h2a. The other was allowing delegates to not grade competitors solutions if the competitor submitted intentionally hard to execute solutions or submitted am intentionally poor solution (excessive use of wide moves or rotations, doing things like U U U U2 U’, getting 69 moves on every solve, etc.) by applying A1c to FMC (article A doesn’t apply to FMC). While I think both of these are good things to do I don’t think the way that they did it was appropriate or upholds the spirit of the WCA. Due to neither of these being announced it would be very possible for people to be receiving differing rulings for the same things and for competitors do not understand what is and isn’t legal. Competitor A in location A may not be allowed to use their PVC coated cube or may have their average DNFd after the delegate discovers them using it, competitor B in location B may not bring their PVC coated cube to the competition at all since they read the regs and know it’s illegal, competitor C in location C uses their PVC coated cube and has no repercussions. In the case of FMC a competitor goofing around after they find a good solution with plenty of time to spare may transform their solution to all wide moves knowing it’s legal thinking others may find it humorous, they receive a DNF while on the other side of the world another competitors solution uses nothing but rotations and Dw moves with no repercussions. In a case like FMC it’s also unfair to the graders seeing how one had to spend the time to grade a ridiculous solution while the other rejected it immediately.

**Comment by UnderwaterCuber** [comment]
> We currently use the Incidents log for this: https://www.worldcubeassociation.org/incidents
> 
> Regarding these particular topics:
> 
> ## PVC coated cubes
> This was not entered in the Incidents log yet, and we hadn't received any public inquiries about it. Since you brought it up here, I've gone ahead and published an entry: https://www.worldcubeassociation.org/incidents/42
> 
> In the past, the WRC has received criticism for being slow to allow puzzle modifications that many think don't provide an unfair advantage. Do you think it would have been any better to disallow these puzzles for now and allow them in a future Regs update?
> 
> ## A1c and Fewest Moves
> A1c was originally designed to apply to Fewest Moves: #225
> This WRC has correspondingly allowed the use of A1c for Fewest Moves since its introduction.
> Since this formatting issue was brought up recently, we have a pending change for 2020 to make it clear: #868
> 
> In any case, we can't solve the fundamental problem that Delegate discretion will vary from competition to competition.
> 
> In my experience, Delegates used to agree on _many_ unwritten rules and the Regulations had many consistency issues that "technically" contradicted common practice. Since the introduction of the WRC, I believe we've gotten a lot better at making the wording of the Regulations match the intent, to the point that the A1c issue looks like a sore thumb in retrospect.
> 
> Based on talking to the Board and Delegates, I don't think it's a good idea to make major changes to the Regulations more than once (maybe twice) a year, so the Incidents log is the place for "unclarified" and "unwritten" Regs.
> 
> I think it's good to call us out if we're not publishing important clarifications, but are you seeing issues beyond what you have mentioned here?

The main problem with the incident log is that it isn’t easy to read through all of it to learn about rulings, rulings may have been made with old regulations in mind meaning some rulings could be outdated and shouldn’t be applied to current regs, rulings may not be consistent (see A6e, I can look for other examples later but that’s a big one). Also I can’t find anything anywhere saying that rulings from the incident log can be applied to other similar scenarios (if that is a thing I would love to see it be easier to find) 

In the case of A1c it was ruled that it could be used for FMC nearly 8 hours before the PR was made and it’s currently not on the incident log. Unless you have read this GitHub issue or you looked at the comments on kits post in cyoubxs friends you have no idea A1c can legally be applied to FMC. You also can’t really put it on the incidents log seeing how it’s not an incident, the regs are very clear that A1c applies to speedsolving events only so by the definition of incidents in article 11 it doesn’t count as one. 

Some things which I think could potentially help:
-Reference the incidents log in the regulations or guidelines and clarify that rulings of those incidents can be applied to similar incidents.
-create something new which can cover all the rulings of the incidents and lay them out in a way that looks a lot more manageable like the regs, this could allow for us to put non-incidents on there. 

In closing the current system works but I definitely see room for improvement to make things more consistent, clear and transparent. I would love to hear some of your ideas to do this :)
