### ISSUE TITLE
Require Delegates to be present and able to see competitors

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#872]
I have been thinking about Fabio’s cheating incident recently and the biggest thing that stands out to me was how preventable most of it was. Despite there being 3 delegates they were all in the main room where there were only 64 competitors (including them). If one of them had been in the room the cheating wouldn’t have happened or would have been caught much more easily which could have saved the WDC from doing an intensive investigation and causing controversy. 

I would like to have a regulation or guideline which requires a delegate present at all times in the room and able to view all competitors. 1c heavily implies this already but I have seen several stories online in which the delegate was in the main room and the side room was only supervised by judges. Not only does it make it easier to cheat but it also causes extra problems when there is an incident, instead of just having to call the delegate over you have to send a runner to fetch them which eats into competition time. 

The biggest problems with my proposal are:
1. Competitions with two rooms and one delegate can’t exist 
2. Everything has to be put on hold if the delegate needs to leave for a moment (ex. Use the restroom) or is unable to deal with issues (ex delegate is doing MBLD) 

The first issue shouldn’t be an issue imo, I feel like we shouldn’t be having competitions where delegates are unable to oversee parts of the competition in the first place.

To fix the second issue that I think allowing the delegate to appoint an experienced competitor to watch over the competition temporarily could be helpful. This person could be given temporary delegate powers or could have to wait for a call from the delegate, but their main purpose is to make sure regs are being followed. 

I would love to see critiques, alternative solutions, and overall thoughts on this.

**Comment by AlexKatyukov** [comment]
Delegate can ask trust man to oversee side zone.

**Comment by xsrvmy** [comment]
If the delegate can delegate responsibilities to another person, then having a side room without a delegate is not a problem.
Tbh I actually fail to see anyway to enforce this.

**Comment by maconard** [comment]
It's pretty standard for Delegates to ask a trusted competitor to watch over a comp when they run to the bathroom and such. 

I suppose it would make sense for them to ask a trusted competitor to watch over a side room that they can't be in, but that kind of things gets pretty hard to enforce.

**Comment by Samuel-Baird** [comment]
> If the delegate can delegate responsibilities to another person, then having a side room without a delegate is not a problem.
> Tbh I actually fail to see anyway to enforce this.

If it were up to me then I wouldn’t allow comps that have two rooms and only one delegate.

The honor code works pretty well usually :P competitors could always report if the delegate isn’t there for some reason. Or if this was implemented it could just say the delegate should be present at all times (which means they aren’t required but it’s highly recommended basically)

**Comment by xsrvmy** [comment]
It probably would have to be a "should". There is no incentive to report the delegate isn't there unless you want to prevent someone from beating your record or something, and things get unsporting pretty quick.

**Comment by Ivan-Brigidano** [comment]
I **feel** that this is more likely to be in the Delegates motion rather than in the Regulations

**Comment by ghost** [comment]
There was one incident that makes me think we need to have some regulation enforcing some sort of required delegate oversight. I was at a comp a few years back where they had FMC and other events running simultaneously with only one delegate. Needless to say the comp was without a delegate for three hours. Nobody was assigned to make decisions, which left a group of experienced cubers to make phone calls/have video chats with other delegates in order to solve incidents and make decisions that the delegate should be making.

**Comment by Jambrose777** [comment]
There's an internal thread pseudo-relating to this if new WRC is interested. It outlines some of the issues revolved around making this a requirement aside from what's been mentioned here like a bathroom break issue. The thread is "Restricting amount of competitors and rooms per Delegate"

I know with github we try to avoid referencing internal threads, but I feel it is appropriate here.

**Comment by alexmaasswca** [comment]
I think this regulation has the right idea, I know from past experience that it would've prevented a very serious incident from happening and definitely other incidents. 

I don't think this is very necessary to be in the regulations if only the delegate needs to know this.

**Comment by cubewhiz** [comment]
I gave my opinion in the internal thread about this a few months ago, but I'll summarize it here. I feel like adding this as a specific requirement adds unnecessary bureaucracy. Delegates should use their judgement and if there are two rooms, they should consider appointing another Delegate to assist with the competition.

**Comment by casiku** [comment]
I think this is too harsh. What if the delegate needs to go to the bathroom? Should people blame him because he needs to go? They already do a ton of work, so I suggest we get more delegates instead, to increase the quality of competitions and decrease the likelihood of cheating (as the forementioned BLD incident)
