### ISSUE TITLE
Competitors should be quiet for “quiet events”

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#873]
Talking and noise can be very distracting for competitors competing in Fewest Moves and in Blindfolded events, especially during the last few minutes of Multi-Blind or Fewest Moves with the time limit being near to running out. Having something in the regs to encourage or require competitors to be quiet during these events could be nice. 

Cyoubx’s friends, a private group on Facebook, is discussing a 5 minute period of complete silence for the last 5 minutes of mbld or fmc in which competitors have to sit down. I don’t think this would work well for mbld seeing how competitors can (and often do) start their attempts at different times. It would also require someone to notify all competitors to sit down and be quiet, perhaps the judge calls 5 minutes and then talks loud enough for all the competitors in the venue to hear them and explains how they must all sit and remain silent for the next 5 minutes? I would find that pretty distracting though but I found it an interesting idea which I found discussion worthy.

Even if we didn’t do that I think having something that is a bit more explicit than 2k4. about having noise during quiet events could be helpful, lots of beginners don’t realize how much concentration those events take and often talk while the event is in progress. Something like this could be nice

2f+) Competitors, when asked remain asked to do so by the WCA Delegate, should remain quiet for the duration of the round for the following events: 3x3x3 Blindfolded, 4x4x4 Blindfolded, 5x5x5 Blindfolded, 3x3 Multi-Blind, and 3x3x3 Fewest Moves.

If we want to be a little more strict then replace “should” with “must”, add “Penalty: Disqualification from the competition at the discretion of the WCA Delegate” and have it be 2f1 instead of 2f+

Or listing competitors making excessive noise as an example in 2k4+ could be nice as well

**Comment by alexmaasswca** [comment]
I support this, but only disqualification from the current event, not competiton imo.

**Comment by Samuel-Baird** [comment]
> I support this, but only disqualification from the current event, not competiton imo.

That doesn’t help at all if the person making noise isn’t competing in the event :P

**Comment by UnderwaterCuber** [comment]
A private group on Facebook is discussing a 5 minute period of complete silence for the last 5 minutes of mbld or fmc in which competitors have to sit down. I don’t think this would work well for mbld seeing how competitors can (and often do) start their attempts at different times.

**Comment by Laura-O** [comment]
We already have [2k4](https://www.worldcubeassociation.org/regulations/#2k4).

**Comment by xsrvmy** [comment]
2k4 already covers this. Also this would have to be enforced reasonably so instinctive reactions are not penalized.

**Comment by Samuel-Baird** [comment]
> 2k4 already covers this. Also this would have to be enforced reasonably so instinctive reactions are not penalized.

2k4 covers this but it could be nice to make it more explicit, also there is that “last 5 minutes is silent” proposal which is new 

Delegate discretion applies, what do you mean by natural reactions though?

**Comment by xsrvmy** [comment]
> natural reactions

For example when someone gets WR

**Comment by Samuel-Baird** [comment]
> > natural reactions
> 
> For example when someone gets WR

Competitors can suppress their excitement and be respectful to other competitors. People who get world records in blind are usually pretty respectful as well, they might make some excited faces but they are usually pretty quiet :P

**Comment by xsrvmy** [comment]
@UnderwaterCuber I meant the reaction from the audience obviously. You can't seriously expect this rule to be enforced fairly. IMO this requires a direct, personal warning from the delegate and also disqualification from the competition is too harsh (at worst ask him to leave the room).

**Comment by Samuel-Baird** [comment]
> @UnderwaterCuber I meant the reaction from the audience obviously. You can't seriously expect this rule to be enforced fairly. IMO this requires a direct, personal warning from the delegate and also disqualification from the competition is too harsh (at worst ask him to leave the room).

Yeah I definitely agree that the delegate should have to directly interact with them. I feel like disqualification is fair, you are doing intentionally doing something that is likely is harming the performance of others.

**Comment by xsrvmy** [comment]
> Yeah I definitely agree that the delegate should have to directly interact with them. I feel like disqualification is fair, you are doing intentionally doing something that is likely is harming the performance of others.

Key word "intentionally". Most of the time distractions are not intentional (like whispering too loud near the competitor's area and especially reactions).

**Comment by casiku** [comment]
I support this idea
