### ISSUE TITLE
Remove 11g

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-regulations#874]
11g is redundant as it is mentioned in point 8.2.7 in the WCRP.

**Comment by alexmaasswca** [comment]
I don't think its a good idea. I think the fact that regulations are required to be accessible at the competition is pretty important for resolving an incident.

**Comment by Burnsy101** [comment]
I agree with alex - even though it is mentioned in 8.2.7 I think having it in the regs is pretty useful to make sure that competitors have access.
As well, is the WCRP public? It doesn't seem to be and it feels like an important reg for everyone to know about to ensure people know that the regs will be enforced at a comp

**Comment by Jambrose777** [comment]
Regulation [1c)](https://www.worldcubeassociation.org/regulations/#1c).

All public policies are listed in WCA Documents: https://www.worldcubeassociation.org/documents (you can find this by Information > WCA Documents on any page of the website). WCRP is one of those policies.

Considering this regulation relates to only the Delegates and not the competitors, I agree it should be removed from the regulations.

**Comment by alexmaasswca** [comment]
> Regulation [1c)](https://www.worldcubeassociation.org/regulations/#1c).
> 
> All public policies are listed in WCA Documents: https://www.worldcubeassociation.org/documents (you can find this by Information > WCA Documents on any page of the website). WCRP is one of those policies.
> 
> Considering this regulation relates to only the Delegates and not the competitors, I agree it should be removed from the regulations.

so you're saying that competitors have no need to look up the regulations during the competition?

**Comment by Jambrose777** [comment]
> > Regulation [1c)](https://www.worldcubeassociation.org/regulations/#1c).
> > All public policies are listed in WCA Documents: https://www.worldcubeassociation.org/documents (you can find this by Information > WCA Documents on any page of the website). WCRP is one of those policies.
> > Considering this regulation relates to only the Delegates and not the competitors, I agree it should be removed from the regulations.
> 
> so you're saying that competitors have no need to look up the regulations during the competition?

no, it's in the WCRP that the Delegate must have a copy. Its not information needed to know by the competitor, which is why its in the WCRP in the first place.

**Comment by Ivan-Brigidano** [comment]
I agree that 11g is redundant. Indeed I think there are more regulations or guidelines that should be moved into WCA Documents of Policies (such us Article 6).

**Comment by xsrvmy** [comment]
IMO actually the reg should also allow the competitor to access said copy of the reg in the event that the competitor needs to dispute a ruling based on the regs. It is fair sportsmanship to for the delegate to do that though, so not sure if it has to be a reg.

**Comment by UnderwaterCuber** [comment]
> IMO actually the reg should also allow the competitor to access said copy of the reg in the event that the competitor needs to dispute a ruling based on the regs. It is fair sportsmanship to for the delegate to do that though, so not sure if it has to be a reg.

I believe the regulations used to be something along the line of the delegate or organizational team must have a copy of the regulations for competitors and then it shifted to the delegate must have a copy of the regs for handling incidents. Not sure how that change happened over time but I would definitely be in favor of requiring the delegate or organization team to have a copy of the regs for competitors to use.

**Comment by Ivan-Brigidano** [comment]
There is nothing that wouldn't allow competitors to have a copy of the Regulations.

**Comment by Samuel-Baird** [comment]
> There is nothing that wouldn't allow competitors to have a copy of the Regulations.

Other than not having access to a device that can access the Internet at home or during a competition?

**Comment by Ivan-Brigidano** [comment]
> > There is nothing that wouldn't allow competitors to have a copy of the Regulations.
> 
> Other than not having access to a device that can access the Internet at home or during a competition?

Competitors can bring printed copies of Regulations if they wish. So not having Internet access shouldn't be a problem. And if they don't have any copy (printed or Internet), there shouldn't be any problem as Delegate is required to do it.

**Comment by xsrvmy** [comment]
@Ivan-Brigidano I think the problem we are trying to address here is that the Delegate should not be allowed to withhold information about the regs front the competitor, especially if there is a dispute.

**Comment by Ivan-Brigidano** [comment]
> @Ivan-Brigidano I think the problem we are trying to address here is that the Delegate should not be allowed to withhold information about the regs front the competitor, especially if there is a dispute.

But the Delegate would still be required to have a copy of the Regulations according to WCRP. So really there wouldn’t be any change on the competitions

**Comment by hanwu85** [comment]
I think what they are talking about is,  if a competitor requests to see a copy of the regulations., the WCA Delegate should present the copy to the competitor.

**Comment by Jambrose777** [comment]
@hanwu85 Why was this closed? This regulation should be removed, the same as everything else that was moved to the WCRP or other documents.

**Comment by hanwu85** [comment]
Sorry, I pressed the wrong button when leaving a comment.

**Comment by Ivan-Brigidano** [comment]
> I think what they are talking about is, if a competitor requests to see a copy of the regulations., the WCA Delegate should present the copy to the competitor.

That is arguably a good addition for the WCRP but it wouldn't make sense in the Regulations

**Comment by c-goodyear** [comment]
I'd be in favour of keeping this regulation, given that basically all competitors are advised "be familiar with the regulations" so this would allow them to know that they would be able to refer to the regulations without worrying about how to have access to their own copy at the competition.

>  Regulation 1c).
> 
> All public policies are listed in WCA Documents: https://www.worldcubeassociation.org/documents (you can find this by Information > WCA Documents on any page of the website). WCRP is one of those policies.
> 
> Considering this regulation relates to only the Delegates and not the competitors, I agree it should be removed from the regulations.

> Its not information needed to know by the competitor

Having the same thing written in two places isn't drastically bad given they have two different audiences. The copy in the regulations ensures that competitors are aware of their "rights" by reading the regulations before attending a competition. Then the WCRP can enforce the standard of Delegates having to provide this in a more thorough manner, so I agree with the addition to the WCRP for Delegate reference.

If the argument is that competitors can know the same thing by proxy of 1c) and the WCRP then are they expected to read all our policies before attending a competition? This seems unreasonable, and not fair to those who do not have good English skills. Rememer that the regulations are translated, unlike other WCA documents. This gives basically all cubers easy access to their "rights" via having it in the regulations.
