### ISSUE TITLE
Allow big competitions to have 5 rounds for a event

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-regulations#878]
This would allow big competitions (such as Continental or World Championships) to have 5 rounds of popular events (mainly 3x3 and maybe 2x2, Pyraminx and Skewb). For example:

> 9m4) Exception: At Championships competitions, events must have at most five rounds.
>> 9m4a) Rounds with XX or fewer competitors must have at most three subsequent rounds.

Another possibility could be:

>9m) Events must have at most ~four~ five rounds.
>> 9m1) (Same)
>> 9m2) (Same)
>> 9m3) (Same)
>> 9m4) Rounds with XX or fewer competitors must have at most three subsequent rounds.

Being XX a large number such us 299 competitors.

I will be updating this summary of Pros and Cons based on comments:

## Pros:
- More rounds=more fun (not applicable here?)
- A higher expectation to view who have classified
- Extra options for organizers

## Cons:
- Difficult to fit in already crowded Championship schedules
- Only affect a very little number of competitors
- Increase the chance that a good competitor can't classify for finals
- Time could be better spent by advancing more people and/or having more rounds of other events

**Comment by EdHollingdale** [comment]
Why do we need 5 rounds? I don't think it actually adds more fun, nor does it establish a clearer winner. WC2019 had only one event with 4 rounds (3x3x3 Cube). An organisation team of a 500+ competition should, in my opinion, prioritise things that will impact the majority of competitors, rather than giving 30-40 fast people 5 more solves.

**Comment by Baiqiang** [comment]
I agree with @EdHollingdale . The pro `More rounds=more fun` is not true. More rounds only give some people more solves.

**Comment by xsrvmy** [comment]
I am highly against this. This increases the chance that someone good might DNF out early.

**Comment by pedrosino** [comment]
> I am highly against this. This increases the chance that someone good might DNF out early.

What? Why is that?

I agree that 5 rounds is not necessary. Time could be better spent by advancing more people and/or having more rounds of other events. But time at major championships is already small, so...

**Comment by xsrvmy** [comment]
@pedrosino Not a major champ, but I'm been at a Toronto comp with 4 rounds of 3x3 where like 5 good people got a DNF average.

**Comment by pedrosino** [comment]
But that is not directly related to how many rounds the event has. Anyone is subject to a DNF average at any round. If the top competitor fails the first round, it makes no difference if there's just one or four subsequent rounds.

**Comment by xsrvmy** [comment]
It increases the chance a top competitor may DNF before finals becuase of the extra round.

**Comment by UnderwaterCuber** [comment]
I think that this could be something to discuss later on in the future as cubing grows but for now I don’t really see much use in doing this.

**Comment by aneurinhunt** [comment]
What does 5 rounds actually give? It feels like adding round becomes a little redundant at this point. Only very few people will actually get to complete in 5 rounds.

**Comment by cubewhiz** [comment]
I don't believe 5 rounds is necessary. On the contrary, I think the number of people who can compete in rounds 2-4 should be altered (something like: require 16 competitors for 2 rounds, 64 competitors for 3 rounds, 256 competitors for 4 rounds)

**Comment by Jambrose777** [comment]
> I don't believe 5 rounds is necessary. On the contrary, I think the number of people who can compete in rounds 2-4 should be altered (something like: require 16 competitors for 2 rounds, 64 competitors for 3 rounds, 256 competitors for 4 rounds)

Off topic, but I’d disagree with changing the number for 2 rounds. We have guideline 1h++ and at smaller comeptitions (with less than 16 people) it is often times impossible to follow this guideline with 1 round.

**Comment by Samuel-Baird** [comment]
> > I don't believe 5 rounds is necessary. On the contrary, I think the number of people who can compete in rounds 2-4 should be altered (something like: require 16 competitors for 2 rounds, 64 competitors for 3 rounds, 256 competitors for 4 rounds)
> 
> Off topic, but I’d disagree with changing the number for 2 rounds. We have guideline 1h++ and at smaller comeptitions (with less than 16 people) it is often times impossible to follow this guideline with 1 round.

It’s a recommendation so it wouldn’t cause any real issues :P

**Comment by KitClement** [comment]
I agree with others regarding 5 rounds, there really is no purpose to holding that many rounds. Honestly, for the purposes of determining a champion, 3 is sufficient - one round to give everyone a chance to compete, a second to determine finalists with the best competitors getting the same scrambles, and then the final round. 

Regarding raising the threshold for holding multiple rounds: I think that 8 competitors for 2 rounds should not change. Small competitions need to be able to have multiple rounds to use different scramble groups, and raising that number may pose logistical issues. I wouldn't be opposed to raising the number of competitors required for 3 or 4 rounds, however. These numbers were defined when the typical competition was much smaller, and only enabled major events to have 4 rounds. Today it should be reasonable to expect far more than 100 competitors to hold 4 rounds.

**Comment by cubewhiz** [comment]
I'd be interested in seeing the stats of how many competitions/events had 8 - 15 competitors and held two rounds. I'll fork this conversation into a new thread so as not to hijack it completely.
