### ISSUE TITLE
Change +2 for inspection between 15-17 seconds to DNF

### ISSUE THREAD

**Issue by saranshgrover** [thewca/wca-regulations#880]
This makes going beyond inspection complicated - and 15-17 seconds seems like an arbitrary interval (why not 15-16 or 15-18) without any purpose. I think it reasonable to give a DNF if someone goes beyond 15 seconds as opposed to waiting another 2 seconds.

**Comment by ccbaird** [comment]
15 seconds is arbitrary too. On the balance between “too strict” and “too complicated” this seems like a happy medium.

**Comment by xsrvmy** [comment]
This is a duplicate of #787 
The main objection is that stopwatch timing is not accurate enough.

**Comment by saranshgrover** [comment]
Woops - i looked around for a bit but couldn't find a similar issue. Sorry about that. We should probably continue discussion on #787
