### ISSUE TITLE
Disallow the use of non-standard color schemes 

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#881]
One issue I have experienced with competitions is non-standard color schemes. Scrambles aren’t as easy to check, there is often confusion about which orientation the puzzle should be scrambled in, and puzzles may not consistently be scrambled in the same orientation which can give competitors unfair advantages or disadvantages. Requiring competitors to use standard color schemes could help reduce a lot of these issues and could simplify the regs. 

While implementing some of these regulations would be very controversial and may cause lots of issues initially I think in the long term it would be for the best interest of the wca. It’s not uncommon for sports to have very regulations about legal equipment and I feel like requiring standard color schemes isn’t too much to ask of competitors. 

Another (small) benefit it is makes things a lot more consistent and professional looking. For example a cube that has two different shades of gray, white, black, brown, maroon, and navy would be really distracting.

Short term issues that I see:
For competitors who have used non-standard color schemes for large amounts of time it would throw them off to be required to use a different color scheme. They also may not own puzzles with normal color schemes. 

Square-1 it’s not uncommon for competitors to switch white and yellow or to replace white or yellow with black

Megaminx seems to be very popular for having non-standard coloring schemes and it may be hard for scramblers to spot non-standard coloring schemes

Long term issues that I see: 
Colorblind competitors may use non-standard color schemes to allow them to more easily distinguishable colors. (Ex a competitor who gets red and green mixed up might replace green with black) requiring them to use the standard color scheme may make solving much more difficult for them. A potential fix for this could be to allow other coloring schemes that are “colorblind friendly” these schemes would be tailored to make colors recognizable while also making them as similar to current schemes as possible. 

Some colors may be ambiguous, for example some Stickerless puzzles use a dark pink color in the place of red. With the growing popularity of stickerless puzzles it’s getting much less common for cubers to have non-standard coloring schemes and most stickerless colors are very unambiguous. Additionally if this regulation was implemented cube manufacturers would likely stray away from making ambiguous colors. 

Other ideas:
recommend competitors to use standard color schemes

don’t require standard color schemes for megaminx and/or square-1

**Comment by maconard** [comment]
> 4d3 Square-1 is scrambled starting with green on front

You can't scramble a Square-1 with green front on the standard color scheme. Square-1 has to have the slice action going from front to back.

**Comment by Samuel-Baird** [comment]
> > 4d3 Square-1 is scrambled starting with green on front
> 
> You can't scramble a Square-1 with green front on the standard color scheme. Square-1 has to have the slice action going from front to back.

Oops! My bad for the typo. I have changed it to red :)

**Comment by HippolyteM** [comment]
How do you define a "color"? There are almost infinites shades of green, or any other color. Would you like to specify a color with a cmjn code? Then you would have to choose this following a color used by a specific brand, which is definitely terrible.
Your point about colourblindness is a major reson not to pursue this idea any further.
Also you gave many cons, and your pro is really unsignificant. Scramblers scramble the wrong way when they are not aware of the regulations, which are quite simple to understand.
I see no point in this proposal.

**Comment by Samuel-Baird** [comment]
> How do you define a "color"? There are almost infinites shades of green, or any other color. Would you like to specify a color with a cmjn code? Then you would have to choose this following a color used by a specific brand, which is definitely terrible.
> Your point about colourblindness is a major reson not to pursue this idea any further.
> Also you gave many cons, and your pro is really unsignificant. Scramblers scramble the wrong way when they are not aware of the regulations, which are quite simple to understand.
> I see no point in this proposal.

We would define colors the exact same way that they are currently defined in the regs.

Color blindness does seem to be one of the biggest issues. I think a good solution would be to have a list of legal color schemes and make several of those color schemes with colorblind cubers in mind. Anyone can choose from the schemes but most people will likely go with the standard coloring scheme.

I did give a lot of cons and only two of those are long term. The color blind issue could be solved with the method above and ambiguous colors are rare. Implementing this could prevent misscrambled and inconsistency which is great thing to do.

**Comment by xsrvmy** [comment]
A ton of downvotes lol
I see this as a breaking change. The standard color scheme we use these days is just a convention, but it's not even that good, especially on stickered cubes. Opposite colors can be hard to see in bad lighting.
It would be much better if we just allowed black top green front if white is replaced with black (or some other color like grey)

Also will Rubik's cause problems?

**Comment by Samuel-Baird** [comment]
> A ton of downvotes lol
> I see this as a breaking change. The standard color scheme we use these days is just a convention, but it's not even that good, especially on stickered cubes. Opposite colors can be hard to see in bad lighting.
> It would be much better if we just allowed black top green front if white is replaced with black (or some other color like grey)
> 
> Also will Rubik's cause problems?

Not a lot of discussion though sadly. 

Lighting should be good at venues, at home it’s nice to be able to compare colors in dim lighting but venues shouldn’t have mood lighting lol

How many mass produced puzzles replace white with black? 

What about Rubik’s?

**Comment by casiku** [comment]
I like this. Weird color schemes delay rounds a lot. I once sent back a cube 2+ times because I didn't realise he switched the colors. And some people deliberately use a weird color scheme to confuse the scramblers in events they don't care for.

**Comment by xsrvmy** [comment]
> > A ton of downvotes lol
> > I see this as a breaking change. The standard color scheme we use these days is just a convention, but it's not even that good, especially on stickered cubes. Opposite colors can be hard to see in bad lighting.
> > It would be much better if we just allowed black top green front if white is replaced with black (or some other color like grey)
> > Also will Rubik's cause problems?
> 
> Not a lot of discussion though sadly.
> 
> Lighting should be good at venues, at home it’s nice to be able to compare colors in dim lighting but venues shouldn’t have mood lighting lol
> 
> How many mass produced puzzles replace white with black?
> 
> What about Rubik’s?
I've not talking about manufacturers, although I bought cubes with black before. I'm ralking about world class competitors in several events using black (mega, sq1, bld)

Can Rubik's start getting at WCA for putting their color scheme in regs?

**Comment by julesDesjardin** [comment]
Wow, I didn't expect this to go into a serious discussion, but let's be serious then!

This has the con of removing the ability for competitors to adapt their cubes to their own preferences. Color scheme can play a role, exactly like tensioning and lubing (although less significant).
I'll take my personal example: I use fluoresecent pink instead of red, and all my other colors aren't bright. This has an amazing effect on F2L, and I instantly see corners, whereas a normal red shade takes me sliiightly longer to spot. This is even more noticeable in big cubes: to pair cross edges, my eyes are so attracted to the pink that I see only that, which is helpful when a ton of pieces of still unsolved.
And you already mentioned colorblind people, but you seem to allow them to still be able to have another scheme.

However, as Hippolyte said, what is a color? Colors are subjective. Hell, my eyes are so used to pink that I call it red (and actually see it red on my pyra).

Now that I discussed the cons, let's go to the pros: what are they exactly?
If you need to pay more attention to a scrambled cube because the color scheme was weird, congrats! You just checked the cube muuuuuch more than 95% of scramblers, so it's much more likely to be correctly scrambled! (also, that only applies to bigger changes than color shades, for example white<->black, or BYO<->BOY)

Now I should probably go back to deal with more important stuff :D
