### ISSUE TITLE
Multi-Step Proposal "Tracks"

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#882]
In the past, I believe there was more of a willingness to implement more impactful changes to the Regulations if it was the right place to land.

However, I've noticed a pattern where we need 2 or 3 Regulations cycles in order to formalize a desired end goal. This is especially common for scramble accountability.

I think it would be good for proposals to have a multi-step plan where appropriate. For example:

- Allow X.
- Recommend X.
- Strongly recommend X.
- Require X but allow certain likely mistakes/exceptions.
- Require X in all cases.

Depending on the proposal, fewer steps may be needed or we may stop in the middle. They also don't need to have a strict timeline with exact years. We can evaluate whether to take the next steps in a proposal as needed. However, communicating *intended* changes ahead of time signals to Delegates/judges/competitors that they should prepare for the future rather than assuming that we are at an "end state". It also helps us identify defines "best practices" that Delegates can strive to meet, but that we don't want to implement until they've been tried sufficiently often.

This isn't really a proposal on its own — new proposals can use this approach as they see fit — but I'm filing it as an issue in order to reference it for other specific topics.

**Comment by Samuel-Baird** [comment]
Seems like a pretty good idea. I think just to keep things simple it might be nice to just combine recommend and strongly recommend. Also if systematic leniency gets approved then Require X in all cases and Require X but allow certain exceptions could be merged, correct?
