### ISSUE TITLE
New A6c/A6e changes doesn't seem to work

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#894]
There was a recent A6c/A6e update in the PRs that changed the discretion from judge to delegate. Apparently the intention was to allow systematic leniency (like that 4x4 WR) but it does not have the effect of doing so. The new wording only slow down comps by requiring the delegate to come over for almost every single A6c/A6e violation and still does not allow waiving the penalty.
(I have chosen not to comment on the PRs since they are merged already)

**Comment by lgarron** [comment]
We already planned to update this after https://www.worldcubeassociation.org/incidents/23

The Delegate is already usually involved in these decisions, and systematic leniency needs to rely on the discretion of the Delegate to be accountable.

I don't expect that we will revert this update, but I think we should be open to it if others feel strongly.
