### ISSUE TITLE
Restrictions on applying penalties based on evidence after the competition

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#895]
This is motivated by the new reg that FMC sheets can be uploaded. There is also a discussion about something similar to this, but on the limitation of the timeframe rather than the reason of applying a penalty.

In my opinion there are some elements of an attempt that should not be scrutinised after a competition, because they are based too much on discretion. Here are some examples:
- Handwriting on scoresheet/FMC sheet
- Reasonable wear
- Application of A1c
- Whether or not a competitor is distracting another competitor
- Intention in case of OH cube drop

Another category is borderline decisions, and these are more open for debate. Examples:
- Borderline +2
- Borderline timer start (are fingers on timer or not?)
- Puzzle fully released when stopping
- Inspection too close to 15
- Nod-don

**Comment by lgarron** [comment]
Given that 1) we regularly get *more* requests to revise changes over time, and 2) people really want internationally fair conditions, this is rather tricky.

A ["statute of limitations"](https://github.com/thewca/wca-regulations/issues/800
) would address some of this, but I haven't really seen discussion or support for it.

However, I want us to prioritize ways to give the Delegate systematic discretion over these kinds of things: https://github.com/thewca/wca-regulations/issues/798
As part of this, it could be a good idea to work on a list of penalties that we will not revise unless it was an extreme case.

**Comment by xsrvmy** [comment]
I feel even more strongly about this now that I saw the 0.60 +2 incident.
Video evidence is also not fair for borderline decisions by nature IMO. Recording in 60fps would be more punishing than recording in 30fps.
