### ISSUE TITLE
Stricter enforcement of 7b

### ISSUE THREAD

**Issue by SeanMoran27** [thewca/wca-regulations#896]
> 7b) Spectators must remain at least 1.5 meters away from the solving stations when they are in use.
>
I've seen this regulation broken on multiple occasions throughout competitions, so I feel like stricter enforcement (e.g. requiring a set out boundary through tape/signage) may be beneficial in reducing this and would also reduce the chance of extras needing to be given. Since some may have issues with gauging distances or potentially not using the metric system, having a physical boundary would help to minimise accidental breaking of this regulation too.

**Comment by xsrvmy** [comment]
Tape might not be allowed at certain venues so I'm not sure if this is a valid course of action.
Plus, usually in my experience, this rule seems to be broken from behind more often so tape would not really help.

**Comment by hanwu85** [comment]
Do you have new ideas about how to enforce this regulation?
A physical boundary might cause logistic issue.  We already have logistic issue regarding scramble table dividers.  I agree tape sometimes does not help even it is in the front.

**Comment by Burnsy101** [comment]
It could be simple - honestly just a rope that you can't cross unless youre a runner / scrambler / competitor, tied from a stand at one end of the area to another
I agree with sean that this issue should be addressed  and there is nothing worse than having so many people crowd around you - even if it is for a reaction for a  good solve
