### ISSUE TITLE
Rewording some regs to allow "scorecardless" competitions?

### ISSUE THREAD

**Issue by Sixstringcal** [thewca/wca-regulations#898]
It's currently possible (probably not logistically sound yet and it doesn't work too well with the current set of regs stating there is a scorecard and signatures) to go "scorecardless" (that being said, we still need a competitor identifier for the cube of some sort.  We could solve this by NFC, but that kind of a solution seems far out right now).  If I'm remembering correctly, I was told about a comp in Poland that tried a scorecardless comp (I don't even know if this was official)?  I can't be certain of it though and I don't know which one it was.

It's currently possible to have a great system that doesn't follow the regulations as follows (although it might be costly.  It would not cost more than getting another speedstacks display for each station though.  There are also many other systems I'd imagine would also work, this is just the first system to come to mind.):

- Every station has a Raspberry Pi running a program on it.  It has an NFC chip, a small speaker capable of making a small beep sound, some wireless transmitter, and a display capable of displaying every number a stackmat could display.
- Every station has an NFC chip for a judge.  Maybe the judge could find some way to put their initials inside the signal, but I don't think this is required.
- Every competitor on their nametag (yes, they'd have to have nametags, they're quite useful and they can give relevant data to the competitors, such as groups.  I use them at all comps I organize, just not with NFC chips yet).
- The stackmats connect to this Raspberry Pi and optionally the display as well.
- Competitor does Solve.
- Solve time is displayed on the Raspberry Pi's display
- Judge checks the time on the Raspberry Pi's display and the Stackmat Display
- When the judge confirms the time, the judge taps his/her NFC chip to the Raspberry Pi
- Raspberry Pi beeps
- Competitor taps their card to the Raspberry Pi, sending the result
- Raspberry Pi beeps.
- If competitor does not tap their card within 10 seconds of the judge, it starts beeping (like a credit card terminal if after a while a customer doesn't remove their card).
- If the time doesn't match, a delegate can tap their tag to the Raspberry Pi and connect a USB numpad and enter the correct result.
- There would also be a separate NFC chip for penalties (or we could put buttons on it).
- Scramblers would have a program open that syncs with the NFC system stating what solve everyone is on, so they get the cube back with something stating who's cube it is and they check the program and it says what scramble to apply.  After scrambling, the scrambler taps their scramble NFC tag to some NFC reader and that's "scramble signing"

Under the current regs, this would not be allowed, but this system, I believe should totally be allowed.  Not only is it paperless (well, you'd need an identifier for the puzzle, but this can use significantly less paper.  You could actually take it a bit further and tag the cube covers, but I think that's overkill/needlessly complicated), but it also ensures that unintelligible scribbles don't have to be deciphered, no more cases of (original time with the +2 added) +2, it's likely that the post-solve time spent at the station will be more efficient, and you wouldn't have to deal with unsigned times, because we'd have a Raspberry Pi beeping at you.

To allow a system like this, we'd have to modify the regs.  I believe we could put something in the guidelines saying that "score sheet" is a generic term used to describe the storage of a competitor's times and that "sign", "signature", "initial", etc., may be substituted for another form of acceptance of the time.

I'm not saying we need to have all comps switch to this system or any comps, but I feel that this kind of system should 100% be allowed (and maybe encouraged) and the current wording of the regs I don't think allows this.

That being said, if a comp goes scorecardless, should we require there to be a backup if technology fails?  Like, should bringing a printer be required in this situation, or would it just be expected that you could adapt?

Edit: I deleted the first line because it was a relic of my original draft in writing this that doesn't fit where it was.

**Comment by lgarron** [comment]
If someone wants to try this, I think it's fine to count an NFC swipe as a signature. A lot of things can legally count as a signature in the modern world already.

Do you know anyone who is close to implementing this?

**Comment by poiuytre121** [comment]
Say hello to Cubing Spring Grudziądz 2012 and opencubeware: https://www.youtube.com/watch?v=D_s-YfMIccI
It was happening before I even started cubing, but from what I know this system was used at this competition in addition to standard scorecards and was working pretty well. Competitor had to check-in before attempt and check-out to confirm that they agree with the time using some magnetic cards (I think that some competitors could still have them stashed somewhere). Unfortunately it was abandoned many years ago for reasons unknown to me. Opencubeware was created by Piotr Padlewski and Rafał Studnicki and possibly some other guys. Also some other video that I found about it: https://www.youtube.com/watch?v=vnY-BjmU5t4

For active projects I know that local unofficial league here in Warsaw (DLS, they were also organizing official comps in the past and want to go back official in 2020) tried to implement some system of automatic scoretaking based on judge smartphone and QR code on competitor's ID. I remember that on one of these unofficial competitions they tried to use it but it failed to work after first round of the day and we switched back to using scorecards. They have their own system with results on http://live.teamcubing.pl/. 

If WRC would send clear signal that this kind of system will be allowed on official competitions I think that development of such systems would leap forward, possibly ending up with working solutions in near future.

**Comment by lgarron** [comment]
> If WRC would send clear signal that this kind of system will be allowed on official competitions I think that development of such systems would leap forward, possibly ending up with working solutions in near future.

If that is the case, please consider this a signal!

**Comment by Ivan-Brigidano** [comment]
A Spanish competitor was also working on a project for this.
I think it might work in a future to allow it. This will, of course, need a good system to avoid cheating,

**Comment by asdfjklsemicolon** [comment]
I was thinking of something similar to this a few months back, however instead using barcodes/QR codes on cube covers, and a phone app, which would likely be cheaper and easier to develop.
