### ISSUE TITLE
Stackmat requirements/loopholes

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#90]
In particular, make are clear about what timers/mats must be used. If there are options, clarify competitor rights.

See [Delegate discussion, November 13, 2013](https://groups.google.com/forum/#!topic/wca-delegates/DWqU7-IM_W4).

**Comment by lgarron** [comment]
[One station at BASC 4 was missing a mat.](https://groups.google.com/forum/#!msg/wca-delegates/JUCzPfnID2Y/Wjmi7Ce3S08J)

**Comment by lgarron** [comment]
[Report for Back To Cubing Hong Kong 2015](https://groups.google.com/forum/#!msg/wca-delegates/AF42_R_D334/4kO0QJK-gtQJ): None of the competitors in the feet event used mats. Everyone is now on the same pag e(mats are mandatory), but Natán wrote:

> Hey WRC people,
> 
> Are there any plans to change this regulation? I have terrible memory but I think that the last time this issue came up, it was sort of agreed that we were going to continue having mats as mandatory. I think most arguments favored equal conditions across competitions, surface protection and timer stability provided by mats. And I distinctly remember that we said competitions are more fun with Mats, :P

**Comment by Laura-O** [comment]
I think this is not an issue in competition anymore.
Furthermore, we have defined requirements for mats in the 2016 regulation changes, so I am closing this issue.
