### ISSUE TITLE
2i2a+ should read A monitor

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#901]
> - 2i2a+) [ADDITION] The monitor of a camera can be visible to the competitor as long as it does not show the live feed of the camera.

Cameras can have multiple monitors. The specific case that this addition is for when a camera has a display of the times, mode, etc on the front of the camera and potentially another monitor on the back for the live feed.

- 2i2a+) [ADDITION] **A** monitor of a camera can be visible to the competitor as long as it does not show the live feed of the camera.

**Comment by lgarron** [comment]
There is also the possibility of streaming to a phone or other device. Can you think of a way to phrase it that also covers this?

**Comment by Jambrose777** [comment]
How does this sound?

2i2a+) [ADDITION] A monitor of a camera can be visible to the competitor as long as it does not show the live feed of **the puzzle or solver**.

**Comment by hanwu85** [comment]
> live feed of **the puzzle or solver.**

What if the live feed is showing an audience passing cheating signal?  (parity or not..etc)

**Comment by lgarron** [comment]
Thanks, @Jambrose777!
