### ISSUE TITLE
H1+ should read scramble instead of puzzle

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#902]
> - H1+) [ADDITION] If a duplicate **puzzle** is found during an attempt, the puzzle may be re-scrambled using an unused scramble, at the discretion of the WCA Delegate.
- H1+) [ADDITION] If a duplicate **scramble** is found during an attempt, the puzzle may be re-scrambled using an unused scramble, at the discretion of the WCA Delegate.

As well unused is a bit vague here as it could mean:
1) nobody has yet to receive the scramble
or
2) the competitor has not received the scramble

**Comment by lgarron** [comment]
Hmm, I wanted to keep this concise. I think "puzzle with a duplicate scramble" would be okay, though.

Ideally, I'd like to add extra scrambles to TNoodle. Do you have a suggestion for how rephrase "unused" while keeping it concise?

**Comment by Jambrose777** [comment]
Maybe something similar to 11e1?

H1+) [ADDITION] If a **puzzle with a duplicate scramble** is found during an attempt, the puzzle may be re-scrambled using a **different scramble sequence**, at the discretion of the WCA Delegate.

**Comment by xsrvmy** [comment]
@Jambrose777 "different" is ambiguous (it's not clear it must be different to every other puzzle in the attempt)
We could ask extra scrambles to be used, but does Tnoodle generate MBLD extras?

**Comment by Jambrose777** [comment]
> @Jambrose777 "different" is ambiguous (it's not clear it must be different to every other puzzle in the attempt)
> We could ask extra scrambles to be used, but does Tnoodle generate MBLD extras?

It's the exact wording used in 11e1, which is for extra attempts.

**Comment by Ivan-Brigidano** [comment]
Thanks for spotting it @Jambrose777
