### ISSUE TITLE
C1b4 is a duplicate of A5c

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#903]
>  - A5c) The competitor may hold the puzzle against the surface to help operate the puzzle (see [Regulation 7f1d](regulations:regulation:7f1d)).

>  - C1b4) During the solve, the competitor may hold the puzzle against the surface to help operate the puzzle (see [Regulation 7f1d](regulations:regulation:7f1d)).

Since this is being defined In Article A, C1 covers this regulation.

**Comment by xsrvmy** [comment]
I think C1b4 was added because there was argument about whether C1b bans table abuse so this should probably stay.

**Comment by hanwu85** [comment]
Yes, C1b4 is explicitly defined for One-Handed, so we don't have grey zone whether using table during OH is okay or not.

**Comment by Ivan-Brigidano** [comment]
I think the problem that we wanted to solve is that some competitors are still confused if this is allowed for OH. Isn't it, @hanwu85 ?
However, I agree that this should be better a guideline reminder. But I agree that is fine to keep it if it helps competitors to better understand the Regulations.

**Comment by lgarron** [comment]
> But I agree that is fine to keep it if it helps competitors to better understand the Regulations.

I agree with this, since:

> Foremost, make the Regulations easy for a human to search and read, and don't let anything get in the way of accuracy and clarity.
> (https://github.com/thewca/wca-regulations/blob/draft/style-guide.md)

It's good to avoid duplication in general and a `REMINDER` Guideline might technically suffice. But it's valuable to be clear in this case because C1b) on its own could be taken to imply that it overrides A5c (which is why #718 was filed), and this is an important part for some competitors to know.

**Comment by lgarron** [comment]
I'm going to close this for now, since this was an intentional change for 2020. If it feels out of place compared to its neighbors, it's not set in stone.
