### ISSUE TITLE
Reasons to remove/keep 4BLD + 5BLD as events

### ISSUE THREAD

**Issue by asdfjklsemicolon** [thewca/wca-regulations#904]
Here is a list of pros/cons for removing 4x4 Blindfolded, and 5x5 Blindfolded as events in the WCA:

Pros

- Both 4x4 and 5x5 Blindfolded have some of the lowest participation rates of any WCA event and are some of the rarest events to be hosted at official competitions (Only 47 people have official 5BLD means).
- It is logistically challenging to host and requires extra equipment. Usually, comps need to be hosted specifically for these events, and at large/championship comps an extra room that is quiet is needed. Additionally, it requires extra equipment such as harmonica holders to hold a sight blocker unless you want to have a judge assigned to every competitor (which has its own problems.)
- 4x4 Blindfolded and 5x5 Blindfolded both have the highest and second-highest DNF rates of any event.
- It is one of the most time-consuming events to host, usually requiring an hour or more, even just for a few competitors.
- In terms of uniqueness, it has the same basic fundamentals as 3x3 blindfolded, just with more algs and more memo needed.

Cons

- Removing 4x4/5x5 Blindfolded would allow for no more official solves/results in either of those events, which would disappoint those who have put time into the event.

Neutral points
- Feet is not a very spectator friendly event, however, almost nobody watches it anyways.

**Comment by KitClement** [comment]
What a great, unbiased list of pros/cons you got there.

**Comment by asdfjklsemicolon** [comment]
> What a great, unbiased list of pros/cons you got there.

I mean, you could look at the WRC and say the same thing...

**Comment by UnderwaterCuber** [comment]
I guess we have no choice but to keep feet, if we don’t then we will have to remove these events it seems

**Comment by asdfjklsemicolon** [comment]
It is setting the precedent that the WRC can just remove events because they don't like them.

**Comment by Samuel-Baird** [comment]
> It is setting the precedent that the WRC can just remove events because they don't like them.

How?

**Comment by lgarron** [comment]
As alluded at https://www.worldcubeassociation.org/posts/removing-official-status-for-3x3x3-with-feet , we will not consider removing additional events unless we have a clear and transparent process.

However, people are welcome to add points in this thread to help discuss the pros and cons of these events.

> It is setting the precedent that the WRC can just remove events because they don't like them.

This is inaccurate and impossible. Please refrain from conspiracy theories or other non-constructive comments here.

**Comment by ccbaird** [comment]
@lgarron All of the arguments for removing Feet (including low participation) were fully answered and refuted in the discussion about its removal, and none of those refutations were addressed in the announcement of the decision. That does not leave a lot of room for understanding why the decision was made beyond the irrefutable fact that the people in charge don't like it.

**Comment by Samuel-Baird** [comment]
> @lgarron All of the arguments for removing Feet (including low participation) were fully answered and refuted in the discussion about its removal, and none of those refutations were addressed in the announcement of the decision. That does not leave a lot of room for understanding why the decision was made beyond the irrefutable fact that the people in charge don't like it.

Saying that something has been refuted is an opinion. For almost every argument I saw in favor of keeping feet I saw a counter argument, does that mean all the reasons to keep feet were refuted and as a result the WRC shouldn't have factor them in making their final decision? No it doesn't, the WRC weighed in on points from both sides and thought them through before making their decision, just because you don't agree with points doesn't mean they are invalid.

**Comment by asdfjklsemicolon** [comment]
@lgarron Sorry if it seemed like I was accusing the WCA of removing the event just because they didn't like it. What I'm trying to say is that there aren't really any major regulatory problems with having 3x3 with feet as an event and that it seems like the biggest reason why it's being removed is that a portion of the community doesn't like it. To add to what @ccbaird said, no real arguments were presented by the WCA for its removal, besides the delegate vote, both in #652 and in the official announcement today. Compare that to when the magics were removed https://www.worldcubeassociation.org/archive/forum_topics/1013 where they were provided, and largely were because of issues regulating the event.
Now, on a side note, I fail to understand why this was done only 28 days before it will be enforced, was adding time, delaying it never an option? Because of the lack of issues with regulation, I don't see why it could have stayed for another 6 months to a year to give time to the WCA to get more concrete reasoning and community input.

**Comment by Samuel-Baird** [comment]
@lgarron @Ivan-Brigidano @Claster @KatieHull could one of you ban asdfjklsemicolon, it appears as though their account was created 3 hours ago, likely for the sole reason of harassing the WRC about the decision to remove feet

**Comment by ccbaird** [comment]
> @lgarron could you ban asdfjklsemicolon, it appears as though their account was created 3 hours ago, likely for the sole reason of harassing you and the WRC about feet

You are asking the person allegedly being harassed to deal with it?

**Comment by Ivan-Brigidano** [comment]
Closing as is a biased Issue. I encourage you to create an Issue when you take GitHub as a serious tool and not as a children's game.
