### ISSUE TITLE
Reasons to keep or remove Pyraminx as an event

### ISSUE THREAD

**Issue by OrangeGreenCuber** [thewca/wca-regulations#906]
Hi,

With the discussion on here as of late, I think that this is just as valid as some of the recent stuff.  While I'm not personally thrilled about feet being removed, Pandora's box has been opened.

Cons of keeping

- Nobody practices pyraminx but everyone registers
- People don't like competing in it, but they register
- It takes up forever on the schedule
- Tips
- Doesn't follow White top Green Front
- Is super fast
- Timer stops are hard to judge
- The wrist-tricks are very much similar to magic and could cause someone to elbow someone else.
- They're very pointy and could be used as a weapon

Pros of keeping
- Gets people into trying other events
- Cube manufacturers make more money.

Also, this is not meant as an attack on anyone.  I value the WRC and their opinions.  That's why I submit these issues.  As a reminder, please be civil.  Not everyone likes pyraminx, and not everyone hates pyraminx.

**Comment by asdfjklsemicolon** [comment]
I know I suggested the removal of 4/5BLD, however, please try and think to yourself about how reasonable your requests are before posting them here. Points 1 and 2 are false, 5 and 6 are irrelevant and meaningless, and 8 and 9 are just stupid.

**Comment by OrangeGreenCuber** [comment]
I'd say these are reasonable requests.

In my experience, lots of people average 20 something seconds on pyraminx.  That's really only possible from not practicing.  Also, nearly everyone registers for pyraminx at comps I attend.

5 and 6 aren't irrelevant and meaningless.  5 is about consistency.  6 and 7 really go hand in hand tbh.  6 probably could have been removed since it's redundant in terms of 7.  I'll admit that.

8 and 9 are very serious.  We need competitions to be safe.

**Comment by asdfjklsemicolon** [comment]
Even though many people don't practice, it is still false to claim that "nobody does". Skewb isn't scrambled with white top green front, neither is square-1, so if this is about consistency, then there are other things that need to be addressed...
Lastly, your fists would make a better weapon than a pyraminx.

**Comment by OrangeGreenCuber** [comment]
My fist is not pointy, so I don't get how that's a better weapon.
Square-1 does have the same problem.
Nobody is only meant to refer to most people.  Sorry for the generalization.

**Comment by Ivan-Brigidano** [comment]
Closing as is a biased Issue. I encourage you to create an Issue when you take GitHub as a serious tool and not as a children's game.
