### ISSUE TITLE
Interpreting FMC solutions based on context

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#907]
This is sort of systematic leniency, but it can be codified.
There are several different types of ambiguous symbols in FMC:
- A symbol is ambiguous between valid and invalid notation, eg. u vs U, g vs y (cursive), 2 vs Z
- A symbol is ambiguous between two valid notation, but
  - it looks closer to one symbol than the other, based on the rest of the solution's handwriting
  - one interpretation is much more likely than another based on surrounding moves (eg. U * U where * is ambiguous between U and L)
  - there is no way to tell

The first one usually does not result in a DNF, and the fourth one usually does. I believe the second case should not result in a DNF but this is not cleared from the regs. The third case is more debatable. Moves like U D U have appeared in solutions before (even in a former WR mean iirc).

**Comment by Samuel-Baird** [comment]
I would say allow the moves as long as the intention is unambiguous. If a letter is sloppy and you can’t tell if it’s U or L then DNF, if a competitor used u instead of U then the intention is unambiguous.

**Comment by xsrvmy** [comment]
@UnderwaterCuber the argument is that a letter can look like U or L without the rest of the solution, but if you look at the handwriting of the rest of the solution it can be much closer to one than the other. (This happened when grading a solution at FMC Americas. Me and the delegate agreed to accept the solution)

**Comment by casiku** [comment]
Graders already do this anyway, so I support this idea
