### ISSUE TITLE
Remove Pyraminx as an official event

### ISSUE THREAD

**Issue by casiku** [thewca/wca-regulations#910]
Pyraminx is commonly a hated event. I will summarize some common issues with the puzzle.

- Tips do not require cognitive thinking. A monkey can solve tips.
- Body does not require cognitive thinking. It can be solved by solving one face over and over until it is solved.
- Timer stops. Just like cup stacking, this event's main talent is dexterity. This is not in the spirit of WCA. It also makes the event hard to judge.
- We already have skewb, which has the same body like pyraminx.
- Hardware has not developed significantly in the past years.
- Pyraminx do not fit in cube covers properly. Often you can see the tip, even though the cover is pressed down on the puzzle.
- Most people participating compete, even though they don't practice or like the event. This has a negative effect on the social community, because of hate speech. It is not a competitive event.
- It is highly dependent on scrambles. Since the event is so common, it is not possible to give everyone the same scramble sets, and this is unfair.

**Comment by Ivan-Brigidano** [comment]
Is that hard to be serious?
