### ISSUE TITLE
Official Report Relating to the Removal of Feet

### ISSUE THREAD

**Issue by spencerchubb** [thewca/wca-regulations#915]
The WRC should publish an official report thoroughly explaining the process by which they decided that 3x3x3 With Feet would be removed as well as listing the arguments and counterarguments that they considered for and against the decision. If the WRC fails to do so by January 1, 2020, they must repeal the decision and allow feet to remain as an event. 

To understand why they should do this, continue reading.

. . . 

“We would also like to take this time to apologize for the flaws in the process used for this decision. We have learned greatly from the community's feedback, and will prioritize a clear and transparent process for event changes in the future.” - Lucas Garron

He recognizes that the WRC has been secretive about the removal decision and claims they will improve in the future, however this reparation will not alleviate any of the current damage. If the WRC cares about the community, it is imperative that they make it clear how the final decision was agreed upon. If the decision was in fact fair and carefully considered, this task should be quite simple for the WRC. On the contrary, their failure to complete the report in a timely manner will be evidence that the decision was sloppy and biased, and therefore, should be repealed.

A report is necessary for the entire WCA community because communication has been disjointed and unclear. Although discussions have happened on Github, Facebook, forums, in private among the WRC, and many other places, there has not been a solid synthesis of all the information. We require this report from the WRC or else their credibility will be severely hindered. Any reputable organization must be able to strongly defend their choices, especially those that have long-lasting and widespread impacts.

The timeframe I propose, which is completion by the beginning of 2020, may seem extreme at first, but keep in mind that this length of time is precisely what the community was given when we were notified that the event will be removed. If the WRC feels that this time is not sufficient for drafting such a report, they may choose to remove the event at a later date and release the report at that time. We should expect this high standard given that the WRC expects us to accept new changes at an equally short notice.

Sincerely,
Spencer

**Comment by KitClement** [comment]
> If the WRC fails to do so by January 1, 2020, they must repeal the decision and allow feet to remain as an event.

I find it humorous that you believe yourself to be able to impose such an implication.

This does not belong on the GitHub issues, as it has nothing to do with suggesting changes to the regulations. If you would like a report on the process, contact the WRC and WCA Board directly.

**Comment by spencerchubb** [comment]
> >
> This does not belong on the GitHub issues, as it has nothing to do with suggesting changes to the regulations. If you would like a report on the process, contact the WRC and WCA Board directly.

I find it not at all humorous that you thought I genuinely believed this would be enforcable. I am well aware. Thanks nonetheless for suggesting a better place to make this proposal.

**Comment by casiku** [comment]
Dear WRC,
I look forward to reading the report. I still have some faith left in your professionalism.
Imagine thinking that removing feet at short notice is a professional decision.

**Comment by KitClement** [comment]
> I still have some faith left in your professionalism.
> Imagine thinking that removing feet at short notice is a professional decision.


Imagine losing your faith one sentence later.

**Comment by casiku** [comment]
> > I still have some faith left in your professionalism.
> > Imagine thinking that removing feet at short notice is a professional decision.
> 
> Imagine losing your faith one sentence later.

So WRC made a small mistake, everyone do that. They can still save their credibility by either annulling/delaying the removal, or write an official report.
Most likely the decision was rushed by the team leader, because of the 2020 deadline. But we will never know, if they keep being secretive about large decisions like removing an event and "promising they'll do better next time" (psst clock will be harder to remove because of this)

**Comment by KitClement** [comment]
If you want transparency, then stop turning this once-productive GitHub repository into a cesspool of your whining. If I were leading this committee, I'd highly be considering just moving regulations discussions to an internal setting if this is how the community is going to act.

**Comment by lgarron** [comment]
We'll take this under consideration. However, continuing the discussion is here is not productive.
