### ISSUE TITLE
3x3 With Feet is not the least popular speedsolving event

### ISSUE THREAD

**Issue by casiku** [thewca/wca-regulations#917]
5BLD is by definition af speedsolving event and is less popular than 3WF, so the claim in the WRC announcement on WCA is false.
https://www.worldcubeassociation.org/posts/removing-official-status-for-3x3x3-with-feet

**Comment by KitClement** [comment]
The regulations github is for suggesting productive changes to the regulations. Comments about a WRC announcement should be directed at the WRC directly via email.

That being said, to respond to your critique, it's not really clear what definition you using as a basis. The only event that does not have a speed element is fewest moves, and a dichotomy of 17 vs 1 events is not particularly useful. The articles being split by types of events with all blindfolded events referring to Article B (or H for MBLD) makes the difference clear between the events, even if Article B refers to Article A for baseline procedures.

**Comment by casiku** [comment]
Thank you for your feedback.
I claim that 5BLD is a speedsolving event by any possible definition. You simply solve the puzzle in the fastest time possible, like any other speedsolving event. Rankings are only based on your time.
3BLD is generally accepted to be a speedsolving event, and there is not any logistical difference between 3BLD and 5BLD.
5BLD is often compared to MBLD because of the amount of memorization you need, but that is an implication of the nature of a 5x5 puzzle, not the type of speedsolving/non-speedsolving event.

Like you mention, 5BLD is a speedsolving event as defined by the regulations too. In article B, the first sentence says that "standard speed solving procedures are followed", just like article C (one-handed) says the same, and etc.

**Comment by ccbaird** [comment]
The division of events into speedsolving and blind solving events, and FMC as a third category, is a common and well-established one. Occasionally Feet and OH are counted in a fourth category.

**Comment by casiku** [comment]
OH is not a speedsolving event? lmao

**Comment by ccbaird** [comment]
>OH is not a speedsolving event? lmao

Only inasmuch as there is more to it than “how fast can you solve this puzzle?”

**Comment by casiku** [comment]
If OH is not a speedsolving event, then WF is not a speedsolving event either, making the WRC statement even more false
