### ISSUE TITLE
Proposal: Reconsidering the pins at clock to not beeing part of the scramble anymore

### ISSUE THREAD

**Issue by AlexICG** [thewca/wca-regulations#918]
Be aware that I know of the rejected pin state proposal of the 2020 draft. I just think that my proposal is quite different and better.

Proposal: Eliminating the pin state from clock scrambles. This is meant as followed:
1) Scrambles will not have a specific pin state at the end. 
2) The competitor is allowed to change the pin state in his/her inspection time
3) Judge and scrambler are not obligated to maintain a certain pin state (eg. the scramblers could push or pull all pins and the judge may lay the clock face down on the solving station)
 
This would definitely make it a lot easier to hold clock at competitions in various aspects. The only con, I can think of, is that this is an advantage that future clock solvers will have in comparison to clock solvers that competed with the old reg in terms of their PBs, but that seems to be a rather weak con.

**Comment by casiku** [comment]
I think that's a good idea. Organizers are currently unhappy with the clock event, so we should try different formats to improve the event. If we discover that clock is inherently a bad event, we can then justify the removal of clock as an event.

**Comment by Samuel-Baird** [comment]
Issues that would be fixed:
 * Some scramblers have had issues with pins (thinking up is down and down is up), which has lead competitors results being DNFd. 
 * If judges knock over the clock while lifting the cube cover than the competitor has to receive an extra. 
 * Runners can accidentally mess up the pin state which can to be corrected or can result in misscrambles being given.
 * Competitors with magnetic clocks can easily DNF in inspection by bumping a pin.

Negative outcomes:
 * Older competitors would be at a small disadvantage
 * it is possible to make moves on clock by turning pins, competitors may be able to do this if judges think they are just altering pin state
 * no other event allows for mechanical movement of the puzzle during inspection, judges could easily get confused about this

**Comment by TheMagicCuber** [comment]
> Be aware that I know of the rejected pin state proposal of the 2020 draft. I just think that my proposal is quite different and better.
> 
> Proposal: Eliminating the pin state from clock scrambles. This is meant as followed:
> 
> 1. Scrambles will not have a specific pin state at the end.
> 2. The competitor is allowed to change the pin state in his/her inspection time
> 3. Judge and scrambler are not obligated to maintain a certain pin state (eg. the scramblers could push or pull all pins and the judge may lay the clock face down on the solving station)
> 
> This would definitely make it a lot easier to hold clock at competitions in various aspects. The only con, I can think of, is that this is an advantage that future clock solvers will have in comparison to clock solvers that competed with the old reg in terms of their PBs, but that seems to be a rather weak con.



> Issues that would be fixed:
> 
> * Some scramblers have had issues with pins (thinking up is down and down is up), which has lead competitors results being DNFd.
> * If judges knock over the clock while lifting the cube cover than the competitor has to receive an extra.
> * Runners can accidentally mess up the pin state which can to be corrected or can result in misscrambles being given.
> * Competitors with magnetic clocks can easily DNF in inspection by bumping a pin.
> 
> Negative outcomes:
> 
> * Older competitors would be at a small disadvantage
> * it is possible to make moves on clock by turning pins, competitors may be able to do this if judges think they are just altering pin state
> * no other event allows for mechanical movement of the puzzle during inspection, judges could easily get confused about this

I honestly think that this would be a good change. You could make the comparison to feet with how older competitions would have a disadvantage in that in previous comps, only inspection with feet was allowed. Once it changed to hands also, older comps were put at a disadvantage. So, I think that having a new change that is similar wouldn’t be bad.
With changing pin state in inspection, I think this is something to really consider due to no other puzzle having this feature in competition. A possible compromise would be that the scrambler would send out the puzzle with all pins up, and once the cover is lifted, the competitor would be allowed to have all pins up or all pins down. That would be the only change and would only give a slight advantage as to which side you start with. 
With this change, you would have to have judges that know what they are doing and can watch both the inspection timer and the competitor to make sure no gear turns are made (and if my compromise is taken, that either all pins are up or down). This would take more time to train judges, but similarly, BLD has a different way of judging that others need to be trained for if they have only judged sighted, so I don’t believe this would be a big issue. 

I am for this honestly, I don’t think it would affect times drastically, but I could see times decrease depending on scrambles

**Comment by KitClement** [comment]
This has been proposed many times before. The biggest issue is that it is incredibly difficult to detect if a move is being performed on a clock visually, but it is easy to detect aurally. Now that clocks are magnetic, the sound of a pin moving is fairly noticeable, and also similar enough to the clock being turned on the gears. Currently, any pin movement or gear movement would make a noise, which is easy to detect, but telling apart the two is more difficult. The gears can also be turned by turning the pins, which could also be hard to detect by the judge. I'm more concerned about how this would drastically lower the floor on clock times, but the added difficulty to judge is my second concern.

**Comment by AlexICG** [comment]
> > Be aware that I know of the rejected pin state proposal of the 2020 draft. I just think that my proposal is quite different and better.
> > Proposal: Eliminating the pin state from clock scrambles. This is meant as followed:
> > 
> > 1. Scrambles will not have a specific pin state at the end.
> > 2. The competitor is allowed to change the pin state in his/her inspection time
> > 3. Judge and scrambler are not obligated to maintain a certain pin state (eg. the scramblers could push or pull all pins and the judge may lay the clock face down on the solving station)
> > 
> > This would definitely make it a lot easier to hold clock at competitions in various aspects. The only con, I can think of, is that this is an advantage that future clock solvers will have in comparison to clock solvers that competed with the old reg in terms of their PBs, but that seems to be a rather weak con.
> 
> > Issues that would be fixed:
> > 
> > * Some scramblers have had issues with pins (thinking up is down and down is up), which has lead competitors results being DNFd.
> > * If judges knock over the clock while lifting the cube cover than the competitor has to receive an extra.
> > * Runners can accidentally mess up the pin state which can to be corrected or can result in misscrambles being given.
> > * Competitors with magnetic clocks can easily DNF in inspection by bumping a pin.
> > 
> > Negative outcomes:
> > 
> > * Older competitors would be at a small disadvantage
> > * it is possible to make moves on clock by turning pins, competitors may be able to do this if judges think they are just altering pin state
> > * no other event allows for mechanical movement of the puzzle during inspection, judges could easily get confused about this
> 
> I honestly think that this would be a good change. You could make the comparison to feet with how older competitions would have a disadvantage in that in previous comps, only inspection with feet was allowed. Once it changed to hands also, older comps were put at a disadvantage. So, I think that having a new change that is similar wouldn’t be bad.
> With changing pin state in inspection, I think this is something to really consider due to no other puzzle having this feature in competition. A possible compromise would be that the scrambler would send out the puzzle with all pins up, and once the cover is lifted, the competitor would be allowed to have all pins up or all pins down. That would be the only change and would only give a slight advantage as to which side you start with.
> With this change, you would have to have judges that know what they are doing and can watch both the inspection timer and the competitor to make sure no gear turns are made (and if my compromise is taken, that either all pins are up or down). This would take more time to train judges, but similarly, BLD has a different way of judging that others need to be trained for if they have only judged sighted, so I don’t believe this would be a big issue.
> 
> I am for this honestly, I don’t think it would affect times drastically, but I could see times decrease depending on scrambles

The Problem with all pins up/down is, that it is a disadvantage to the current regs, since you cant have a pin skip for the first move anymore, which would be unfair towards future competitions and thats the direction we shouldnt go.

**Comment by AlexICG** [comment]
> This has been proposed many times before. The biggest issue is that it is incredibly difficult to detect if a move is being performed on a clock visually, but it is easy to detect aurally. Now that clocks are magnetic, the sound of a pin moving is fairly noticeable, and also similar enough to the clock being turned on the gears. Currently, any pin movement or gear movement would make a noise, which is easy to detect, but telling apart the two is more difficult. The gears can also be turned by turning the pins, which could also be hard to detect by the judge. I'm more concerned about how this would drastically lower the floor on clock times, but the added difficulty to judge is my second concern.

Honestly this is something that we should try out. I am pretty certain that noticing such a move on the judges side will not be noticed significantly less then with current regs. I didnt even knew about that before yesterday when you told me and I would have not noticed this while judging.

**Comment by xsrvmy** [comment]
> Issues that would be fixed:
> 
> * Some scramblers have had issues with pins (thinking up is down and down is up), which has lead competitors results being DNFd.
> * If judges knock over the clock while lifting the cube cover than the competitor has to receive an extra.
> * Runners can accidentally mess up the pin state which can to be corrected or can result in misscrambles being given.
> * Competitors with magnetic clocks can easily DNF in inspection by bumping a pin.
> 
> Negative outcomes:
> 
> * Older competitors would be at a small disadvantage
> * it is possible to make moves on clock by turning pins, competitors may be able to do this if judges think they are just altering pin state
> * no other event allows for mechanical movement of the puzzle during inspection, judges could easily get confused about this

Another one: knocking over the clock would probably no longer be a DNF (I've DNFed an average because of this before)

**Comment by CadyShields** [comment]
With specialized clock covers and clock stands becoming standard practice, I don't see why pins is a big issue anymore.
Allowing pins to be moved during inspection makes it the only event where moves can be made during inspection. That can be difficult to explain to inexperienced judges. Not to mention that this gives an unfair advantage to future results as opposed to past ones. 
Pin scramble states often influence what side you start on which can drastically change how the solve goes (lucky cases, skips, etc). I have more of an issue with undefined pin states than the all up/all down proposal.

**Comment by Ivan-Brigidano** [comment]
For your information, this proposal was debated but the WRC didn't reach a consensus. The main reasons:

1. It would make the event even more difficult to judge
2. It would make new results completely incomparable with current ones
3. There were other regulations change alternatives more reasonables

**Comment by aedanbryant** [comment]
Yes future results would have an advantage over past results, however this has happened with many other events also, such as feet with inspecting with your hands, and even all the other events with hardware improvements over the years. This change wouldn’t drop my times by too much because pins only take like .1 seconds to push when I pick up the puzzle (for reference I average ~5.0 seconds). Not being able to tell if someone has made a move or not is a big thing, but if you just watch someone inspecting you should be able to see if their moving the pin or turning a gear. Lastly I think this would make clock easier to compete in, when I’m scrambling clock at comps, there are always at least a few clocks that are illegal because the pins fall, this would make those competitors able to compete and not have to find another clock or just quit the round.

**Comment by Samuel-Baird** [comment]
> Yes future results would have an advantage over past results, however this has happened with many other events also, such as feet with inspecting with your hands, and even all the other events with hardware improvements over the years. This change wouldn’t drop my times by too much because pins only take like .1 seconds to push when I pick up the puzzle (for reference I average ~5.0 seconds). Not being able to tell if someone has made a move or not is a big thing, but if you just watch someone inspecting you should be able to see if their moving the pin or turning a gear. Lastly I think this would make clock easier to compete in, when I’m scrambling clock at comps, there are always at least a few clocks that are illegal because the pins fall, this would make those competitors able to compete and not have to find another clock or just quit the round.

Those clocks would still be illegal :P

**Comment by AlexKatyukov** [comment]
I'd like to say "Good", "Yes". But with Cady clock covers the problem is really less than earlier.
