### ISSUE TITLE
Reconsidering +2 penalty on clock

### ISSUE THREAD

**Issue by XuLx** [thewca/wca-regulations#919]
I know this has already been discussed in #381 . However, since that one is closed now I would like to propose a new one.

My main concern is this state: On the backside (touching the mat), all but the corners are solved; on the frontside, all clocks point to the same direction (e.g. 6 o'clock). Since all pins are pushed upward after you throw the clock onto the table (in most cases), all you need to do is 1 move of the cogs. In order to be consistent with other events, I think this should definitely be considered as a +2 rather than a DNF. 

Whether allowing other "1 move" cases to be considered as +2 or DNF depends on how you define "1 move". If you regard manipulating pins as moves, then all the 1-move cases have been described above, except extreme cases such that not all pins are pushed upward at the end of the solve (which is nearly impossible).  If you only regard turning cogs as moves, then things can be much more complicated, as described in #381 .

**Comment by LLayug** [comment]
I don't personally find it too faulty but my concern is that if the judge isn't too familiar with how clock moves work, it would make clock a bit harder to judge. At this point, clock in itself is pretty tough to hold in competitions and is pretty difficult to judge especially without experience; adding this would make it even harder to hold.

**Comment by Samuel-Baird** [comment]
There are 154 clock states that are 1 move away from the solved state. The event with the current highest amount of possible +2s is megaminx with 48 states away from 1 move. 

For most events it’s easy to tell judges “if it’s a move away from solved then it’s a +2” it’s pretty easy for almost anyone (even noncubers) to be able to tell that it is a +2. 

With clock people are far less familiar with how clock works and moves often don’t make sense unless you have tried the puzzle out before, just telling judges “if everything is at 12 it’s ok” is a lot easier than giving them a briefing on what is and isn’t a DNF

**Comment by Ivan-Brigidano** [comment]
The reason why Clock doesn't have a +2 penalty for misalignment is quite easy. Is not obvious how to solve a Clock at only "one move". For example, let's see at this case:

![IMG_4374](https://user-images.githubusercontent.com/47502355/70272678-ef013600-17a8-11ea-9ed8-a9d7e01b6df9.jpeg)

For a Clock solver is obvious that you have to push up the top pin and then turn one clockwise the top wheel. But this isn't intuitive for someone that doesn't know how to solve the puzzle.

**Comment by XuLx** [comment]
The whole point of this proposal is to count the 1-move cases **without manipulating pins**  as +2 states. I don't personally think other "1-move" cases should be considered as 1-move under current regulations, since manipulating pins are not allowed during inspection time and thus manipulating pins is actually considered as "1-move".

**Comment by Ivan-Brigidano** [comment]
> The whole point of this proposal is to count the 1-move cases **without manipulating pins** as +2 states. I don't personally think other "1-move" cases should be considered as 1-move under current regulations, since manipulating pins are not allowed during inspection time and thus manipulating pins is actually considered as "1-move".

Still, it wouldn't be obvious to solve for non-clock solvers. In addition, how would we define what a +2 is?

**Comment by XuLx** [comment]
> The whole point of this proposal is to count the 1-move cases without manipulating pins as +2 states. I don't personally think other "1-move" cases should be considered as 1-move under current regulations, since manipulating pins are not allowed during inspection time and thus manipulating pins is actually considered as "1-move".
> 
> Still, it wouldn't be obvious to solve for non-clock solvers. In addition, how would we define what a +2 is?

I admit that it might not be obvious for non-clock solvers to solve such a state. However, in practice it's not that hard to teach judges about this. At least it's no harder than judging whether some square-1 cases are 1 move from solved state.

For definition, the phrase "one move" in Article 10 seems to be a bit unclear. To my knowledge, "one move" should correspond to a certain metric. We can add a new item as below:
12g5) Metric for clock: turning a wheel counts as one move, pushing any number of pins counts as one move.
Then after deleting 10h), 10e3) will automatically define what a +2 is. It's arguable whether a 15 degrees limit should be added to 10f). Another explanation about this should also be added to the guidelines.

By the way, in the current version of regulations, metrics for puzzles other than NxNxN are not explicitly defined. For pyraminx and skewb the "scramble metric" suffices so it seems to be fine. For megaminx and square-1, although 12d) and 10f4+) are trying to clarify what "one move" is, the wording can be further improved. It would be best if metrics for theses puzzles are defined explicitly in the regulations, but this is another issue which probably should not be discussed here.

**Comment by xsrvmy** [comment]
For nxn we do have OBTM. We actually need that metric because FMC.
I have a strong argument against considering pushing a pin a move: the surface would perform a move on the clock during/after the timer stops if the ALL move is skipped.
