### ISSUE TITLE
Change DNF to DQ?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#92]
There is frequent confusion about "did not start" vs. "did not finish".

The current usage of DNF is basically equivalent to DQ, and the Regulations use the word "disqualification" quite a bit.
DQ dissociates the penalty (your time doesn't count) from "you didn't finish the puzzle". If I stopped the cube while holding it, the solved may be disqualified, but arguably I also finished.

DNF does have [some precedent](http://en.wikipedia.org/wiki/Did_Not_Finish) in racing, but I'm much more familiar with "DQ" for various sports.
# DNS

DNS is only used in [9f](https://www.worldcubeassociation.org/regulations/#9f) and 9f5+:

> [9f5+](https://www.worldcubeassociation.org/regulations/guidelines.html#9f5+)) CLARIFICATION The result for an attempt is DNS if the competitor was eligible for the attempt and did not attempt it. If the competitor did not qualify for an attempt (e.g. in a combined round), he does not have any result for the attempt.

**Comment by lgarron** [comment]
Here's every use of `DNF` in the Regulations and Guidelines right now:

> - 5b1) If a competitor chooses to repair the puzzle, he must repair only the defective pieces. Tools and/or pieces of other puzzles must not be used to repair the original puzzle. Penalty: disqualification of the attempt (DNF).
> - 5b2) Any repair to a puzzle must not give the competitor any advantage in solving the puzzle. Penalty: disqualification of the attempt (DNF).
> - 5b4) During blindfolded events, a puzzle defect must be repaired during the attempt, and all repairs must be performed blindfolded. Penalty: disqualification of the attempt (DNF).
> - 5b5c) If more than one part with one coloured face is affected, the puzzle is considered unsolved (DNF).
> - 5b5d) If one or more parts with more than one coloured face is affected, the puzzle is considered unsolved (DNF).
> - 9f4) The result of an attempt is recorded as DNF (Did Not Finish) if the attempt is disqualified or unsolved/unfinished.
> - 9f7) For "Best of X" rounds, a DNF or DNS is the worst possible result.
> - 9f9) For "Average of 5" rounds, one DNF or DNS is permitted to count as the competitor's worst result of the round. If a competitor has more than one DNF and/or DNS result in the round, his average score for the round is DNF.
> - 9f11) For "Mean of 3" rounds, if the competitor has at least one DNF or DNS result, his average score for the round is DNF.
> - 9f12c) For Multiple Blindfolded Solving, rankings are assessed based on number of puzzles solved minus the number of puzzles not solved, where a greater difference is better. If the difference is less than 0, the attempt is considered unsolved (DNF). If competitors achieve the same result, rankings are assessed based on total time, where the shorter recorded time is better. If competitors achieve the same result and the same time, rankings are assessed based on the number of puzzles the competitors failed to solve, where fewer unsolved puzzles is better.
> - 10e4) If more than one move is required, the puzzle is considered unsolved (DNF).
> - A1a2) Cumulative time limits may be enforced (e.g. 3 attempts with a cumulative time limit of 20 minutes). The time elapsed in a DNF result counts towards the cumulative time limit.
> - A1a4) The competitor must end each attempt within the time limit. If a competitor reaches the time limit for an attempt/round, the judge stops the attempt immediately and record the result as DNF. Exception: Multiple Blindfolded Solving (see [Regulation H1b1](regulations:regulation:H1b1)).
> - A1c) A competitor participating in an event must be able to fulfill the event's requirements (e.g. know how to solve the puzzle). A competitor competing with expectation of a DNF result may be disqualified from the event, at the discretion of the WCA Delegate.
> - A3b1) When the judge believes the competitor is ready, he asks "READY?". The competitor must be ready to start the attempt within one minute of being called. Penalty: disqualification of the attempt (DNF), at the discretion of the judge.
> - A3c1) The competitor must not apply moves during inspection. Penalty: disqualification of the attempt (DNF).
> - A4d2) The competitor must start the solve within 17 seconds of the beginning of the inspection. Penalty: disqualification of the attempt (DNF).
> - A5a) While inspecting or solving the puzzle, the competitor must not communicate with anyone other than the judge. Penalty: disqualification of the attempt (DNF).
> - A5b) While inspecting or solving the puzzle, the competitor must not receive assistance from anyone or any object other than the surface (also see [Regulation 2i](regulations:regulation:2i)). Penalty: disqualification of the attempt (DNF).
> - A6b2) If the timer stops before the end of the solve and displays a time of 0.06 seconds or higher, then the attempt is disqualified (DNF). Exception: if the competitor can demonstrate that the timer malfunctioned, he may receive an extra attempt, at the WCA Delegate's discretion.
> - A6e) The competitor must not touch or move the puzzle until the judge has inspected the puzzle. Penalty: disqualification of the attempt (DNF). Exception: If no moves have been applied, a time penalty (+2 seconds) may be assigned instead, at the discretion of the judge.
> - A6f) The competitor must not reset the timer until the judge has recorded the result on the score sheet. Penalty: disqualification of the attempt (DNF), at the discretion of the judge.
> - A7a3) If the result is DNF, the judge calls "DNF".
> - B3b) The competitor must not make physical notes. Penalty: disqualification of the attempt (DNF).
> - B4d) The competitor must not look at the puzzle at any point during the blindfolded phase. Penalty: disqualification of the attempt (DNF).
> - B5c) If he is not touching the puzzle, the competitor may remove the blindfold before he stops the timer. He must not touch the puzzle until the end of the attempt. Penalty: disqualification of the attempt (DNF).
> - C1b) During the solve, the competitor must use only one hand to touch the puzzle. Penalty: disqualification of the attempt (DNF).
> - C1b2) If a puzzle defect occurs, and the competitor chooses to repair it, he must repair it using only the solving hand. Penalty: disqualification of the attempt (DNF).
> - C1c) During the solve, once a competitor touches the puzzle with one hand, he must not touch the puzzle with the other hand. Penalty: disqualification of the attempt (DNF).
> - D1b) During the attempt, the competitor must only use his feet and the surface. Penalty: disqualification of the attempt (DNF).
> - D1c) During the solve, the competitor must use only his feet to touch the puzzle. Penalty: disqualification of the attempt (DNF).
> - E2c) At 60 minutes, each competitor must give the judge a legibly written solution with the competitor's name, using the notation defined for Outer Block Turn Metric (described in [Regulation 12a](regulations:regulation:12a)). Penalty: disqualification of the attempt (DNF).
> - E2e) The competitor's solution must not be directly derived from any part of the scrambling algorithm. Penalty: disqualification of the attempt (DNF).
> - E3) The competitor may use the following objects during the attempt. Penalty for using unauthorised objects: disqualification of the attempt (DNF).
> - F3) At the end of the inspection period, the competitor places the puzzle onto the mat in a standing position. He must not change the positions of any pins from their scrambled positions before the beginning of the solve. Penalty: disqualification (DNF).
> - 5b5++) [EXAMPLE] Examples of pieces physically detached, resulting in a "DNF": two 3x3x3 center caps, two big cube center pieces, a 3x3x3 edge piece, a 4x4x4 edge piece ("wing"), any combination of two pieces that both have coloured faces.
> - 5b5++++) [EXAMPLE] Example of pieces physically attached but not fully placed, resulting in a "DNF": a 3x3x3 edge piece slightly popped out.
> - A1a2+) [ADDITION] In case of a cumulative time limit, the judge records the original recorded time for a DNF on the score sheet in parentheses, e.g. "DNF (1:02.27)".

**Comment by lgarron** [comment]
Consideration: a `DQ` average vaguely suggests that the entire average (i.e. every solve) is disqualified.

**Comment by timhabermaas** [comment]
To clarify: Would you like to replace every occurrence of `DNF` with `DQ`? Or would you like to keep `DNF` for some cases (e.g. stopping the timer with an unsolved cube)?

> There is frequent confusion about "did not start" vs. "did not finish".

If people are confused by such a simple concept I doubt using `DQ` helps.

**Comment by UnderwaterCuber** [comment]
I am definitely in favor of this, DQ is much more clear than DNF

**Comment by viroulep** [comment]
If I had to guess what a "DQ" average means I would guess it means the competitor got disqualified (eg: cheating/leaving).

"Much more clear" is very subjective, "did not finish" for a cube which is not solved sounds cristal clear to me.

While DQ may make more sense in a lot of situations (eg: attempt disqualified for using hands during a feet attempt), it's rather weird to use this for a unsolved cube.
Anyhow, it's basically what Tim said, if people are confused between DNS and DNF I doubt they wont be confused between DNS and DQ(, and DNF).

In my opinion a clear explanation of some of the vocabulary used in the Regulations at the beginning of it would make things a lot clearer (eg: something built around what is in the [style guide](https://github.com/thewca/wca-regulations/blob/draft/style-guide.md#definitions) currently).

**Comment by xsrvmy** [comment]
IMO having a DQ might make more sense for some cases, eg. knocking over the cover. The convention is to give a DNF right now but the technical the meaning of a DNF requires the attempt to have been started.

**Comment by pedrosino** [comment]
I also agree with DQ for some cases. We had discussions in the Results Team about people who were caught cheating afterwards and what to do with their results (ie make all DNF or remove). That's a good case for DQ.

**Comment by xsrvmy** [comment]
We should probably use DNF only for failed attempts if DQ becomes a thing.
