### ISSUE TITLE
Not needing paper inserts to be used in Square-1

### ISSUE THREAD

**Issue by TeebooGH** [thewca/wca-regulations#920]
Pieces of paper/cardboard in Square-1s are useless.
Not only they mess the lube of the cube up, they're also annoying to insert to some puzzles.
A Square-1 puzzle won't move inside the box unless the scrambler drops the puzzle in an odd way. 
Moreover, the moves that could possibly occur while the cube is transported barely, or don't even change the scrambled position.

**Comment by Sixstringcal** [comment]
See #778 , which was closed :(

**Comment by xsrvmy** [comment]
Don't assume people all used more controllable SQ1s. A 1/0 move can definitely occur by accident on a yuxin for example.

**Comment by Sixstringcal** [comment]
I've thrown scrambled sq-1s (of my own, and while at home) at walls (not in rage, but to test if it will move).  They usually don't move.  If they do move, it's barely at all.  The force exerted on these sq-1s is much less than that.  I've tested this on various sq-1s all with poor, loose setups.

**Comment by xsrvmy** [comment]
@Sixstringcal in a scambled state? Non-cubeshape causes problems.

**Comment by weatherman223** [comment]
Wanted to pop in and mention that inserts are at the discretion of the delegate as of the moment. So technically, a delegate could decide to not use them, however its basically an unwritten reg to essentially use them at all times. I agree that inserts may no longer be needed with new hardware (volt v2) but due to most competitors using budget puzzles or not upgrading old hardware, I think it should still be a delegate decision.

**Comment by Sixstringcal** [comment]
Yes, scrambled states.  Outside of cubeshape

**Comment by Laura-O** [comment]
I can't see how throwing your own Square-1s at walls helps to determine whether paper inserts are still needed and I hope the puzzles didn't bounce back and hit your head.

There are still many competitors who use old hardware from the time when this regulation was added - just check the customer reviews people wrote for online shops. If Delegates thinks those inserts are not necessary anymore they can decide to not use them.

**Comment by Samuel-Baird** [comment]
I think disallowing absorbent inserts would be an improvement. It still solves the problem of people using old hardware while minimizing changes in the feel of the puzzle.

**Comment by xsrvmy** [comment]
@UnderwaterCuber There are apparently cube stores that require comps to use their business cards for the insert so that might not be practical.

**Comment by Samuel-Baird** [comment]
> @UnderwaterCuber There are apparently cube stores that require comps to use their business cards for the insert so that might not be practical.

If that reg were to pass then cube retailers would probably switch to plastic cards or they would do something like laminate their cards, if we wanted to give them time for the first year we could make the reg say something like “Inserts should not be made of absorbent materials”

Also lol catering the regs to suit the need of private businesses

**Comment by Claster** [comment]
Yes, definitely we won't take into account how cube stores operate when considering changing Regulation.
Regarding absorbent inserts, I'm not convinced this is an issue. Have you tried a blind testing, guessing which square-1 had a paper insert before that? Is there a statistically significant effect on results?
Anyway, there are lots of square-1s on which accidental move (1, 0) (or even more) is possible during transportation.
