### ISSUE TITLE
Code of conduct for the repo?

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#921]
In the past few days I have seen quite a few unprofessional comments on the repo (conspiracies, personal attacks, etc). Of course this is mostly because of the feet removal announcement, but also probably because recently this repo has because a lot more publicised in places like CF.

Is it time for a repo code of conduct?

**Comment by weatherman223** [comment]
There definitely needs to be a rule set for the repo now after the feet backlash. This used to be a clean place to submit issues and fixes, and new ideas, and now its being barraged with, as you said, conspiracies and attacks by a specific group of users. Having a rule set of whats deemed acceptable and what needs to be posted elsewhere should be a priority.

**Comment by Ivan-Brigidano** [comment]
The repo has been slowly increasing his number of users. I strongly agree that there is a need to introduce some kind of moderation to make it sustainable in the future.

**Comment by ccbaird** [comment]
I apologize for my role in making this change necessary. I believe that there are real problems, I would like to be part of the solutions. I don’t think that I am a good person to spearhead solving this particular problem, but I hope that I can be a productive member of the community moving forward.

**Comment by xsrvmy** [comment]
@ccbaird it's mostly some random people I've never seen on here actually.
