### ISSUE TITLE
Puzzle standards

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#923]
Some of the puzzle standards are pretty outdated, written before the days of stickerless and magnetic puzzles. It may be appropriate to update some of them. Here are some issues/concerns:
- Stickerless puzzles are susceptible to having very slightly different shades on certain colors (eg. replacement pieces) that don't really give an advantage in solves, but this arguably violates 3d2, and fixing the problem may require getting a new puzzle completely.
- Manufacturing defects should be mentioned alongside reasonable wear since they are much more common on magnetic and stickerless puzzles (plastic contamination, glue getting outside pieces, etc.)
- If there is glue stuck in the cracks of a stickerless design, getting rid of said glue usually results in a very small gap near where the glue used to be, not visible from the outside. This is not a problem for speedsolving, but is a potential issue for BLD.
- Specific to BLD, the white center will usually end up a tiny bit stickiers than the other centers after removing a logo.

**Comment by ccbaird** [comment]
Are you suggesting that slight variation in color be explicitly allowed or explicitly disallowed?

As far as blindfolded puzzles, the ban on logos is reasonable, but residual adhesive is going to wear off very quickly. Furthermore, I’m not entirely convinced it’s that big of a problem: it’s going to be no advantage to fast solvers, and will at worst only slightly increase the chance of a successful solve for a slow solver.

If I was going to cheat at blind by having distinguishable centers I would probably put a drop of essential oil or perfume on each center cap, so I could rub my finger on the cap and then itch my nose and know which center it is. With cube retailers offering scented lubes I’m really not sure how one would go about policing that aside from providing all puzzles for blindfolded events, which strikes me as a bad compromise for a few reasons.

**Comment by xsrvmy** [comment]
I am suggesting allowing the slight variation. This is a problem that is introduced only with colored plastic and the regs need to adapt to it.
