### ISSUE TITLE
Make E3a less strict

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-regulations#924]
Currently, E3a says:

> E3a) Paper (supplied by the judge) and **pens/pencils or similar** (supplied by the judge, or optionally self-supplied).

In my opinion, it should be more flexible to allow [correction fluid](https://en.wikipedia.org/wiki/Correction_fluid). They don't provide any significant advantage and can even make some solutions easier to read and understand.

**Comment by xsrvmy** [comment]
In that regard, it should also allow correction tape and eraser.
Correction tape can potentially cause a mess though.

**Comment by danielA7575** [comment]
I'd say correction fluid is a kind of "pens or similar". But eraser should be explicitly legal
