### ISSUE TITLE
Reprecussions of signing and not checking scrambles

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#925]
Are/should there be any reprecussions for a scrambler than signs a scorecard without an attempt to check the scramble? Tell-tell signs would include completely wrong SQ1 cube shape, large blocks and missing y2 is clock scramble.

**Comment by Ivan-Brigidano** [comment]
For your information, the WRC is currently discussing the repercussions about it with WCA Staff (including WCA Delegates).

**Comment by EdHollingdale** [comment]
How does this change from a pre-signature era? One of the tasks of the scrambler is to check that the scramble is correct, if they fail to do this Delegates should not be allowing them to scramble. If they are doing so deliberately then it may be appropriate to escalate to the WDC.

As a side note, this is why I don't think scramble signatures actually decrease misscrambles. Good scramblers will check the scramble as they did before, bad scramblers will continue to not follow regulations and fail to do their job, but now with one more regulation broken. The true benefit is allowing Delegates to work out which scramblers are the bad ones faster, and remove them.

**Comment by xsrvmy** [comment]
@EdHollingdale I can agree with that. I received at least two misscrambles in one round yesterday in square 1, both with incorrect cube shape, and only one of them was signed. I only decided to check the scrambles because I got overall PB on the misscramble that was not signed.
