### ISSUE TITLE
Change wording of 9q+

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#930]
Currently 9q+ reads:
> Events and rounds should have at least 2 competitors.

It should be changed to:
> Events and rounds must have at least 2 competitors.

Also, I think this may have a more appropriate place in the regs

**Comment by xsrvmy** [comment]
Why should this be changed?
There is a legitimate reason to not require 2 competitors: What if the only event a competitor registers in end up having only one competitor, and he already booked his travel and cannot cancel?

**Comment by Samuel-Baird** [comment]
Oops. I was silly and was thinking competitions instead of events for some reason
