### ISSUE TITLE
Merge 2i1c and 2i1c+

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#931]
Remove 2i1c+ and update 2i1c to "Non-Electronic hand warmers"

**Comment by Ivan-Brigidano** [comment]
Any particular thoughts of why do you think this is necessary?

**Comment by Samuel-Baird** [comment]
> Any particular thoughts of why do you think this is necessary?

It cuts an entire line off of the the guidelines while only adding 2 words to the regs.

**Comment by Ivan-Brigidano** [comment]
I think 2ic+ gives important additional information to the competitor

**Comment by Samuel-Baird** [comment]
> I think 2ic+ gives important additional information to the competitor

If we merge 2ic and 2ic+ then it’s not like we are going to throw all of the information that 2ic+ gives out the window :P

**Comment by hanwu85** [comment]
I still think 2ic and 2ic+ are fine the way they are now.
2ic states what non-electronic aids are allowed.
2ic1 states that hand warmers are allowed. (non-electronic ones)
2ic1+ gives an extra information regarding an electronic version of a hand warmer.

Or we can change the `CLARIFICATION` to `ADDITION` if that makes more sense.
