### ISSUE TITLE
2d+ seems unnecessary 

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#933]
I don't see a reason to tell people to be extra careful with securing birthdays when 2d already makes it very clear that confidential information must not be shared without consent

**Comment by Jambrose777** [comment]
This actually belongs in a Data Protection Policy, but I think it's fine to leave in the regulations until that is a thing.

**Comment by hanwu85** [comment]
At this moment, 2d and 2d+ will stay, I am going to close this issue.  @UnderwaterCuber if you have other ideas or concerns, please feel free to reopen this issue or make a new one.
