### ISSUE TITLE
11e1+ seems redundant

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#934]
Is it just me or is 11e1+ almost the exact same as 11e1? The only difference is the "unmodified scramble sequence" which could probably be added to 11e1 easily.

> 11e1) If a competitor is granted an extra attempt, the extra attempt must be scrambled using a different scramble sequence. This scramble sequence must be generated using a current official version of an official WCA scramble program (see Regulation 4f).

> 11e1+) [REMINDER] The extra attempt must be scrambled using an unmodified scramble sequence generated by an official scramble program (see Regulation 4f, Guideline 4f+).

**Comment by Mollerz** [comment]
It was common place many years ago to reverse the scramble sequence (not inverse) of a scramble for an extra to provide a different state. This was prevented from happening with 11e1+.

**Comment by xsrvmy** [comment]
@Mollerz I assume that was before random state 3x3? I don't think reversing would preserve randomness
