### ISSUE TITLE
Proposal: Anything goes for clock

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#937]
Given that we are allowing distinguishable pins, I am proposing allowing any functional clock as long as:
- It is solvable
- Each clock has a clear direction it is pointing at
- There is a 12 o'clock indicator on each clock
- It does not bear information that can be used to cheat
- The back of the clock is not visible from the from (eg. no transparent individual clocks)

This would fix a lot of issues with clocks being rejected for cracks, scratches, etc.

**Comment by HippolyteM** [comment]
The main reasons clock are being rejected is because the button can't stand in place and it's almoste impossible to have them correctly scrambled. New magnetic clocks don't have this issue but many competitors are sill using older ones.
I've never seen clock rejected for scratches?
