### ISSUE TITLE
Make a "judging system" which is not mandatory but highly recommended

### ISSUE THREAD

**Issue by LLayug** [thewca/wca-regulations#938]
I would like to bring up an issue that I believe may be worth a certain amount of discussion, involving the system of officiating competitions, specifically judging. Where I am from (Metro Manila, PH), judges do the following:
1) Go to the scramblers area and take a cube
2) Call the competitor
3) Judge the attempt
4) Return the cube to the scrambling area and repeat

Based on my knowledge and knowledge of delegates here, this isn't the "normal" way of how judging works. In the "normal" way, there is a runner and a judge, wherein the runner does 1,2, and 4 while the judge does 3. With that being said, I have found some issues with our current way of judging. First of all, it is, to an extent, hard for some foreigners who are used to the normal way to adjust to the way we do it here, and vice versa. Granted, this shouldn't be too big of an issue. The bigger issue is that the current system that is ran here provides a small window of opportunity for cheating. This happened during a competition I organized earlier this year which involved two specific competitors getting very good results for rounds where they judged each other. As much as we were not completely sure about what actually happened, we were very suspicious, and a lot of details pointed out that they could have cheated, but at the end of the day, we could not guarantee they cheated, and let the results be. As much as this isn't a case of cheating, it proves that this type of judging system opens a wide opportunity for competitors and judges to cheat. The difficulty of this is that it isn't easy to switch from the current system to the normal one. We actually attempted to switch during another comp this November, but the competition ran a lot slower, and we had to revert back to the original. For one, pretty much all the competitors were not used to the system, and many were confused as to what to do. Also, the normal system requires a lot more volunteers. With running-judges, you would only need an amount of volunteers that matches the amount of timers, while with the normal system, you would need that amount and around 1-3 extra to serve as runners. Not a lot of people volunteer to judge here, and most competitors leave the competition area when it is not their time to compete. I thought it was necessary to bring this up since the regulations page doesn't mention anything about runners. I think we should either find an optimal system for judging that limits possibilities of cheating or at least choose one that would be required for consistency purposes.

**Comment by HippolyteM** [comment]
Hi,
I would like to point out that your system whithout runners is very common around the world. In France we alternate between both systems depending on several factors. Usually a system is used for a whole competition depending monstly on the number of competitors per groups and free space available in the venue (judges that are also runners result in many more people walking around at the same time). It also happened that both system are used in a single competitions depending on the events.
I don't really have a strong opion on this, but even if the point you brought is a valid one, I like the felxibility that we currently have which allow to select the better system for every round.

**Comment by ccbaird** [comment]
Unless I’m understanding wrong, having a judge leave the timing station to go to the scrambling station, the competitor waiting area, and back to the timer means that the timing station is unused for that time. That means that your system uses staff slightly more efficiently, but timers much less efficiently. 

As far as the possibility of cheating, no system is completely foolproof. Reasonable precautions should be taken, and people who cheat should be subject to strong censure, but at some point we just have to trust people. The vast majority of the time people will live up to the expectations placed on them: cheaters or not cheaters. The real question is how to handle exceptions.

**Comment by xsrvmy** [comment]
Several objections to forcing a no-runner judging system:
- This does not really save competition resources. Either you need spare judges to use up a timing station, or you are leaving timing stations empty.
- There will be way too many people walking around, so higher potential of bumping into competitor's which could be an unnecessary extra.

That being said, the American judging system does make it harder to track down what happened if a scrambler finds a judge signature missing.

**Comment by saranshgrover** [comment]
I don't think it makes sense to force any one of these 'systems' onto competitions. If a new system rolls around, or if someone wants to do a competition differently, they should be allowed to as long as the system follows the regs (which both of these do)

Both systems have pros and cons and its better to leave it up to the organizational team to decide what's better for that competition.

**Comment by lgarron** [comment]
I think that *forcing* a system onto organizers is not a good idea. It would send the signal that we don't trust them to handle it in a way that is appropriate for their community, and discourage innovation — things that are now common for major championships were once unusual and would probably not have been part of of a mandated system if we had frozen it in time earlier.

That said, de facto recommendations are good, especially help provide consistent experience for competitors. That's more of a WQAC topic, though.

**Comment by Goosly** [comment]
> Several objections to forcing the European judging systems:

What is the European judging system? Europe is large and I've seen everything being used in several countries. Just use a name everyone can understand please.

**Comment by Samuel-Baird** [comment]
If the system is causing issues then just talk with organizers to see if they will use the “normal” system, if it does slow you down then add extra buffer time in the schedule.

**Comment by LLayug** [comment]
From reading the replies, I do not necessarily see a need for requiring one single system. However, I do think that establishing a normal one would probably be better for the sake of uniformity. At this point, I honestly think that we should go and try to make a new judging system since I do see problems for the 2 most commonly used ones. (Renaming the thread by the way)

**Comment by xsrvmy** [comment]
There is actually a third system:
At some Chinese comps, all rounds are stationary, the judges run, and when a station becomes empty, the next competitor fills it.
This does create the problem that scramble groups are not well defined. The same competitor may get part of one set and part of another set.

**Comment by alexmaasswca** [comment]
I honestly think a general glossary of the judging systems would be nice, because of all of these silly names like "European" doesn't really work out.

**Comment by mirandapedro** [comment]
I agree with what has been said about the issues related to having a "standard" judging system that is highly recommended by the WCA.

Each cubing community has it's own culture, needs and advantadges. I don't think having the WCA "enforce" on judging system is necessary and sensitive to these differences.

To illustrate what I mean, I had never heard of the juding system @LLayug proposed be standard, for example. Here in Brazil we mainly used the fixed judge system, more closely related to the european system, where there judges aren't part of a fixed staff team.
