### ISSUE TITLE
Require number of cubes for all multi competitors before the beginning of the attempt

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#94]
Proposal by Javier Tirado [on the delegates list, November 13, 2013](https://groups.google.com/forum/#!topic/wca-delegates/OUyL7uwxbGo).

**Comment by sarahstrong314** [comment]
It would also be helpful toward the organizers if they had to declare the maximum number of cubes they'll attempt when they register. Not sure whether that's something that should be enforced in the regs, though.

**Comment by lgarron** [comment]
Some concerns:
1. Should this happen _per attempt_?
2. Even if all the numbers are reported before anyone hands their cubes in, competitors are still likely to be able to see how many cubes a competitor has. (If my only contender is attempting 5, I know I only need to solve, say, 7/8.)
3. How strict would this be? Organizers sometimes make special accommodations, especially for other organizers who had a legitimate reason to be busy.

**Comment by lgarron** [comment]
From my email to the Delegate list on Dec. 8:

> Javier's proposal conflates "round" with "attempt". A proposal should be clear and practical about what to do where in the past a competitor would have had multiple consecutive attempts.
> 
> Also, competitors who start their attempt after someone else can see how many cubes the first competitor is attempting (e.g. by just walking into the room for the attempt); this might allow them to decide that they don't need to solve all their cubes successfully. The proposal should either make it clear that this is okay, or clarify how to prevent it.

**Comment by lgarron** [comment]
Haven't seen a good proposal that addresses all the issues for this. Marking as `2014-wontfix` for now.

**Comment by lgarron** [comment]
TODO: Create a branch based on Natan's proposal.

**Comment by lgarron** [comment]
Also to consider: Does every competitor have a right to base the number on previous attempts? The currently discussed changes might encourage organizers to collect all the numbers earlier.
