### ISSUE TITLE
Reviewing the regulations regarding a legal timer stop, in light of video evidence incidents

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#940]
Here is the current A6d:

> A6d) The competitor must stop the timer using both hands, placed flat on the sensors with palms down. Penalty: time penalty (+2 seconds).

One point of controversy is the word "flat". What is flat enough? Can your fingers be flexing upwards to avoid touching the cube by accident? Can your hand be slightly rotated?

The more significant issue is that while A6d is a good description of the general motion of stopping the timer, in reality, applying it to the instant of a fast timer stop, under some interpretations, result in unfair conditions. If the table is high, it is more likely that the hand has not fully rotated when hitting the timer.

Another comment: should the three timer stop regulations (A6c,d,e) be merged into one for a single +2? Especially violating A6c usually leads to violating A6d as well, and sometimes it can be hard to tell if A6c and A6e are both violated.

**Comment by Ivan-Brigidano** [comment]
Some people said that the best way to handle this is with #798
