### ISSUE TITLE
Timestamps for NR/CR/WR

### ISSUE THREAD

**Issue by mintydev789** [thewca/wca-regulations#941]
I suggest that every time there is a record, the judge calls a delegate and they write down the time and their signature on the back of the scorecard. This would allow the inclusion of most records of the same type set on the same day (time zones should obviously be adjusted). I think there should be just one record of a given type per round (e.g. if 2 people get 3x3 avg NR in the same round, the better one becomes the record, if 3 people get a skewb single NR, only the best one becomes the record). If there are 2 records of the same type that were set within 5 minutes of each other, the faster one wins to give some margin of error. If a record did not have a time stamp or the time stamp was not confirmed by a delegate within 5 minutes or it was later proven to be inaccurate, the time is 23:59 in the time zone of the competition. I think with this system there would be very few issues with records set on the same day, this would be a positive addition and it would only make the organization process slightly different, cause a delegate would simply have to write the time on the back of the scorecard and a WCA team member would have to mark the records accordingly. In most cases when multiple records are set it is very obvious, which one was first. When a new event is added, a period of one month with the old one day = one record system may be used.

**Comment by xsrvmy** [comment]
I think using end of round is much better. Some times an NR may go unnoticed.

**Comment by Samuel-Baird** [comment]
There is a discussion for this at #212
