### ISSUE TITLE
Allowing cumulative time limits to include MBLD

### ISSUE THREAD

**Issue by ccbaird** [thewca/wca-regulations#942]
[A1a2](https://www.worldcubeassociation.org/regulations/#A1a2) as it stands is clear that MBLD cannot use a combined time limit with other events. With a couple of caveats that seems like a reasonable rule to consider relaxing:
1. The combined time limit must be at least 1 hour. 
2. All MBLD attempts must also comply with WCA time limits (e.g. a 2 hour cumulative limit does not allow a 2 hour MBLD attempt, a 1 hour time limit does not allow an hour for a 3 cube MBLD attempt)
3. All MBLD attempts by a competitor must be completed before any other attempts, OR there must be enough time left after other attempts that the WCA time limits for MBLD are not less restrictive than the cumulative time limit (e.g. if a competitor has used 19 minutes of a one hour cumulative time limit he has 41 minutes left, and may not attempt more than 4 cubes for MBLD. If he has used 21 minutes then he has 39 minutes left, and cannot attempt more than 3 cubes.)

In most cases this rule change would be inconsequential. For small competitions like the one I am currently planning it would allow flexibility to schedule more events without compromising the integrity of the competition. Personally I would very much like to make a 3 cube MBLD attempt, and then attempt either 4BLD or 5BLD. As it stands I can schedule 4BLD and 5BLD to share a time limit, and MBLD in the same time slot, but competitors have to choose between MBLD and the other two events.

**Comment by xsrvmy** [comment]
All this does is give more attempts to beginners (rather than good competitors) so it is against the purpose of a cumulative limit.
Also why on earth would you restrict attempt with 59 minutes left to only 5 cubes?

**Comment by ccbaird** [comment]
> All this does is give more attempts to beginners (rather than good competitors) so it is against the purpose of a cumulative limit.

I thought this was the purpose of a cumulative time limit?

> Also why on earth would you restrict attempt with 59 minutes left to only 5 cubes?

To avoid the issue of a competitor attempting 6 or more cubes not getting their allotted hour. The first option of requiring all MBLD attempts to be completed first may be a better way to address this.

**Comment by xsrvmy** [comment]
The purpose of a cumulative time limit is to allow more people to compete while only letting the better competitors get all the attempts, basically a cutoff for BLD. An MBLD cumulative does the opposite - it only lets beginners get all the attempts.

**Comment by ccbaird** [comment]
> The purpose of a cumulative time limit is to allow more people to compete while only letting the better competitors get all the attempts, basically a cutoff for BLD. An MBLD cumulative does the opposite - it only lets beginners get all the attempts.

I can see that argument, but that’s not the way I had envisioned it working. There would have to be at least an hour scheduled for every MBLD attempt (see my caveat 1 above). It might force competitors to choose between a “full” MBLD attempt and big blind (or whatever else is co-scheduled with MBLD) but that is no different than the current system where two events can be scheduled simultaneously and competitors have to choose one or the other.

**Comment by xsrvmy** [comment]
Still point 2 should not exist. No point logistically.

**Comment by ccbaird** [comment]
Point 2 is just to clarify that WCA limits (10 minutes per cube, up to 60 minutes) for MBLD take precedence over competition time limits.

**Comment by Samuel-Baird** [comment]
I’m not sure that I like the idea of encouraging competitors to not perform to the fullest of their ability for multi-blind so that they can compete in other events, or “punishing” competitors who take the full hour in mbld by giving them less time for other events than someone who may have only attempted 2 cubes for multi-blind

**Comment by ccbaird** [comment]
> I’m not sure that I like the idea of encouraging competitors to not perform to the fullest of their ability for multi-blind so that they can compete in other events, or “punishing” competitors who take the full hour in mbld by giving them less time for other events than someone who may have only attempted 2 cubes for multi-blind

It’s not a matter of punishing anybody, it’s a matter of allowing more opportunities for more people. And nobody would get more MBLD attempts than anybody else, if there are 3 MBLD attempts planned there has to be at least 3 hours allowed. This just allows people who make smaller MBLD attempts to attempt other events (probably usually big BLD) while people who do full hour MBLD finish, instead of having nothing to do and possibly distracting other competitors.

**Comment by Jambrose777** [comment]
> > I’m not sure that I like the idea of encouraging competitors to not perform to the fullest of their ability for multi-blind so that they can compete in other events, or “punishing” competitors who take the full hour in mbld by giving them less time for other events than someone who may have only attempted 2 cubes for multi-blind
> 
> It’s not a matter of punishing anybody, it’s a matter of allowing more opportunities for more people. And nobody would get more MBLD attempts than anybody else, if there are 3 MBLD attempts planned there has to be at least 3 hours allowed. This just allows people who make smaller MBLD attempts to attempt other events (probably usually big BLD) while people who do full hour MBLD finish, instead of having nothing to do and possibly distracting other competitors.

Which would restrict 9k even more than we already do...

**Comment by ccbaird** [comment]
> Which would restrict 9k even more than we already do...

Is it better to restrict that or to take events out of smaller competitions?

**Comment by Samuel-Baird** [comment]
> > Which would restrict 9k even more than we already do...
> 
> Is it better to restrict that or to take events out of smaller competitions?

You can just disallow competitors from competing in both events, this is already what your proposal would allow you to do to competitors who get close to using the full hour for mbld :P

**Comment by ccbaird** [comment]
> You can just disallow competitors from competing in both events, this is already what your proposal would allow you to do to competitors who get close to using the full hour for mbld :P

Yeah, that’s the system we have now. It’s not the worst system in the world, but why hold people back from doing more solves when we’ve got all the stuff in place to do it anyway, it just requires a minor rule change?
