### ISSUE TITLE
SEE Cooperation

### ISSUE THREAD

**Issue by danielA7575** [thewca/wca-regulations#943]
The transfer of 3x3x3 With Feet from WCA to SEE (Speedcubing Extra Events association) has been succesful, and there are already two WCA-SEE competitions with Feet scheduled in January.

[https://speedcubingextraevents.org/Event/333ft](https://speedcubingextraevents.org/Event/333ft)
[https://speedcubingextraevents.org/Competitions](https://speedcubingextraevents.org/Competitions)

I suggest we start thinking about transfer of similarly unpopular/problematic events like the following:

- Clock
- 5BLD
- 4BLD
- 7x7x7
- 6x6x6

I.e. the events may be transferred January 2021. The transfer will not have a big impact on the common competitor, as the events can still be held at WCA-SEE competitions with official rankings, but will not be required at major WCA championships, and may not be eligible for sponsor prize money.

SEE is an association that organizes Extra Events, with 93 official competitions so far. The transfer of unpopular WCA events will make popular non-WCA events more likely to be held. E.g. Kilominx, Team-Blind and Rescramble may be more popular than say 5BLD, in the interest of the common speedcuber.

Very popular events like Kilominx may be transferred from SEE to WCA eventually, as desired.

**Comment by jamesquinn1** [comment]
Ah yes, the casual removal of 5 events. Please tell me you're not serious.

On a more relevant note, cooperation between the two is a great idea.

**Comment by HippolyteM** [comment]
Please... :/
This is not cyoubx fucking friends. Please try not to shitpost here.
That's exhausting to read.
Don't dare asking the wrc for any seriousness when all you can do is just turning this place into a trashroom.

(I don't have anything against "see", it's great that people can have fun. But this had nothing to do here. This "transfering" thing is just absurd.)

**Comment by Ivan-Brigidano** [comment]
The idea behind SEE seems interesting. However, removing 5 events at once is just unreliable.
As this Repository is for official discussions about the official WCA Regulations and Guidelines, I'm closing it.

**Comment by ccbaird** [comment]
>removing 5 events at once is just unreliable.

The same can reasonably be said about removing any events at all.
