### ISSUE TITLE
Remove the 2Xw notation from 12a2 from FMC  

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#946]
Right now we have two different ways to write the same wide moves. In order to simplify things for graders by making proofreading easier and less confusing, I think we should make the 2Xw part of 12a2 not apply to FMC. The 2Xw moves are redundant and unnecessary like bracket rotations moves such like R2'. The 2Xw moves take up more space on paper, are rarely used, and can cause confusion, ex. U 2Rw2 can be misinterpreted as U2 Rw2 and vice versa, 2Uw may be interpreted as Uw2. Since the only place where Rxw notation is in competitors FMC solutions, it will not cause any issues to remove the notation from FMC

Edit: changing 1 < n < N to 2 < n < N in 12a2 would resolve this issue

**Comment by Goosly** [comment]
Removing 12a2 means removing **all** wide moves... which is probably not what you want

**Comment by xsrvmy** [comment]
Actually, easier:
The current rule is 2<=x<n. Just change it to 3<=x<n.

**Comment by UnderwaterCuber** [comment]
> Actually, easier:
> The current rule is 2<=x<n. Just change it to 3<=x<n.

We need 2Xw moves for big cubes still :P

**Comment by xsrvmy** [comment]
IIRC Rw is used instead of 2Rw in big cube scrambles.

**Comment by Samuel-Baird** [comment]
> Actually, easier:
> The current rule is 2<=x<n. Just change it to 3<=x<n.

> IIRC Rw is used instead of 2Rw in big cube scrambles.

I thought 2Rw was used in big cube scrambles, if they aren't used in them then it seems perfectly reasonable to 3<=x<n.

**Comment by GuidoDipietro** [comment]
Has any decision been taken on the matter?

**Comment by Samuel-Baird** [comment]
Another benefit of removing this notation, it leaves enough room on the fmc sheet for all legal moves :) picture credit to Alexandre Henrique Afonso Campos 

![8A009D9A-B8D1-4398-9518-21880F1A7734](https://user-images.githubusercontent.com/45566917/72579989-e9af0500-3897-11ea-9a17-8b7a93e61c5b.jpeg)
