### ISSUE TITLE
Explicitly state weather stickerless cubes without centre caps can be used.

### ISSUE THREAD

**Issue by aneurinhunt** [thewca/wca-regulations#949]
As 3d reads you could use a stickerless cube without any centre caps, provided that the plastic underneath is coloured.

**Comment by SAuroux** [comment]
3d2) The colors of the colored parts must be solid, with one uniform color per face. Each color must be clearly distinct from the other colors.

I don't see how a center without center cap could possibly fulfill this.

**Comment by xsrvmy** [comment]
The screw is not a colored part, just like how the black plastic of a stickered puzzle is not a colored part

**Comment by hanwu85** [comment]
Due to `3d)` and `3d2)`, a puzzle without any center caps is not competition legal.  I am going to close this issue.

Thank you for the post, you are welcome to file other issues if you have any ideas.
