### ISSUE TITLE
Move B4e into B4a1

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-regulations#954]
Regulation B4e states:
> B4e) Until the competitor applies the first move to the puzzle, they may remove the blindfold to return to the memorization phase.

And this is an exception of B4a, which states:
> B4a) The competitor dons the blindfold to start the blindfolded phase.

In my opinion, moving B4e into B4a1 would make Article B clearer and easier to understand.

**Comment by Samuel-Baird** [comment]
That's not an exception though?

**Comment by Ivan-Brigidano** [comment]
> That's not an exception though?

Oh that's true, I quoted the wrong regulation

**Comment by hanwu85** [comment]
I agree with this one.
I also think B4a1 or B4b1 are both acceptable.

**Comment by Samuel-Baird** [comment]
Yeah I think it would be good as a B4a1

**Comment by mirandapedro** [comment]
Having B4e under B4a, as proposed in the title of the issue, looks good to me.
