### ISSUE TITLE
Provisional extra issues

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#955]
Two issues regarding extra attempts:
1. What should happen if a provisional extra affects who advances to the next round, or whether or not an extra person can advance to the next round (in case of a DNF-related issue in 3bld)?
2. If there is a disputed incident where immediate resolution is not practical, can a competitor specify that he wants an extra only if the incident, specifically a penalty, is counted against him? Similarly can a competitor choose between a provisional extra vs a normal extra if the circumstance permits both (eg. judge accidentally moves competitor's blindfold with paper, in which case a normal extra can be argued for distraction, and a provisional extra can be argued for possible improper placement of blindfold)?

**Comment by xsrvmy** [comment]
An example of the first case in 2:
A new competitor get a PB single, but breaks A6e in a way that is disputable between DNF and +2. He would probably not want an extra if it is only a +2, but definitely would want one for DNF.

**Comment by Ivan-Brigidano** [comment]
Provisional extras are just extras that have been granted to bring the WRC more options to make a decision about an unclear incident. I don't think provisional extras should be limited because there are very different incidents and these provisional extras really help the WRC making decisions.

**Comment by xsrvmy** [comment]
For number 1 I'm asking about what happens to advancement conditions, not what happens to the extra.

**Comment by Goosly** [comment]
In such a case you let both competitors advance, and when the decision related to the provisional extra is made, the results of the subsequent round are adjusted/removed as needed.

**Comment by Ivan-Brigidano** [comment]
Usually the WRC follow [this](https://www.worldcubeassociation.org/incidents/48) procedure in advancement conditions related incidents. But there are very different incidents so it's impossible to define a general rule that covers every single case with no exemption.
