### ISSUE TITLE
Restrict FMC move to Face Moves, Rotations and Wide Moves. List them all in the FMC sheet.

### ISSUE THREAD

**Issue by campos20** [thewca/wca-regulations#956]
The ideia here is to only allow the following moves
R, U, F, D, L, B
R', U', F', D', L', B'
R2, U2, F2, D2, L2, B2

x, y, z
x', y', z'
x2, y2, z2

Rw, Uw, Fw, Dw, Lw, Bw
Rw', Uw', Fw', Dw', Lw', Bw'
Rw2, Uw2, Fw2, Dw2, Lw2, Bw2

This set of moves covers all the advanced techniques (slices for example) and the novice ones (like using CFOP)
We could remove the Article 12 mention, since we would list all the moves, making it more friendly. The FMC sheet would look like this.

![82308255_535682917037169_641845083854864384_n](https://user-images.githubusercontent.com/10170850/72687802-5fa5ad00-3ae0-11ea-82b5-7e1c73218eb0.png)

This is related to #946.

**Comment by c-goodyear** [comment]
Using something like [12a4](https://www.worldcubeassociation.org/regulations/#12a4) for the rotations would be a good addition to this. Otherwise they are not defined very well to less experienced competitors.
