### ISSUE TITLE
Allow for competitors to optionally use a self-supplied "surface" in MBLD.

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#959]
One issue with magnetic puzzles in MBLD is that they will often repel each other due to the magnets in the pieces. This issues is compounded by the fact that the magnetic push is incredibly weak, and whether the cubes push apart can depend on the friction of the table being used, thus, one competitor may practice with these puzzles at home and find no issues, then have to deal with the issue for the first time at a competition.

Allowing for the competitor to provide a self-supplied surface in MBLD would allow for them to ensure that attempts in competition will be similar to those practiced at home, regardless of the type of table used in competition. Some examples of objects that could be used as a surface include a large mat (like a rectangular gen2 stackmat) or a tablecloth for those doing larger attempts.

**Comment by mirandapedro** [comment]
Hi.

IMO, this is currently not disallowed by the Regulations. Competitors should be able to do this, unless a Delegate forbids for a particular (and very well founded) reason.

Has there been any report of a MBLD competitor trying to do this and not being allowed to?

**Comment by KitClement** [comment]
My main concern would be 2i1, if such an object that a competitor self-supplied would give them an unfair advantage over competitors that do not have the same access to this item. In the past, it's not been allowed in feet, for example, to provide your own surface to put underneath the stackmat, as this makes the environment inequitable for all competitors. There are other similar environment-related requests that a competitor may request such as placing a small object over the display on the timer to prevent the competitor from looking down at the timer. Obviously that example has other reasons to disallow it (judge needs to confirm when/if timer is running), but generally I've seen that most rulings pertaining to the competition environment are done to ensure that competitors are competing under equal conditions.

**Comment by Ivan-Brigidano** [comment]
This is the first time I heard about this issue. It's really that harmful for MBLD competitors?
Do you have a specific idea on how to include this in the Regulations?

**Comment by KitClement** [comment]
I know there are many competitors that have stopped using magnetic cubes in
MBLD solely because of this issue. Mark sold me some magnetic GTS2s at a
cheap price as he had to unload about 50 of them after learning that they
would repel each other on certain competition tables.
