### ISSUE TITLE
Holy See should be called Vatican City in list of states

### ISSUE THREAD

**Issue by Mollerz** [thewca/wca-regulations#962]
Vatican City is actually the name of the country. Holy See is the jurisdiction of the Bishop of Rome (the pope), kind of like a company or something. It is known as Holy See within places like the UN, Council of Europe, etc. However this operates from and exercises "exclusive dominion" over the independent Vatican City State enclave.

So yeah that's an easy change I think

**Comment by hanwu85** [comment]
Thank you for spotting this!
