### ISSUE TITLE
Update how 2e2 works 

### ISSUE THREAD

**Issue by maconard** [thewca/wca-regulations#963]
Hello! Currently, regulation point 2e2 (regarding changing the country you represent) only allows you to change your representation at your first competition of the calendar year (in the case of dual citizenship). It seems clear the reason for this is to limit competitors to doing so once per year, but this has the unintended side effect of potentially making a competitor wait a full year unnecessarily (say they moved countries and obtained a dual citizenship on competition number 2 of the year). Note: we already allow swapping at any point in the year in the case of *losing* citizenship for the country you represent.

I would like to propose that we instead allow a country of representation change at any point in the year for new citizenship as well, and instead record a time stamp of the change and allow people to do this only once every full year (i.e. 365 days of real time, not competing in a fresh calendar year). 

This maintains the same frequency limiting effect while removing the side effect of delaying a first time change or mid-year change unnecessarily.

Current phrasing:
> Competitors with updates to their citizenship status may change their country of representation before or at their first competition of a calendar year. Exception: if the competitor loses citizenship of the country which they were previously representing, they must change the country of representation before or at their next competition (see Regulation 2c2).

Proposed phrasing:
> Competitors with updates to their citizenship status may change their country of representation at any time, as long as at least one full year has passed since the day of their last change. Exception: if the competitor loses citizenship of the country which they were previously representing, they must change the country of representation before or at their next competition regardless of any prior changes within one year (see Regulation 2c2).

https://www.worldcubeassociation.org/regulations/#2e2

Cheers!

**Comment by alexmaasswca** [comment]
I think this would be an okay change, I don't see any issue with this or any issues with how it is now (except for maybe WRT workload timing). Not sure if delegates or the WRT handles that. 

I think it would actually be sort of an achievement to lose citizenship. What happens if the person can't find another country to be a citizen of? Are they stateless? How would the WCA even know that they lost citizenship? Would they be banned since a requirement to compete is representing a country?

I think the losing citizenship part is silly, and if it somehow happens, then the competitor should just keep the citizenship of the country they lost it from. I just don't see why it has to be mentioned.

**Comment by maconard** [comment]
> Not sure if delegates or the WRT handles that.

See regulation 2c2.

> How would the WCA even know that they lost citizenship?

They wouldn't, until you tell them. Ethically it is the correct thing to do, particularly if you're capable of breaking national records under your previous citizenship. 

> Would they be banned since a requirement to compete is representing a country?

See regulation 2e: paraphrasing, the country you represent *must* be one you have citizenship in, not that you *must* have such a country. You can get banned if you tried to or got away with representing a country you don't have citizenship in (like trying to farm Jamaica NRs), further explained in 2e. Also see regulation 2e3 about statelessness.

> I think the losing citizenship part is silly

Happens somewhat frequently when someone obtains citizenship and the two countries do not allow dual citizenship. You must lose the old one to obtain the new one. A more relevant example, maybe, is in the US if you run for a government position in a foreign country or enlist in a foreign military you can automatically lose your US citizenship. So I think it's safe to say citizenship loss is a possibility, even if somewhat rare. The regulations are made more robust by including that bit.

**Comment by EdHollingdale** [comment]
This has already been discussed in #752 . I also agree that forcing people to wait until the end of the year is really stupid. (see [here](https://github.com/thewca/wca-regulations/issues/752#issuecomment-551342684) and [here](https://github.com/thewca/wca-regulations/issues/752#issuecomment-551999981)), and particuarly challenging to implement now given the pace of competitions. Hopefully this can be fixed in the mid-year regulations update (if it occurs).

**Comment by maconard** [comment]
Oh thanks for linking those! I had tried searching for 2e and such on here but kept returning no results. I should have searched "citizenship" as a keyword.

I will close this issue as #752 lives on.

**Comment by Jambrose777** [comment]
Even though this is closed, one counter-point is that this allows a competitor to qualify for multiple championship titles in the same year. So someone could be both the North American Champion and the European Champion, and could do so every year if they had intel on which would happen first.

**Comment by xsrvmy** [comment]
@Jambrose777 It is technically already possible for this to happen through a mandatory citizenship change.

**Comment by maconard** [comment]
@Jambrose777 I suppose it would fall on the results team to not allow that. If someone won a title at such a competition very recently, using discretion to delay their optional representation change (under dual citizenship).

But that is an interesting counter point I hadn't thought of. Thanks for bringing it up here!

**Comment by Jambrose777** [comment]
> @Jambrose777 I suppose it would fall on the results team to not allow that. If someone won a title at such a competition very recently, using discretion to delay their optional representation change (under dual citizenship).
> 
> But that is an interesting counter point I hadn't thought of. Thanks for bringing it up here!

So we should treat people differently based on their speed and accomplishments? I don’t buy it.

**Comment by maconard** [comment]
> So we should treat people differently based on their speed and accomplishments? I don’t buy it.

I see what you mean, but if someone is gaming the citizenship system to spam winning titles, that's something *only* possible by a fast person. I'd say it may be a suspendable offense to intentionally game the system like that (we'd have to decide that of course). Based on that, I don't think it really counts as treating people differently based on speed since it's just impossible for slow people to commit this offense. 

You'd be treating everyone the same because the standard would be "if you're spamming winning titles by changing country of representation you'll get suspended (or X punishment)" it just so happens that slow cubers most likely can't do that.
