### ISSUE TITLE
11e timeframe issues

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#965]
Two problems with the current timeframe requirement in 11e:
- It is not always possible to tell that an incident has occurred during the attempt. For example, at a recent competition in Ontario, a timer started telesensing, and was only discovered after several attempts (including at least one DNF).
- How does 11e and A7g interact? If a new competitor signs, and then someone tries to call a delegate, does 11e overrule A7g (must over should), or is signing before calling the delegate in itself an incident and covered by A7g?

**Comment by hanwu85** [comment]
IMO, I think A7g does overrule 11e in someway.  
The inexperience of a competitor result in signing before appealing, if you think it this way, an extra attempt can still be granted.

**Comment by hanwu85** [comment]
Closing this issue now, if you have further questions, you are welcome to reopen this one.
