### ISSUE TITLE
A7g wording is problematic

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#966]
This issue is unrelated to the other issues regarding when to apply A7g.

> A7g) At the discretion of the WCA Delegate, an incident or penalty caused by a new competitor's inexperience may be replaced with an extra attempt.

An extra attempt cannot replace an incident or penalty.

The difference here actually makes it hard to tell how 11e and A7g interact. See #965

**Comment by hanwu85** [comment]
> An extra attempt cannot replace an incident or penalty.

Sorry, I do not understand the statement of this.
After an extra is granted, the extra attempt will be officially recorded instead of the old one(incident or penalty one)

**Comment by hanwu85** [comment]
Closing this issue now, if you have further questions, you are welcome to reopen this one.

**Comment by xsrvmy** [comment]
Didn't see the reply. The problem is in the wording (which grammatically suggests an attempt replaces an incident) not in the meaning of reg itself. A better wording would be something like "may be *resolved* by granting an extra attempt."
