### ISSUE TITLE
Recognize 'Seasonal Records' officially

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/wca-regulations#972]
There was a discussion in WCA Forum - https://forum.worldcubeassociation.org/t/wr-history/183.

In the forum, many people have been mentioning that we will reach a stage where the WR cannot be broken further and many people are losing motivation. Somebody commented that yearly records or seasonal records will be a good idea and I really liked that idea hence I posted the same in Slack and now I'm posting it here for public discussion. Along with WR, CR, NR, can we also officially recognize something like YWR, YCR, YNR and corresponding ranking so that people can target something like 'top 100 of 2020 YNR in squan'? Will such an implementation motivate a lot of cubers?

**Comment by Ivan-Brigidano** [comment]
Hi @danieljames-dj, as I have just posted, we are moving the community feedback to WCA Forum. Would you mind to post there?

**Comment by danieljames-dj** [comment]
Hi @Ivan-Brigidano , the discussion for this was actually initiated in the WCA Forum (https://forum.worldcubeassociation.org/t/wr-history/183).
